### PR TITLE
Add tox-uv to test environment for speedup installation, fix codecov upload

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR adds tox-uv plugin to test env for speedup test environment creation. 

For Initial test (3.9, ubuntu-latest, pyqt5, _pydantic_1, no_cov) / ubuntu-latest py 3.9 pyqt5 no_cov it reduced setup time from 55s to 10s 

For macos-latest / macos-latest py 3.12 pyqt5 no_cov it reduces time from 55s to 9s

It also fixes codecov upload by pin codecov cli to 0.6.0. It may need to be reverted once the bug in codecov cli is fixed.

### CODE REVIEW

**Comment by Czaki** [comment]
It looks like upload is failing because of codecov bug https://github.com/codecov/codecov-action/issues/1487

**Review by brisvag — APPROVED** [review]
Nice, yet another little reduction to CI time :)

**Comment by Czaki** [comment]
should I keep codecov fix in this PR or open a separate one?

**Comment by brisvag** [comment]
I think it's fine here, just add it to the description/title.

**Comment by Czaki** [comment]
could you check description now?

**Review by brisvag — APPROVED** [review]
Yup, good to go!

**Pull request merged**
