### PR TITLE
World Coordinates

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR begins to add support for world coordinates, as described in #763 and other places.

It adds two properties to a layer `_data_range` and `_world_range` (both of which can be renamed), which provide the range of the layer in data coordinates and world coordinates respectively and leverages to `layer._transforms` to do this conversion.

The big question now is how these properties should interact with or live on the dims model? 

Basically now we're in a somewhat awkward position where some of the necessary info lives on the layer, then some lives on the layer dims model. We also have the dims model that lives on the viewer. The likely resolution of some of that strangeness might come with the layer groups in #1089, where we could just have a dims model for each layer/ layer group and clear ways to composite across them, but for now we'll need to decide where these properties should go.

One approach would be to put everything on the dims model, including the transforms. The other could be to try and move away from having the dims model on each layer all together. Alternatively we could really try and separate concerns between them.

I'll be working on this more tomorrow, but any early input from @jni or @tlambert03 would be welcome.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by d-v-b** [comment]
Great to see this moving forward! A couple of comments:

* I'm not sure what "data coordinates" are -- for image data, are these array indices? If so, since the size of the data array is already represented by it's shape property, I'm not sure what the utility is of representing the same thing twice.  Can you elaborate on this?

* Separation of concerns: I think it makes sense to define the mapping between the data and some coordinate space via a single object. Neuroglancer uses this pattern to construct a layer (very analogous to a layer in napari): neuroglancer [constructs a layer](https://github.com/google/neuroglancer/blob/master/python/examples/example.py#L42) with data (an array), and a [`CoordinateSpace`](https://github.com/google/neuroglancer/blob/3c574d2dc6e9ffedd3565cf138c3029f63c17de6/python/neuroglancer/viewer_state.py#L147) object, which fully describes how the the data is embedded into world coordinates. Similarly, an [xarray.DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html) is constructed with data (an array) and a `coords` object, which assigns a point to every array index in data, thereby mapping array indices to positions in some space.

Like you suggest, the natural locus for "object that maps array indices to positions in space" in napari is the `dims` object. But I think currently `dims` is trying to do two things at once -- it tries to account for properties of the data (the number of dimensions, the number of samples along each axis) while also tracking properties of the current rendering of the data (the current slice, the display mode, the axis display order) Via this second set of properties, `dims` is basically doing the work of a geometric sampling plane. It might be necessary to factor out these two distinct functions into separate objects. 

I'm interested to hear what other people think! This is exciting!

**Comment by jni** [comment]
I like all your suggestions @d-v-b!

**Comment by sofroniewn** [comment]
> I'm not sure what "data coordinates" are -- for image data, are these array indices? If so, since the size of the data array is already represented by it's shape property, I'm not sure what the utility is of representing the same thing twice. Can you elaborate on this?

For image data that is the mostly case, though if the data is `rgb` then it doesn't include the final dim, and if the data is multiscale then it just takes the highest resolution. Right now we need a concept like to achieve standardization with the other layers like points and shapes. In the case of points and shapes though one could argue that there should be no scale and translate properties on the layer and that data should already come in "world" coordinates. I'm open to revisiting this @jni

> But I think currently dims is trying to do two things at once -- it tries to account for properties of the data (the number of dimensions, the number of samples along each axis) while also tracking properties of the current rendering of the data (the current slice, the display mode, the axis display order) Via this second set of properties, dims is basically doing the work of a geometric sampling plane. It might be necessary to factor out these two distinct functions into separate objects.

Indeed well put - this is the source of a lot of the awkwardness right now. Right if there are three things - data, spatial information, and slicing, then we sort of awkwardly mix these things all together, but it is probably cleanest if data + spatial information live nicely together and then slicing can do its own thing on this object.

Note that @pwinston is thinking about some big improvements in #845 that could result in a new tile fetching system, but my sense @jni @royerloic is that we'd want that to live more on the "view" side of things rather than the "model" side of things, right? Maybe riffing off of some discussion in #1272 a good question to start asking ourselves is what would we like a plugin developer to have access to? Certainly they need the data + spatial information, but they might not need the slicing (or at least slicing could be exposed in a more advanced interface).

>  I think it makes sense to define the mapping between the data and some coordinate space via a single object. Neuroglancer uses this pattern to construct a layer (very analogous to a layer in napari): neuroglancer constructs a layer with data (an array), and a CoordinateSpace object, which fully describes how the the data is embedded into world coordinates. Similarly, an xarray.DataArray is constructed with data (an array) and a coords object, which assigns a point to every array index in data, thereby mapping array indices to positions in some space.

@jni do we want to bite the bullet, depend on xarray, and construct an xarray representation of data with coordinates internally? I'd imagine our public API remains unchanged - we still accept bare numpy arrays, translation, scale parameters, but then we construct an xarray internally where we have all these things nicely. We could either just put that xarray privately somewhere like `._coordinate_array` and `.data` returns whatever they gave us, or just make it so that `.data` always returns an xarray regardless of what was passed? If people pass us xarray's that conform to our pattern we just use it directly, if they pass us xarray's that have a different structure, i guess we'll need to adapt it to our own xarray conventions? As long as we don't copy data, force instantiation or clober peoples own metadata this could all be ok, but it might get a little crazy, thinking about zarr, dask etc too.

On option would be to always convert what is given to being an xarray, keep track of if an xarray was not given, then if an xarray was not given pull the array out of the xarray for the `.data` property, otherwise give the `xarray` back. In this model you'd have numpy in numpy out, xarray in xarray out, always xarray on the inside and only one thing on the inside.

Is this how you were thinking about it @d-v-b?

**Comment by sofroniewn** [comment]
Following discussion with @jni i'm going to press on with what will hopefully be a fairly minimal feature addition, but more refactoring and improvements to this will hopefully becoming soon.

**Comment by sofroniewn** [comment]
Progress with the minimal approach is coming along well, the coordinate transform inverse going back from world to data is now in place on the base layer.

I still have some stuff to do on the Qt slider side to get all the float stuff working, and we'll have to make some choices about what labels to appear next to the sliders, (i.e. right now you see the current slider position followed by the max slider position)

Screen Shot 2020-05-25 at 10 14 20 PM

Once these sliders are in a "world coordinates" I guess one might be interested in the minimum value, the maximum value, the step size, and the current value? Need to think about this more, and open to suggestions from all

**Comment by tlambert03** [comment]
fwiw, I was definitely hoping that a move to world coordinates would _not_ have to change those labels there.  When I think about indexing a dataset (as we do with those sliders), I definitely think in terms of plane number pixel number, and I want the program to convert that to world coordinates/scales for me behind the scenes.  (I'd also like to be able to see distances/lengths _somewhere_ in world units, of course, but not on the sliders)

**Comment by d-v-b** [comment]
I think eventually the sliders should show *both* array indices and world coordinates. As soon as you have data at multiple resolutions, you can't think exclusively in terms of plane number / pixel number any more. This was actually why I started using xarray in the first place: I had raw EM data at 4nm resolution, and ground-truth data that had been upscaled to 2nm resolution AND padded. Compared to manually tracking the offset + scaling conversion, it was much much easier to just assign coordinates to these datasets, make xarray.DataArrays, and query the data with arguments defined in the common coordinate system (nanometers). xarray took me from doing error-prone index arithmetic to `data.sel({'x': x_range_in_nm, 'y': y_range_in_nm, 'z' : z_range_in_nm})`, which is a completely uniform interface for both datasets.

> I definitely think in terms of plane number pixel number, and I want the program to convert that to world coordinates/scales for me behind the scenes.

I actually think the opposite -- I'd prefer that napari assume that all images are defined over some kind of space, and internally dispatch to different sampling methods depending on the source of the data (array indexing for arrays, something else for vectors, etc). Plane number / pixel number (i.e., array indices) is an implementation detail of data acquired in a certain way (gridded sampling) and represented internally as an array, but outside of light microscopy these images are actually a special case: e.g., array indices don't make a lot of sense for vector data, or data sampled with a spiral pattern.

> On option would be to always convert what is given to being an xarray, keep track of if an xarray was not given, then if an xarray was not given pull the array out of the xarray for the .data property, otherwise give the xarray back. In this model you'd have numpy in numpy out, xarray in xarray out, always xarray on the inside and only one thing on the inside.

Yeah this is roughly what I was thinking. The user does not need to know anything about xarray, and they can always get their data out the way they put it in, but xarray is used internally to track coordinates. An alternative approach would be to implement an xarray-compatible interface / protocol without having xarray as a dependency, but I'm not sure what would keep the APIs from drifting apart.

**Comment by tlambert03** [comment]
> I think eventually the sliders should show both array indices and world coordinates

fine with me, as long as image indices are clearly available somewhere

**Comment by sofroniewn** [comment]
@d-v-b @tlambert03 thanks both for weighing in. Sounds like people will want to see both representations, and to move back and forth between them, fairly easily. Will keep you posted!

**Comment by d-v-b** [comment]
I have a really basic API question -- what is the difference between the `dims` attribute of a layer vs the `dims` attribute of the viewer?

**Comment by sofroniewn** [comment]
> I have a really basic API question -- what is the difference between the dims attribute of a layer vs the dims attribute of the viewer?

The dims on the viewer has the full nD representation of all the layers and is linked to the sliders on the screen. The dims on the layers have the same dim as the layer itself and are then used for the slicing. 

There has been some discussion about removing `dims` from a layer (or at least making it private). This PR experimentally puts a dims on the layerlist rather than the viewer, but we'll see if that's a step in the right direction.

The alternative after #1040 is done is that we can maybe move the slicing logic off the layer itself and then drop the additional dims representations.

**Comment by Czaki** [comment]
It will be nice if this PR fix exception on change spacing of layer like:

```
IndexError: index 44 is out of bounds for axis 1 with size 44
  File "D:\a\1\s\package\PartSeg\common_gui\napari_image_view.py", line 239, in update_spacing_info
  File "site-packages\napari\layers\base\base.py", line 336, in scale
  File "site-packages\napari\layers\base\base.py", line 403, in _update_dims
  File "site-packages\napari\layers\base\base.py", line 633, in refresh
  File "site-packages\napari\layers\base\base.py", line 586, in set_view_slice
  File "site-packages\napari\layers\image\image.py", line 527, in _set_view_slice
```

**Comment by sofroniewn** [comment]
Superseded by #1539

**Pull request closed without merging**
