### PR TITLE
Added popup to manually order the viewer axes.

### LINKED ISSUE #2468: Better chunk and/or memory awareness when rolling dims
## 🚀 Feature
@AbigailMcGovern and I have run into the issue that we have bigger-than-RAM 3D+t data chunked into timepoints. During manual annotation we want to roll the dims to be able to look at XZ or YZ planes, but the UI does not allow one to ignore t when rolling.

This is more general, e.g. 3D data where individual planes are usable but the full dataset is larger than RAM.

There's a few, not-mutually exclusive routes that napari could take here:

- understand chunks and chunked loading, and prevent views (rolling or 2D/3D) that would result in larger-than-RAM loads.
- allow users to define axes that shouldn't be rolled
- have a "rolling" widget where one can drag and drop axes to reorder them
- something else?

### PR DESCRIPTION
**Pull request by JoOkuma**
# Description

This PR adds a popup to manually order the viewer axes, this is necessary because in some applications rolling the axes crashes napari because it tries to load the whole dataset into memory (#2468).

This was copied from @jni plugin [zarpaint](https://github.com/jni/zarpaint/blob/main/zarpaint/_dims_chooser.py)
See gif below.

manual-sort

## Type of change
- [X] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# References

It was copied from @jni plugin [zarpaint](https://github.com/jni/zarpaint/blob/main/zarpaint/_dims_chooser.py)
I think this could close #2468.

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by JoOkuma** [comment]
There are three issues that I still need to fix:
- The axis names are reversed.
- The font styling is different, I don't know how to match the other popup.
- Write tests.

**Comment by sofroniewn** [comment]
Overall I like it, i think this will be useful to have in. It might be good to work with @isabela-pf on a design for the popup so that we can get a style we like. Right now it seems very wide - maybe that's to accommodate the names of the variables. @ppwadhwa might also be able to help review this PR and advise on how to add tests etc as she's worked on some other similar dialogs

**Review by ppwadhwa — COMMENTED** [review]
I think it looks pretty good.  I tested it and it works well for me.  I agree that its a bit wide, but maybe @isabela-pf will have more comments on a nice look for the widget.
@JoOkuma when you say that the font styling did not match the other popup, which popup are you referring to?  I think it looks very similar to the grid mode popup and the playbutton popup, but I didn't check others.  The only thing I could see that looks different is the label is bold. Is that what you mean?  Just wanting to see if I can help figure out how to fix that.

Also, I, apparently, did not write tests for the other popups that I worked on.  :(  I need to fix that.  These tests look helpful: https://github.com/napari/napari/blob/main/napari/_qt/widgets/_tests/test_qt_range_slider_popup.py

**Comment by JoOkuma** [comment]
Hi, I reduced its size and added some tests. However, I couldn't figure out where napari sets the style and size of the font.

image

I also added the widget to the `tools/string_list.py` file, what's this for?

**Comment by sofroniewn** [comment]
> Hi, I reduced its size and added some tests. However, I couldn't figure out where napari sets the style and size of the font.

Amazing! Not sure if you saw the following question from @ppwadhwa 

> The only thing I could see that looks different is the label is bold. Is that what you mean? Just wanting to see if I can help figure out how to fix that.

That might help figure out what you need to know about font size/ styling

> I also added the widget to the tools/string_list.py file, what's this for?

We use that for translations I believe. We can check in review if that's done right. thanks for flag

**Comment by JoOkuma** [comment]
The other popups have smaller and gray font, I don't think it's bold. 

image

**Comment by sofroniewn** [comment]
We're currently getting a fail on our minreq tests here with the oldest version of numpy we support

```python-traceback
  ________________ ERROR collecting napari/_qt/_tests/test_app.py ________________
  ImportError while importing test module '/home/runner/work/napari/napari/napari/_qt/_tests/test_app.py'.
  Hint: make sure your test modules/packages have valid Python names.
  Traceback:
  /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/importlib/__init__.py:127: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  napari/_qt/__init__.py:58: in <module>
      from .qt_main_window import Window
  napari/_qt/qt_main_window.py:49: in <module>
      from .qt_viewer import QtViewer
  napari/_qt/qt_viewer.py:46: in <module>
      from .widgets.qt_viewer_buttons import QtLayerButtons, QtViewerButtons
  napari/_qt/widgets/qt_viewer_buttons.py:20: in <module>
      from .qt_dims_sorter import QtDimsSorter
  napari/_qt/widgets/qt_dims_sorter.py:4: in <module>
      from numpy.typing import ArrayLike
  E   ModuleNotFoundError: No module named 'numpy.typing'
```

can this get fixed before merge. thanks!!

**Comment by JoOkuma** [comment]
Fixed. Thanks!

**Review by tlambert03 — APPROVED** [review]
this is really awesome functionality @JoOkuma!  code looks good too.  I'm approving, (with a minor nit if you have time):

on my mac at least, the height management could use some work: each individual object is rather tall compared to the height of the popup, so as soon as you have more than 2 dimensions (probably the norm for someone using this popup), it gets a bit hard to drag/drop since you also have to scroll... 
Untitled
 
I see that you have `view.setSizeAdjustPolicy(QtListView.AdjustToContents)` there... not sure if that was an attempt to fix this.  does it look like this on your screen?

**Comment by JoOkuma** [comment]
In Linux is like that as well. This is a  [bug](https://bugreports.qt.io/browse/QTBUG-58749) with `AdjustToContets` and `QListView`, it's fixed in Qt 6.

And without `AdjustToContents`, there is a big empty space below the list.

**Comment by jni** [comment]
> And without AdjustToContents, there is a big empty space below the list.

Honestly, I think this is preferable. Tiny unnecessary scrollbars drive me up the wall. True story: one of the original reasons napari is not browser based is the prevalence of annoying "scroll area within a scroll area" of browser based tools (e.g. Jupyter notebook output cells). I really really hate them.

**Comment by sofroniewn** [comment]
I will merge now, we can iterate on design in a followup if we want. thanks all!!

**Pull request merged**
