### PR TITLE
Ensure pandas Series is initialized with a list as data

### LINKED ISSUE #6225: property in labels layer does not understand objects of different lengths
## 🐛 Bug

I am trying to use the properties attribute of `add_labels` to add a dictionary of properties that contains a self defined property that happens to be in the form of list but of unequal lengths. So every region has an extra property of different length. Similar to how image is a property that has different lengths for every region.

This is a silly example of what I have:

## To Reproduce

```python
import numpy as np
from skimage.measure import regionprops_table, label
import napari

def random_length_property(regionmask):
      return [0] * np.random.randint(10)

image = data.coins()
viewer = napari.view_image(image)

label_image = label(image > 110)
table_props = regionprops_table(
      label_image,
      intensity_image=image,
      extra_properties=(random_length_property,),
  )

label_layer = viewer.add_labels(
      label_image, name="segmentation", properties=table_props
  )

napari.run()
```

And this makes napari unhappy with:

```bash 
 label_layer = viewer.add_labels(
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\napari\components\viewer_model.py", line 4, in add_labels
    import itertools
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\napari\layers\labels\labels.py", line 328, in __init__
    self._feature_table = _FeatureTable.from_layer(
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\napari\layers\utils\layer_utils.py", line 956, in from_layer
    return cls(features, defaults=feature_defaults, num_data=num_data)
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\napari\layers\utils\layer_utils.py", line 788, in __init__
    self._defaults = _validate_feature_defaults(defaults, self._values)
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\napari\layers\utils\layer_utils.py", line 1015, in _validate_feature_defaults
    defaults = {c: _get_default_column(values[c]) for c in values.columns}
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\napari\layers\utils\layer_utils.py", line 1015, in <dictcomp>
    defaults = {c: _get_default_column(values[c]) for c in values.columns}
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\napari\layers\utils\layer_utils.py", line 975, in _get_default_column
    return pd.Series(data=value, dtype=column.dtype, index=range(1))
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\pandas\core\series.py", line 500, in __init__
    com.require_length_match(data, index)
  File "C:\Users\elena.pascal\AppData\Local\pypoetry\Cache\virtualenvs\image-process-zoTHhXWu-py3.8\lib\site-packages\pandas\core\common.py", line 576, in require_length_match
    raise ValueError(
ValueError: Length of values (8) does not match length of index (1)
```

## Environment

napari: 0.4.17rc4.dev505+g7c9ea89d
Platform: Windows-10-10.0.19045-SP0
Python: 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.24.4
SciPy: 1.9.1
Dask: 2023.5.0
VisPy: 0.13.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.2

OpenGL:
- GL version: 4.6.0 - Build 31.0.101.3959
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 2560x1440, scale 1.0

Settings path:
- C:\Users\elena.pascal\AppData\Local\napari\illumion_033691400d65ecf164fea402e77f284e6b482050\settings.yaml

 - Any other relevant information:

## Additional context

@jni answered here: https://forum.image.sc/t/struggle-to-add-property-of-unequal-length-to-labels-layer/86201?u=elena_pascal

### PR DESCRIPTION
**Pull request by elena-pascal**
# References and relevant issues

Closes #6225 
# Description

Pandas is now given an explicit list which means properties of unequal lengths are understood correctly. 

# Final Checklist
- [x] My PR is the minimum possible work for the desired functionality

- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by melonora** [comment]
Hi @elena-pascal, 
Good to see you here! Thank you for your contribution:) I enabled the tests and am currently checking the PR. If / when approved we will put a ready to merge label giving other devs a 24 hour time period to check before merging.

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
To me it looks good! I think it was a good idea to modify the test! 😊🙏

**Comment by andy-sweet** [comment]
Great catch. And thanks for the fix!

**Comment by melonora** [comment]
I think this makes it almost exactly 24h. In it goes, thanks!

**Pull request merged**
