### PR TITLE
Update viewer tutorial

### LINKED ISSUE #4472: Alt-text missing for "Dimension slider" example
## 📚 Documentation

In the [Dimension sliders section](https://napari.org/tutorials/fundamentals/viewer.html#dimension-sliders) of the viewer tutorial, the alt-text argument of `nbscreenshot` is empty, which is causing a parse error.

Alt-text should be added there - see https://napari.org/tutorials/fundamentals/viewer.html#layer-controls for an example.

### PR DESCRIPTION
**Pull request by cnstt**
# Description
Update viewer tutorial: just added an alt text. This PR resolves #4472 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by cnstt** [comment]
Any maintainer willing to approve running workflows? ping @melissawm

**Review by melissawm — APPROVED** [review]
Looks goot to me, thanks @cnstt !

**Comment by cnstt** [comment]
I don't know why, but the 'Test typing' is failing... This does not seem to have to do with my PR though.
EDIT: I just saw https://github.com/napari/napari/issues/4470 so this is not related to my changes :)

**Review by sofroniewn — APPROVED** [review]
Thanks so much - very helpful!

**Pull request merged**
