### PR TITLE
Fix crash on python -m napari

### LINKED ISSUE #6483: #6188 introduce crash of python -m napari.
#6188crash fresh start of napari (`python -m napari`).

_Originally posted by @Czaki in https://github.com/napari/napari/issues/6188#issuecomment-1822327152_

### PR DESCRIPTION
**Pull request by Carreau**
Closes #6483

### CODE REVIEW

**Comment by Carreau** [comment]
I need to find the proper way to test it

**Comment by Carreau** [comment]
Test added.

**Review by Czaki — APPROVED** [review]

**Comment by Carreau** [comment]
(i'm not a fan of stack being able to be a bool or a list...)

**Review by brisvag — APPROVED** [review]
> (i'm not a fan of stack being able to be a bool or a list...)

Yeah, that's annoying :/

Anyway, we should get this in as soon as test are green.

**Comment by psobolewskiPhD** [comment]
I can confirm this fixes my issue from https://github.com/napari/napari/pull/6479#issuecomment-1821900874

**Comment by brisvag** [comment]
Merging to fix main asap.

**Comment by jni** [comment]
Thanks for the quick fix @Carreau!

Can someone explain to me though why that code is run at all when running `python -m napari`, though? 🤔

**Comment by Carreau** [comment]
You can pass files/plugin to open when starting napari from the CLI and/or activate deactivate plugins. It's the same code that create the default empty viewer than the one the create a viewer and add files/layers.

**Pull request merged**
