### PR TITLE
[easy] fixes bash codeblock in README.md

### PR DESCRIPTION
**Pull request by neuromusic**
# Description

adds `$` to codeblock in README.md for consistency

### CODE REVIEW

**Review by kevinyamauchi — APPROVED** [review]
Looks good to me! Thanks, @neuromusic !

**Comment by AhmetCanSolak** [comment]
this is not a bash specific command indeed. Should be working with other shells too. It is a minor thing but wanted to point out.

**Comment by neuromusic** [comment]
fixes ~bash~ shell codeblock :D

**Comment by AhmetCanSolak** [comment]
:D i pointed out since `$` is not universal across various shells.

**Pull request merged**
