### PR TITLE
Unify layer creation API

### PR DESCRIPTION
**Pull request by kne42**
# Description
- unify signature/functionality of `gui.imshow` and `viewer.add_image`
- remove `viewer.imshow`
- add `gui.scatter` convenience method for creating a markers layer
- make corresponding changes to the example notebooks
- bugfix `add_to_viewer` decorator

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How has this been tested?
- ran updated `markers.ipynb`
- ran update `layers.ipynb`

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Something I noticed when using the scatter method is that the shape of the layer gets set to be [x, y] when the markers are plotted [y, x] not something that is the responsibility of this PR, but something to fix when we redo the dimensions stuff

**Review by sofroniewn — APPROVED** [review]
Changes look good. I think there are still a couple things we want to change about the add_image API, like adding specific keywords like `clims='auto'` and `colormap='magenta'` etc. but that can come in a follow up PR.

**Review by jni — CHANGES_REQUESTED** [review]
Hmm, I don't think I caught this at the time imshow was introduced, but I very much would like to avoid cloning the state machine part of the mpl API. They have spent close to a decade deprecating it for a reason. Instead, calls like imshow and scatter should take an optional `viewer=` argument, and either add a layer to that viewer, or create a new viewer if one is not given. It should *never* attempt to find the "active" viewer. (This is also super-terrible in Fiji.) The proposed behaviour mirrors that of e.g. seaborn.

ie my suggestion is that we remove `global _app`. My (very effective) computing fundamentals teacher trained us all to respond: Lecturer: "globals are..." Whole class: "baaaaaaad". Almost two decades later I still remember it. =D

**Comment by kne42** [comment]
I think you're getting confused between a `QApplication` and a `Viewer`. A `QApplication` is a singleton which is why we want to call the `instance` method in case some other program has created one already. So we're not finding the "active" viewer or anything; we are creating a new viewer/window each time.

I'll assume that your desire for a `viewer` argument is born out of this misunderstanding but if you still think we should have one, I disagree because the function returns the viewer which users can then add layers to, so this workflow is redundant. I think that these functions should simply be macros/convenience methods for a standard workflow.

`global _app` was actually introduced to keep the QApplication from being garbage collected. However you are right in the sense that it is unnecessary – I have just tested it and it does not seem to have an impact on the running of the program whether it is garbage collected or not. I will make it a local `app` variable.

**Comment by jni** [comment]
@kne42 

> I think that these functions should simply be macros/convenience methods for a standard workflow.

Well which is it, do we want to provide convenience, or a shortcut that shaves one line of code but then has you revert to the object-oriented API? =P

I don't think `scatter` provides any value to Napari if you can't follow it or precede it with `imshow`. We are an image viewer/editor, not a plotting library, so if I'm going to scatter but then use `add_image`, or even `add_markers` again, then my feeling is that this mixing of APIs is ugly and mostly pointless. 

> I think you're getting confused between a `QApplication` and a `Viewer`. A `QApplication` is a singleton which is why we want to call the `instance` method in case some other program has created one already. So we're not finding the "active" viewer or anything; we are creating a new viewer/window each time.

This much was true, I was indeed getting confused between the two, thanks for clarifying. =) I don't really understand the application abstraction then, though...? What does this singleton do?

**Comment by kne42** [comment]
> Well which is it, do we want to provide convenience, or a shortcut that shaves one line of code but then has you revert to the object-oriented API? =P
> 
> I don't think `scatter` provides any value to Napari if you can't follow it or precede it with `imshow`. We are an image viewer/editor, not a plotting library, so if I'm going to scatter but then use `add_image`, or even `add_markers` again, then my feeling is that this mixing of APIs is ugly and mostly pointless.

As usual, you are absolutely right – tbh I'd greatly prefer a functional API but I'm just not sure how to avoid mixing and matching OO with functional-style programming due to the ability for users to define their own layer types with their own properties. What are your thoughts on this?

In the meantime I'll remove `scatter`.

> I don't really understand the application abstraction then, though...? What does this singleton do?

It's what provides the event loop. In interactive mode, this loop is provided to us by Python (in IPython you are required to use the `%gui qt5` magic).

**Comment by sofroniewn** [comment]
Yup @kne42 and @jni I'm also a little unsure about what to do here. I agree the mixing of two commands is confusing and should be avoided. Would it be cleaner if they at least had the same time name? So from `napari.gui import imshow`, `imshow(image)` or `viewer.imshow(image)` and the same for `scatter`.

Or should we only have the one method - in which case we could have either

1. only `viewer.add_image(image)` etc.
2. only the `imshow` where `imshow(image, viewer=None)` will create a viewer and `imshow(image, viewer=viewer)` will add an image layer to that viewer?

If we can make 2. work that could be good. Thoughts @freeman-lab?

**Comment by freeman-lab** [comment]
This one is tough! A couple ways to slice it and no obvious answers. My thoughts:

- I think @kne42 is right that mixing and matching the functional and object approach is "the problem" here, and whatever we do we should be consistent and probably only expose one route, e.g. it's only `imshow` `scatter` etc. with `viewer` as an optional argument (without which a new one gets created) OR you always start by creating a `viewer` and then adding images, points, etc. to it, but we don't mix the two

- What I personally like less about the functional approach is that it feels like a plotting library, which as @jni says, this isn't!

- To me the viewer is a core concept and a central, grounding force in the workflow, far more so then say a plot or a set of axes, so it feels that the workflow should start by creating a viewer... maybe we just need some creative ideas for streamlining that step, which seems to have been the motivation toward `imshow` in the first place

**Comment by freeman-lab** [comment]
What about the following pure OO approach

**Comment by freeman-lab** [comment]
As one idea for a streamlined but purely object-oriented approach, we could do something like the following

### create an empty viewer
```
from napari import gui
viewer = gui.launch()
```

### create an empty viewer and add an image to it
```
from napari import gui
viewer = gui.launch()
viewer.add_image(data)
```

### create a viewer with an image already in it
```
from napari import gui
viewer = gui.launch(image=data)
```

This way it always starts with the viewer as the grounding element, but there's a shortcut for getting a viewer with an image in one line.

Thoughts?

**Comment by sofroniewn** [comment]
It's an interesting hybrid, I'm unsure then for that third case would be support keywords arguments for all our layer types `markers`, `vectors`, `shapes` etc and would that get unwieldily (and what would happen if you tried to add multiple ones), or would be support being able to pass multiple images as a list or pass a dictionary of different layer types and their data? That all seems a bit weird and that the shortcut would become too complex.

I'm also a little unsure about `gui.launch()` and how that relates now to things like the `Window` etc. but that could be figured out

**Comment by sofroniewn** [comment]
After good discussion during the meeting I think where we landed is that for this PR we would just remove imshow entirely and merge. This means all examples will use an api that is like the following:

```python
from napari_gui import Window, Viewer
viewer = Viewer()
window = Window(viewer)
viewer.add_image(astro)
viewer.add_image(camera)
```

We will then make a followup PR that supports the following API

```python
from napari_gui import Viewer
viewer = Viewer(astro)
viewer.add_image(camera)
```
and
```python
from napari_gui import Viewer
viewer = Viewer()
viewer.add_image(astro)
viewer.add_image(camera)
``` 
where the input arguments to `Viewer` get treated identically to the input arguments to `add_image` as images are our main layer type and we want away to show an image in 2-lines.

Additionally now window creation will be handled inside `Viewer` and the window will be accessible through `viewer.window` and the layers will be accessible through `viewer.layers`. Under the hood though we will using a pass-through from a Viewer object to a ViewerWidget object (that does not know about `Window`) such that the following code path would also be acceptable for advanced developers that want to embed Napari in their own applications.
```python
from napari_gui import ViewerWidget
viewer = ViewerWidget()
viewer.add_image(astro)
viewer.add_image(camera)
custom_application.add(viewer)
``` 
where that final line embeds the viewer in their custom application

**Comment by royerloic** [comment]
Great! I like it!

**Review by royerloic — APPROVED** [review]
Let's do this

**Comment by sofroniewn** [comment]
I'd also say we drop the `layers.ipynb` and `markers.ipynb` and rewrite all the examples without `imshow` for now just using the `Viewer()` but then we can revisit in the next PR.

**Comment by royerloic** [comment]
We have some conflicts with the notebook files, this needs to be resolved...

**Comment by sofroniewn** [comment]
I can try and fix this and then push a commit - is that ok @kne42? It's about to be dinnertime on a Friday night, so don't want to force anyone in SF to work right now, but also don't want to leave you blocked @royerloic

**Comment by jni** [comment]
@sofroniewn I say just go for it, just don't delete @kne42's branch. Or just grab the branch and issue a new PR?

**Comment by jni** [comment]
@sofroniewn correction, we've settled on:

```python
from napari import Viewer
```

=P

**Comment by sofroniewn** [comment]
ok i will create a new branch off of this one remove imshow and fix the examples right now, expect a new PR soon (and then I'm off to dinner too!)

**Comment by freeman-lab** [comment]
Fantastic summary, feeling great about this direction!

**Comment by sofroniewn** [comment]
Ok just created a new PR, should have all the changes from this one and both the imshow and scatter API removed.

**Comment by sofroniewn** [comment]
This has been superseded by #143

**Pull request closed without merging**
