### PR TITLE
Type napari.layers.points helper sub-modules

### PR DESCRIPTION
**Pull request by dstansby**
# Description
Depends on https://github.com/napari/napari/pull/6499.

### CODE REVIEW

**Comment by Carreau** [comment]
Just be careful I have ~5 Typings PRs that are open/draft and it seem we are often adding typing to the same files.

**Comment by dstansby** [comment]
> Just be careful I have ~5 Typings PRs that are open/draft and it seem we are often adding typing to the same files.

👍 hopefully the changes will be easy enough to sort out - I can rebase my PRs when yours are merged.

**Comment by Carreau** [comment]
I pushed a commit that should fix some of the errors.

**Comment by Carreau** [comment]
The remaining errors seem to be changes in values instead of just having Sections compared to sets.

**Comment by dstansby** [comment]
I lost track of this and it looks tricky to rebase, so I will close.

**Pull request closed without merging**
