### PR TITLE
QLargeIntSpinbox with QAbstractSpinbox and python model

### LINKED ISSUE #2647: Change `QtLargeIntSpinBox` for Labels to inherit directly from `QAbstractSpinBox`
## 🚀 Feature
Following on from #2608 and #2640 , an ideal implementation would inherit from `QAbstractSpinBox` and therefore support any integer types for Labels layers, as well as overriding the necessary private methods of the `QAbstractSpinBox`.

## Motivation
This would provide all the support required for unbound integers without resorting to some 'hacky' signal emissions as was required in #2640 to ensure `valueChanged` was correctly emitted.

## Pitch

@tlambert03 has written a basic implementation of this spin box already:

```python
from qtpy.QtCore import QSize, Signal
from qtpy.QtGui import QFontMetrics, QValidator
from qtpy.QtWidgets import QAbstractSpinBox, QStyle, QStyleOptionSpinBox


class AnyIntValidator(QValidator):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)

    def validate(self, input: str, pos: int):
        if input.isnumeric():
            return 2, input, len(input)
        else:
            return 0, input, len(input)


class QtLargeIntSpinBox(QAbstractSpinBox):
    """An integer spinboxes backed by unbound python integer

    Qt's built-in ``QSpinBox`` is backed by a signed 32-bit integer.
    This could become limiting, particularly in large dense segmentations.
    This class behaves like a ``QSpinBox`` backed by an unbound python int.

    Does not yet support "prefix", "suffix" or "specialValue" like QSpinBox.
    """

    textChanged = Signal(str)
    valueChanged = Signal(int)

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self._value: int = 0
        self._minimum: int = 0
        self._maximum: int = 2 ** 64 - 1
        self._single_step: int = 1
        validator = AnyIntValidator(self)
        self.lineEdit().setValidator(validator)
        self.lineEdit().textChanged.connect(self._editor_text_changed)
        self.setValue(0)

    def value(self):
        return self._value

    def setValue(self, value):
        self._value, old = self._bound(int(value)), self._value
        self._updateEdit()
        self.update()
        if self._value != old:
            self.textChanged.emit(self.lineEdit().displayText())
            self.valueChanged.emit(self._value)

    def _updateEdit(self):
        new_text = str(self._value)
        if self.lineEdit().text() == new_text:
            return
        self.lineEdit().setText(new_text)

    def singleStep(self):
        return self._single_step

    def setSingleStep(self, step):
        self._single_step = int(step)

    def minimum(self):
        return self._minimum

    def setMinimum(self, min):
        self._minimum = int(min)

    def maximum(self):
        return self._maximum

    def setMaximum(self, max):
        self._maximum = int(max)

    def setRange(self, minimum, maximum):
        self.setMinimum(minimum)
        self.setMaximum(maximum)

    def stepBy(self, steps: int) -> None:
        step = self._single_step
        self.setValue(self._bound(self._value + (step * steps)))

    def _editor_text_changed(self, t):
        state, *_ = self.validate(t, self.lineEdit().cursorPosition())
        if state == QValidator.Acceptable:
            self.setValue(int(t))

    def _bound(self, value):
        return max(self._minimum, min(self._maximum, value))

    def stepEnabled(self):
        flags = QAbstractSpinBox.StepNone
        if self.isReadOnly():
            return flags
        if self._value < self._maximum:
            flags |= QAbstractSpinBox.StepUpEnabled
        if self._value > self._minimum:
            flags |= QAbstractSpinBox.StepDownEnabled
        return flags

    def sizeHint(self):
        self.ensurePolished()
        fm = QFontMetrics(self.font())
        h = self.lineEdit().sizeHint().height()
        w = fm.horizontalAdvance(str(self._value)) + 3
        w = max(36, w)
        opt = QStyleOptionSpinBox()
        self.initStyleOption(opt)
        hint = QSize(w, h)
        return self.style().sizeFromContents(QStyle.CT_SpinBox, opt, hint, self)
```

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
implementation of a QSpinBox as a QAbstractSpinbox with an unbound python `int` as the model.

closes #2647 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
added tests that are now passing locally on pyside2 and pyqt5 (will see if they pass on CI), setting values up to `1e100`
in the viewer I test up to `2**64` ... any higher and you get an error in `_raw_to_displayed`

<details>

```python
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/_qt/layer_controls/qt_labels_controls.py", line 300, in changeSelection
    self.layer.selected_label = value
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/labels/labels.py", line 509, in selected_label
    self._selected_color = self.get_color(selected_label)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/labels/labels.py", line 827, in get_color
    val = self._raw_to_displayed(np.array([label]))
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/labels/labels.py", line 757, in _raw_to_displayed
    np.arange(max_val + 1), self._seed
ValueError: Maximum allowed size exceeded
```

</details>

**Comment by DragaDoncila** [comment]
I've pulled this down and it works great, with the original caveats that this would report errors for valid integers for other reasons due to the way we compute our `Labels` layers. 

I feel like that distinction should be very clearly documented somewhere - maybe in the `QtLargeIntSpinBox` docstring?

I also feel we need to address this limitation of the `Labels` layer by mapping to smaller values where possible, and if not possible, falling back to the original layer behaviour. But that's a separate issue.

**Review by sofroniewn — APPROVED** [review]
Ok this looks good to me! I think we can go with this approach. Based on conversations with @DragaDoncila I think this will then supersede #2640 which we can then close.

**Comment by jni** [comment]
@tlambert03 I think we've lost here the limits on the spinbox of the backing array's dtype, which I think is useful. ie right now I can do:

```python
import napari
import numpy as np

labels = np.random.randint(0, 45, size=(5, 5)).astype(np.uint8)
viewer = napari.view_labels(labels)
napari.run()
```

Then set the spinbox to 300 and paint away, not knowing that I'm actually writing 44s into the array. I think it's fixable within this infrastructure using the setMinimum and setMaximum — what do you think about doing that in the init based on the backing labels layer?

Much smaller issue but I also think you should bring back the `qt_large_int_spinbox` name, `qt_large_spinbox` is... weird?

**Comment by tlambert03** [comment]
I think my preference (for the sake of keeping the interface of qt things consistent), would be to use setMin/Max, but outside of the init here ... like we would with any other Qt widget. Or with a subclass of this that auto sets min/max...  
but I can do that in this PR too

**Comment by jni** [comment]
Yeah, doesn't have to be in the init, but it should be done automagically by us somewhere during construction of the UI. Yeah I have a small preference to have it done before merging.

**Comment by sofroniewn** [comment]
Looks like this is now done @jni - I think this is good to merge?

**Pull request merged**
