### PR TITLE
add new PRs merged for 0.4.17 to release notes

### PR DESCRIPTION
**Pull request by alisterburt**

### CODE REVIEW

**Comment by Czaki** [comment]
maybe collect few of them instead of creating a single PR per PR?

**Comment by alisterburt** [comment]
@Czaki doing now :)

**Comment by andy-sweet** [comment]
@Czaki : I'll likely merge this in the next 24 hours, then create one last PR (based on a branch in my fork) to update the 0.4.17 release notes with any other merged PRs, as well the summaries. Does that work for you?

**Review by andy-sweet — APPROVED** [review]

**Comment by Czaki** [comment]
My only worries are doubling commits by creating additional commits per merged PR. Only this.

**Comment by andy-sweet** [comment]
> My only worries are doubling commits by creating additional commits per merged PR. Only this.

Agreed. In future releases, I would be in favor of just creating one PR to track release notes and only merge it for the first RC - at least when's there's only one release manager! There's no real value in merging it earlier as it just creates more commits on `main` for a file that cannot have merge conflicts.

**Pull request merged**
