### PR TITLE
[WIP] Functional plugins infrastructure

### PR DESCRIPTION
**Pull request by jni**
# Description

This is a skeleton for what I envision functional plugins to look like, as a first pass. Things like live update etc I think we should leave till later.

For reference, here's what happens when I crawl the `test_validation` [module](https://github.com/napari/image-types/blob/eb2fecab25f02f0c5c3cb9b47baa8c7f1b978437/tests/test_validation.py) from image-types:

```python
In [6]: plug.crawl(tv)                                                    
Out[6]: {'gaussian_filter': <function test_validation.gaussian_filter(image: 'Image', sigma: 'Sigma') -> 'Image'>}
```

As a side bonus this PR includes a menu bar and a close-window shortcut. :tada:

This isn't even functional yet but wanted to submit to discuss during meeting.

Q: wasn't sure whether this should live in the window or the viewer, guidance here would be much appreciated. I kinda think the window.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
@jni this is really cool to see - definitely helps me understand how you're thinking about all this.

I'd say this should all live on `Window` for now, and that at some point in time we might want to pull it out of this repo entirely and into the `napari-app` repo. Having it on `Window` will make that transition easier. I don't think `Viewer` should know about plugins at all.

Looking forward to more discussion later!

**Comment by jni** [comment]
@sofroniewn I've picked this up again finally, fyi. It's looking pretty cool right now. Just need to hook up actions to the functions. =) I've temporarily given up on typing and we'll just have to rely on users to give sane inputs to the functions, which is The Python Way anyway. It should be easy to add typing after an initial version is working.

The next stage is to have a popup menu for each action that lets you select either existing layers or variables in the global workspace or Python literals as input. Again, this can be replaced with a drawer with e.g. preview mode in the future.

Just keeping everyone updated... ;)

**Comment by jni** [comment]
btw, I do get this warning when adding the scikit-image module: "The gui lock can only be acquired by one toolkit per session.             The lock is already acquired by qt". I presume it has something to do with adding menu items at runtime, but I have no idea... If anyone knows what it's about, pointers are appreciated!

**Comment by sofroniewn** [comment]
@jni this looks so cool, great that you're picking it up again! i think this is a great time for us to make a push for the plugins :-)

when ready I'm very happy to reimplement the project @marshuang80 did this summer around image segmentation as a plugin - https://github.com/transformify-plugins/segmentify - right now it uses napari as a dependency and subclasses the Viewer.

We'll have to think about some additional things like how is a plugin allowed to define custom keybindings, and eventually how is a plugin allowed to request UI elements.

**Comment by jni** [comment]
@sofroniewn indeed! To clarify, my goal for this PR is to only provide support for "functional" plugins (things that take in layer data and spit out other layer data). I feel like other stuff can come in later PRs.

I haven't thought very much about interactive plugins, but one idea is to have them be Python functions that take the viewer as input. Then the world is their oyster. =)

Something to discuss once this is ready for review. Hold please. =)

**Comment by jni** [comment]
😂 I think we are going to have to curate a NumPy plugin rather than recommend that people add NumPy directly (note that the list below is in alphabetical order):

Screen Shot 2019-09-23 at 4 29 12 pm

**Comment by goanpeca** [comment]
Is this something we can close now @jni? Thanks!

**Comment by sofroniewn** [comment]
ToDo here is to convert this into an issue containing the code we want to preserve/ reuse in the future - cc @jni

**Comment by jni** [comment]
Closing as outdated, discussion to continue in #3525.

**Pull request closed without merging**
