### PR TITLE
Rewrite ellipse discretization from scratch

### PR DESCRIPTION
**Pull request by Carreau**
There was many problem with ellipse discretization, which was losing a
lot of informations about the ellipse orientation in 3D. (Aka, fas often completely wrong if not axis aligned).

This almost completely rewrite it to be more general, as well as a bit
more efficient in the generation of the triangulation indices.

I'm not sure it is more readable (but it looks way more generic).

Main difficulty in reading this code is that the shapes of objects
(transforms), depends on Wether you are in 2 or 3D, but the math is the
same.

I've tried to heavily comment it for the next modification, as I'm
pretty sure we will hit some degenerate cases.

I've also modified one of the existing example that display ellipses
in addition to points where the 4 corners would be in order to properly
visually check the rendering it correct.

See #4326 for some visualisation of incorrect rendering.

The triangle index generation at the end is a bit hard to read:

```
-    triangles = np.array([[0, i + 1, i + 2] for i in range(num_segments)])
+    triangles = (
+        np.arange(num_segments) + np.array([[0], [1], [2]])
+    ).T * np.array([0, 1, 1])
```

So I'm' happy to revert it, but it is about an order of magnitude faster
than the Python list comprehension.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# How has this been tested?

Currently only visually, let's see how the test suite reacts.
I likely need to add a few test to make sure some discretizations are ok.

### CODE REVIEW

**Comment by Carreau** [comment]
I think @sofroniewn and @jni you did most of that in #100 originally, so your input would be appreciated.

**Comment by sofroniewn** [comment]
Hi @Carreau - thanks for picking this up. I think the previous ellipse code was limited to axis aligned planar projections and we didn't support any non-axis aligned ellipses - that probably should have been more clearly documented. Can you check whether this is true for our rectangles and polygon code too.

It's fine if we expand generality with ellipses first, but we should have a plan to support the other shapes in the same way if we need to as well.

I'll give this a more through review and demo when I can

**Comment by Carreau** [comment]
> Can you check whether this is true for our rectangles and polygon code too.

AFAICT, rectangles and polygons are fine, as some of the examples actually show off-axis/off-plane rectangles and polygon. 

Really here it's only the triangulation and display of ellipses that is/was wrong as the for the the rectangles/polygon it is _already_ an polygon so you don't need to change base to make it a polygon. At least the above is true for polygon that live in a 3D "slice".

I'm wondering if we should verify that for all coordinate of vertices except 3 the values are the same.

**Review by sofroniewn — APPROVED** [review]
Current behaviour of this example on main

image

New behaviour of this example after this PR 
image

This is much better!!!

> Really here it's only the triangulation and display of ellipses that is/was wrong as the for the the rectangles/polygon it is already an polygon so you don't need to change base to make it a polygon. At least the above is true for polygon that live in a 3D "slice".

Yes ok that makes sense to me now, I understand what's happening here.

This looks great and I think is good to go in. Sorry for taking so long to review this. I will merge now. Let me know if there are more improvements you want to make in other PRs. As I think I may have said elsewhere this part of the code base hasn't received very much love

**Pull request merged**
