### PR TITLE
[Draft] - Suport Qt6

### PR DESCRIPTION
**Pull request by tlambert03**
# Description

this is just an experiment to see whether we could use `superqt.qtcompat` instead of qtpy.  I see a number of packages making their own Qt6 compatibility layers given the lack of activity on the topic (~6 months without much response) and superqt.qtcompat has Qt6 support (for the modules we need at least).

(note, for anyone concerned, this would _not_ prevent someone from using qtpy in the same environment as napari... both of these compatibility layers respect already imported modules and effectively point to the same things).

### CODE REVIEW

**Comment by tlambert03** [comment]
looks like it works fine (headless test fail is minor and can be fixed)

**Comment by goanpeca** [comment]
Sounds good, indeed a lot of those projects are stuck with no maintenance, so it makes sense to make the move!

**Comment by tlambert03** [comment]
can confirm this is mostly working on PySide6 (with https://github.com/napari/superqt/pull/34) ...
PyQt6 is a problematic because it dropped support for compiled resources via `pyrcc`... this doubles the importance of #3136 and  https://github.com/napari/superqt/pull/24

**Comment by Czaki** [comment]
pyside6 (and partially pyqt6) support is already (5 days ago) merged in qtpy https://github.com/spyder-ide/qtpy/pull/225

**Comment by tlambert03** [comment]
I'm aware thanks

**Comment by Czaki** [comment]
> this doubles the importance of #3136

what is the benefit of using fonts instead of QColoredSVGIcon from `napari._qt.qt_resources._svg`?

**Comment by tlambert03** [comment]
One major difference is that font colors can be styled via QSS... so a theme change needn't require cascading through all widgets looking for svgs to swap

**Comment by Czaki** [comment]
ahh. No option for query qss in PaintEngine. 
But paint engine could be connected to settings?

**Comment by tlambert03** [comment]
> But paint engine could be connected to settings?

yep, you could do something like that.  In any case, I suspect both are useful.  Another big benefit of fonts is how easy it is quickly access a ton of icons via font-icon libraries.

**Comment by CAM-Gerlach** [comment]
FYI, PyQt6 support in QtPy is mostly complete and tested on our CIs; spyder-ide/qtpy#271 should be merged soon and resolve many of the remaining known issues, with any further ones will be worked on and merged shortly. If you do find any issues following that that aren't already mentioned on spyder-ide/qtpy#233 , please do mention them there, open an issue or submit a PR and we'll promptly take a look. Other than that, QtPy 2.0 should be more or less feature-complete, with a relatively small amount of work remaining in bugfixes, testing and documentation, and the plan is to release in the next few weeks to a month, no later than the end of the year. See spyder-ide/qtpy#269 where this is discussed.

**Comment by tlambert03** [comment]
> FYI, PyQt6 support in QtPy is mostly complete and tested on our CIs; [spyder-ide/qtpy#271]

thanks @CAM-Gerlach!

**Comment by CAM-Gerlach** [comment]
And sorry for the six+ month gap in QtPy maintenance; the main QtPy maintainer abruptly left the Spyder project at around the same time the Spyder 5 release cycle kicked into high gear and needed all hands on deck for that, and while I stepped in to propose a plan for QtPy 1.x and 2.0, overhaul the CIs and shepard along some PRs, I then had to take a break myself for some personal reasons, but now QtPy has a much more Qt-knowledgeable full-time lead maintainer in @dalthviz as well as I'm back again to help, so things are moving along well again (with plenty of help from the community too).

**Comment by tlambert03** [comment]
> And sorry for the six+ month gap in QtPy maintenance

no worries!  We definitely understand how it goes! :)  we were going to make do if we had to, but we're very glad to have you back at it :)

**Comment by CAM-Gerlach** [comment]
Thanks so much for your kind words, @tlambert03 ! They really mean the world to all of us (and my individual role was relatively minor); in particular, @jschueller did most of the work for initial Qt6 compat (especially for PySide6), @dalthviz took care of most of the rest, and @stonebig and others helped a lot too,

**Pull request closed without merging**
