### PR TITLE
Remove deprecated code from Labels layer

### PR DESCRIPTION
**Pull request by jni**
# References and relevant issues

This completes the deprecations started in #6542. All it does is remove the
things we warned we would remove. 😂

### CODE REVIEW

**Comment by Czaki** [comment]
Tests

**Comment by jni** [comment]
Hmmm, thanks for the ping, I thought I had fixed the relevant tests but clearly I missed some 😅

**Comment by jni** [comment]
@Czaki I've seen [this](https://github.com/napari/napari/actions/runs/7763656257/job/21176073027?pr=6641#step:11:424) a couple of times now... It doesn't affect the tests passing but it's weird/concerning. Any ideas?

```pytb
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
      self.run()
    File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/multiprocessing/process.py", line 108, in run
      self._target(*self._args, **self._kwargs)
    File "/home/runner/work/napari/napari/.tox/py311-linux-pyqt6-no_cov/lib/python3.11/site-packages/pytest_pystack/_monitor_process.py", line 57, in _run_monitor
      raise Exception(
  Exception: new test should not start before previous test finished
```

Also as a side note — do you know if there's a way to auto-expand the test suite lines automatically?

**Comment by jni** [comment]
(failing tests should be fixed now... 🤞)

**Comment by Czaki** [comment]
> @Czaki I've seen [this](https://github.com/napari/napari/actions/runs/7763656257/job/21176073027?pr=6641#step:11:424) a couple of times now... It doesn't affect the tests passing but it's weird/concerning. Any ideas?

It looks like in some test, one of thread is not properly finished before test end. But I do not have idea how to debug it. 



> Also as a side note — do you know if there's a way to auto-expand the test suite lines automatically?

I do not understand

**Comment by jni** [comment]
> > Also as a side note — do you know if there's a way to auto-expand the test suite lines automatically?
> 
> I do not understand

When I go to a failing test action, I have to find the tox line and expand it to see the test output:

https://github.com/napari/napari/assets/492549/64062ca8-041a-4261-b8dd-81191eca1c6e

99.99% of the time, that is the information we are after, so it would be good if clicking on the check details took you directly to an expanded view of the output.

**Comment by jni** [comment]
(Side note: thank you so much for your PRs adding tests that run the benchmarks!!! 🤩)

**Comment by jni** [comment]
Looks like everything is passing now! 😍

**Comment by Czaki** [comment]
As it is touching benchmarks, I prefer to finish and merge #6496 first. To have fully working benchmarks.

**Comment by jni** [comment]
This seems just as easy to merge into #6496 as vice versa? I don't see why they need to be coupled? (This PR obviously does not have performance implications.)

**Review by melonora — APPROVED** [review]
I think these are indeed just removing deprecations. Checking locally seems to work fine for me so I am approving. @Czaki is there still a reason to wait for merging this one given that #6496 is merged?

**Comment by Czaki** [comment]
> I think these are indeed just removing deprecations. Checking locally seems to work fine for me so I am approving. @Czaki is there still a reason to wait for merging this one given that #6496 is merged?

We will see. I just merged main into this PR.

**Comment by jni** [comment]
Looks like only a flaky windows test failing. 🥳 I propose this gets merged before the PR party starts. 😃

**Review by Czaki — APPROVED** [review]

**Pull request merged**
