### PR TITLE
coerce surface vertex data to float32

### LINKED ISSUE #2817: New surface shaders are broken
## 🐛 Bug

With `0.4.9rc0`, new shaders for mesh rendering were added (#2792).
On my machine, this broke surface layers:

## To Reproduce
```python
import napari
import numpy as np
pos = np.array([[0, 0, 0], [1, 1, 1], [0, 1, 0]]) * 10
faces = np.array([[0, 1, 2]])
v = napari.Viewer(ndisplay=3)
v.add_surface((pos, faces))
```
This fails with a [long trace](https://pastebin.com/ZjCNNRfi), whose starting point seems to be:
```python
File "~/.local/lib/python3.9/site-packages/napari/_vispy/vendored/filters/mesh.py", line 301, in _update_data
    if not self._attached:
AttributeError: 'ShadingFilter' object has no attribute '_attached'
```
and ends with
```python
RuntimeError: Cannot draw program if code has not been set
```

## Environment

```yaml
napari: 0.4.9rc0
Platform: Linux-5.12.8-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 465.31
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-properties-plotter: 0.1.dev2+g2734460.d20210520
- ndtiffs: 0.1.1
- scikit-image: 0.4.8
- svg: 0.1.5
```

### PR DESCRIPTION
**Pull request by alisterburt**
partial fix for #2817 (same root cause as vispy/vispy#2007)
together with #2821 this should fix #2817 completely

### CODE REVIEW

**Comment by sofroniewn** [comment]
Looks like one of our round trip tests is failing here - can we do the conversion after slicing? possibly on right before the vispy end inside https://github.com/napari/napari/blob/master/napari/_vispy/vispy_surface_layer.py?

**Comment by alisterburt** [comment]
have moved the recasting to the vispy surface layer as suggested - cleaner, thanks!

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Comment by sofroniewn** [comment]
Thanks @alisterburt, let's merge this, and then you can rebase #2821 and we can make sure all different permutations are working there

**Comment by alisterburt** [comment]
sounds good @sofroniewn - if the rebase doesn't fix [the error](https://github.com/napari/napari/pull/2821/checks?check_run_id=2730288675) in #2821 I'm not sure what to do unfortunately

**Pull request merged**
