### PR TITLE
Finds layer_controls based on layer's MRO

### PR DESCRIPTION
**Pull request by glyg**
# Description

See discussion on image.sc [here](https://forum.image.sc/t/custom-layer-control/58727)

This PR should allow to use inheritance for the QtLayerControls widgets (which is not possible right now due to the way the `layer_to_controls` dictionary is parsed

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

https://forum.image.sc/t/custom-layer-control/58727

# How has this been tested?

I added `test_qt_layer_controls.py` to assert that the class higher in the layer's MRO was used. The test fails with the current implementation and passes with the proposed changes.

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas
_As this is not part of the public API, I'm not sure what I have to modify_ (I still updated the docstring)
- [ ] I have made corresponding changes to the documentation

- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by jni — APPROVED** [review]
Nice! I'm happy to merge this as is. :partying_face: Thanks @glyg!

**Comment by jni** [comment]
(It looks like Windows CI is completely dead — that has nothing to do with this PR.)

**Comment by glyg** [comment]
Thanks @jni - this is a really cool project!

**Review by sofroniewn — APPROVED** [review]
LGTM too, i'm going to try rerunning tests. We've got 6 fails here which is a lot. If they still fail maybe we can update from main and then rerun as I just merged a PR with less fails. I just want to make sure nothing unexpected slips in.

Thanks for PR!!

**Comment by glyg** [comment]
Do you want me to merge the latest main and push here?

**Comment by sofroniewn** [comment]
> Do you want me to merge the latest main and push here?

Yes can you, thanks!

**Comment by sofroniewn** [comment]
We've got some widgets leaking here. I think they might be specific to this PR. Maybe @tlambert03 can take a look?

**Comment by tlambert03** [comment]
> We've got some widgets leaking here. I think they might be specific to this PR.

probably want to use `qtbot.addWidget` for each of the widgets that get created during the test.  See here for a bit more detail:  
https://napari.org/developers/testing.html#testing-with-qt-and-napari-viewer
and
https://pytest-qt.readthedocs.io/en/latest/reference.html?highlight=addWidget#pytestqt.qtbot.QtBot.addWidget

**Comment by glyg** [comment]
Out of curiosity, how do you determine there is a memory leak? It does not show in the tests, does it?

**Comment by tlambert03** [comment]
> Out of curiosity, how do you determine there is a memory leak? It does not show in the tests, does it?

@sofroniewn  is referring to this error in the tests: 
https://github.com/napari/napari/runs/3899094453?check_suite_focus=true#step:9:228

however, I'll also add that "leaked widget" can happen if there is some other error in the test that causes execution to stop before the cleanup.  So, in this case, I'd try to figure out whether this timeout mentioned here is true: https://github.com/napari/napari/runs/3899094453?check_suite_focus=true#step:9:109

will have to look later

**Comment by sofroniewn** [comment]
I've just commented out the new tests from @glyg and am rerunning the test suite - hopefully this will at least tell us if problem is with the new tests or with the new code

**Comment by sofroniewn** [comment]
Tests are still failing, so it looks like the problem is with the added code, not just the added tests. Hope that helps debugging

**Comment by glyg** [comment]
Hi, thanks @sofroniewn - I'm not sure the failed macos test comes from this patch, as the latest tests from `main` seem to show the same Timeout error in some macos build (not consistently with pyqt or pyside, and not consistently w/t to the python version). See for example:
https://github.com/napari/napari/runs/3922293987#step:7:568
or
https://github.com/napari/napari/runs/3922293961#step:7:541

**Comment by sofroniewn** [comment]
> Hi, thanks @sofroniewn - I'm not sure the failed macos test comes from this patch, as the latest tests from main seem to show the same Timeout error in some macos build (not consistently with pyqt or pyside, and not consistently w/t to the python version). See for example:

Oooh ok maybe i missed this in those PRs. Can you try one last update from main and uncommenting your test, and then I'll merge. Sorry about this taking longer, we've just been trying hard lately to chase down some of these fails and want to make sure we're not adding new one. thanks for understanding!!

**Comment by glyg** [comment]
Thanks for the  merge @sofroniewn and all, that was smooth :) I fully understand your cautiousness, those bugs look really tricky!

**Pull request merged**
