### PR TITLE
Pin support pkg revision macos

### LINKED ISSUE #2965: Unable to install any packages/plugins in current bundle
## 🐛 Bug

Unable to install any packages/plugins in current bundle.

## To Reproduce

1. Download recent bundle build: https://github.com/napari/napari/actions/runs/988280586
2. Try to install any plugins or other packages in plugins > Install/Remove plugins...
3. Get the error: `error: unrecognized arguments: --upgrade`

Latest version of pip has not actually removed `--upgrade` so it's unclear to me what is going on. For reference the code that is failing is here:

https://github.com/napari/napari/blob/3aef5a5e6ab6c4fb4a83202040f1234ee4aca90b/napari/_qt/dialogs/qt_plugin_dialog.py#L82-L93

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

## Type of change

- [X] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Closes #2965 

# How has this been tested?

- [X] Run `python bundle.py`, install the DMG and try to install a plugin.

Screen Shot 2021-08-27 at 4 32 45 PM

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by jaimergp** [comment]
I can only test with Python 3.9 since I am on Big Sur.

Turns out the b1 build only contains `lib` and `bin` at the root level (instead of under `Python/Resources`), so a symlink needs to be added:

```
ln -s $HOME/Desktop/napari.app/Contents/Resources/Support/lib \ 
  $HOME/Desktop/napari.app/Contents/Resources/Support/Python/Resources/lib
```

Otherwise, Python fails to find the modules. That said, `sys.executable` is still pointing to `$HOME/Desktop/napari.app/Contents/MacOS/./napari`, so the `--upgrade` flag issue is still there. I'll need to add some logic in the plugin installer code to find the right Python.

**Comment by jaimergp** [comment]
Last commit addresses the symlink _and_ tries to find the Support Package Python executable. I saw there's a `running_as_bundled_app()` utility function to test whether we are on Briefcase, but it didn't work for me here, hence the workaround.

**Review by Carreau — APPROVED** [review]
I'm not super familiar with bundling but this seem ok to me.

**Review by sofroniewn — APPROVED** [review]
LGTM! Thanks @jaimergp!! 

This is a high value fix, so i think we should try and get in for 0.4.11 cc @jni who raised original issue.

**Review by tlambert03 — APPROVED** [review]
Looks great thanks!

>  I saw there's a running_as_bundled_app() utility function to test whether we are on Briefcase, but it didn't work for me here

Yeah, that function was never rock solid (was based on advice from Russel, who pointed out the difficulty since briefcase is trying to "just be a regular environment"...  whatever you need to do to patch is fine)

**Pull request merged**
