### PR TITLE
handle npe2 dock widget return type

### LINKED ISSUE #3617: npe2 dock widget TypeError
## 🐛 Bug

Binding a `napari_experimental_provide_dock_widget()` function as the callable for a npe2 widget raises a TypeError when the corresponding menu item is invoked.  

This is because some plugins return a `(callable,dict)` and other just the `callable`.

## To reproduce

1. Install the branch corresponding to  [tlambert03/npe2#26]
2. Adapt `napari-animation` to be a npe2 plugin. (e.g see [this branch](https://github.com/nclack/napari-animation/tree/npe2))
3. attempt to start the animation wizard from the plugins menu
 
Example napari.yaml (this format may change)
```yaml
name: napari_animation
display_name: animation
license: BSD-3-Clause
entry_point: napari_animation
contributions:
  commands:
    - id: napari_animation.widget
      python_name: napari_animation._hookimpls:napari_experimental_provide_dock_widget
      title: napari animation widget
  widgets:
    - command: napari_animation.widget
      name: wizard
```

Example entry points section in setup.cfg:
```ini
[options.entry_points]
# napari.plugin = 
	# animation = napari_animation
napari.manifest = 
    napari-animation = napari_animation:napari.yaml
```

## Traceback

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/src/CZI/napari/napari/_qt/menus/plugins_menu.py in _add_toggle_widget(key=('napari_animation', 'Wizard'), hook_type='dock')
    107 
    108                 if hook_type == 'dock':
--> 109                     self._win.add_plugin_dock_widget(*key)
        global self._win.add_plugin_dock_widget = undefined
        key = ('napari_animation', 'Wizard')
    110                 else:
    111                     self._win._add_plugin_function_widget(*key)

~/src/CZI/napari/napari/_qt/qt_main_window.py in add_plugin_dock_widget(self=<napari._qt.qt_main_window.Window object>, plugin_name='napari_animation', widget_name='Wizard')
    687 
    688         # instantiate the widget
--> 689         wdg = Widget(**kwargs)
        wdg = undefined
        Widget = (<class 'napari_animation._qt.animation_widget.AnimationWidget'>, {'name': 'Wizard', 'add_vertical_stretch': False})
        kwargs = {}
    690 
    691         # Add dock widget

TypeError: 'tuple' object is not callable
```

### PR DESCRIPTION
**Pull request by nclack**
# Description
closes #3617

If you're trying to reproduce this, see the issue for instructions.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# How has this been tested?

- [x] example: the test suite for my feature covers cases x, y, and z

It's hard to tell, but here's activation of an npe2 dock widget:

https://user-images.githubusercontent.com/98295/141726245-377fdfb5-e73b-4352-aeff-c6c4fcf21ed6.mov

### CODE REVIEW

**Comment by nclack** [comment]
There's another issue where a plugin widget that has both npe1 and npe2 interfaces ends up being duplicated in the menus. 

I haven't solved this yet, but it looks like I can filter the iterator by unique (plugin_name, widget name).  The npe2 instance would get selected first.

**Comment by sofroniewn** [comment]
@nclack i think you'll need to update from main here to deal with hanging examples test that was just fixed

**Comment by tlambert03** [comment]
> There's another issue where a plugin widget that has both npe1 and npe2 interfaces ends up being duplicated in the menus.

I don't think we should support using both interfaces in the same plugin.  (Can't see any compelling reason to use both? and npe1 sort of defeats the purpose of npe2)

See also my https://github.com/tlambert03 ... I don't think npe2 should accept the npe1 hookspec.  It's not particularly good, and now's the time to change it.  (If we do this to "smooth" the transition, then we stick ourselves with the problem of needing to change it later).  The autogeneration of the manifest from npe1 interface is also easy in this case

**Comment by nclack** [comment]
@tlambert03 I'm generally supportive of your points but I'm going to ask a lot of questions below. 

> supporting both interfaces in the same plugin

I was wondering about that. I'm going to point out what bothers me at the moment.

Q1: Hypothetically, if I'm updating napari-animation, I can release v0.0.3 with npe2 support and drop npe1 support.  Non-npe2-enabled napari users would still find v0.0.2?  

Q2: If I later found a bug in napari-animation, how would I fix that bug for both the npe1 and npe2 user base?

If we make npe2 a required dependency of napari, then these don't seem like so much of a problem.  

>  I don't think npe2 should accept the npe1 hookspec

I imagine this is a natural mistake to make so I'd like to point the user in the right direction with an error message. What do you think about that?

Should we do some inspection of the function type on the npe2 side so this kind of problem is uniformly handled? 

>  The autogeneration of the manifest from npe1 interface is also easy in this case

could you elaborate?  I'm imaging it's automatic when the calling convention matches but "needs manual intervention" otherwise.

**Comment by tlambert03** [comment]
> Q1: Hypothetically, if I'm updating napari-animation, I can release v0.0.3 with npe2 support and drop npe1 support. Non-npe2-enabled napari users would still find v0.0.2?

not sure what you mean here.  "find" how?  find on pypi?  find in entry points?  find in the plugin installer?  elaborate.

> If we make npe2 a required dependency of napari, then these don't seem like so much of a problem.

npe2 _will_ be a required dependency of napari.  I certainly wouldn't imagine any plugin developers to be creating manifests for npe2 before npe2 is a required dependency of napari.  (I see the fact that we've done it "optionally" so far as an idiosyncracy of our internal development... not as a model for how we intend to release this)

> I imagine this is a natural mistake to make so I'd like to point the user in the right direction with an error message. What do you think about that?

like, you think people will be releasing plugins with both entry points?  let's just block that!  our _primary_ concern is the end-user of napari.  If a plugin developer has to put in 5 more minutes of work to make sure that they remove their old entry point when they create an npe2 manifest, that's fine with me.  We can add a check for it if you'd like.

> Should we do some inspection of the function type on the npe2 side so this kind of problem is uniformly handled?

which function type?  not following.

> could you elaborate? I'm imaging it's automatic when the calling convention matches but "needs manual intervention" otherwise.

the calling conventions are non-overlapping.  `napari_experimental_provide_dock_widget` simply doesn't exist in npe2.  there's no need for it at all.  The `command` is simply a callable that returns a widget instance.  We no longer need the "or a tuple of widget and metadata" because all the metadata comes in the manifest

**Comment by sofroniewn** [comment]
> I don't think npe2 should accept the npe1 hookspec. It's not particularly good, and now's the time to change it.

I may not be following all the nuances of the conversation - but I agree with @tlambert03 and this sentiment. It might be like ripping a bandage off, but i'd like the npe1 -> npe2 transition to be as rapid and complete as possible once we're ready to pull the trigger!

**Comment by tlambert03** [comment]
@nclack and i had a chat about this.  I don't think napari should need to handle this case for npe2.  That is, a widget-providing npe2 plugin won't ever return a tuple.  _But_ we definitely want to help plugin devs in the transition from the old hookspec to the new.  That could happen both in our conversion script, and in some sort of `npe2 validate --full` cli command that would find bugs like this.
But I'm going to close this, since we don't want to support this return type anymore

**Pull request closed without merging**
