### PR TITLE
MAINT: Follow Nep29, bump minimum numpy.

### PR DESCRIPTION
**Pull request by Carreau**
As usual this is open for discussion.
See previous thread in #5089.

Also add a Nep29 badge to the readme.

for info Nep29 suggests:

> On Jan 31, 2023 drop support for NumPy 1.20 (initially released on Jan 31, 2021)

This also remove any conditional branching based on numpy version.

Note that this is _technically_ a change of API ad DTypeLiike is not exposed by `napari.types` anymore. I did not manage to keep it there as `ruff` is removing is as an unused import. I think that's ok as this was likely only used internally.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

https://numpy.org/neps/nep-0029-deprecation_policy.html

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by Czaki — APPROVED** [review]
Looks ok for me. 
As it removes conditional imports it is improvement for me. 

As I do not know when the next release will be I'm ok with fast merge.

**Comment by Carreau** [comment]
The ubuntu archive seem to have been down. 
GitHub does not seem happy about it and won't let me restart the failing workflow for now... I'll do it later.

**Review by brisvag — APPROVED** [review]

**Comment by brisvag** [comment]
Minreq failure is unrelated, but maybe this PR could *also* affect that... maybe we shoudl wait? @Czaki any progress on the minreq issue?

**Comment by Czaki** [comment]
I have created #5560. 
I do not like it, but I do not think that I will be able to ship something better in short time.

My attempt for better solution is here but require time to polish https://github.com/Czaki/tox-min-req

**Comment by brisvag** [comment]
Tests are good now, let's merge!

**Pull request merged**
