### PR TITLE
Do not use random shapes in napari_builtins conftest fixtures

### LINKED ISSUE #5286: [test-bot] pip install --pre is failing
The --pre Test workflow failed on 2022-11-03 12:17 UTC

The most recent failing test was on windows-latest py3.9 pyside2
with commit: 4ebbf1e58ac258a27775f4a314c3aa53418503da

Full run: https://github.com/napari/napari/actions/runs/3385519090

(This post will be updated if another test fails, as long as this issue remains open.)

### PR DESCRIPTION
**Pull request by Czaki**
# Description

From time to time, using random shapes cause test failure. This PR switch from random number to const one. 

```python-traceback
  ________________________ ERROR collecting test session _________________________
  /opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/importlib/__init__.py:127: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  <frozen importlib._bootstrap>:1030: in _gcd_import
      ???
  <frozen importlib._bootstrap>:1007: in _find_and_load
      ???
  <frozen importlib._bootstrap>:986: in _find_and_load_unlocked
      ???
  <frozen importlib._bootstrap>:680: in _load_unlocked
      ???
  /tmp/.tox/py39-linux-pyside2/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:168: in exec_module
      exec(co, module.__dict__)
  napari_builtins/_tests/conftest.py:41: in <module>
      layers.Shapes(
  napari/layers/shapes/shapes.py:508: in __init__
      self._init_shapes(
  napari/layers/shapes/shapes.py:2076: in _init_shapes
      self._add_shapes(
  napari/layers/shapes/shapes.py:2191: in _add_shapes
      self._add_shapes_to_view(shape_inputs, self._data_view)
  napari/layers/shapes/shapes.py:2203: in _add_shapes_to_view
      sh_inp = tuple(
  napari/layers/shapes/shapes.py:2205: in <genexpr>
      shape_classes[ShapeType(st)](
  napari/layers/shapes/_shapes_models/polygon.py:30: in __init__
      super().__init__(
  napari/layers/shapes/_shapes_models/_polgyon_base.py:51: in __init__
      self.data = data
  napari/layers/shapes/_shapes_models/_polgyon_base.py:76: in data
      self._update_displayed_data()
  napari/layers/shapes/_shapes_models/_polgyon_base.py:81: in _update_displayed_data
      self._set_meshes(
  napari/layers/shapes/_shapes_models/shape.py:224: in _set_meshes
      vertices, triangles = triangulate_face(clean_data)
  napari/layers/shapes/_shapes_utils.py:562: in triangulate_face
      vertices, triangles = PolygonData(vertices=data).triangulate()
  /tmp/.tox/py39-linux-pyside2/lib/python3.9/site-packages/vispy/geometry/polygon.py:125: in triangulate
      tri.triangulate()
  /tmp/.tox/py39-linux-pyside2/lib/python3.9/site-packages/vispy/geometry/triangulation.py:186: in triangulate
      self._edge_event(i, j)
  /tmp/.tox/py39-linux-pyside2/lib/python3.9/site-packages/vispy/geometry/triangulation.py:405: in _edge_event
      self._add_tri(polygon[ind], polygon[ind-1],
  /tmp/.tox/py39-linux-pyside2/lib/python3.9/site-packages/vispy/geometry/triangulation.py:747: in _add_tri
      assert a != b and b != c and c != a
  E   AssertionError
```

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

closes #5286 

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by Czaki** [comment]
@andy-sweet I assign you as you have done similar PR in the past.

**Review by Carreau — APPROVED** [review]

**Review by andy-sweet — APPROVED** [review]
Thanks for the fix @Czaki. As before with #5245, the randomness reveals a bug (#1058), but at the cost of a flaky test, which is undesirable, so the fix makes sense and looks good.

Approving this, but I did notice more use of `rand` above the lines you changed for other layer types/properties. Maybe consider using `np.random.seed` above those lines so we have reproducible input that doesn't break CI (assuming we get lucky with the seed!).

Either way, I'll merge this after 24 hours unless there are any objections.

**Comment by brisvag** [comment]
I'm tempted to say to just leave the rest as is in case it reveals other bugs... ^^'

**Comment by andy-sweet** [comment]
Merging this to de-flake CI. I was about to write up an issue related to adding a fuzzing tool to napari's test, but found the existing #2444, which already does a great job of this. That issue mentions targeting a small part of napari's tests at first and the `LAYERS` defined here for `napari_builtins` seems like a good target.

**Pull request merged**
