### PR TITLE
Fix error in `Viewer.reset_view()` with vispy 0.7

### PR DESCRIPTION
**Pull request by alisterburt**
# Description
This PR is a fix for an issue @sofroniewn found with vispy 0.7 #2875 

In `napari._vispy.vispy_camera.VispyCamera` when setting zoom we get the camera width and height from the vispy viewbox. The cause of the issue is that the camera width and height become zero temporarily during a call to `Viewer.reset_view()` - below I've printed the canvas size and the scale on running `examples/add_image.py`

```
[800 600] [1. 1.]
[491 653] [0. 0.]
/Users/aburt/Programming/napari/napari/_vispy/vispy_camera.py:112: RuntimeWarning: divide by zero encountered in true_divide
  zoom = np.min(canvas_size / scale)
[491 653] [537.89473684 715.36713474]
```

and the stack leading to the call
image

because the situation where the scale is 0 appears only temporarily during `Viewer.reset_view()` simply checking whether the scale values are zero and temporarily setting them both to 1 appears to be an acceptable workaround.

I'm not at all sure why the camera gets into this weird temporary state - @djhoese do you know what might have changed with the viewbox camera?

### CODE REVIEW

**Comment by djhoese** [comment]
It depends what specific commit you're using from vispy. 6 days ago I merged https://github.com/vispy/vispy/pull/2100 which pointed out some important issues with the new grid solver code (missing an important method call on the solver). I would hope this solves this if it wasn't being included, but it is possible there are other issues if any `GridWidget`s are involved in the napari stuff (`.add_grid`) as that's where the solver was updated.

**Comment by alisterburt** [comment]
thanks for the info @djhoese - problem was present using master from today, we do have some grid things going on in napari but I'm not sure of specifics. Will try to have another dig

**Comment by djhoese** [comment]
The grid solver we were using (cassowary) is no longer maintained as far as I understand it. One of the developers (I think) of kiwisolver which is based on cassowary made a PR with the starting point for replacing cassowary. I merged that PR as it seemed to do everything needed. That 2100 PR is the only direct fix I've found that was needed. Our other tests have passed, but there is also a good chance that although we are running the code we aren't verifying the exact same visual output for all the tests.

**Review by sofroniewn — APPROVED** [review]
Ok, i'm fine with this as a fix. Thanks @alisterburt!! and thanks for the additional detail @djhoese! Once merged i will rerun all tests with 0.7, but i've been using for a while now and this is only problem i've seen yet - so things are looking very promising!!

**Pull request merged**
