### PR TITLE
Add pre commit steep for remove unused imports

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR adds a pre-commit check that removes unused imports. In the past, I needed to manually remove some unused imports that were left after previous refactors. 

It also cleans a few such imports in the current codebase. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
Ah yeah, I also stumbled on this before.

**Comment by goanpeca** [comment]
Pretty cool @Czaki does this hook also check for missing imports not declared in the setup.cfg/pyproject.toml files?

**Comment by Czaki** [comment]
I do not find information that it is possible to use `pycln` for this.

**Comment by goanpeca** [comment]
>I do not find information that it is possible to use pycln for this.

That would have been extra useful :).

Thanks for working on this! 🚀

**Review by goanpeca — APPROVED** [review]

**Comment by goanpeca** [comment]
@Czaki side note, we should get this inside the cookiecuter template!

**Comment by brisvag** [comment]
> Pretty cool @Czaki does this hook also check for missing imports not declared in the setup.cfg/pyproject.toml files?

not sure if that's possible in a rigorous way, given how names of packages and modules can be different (`scikit-image`/`skimage`).

**Pull request merged**
