### PR TITLE
Fix PR html stripping workflow

### LINKED ISSUE #6138: Removing comments from PR does not work
## 🐛 Bug
After merging it looks like the action for removing comments does not work. 

I will be happy to fast merge potential bugfix without the standard 24 hours as it needs to be merged to test.

### PR DESCRIPTION
**Pull request by Carreau**
Got the boolean condition on the PR description incorrect.

Closes #6138

### CODE REVIEW

**Comment by Czaki** [comment]
Did you know why there is 404? on action run?

**Comment by Carreau** [comment]
I think I have an idea, i'll investigate. At least we know the script runs
now.

**Comment by Carreau** [comment]
I pushed a commit that give write pr-write permission to the script. 
I think it will fail again as this PR modifies the actions script and I think GitHub will only give RO token when a PR modifies a workflow.

**Comment by Czaki** [comment]
Hm. I'm worried that even reopening do not trigger workflow. How did you think? It is caused by editing the trigger part of the workflow file? Should I merge and check how it behaves after merging?

**Comment by Carreau** [comment]
Yes, i think we should merge and iterate: I don't see many other ways.

**Comment by kne42** [comment]
I agree that merging and iterating would probably be best here

**Review by Czaki — APPROVED** [review]

**Comment by Czaki** [comment]
@Carreau it looks like trigger is wrong: https://github.com/napari/napari/actions/runs/5853233024

**Comment by Carreau** [comment]
> @Carreau it looks like trigger is wrong: https://github.com/napari/napari/actions/runs/5853233024

I think that's because it pulls the action from the base branch ? I've tryed to rebase your see it it triggers ok... Looking into it.

**Comment by Czaki** [comment]
This happens after I merge this PR.

**Comment by Carreau** [comment]
I'm looking into it. It seem that the env variable set on pull_request and pull_request_target are not the same, and GH docs is incorrect wrt to what is in those env varaibles.

**Pull request merged**
