### PR TITLE
Fix points layer coloring

### PR DESCRIPTION
**Pull request by liu-ziyang**
# Description
Address points layer coloring mismatch by adding dictionary support for mapping property and color

## Type of change
- New feature (non-breaking change which adds functionality)

# References
https://github.com/napari/napari/issues/1348

# How has this been tested?
Running code snippet 
```
import numpy as np
import napari
from skimage import data
from skimage.color import rgb2gray

with napari.gui_qt():
    # add the image
    viewer = napari.view_image(rgb2gray(data.astronaut()))

    points = np.array([[0, 0], [100, 0], [0, 100]])

    # property to colors that I want to achieve:
    color_map_expected = {1: 'green', 2: 'red', 3: 'blue'}

    # how to currently do it in napari
    properties = {'my_colors': [2, 6, 3]}
    viewer.add_points(points, face_color='my_colors', properties=properties, face_color_cycle=color_map_expected)
```

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Hi @ziyangczi I see this is still marked as draft, but it sounds like it might be ready for review, is that the case?

It also closes #1348 right? Is there a way to add a minimal test too?

Thanks!!

**Comment by liu-ziyang** [comment]
> Hi @ziyangczi I see this is still marked as draft, but it sounds like it might be ready for review, is that the case?
> 
> It also closes #1348 right? Is there a way to add a minimal test too?
> 
> Thanks!!

Sorry was out of office, yeah I am going to mark it ready for review, gonna try to add a test today

**Review by sofroniewn — APPROVED** [review]
@ziyangczi this looks great, thanks for the test. I have confirmed this works and closes #1348. @constantinpape feel free to check if you like. I will merge tomorrow.

Before this PR merges the above example gives
```
UserWarning: The provided face_color_cycle parameter contained illegal values, resetting all face_color_cycle values to white.
  f"The provided {elem_name} parameter contained illegal values, "
```
and the points appear all white. After this PR the warning disappears and the points appear with the expected colors.

Screen Shot 2020-09-21 at 12 39 12 PM

**Comment by psobolewskiPhD** [comment]
> After this PR the warning disappears and the points appear with the expected colors.

In that screenshot and what I'm seeing with 0.4.18 and main, the first point is white and not green...

**Pull request merged**
