### PR TITLE
Set focus for current active QtViewer base on mouse move

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR set focus on QtViewer over which is mouse. This is useful for examples like in #4665 where if more than one Viewer in one Window. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by goanpeca** [comment]
Is this related to having the status bar update on move depending on the viewer or?

How common is this pattern, in terms of having the focus change ion just moving the mouse on top of it. It might be useful, but seems like a not very common pattern based on other apps with multiple viewers I have used, in the past 🤔

**Comment by Czaki** [comment]
The core problem why I create this PR is that napari uses vispy for process shortcuts. 

Even without this PR mouse events are processed for viewer for which mouse is over. But shortcuts are processed for last clicked viewer.

**Comment by tlambert03** [comment]
yeah, this fix feels a bit aggressive to me.  It doesn't feel like it would be without potential unexpected (and perhaps worse) side effects

**Comment by Czaki** [comment]
The only problem that I see is that this change may steal focus from console when move mouse over canvas.

Otherwise it should have impact only if more than one viewer is in same active window. Or I miss something?

**Comment by tlambert03** [comment]
> from console when move mouse over canvas.

wouldn't it steal it from literally any other widget?  or does the focus only go with the active widget?

(but even stealing from the console feels unfortunate)

**Comment by Czaki** [comment]
Close as have too many side effects.

**Pull request closed without merging**
