### PR TITLE
[Maint] Update version_denylist.txt to block mpl 3.9.1 on windows

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# References and relevant issues
Windows tests are failing due to matplotlib 3.9.1: https://github.com/matplotlib/matplotlib/issues/28551
e.g.:
https://github.com/napari/napari/actions/runs/10232235699/job/28309138502

Edit: the wheels have been pulled from pypi so now tests fail because of build issues.

# Description
Adds mpl 3.9.1 on windows to the deny list for our test constraints.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by Czaki** [comment]
How is it possible that it pass when merging constraints files?  Did they yank some release?

**Comment by psobolewskiPhD** [comment]
My understanding from the issue is that it's windows 3.9.1 wheels specifically that have a bug, which has affected other downstream projects. So they pulled those wheels, which is now affecting us.
I assume our CI didn't hit the original bug.

**Comment by psobolewskiPhD** [comment]
This looks in the clear now @Czaki 
The pyside segfaults are in plugin-related code:
https://github.com/napari/napari/actions/runs/10232738966/job/28312343785?pr=7154#step:13:347

Looks like my constraint update included both the new manager and new npe2, so could be something in one of those?

**Review by Czaki — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
@Czaki should we just merge this, bypassing 24 hrs, to fix CI and make it easier to debug the issue with pyside?

**Comment by Czaki** [comment]
Fell free to merge imediatelly.

**Comment by tacaswell** [comment]
The 3.9.1 wheels on windows would, depending on import order, cause segfaults, see https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266699619.

We deleted the bad wheels to avoid segfaults (which seemed like a good idea) but failed to anticipate that this would cause downstream projects to start trying to build mpl from source instead of pulling the 3.9.0 wheel.

**Comment by psobolewskiPhD** [comment]
Thanks for reaching out! And no worries, shit happens--no need to apologize.
❤️

**Pull request merged**
