### PR TITLE
Add stateful StyleEncoding tests

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description
The main contribution of this PR is adding some test coverage for the style encoding implementation types: `ConstantStyleEncoding`, `ManualStyleEncoding`, and `DerivedStyleEncoding`. There were two movitations behind this.

1. `DerivedStyleEncoding` was broken on main.
2. By testing the stateful private part of `StyleEncoding` in `test_style_encoding` the public `__call__` in dtype-specific encodings like `StringEncoding`, we can achieve good coverage without combinatorial growth of the number of tests. We'll also test some of this behavior through more integrative tests in `test_text_manager`, `test_points`, and `test_shapes`, but it will be hard to be exhaustive there.

I also made some changes/simplifications to the `StyleEncoding` protocol.

a. I made `_values` a property instead of a method. Given what it does/represents that seems more natural.
b. Given that `_values` implies that the cached values are immediately ready for use (e.g. without requiring `features`), I changed the signature of `_update` to update all the cached values, removed the `indices` parameter, and do not return the possibly indexed cached values anymore. The original intent was that this method would allow lazy generation/caching  of values, but the presence/expectation of `_values` does not play well with that.

So now you'd expect to do something like the following.

```python
features = pd.DataFrame({
    'class': ['dog', 'cat', 'dog'],
    'conf': [0.5, 0.9, 0.1],
})
encoding = FormatStringEncoding(format='{class}: {conf:.2f}')
encoding._update(features)
assert encoding._values[1] == 'cat: 0.90'
```

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

The things being tested here are not public yet, so no breaking changes here.

# References
Related to #3992 

# How has this been tested?
- [ ] all the new tests `test_style_encoding.py` pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
thanks!  helpful to see the tests

**Comment by Carreau** [comment]
Tried to rebase to fix the tests (lfs), but apparently I can't push, I guess you haven't checked "allow edits from maintainers" ?

**Comment by andy-sweet** [comment]
> Tried to rebase to fix the tests (lfs), but apparently I can't push, I guess you haven't checked "allow edits from maintainers" ?

It is checked on the PR (I guess that's by default?). I merged `main` into this branch, but let me know if I need to rebase instead. Or feel free to do it if you can.

**Comment by Carreau** [comment]
> It is checked on the PR (I guess that's by default?)

Ok, maybe that was a problem on my end, github had issue today maybe I was just unlucky ?

**Comment by sofroniewn** [comment]
Looks like this is now all ready to go - i will merge! thanks!!

**Pull request merged**
