### PR TITLE
Fix circular import in _vispy module

### PR DESCRIPTION
**Pull request by Czaki**
# Description

I found that importing `API_NAME` from `napari._qt` was obsolete to get a warning, and it was an artifact. from the phase before, I discovered that import is caused by magicgui importing.

So revert this one line solves circular import.  

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

alternative for #5271

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Hmm, I'm getting errors when
I do `pytest napari/_vispy/_tests/`
If I go back before the problem commit:
`git checkout b445d2ff0d54505ba9d7df64f915c9a44e574ebc`
```
================== 100 passed, 7 skipped, 1 warning in 10.88s ==================
```
On `main` I get the circular imports:
```
E   ImportError: cannot import name 'VispyAxesOverlay' from partially initialized module 'napari._vispy' (most likely due to a circular import) (/Users/piotrsobolewski/Dev/napari/napari/_vispy/__init__.py)
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 5 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
============================== 5 errors in 0.57s ===============================
```
With this `gh pr checkout 5276`:
```
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 5 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
=============== 2 failed, 7 passed, 1 warning, 3 errors in 1.54s ===============
```

The errors:
```
        _do_not_inline_below = len(QtViewer._instances)
        # do not inline to avoid pytest trying to compute repr of expression.
        # it fails if C++ object gone but not Python object.
>       assert _do_not_inline_below == 0
E       AssertionError
```
```
>       assert _do_not_inline_below == 0, (
            "Some instance of QtViewer is not properly cleaned in one of previous test. For easier debug one may "
            f"use {_SAVE_GRAPH_OPNAME} flag for pytest to get graph of leaked objects. If you use qtbot (from pytest-qt)"
            " to clean Qt objects after test you may need to switch to manual clean using "
            "`deleteLater()` and `qtbot.wait(50)` later."
        )
E       AssertionError: Some instance of QtViewer is not properly cleaned in one of previous test. For easier debug one may use --save-leaked-object-graph flag for pytest to get graph of leaked objects. If you use qtbot (from pytest-qt) to clean Qt objects after test you may need to switch to manual clean using `deleteLater()` and `qtbot.wait(50)` later.

napari/utils/_testsupport.py:167: AssertionError
```
The fails:
```
make_napari_viewer = <function make_napari_viewer.<locals>.actual_factory at 0x14e7ea320>

    def test_image_rendering(make_napari_viewer):
        """Test 3D image with different rendering."""
>       viewer = make_napari_viewer()

napari/_vispy/_tests/test_image_rendering.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
napari/utils/_testsupport.py:201: in actual_factory
    viewer = ViewerClass(*model_args, **model_kwargs)
napari/viewer.py:67: in __init__
    self._window = Window(self, show=show)
napari/_qt/qt_main_window.py:476: in __init__
    self._qt_window = _QtMainWindow(viewer, self)
napari/_qt/qt_main_window.py:98: in __init__
    self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
napari/_qt/qt_viewer.py:288: in __init__
    self._bind_shortcuts()
napari/_qt/qt_viewer.py:397: in _bind_shortcuts
    action_manager.bind_shortcut(action, shortcut)
napari/utils/action_manager.py:265: in bind_shortcut
    self._emit_shortcut_change(name, shortcut)
napari/utils/action_manager.py:311: in _emit_shortcut_change
    tt = self._build_tooltip(name) if name in self._actions else ''
napari/utils/action_manager.py:320: in _build_tooltip
    shorts = jstr.join(f"{Shortcut(s)}" for s in self._shortcuts[name])
napari/utils/action_manager.py:320: in <genexpr>
    shorts = jstr.join(f"{Shortcut(s)}" for s in self._shortcuts[name])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <napari.utils.interactions.Shortcut object at 0x151f92500>
shortcut = KeyBinding(parts=[SimpleKeyBinding(ctrl=False, shift=False, alt=False, meta=False, key=<KeyCode.LeftArrow: 66>)])

    def __init__(self, shortcut: KeyBindingLike):
        """Parameters
        ----------
        shortcut : keybinding-like
            shortcut to format
        """
        error_msg = trans._(
            "{shortcut} does not seem to be a valid shortcut Key.",
            shortcut=shortcut,
        )
        error = False
    
        try:
            self._kb = coerce_keybinding(shortcut)
        except ValueError:
            error = True
        else:
            for part in self._kb.parts:
                shortcut_key = str(part.key)
                if len(shortcut_key) > 1 and shortcut_key not in KEY_SYMBOLS:
                    error = True
    
        if error:
>           warnings.warn(error_msg, UserWarning, stacklevel=2)
E           UserWarning: LeftArrow does not seem to be a valid shortcut Key.

napari/utils/interactions.py:307: UserWarning
```
That seems related to https://github.com/napari/napari/commit/6ba16c1af85ebb395633f6f18924599822a961e0 perhaps and unmasked by the circular imports fix?

Full pytest output:
<details>
```
============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
PyQt5 5.15.7 -- Qt runtime 5.15.6 -- Qt compiled 5.15.4
rootdir: /Users/piotrsobolewski/Dev/napari, configfile: pyproject.toml
plugins: hypothesis-6.54.6, qt-4.1.0, napari-plugin-engine-0.2.0, npe2-0.6.2.dev9+gafb0bf6, cov-4.0.0, napari-0.4.17rc4.dev27+g6bff1e66
collected 107 items                                                            

napari/_vispy/_tests/test_image_rendering.py FEE.                        [  2%]
napari/_vispy/_tests/test_utils.py ......FE

==================================== ERRORS ====================================
__________________ ERROR at teardown of test_image_rendering ___________________

qtbot = <pytestqt.qtbot.QtBot object at 0x14e775870>
request = <SubRequest 'make_napari_viewer' for <Function test_image_rendering>>
napari_plugin_manager = <napari.plugins._plugin_manager.NapariPluginManager object at 0x14e775930>

    @pytest.fixture
    def make_napari_viewer(
        qtbot, request: 'FixtureRequest', napari_plugin_manager
    ):
        """A fixture function that creates a napari viewer for use in testing.
    
        Use this fixture as a function in your tests:
    
            viewer = make_napari_viewer()
    
        It accepts all the same arguments as napari.Viewer, plus the following
        test-related paramaters:
    
        ViewerClass : Type[napari.Viewer], optional
            Override the viewer class being used.  By default, will
            use napari.viewer.Viewer
        strict_qt : bool or str, optional
            If True, a check will be performed after test cleanup to make sure that
            no top level widgets were created and *not* cleaned up during the
            test.  If the string "raise" is provided, an AssertionError will be
            raised.  Otherwise a warning is emitted.
            By default, this is False unless the test is being performed within
            the napari package.
            This can be made globally true by setting the 'NAPARI_STRICT_QT'
            environment variable.
        block_plugin_discovery : bool, optional
            Block discovery of non-builtin plugins.  Note: plugins can still be
            manually registered by using the 'napari_plugin_manager' fixture and
            the `napari_plugin_manager.register()` method. By default, True.
    
        Examples
        --------
        >>> def test_adding_shapes(make_napari_viewer):
        ...     viewer = make_napari_viewer()
        ...     viewer.add_shapes()
        ...     assert len(viewer.layers) == 1
    
        >>> def test_something_with_plugins(make_napari_viewer):
        ...     viewer = make_napari_viewer(block_plugin_discovery=False)
    
        >>> def test_something_with_strict_qt_tests(make_napari_viewer):
        ...     viewer = make_napari_viewer(strict_qt=True)
        """
        from qtpy.QtWidgets import QApplication
    
        from napari import Viewer
        from napari._qt.qt_viewer import QtViewer
        from napari.settings import get_settings
    
        global GCPASS
        GCPASS += 1
    
        if GCPASS % 50 == 0:
            gc.collect()
        else:
            gc.collect(1)
    
        _do_not_inline_below = len(QtViewer._instances)
        # # do not inline to avoid pytest trying to compute repr of expression.
        # # it fails if C++ object gone but not Python object.
        if request.config.getoption(_SAVE_GRAPH_OPNAME):
            fail_obj_graph(QtViewer)
        QtViewer._instances.clear()
        assert _do_not_inline_below == 0, (
            "Some instance of QtViewer is not properly cleaned in one of previous test. For easier debug one may "
            f"use {_SAVE_GRAPH_OPNAME} flag for pytest to get graph of leaked objects. If you use qtbot (from pytest-qt)"
            " to clean Qt objects after test you may need to switch to manual clean using "
            "`deleteLater()` and `qtbot.wait(50)` later."
        )
    
        settings = get_settings()
        settings.reset()
    
        viewers: WeakSet[Viewer] = WeakSet()
    
        # may be overridden by using `make_napari_viewer(strict=True)`
        _strict = False
    
        initial = QApplication.topLevelWidgets()
        prior_exception = getattr(sys, 'last_value', None)
        is_internal_test = request.module.__name__.startswith("napari.")
    
        def actual_factory(
            *model_args,
            ViewerClass=Viewer,
            strict_qt=is_internal_test or os.getenv("NAPARI_STRICT_QT"),
            block_plugin_discovery=True,
            **model_kwargs,
        ):
            nonlocal _strict
            _strict = strict_qt
    
            if not block_plugin_discovery:
                napari_plugin_manager.discovery_blocker.stop()
    
            should_show = request.config.getoption("--show-napari-viewer")
            model_kwargs['show'] = model_kwargs.pop('show', should_show)
            viewer = ViewerClass(*model_args, **model_kwargs)
            viewers.add(viewer)
    
            return viewer
    
        yield actual_factory
    
        # Some tests might have the viewer closed, so this call will not be able
        # to access the window.
        with suppress(AttributeError):
            get_settings().reset()
    
        # close viewers, but don't saving window settings while closing
        for viewer in viewers:
            if hasattr(viewer.window, '_qt_window'):
                with patch.object(
                    viewer.window._qt_window, '_save_current_window_settings'
                ):
                    viewer.close()
            else:
                viewer.close()
    
        if GCPASS % 50 == 0 or len(QtViewer._instances):
            gc.collect()
        else:
            gc.collect(1)
    
        if request.config.getoption(_SAVE_GRAPH_OPNAME):
            fail_obj_graph(QtViewer)
    
        _do_not_inline_below = len(QtViewer._instances)
        # do not inline to avoid pytest trying to compute repr of expression.
        # it fails if C++ object gone but not Python object.
>       assert _do_not_inline_below == 0
E       AssertionError

napari/utils/_testsupport.py:234: AssertionError
________________ ERROR at setup of test_visibility_consistency _________________

qtbot = <pytestqt.qtbot.QtBot object at 0x14e792380>
request = <SubRequest 'make_napari_viewer' for <Function test_visibility_consistency>>
napari_plugin_manager = <napari.plugins._plugin_manager.NapariPluginManager object at 0x14e792230>

    @pytest.fixture
    def make_napari_viewer(
        qtbot, request: 'FixtureRequest', napari_plugin_manager
    ):
        """A fixture function that creates a napari viewer for use in testing.
    
        Use this fixture as a function in your tests:
    
            viewer = make_napari_viewer()
    
        It accepts all the same arguments as napari.Viewer, plus the following
        test-related paramaters:
    
        ViewerClass : Type[napari.Viewer], optional
            Override the viewer class being used.  By default, will
            use napari.viewer.Viewer
        strict_qt : bool or str, optional
            If True, a check will be performed after test cleanup to make sure that
            no top level widgets were created and *not* cleaned up during the
            test.  If the string "raise" is provided, an AssertionError will be
            raised.  Otherwise a warning is emitted.
            By default, this is False unless the test is being performed within
            the napari package.
            This can be made globally true by setting the 'NAPARI_STRICT_QT'
            environment variable.
        block_plugin_discovery : bool, optional
            Block discovery of non-builtin plugins.  Note: plugins can still be
            manually registered by using the 'napari_plugin_manager' fixture and
            the `napari_plugin_manager.register()` method. By default, True.
    
        Examples
        --------
        >>> def test_adding_shapes(make_napari_viewer):
        ...     viewer = make_napari_viewer()
        ...     viewer.add_shapes()
        ...     assert len(viewer.layers) == 1
    
        >>> def test_something_with_plugins(make_napari_viewer):
        ...     viewer = make_napari_viewer(block_plugin_discovery=False)
    
        >>> def test_something_with_strict_qt_tests(make_napari_viewer):
        ...     viewer = make_napari_viewer(strict_qt=True)
        """
        from qtpy.QtWidgets import QApplication
    
        from napari import Viewer
        from napari._qt.qt_viewer import QtViewer
        from napari.settings import get_settings
    
        global GCPASS
        GCPASS += 1
    
        if GCPASS % 50 == 0:
            gc.collect()
        else:
            gc.collect(1)
    
        _do_not_inline_below = len(QtViewer._instances)
        # # do not inline to avoid pytest trying to compute repr of expression.
        # # it fails if C++ object gone but not Python object.
        if request.config.getoption(_SAVE_GRAPH_OPNAME):
            fail_obj_graph(QtViewer)
        QtViewer._instances.clear()
>       assert _do_not_inline_below == 0, (
            "Some instance of QtViewer is not properly cleaned in one of previous test. For easier debug one may "
            f"use {_SAVE_GRAPH_OPNAME} flag for pytest to get graph of leaked objects. If you use qtbot (from pytest-qt)"
            " to clean Qt objects after test you may need to switch to manual clean using "
            "`deleteLater()` and `qtbot.wait(50)` later."
        )
E       AssertionError: Some instance of QtViewer is not properly cleaned in one of previous test. For easier debug one may use --save-leaked-object-graph flag for pytest to get graph of leaked objects. If you use qtbot (from pytest-qt) to clean Qt objects after test you may need to switch to manual clean using `deleteLater()` and `qtbot.wait(50)` later.

napari/utils/_testsupport.py:167: AssertionError
______ ERROR at teardown of test_get_view_direction_in_scene_coordinates _______

qtbot = <pytestqt.qtbot.QtBot object at 0x14e8383a0>
request = <SubRequest 'make_napari_viewer' for <Function test_get_view_direction_in_scene_coordinates>>
napari_plugin_manager = <napari.plugins._plugin_manager.NapariPluginManager object at 0x14e83b970>

    @pytest.fixture
    def make_napari_viewer(
        qtbot, request: 'FixtureRequest', napari_plugin_manager
    ):
        """A fixture function that creates a napari viewer for use in testing.
    
        Use this fixture as a function in your tests:
    
            viewer = make_napari_viewer()
    
        It accepts all the same arguments as napari.Viewer, plus the following
        test-related paramaters:
    
        ViewerClass : Type[napari.Viewer], optional
            Override the viewer class being used.  By default, will
            use napari.viewer.Viewer
        strict_qt : bool or str, optional
            If True, a check will be performed after test cleanup to make sure that
            no top level widgets were created and *not* cleaned up during the
            test.  If the string "raise" is provided, an AssertionError will be
            raised.  Otherwise a warning is emitted.
            By default, this is False unless the test is being performed within
            the napari package.
            This can be made globally true by setting the 'NAPARI_STRICT_QT'
            environment variable.
        block_plugin_discovery : bool, optional
            Block discovery of non-builtin plugins.  Note: plugins can still be
            manually registered by using the 'napari_plugin_manager' fixture and
            the `napari_plugin_manager.register()` method. By default, True.
    
        Examples
        --------
        >>> def test_adding_shapes(make_napari_viewer):
        ...     viewer = make_napari_viewer()
        ...     viewer.add_shapes()
        ...     assert len(viewer.layers) == 1
    
        >>> def test_something_with_plugins(make_napari_viewer):
        ...     viewer = make_napari_viewer(block_plugin_discovery=False)
    
        >>> def test_something_with_strict_qt_tests(make_napari_viewer):
        ...     viewer = make_napari_viewer(strict_qt=True)
        """
        from qtpy.QtWidgets import QApplication
    
        from napari import Viewer
        from napari._qt.qt_viewer import QtViewer
        from napari.settings import get_settings
    
        global GCPASS
        GCPASS += 1
    
        if GCPASS % 50 == 0:
            gc.collect()
        else:
            gc.collect(1)
    
        _do_not_inline_below = len(QtViewer._instances)
        # # do not inline to avoid pytest trying to compute repr of expression.
        # # it fails if C++ object gone but not Python object.
        if request.config.getoption(_SAVE_GRAPH_OPNAME):
            fail_obj_graph(QtViewer)
        QtViewer._instances.clear()
        assert _do_not_inline_below == 0, (
            "Some instance of QtViewer is not properly cleaned in one of previous test. For easier debug one may "
            f"use {_SAVE_GRAPH_OPNAME} flag for pytest to get graph of leaked objects. If you use qtbot (from pytest-qt)"
            " to clean Qt objects after test you may need to switch to manual clean using "
            "`deleteLater()` and `qtbot.wait(50)` later."
        )
    
        settings = get_settings()
        settings.reset()
    
        viewers: WeakSet[Viewer] = WeakSet()
    
        # may be overridden by using `make_napari_viewer(strict=True)`
        _strict = False
    
        initial = QApplication.topLevelWidgets()
        prior_exception = getattr(sys, 'last_value', None)
        is_internal_test = request.module.__name__.startswith("napari.")
    
        def actual_factory(
            *model_args,
            ViewerClass=Viewer,
            strict_qt=is_internal_test or os.getenv("NAPARI_STRICT_QT"),
            block_plugin_discovery=True,
            **model_kwargs,
        ):
            nonlocal _strict
            _strict = strict_qt
    
            if not block_plugin_discovery:
                napari_plugin_manager.discovery_blocker.stop()
    
            should_show = request.config.getoption("--show-napari-viewer")
            model_kwargs['show'] = model_kwargs.pop('show', should_show)
            viewer = ViewerClass(*model_args, **model_kwargs)
            viewers.add(viewer)
    
            return viewer
    
        yield actual_factory
    
        # Some tests might have the viewer closed, so this call will not be able
        # to access the window.
        with suppress(AttributeError):
            get_settings().reset()
    
        # close viewers, but don't saving window settings while closing
        for viewer in viewers:
            if hasattr(viewer.window, '_qt_window'):
                with patch.object(
                    viewer.window._qt_window, '_save_current_window_settings'
                ):
                    viewer.close()
            else:
                viewer.close()
    
        if GCPASS % 50 == 0 or len(QtViewer._instances):
            gc.collect()
        else:
            gc.collect(1)
    
        if request.config.getoption(_SAVE_GRAPH_OPNAME):
            fail_obj_graph(QtViewer)
    
        _do_not_inline_below = len(QtViewer._instances)
        # do not inline to avoid pytest trying to compute repr of expression.
        # it fails if C++ object gone but not Python object.
>       assert _do_not_inline_below == 0
E       AssertionError

napari/utils/_testsupport.py:234: AssertionError
=================================== FAILURES ===================================
_____________________________ test_image_rendering _____________________________

make_napari_viewer = <function make_napari_viewer.<locals>.actual_factory at 0x14e7ea320>

    def test_image_rendering(make_napari_viewer):
        """Test 3D image with different rendering."""
>       viewer = make_napari_viewer()

napari/_vispy/_tests/test_image_rendering.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
napari/utils/_testsupport.py:201: in actual_factory
    viewer = ViewerClass(*model_args, **model_kwargs)
napari/viewer.py:67: in __init__
    self._window = Window(self, show=show)
napari/_qt/qt_main_window.py:476: in __init__
    self._qt_window = _QtMainWindow(viewer, self)
napari/_qt/qt_main_window.py:98: in __init__
    self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
napari/_qt/qt_viewer.py:288: in __init__
    self._bind_shortcuts()
napari/_qt/qt_viewer.py:397: in _bind_shortcuts
    action_manager.bind_shortcut(action, shortcut)
napari/utils/action_manager.py:265: in bind_shortcut
    self._emit_shortcut_change(name, shortcut)
napari/utils/action_manager.py:311: in _emit_shortcut_change
    tt = self._build_tooltip(name) if name in self._actions else ''
napari/utils/action_manager.py:320: in _build_tooltip
    shorts = jstr.join(f"{Shortcut(s)}" for s in self._shortcuts[name])
napari/utils/action_manager.py:320: in <genexpr>
    shorts = jstr.join(f"{Shortcut(s)}" for s in self._shortcuts[name])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <napari.utils.interactions.Shortcut object at 0x151f92500>
shortcut = KeyBinding(parts=[SimpleKeyBinding(ctrl=False, shift=False, alt=False, meta=False, key=<KeyCode.LeftArrow: 66>)])

    def __init__(self, shortcut: KeyBindingLike):
        """Parameters
        ----------
        shortcut : keybinding-like
            shortcut to format
        """
        error_msg = trans._(
            "{shortcut} does not seem to be a valid shortcut Key.",
            shortcut=shortcut,
        )
        error = False
    
        try:
            self._kb = coerce_keybinding(shortcut)
        except ValueError:
            error = True
        else:
            for part in self._kb.parts:
                shortcut_key = str(part.key)
                if len(shortcut_key) > 1 and shortcut_key not in KEY_SYMBOLS:
                    error = True
    
        if error:
>           warnings.warn(error_msg, UserWarning, stacklevel=2)
E           UserWarning: LeftArrow does not seem to be a valid shortcut Key.

napari/utils/interactions.py:307: UserWarning
_________________ test_get_view_direction_in_scene_coordinates _________________

make_napari_viewer = <function make_napari_viewer.<locals>.actual_factory at 0x1531cb9a0>

    def test_get_view_direction_in_scene_coordinates(make_napari_viewer):
>       viewer = make_napari_viewer()

napari/_vispy/_tests/test_utils.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
napari/utils/_testsupport.py:201: in actual_factory
    viewer = ViewerClass(*model_args, **model_kwargs)
napari/viewer.py:67: in __init__
    self._window = Window(self, show=show)
napari/_qt/qt_main_window.py:476: in __init__
    self._qt_window = _QtMainWindow(viewer, self)
napari/_qt/qt_main_window.py:98: in __init__
    self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
napari/_qt/qt_viewer.py:288: in __init__
    self._bind_shortcuts()
napari/_qt/qt_viewer.py:397: in _bind_shortcuts
    action_manager.bind_shortcut(action, shortcut)
napari/utils/action_manager.py:265: in bind_shortcut
    self._emit_shortcut_change(name, shortcut)
napari/utils/action_manager.py:311: in _emit_shortcut_change
    tt = self._build_tooltip(name) if name in self._actions else ''
napari/utils/action_manager.py:320: in _build_tooltip
    shorts = jstr.join(f"{Shortcut(s)}" for s in self._shortcuts[name])
napari/utils/action_manager.py:320: in <genexpr>
    shorts = jstr.join(f"{Shortcut(s)}" for s in self._shortcuts[name])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <napari.utils.interactions.Shortcut object at 0x14e838100>
shortcut = KeyBinding(parts=[SimpleKeyBinding(ctrl=False, shift=False, alt=False, meta=False, key=<KeyCode.LeftArrow: 66>)])

    def __init__(self, shortcut: KeyBindingLike):
        """Parameters
        ----------
        shortcut : keybinding-like
            shortcut to format
        """
        error_msg = trans._(
            "{shortcut} does not seem to be a valid shortcut Key.",
            shortcut=shortcut,
        )
        error = False
    
        try:
            self._kb = coerce_keybinding(shortcut)
        except ValueError:
            error = True
        else:
            for part in self._kb.parts:
                shortcut_key = str(part.key)
                if len(shortcut_key) > 1 and shortcut_key not in KEY_SYMBOLS:
                    error = True
    
        if error:
>           warnings.warn(error_msg, UserWarning, stacklevel=2)
E           UserWarning: LeftArrow does not seem to be a valid shortcut Key.

napari/utils/interactions.py:307: UserWarning
=============================== warnings summary ===============================
napari/_vispy/_tests/test_image_rendering.py::test_image_rendering
  /Users/piotrsobolewski/Dev/npe2/npe2/_pytest_plugin.py:17: UserWarning: TestPluginManager is unable to discover plugins. Please use `tmp_plugin()` to add a plugin to this plugin manager.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================= slowest 10 durations =============================
0.25s call     napari/_vispy/_tests/test_image_rendering.py::test_image_rendering
0.25s setup    napari/_vispy/_tests/test_image_rendering.py::test_image_rendering
0.17s teardown napari/_vispy/_tests/test_image_rendering.py::test_image_rendering
0.10s teardown napari/_vispy/_tests/test_utils.py::test_get_view_direction_in_scene_coordinates
0.05s call     napari/_vispy/_tests/test_utils.py::test_get_view_direction_in_scene_coordinates
0.04s setup    napari/_vispy/_tests/test_utils.py::test_get_view_direction_in_scene_coordinates
0.03s teardown napari/_vispy/_tests/test_image_rendering.py::test_clipping_planes_dims
0.03s teardown napari/_vispy/_tests/test_utils.py::test_quaternion2euler[angles5-False]
0.02s teardown napari/_vispy/_tests/test_utils.py::test_quaternion2euler[angles1-True]
0.02s teardown napari/_vispy/_tests/test_utils.py::test_quaternion2euler[angles4-False]
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 5 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
=============== 2 failed, 7 passed, 1 warning, 3 errors in 1.54s ===============
```
</details>

**Comment by psobolewskiPhD** [comment]
Yup, if I roll back to d5ffbaccfe648e0ee0583a1a949e9c3392846388 (before the app-model keybinds commit) and apply your fix tests pass:
```
================== 100 passed, 7 skipped, 1 warning in 10.52s ==================
```
But if I checkout 6ba16c1af85ebb395633f6f18924599822a961e0 and apply your fix:
```
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 5 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
=============== 2 failed, 7 passed, 1 warning, 3 errors in 1.64s ===============
```
It's the same as above. So 6ba16c1af85ebb395633f6f18924599822a961e0 has introduced an issue on macOS 12.6 (python 3.10, pyqt5, arm64)

**Comment by Czaki** [comment]
> It's the same as above. So [6ba16c1](https://github.com/napari/napari/commit/6ba16c1af85ebb395633f6f18924599822a961e0) has introduced an issue on macOS 12.6 (python 3.10, pyqt5, arm64)

No it just bumps `app-model` minimal version . Execute `pip install -e .` and it will start working.

**Comment by psobolewskiPhD** [comment]
Bah, of course you're right. In my defense, when I go to:
https://github.com/napari/napari/commit/6ba16c1af85ebb395633f6f18924599822a961e0
the left panel of files doesn't scroll down further, so I assumed it was all the changes and I didn't see the setup change.
Need to scroll the other frame and then can scroll the side panel.

**Comment by psobolewskiPhD** [comment]
@Czaki you have #5021 in the OP, but that's an unrelated PR.
I don't think there's an issue for the circular imports error, just the zulip:
https://napari.zulipchat.com/#narrow/stream/215289-release/topic/0.2E4.2E17/near/306229665

**Comment by Czaki** [comment]
> I don't think there's an issue for the circular imports error, just the zulip:

True. My bad.

**Review by Carreau — APPROVED** [review]

**Review by andy-sweet — APPROVED** [review]
Thanks for resolving this @Czaki ! I'll merge after 24 hours unless anyone objects.

I'll also create an issue in the napari repo for checking/finding potential circular imports (rather than relying on import order). Ideally, this should run as an action. We may be able to combine with traversing the public API to look for breaking changes too!

**Comment by Czaki** [comment]
Pylint has some utilities for detect circular imports. But requires proper configuration as napari break many pylint rules.

**Comment by andy-sweet** [comment]
> I'll also create an issue in the napari repo for checking/finding potential circular imports (rather than relying on import order).

Added #5289

**Pull request merged**
