### PR TITLE
Restore old breakpointhook after console import in tests fixture

### LINKED ISSUE #6432: can no longer use breakpoints in napari qt tests
### 🐛 Bug Report

Was just trying to debug something for someone and noticed that it's no longer possible to use breakpoints inside of tests in the napari repo after #5890

### 💡 Steps to Reproduce

 
```python
def test_thing(qapp):
    breakpoint()
```

nothing happens... but if you comment out the `mock_console` fixture added here, you can debug again

https://github.com/napari/napari/blob/c61e9230bd01cbb2f7ce3fe69d13e4b045ba2d06/napari/conftest.py#L772-L780

### 💡 Expected Behavior

_No response_

### 🌎 Environment

❯ napari --info
napari: 0.5.0a2.dev427+gb664fa06.d20231105
Platform: macOS-13.6.1-x86_64-i386-64bit
System: MacOS 13.6.1
Python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:20) [Clang 16.0.6 ]
Qt: 6.6.0
PyQt6:
NumPy: 1.26.1
SciPy: 1.11.3
Dask: 2023.10.1
VisPy: 0.14.1
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.3.dev9+g0717900
npe2: 0.7.3

### 💡 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues

closes #6432
 
# Description

I have followed Talley's suggestion and just prevented the creation of a console using monkeypatch.

### CODE REVIEW

**Comment by Czaki** [comment]
@tlambert03 It works on my computer but it will be nice if you could test.

I am thinking about adding the same lines in QtViewer.console property. I do not understand why ipykernel has it in default dependencies as the code looks ready to work without debugpy installed.

**Review by Carreau — APPROVED** [review]

**Comment by tlambert03** [comment]
> @tlambert03 It works on my computer but it will be nice if you could test.

yep works for me, breakpoints are back

**Review by brisvag — APPROVED** [review]
LGTM.

EDIT: This, together with `napari-console==v0.0.9` also solves my long-existing issue of `breakpoint()` not working if the qt viewer was involved! Awesome :D

**Comment by Czaki** [comment]
waiting on merge of #6443

**Pull request merged**
