### PR TITLE
Fix ability to test released distributions

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
following the conversation on zulip.  This PR fixes tests in our released distributions as follows:

1. moves everything in `napari.plugin.tests` to `napari.plugins._tests`
2. adds `recursive-include napari/plugins/_tests/fixtures` to `MANIFEST`
3. removes the top level `conftest.py` file and moves the fixture that was in `_tests/infra/viewer.py` into `_qt/_tests/conftest.py` (`_qt` is currently the only subpackage that uses the `viewermodel_factory` fixture... so we don't need a global `conftest.py` yet)

## how i tested
i ran `python setup.py sdist`, then `cd`ed into newly created dist folder, confirmed that all the required files are included, and ran pytest successfully within the sdist folder.

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
This looks good to me, but can you add a line to the `0.2.12` release note with (1002) in there too before merge @tlambert03

**Comment by sofroniewn** [comment]
It also looks like this change might fix our linux 3.7 test

**Review by jni — APPROVED** [review]
Thank you @tlambert03! Installing that sdist in a fresh env would be a further useful test! But this sounds good to me

**Comment by tlambert03** [comment]
> It also looks like this change might fix our linux 3.7 test

well that would be amazing.  I'll believe it when i (continue to) see it :)

> can you add a line to the 0.2.12 release note with (1002) in there too before merge @tlambert03

sure.  added to support

**Comment by tlambert03** [comment]
just tested the sdist locally in a clean env and everything passed

**Pull request merged**
