### PR TITLE
PR: Add parent parameter to about dialog to correctly inherit and apply theme

### LINKED ISSUE #2301: The Help 'napari info' dialog box does not match the napari theme
## 🐛 Bug

Somewhere between napari release 0.4.5 and the current master branch, we've lost the theme that should be applied to the `napari info` dialog box from the Help menu.

On napari 0.4.5 I don't see this issue, the theme of the napari info dialog box matches the rest of napari.

## To Reproduce

1. Launch napari from the master branch
2. Click the `Help` menu, then the `napari info` menu item
3. Observe the colour of the dialog box, it doesn't match the rest of the 'dark' theme the way it used to do.

If you follow the same steps, but using a napari 0.4.5 installation, we don't see this issue.

I tried explicitly setting `viewer.theme = 'dark'`, in case napari was remembering a setting from last time or something, but no luck there.

## Expected behavior

I expected the napari info dialog box to match the overall 'look' of the rest of napari. I also expect this will change depending on what theme is currently set in napari.

The 'keybindings' dialog box doesn't have the same weird behaviour.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.4.6.dev22+g02019b9
Platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.10
System: Ubuntu 20.04.2 LTS
Python: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.2
SciPy: 1.5.2
Dask: 2.30.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- svg: 0.1.4
- ```
 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

I had seen this yesterday when looking at the demos, so I figured I would fix it.

Fixes #2301

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Screen Shot 2021-02-24 at 10 09 37 PM
Screen Shot 2021-02-24 at 10 10 03 PM

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jni — APPROVED** [review]
:pray:

**Review by ppwadhwa — APPROVED** [review]
Looks good to me!  :)

**Review by sofroniewn — APPROVED** [review]
Wonderful, thanks! I will merge this now :-)

**Comment by tlambert03** [comment]
We should also remove the unnecessary "setStyleSheet" line in the dialog

**Comment by goanpeca** [comment]
Indeed @tlambert03, see https://github.com/napari/napari/pull/2312/files

**Pull request merged**
