### PR TITLE
add `MultiScaleData` wrapper to give multiscale data a consistent API

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This PR introduces the concept of a runtime checkable `LayerDataProtocol`: the bare minimum set of properties we expect from an object that can be used as napari layer data.  It's far from "complete" at the moment (mostly just requiring `shape` and `dtype` ... the two main required attributes in the [numpy array interface](https://numpy.org/doc/stable/reference/arrays.interface.html#python-side))... but it provides a place for us to define what one should be able to "expect" from `layer.data`.

An immediate need for this sort of thing comes with multiscale data (see #2679, where the absence of a good data interface means that we leak little bugs based on assumptions of data types).  There's another latent bug with the same assumption that `labels.data` is never multiscale right [here](https://github.com/napari/napari/blob/c4a3dcf10dc8e852cfb5be33c3571eb15aab5361/napari/layers/labels/_labels_key_bindings.py#L52) in keybindings, where we take the `max()` of something that might be a list.

Along with this protocol, I would propose that we extend `napari._tests.utils.layer_test_data`, with _all_ of the things we consider to be valid inputs (for instance, that list is currently lacking multiscale labels data)... and this PR adds a test to make sure that they provide the required interface.  This PR also adds a `MultiScaleData` wrapper that avoids the need for `if self.multiscale ...` in a few places... but it of course doesn't provide total parity.

Two remaining issues:
1. I don't really know enough about `shapes` and `surface` to define their protocols here.  So I'm skipping them in the tests, and could use some input from @sofroniewn or others on exactly what is and isn't considered to be valid input there.
2. `magic_name` works on the assumption that the data object [_IS_ the object passed](https://github.com/napari/napari/blob/c4a3dcf10dc8e852cfb5be33c3571eb15aab5361/napari/utils/naming.py#L92) into the constructor.  So it won't work with the current `MultiScaleData` wrapper without some modifications.  (there's another latent bug here, since it also wouldn't work multiscale data based on `GeneratorTypes`, since we call `list(data)` and create a new object... and it won't work with bool type labels, since we convert those to int arrays... but we don't test those either))

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
This is ready for review @jni, @sofroniewn.  To summarize/simplify my first post.  This mostly adds a wrapper for multiscale data so we can ask `.dtype` and `.shape` of all `Image.data`.  I fixed the `magic_name` issue by duplicating the `magic_name` code in other layer `.__init__` methods.

**Comment by tlambert03** [comment]
test fail seems unrelated:
Untitled 2

**Review by sofroniewn — APPROVED** [review]
Changes look good here, and I think move us in the right direction. I'm not sure though long run how we should handle all of this (including for more general layers) and what makes sense on the `layer.data` property vs some more internal representation. I'm also thinking about how we might one day solve some of our slicing problems .... but those are problems for another PR.

Curious what @jni thinks about this?

> I don't really know enough about shapes and surface to define their protocols here. So I'm skipping them in the tests, and could use some input from @sofroniewn or others on exactly what is and isn't considered to be valid input there.

Do we want to deal with this now or later? Happy to help advise. Shapes is a list of arrays, and surface is a 2-tuple/ 3-tuple, but you could add a `dytpe` and `shape` to both. Could come later too

**Comment by sofroniewn** [comment]
I think we can go with this as a reasonable intermediate step and then continue to clean up/ improve other areas as needed. @tlambert03 if you fix the merge conflict I think we can then get this in!! Thanks

**Comment by sofroniewn** [comment]
Actually @tlambert03 i just fixed so don't worry about that - i will move this to awaiting merge once tests pass, in case @jni wants a final look, otherwise will merge tomorrow morning

**Pull request merged**
