### PR TITLE
Include requirements/default.txt in sdist

### PR DESCRIPTION
**Pull request by cgohlke**
Fix FileNotFoundError: [Errno 2] No such file or directory: 'requirements\\default.txt'

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kne42 — APPROVED** [review]
@cgohlke Thanks for the fix!

Out of curiosity's sake, in what context exactly was this bug occurring? Looks like this is happening on a Windows machine if I'm not mistaken.

**Comment by cgohlke** [comment]
> in what context exactly was this bug occurring?

Install from source distribution `napari-0.1.4.tar.gz` downloaded from [PyPI](https://pypi.org/project/napari/#files), e.g. via `python -m pip install .` or `python setup.py bdist_wheel`.

**Comment by kne42** [comment]
Mmm, ok, thanks for the info! I'll merge as soon as the tests pass for tradition's sake ;)

**Comment by cgohlke** [comment]
Thanks.

FWIW, the source releases at https://github.com/napari/napari/releases seem also broken:
```
Processing napari-0.1.4
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'X:\Python37\python.exe' 'X:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'AppData\Local\Temp\tmpd4svdkzb'
       cwd: AppData\Local\Temp\pip-req-build-_n6098s0
  Complete output (27 lines):
  fatal: not a git repository (or any of the parent directories): .git
  fatal: not a git repository (or any of the parent directories): .git
  fatal: not a git repository (or any of the parent directories): .git
  Traceback (most recent call last):
    File "X:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "X:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "X:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "AppData\Local\Temp\pip-build-env-649wylb7\overlay\Lib\site-packages\setuptools\build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "AppData\Local\Temp\pip-build-env-649wylb7\overlay\Lib\site-packages\setuptools\build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "AppData\Local\Temp\pip-build-env-649wylb7\overlay\Lib\site-packages\setuptools\build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "AppData\Local\Temp\pip-build-env-649wylb7\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 84, in <module>
      version=versioneer.get_version(),
    File "AppData\Local\Temp\pip-req-build-_n6098s0\versioneer.py", line 1538, in get_version
      return get_versions()["version"]
    File "AppData\Local\Temp\pip-req-build-_n6098s0\versioneer.py", line 1507, in get_versions
      pieces = from_vcs_f(cfg.tag_prefix, root, verbose)
    File "AppData\Local\Temp\pip-req-build-_n6098s0\versioneer.py", line 1144, in git_pieces_from_vcs
      pieces["distance"] = int(count_out)  # total number of commits
  ValueError: invalid literal for int() with base 10: ''
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'X:\Python37\python.exe' 'X:\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'AppData\Local\Temp\tmpd4svdkzb' Check the logs for full command output.
```

**Comment by kne42** [comment]
Hmm interesting, I didn't even realize we had releases on GitHub. Must've been automatically created.

Regardless, it seems to have to do with the downloaded tarball not being a git repository and thus `versioneer` not being able to figure out the version.

Strangely enough it is able to complete running on my Mac so it's likely that there's a Windows-related error in `versioneer`.

Any ideas @jni?

**Pull request merged**
