### PR TITLE
async-45: Docs and Cleanup

### PR DESCRIPTION
**Pull request by pwinston**
# Description
* WIP, but opening this for docs and code cleanup related to docs

# Changes
* Fix `loader_defaults` and `octree` config file keys.

## Type of change
- [x] Refactoring in experimental code

### CODE REVIEW

**Comment by sofroniewn** [comment]
Hi @pwinston I just gave this a quick read, it's coming along nicely! We're getting ready to make the `0.4.3` release now and this is one of the last things to go in. Just wondering how much more you're planning to add to this / when you think you'll be done? I could probably make the release candidate tonight if this was ready.

We could also merge what we have now (which includes a couple code changes) and then have some docs only PRs that come after the release if there's a lot more you still want to add.

**Comment by pwinston** [comment]
The code change is needed, it's fixing the config file keys.
The rendering "explanation" is "done", no more changes planned.

The "guide" is still very much in progress. I haven't even gotten the RST rendering locally right now so probably there are bugs in that. I'd suggest that I just remove that from this PR. Merge the code and explanation. And then I can make a new PR for the "guide".

I'm heading out now but I can remove the guide change from this PR later tonight like by 8PM ET.

**Comment by sofroniewn** [comment]
Splitting it up sounds good! Will be a couple days before we actually release and so we can merge some docs only PRs during the testing process

**Comment by pwinston** [comment]
@sofroniewn okay this is now just the code change and the rendering doc.

I will create a new PR for the rendering "guide" tomorrow.

**Review by sofroniewn — APPROVED** [review]
Ok, this looks good. Thanks @pwinston I will merge now!

**Pull request merged**
