### PR TITLE
allow pass an array of colors to text

### PR DESCRIPTION
**Pull request by giovp**
# Description
see #2019 
remove the indexing of color array in order to pass different colors for text

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
although not 100% sure about breaking
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
address #2019 (but does not close it) 

# How has this been tested?
some tests pass but did not checked all
EDIT: `napari/layers/points/_tests/test_points.py` fails.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Tests fail as it looks like the assumption that this property is now 1D is not true and so should be changed possibly with something like an `np.expand_dims` if needed.

```
E           (shapes (1, 4), (4,) mismatch)
E            x: array([[0., 0., 0., 1.]], dtype=float32)
E            y: array([0, 0, 0, 1])
```

Would be great if @kevinyamauchi can weigh in with a review as I havn't followed convo in #2019, but overall this seems very reasonable, and thanks @giovp for the contribution and thanks @kevinyamauchi for helping out!!

**Review by kevinyamauchi — COMMENTED** [review]
Hey everyone !  Thanks again for this PR, @giovp . Based on #2019, my understanding of the intention of this PR is to enable the user to independently set the colors of individual text elements (e.g., make one red, one blue, one purple). Is that correct, @giovp ?

Some context on the failed tests: we made this initial version of `TextManager` only support a single color because it is makes adding new text elements more simple. That is, since all of the text elements managed by an instance of `TextManager` are one color we don't have to figure out what color the new text elements should be. Thus, the tests expect the `TextManager.color` to be 1D because `TextManager.color` should store a single color.

My plan had been to use the forthcoming `ColorManager` (#1940) to bring more complex coloring (i.e., setting colors for each text element directly or mapped to layer property values) to `TextManager`. Of course, I am open to an intermediate fix if this is blocking people!

If my understanding of the goal of this PR is correct, I think there are a couple of paths forward (see [my comment](https://github.com/napari/napari/issues/2019#issuecomment-746427279) on #2019 for a bit more discussion):
1. We can with a couple of small changes (listed below) merge this PR to allow the user to pass an array of colors to set the text color for each element. The caveat of this approach (as discussed above) is that when we add a new text element, `TextManager` won't add a corresponding color element. That is the number of elements in `TextManager.color` and `TextManager.values` will not be equal. This won't cause errors, as [`vispy` clones the color to make it the same size as the data](https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/visuals/text/text.py#L579-L582), but I think the behavior is inconsistent with the rest of the annotations in napari and I think it is not ideal for the model and view to be out of sync in this manner.
2. We can do option (1) and then make `Text.color` always an (Nx4) array of colors where N is the number of text elements. We can add something simple to color new text elements (e.g., takes the first color in the array). This would be straightforward, but would require a lot more changes than (1). I can help with this. This might be a bit of an awkward middle ground (i.e., more work, but doesn't get us all of the way to the desired feature).
3. We can do option (2) and add the code to make the behavior for the color of the next text elements to be added the same as the layer elements (i.e., the same as the `current_*_color` pattern on the layers). I am leaning against this approach, as it seems like work that will be quickly superceded once we have the `ColorManager`.
4. Once `ColorManager` is done, we can use it to add support for coloring text with the same API as face_color and edge_color in the layers. #1940 will be ready for review by the end of the week, so depending on how review goes, we could add it to `TextManager` in the coming weeks.

The changes I think we'd need to make to do option (1):
- update the [`TextManager.color` setter](https://github.com/napari/napari/blob/4545de2d1335df57b26071ece7fec968f5b27021/napari/layers/utils/text.py#L161-L163) to allow arrays of colors to make it consistent with the `__init__` method.
- update the tests to expect a color of shape (1, 4)  rather than (4,). I can help with this if we proceed with this option.

I am open to performing option (1) or (2) now if it unblocks @giovp and then option (4) when #1940 merges. I think it is worth noting that I would still consider setting text color with an array of colors as an "incomplete feature" following (1) as the color setting for new text elements wouldn't be working yet. Also, I proposed a hacky way of setting the color as an array of colors that I think works in #2019 (comment [here](https://github.com/napari/napari/issues/2019#issuecomment-746427279)) that could be an alternative stop gap measure to (1). 

What do you think, @giovp and @sofroniewn ?

**Comment by giovp** [comment]
Hi all,

thanks a lot for the very prompt reply and detailed explanation! Was very useful.

A little more explanation on our side about feature implementation. The main reason to have colored text is to be able for users to easily match the cluster text (integers in the figure) to the color of respective points. You can see in the example in #2019 for instance that the cluster label "10" does not clearly overlap any light-oranged point.

<details>
<summary>Details</summary>

image

</details>

this is actually a problem on our side in the first place 😅 as we don't have yet a robust way to assign text position to respective cluster (for now we are using `scipy.spatial.KDTree` but we might look into it a little bit more). The colour would be superflous if text is always matching a "good" cluster candidate spot (as it would be clear that text relates to underlying cluster colour).

Secondly, we realized that even if there was an easy fix for the colouring, missing an edge would still make the text not very readable.

The submitted PR was really sloppy on my side 😅 as I should have thought that simply removing the index wasn't doing the job. Since we set `layer.editable = False`, I never thought that indeed a problem would be if a new point was added to the layer interactively.

Since it's really a minor aestethic thing, we are really not in a rush and we can definitely wait for #1940 to be merged and then go from there, looks like a very useful addition that would provide the flexibility for such thing (particularly like the ability to map colors to layer property for consistency).
Meanwhile we might end up having a better way to assign text to cluster and thus overcome the problem.

So I'd be totally happy to close this and wait for the new release with Color Manager and get back to you then! Looking forward to it!
Thanks a lot for the very detailed explanation and for providing so many alternatives!

**Comment by sofroniewn** [comment]
This was great additional context @giovp and I think this is something we do want to support! [EDIT: my original message seemed to say "don't", when I meant "do", sorry for the terrible typo, and I hope that didn't cause any confusion @giovp]

> So I'd be totally happy to close this and wait for the new release with Color Manager and get back to you then! Looking forward to it!

Thanks for letting us know this. I'm fine leaving this open so we don't forget about it, but I think waiting till after #1940 makes the most sense!

**Comment by kevinyamauchi** [comment]
No worries and thank you for the additional information, @giovp ! I will ping you once we open a PR to add `ColorManager`  to the `TextManager` in case you'd like to follow along.

**Comment by giovp** [comment]
> No worries and thank you for the additional information, @giovp ! I will ping you once we open a PR to add `ColorManager` to the `TextManager` in case you'd like to follow along.

yes, that'd be great, thank you!

**Comment by sofroniewn** [comment]
@giovp thanks for you patience here! We've added the ColorManger in #2204 and we're very close to adding the text manager in #2855. Now might be a good time to revisit this and the underlying issue described in #2019.

Maybe @andy-sweet when you have time you can read through the issue in #2019 and #2020 and we can think about the best way to address that request in light of the progress we've made. Thanks!!

**Pull request closed without merging**
