### PR TITLE
update event tables in the in-depth guides

### LINKED ISSUE #3984: Add layerlist events to docs
## 🧰 Task
Note to self (or anyone who'd like to take it up), we need to add `LayerList` events to the events reference at https://napari.org/guides/stable/events_reference.html

### PR DESCRIPTION
**Pull request by grlee77**
# Description

closes #3984 

This PR adds a `LayerList` events table to the docs. It also modifies the existing Layer events table, adding a new first column that indicates the layer type corresponding to the event.

## Type of change
- [x] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

I verified that the new markdown file is generated as expected, but still need to check the rendered docs.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by grlee77** [comment]
There are a few other EventedList classes I did not document. These were
- `napari.utils.transforms.ClippingPlaneList` which is accessed as `layer.experimental_clipping_planes`
- `napari.utils.transforms.transforms.TransformChain` which is private `layer._transforms`
- `napari.utils.tree.group.Group`

It did not look like there were any `EventedDict` or `EventedSet` events we would need to document, but the same `iter_evented_container_events` function can be used to generate those later if needed.

**Comment by tlambert03** [comment]
thanks @grlee77!  The new first column on Layer types is great.  But [these docs](https://github.com/napari/napari/blob/6a3e11aa717e7928a0a5a3c7693577729a466ef1/napari/utils/events/containers/_evented_list.py#L55-L72) don't seem to be making it into the table:

Untitled

(I know it's annoying that each class has a slightly different description extraction method...  )

_edit_: if need to change the title `Events` to something that matches numpy docs format, go for it

**Comment by tlambert03** [comment]
also, I _think_ you'll need to edit the `TOC_IGNORE` list in `copy-docs.py`.  Hopefully that step should go away soon with the docs refactor

**Comment by grlee77** [comment]
> edit: if need to change the title Events to something that matches numpy docs format, go for it

Yes, that is why the current approach doesn't work. I will change it

The other backticks are because I accidentally used `ev_model_row` when it should have been `layer_row` (actually once I update the docstring maybe it should still be `ev_model_row`)

**Comment by grlee77** [comment]
Also, just noticed there are still a few duplicated events due to `IntensityVisualizationMixin`. Those are `gamma`, `contrast_limits` and `colormap` and are shared across `Image`, `Labels` and `Surface`!

**Comment by grlee77** [comment]
There are also a few more events on `layers.selection` which is a `Selected` class

**Comment by grlee77** [comment]
Okay, it looks a lot better now. Only the Event.value types don't show up, but that is because I wasn't sure how this should be formatted in the docstring. Is the type supposed to be listed as the value type there? If so, then what do you list for ones that don't have any "value" listed currently (I copied those docstrings from `SelectableEventedList`/`EventedList`)

layerlist_table

**Comment by grlee77** [comment]
Should we manually exclude any events whose names start with underscore? (currently only private `layers.selection.events._current`)

**Comment by tlambert03** [comment]
> Event.value types don't show up, but that is because I wasn't sure how this should be formatted in the docstring. Is the type supposed to be listed as the value type there? If so, then what do you list for ones that don't have any "value" listed currently

`event.value` is just a convention we use in some places, `value` isn't actually an attribute of `Event` objects unless you _emit_ the event with `(value=...)`, but events can also have multiple attributes/names/values.  In the case of evented lists, we don't use value, and some have multiple values.  So this would need to be special cased.  The docstrings are "correct" in a sense (of course, numpy docs doesn't have a spec for how to show the type of "an attribute of an attribute" which is what we have here, but there's no class to point to either... that's an unfortunate consequence of the way event objects are created)

**Comment by tlambert03** [comment]
> Should we manually exclude any events whose names start with underscore? (currently only private layers.selection.events._current)

sure

**Comment by tlambert03** [comment]
how's this going @grlee77, need anything from me?

**Comment by grlee77** [comment]
@tlambert03, after the docs update, we no longer need to manually exclude `_layerlist_events.md` from the TOC? (The prior `_config.yml` and `copy-docs.py` no longer exist on main)

There is currently a [CI failure related to Git-LFS quota](https://github.com/napari/napari/runs/5242457597?check_suite_focus=true#step:4:14)

**Review by sofroniewn — APPROVED** [review]
LGTM! git-lfs fail can be ignored, we've bumped our quota. I think this can now be merged. Does @tlambert03 want to give it a final look?

**Review by tlambert03 — APPROVED** [review]
looks good thanks!
Let's merge now, but in a future PR, would be nice to make clearer that the event object has these attributes, and what their types are.  (e.g. explain what `value` and `index` are  for `layers.events.inserted`)

Untitled

**Pull request merged**
