### PR TITLE
About copy button

### LINKED ISSUE #752: Add "copy to clipboard" to version box in the "info" panel
## 🚀 Feature

Reviewing #750, it occurred to me that it would be nice to be able to push a button to copy all the required information in the "info" box, rather than having to select it from the scroll box.

### PR DESCRIPTION
**Pull request by boonepeter**
# Description

Adds "Copy to clipboard" functionality to the "about" menu. 
Looks like this:
copy-to-clipboard

I used GitHub's [Octicons](https://octicons.github.com/) which are free to use anywhere. 
## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

closes #752 
# How has this been tested?

- [x] Manually tested on the following setup:
```
napari: 0.2.6+29.g978b007 
Platform: Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid 
Python: 3.7.0 (default, Jun 28 2018, 13:15:42) [GCC 7.2.0] 
PySide2: 5.13.2 
Qt: 5.13.2 
VisPy: 0.6.3 
NumPy: 1.17.4 
SciPy: 1.3.3 
scikit-image: 0.16.2 
Dask: 2.9.0 

GL version: '3.0 Mesa 18.2.8'
MAX_TEXTURE_SIZE: 16384 

```
(I got this info by using the new feature :smile: )
- [ ] Automated tests

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by boonepeter** [comment]
Couple of things:
- `build_icons.py` inserts coloring info on the 4th line...which doesn't work with every svg file. Some don't have any new lines for example. This could be a little smarter with where it inserts that information. Let me know if it's worth the effort.
- I didn't rebase commits fully. I can read about that more and clean this up if that is a problem.
- This was my first time doing anything with Qt. I tried to follow the code style that you have going on, specifically the buttons in `qt_viewer_buttons.py` and the corresponding styling in `res.qrc`

**Review by sofroniewn — APPROVED** [review]
This looks amazing! Thanks so much @boonepeter - love the choice of the octicons. I'm not sure if we've been using them elsewhere, but we definitely should. I like their trashcan too. We might want to do some follow-up PRs where we standardize some of our icon set using what they offer.

I made a few minor tweaks to the PR, naming conventions etc, and adjusted the stylings slightly so that the button is now a bit smaller and aligned to the top of the text edit boxes. Curious what people think / what people prefer.

image

I'm approving this now and think it's good to merge (I also verified the functionality works very nicely), but maybe @tlambert03 or @jni can give this a look over as well before we merge!

**Comment by sofroniewn** [comment]
Also as to your comment on `build_icons.py` if that is a frequent problem maybe we should fix. In general there's probably some stuff we could do that we automate the build icon process more. I feel like right now one has to add things manually in many places, but some of that stuff could be reduced. Maybe we should make a follow-up issue to discuss reducing the complexity here

**Review by tlambert03 — APPROVED** [review]
Great!  I agree: nice find on the octicons.  we should use them more.

I slightly tweaked the style again to add some padding so that one edge isn't right against the highlighted background upon mouse hover.  also removed a couple unnecessary lines (styles are already in stylesheet, no need to enforce width;  `lambda: function()` is the same as `function`; and `cb.setText` will `clear()` previous contents anyway)

Regarding the `build_icons.py` comment.  I have also seen that and had to make some manual changes to SVGs before.  Probably worth addressing in a follow-up PR.

**Comment by tlambert03** [comment]
> the button is now a bit smaller and aligned to the top of the text edit boxes. Curious what people think / what people prefer.

I prefer the smaller top-aligned button

**Comment by boonepeter** [comment]
Sweet, I'm glad it works! I think the smaller icon and placement look great, I didn't think much about that. I'm happy to help out as time allows, and I appreciate how encouraging you all are to contributions.

**Comment by sofroniewn** [comment]
Thanks for those further tweaks @tlambert03, and @boonepeter I'm glad contributing was a good experience, we look forward to seeing you around the repo. Do let us know if there are particular features / bug fixes you're interested in either from a user or contributor standpoint.

I'll let this sit till tomorrow in case @jni has comments, but I think we're pretty close now to having this done.

**Comment by jni** [comment]
For what it's worth, @jni approves wholeheartedly, including of the refined icon size and placement. 🎉 Thanks everyone!

**Pull request merged**
