### PR TITLE
Update script for vendored modules

### PR DESCRIPTION
**Pull request by Czaki**
# Description

As current workflows for updating vendor modules produces warnings 

obraz

This PR update workflow to use environment variables.

THere should be a decision on what should be done with matplotlib. 

# References

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by brisvag — COMMENTED** [review]
IMO matplotlib should be left out, as it's not really strictly a copy-paste from a different package.

**Comment by Carreau** [comment]
> IMO matplotlib should be left out, as it's not really strictly a copy-paste from a different package.

At the same time, maybe we should update it and see what breaks then fix it ?

**Comment by brisvag** [comment]
I think we should do as @Carreau suggested and update this module to whatever its current version is and see how things go...

**Comment by Czaki** [comment]
@brisvag updated

**Review by brisvag — APPROVED** [review]
Nice! Looks like they are all pretty straighforwards formatting changes. We get a couple extra colormaps as well (`berlin`, `managua` and `vanimo`).

**Pull request merged**
