### PR TITLE
Fix README links Contributing Guide, Mission&Values, Code of Conduct, & GovModel

### LINKED ISSUE #4266: Contributing Guide instructions don't work: requirements.txt missing??
## 🐛 Bug

<preface: I have no idea if this is the proper place to report this. The whole napari/napari.org/docs/etc. thing is **super confusing**.>

Following the Contributing Guide: https://napari.org/docs/dev/developers/contributing.html#setting-up-a-development-installation fails when it says to: `pip install -r requirements.txt`
This doesn't work: 
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```
This file does not appear to be present in the napari repo.

## To Reproduce

Follow the Guide:
1. clone the repo
2. cd napari
3. pip install -r requirements.txt

## Expected behavior

Not sure? Not an error anyways—already stressed enough!

## Environment

```
napari: 0.4.16.dev17+g2a14717f
Platform: macOS-12.2.1-arm64-arm-64bit
System: MacOS 12.2.1
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:27:43) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- StarDist: 2021.10.25
- aicsimageio-in-memory: 0.6.1
- aicsimageio-out-of-memory: 0.6.1
- clEsperanto: 0.15.3
- console: 0.0.4
- napari-brightness-contrast: 0.1.6
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.10
- napari_skimage_regionprops1: 0.2.9
- napari_skimage_regionprops2: 0.2.9
- ome-types: 0.2.9
- scikit-image: 0.4.16.dev17+g2a14717f

```

## Additional context

macOS 12.2.1, arm64

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description
Not sure I'm doing this correctly, but the link in the GitHub README was to an old doc and now is a 404.
This should point to the proper napari.org page.

## Type of change
- [. ] Bug-fix (non-breaking change which fixes an issue)

# References
napari.org Contributing Resources

This should fix: https://github.com/napari/napari/issues/4266

# How has this been tested?
N/A ? I think?

## Final checklist:
- [. ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by alisterburt — APPROVED** [review]
Thank you @psobolewskiPhD ! LGTM 🚀

**Comment by tlambert03** [comment]
Yay!  Finally got him!  :joy:

I think there's a few more in there that also use /docs/dev... wanna hit those too?

**Comment by psobolewskiPhD** [comment]
> I think there's a few more in there that also use /docs/dev... wanna hit those too?

I think I got em. Just using the `pencil` in the corner option so I don't think any of the fancy commit things are happening. Sorry, I'm not quite confident in all the branch/repo swapping.

**Review by alisterburt — APPROVED** [review]
Excellent, thank you @psobolewskiPhD !!

**Review by tlambert03 — APPROVED** [review]
Lovely. Thanks @psobolewskiPhD !

**Pull request merged**
