### PR TITLE
Add expandable layer properties

### PR DESCRIPTION
**Pull request by sofroniewn**
# What does this PR do? Why are doing this? References?
This PR adds layer specific properties back to the layer widgets. They are accessible by double clicking the layer widget. The layer widget then expands in place to reveal the extra properties.

This PR is still in progress, but I thought I'd give people a chance to check it out now and weigh in on some of the stylistics aspects before going too far. I feel right now it just looks a little ugly with the text labels and layer name not lining up and the spacing not being regular. I also havn't implemented all the possible layer properties yet, like the symbol for markers, and the interpolation mode for images. I'm also thinking about adding a text edit box that only accepts numbers next to the opacity slider so you can type in a value too.

A final note, this PR also contains the edits from the drag / drop PR and the delete button PR as well.

image

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
[Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.]
- [x] TestCase Run `examples/layers.ipynb` and manually interact with gui

## Final Checklist:
- [x] My PR is the possible minimum work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by freeman-lab** [comment]
small aesthetic comment -- i'd move the trash icon to the lower right :) that's where it is on the mac desktop, in photoshop, and a few other tools i know

**Comment by jni** [comment]
I love the idea, and except for the alignment issue that you already flagged and the naming issue that I've flagged before (it's unclear that I can change the layer names), I think it looks great!

Incidentally, default names could be improved to (a) include the layer type (so `add_markers` would default to `markers`, not `layer`), and (b) add an incrementing integer for each layer (optionally only counting layers of that type).

I also agree with @freeman-lab that the trash icon would be way better at the bottom right, though I don't know why. =D

**Comment by jni** [comment]
PS Thanks for including a screenshot, so useful. =)

**Review by kne42 — APPROVED** [review]
Looks beautiful, thank you Nick!

I agree with Juan and Jeremy, I think it would make the most sense to move the trash icon into the lower right corner to separate it in functionality from other utilities that you may want to place up there (e.g. a "new layer" button).

I also agree with Juan surrounding layer naming, but I think we can address that in a future PR.

Other than that, my only other comment is that it seems a bit weird to me how a lot of the existing layout "shifts" when you expand the layer (e.g. the layer name moves left to align with the other properties).

**Comment by AhmetCanSolak** [comment]
> Incidentally, default names could be improved to (a) include the layer type (so `add_markers` would default to `markers`, not `layer`), and (b) add an incrementing integer for each layer (optionally only counting layers of that type).
> 
I love to see option (b). An easy feature indeed. @sofroniewn if you want i can address that after merge of this?

**Review by AhmetCanSolak — CHANGES_REQUESTED** [review]
Everything seems good aside from the conflicts. I think it is ready to be merged after resolving conflicts.

**Comment by sofroniewn** [comment]
I've moved the trash icon to the lower right. I had initially put it on top as new layers are created up there, so thought it would be easier to have it closer, but agree most other apps have it down there. As to other icons like new layer buttons etc. I was imaging them in a row along with the trash icon too, but that can be at the bottom too.

I've also changed the default layer names for the different classes, but havn't implemented the numerical counter yet. Happy to sync with @AhmetCanSolak on that in a future PR. I think we should also allow layer names to be passed as input arguments to the add_layers functions.

As to the editing of the layer name, agreed that right now it is hard to discover that you can do it, I find the white edit box background that's default quite jarring, maybe we can find some middleground when we redo all the stylings.

I'm going to work now on sorting out some of the alignment problems and extra properties, and then resolve the conflicts. I'll post another screen shot when I think it's ready to go!

**Comment by sofroniewn** [comment]
Also noting here that I closed #65 that just had the trash icon code, which is also contained here

**Comment by sofroniewn** [comment]
Have added some extra properties to the image / marker layers. Definitely still a couple more that could be added, but this seemed like a reasonable place to stop. Didn't add any edit boxes next to the sliders to type in numbers but could be done in the future.

I tried to fix some of the alignment sizing issues. I think it's passable now, but could be improved when we revisit stylings more generally. I'm tempted to make the layer's panel a fixed width that cannot be adjusted - it might be cleaner.

Here's an updated screenshot
image
I think if everyone approves then it's ready to merge

**Comment by royerloic** [comment]
Looks great. Concerning the style I think we could reduce margins to have a slightly more compact layout (particularly for the layers panel). Otherwise, I think it is great!

**Comment by sofroniewn** [comment]
@royerloic sounds reasonable, but something that will probably wait until we make a big push on the stylings if that's ok

**Comment by jni** [comment]
@sofroniewn this looks so great! Re the text styling, it can definitely wait until we're making a concerted style push, but here's my suggestion:

- frame around it *with background matching the surrounding*
- when you click on it, the background becomes white and you're editing
- when you press enter or click out, the rename is executed and the background goes back to matching the surrounds.

**Review by AhmetCanSolak — APPROVED** [review]
Thank you @sofroniewn

**Comment by kne42** [comment]
@AhmetCanSolak please squash-merge big pull requests like this in the future to avoid cluttering the git history.

**Comment by AhmetCanSolak** [comment]
@kne42 i presumed it was squashed on his branch. #70 is only thing merged after this, let me revert and remerge.

**Comment by AhmetCanSolak** [comment]
Missed that @kne42, i presumed he squashed on his branch. It is not deep yet. If we have #68 and #70 we can revert these two PRs and merge back.

**Pull request merged**
