### PR TITLE
Fix automatic selection of points when setting data

### LINKED ISSUE #6064: Stop automatically highlighting "added" points on set_data
## 🐛 Bug

Currently when we set the data of a points layer, if the new data has more points than the previous data, then the additional points get selected automatically and highlighted. This can be very harmful to a visualisation because the highlight is very distracting and totally unrelated to the data. In many situations, the points are actually a completely different set of points, so highlighting the last few is completely nonsensical — they are not the "new" points, all the points were new.

## To Reproduce

```python
import numpy as np
import napari
from magicgui import magicgui


viewer = napari.Viewer(ndisplay=3)

@magicgui(
    auto_call=True,
    x={'widget_type': 'Slider', 'min': 0, 'max': 5000}
)
def get_pts(x=2500) -> napari.types.LayerDataTuple:
    npoints = np.random.randint(900, 1100)
    data_raw = np.random.random((npoints, 3))
    data = data_raw[np.lexsort(data_raw.T)]
    return (
        data * 255,
        {'size': 2, 'name': 'pts', 'shading': 'spherical'},
        'points',
    )

w = viewer.window.add_dock_widget(get_pts, area='bottom')
_ = get_pts()  # call once to create the layer

napari.run()
```

https://github.com/napari/napari/assets/492549/dd49c2c3-ca94-41e2-a559-85dfb6a0fd04

## Expected behavior

Points should not be selected on setting data.

CC @francescalted

### PR DESCRIPTION
**Pull request by akuten1298**
# Closes #6064

# Description

This PR fixes the points layer bug related to highlighting/selection of the points from the previous dataset when there are more number of points data on the newer set compared to the older one. To fix this, we have moved the selection outside of the data setter and into the points::add functionality.

Points Data Setter:

https://github.com/akuten1298/napari/assets/51192400/a573cd8a-98c5-4877-a06c-9b6b7ddd3d10

Points Data Add:

https://github.com/akuten1298/napari/assets/51192400/5e3c3561-f298-4c2d-9dbd-4c2f03157209

# References

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Maintenance (changes required to run napari, tests, & CI smoothly)
- [ ] Enhancement (non-breaking improvements of an existing feature)
- [ ] Documentation (update of docstrings and deprecation information)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [x] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by andy-sweet** [comment]
I set the 0.5.0 milestone because this bug has been around for a while. But given the code changes are small, simple, and isolated, it could be worth bringing into 0.4.19.

**Comment by andy-sweet** [comment]
@jni : assigned to you as this fixes a bug that annoyed you in a simple way. Feel free to pass it on!

**Review by jni — APPROVED** [review]
YASSSSS! So simple! Thanks @akuten1298! 🙏 🚀

**Comment by jni** [comment]
@Czaki I'll let you make a decision on the milestone here. I don't think it's critical for 0.4.19 and given the cherry picking etc I think it's probably not worth backporting.

**Comment by jni** [comment]
Gah. Didn't change the title before merge, only the description. 🤦

**Pull request merged**
