### PR TITLE
Fix headless test failure

### PR DESCRIPTION
**Pull request by lukasz-migas**
This PR fixes the headless test failure introduced by #3299 

- moved the failing plugin test to `napari/plugins/_tests/test_qt_*` file and modified `tox.ini` to ignore all files with that glob pattern when running in headless mode

### CODE REVIEW

**Comment by tlambert03** [comment]
I'd rather not start adding  tests that require Qt into more parts of the code base and then ignoring them in `tox.ini` (ideally, we'd even be able to remove `--ignore napari/_tests` someday).  We've really tried to keep that isolation clean, and that's why the headless test is there.  

Is there no way to fix this test so that it doesn't require Qt at all?  If you're specifically just trying to test that `Window._add_theme` and `Window._remove_theme` are called, then those tests should go in the `_qt/_tests` folder where the other Window tests are

**Comment by sofroniewn** [comment]
> We've really tried to keep that isolation clean, and that's why the headless test is there.

Agreed it would be nice to fix this rather than ignore it otherwise it will come back to cause us problems

**Comment by sofroniewn** [comment]
>  If you're specifically just trying to test that Window._add_theme and Window._remove_theme are called, then those tests should go in the _qt/_tests folder where the other Window tests are

That functionality alone is already tested https://github.com/napari/napari/blob/47df23877345a043c35d624e5d7b8252fb8ffca0/napari/_qt/_tests/test_qt_window.py#L49-L76

I've moved this test now (which includes the plugin registration too the qt folder) to match our plugin dock widget registration test with qt in it https://github.com/napari/napari/blob/47df23877345a043c35d624e5d7b8252fb8ffca0/napari/_qt/_tests/test_plugin_widgets.py#L43-L64. i see that as very analogous

The tox.ini changes are reverted

If all tests pass then i will merge. Thanks for getting this going @lukasz-migas and good flag for additional fix @tlambert03

**Review by sofroniewn — APPROVED** [review]

**Comment by lukasz-migas** [comment]
@sofroniewn thanks for moving the tests to the right place. 
This test was specifically for plugin provided themes which wasn't tested in the 'window' tests.

The test in 'window' was passed just fine because theme addition was carried out after the while app had started so it didn't catch the bug.

**Pull request merged**
