### PR TITLE
exit context before return on _repr_png

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
lets try this fix for the notebook tests... exiting the context before returning.

I also think something funny is going on with cirrus today.  i tried to test this on my branch and after an hour, it still was hanging.

### CODE REVIEW

**Comment by sofroniewn** [comment]
> lets try this fix for the notebook tests... exiting the context before returning.

looks like it is fixing the linux fails!!

> I also think something funny is going on with cirrus today. i tried to test this on my branch and after an hour, it still was hanging.

looks like the mac fails are cirrus related ...

**Comment by tlambert03** [comment]
yeah, encouraging... maybe if it passes we should run it again a couple times?

**Comment by tlambert03** [comment]
ok I've run this a few times now... and except for the timeouts (where the test takes like 50+min due to some cirrus stuff), I haven't seen any errors.  so maybe it's good?

**Comment by sofroniewn** [comment]
I think it is good - merging now!!

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Review by sofroniewn — COMMENTED** [review]
Actually @tlambert03 - should you initialize `png=None` or something else outside the context manager just in case it fails? Not sure if that is best practice?

**Comment by jni** [comment]
I don’t think that’s necessary @sofroniewn. This isn’t a try/except so a failure above will raise an error. I could be mistaken but I don’t think you’ll ever hit an unbound local error here.

**Comment by sofroniewn** [comment]
Ok sounds good @jni I will merge then

**Pull request merged**
