### PR TITLE
proof of principle example using napari with full 3D interaction in jupyter notebook

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
I won't have time to follow up on this example, but I thought some here might be interested to see it...  If anyone wants to follow up, feel free to take this code and clean it up, otherwise fine to close it.

This draft shows the minimal changes that would need to be made to napari in order to be compatible with @almarklein's clever https://github.com/vispy/jupyter_rfb ... allowing fully interactive 3D reprs in a notebook (using a remote frame buffer).

Mostly, it means not enforcing that vispy uses at `'qt'` app (allowing the end-user to use `use_app('jupyter_rfb'), and then cleaning up the various places where the vispy canvas backend abstraction has leaked into napari's code.

example notebook in the `examples` folder (note, it requires `pip install jupyter_rfb 'ipywidgets<8'` until https://github.com/vispy/jupyter_rfb/issues/58 is solved)

https://user-images.githubusercontent.com/1609449/190674996-01c40d33-656b-4c77-bf3a-a9dd62389d09.mov

### CODE REVIEW

**Comment by jni** [comment]
Wow. That's super super cool. ❤️ Makes me think we probably want to prioritise building a declarative GUI with both Qt and ipywidgets front-end...

**Comment by Czaki** [comment]
Did I good understand that vispy set backend as a global state, and it is impossible to have jupyter widget and napari window in one interpreter session?

**Comment by brisvag** [comment]
Wow, this is amazing! I tried going down this road before, but I got lost quickly and thought this was gonna be a lot more work. I can't believe it works with so few changes!

@Czaki yeah I think so, I remember that being one of the disappointing things about it. I' m not sure if we can change vispy to allow swapping backend.

**Comment by andy-sweet** [comment]
Very impressive! I think this has been open long enough to get some exposure/traction and there are some conflicts with `main`, so I'm going to close this to reduce the number of open PRs. Feel free to reopen if the work continues.

**Pull request closed without merging**
