### PR TITLE
PR: Store unmaximized size if napari closes maximized

### LINKED ISSUE #3038: Storing window size in properties fails when closing napari in full screen mode
## 🐛 Bug

If you close napari when its window is maximized, it stores the window size of the full screen.

## To Reproduce

1. Start napari.
2. Make the window e.g. 500x500 pixels large.
3. Make the window full screen.
4. Close napari
5. Start napari again
6. Undo full screen

## Expected behavior

Napari should have size 500x500 then. This could be achieved by automatically undoing full screen before saving the window size to the settings.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.10
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.07.0
VisPy: 0.7.0

OpenGL:
- GL version: 4.6.14756 Compatibility Profile Context 20.40.44.02 27.20.14044.2001
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.3
- ome-types: 0.2.7
- scikit-image: 0.4.10
- svg: 0.1.5
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

Fixes https://github.com/napari/napari/issues/3038

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by goanpeca** [comment]
@haesleinhuepf could you tests this branch to see if it fixes the issue :) ?

Thanks!

**Comment by haesleinhuepf** [comment]
Hi @goanpeca ,

thanks for taking care of this! I just tried. When I tested it, the error is still there. I set the window size to some random values, maximized napari and closed it. After restarting napari, napari is in maximized state. After un-maximizing it, it stays in full-screen size. I would expect it returning to the random size I set initially. 

Furthermore, while testing, I received this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\structure\code\napari\napari\_qt\qt_main_window.py in resizeEvent(self=<napari._qt.qt_main_window._QtMainWindow object>, event=<PyQt5.QtGui.QResizeEvent object>)
    297             self.mapToGlobal(QPoint(self.height() / 2, self.width() / 2))
    298         )
--> 299         if event.size() == screen.size():
        event.size = <built-in method size of QResizeEvent object at 0x000002C9EB93C310>
        screen.size = undefined
    300             old_size = event.oldSize()
    301             self._window_size = (old_size.width(), old_size.height())

AttributeError: 'NoneType' object has no attribute 'size'
```

Not sure when exactly, but napari froze afterwards. I can't reproduce the error. Is it possible that this only happens once when the old settings and new settings collide?

Thanks!

Best,
Robert

**Comment by goanpeca** [comment]
Hi @haesleinhuepf thanks for testing. So I have this working for mac but I will need to check on a windows computer to fully reproduce.

I might get access to one this week

Cheers!

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Comment by goanpeca** [comment]
I still need to get it workin on win @sofroniewn :)

**Comment by goanpeca** [comment]
@haesleinhuepf I implemented a different approach. Could you please check again on windows to see if it is fixed now?

Thanks!

**Comment by sofroniewn** [comment]
Sounds like this is ready to go. If so I will merge tomorrow morning after #2932

**Comment by goanpeca** [comment]
I tested on a windows machine, but I still would like to have some input from @haesleinhuepf :)

**Comment by haesleinhuepf** [comment]
> I tested on a windows machine, but I still would like to have some input from @haesleinhuepf :)

Hey @goanpeca ,

I just tested again and it works like a charm! Thanks so much for your work :-) I owe you a drink or a bugfix on one of my repositories of your choice ;-)

Cheers,
Robert

**Comment by goanpeca** [comment]
>I just tested again and it works like a charm! Thanks so much for your work :-)

Wohoo 🚀 

>I owe you a drink or a bugfix on one of my repositories of your choice ;-)

Wohoo! I will take the 🍺, we will sort out the when later 😆

**Pull request merged**
