### PR TITLE
PR: Fix updating of plugins

### LINKED ISSUE #3251: 4.11rc2 Plugin window Installed panel not showing available plugin updates.
## 🐛 Bug

In Napari 4.11rc2 I am not seeing any updates to my installed plugins, even though I know there's new versions.
For example:
Installed: napari_plot_profile 0.1.3, but that's 2 versions out of date: both the hub and pypi show 0.1.5 available.
Installed: napari-pyclesperanto-assistant 0.9.10, while I know 0.10 has been released few weeks ago.
Installed: napari-skimage-regionprops 0.1.4, but 0.1.6 is the latest version on hub and pypi.
image

This is a regression, because this last one (`napari-skimage-regionprops`) I had in napari 4.10 in another conda env and there I was correctly shown that I can update to 0.1.6.
image

If I *uninstall* the out of date plugin, then the Available pane will show me the correct latest version. Here's `napari_plot_profile` (4.11rc2)
image

## To Reproduce

1. Install napari 4.11rc2 using `pip install --pre napari -U`
2. Have an out of date plugin
3. Open plugin panel.

## Expected behavior

If a plugin is out of date, then the Installed Plugin listing should flag that and let me update, just like in 4.10.

## Environment

napari: 0.4.11rc2
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- 3 Utilities: 0.1.4
- 4 Measurements (skimage): 0.1.4
- StarDist: 2021.6.28
- aicsimageio-in-memory: 0.3.5
- aicsimageio-out-of-memory: 0.3.5
- animation: 0.0.2
- clEsperanto: 0.9.10
- console: 0.0.3
- ome-types: 0.2.6
- scikit-image: 0.4.11rc2
- svg: 0.1.5
- video

## Additional context

N/A

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

Fixes https://github.com/napari/napari/issues/3251

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [x] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

napari

### CODE REVIEW

**Comment by goanpeca** [comment]
@psobolewskiPhD could you give it a spin and check if it works as expected :) ?

[Binder](https://mybinder.org/v2/gh/goanpeca/napari/fix/plugins-update?urlpath=%2Fdesktop)

Thanks!

**Comment by psobolewskiPhD** [comment]
Thanks to @jni tip, i used:
`gh pr checkout 3288`
to get it locally!
I see skimage-regionprops being offered to update.
62 Available plugins. 4 installed
I can see napari-plot-profile just fine.
NB: In 4.10 I see 60 available, 8 installed (if I'm counting right)

**Comment by goanpeca** [comment]
@psobolewskiPhD thanks for checking. The way napari displayed installed plugins in 4.10 is different from 4.11

Now we display packages on top and bottom.

The only way to compare that amounts match is to make sure no plugins are installed. Then the available number of plugins should match

**Review by sofroniewn — APPROVED** [review]
LGTM! Thanks for fix!!

**Review by ppwadhwa — APPROVED** [review]
LGTM!  Also, opening in binder was pretty cool.  :)

**Comment by psobolewskiPhD** [comment]
Just installed 4.11rc3.
I am offered updates to plugins (yay!), but still not seeing the napari-plot-profile plugin:
image

Showing 54 available.
(BTW I love the [filter....] at the top!)

**Comment by goanpeca** [comment]
Thanks for testing @psobolewskiPhD 

---

@tlambert03 any thoughts on why that particular package is not appearing napari-plot-profile ?

**Comment by sofroniewn** [comment]
I see it on mine, not sure if there is platform specific stuff happening (i'm on mac)

image

I think we can release without more changes and then monitor if issue persists.

**Comment by psobolewskiPhD** [comment]
I also see it now:
image
Note that Available shows 62 and before was 54.
Not sure what's changed: same conda, same way to launch, same IP.

**Pull request merged**
