### PR TITLE
Update layer's loaded state before vispy and thumbnail

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description

This moves the update to `Layer.loaded` to be before rather than after the updates to the vispy layer and qt thumbnail. I made that change for a few reasons.

1. One of [the async slicing tests flaked](https://github.com/napari/napari/actions/runs/5424665334/jobs/9864350221#step:8:306) maybe because it was waiting on the vispy update and assumed that loaded would also be updated. 
2. Consistent with the previous definition of `Layer.loaded` with regards to the old async.
3. The vispy layers still read the layer's slice state (after `Layer.events.set_data`) has been emitted, and in [at least one case that includes `Layer.loaded`](https://github.com/napari/napari/blob/acddda2000ef6498731c4687cfb5ac60e378a68a/napari/_vispy/layers/labels.py#L11).

# References
Related to #4795

### CODE REVIEW

**Review by brisvag — CHANGES_REQUESTED** [review]
I get the practical reasons but... this just feels wrong? Isn't the whole point of `Layer.loaded` to signal that the canvas is in fact showing what you asked for? Should we instead consider having another event (say: `ready`) that does what you're asking (mark a layer as "just about to be rendered")?

**Comment by andy-sweet** [comment]
> I get the practical reasons but... this just feels wrong? Isn't the whole point of `Layer.loaded` to signal that the canvas is in fact showing what you asked for? Should we instead consider having another event (say: `ready`) that does what you're asking (mark a layer as "just about to be rendered")?

I don't have strong opinions about `Layer.loaded`, so I'm open to ideas here. I'd also be appreciative of any code examples using it to help clarify what it's actually for, especially most other slice/render state is not public.

But `Layer.loaded` has been around for a while (i.e. before the new async slicing), and it was not indicating state described above, instead the immediate slice state in the layer as in the docstring: https://github.com/napari/napari/blob/acddda2000ef6498731c4687cfb5ac60e378a68a/napari/layers/base/base.py#L535

It's also strange that `Layer` would have state related to the corresponding vispy layer because the ownership model is the other way round - i.e. the vispy layer owns the layer.

My suspicion is that we really want something like `Viewer.wait_until_layers_rendered`, which would effectively wait for all the layers to be loaded and then wait for any other Qt events to be processed.

**Comment by brisvag** [comment]
> My suspicion is that we really want something like `Viewer.wait_until_layers_rendered()`, which would effectively wait for all the layers to be loaded and then wait for any other Qt events to be processed.

Yup, 100% agree on this! Not sure what that means for this PR. I guess you're saying that either way (pre/post PR) my expectations about `layer.loaded` are wrong (i.e: no guarantee of the vispy canvas to be up to date)?

**Comment by andy-sweet** [comment]
> I guess you're saying that either way (pre/post PR) my expectations about `layer.loaded` are wrong (i.e: no guarantee of the vispy canvas to be up to date)?

Yes, mostly because that's how it was defined before by the docstring and the implementation.

We might be able to change its definition to ensure that it represents the rendered canvas state, but that depends on exactly how the vispy Qt backend is implemented. My assumption is that updating the vispy visual causes an event to be posted to the Qt main event loop, so you'd need to the extra call to `processEvents` (and maybe `sendPostedEvents`) to ensure that all pending events (like draws) are actually executed. Would be great to clarify if vispy makes any guarantees about that stuff like that.

I'm also not certain if this PR will fix the test flake, as there's another possible cause for that, which is that changing `current_step` causes the corresponding event to be fired twice. Will file a separate bug for that.

**Comment by andy-sweet** [comment]
> I'm also not certain if this PR will fix the test flake, as there's another possible cause for that, which is that changing `current_step` causes the corresponding event to be fired twice. Will file a separate bug for that.

Filed this bug: https://github.com/napari/napari/issues/6032

**Review by brisvag — APPROVED** [review]
Ok, color me convinced!

**Pull request merged**
