### PR TITLE
Fix dims order for clipping planes

### LINKED ISSUE #3767: ClippingPlanes uses vispy `x,y,z` convention and not napari's `z,y,x`
## 🐛 Bug

Experimental clipping planes API uses a different convention than our default.

## To Reproduce

1. Execute the code below:

```python3

import napari
from napari.layers.utils.plane import ClippingPlaneList
import numpy as np

shape = np.array((10, 50, 100))
image = np.arange(np.prod(shape)).reshape(shape)

center = shape / 2  # does not work
# center = np.flip(shape) / 2  # does work

cpl = ClippingPlaneList.from_bounding_box(center, dimensions=[5] * 3)

napari.view_image(image, experimental_clipping_planes=cpl, ndisplay=3)

napari.run()
```

## Expected behavior

I expected it to display a cube in the center of the canvas. It works when we flip the coordinates.

## Environment
```
napari: 0.4.11.dev374+gac3d85f5.d20211207
Platform: Linux-5.11.0-40-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.3 LTS
Python: 3.8.10 (default, Jun 4 2021, 15:09:15) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.1
Dask: 2021.06.2
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 460.73.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- console: 0.0.4
- napari-ome-zarr: 0.3.0
- napari-tracks-reader: 0.1.3
```

### PR DESCRIPTION
**Pull request by brisvag**
# Description
Fixes #3767.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM! Any chance of a test here? I can see how it might be tough on the vispy side of codebase, but thought I'd ask.

cc @JoOkuma

**Comment by brisvag** [comment]
We could do it with a screenshot I suppose, using code similar to the example in #3767? It seems a bit overkill, but I don't think there's another way (other than a stupid "check that `ViewerModel` and `Visual` have inverted clipping planes, maybe)?

**Comment by alisterburt** [comment]
I'm stuck on mobile for a bit so haven't been able to test

I'm sure this PR fixes the problem but it feels like the vispy behaviour of your clipping planes is what's unexpected/incorrect here, the visual has some attributes ordered zyx (volume data) and some xyz (the planes positions/normals). 

Am I thinking about this incorrectly? I remember inverting the order in both the setter and getter when I did the slicing plane stuff to get around the 'inversion' in the shader itself

Edit misremembered slightly, only changed in the setter

    @property
    def plane_position(self):
        """Position on a plane through the volume.

        A (3,) array containing a position on a plane of interest in the volume.
        The position is defined in data coordinates. Only relevant in
        raycasting_mode = 'plane'.
        """
        return self._plane_position

    @plane_position.setter
    def plane_position(self, value):
        value = np.array(value, dtype=np.float32).ravel()
        if value.shape != (3, ):
            raise ValueError('plane_position must be a 3 element array-like object')
        self._plane_position = value
        self.shared_program['u_plane_position'] = value[::-1]
        self.update()

**Review by kevinyamauchi — COMMENTED** [review]
The fix looks good to me!

I was having a bit of trouble following the code related to @alisterburt 's comment above, so I'd like to just confirm something. My understanding is that on the napari side, the order of the dims for all of the clipping planes parameters is in the data coordinates order (i.e., not "inverted") and the order of the dims is only flipped when the plane data is passed to the vispy node. Is that right?

> other than a stupid "check that ViewerModel and Visual have inverted clipping planes, maybe

I think this is a reasonable test to add, as it was the root cause of the issue here.

**Comment by alisterburt** [comment]
Yeah I think that'll be right once this PR is merged @kevinyamauchi

I'm just not sure the behaviour on the vispy note, I.e. the node expecting inverted data, is expected so I wanted to clarify 🙂 the example is what I'm doing for plane position, inverting only when actually passing the value to the shader. There the value on the node has the same order as the data on the node

**Comment by brisvag** [comment]
@alisterburt you remember right, but at the time the planes were defined in data space, so they HAD to be in the same coordinate system as the data.
Now, however, they are defined in world space, which added an additional complication: volumes in vispy use the opposite order (in data space) compared to other visuals. If you test with anything other than just a volume, you'll see (unless I messed up xD) that the clipping works the same way with all of them as is now!

**Comment by alisterburt** [comment]
Hahaha love it, okay, I'm not surprised that there's a bunch of additional complexity, glad you've got a handle on it! Happy to merge this and agree that a simple test would be ideal 🙂 thanks @brisvag !

**Comment by brisvag** [comment]
Actually, something's off. Do not merge this yet!

**Comment by brisvag** [comment]
Ok, it was just an issue due to not geing up to date with main. To summarize the issue at play:

- clipping planes in vispy volume used to be defined in data coordinates, which are reversed for volume, so we had to swap them
- now that clippign planes work on other visuals, they all use scene (=world) coordinates, which are automatically converted by each visual to the right system. This means that a plane working on a volume works the same on a different object, no matter what transformations are applied to it (i.e: a clipping plane is an entity in world coordinates).
- something went wrong between step 1 and 2 and I must have used vispy volume data-coordinate conventions instead of everything else's.
- Now it's fixed :) `examples/clipping_planes_interactive.py` works fine. Things on the *positive* side of the normal are shown, while things on the *negative* side are clipped, which is the intended behaviour.

**Comment by sofroniewn** [comment]
Sounds like @brisvag adding a simple test before merge might be good? Then this can go in

**Review by alisterburt — APPROVED** [review]
LGTM, thanks for adding the test @brisvag 🙂

**Pull request merged**
