### PR TITLE
PR: Close floating docks on close event

### LINKED ISSUE #2365: If napari closed with undocked windows, they never work on next launch
## 🐛 Bug
Now that settings saves various window states, a couple new bugs may appear. I just noticed that if you undock the layer list or the layer controls and quit napari, then on the next launch, even if you reshow those windows (since they will be hidden on launch), then they never work properly.  They are just blank rectangles...

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

Fixes https://github.com/napari/napari/issues/2365

@tlambert03 this is the easiest and simplest so far. Could you test this?

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
thanks!
I'm unable to figure out why just yet, but _sometimes_ when I close the viewer with either the layer list or the qt controls floating, the floating widget is not visible on the next launch.  This time though, when I unhide them, they do work fine.  Can't figure out how to repeat it just yet... let me know if you also see that?  Either way, this is good for merge by me!

**Comment by goanpeca** [comment]
>I'm unable to figure out why just yet, but sometimes when I close the viewer with either the layer list or the qt controls floating, the floating widget is not visible on the next launch. 

That is odd :-\ I tried several times and nothing like what you suggest. 

Happy to fix when we can reproduce ti :)

**Comment by tlambert03** [comment]
maybe some sort of race condition?  It happens for me more often than not when floating the layer controls:

https://user-images.githubusercontent.com/1609449/110727206-cad0a800-81e8-11eb-8987-1717d2842640.mov

**Comment by goanpeca** [comment]
Ok let me check. How did you quit Napari?

**Comment by tlambert03** [comment]
command Q

**Comment by goanpeca** [comment]
@tlambert03 can reproduce randomly with Cmd Q ... but weird haha

**Comment by goanpeca** [comment]
I have no idea what is going on, but it only happens with Cmd+Q

**Comment by goanpeca** [comment]
@tlambert03 I don't think that Cmd+Q and clicking the red x are doing the same thing, and hence the issues./

**Comment by goanpeca** [comment]
@tlambert03 I think I got it, could you check again :)

**Comment by tlambert03** [comment]
that does fix the problem, but it also means that if you close one viewer in a multiviewer state, you lose them all

**Comment by goanpeca** [comment]
>that does fix the problem, but it also means that if you close one viewer in a multiviewer state, you lose them all

Hmm ok well, not sure what to do, but calling quit_app on Cmd+Q and doing a different thing on closeEvent, is going to bite us on other things, so we need to make things uniform.

Open to suggestions :)

**Comment by sofroniewn** [comment]
> > that does fix the problem, but it also means that if you close one viewer in a multiviewer state, you lose them all
>
> Hmm ok well, not sure what to do, but calling quit_app on Cmd+Q and doing a different thing on closeEvent, is going to bite us on other things, so we need to make things uniform.

I'm coming to this a little late, so apologies if my proposal here is off the mark, reflects a misunderstanding. I just looked at how `preview` appears to do this on the mac, and it seems like cmd+q quits everything, closing multiple documents (in our case viewers). cmd+w closes individual documents. clicking the red x closes individual documents but doesn't quit - BUT - if you then tab the focus away with no documents open the app seems to quit ...

I'm not sure we have to match that behavior exactly. One option might be that cmd+q quits everything, cmd+w closes individual viewers, and if we close the only open viewer we then quit right away too, or we're ok being in a state with no viewers and we add an option to the menubar which is "create viewer" or something similar?

**Comment by goanpeca** [comment]
It makes sense @sofroniewn. Do you agree on that approach @tlambert03 ?

**Comment by tlambert03** [comment]
Yep, I thought that was the general pattern we are already aiming for.

**Comment by goanpeca** [comment]
@tlambert03 added some changes, would this address the multiple viewer closing issue?

Thanks!

**Comment by tlambert03** [comment]
perfect!

I think we've had this problem for a long time (in master), but I'll just note here that if you run the following script, and then close only one of the windows with Cmd-W, you can't close any of the other windows with cmd-W (you have to use the red x button). 
```python
import napari
v1 = napari.Viewer()
v2 = napari.Viewer()
v3 = napari.Viewer()
napari.run()
```

but this is already a big improvement.  we can address that elsewhere

**Comment by goanpeca** [comment]
>I think we've had this problem for a long time (in master), but I'll just note here that if you run the following script, and then close only one of the windows with Cmd-W, you can't close any of the other windows with cmd-W (you have to use the red x button).

@tlambert03 I just tried your example and using Cmd+W works on each one of them as expected 🤔

**Comment by tlambert03** [comment]
it will depend on how you're running it (framework build or not, for example).  On my system, with the example listed above as a script named `test.py`:

```sh
pythonw test.py  # works fine

python test.py  # fails

napari test.py  # works fine because `napari.__main__` will call pythonw if available
```

or with IPython, if I paste that text into ipython (without gui qt), then I get the command-w bug... however, if I paste into ipython with an active `%gui qt` loop, then it works as expected.

how were you running it?

**Comment by goanpeca** [comment]
Oh, I just opened a terminal `python` and typed things there :-p

**Comment by goanpeca** [comment]
On my system, (except ipython that I did not test) all work fine. Anyway :) 

Let me know if there is anything extra I should look into for this PR

**Comment by tlambert03** [comment]
yeah, not too concerned about fixing it here.  it's almost certainly OS and environment dependent.  thanks again

**Review by tlambert03 — APPROVED** [review]

**Pull request merged**
