### PR TITLE
add extras_require for bundle deps

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

---

This adds the dependencies installed in the `make_bundle` CI steps to `setup.cfg` to have them in a single place, and to simplify developer setup when debugging locally. I am going to be working on this on the coming weeks and had to hunt down the deps in the CI files. Hope it's ok as a first contribution!

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
🚀

**Comment by tlambert03** [comment]
thanks!
side note: also want to draw your attention to this little chunk of things here in `bundle.py`:

https://github.com/napari/napari/blob/ae7c5b6e1852c4cb3f5588b9a6550426b7021ae3/bundle.py#L22-L30

these are things that we want to include in the bundle (or override from our setup.cfg install requires).  They get added to the `briefcase.app.napari.requires` part of the (transient) pyproject.toml [here](https://github.com/napari/napari/blob/ae7c5b6e1852c4cb3f5588b9a6550426b7021ae3/bundle.py#L73-L86)

**Review by Carreau — APPROVED** [review]
Is that 0.4.11 Material or waiting for 0.4.12 ?

**Comment by jaimergp** [comment]
Thanks @tlambert03! One question. With this:

> side note: also want to draw your attention to this little chunk of things here in bundle.py [...]

Do you mean I should also add this to the `bundle` section or are those handled automatically by the script? I ran this locally and didn't run into any missing requirements error, so I am guessing it's handled by the script / briefcase?

**Comment by jaimergp** [comment]
nvm, I just realized what you meant. I have added those deps to `setup.cfg` too and refactored how `EXTRA_REQS` is populated!

**Comment by tlambert03** [comment]
Cool thanks!  Yeah, I was just drawing your attention to a somewhat weird thing (that it might be hard for someone to guess where to  look to find what additional packages gets put in the bundle).

You nailed it :) thanks

**Comment by jaimergp** [comment]
Thanks!

CI is failing for unrelated reasons (`setuptools_scm`, see [here](https://github.com/pypa/setuptools_scm/issues/608)).

**Review by sofroniewn — APPROVED** [review]
LGTM! I like having all deps in setup.cfg easier to track down, will merge now

**Pull request merged**
