### PR TITLE
Add checkbox to labels layer controls for displaying selected color mode

### PR DESCRIPTION
**Pull request by DragaDoncila**
# Description
Add checkbox next to label selection spinbox to allow user to toggle between selected and previous color mode as described in #1761 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by DragaDoncila** [comment]
@jni @sofroniewn I've removed the selected color mode as per comments on #1761 , I'm not sure if this is the desired approach so appreciate any comments

**Review by sofroniewn — COMMENTED** [review]
This is looking really good @DragaDoncila my only two suggestions are to rename `filter_to_selected` to be `show_selected_labels` and move the checkbox to the bottom right of the control panel and make a string label for it `show selected:`

**Comment by sofroniewn** [comment]
Follow up PRs could add the ability to have multiple selected labels (both in API and possible via dropdown in GUI)

**Review by sofroniewn — APPROVED** [review]
Ok, nice changes @DragaDoncila! I've also just fixed a check box location issue the @jni mentioned to me. It used to look like this

Screen Shot 2020-10-31 at 9 03 13 PM

now looks like this, which i think is much nicer

Screen Shot 2020-10-31 at 9 05 03 PM

I'm approving, @jni you can take out of draft and merge if it looks good to you!!

**Comment by DragaDoncila** [comment]
Only about 1000x nicer - thanks @sofroniewn ! That grid was really testing my patience...

**Pull request merged**
