### PR TITLE
Use briefcase 0.3.1 on all platforms

### PR DESCRIPTION
**Pull request by jni**
# Description

This is a temporary fix for #2965.

If anyone has ideas about how to test that bundles can get installs, that would be awesome. But for now we should just fix!

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
If anyone merges this, please reopen #2389. #2965 should probably be closed also in favour of a new issue tracking the longer-term fix, detailed in [this comment](https://github.com/napari/napari/issues/2965#issuecomment-871926379) and subsequent discussion.

**Comment by jni** [comment]
(Windows failure is unrelated.)

**Comment by liu-ziyang** [comment]
I suggest that we just remove the entire block instead, and so that macos would follow other distributions to install 0.3.1

(github suggest edits can't cover deleted lines but removing line 53 - 55)

**Comment by jni** [comment]
Thanks @ziyangczi! Is there any reason not to move the lot to 0.3.4?

**Comment by liu-ziyang** [comment]
> Thanks @ziyangczi! Is there any reason not to move the lot to 0.3.4?

no objection to upgrading, just that we didn't test 0.3.4 and there doesn't seem to be features added that would benefit us.

**Comment by jni** [comment]
Ok, you're right, I've just reverted everything to 0.3.1. @napari/core-devs this should be ready to be merged.

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Review by liu-ziyang — APPROVED** [review]

**Comment by jni** [comment]
@sofroniewn I've updated the title to better reflect what was actually done here. I think the release script grabs the PR title rather than the commit title, but something to keep in mind for the release notes!

**Pull request merged**
