### PR TITLE
Change layers.Markers to layers.Points

### LINKED ISSUE #334: API Proposal: rename Markers to Points
To my ears Markers has always sounded a bit ambiguous: I don't know immediately what the data type is. Even though our Points have attributes (unlike mathematical points) such as size and colour, I think it is clearer and fits in better with Vectors and Shapes than Markers.

Happy to be outvoted here but just wanted to raise it before 0.1.

### PR DESCRIPTION
**Pull request by kevinyamauchi**
# Description
As discussed in #334, this PR renames the `Markers` layer to `Points` layer. 

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# References
Closes #334 

# How has this been tested?
I ran all of the example files that were touched by this PR.
- [x] /examples/add_points.py
- [x] /examples/annotate-2d.py
- [x] /examples/to_svg.py
- [x] /examples/nD_points.py

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
@AhmetCanSolak, I need to update the .rst files for the docs (e.g., `napari.layers._markers_layer.rst`). Are those autogenerated or should I edit them manually?

edit: spoke with @AhmetCanSolak IRL - doc tree updated

**Review by sofroniewn — APPROVED** [review]
This looks great, tests are passing, I'm approving. Thanks @kevinyamauchi!

**Comment by kne42** [comment]
Seems like a lot of unrelated docs are changed but i guess it shouldnt make too much off a difference so it's fine

**Comment by sofroniewn** [comment]
It had been a while since we'd rebuilt the docs. I'm going to go ahead and merge

**Comment by kevinyamauchi** [comment]
@kne42 yeah, the doctree hadn't been rebuilt in a long time :/ There are some warnings that should probably be attended to, but I'll make a separate issue to address that.

**Pull request merged**
