### PR TITLE
Drag drop layers to rearrange

### PR DESCRIPTION
**Pull request by sofroniewn**
# What does this PR do? Why are doing this? References?
This PR adds support for dragging and dropping layer widgets to rearrange them. Rearranging them changes the order of display of the images in the canvas. Multiple widgets can be simultaneously selected and rearranged at the same time. During dragging the layer name appears by the cursor.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
- [ ] TestCase Run examples/layers.ipynb and manually drag and drop layer widgets

## Final Checklist:
- [x] My PR is the possible minimum work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kne42 — APPROVED** [review]
Looks great, thank you Nick!

Only comment I have is that I think it would seem more intuitive to have the divider appear when you're moving the layer back into its original place. i.e. I select a layer and try to move it around, currently a divider only appears before or after another layer if that space is not already adjacent to the selected layer.

**Comment by sofroniewn** [comment]
@kne42 - thanks! On the dividers appearing when moving the layer back. We could just have the closest divider always highlighted, not sure how everyone else feels. It's an easy change to make. We can also revisit in a future PR after we spend some time playing around with it. Maybe next time at biohub you show me exactly the behaviour you mean and I'll have a better understanding of it.

**Comment by kne42** [comment]
@sofroniewn Yeah that sounds reasonable. I will be at the Redwood City CZI office on Monday for a few hours though if you'd have time to chat :)

**Review by AhmetCanSolak — APPROVED** [review]
Thank you @sofroniewn !

**Pull request merged**
