### PR TITLE
Fix evented model array equality tests

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR will address the comment by @kevinyamauchi https://github.com/napari/napari/pull/2042#discussion_r567911985 around equality testing for models with arrays. Right now it only has tests.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
This seems quite challenging actually - if you look at the `__eq__` method in pydantic it is just taking the `.dict` method then doing the `==`, see https://github.com/samuelcolvin/pydantic/blob/43308d1b24c5d1163c44b8fa786d1b27e000c64e/pydantic/main.py#L850-L854

I'm not sure if we should just overwrite this ourselves completely? Thoughts @tlambert03? Any advice/ recommendations here appreciated

**Comment by tlambert03** [comment]
> I'm not sure if we should just overwrite this ourselves completely? Thoughts @tlambert03? Any advice/ recommendations here appreciated

yeah, it's a bit tricky.  I think we'll need to special case it (since it's just dict comparison).  ~We could take advantage of the `exclude` parameter in `dict()`, and pull out all array fields to compare them separately~ (see next comment for slightly better):

```python
class EventedModel(BaseModel):

    ...
    
    def __eq__(self, other) -> bool:
        import numpy as np

        array_fields = {
            n for n, f in self.__fields__.items() if _is_array(f.type_)
        }
        _dict = self.dict(exclude=array_fields)
        if isinstance(other, BaseModel):
            other_dict = other.dict(exclude=array_fields)
            if _dict == other_dict:
                
                return all(
                    np.array_equal(getattr(self, f), getattr(other, f))
                    for f in array_fields
                )
            return False
        else:
            # haven't worked on this part yet
            return _dict == other


def _is_array(obj):
    import numpy as np
    import dask.array as da

    return issubclass(obj, (np.ndarray, da.Array))
```

**Comment by tlambert03** [comment]
actually... now that we're using BaseModel instead of dataclasses ... we can take better advantage of the metaclass to detect if we're working with a model that has arrays, and only then override the `__eq__` method:

```python

def _is_array(obj):
    import numpy as np
    import dask.array as da

    return issubclass(obj, (np.ndarray, da.Array))


def make_eq(array_fields):
    def _eq_(self, other) -> bool:
        import numpy as np

        _dict = self.dict(exclude=array_fields)
        if isinstance(other, BaseModel):
            other_dict = other.dict(exclude=array_fields)
            if _dict == other_dict:

                return all(
                    np.array_equal(getattr(self, f), getattr(other, f))
                    for f in array_fields
                )
            return False
        else:
            # haven't worked on this part yet
            return _dict == other

    return _eq_


class _Meta(ModelMetaclass):
    def __new__(mcs, name, bases, namespace, **kwargs):
        cls = super().__new__(mcs, name, bases, namespace, **kwargs)
        array_fields = {
            n for n, f in cls.__fields__.items() if _is_array(f.type_)
        }
        if array_fields:
            cls.__eq__ = make_eq(array_fields)
        return cls


class EventedModel(BaseModel, metaclass=_Meta):
    ...
```

**Comment by sofroniewn** [comment]
> actually... now that we're using BaseModel instead of dataclasses ... we can take better advantage of the metaclass to detect if we're working with a model that has arrays, and only then override the __eq__ method:

@tlambert03 would this approach allow us to drop `__equality_checks__` and `from .dataclass import _type_to_compare, is_equal` that we use inside the event emission? Ideally we'd have just one unified way to do equality checking.

Also right now this is only relevant for our custom type [Array](https://github.com/napari/napari/blob/master/napari/utils/events/custom_types.py#L4) I wonder if we can't leverage that class more - i.e. add a special `__eq__` method to that type that then gets used here. It would keep all the numpy imports and calls localized to that class, which we'll probably need to extend as we think about supporting arrays of other types

**Pull request closed without merging**
