### PR TITLE
Cleanup list of non-translatable strings.

### PR DESCRIPTION
**Pull request by Carreau**
All those strings seem to not exists in the corresponding files.

### CODE REVIEW

**Review by andy-sweet — APPROVED** [review]
Looks good to me! If these were actually present the translation test should fail, right?

**Comment by Carreau** [comment]
Well it's already failing (#4640), but yes. 

This, #4733 and follow-up PR once those two are merged should make the trans test pass, but there are several dozen of errors that need manual inspection.

**Comment by andy-sweet** [comment]
Sounds good. Feel free to merge this when you're ready.

**Review by sofroniewn — APPROVED** [review]
LGTM! Looks like this feel through cracks so i will merge now

**Pull request merged**
