### PR TITLE
MAINT: Don't deprecate something that was never stable.

### PR DESCRIPTION
**Pull request by Carreau**
Interpolation2d is new since 0.4.17, so technically we could can directly fail if interpolation2d is set to bilinear and move the warning to the interpolation setter to keep backward compatibility.

This way we should never have users of interpolation2d that set an incorrect value.

See also #5067 sibling PR

### CODE REVIEW

**Comment by Carreau** [comment]
Failure on ubuntu-latest 3.9 pyside6  likely due to #5069 (new version of shiboken)

**Comment by brisvag** [comment]
~It should also warn if someone sets `interpolation3D` by using the deprecated `interpolation` setter when `ndisplay` is 3.~ actually, I guess it never was ok because 3d only accepted linear?

**Review by andy-sweet — APPROVED** [review]
Good catch @Carreau! Agreed that not allowing something `layer.interpolation2d = 'bilinear'` and capturing the deprecated usage of `layer.interpolation = 'bilinear'` entirely in the deprecated `interpolation` attribute is preferred.

**Comment by andy-sweet** [comment]
As we'd like this in v.0.4.17 and it would be great to test it in the first release candidate, I will likely merge after a few hours and break the typical 24 hour rule. If it's disputed we can always revert or update this commit for a future release candidate before release.

**Comment by andy-sweet** [comment]
Also, I think this effectively replaces #5067, since a deprecation is not needed there after this is merged, so we can close that too.

**Pull request merged**
