### PR TITLE
Bump app-model

### PR DESCRIPTION
**Pull request by Czaki**
# Description

there was a bug in app-model fixed in https://github.com/pyapp-kit/app-model/pull/122 that raises exceptions on the open file menu

### CODE REVIEW

**Comment by Czaki** [comment]
@tlambert03 did you have any opinion about bump upper bound?

**Comment by tlambert03** [comment]
nope, your call.  The original upper bound was there by your request for 0.4.17.... so if you want to create a new upper app-model upper bound for the next version of napari (and update the corresponding issue at app-model indicating the new contract https://github.com/pyapp-kit/app-model/issues/50) that's fine.

**Comment by Czaki** [comment]
@napari-bot update constraints

**Review by kne42 — APPROVED** [review]

**Comment by brisvag** [comment]
> @napari-bot update constraints

^

**Pull request merged**
