### PR TITLE
[WIP] Optimize transforms

### PR DESCRIPTION
**Pull request by kephale**
# Description

A set of optimizations for `napari.utils.transforms`.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by kephale** [comment]
@aganders3

**Comment by kephale** [comment]
This shows the bug introduced by caching. Based on the discussion with @aganders3 we probably need to just add some more `_clean_cache` calls. I haven't dug through them all, but adding the recent ones led to less jumping behavior.

In this demo I'm moving my scroll wheel one notch at a time, but you can see some big jumps that do not typically happen.
https://user-images.githubusercontent.com/400105/198729413-b3c1d98d-f979-4dc1-a08a-4b3b079a9c3b.mov

**Comment by aganders3** [comment]
> Based on the discussion with @aganders3 we probably need to just add some more _clean_cache calls.

I'm not so sure now. I tried adding all the mixins and abstract methods for the `MutableSequence` interface and still saw issues. I'm guessing some of the transforms are mutated within the chain somewhere but I'm not familiar enough with the codebase to know off the top of my head. I think there should still be a way to safely cache this but need to play around with it.

**Comment by aganders3** [comment]
Here's another micro-optimization that would apply to any `TypedMutableSequence`. The idea is that type checking can be skipped because `__newlike__` is private and only used on instances that have already been checked.
```
diff --git a/napari/utils/events/containers/_typed.py b/napari/utils/events/containers/_typed.py
index 9da4f794..66e3cd6a 100644
--- a/napari/utils/events/containers/_typed.py
+++ b/napari/utils/events/containers/_typed.py
@@ -167,7 +167,8 @@ class TypedMutableSequence(MutableSequence[_T]):
         # seperating this allows subclasses to omit these from their `__init__`
         new._basetypes = self._basetypes
         new._lookup = self._lookup.copy()
-        new.extend(iterable)
+        # skip type checking as it should have been done on initial construction
+        new._list.extend(iterable)
         return new
 
     def copy(self) -> 'TypedMutableSequence[_T]':
diff --git a/napari/utils/transforms/transforms.py b/napari/utils/transforms/transforms.py
index aecb7f15..656af080 100644
--- a/napari/utils/transforms/transforms.py
+++ b/napari/utils/transforms/transforms.py
@@ -126,9 +126,6 @@ class TransformChain(EventedList, Transform):
     def __call__(self, coords):
         return tz.pipe(coords, *self)
 
-    def __newlike__(self, iterable):
-        return TransformChain(iterable)
-
     @property
     def inverse(self) -> 'TransformChain':
         """Return the inverse transform chain."""
```
This provides a substantial speedup when indexing a `TransformChain` with a slice (for example), though I'm not really sure it's meaningful/impactful in any real world use.

**Comment by aganders3** [comment]
So clearly the above didn't work 😆 - I'm going to make sure I understand more about the events, etc. before taking another crack at this.

**Comment by kephale** [comment]
Lol, yeah, that was my feeling. We don't need to rush anyway.

**Pull request closed without merging**
