### PR TITLE
Add pydantic<2 constrains to plugin install

### PR DESCRIPTION
**Pull request by Czaki**
# Fixes/Closes

Closes #

# Description

Based on the discussion in https://github.com/pydantic/pydantic/discussions/5402, I would like to add pydantic constraints to the plugin install mechanism. I prefer to crash installation process than the napari installation.  

# References

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by Czaki** [comment]
@jaimergp It will be nice to port this to the new package

**Comment by jaimergp** [comment]
Thanks for the ping! I would even consider adding the PR there in the new repo directly!

**Comment by Czaki** [comment]
First I prefer to have reviewed it here to check if people are ok with this change.

**Comment by jni** [comment]
LGTM but I agree with @jaimergp let's just do this in the new repo?

**Comment by jni** [comment]
btw does the cookiecutter have the constraint already? That's also a good idea

**Comment by Czaki** [comment]
> LGTM but I agree with @jaimergp let's just do this in the new repo?

As I would like to backport it to 0.4.18 release and I think that in 0.4.18 we should keep the plugin manager inside (I hope that we could start working on 0.4.18 fast)

**Comment by jni** [comment]
Oh yeah that's a very good point, thanks for thinking about it @Czaki !

**Review by brisvag — APPROVED** [review]

**Pull request merged**
