### PR TITLE
Add 3D image with non-default 3D interpolation

### LINKED ISSUE #3551: 3D interpolation mode cannot be set at layer creation time
## 🐛 Bug

Using `viewer.add_image(image, interpolation='nearest')` when the viewer is in 3D mode doesn't work.

```python
import numpy as np
import napari

image = (np.random.random((5, 5, 5)) > 0.7).astype(int)

viewer = napari.viewer(ndisplay=3)
image_layer = viewer.add_image(image, interpolation='nearest')
# image_layer.interpolation = 'nearest'  # uncomment to get correct interpolation

napari.run()
```

napari info

```
napari: 0.4.12.dev18+gc53f34e85
Platform: macOS-11.4-x86_64-i386-64bit
System: MacOS 11.4
Python: 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:58:46)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.9.3

OpenGL:
  - GL version:  2.1 ATI-4.5.14
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2304x1296, scale 2.0
  - screen 2: resolution 1792x1120, scale 2.0

Plugins:
  - animation: 0.0.2
  - console: 0.0.4
  - napari-midi: 0.1.dev5+g16c91f6.d20210914
  - napari-ome-zarr: 0.3.0
  - nd2-reader: 0.0.6
  - platelet-unet-watershed: 0.0.3
  - scikit-image: 0.4.12.dev18+gc53f34e85
  - svg: 0.1.5
  - tracks: 0.0.2
  - zarpaint: 0.2.0
```

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description

This is a simple, but ugly, fix for #3551 where the interpolation setter always updates the 2D interpolation with the passed value and updates the 3D interpolation only if the value is a valid 3D interpolation mode. Some downsides of this solution are:
- if we're trying to set the 3D interpolation mode, but pass an invalid value, this will not change it silently (i.e. raising an exception, or at least warning would be preferred)
- there is some asymmetry between the interpolation getter and setter
- need some special handling for linear/bilinear correspondence

I think the slightly harder, but better long term fix is to change the `Image.interpolation` property to behave in a simpler way that does not depend on `_ndisplay`. E.g. by defining separate `interpolation2d` and `interpolation3d` properties. But I'm unsure of the history of this property, so might be missing something.

Also open to other ideas!

I'm marking this as draft because I'm unsure what direction to go in here.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
Closes #3551 

# How has this been tested?
- [ ] all existing tests pass with my change
- [ ] the new test to cover the desired behavior passes

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by andy-sweet** [comment]
@brisvag : assigning to you as a core-dev with more experience than me here. I think this initial solution is a bit straw man for you to take down, but wanted to get some input before doing more work.

**Comment by brisvag** [comment]
> I think the slightly harder, but better long term fix is to change the `Image.interpolation` property to behave in a simpler way that does not depend on `_ndisplay`. E.g. by defining separate `interpolation2d` and `interpolation3d` properties. But I'm unsure of the history of this property, so might be missing something.

Yeah, I think we should target the property from the beginning. See also #2852 for another place where this came up.

*Ideally* we could merge vispy/vispy#2322 and then we can use the same interpolation for both :P. On the other hand, interpolations that use big kernels (e.g: `spline36` work fine with 2D data but might cripple your GPU in 3D. So there's an argument to be made about keeping this separate in the interest of not killing the viewer when swithcing ndisplay.

**Comment by andy-sweet** [comment]
If you think https://github.com/vispy/vispy/pull/2322 is close, maybe my latest straw man could work? I made the interpolation setter always update the 2d mode and update the 3d mode if it can. But I still kinda hate it.

Otherwise, I'll just implement the two property solution.

**Comment by brisvag** [comment]
> I made the interpolation setter always update the 2d mode and update the 3d mode if it can. But I still kinda hate it.

Yeah, that's quite ugly, I agree :/

> If you think [vispy/vispy#2322](https://github.com/vispy/vispy/pull/2322) is close, maybe my latest straw man could work?

I think in terms of functionality it's basically done; we need to find some time (with help from @djhoese) to push it over the line and get a release out :) I think the main blockage now will come from making sure that we're not messing up nor overcomplicating the `Volume` interface.

**Comment by andy-sweet** [comment]
OK, sounds like it's worth waiting on https://github.com/vispy/vispy/pull/2322 for #3551 and #2852. After https://github.com/vispy/vispy/pull/2322 is in, we can just have one `interpolation` property that is used for both 2D and 3D rendering.

I'd hate to introduce separate properties for 2D and 3D interpolation, then deprecate/remove them.

If we find that we do need 2 separates ones (e.g. because certain interpolation modes are very slow for 3D), then we can add them then.

Therefore, I'm closing this PR.

**Pull request closed without merging**
