### PR TITLE
Docker: Update xpra's apt too

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

## Type of change

- [X] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Docker jobs are failing on `main`.

Follow up to https://github.com/napari/napari/pull/4568, where Ubuntu's image was updated from v20 to v22. Unfortunately, this means that the codename changed from `focal` to `jammy`, and that needs to be reflected in the Xpra APT definitions below.

# How has this been tested?

- [ ] CI passes on PR.
- [ ] Removed temporary CI triggers for PR.

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by Czaki — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
@jaimergp 
I'm trying this docker image and getting a blank window for napari:

**Comment by psobolewskiPhD** [comment]
Actually, maybe this is the relevant part:
```
2023-07-24 16:06:36 Traceback (most recent call last):
2023-07-24 16:06:36   File "/usr/lib/python3/dist-packages/xpra/server/source/client_connection.py", line 300, in encode_loop
2023-07-24 16:06:36     fn_and_args[1](*fn_and_args[2:])
2023-07-24 16:06:36   File "/usr/lib/python3/dist-packages/xpra/server/window/windowicon_source.py", line 225, in compress_and_send_window_icon
2023-07-24 16:06:36     image = image.resize((rw, rh), Image.ANTIALIAS)
2023-07-24 16:06:36 AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
2023-07-24 16:06:36 2023-07-24 20:06:36,233 Error during encoding:
2023-07-24 16:06:36 Traceback (most recent call last):
2023-07-24 16:06:36   File "/usr/lib/python3/dist-packages/xpra/server/source/client_connection.py", line 300, in encode_loop
2023-07-24 16:06:36     fn_and_args[1](*fn_and_args[2:])
2023-07-24 16:06:36   File "/usr/lib/python3/dist-packages/xpra/server/window/windowicon_source.py", line 225, in compress_and_send_window_icon
2023-07-24 16:06:36     image = image.resize((rw, rh), Image.ANTIALIAS)
2023-07-24 16:06:36 AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
2023-07-24 16:06:36 2023-07-24 20:06:36,238 Error during encoding:
2023-07-24 16:06:36 Traceback (most recent call last):
2023-07-24 16:06:36   File "/usr/lib/python3/dist-packages/xpra/server/source/client_connection.py", line 300, in encode_loop
2023-07-24 16:06:36     fn_and_args[1](*fn_and_args[2:])
2023-07-24 16:06:36   File "/usr/lib/python3/dist-packages/xpra/server/window/windowicon_source.py", line 225, in compress_and_send_window_icon
2023-07-24 16:06:36     image = image.resize((rw, rh), Image.ANTIALIAS)
2023-07-24 16:06:36 AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

Also, as an aside, pip shows it's napari 0.4.17 but the image is tagged 0.4.18 on ghcr.io

**Comment by psobolewskiPhD** [comment]
I was able to use a bash ENTRYPOINT to install pillow 9.5.0 to fix the errors (it's patched in XPRA repo already but not released) but still no napari on screen which is sad.

**Comment by jaimergp** [comment]
Thanks @psobolewskiPhD, can you open an issue (here or on packaging)? I'll take a look later this week.

**Pull request merged**
