### PR TITLE
Add instant hover tooltips

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).
napari

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
love it.

wanna add to `QtPluginSorter.info` in this PR?  or another one?

**Comment by goanpeca** [comment]
I can do for this one, but where should I put the widget, since it would be used by other ones?

**Comment by tlambert03** [comment]
> but where should I put the widget, since it would be used by other ones?

🤷‍♂️  i trust your judgement :)

**Comment by goanpeca** [comment]
`_qt/widgets/qt_tooltip.py` ?

**Comment by goanpeca** [comment]
>🤷‍♂️ i trust your judgement :)

Oh mr you have made that mistake before 😆

**Comment by tlambert03** [comment]
> _qt/widgets/qt_tooltip.py ?

works for me!

**Comment by Czaki** [comment]
add to public interface?

**Comment by sofroniewn** [comment]
We've got some test fails here - isort and Qt ones, i havn't looked at what's causing them, but hopefully not too bad. otherwise this seems great!

**Comment by goanpeca** [comment]
I missed those fails, looking at them now!

**Comment by goanpeca** [comment]
Fixed @sofroniewn :)

**Review by sofroniewn — APPROVED** [review]
Works great for me! Thanks!! I will merge soon to get this in next rc, thanks!!

**Pull request merged**
