### PR TITLE
refresh when canvas_size_limits are changed

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# References and relevant issues
If you change `canvas_size_limits` programmatically, nothing happens.
You need to interact with the canvas. 
This is a bit confusing when using a notebook, ipython, etc. because it appears it doesn't work or the size limits are not correct.

# Description
Uses `self.node.update()` in ` _on_canvas_size_limits_change`

### CODE REVIEW

**Review by brisvag — CHANGES_REQUESTED** [review]
`refresh` is pretty heavy-handed; when events are present, they should be used instead and things should be handled on the vispy side. Try instead adding a `self.node.update()` in `_canvas_size_limits_change` in `_vispy/layers/points.py`; does it fix the issue?

**Comment by psobolewskiPhD** [comment]
Thanks @brisvag that works!

Question: I just noticed that when using `canvas_size_limits` the highlight doesn't match the new size.
(previously the points i was trying to visualize were not selected so I didn't notice)
That doesn't look trivial to fix-- should I make an issue?

**Comment by brisvag** [comment]
I noticed that too recently... I must have messed up something on a similar vein to this issue here ^^' Yeah please open an issue and tag me!

**Review by brisvag — DISMISSED** [review]

**Comment by brisvag** [comment]
This was superseded by https://github.com/napari/napari/pull/6853, right @psobolewskiPhD ?

**Comment by psobolewskiPhD** [comment]
I don't think so, this was trying to solve the displayed markers not being updated when changing the limits programmatically -- like in a notebook. I'll check on main later today sometime.

**Comment by psobolewskiPhD** [comment]
Just checked, this is still needed.
To test, launch napari, make a points layer and add a few points.
then use `viewer.layers[0].canvas_size_limits= (50, 1000)` in the console
you will have to mouse over or interact with the viewer to get it to update.

**Review by brisvag — APPROVED** [review]

**Pull request merged**
