### PR TITLE
Update Labels layer keybindings to be more ergonomic

### PR DESCRIPTION
**Pull request by AbigailMcGovern**
# Description
This PR addresses issue #2800, which suggested using numeric keybindings for labels tools. I have taken a similar approach to that outlined by @haesleinhuepf, but have used numbers 1-5 on the left side of the keypad. The numbers correspond to the left-to-right order of the tool icons in the interface. 

The new keybindings are as follows:
- "1" - erase
- "2" - fill
- "3" - paint
- "4" - pick
- "5" - pan zoom
- "-" - decrement selected label number (minus sign)
- "=" - increment selected label number (plus sign)

image
*The graphics aren't quite up to scratch when compared to #2800* 😄 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
Issue #2800 

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by alisterburt — COMMENTED** [review]
Awesome @AbigailMcGovern (and that keymap template @haesleinhuepf! 😍) - looks like to fix tests you will just need to modify the value for the number of methods expected on the labels layer, from `14` to `21`, then we should be good to go!

https://github.com/napari/napari/blob/524491430cb48b629d9d3d20f2b56a8b2f3de57c/napari/_tests/test_viewer.py#L87-L95

**Comment by sofroniewn** [comment]
Hi @AbigailMcGovern thanks for giving this a go - I know it was requested by @haesleinhuepf.

We've actually moved away from the explicit `bind_key` syntax. Instead we now register actions that then get shortcuts here https://github.com/napari/napari/blob/524491430cb48b629d9d3d20f2b56a8b2f3de57c/napari/utils/shortcuts.py.

I'm not sure if we now support multiple shortcuts for each action, but I might be more inclined to just leave this up to the user rather than add these in too. We could change our defaults, but I'm not sure. Maybe @jni can weigh in too.

**Review by sofroniewn — CHANGES_REQUESTED** [review]
See comment above about using shortcuts not bind_key decorator

**Comment by jni** [comment]
We should use the new architecture by all means @AbigailMcGovern but @sofroniewn I do think we should make this the new default, for the reasons outlined by @haesleinhuepf in the original issue. @AbigailMcGovern and I have proofread volumes using both built-in and modified shortcuts, and it's night and day — having the shortcuts mapped to adjacent keys is game-changing for the ergonomics.

**Comment by haesleinhuepf** [comment]
I just wanted to say: Thanks so much @AbigailMcGovern! I ❤️ this PR 🙂

**Comment by sofroniewn** [comment]
Ok, we can change the defaults. But then I think we should move to numerical defaults across all layers. It's strange if pan-zoom on points is a letter, but an unrelated number of labels. I think this will confuse a lot of folks otherwise.

Can we maybe get rid of these at the same time too https://github.com/napari/napari/blob/3bd58bde6858eb4d9f916fe32df262a4ebe1a24f/napari/layers/labels/_labels_key_bindings.py#L87-L124

I really don't like that pressing a modifier key changes the mode even if temporarily.

**Comment by jni** [comment]
@sofroniewn

> I really don't like that pressing a modifier key changes the mode even if temporarily.

Um, didn't you implement "hold space to pan/zoom"? 😂 

At any rate, I'm not deathly opposed to doing that, but preserve labels in particular came from a user request and I'd like to discuss it as a separate issue/PR rather than bundle its removal here...

Sorry @AbigailMcGovern, hold please as we sort ourselves out... 😂

**Review by sofroniewn — APPROVED** [review]
LGTM!

> Um, didn't you implement "hold space to pan/zoom"? 😂

I actually didn't mean that one - I don't consider space a modifier key - but meant the ones like shift, control, alt that @AbigailMcGovern just dropped.

I actually like where this PR is right now and am fine with merging as is 🚀

**Comment by sofroniewn** [comment]
> I actually like where this PR is right now and am fine with merging as is 🚀

Oh once, tests a fixed :-) As noted above https://github.com/napari/napari/pull/3072#pullrequestreview-710803157 the number of expected keybindings has now changed and the tests need to be updated. Should be a quick fix.

This all good with you then @jni?

**Comment by jni** [comment]
@AbigailMcGovern, @sofroniewn and I had a long chat about this. He is concerned about two things:

(1) if we are going to tie shortcuts to the order of icons on the screen, then we should make sure the ordering makes sense. Right now things are basically where they landed when we first implemented the layer. 😂 Specifically: (a) it makes sense for paint and fill to be next to each other. (b) it makes sense for erase and paint to be next to each other. So this argues that the ordering should be erase-paint-fill-pick-panzoom.

(2) additionally, we probably want to then make sure that the buttons and shortcuts match up across layers. For example, selection should match up across points and shapes. Buttons that are *not* mode switches should not be part of the same part of the UI (for example, points deletion).

With the modifiers, I misunderstood his concern: the problem is that modifiers are used in other shortcuts, so we don't want modifier keys to temporarily switch modes, because e.g. typing Ctrl-C would see the mode flicker on and off when the user had no intention to deal with the mode. Instead the modifiers could either be read by the mouse event directly and the layer behaviour would be modified, *or*, we could use different hold keys.

I think point (2) should be done in different PRs to keep them all focused. So for this one, still to be done:

- swap around the order of the paint and fill buttons
- fix the failing tests

Personally, I would move the hold-modifier removal to its own separate PR, so that it's easy for users to find the change in release notes.

**Comment by jni** [comment]
Thanks @AbigailMcGovern! Since @sofroniewn already approved this I'm going to merge, and make a follow-up issue to bring the remaining layers in line with these changes.

**Pull request merged**
