### PR TITLE
PR: Fix close window handling for non-modals

### LINKED ISSUE #2527: Better handling of `cmd-W` with multiple non-modal windows
## 🐛 Bug

The addition of some new non-modal windows is revealing a little bug in our handling of window keyboard shortcuts like command-W.  As an example, if you were to hit command-comma to open the preferences window, I would expect command-w to then close the preferences window and return you to what you were doing.  However, command-w is tied to the `viewer.window._qt_main_window`, and since the app is set to quit when the last main window is closed, the entire program just quits (assuming you have only one viewer).

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

Fixes #2527

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Just checked it, works great for me!

I'm curious though could we also get `cmd-w` to work for our modal dialogs, like the `napari-info` screen (accessible with `cmd-/`). That still doesn't close with `cmd-w`, but it might be nice

**Comment by goanpeca** [comment]
>I'm curious though could we also get cmd-w to work for our modal dialogs, like the napari-info screen (accessible with cmd-/). That still doesn't close with cmd-w, but it might be nice

@sofroniewn that is part of the larger discussion on fowrarding actions to all modals, either on the base dialog class, but I suggest we wait for the actions manager work to be merged so that we can use it to get the global actions and then forward them to all dialogs.

**Comment by sofroniewn** [comment]
> @sofroniewn that is part of the larger discussion on fowrarding actions to all modals, either on the base dialog class, but I suggest we wait for the actions manager work to be merged so that we can use it to get the global actions and then forward them to all dialogs.

Sounds good, I'm fine merging this PR as is and we can then continue this work after the actions manager etc. Thanks for the explanation!!

**Review by tlambert03 — APPROVED** [review]
as advertised!

**Pull request merged**
