### PR TITLE
Block zarr 3.0.0a1 and 3.0.0a2 in pre-release tests

### LINKED ISSUE #7193: [test-bot] pip install --pre is failing
The --pre Test workflow failed on 2024-08-31 12:21 UTC

The most recent failing test was on windows-latest py3.12 pyqt6
with commit: 6e292a8a05f2d195882288d4629695047896f20c

Full run: https://github.com/napari/napari/actions/runs/10645077004

(This post will be updated if another test fails, as long as this issue remains open.)

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues
closes #7193

# Description

When try to fix zarr problems with zarr 3.0.0 in #7215 I have found that it is not easy with this release, so I prefer to block 3.0.0a1 release and open issue in zarr

### CODE REVIEW

**Comment by Czaki** [comment]
@napari-bot update constraints

**Comment by Czaki** [comment]
Pydantic 2.9.0b1 now crashing the tests...

**Review by Czaki — COMMENTED** [review]
block 3.0.0a2

**Comment by jni** [comment]
Will you also block pydantic @Czaki?

**Comment by Czaki** [comment]
> Will you also block pydantic @Czaki?

The pydantic 2.9.0b2 solves the reported bug and I do not want to block 2.9.0b1 because of this bug https://github.com/astral-sh/uv/issues/6640

**Review by jni — APPROVED** [review]

**Pull request merged**
