### PR TITLE
Start work on touch events (pinch to zoom and co).

### PR DESCRIPTION
**Pull request by Carreau**
This does need to use a fork of of vizpy,I'll send pull request to vispy
progressively and try to make it work both on stable and master of
vispy.

Currently need https://github.com/vispy/vispy/pull/1968

I'll try to thread that into the canvas to various dimensions but still
try to wrap my head around napari codebase.

### CODE REVIEW

**Comment by sofroniewn** [comment]
Nice @Carreau as mentioned in meeting, I'm curious your take on #1987 and how it influences how you think about this on the napari side

**Comment by Carreau** [comment]
This now contains a draft when pinch and 2 finger scroll are bound to the 2d camera zoom and pan.

**Comment by jni** [comment]
@Carreau to clarify, that's *wonderful* when using a compatible trackpad, but for mouse wheels it is a massive breaking change — does this leave the behaviour with mice unchanged?

**Comment by Carreau** [comment]
> @Carreau to clarify, that's _wonderful_ when using a compatible trackpad, but for mouse wheels it is a massive breaking change — does this leave the behaviour with mice unchanged?

Not currently yet; I was just trying to get it to work first :-) 
The "pinch to zoom" could be always on; as it will work only on compatible trackpads; 
I'm planning on making the mouse_wheel to zoom or pan configurable.

This hooks into a larger discussion; is there a way to also configure which mouse/trackpad-motion-event is bound to which action on the user side.

From the above it looks like 1/2 of the events (camera motions) are directly configured deep in vispy, and it's relatively difficult to intercept them depending on some of the UI element that are clicked/ selected.

**Comment by Carreau** [comment]
I've also opened `https://github.com/vispy/vispy/pull/1980` to try to make it easier to handle touch events.

**Pull request closed without merging**
