### PR TITLE
Update the sliders `axis_label` widget to be a `QElidingLineEdit` instance

### PR DESCRIPTION
**Pull request by dalthviz**
# Description

This adds eliding text capabilities to the sliders axis labels widget.

A preview:

GIF showing how the text of the sliders axis labels is elided adding three dots add the end of it in case the width available is not enough to show the full text. When editing, the text is restored to show its full version and when focused out the axis label shows again the elided version of the text

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

Follow up of PR #5640 for detected issues related with the sliders `axis_label` width and text management (https://github.com/napari/napari/pull/5640#pullrequestreview-1348876666)

Depends on https://github.com/pyapp-kit/superqt/issues/152

# How has this been tested?

- [x] all tests pass with my change
- [x] I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by andy-sweet** [comment]
I should be able to take a look at this next week, but it might worth considering contributing the elided line edit to superqt, since that's an upstream dependency of napari and already has the more common [elided label](https://github.com/pyapp-kit/superqt/blob/main/src/superqt/_eliding_label.py).

**Review by psobolewskiPhD — APPROVED** [review]
Thanks @dalthviz

**Comment by brisvag** [comment]
Sorry, I marked `ready to merge` but didn't realize @andy-sweet wanted to check up on this again. Waiting for him to merge!

**Review by andy-sweet — APPROVED** [review]
Looks great! Thanks for your patience on this one!

**Pull request merged**
