### PR TITLE
Fix error when binding multiple connections

### LINKED ISSUE #1292: UnboundLocalError in create_worker
## 🐛 Bug

When creating a local worker with multiple yield connections, I get an unboundlocalerror:

```pytb
-------------------------------------------------------------------------
UnboundLocalError                       Traceback (most recent call last)
<ipython-input-23-1749d5f75cac> in <module>
     52 
     53 viewer.window.add_dock_widget(loss_canvas)
---> 54 worker = train(model, data_loader, 500)

~/projects/napari/napari/_qt/threading.py in worker_function(*args, **kwargs)
    628         kwargs['_worker_class'] = kwargs.get('_worker_class', worker_class)
    629         kwargs['_ignore_errors'] = kwargs.get('_ignore_errors', ignore_errors)
--> 630         return create_worker(function, *args, **kwargs,)
    631 
    632     return worker_function

~/projects/napari/napari/_qt/threading.py in create_worker(func, _start_thread, _connect, _worker_class, _ignore_errors, *args, **kwargs)
    505             if not isinstance(val, (tuple, list)):
    506                 _val = [val]
--> 507             for v in _val:
    508                 if not callable(v):
    509                     raise TypeError(

UnboundLocalError: local variable '_val' referenced before assignment
```

napari info:

```
napari: 0.3.2rc0
Platform: Linux-4.15.0-29-generic-x86_64-with-glibc2.10
Python: 3.8.2 (default, Mar 26 2020, 15:53:00) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.0rc1
SciPy: 1.4.1
Dask: 2.15.0
VisPy: 0.6.4

GL version: 3.0 Mesa 19.2.8
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.4
- ome_zarr: 0.0.7
- svg: 0.1.2
```

### PR DESCRIPTION
**Pull request by jni**
Fixes #1292

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] ~~New feature (non-breaking change which adds functionality)~~
- [ ] ~~Breaking change (fix or feature that would cause existing functionality to not work as expected)~~
- [ ] ~~This change requires a documentation update~~

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jni** [comment]
This should get into 0.3.2.

**Comment by jni** [comment]
Hmm, the macOS failure is concerning:

```
napari/utils/_tests/test_notebook_display.py::test_nbscreenshot Fatal Python error: Segmentation fault
```

Looks like we've again added a few extra sporadic failures to our suite... :frowning_face: 

btw @tlambert03 any chance you could look at adding tests for #1210, maybe directly on this PR? Looks like we missed adding tests to that before merging. I knew I shouldn't have overlooked that coverage task! :joy: I'm happy to look at it also but not sure if I'll have time before bed today. (Currently at OME2020 along with @sofroniewn.)

**Review by tlambert03 — APPROVED** [review]
Oh man... thanks. That was silly

**Comment by tlambert03** [comment]
Will look at tests soon

**Comment by tlambert03** [comment]
> Hmm, the macOS failure is concerning:

I don't think that's related to my threading? I wonder if maybe we should be closing the BytesIO stream before returning the image in `_repr_png_` [here](https://github.com/napari/napari/blob/d890f6378eed4387808826fc969b163577ad83f2/napari/utils/notebook_display.py#L73-L76)?

**Pull request merged**
