### PR TITLE
Fix `ImportError: lxml.html.clean module is now a separate project lxml_html_clean` over test suite (Ubuntu 20.04 and benchmarks)

### LINKED ISSUE #6798: `ImportError: lxml.html.clean module is now a separate project lxml_html_clean` over test suite (Ubuntu 20.04 and benchmarks)
## 🧰 Task

Seems like the latest release of `lxml` (5.2.0) moved a module to be an independant package (`lxml.html.clean` -> new `lxml_html_clean` package)? See https://github.com/napari/napari/actions/runs/8510883283/job/23309875720?pr=6794#step:11:174 and https://github.com/napari/napari/actions/runs/8510883283/job/23309397479?pr=6794#step:8:144

### PR DESCRIPTION
**Pull request by dalthviz**
# References and relevant issues

Part of #6798

# Description

Fix test suite by adding new `lxml_html_clean` dependency due to `lxml` 5.2.0 moving the `lxml.html.clean` module to that package (`lxml_html_clean`)

### CODE REVIEW

**Review by psobolewskiPhD — COMMENTED** [review]
Thanks for the quick PR @dalthviz 
I think based on https://lxml.de/5.2/changes-5.2.0.html

> Projects that use lxml without "lxml.html.clean" will not notice any difference, except that they won't have potentially vulnerable code installed. The module is available as an "extra" setuptools dependency "lxml[html_clean]", so that Projects that need "lxml.html.clean" will need to switch their requirements from "lxml" to "lxml[html_clean]", or install the new library themselves.

we should just use
`lxml[html_clean]`

Is there any advantage to splitting it?
I guess it's more explicit?

**Comment by dalthviz** [comment]
> we should just use
> lxml[html_clean]
> 
> Is there any advantage to splitting it?
> I guess it's more explicit?

I didn't now you could define a dependency taking into account the dependency extras over `pyproject.toml` 😮 . Makes more sense to define it as ` lxml[html_clean]` then since `lxml_html_clean` it's actually a dependency of `lxml` :+1:

**Review by psobolewskiPhD — APPROVED** [review]

**Comment by adriens** [comment]
Hi guys, how should we overcome this
image

**Comment by adriens** [comment]
Fixed by the following end-user code: 

- https://github.com/napari/napari/issues/6798#issuecomment-2045952019

**Pull request merged**
