### PR TITLE
fix tracks instantiation with floating point time values

### PR DESCRIPTION
**Pull request by alisterburt**
# Description
This PR fixes a bug I came across when trying to instantiate a tracks layer with data which had float values in the 'time' column of the array.

The error
```python
        # NOTE(arl): it's important to convert the time index to an integer
        # here to make sure that we align with the napari dims index which
        # will be an integer - however, the time index does not necessarily
        # need to be an int, and the shader will render correctly.
        frames = list(set(self._points[:, 0].astype(np.uint).tolist()))
        for f in frames:
            idx = np.where(self._points[:, 0] == f)[0]
>           self._points_lookup[f] = slice(min(idx), max(idx) + 1, 1)
E           ValueError: min() arg is an empty sequence

../_track_utils.py:131: ValueError
```

was because the time values are converted to integers then compared with the original float valued data.

Everything renders as expected for me with my data after this fix and Alan's note suggests the shader was designed to handle this

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by brisvag** [comment]
LGTM in general; however, I'm not super familiar with tracks: are we sure we only want `uint` there, and not possibly a signed `int`?

**Comment by alisterburt** [comment]
@brisvag I'm in the same boat, not sure why it was uint in the first place so left as is to keep changes as small as possible

**Comment by alisterburt** [comment]
@JoOkuma test failure here seems to imply that floating point time values are 'malformed' data - do you have some insight here?

**Comment by JoOkuma** [comment]
LGTM, I think it's unsigned because we assume the time is non-negative. It shouldn't be an issue converting to integer or leaving as it's because NumPy is careful with type conversion/promotion.

I think we might need to `round` the float before converting to an integer. I was looking where the `_points_lookup` is used and it queries the `current_time` variable of the tracks that is computed from [here](https://github.com/napari/napari/blob/15526e3971b407e7d396eda958b090e4f2803d29/napari/layers/base/base.py#L760) with rounding.
This could result in some tracks' labels inconsistency when displaying them. I would check this visually or write a test checking the length of the coordinates (or labels) returned by `Tracks.track_labels(...)`.

**Comment by sofroniewn** [comment]
Looks like there is one test fail that is tracks specific 

```python-traceback
  =================================== FAILURES ===================================
  __________________________ test_malformed_timestamps ___________________________
  
      def test_malformed_timestamps():
          """Test for malformed track timestamps."""
          data = np.random.random((100, 4))
          data[:, 0] = 0
          with pytest.raises(ValueError):
  >           Tracks(data)
  E           Failed: DID NOT RAISE <class 'ValueError'>
  
  napari/layers/tracks/_tests/test_tracks.py:172: Failed
  =============================== warnings summary ===============================
```

If you fix that and then update from main we should be able to merge, thanks!!

**Comment by alisterburt** [comment]
thanks for the input @sofroniewn and @JoOkuma - I've updated the PR so that everything should pass

I rounded as you suggest @JoOkuma but haven't added a test around that behaviour, it wasn't immediately obvious how best to test that to me

**Review by sofroniewn — APPROVED** [review]
LGTM! all tests are passing now too!! thanks for quick turnaround

**Review by jni — APPROVED** [review]

**Pull request merged**
