### PR TITLE
EXPERIMENT: Batched-updates context manager.

### PR DESCRIPTION
**Pull request by Carreau**
This experiment stems from the observation in #3867 that a few methods
have the `update` argument as to whether or not call
`_update_display()`, and this is generally used in case of batched
updated  to not trigger update on every call.

This is error prone, so here I'm attempting to create a reentrant
context manager that batches the updates and call `_update_display()`
only when the last context manager exists.

I'm still trying to see how that should work. In particular I'm trying
to see whether `_update_display()` should be the only method to do that.
And I'm also tempted to split `_update_display()` into to methods:
One that set a boolean flag it should be called, and one that triggers
the actual rendering on context manager exists.

This does not make the code magically faster, but it does allow some
more convenient patterns, as the context manager is reentrant.
Ina perfect world you could eagerly call multiple methods that would
trigger a redraw in a loop, and only trigger a single redraw.

I'm not sure how one would go with detecting that a
`with_batch_updates()` might be useful. I'm thinking maybe a mode where
we can measure time between subsequent update and emit a warning if it's
less that a certain amount ?

Let me know what you think of the approach.

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by brisvag** [comment]
Love this; many times I found myself juggling things around to avoid redrawing, and failed.

> I'm not sure how one would go with detecting that a `with_batch_updates()` might be useful. I'm thinking maybe a mode where we can measure time between subsequent update and emit a warning if it's less that a certain amount ?

A test/benchmark like this seems like an awesome idea to get us started!

**Comment by perlman** [comment]
> I'm still trying to see how that should work. In particular I'm trying
> to see whether _update_display() should be the only method to do that.
> And I'm also tempted to split _update_display() into to methods:
> One that set a boolean flag it should be called, and one that triggers
> the actual rendering on context manager exists

Interesting idea. I've certainly run into cases where updates to multiple properties trigger multiple updates.
I like this idea of condensing them together.

> Love this; many times I found myself juggling things around to avoid redrawing, and failed.

Agreed!

**Comment by andy-sweet** [comment]
@Carreau : this looks like a useful idea, but it's been around for a while without any action. At a minimum, I think you should mark this as a draft to help filter PRs that are ready for review. If you don't plan on working on this in the short term future, it may be worth closing this.

**Comment by kephale** [comment]
@brisvag are you still interested this batched updates approach?

**Comment by brisvag** [comment]
A benchmark would show if this is worth it; if it is, yes :P but it's not really on my priority radar atm.

**Pull request closed without merging**
