### PR TITLE
exclude pyproject.toml from sdist

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Enable #1059 by removing `pyproject.toml` from source bundle
#1215 is not enough because `pyproject.toml` introduce build isolation 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

https://github.com/napari/tutorials/pull/61#discussion_r400777453

# How has this been tested?

- [x] tested on my machine
- [x] all tests pass with my change
- [x] add proper test task

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have added tests that prove my fix is effective or that my feature works

@sofroniewn @jni

### CODE REVIEW

**Comment by Czaki** [comment]
Ready

**Comment by tlambert03** [comment]
I'd like to propose that we're generally going down the wrong path here...

In an attempt to avoid having our users run `pip install napari[pyside2]` or `pip install napari[pyqt5]`, we are jumping through a *lot* of hoops, and breaking a lot of standard practices.  The truth of the matter is that pip and setuptools [don't really support the use case we're after here](https://discuss.python.org/t/conditional-package-install-depending-on-other-packages-in-environment/4140). So we've introduced a few non-standard tricks like [adding logic to `setup.py`](https://github.com/napari/napari/pull/1059), and then we [avoided distributing wheels](https://github.com/napari/napari/pull/1215), but found that [that still doesn't work](https://github.com/napari/napari/issues/1230), and so now we're trying another hack (removing `pyproject.toml`) to see if we can force pip (which has [moved on to a new default behavior and standard](https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support)) to do for us something that it does not do.

Meanwhile, what we have now is a situation in which we very often have both pyside and pyqt installed in the environment, which has created challenges (e.g. for  resource building) and is likely to lead to other bugs... and I don't think avoiding isolated builds and the new PEP517/518 direction of things is going to be our best long-term solution.

I would propose that we just bite the bullet, promote `pip install napari[pyside2]` or `pip install napari[pyqt5]`, add a bomb-proof error message if neither backend is available, start building wheels, and simplify our setup.py logic again.  And if anything is done with pyproject.toml, we should expand it to [make explicit our build-backend](https://github.com/pypa/setuptools/issues/1698)(`build-backend = "setuptools.build-meta"`)

**Comment by tlambert03** [comment]
This issue is largely due to the "split personality" that napari has as a library vs an application:
as an application, we want end-users to be able to "just install napari" and have things as we intended them, which often requires making rather specific dependency declarations.   As a library, we'd like to allow end-users some flexibility in the way they use napari, which necessitates loose dependency declarations.  It's really quite hard to have it both ways.

I'll also reraise the possibility that has been [mentioned in the past](https://github.com/napari/napari/issues/704#issuecomment-572900776), which is to have `napari` be a shell package that requires `napari-lib` and `pyside2` ... and tell those who don't want pyside2 to `pip install napari-lib` ...

**Comment by sofroniewn** [comment]
One approach we could go with is

```
pip install napari[pyside2]
pip install napari[pyqt5]
pip install napari[all]
```

Where pip install napari[all] also pulls down `pyside2`, but also things like `napari-svg`, potentially `napari-console` if we pulled that code out, `napari-builtins` if we put all our builtin code somewhere else.

I don't think it is intimidating or confusing to new users to say

```
pip install napari[all]
```

it doesn't require them to understand the subtleties of our backend, and as new users they can feel confident they are getting everything.

Thoughts @jni @tlambert03?

**Comment by Czaki** [comment]
I totally agree. This was previously rejected, but it is best solution until some default extras was introduced to python package managment.

**Comment by jni** [comment]
I agree 100% with Talley and was about to propose the same thing. So I guess we have consensus!

@Czaki I'll close this PR since it has nothing in common with the proposed strategy we're going for in the end. Happy we found a solution we're all happy with!

**Pull request closed without merging**
