### PR TITLE
Split_channel makes base channel translucent, rest additive

### LINKED ISSUE #3374: Additive blending mode requires black canvas (broken in light theme)
## 🐛 Bug
Originally posted at napari-aicsimageio: https://github.com/AllenCellModeling/napari-aicsimageio/issues/22 

When using Light theme in Napari, the napari-aicsimageio plugin results in wierd behavior: drag-n-dropping a LIF results in a blank image, regardless of colormap, etc. 
However, switching to Dark theme shows that the image was properly loaded.
Light theme:
image

There is no error message.
Note that the tiny preview icon in the layer list does properly show the image.

Dark theme:
image

## To Reproduce

Drag-and-drop a LIF onto napari with napari-aicsimageio v 0.3.3 or 0.3.5 in napari 4.10 or 4.11.
Change theme between Light and Dark.
Here's the smallest LIF I have handy:
https://www.dropbox.com/s/7201v0ae0f3iiy8/2021040_H33342_L929_24w_A3_tilescan.lif?dl=0

## Expected behavior

Image should be visible regardless of theme. 
Perhaps the colormap needs to be adjusted for optimal viewing, but it should not be a blank canvas.

## Environment

```

napari: 0.4.11
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- Measurements (Plot profile): 0.1.5
- Measurements (skimage regionprops): 0.1.6
- Utilities (skimage regionprops): 0.1.6
- aicsimageio-out-of-memory: 0.3.5
- animation: 0.0.2
- clEsperanto: 0.10.0
- console: 0.0.4
- ome-types: 0.2.6
- scikit-image: 0.4.11
- svg: 0.1.5

```

(Note: I also tested 4.10 and v. 0.3.3 of the plugin)

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description
This is related to https://github.com/napari/napari/issues/3374 and https://github.com/napari/napari/issues/3353
I was looking at blending again, because the Light mode issue is really irritating.
So, in reference to https://github.com/napari/napari/issues/3353 the default for images is indeed `translucent`. See:
https://github.com/napari/napari/blob/57c3c348022ffc362f8712ec844dadb0579b7276/napari/layers/image/image.py#L232
https://github.com/napari/napari/blob/57c3c348022ffc362f8712ec844dadb0579b7276/napari/components/viewer_model.py#L726
...but this is only if `channel_axis` is `None`, so single channels.
For a single channel image, it's not clear to me what the advantage would be of using additive —is blending with the canvas ever desired? Meanwhile, the drawback of additive is that in Light mode (white canvas) additive mode means no image, which is a pretty broken behavior IMO.

Now, when a multichannel image is opened and is split into channels, then additive is forced:
https://github.com/napari/napari/blob/57c3c348022ffc362f8712ec844dadb0579b7276/napari/layers/utils/stack_utils.py#L84
...and this of course is the source of the issue with Light mode https://github.com/napari/napari/issues/3374
none of the multichannel examples "work" (Cells, Kidney, Lilly, etc). They all return white squares.
But additive blending is really nice for multichannel overlays.

My solution here is, when splitting, to make the first channel translucent and the rest additive. This eliminates blending with the canvas, restoring expected behavior with sample images and other multichannel images in Light mode.
Check it out:
```
import napari
from skimage import data

viewer = napari.Viewer()
viewer.theme = "light"
viewer.open_sample('napari', 'kidney')
```

You can switch to Dark mode and should see no difference.
Now, if you have images open the behavior will change, again for the better I think. Try:
```
viewer.open_sample('napari', 'binary_blobs')
viewer.open_sample('napari', 'kidney')
```
With this change the new stack doesn't blend with the previously opened image.

## Type of change
- [x] Bug-fix for https://github.com/napari/napari/issues/3374
- [?] Breaking change (stack splitting will be different)
- [ ] This change requires a documentation update

# References
Closes https://github.com/napari/napari/issues/3374
See also https://github.com/napari/napari/issues/3353 and https://github.com/napari/napari/discussions/3914

# How has this been tested?
- [x] tested locally: fixes opening sample images in Light mode
- [x] fixed test to take into account the change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by jni — APPROVED** [review]
I like this! Might be controversial but I've encountered this issue a few times so :+1: from me!

**Comment by psobolewskiPhD** [comment]
> I like this! Might be controversial but I've encountered this issue a few times so 👍 from me!

Thanks @jni 
I *really* like Light mode, especially during the day, and would love for it to be not-broken. It's *really* annoying to be screen-sharing napari for someone and opening a multichannel image only to have the blank square and have to click through the blending dropdown to fix. 

Also I **really** want to get inverted LUTs to work, as mentioned here https://github.com/napari/napari/discussions/3914
Alas, no feedback, so i guess the napari community isn't as into it, but I think there are people out there that care:

image

https://twitter.com/psobolewskiphd/status/1514708652665585667?s=21&t=CLu5oVmuCSj1N7hSjN4q_g

I mean how can you not love that screenshot? 😍

**Comment by sofroniewn** [comment]
Hi so sorry that #3914 hasn't gotten more engagement yet, I just weighed in over there.

This looks like a very reasonable change that makes things work better by default. We can always revisit once we have better support for light mode/ inverted look up tables.

Thanks!!

**Comment by jni** [comment]
> I mean how can you not love that screenshot?

@psobolewskiPhD I literally had already liked and retweeted that! :joy: Thank you very much for the fix! :tada:

**Pull request merged**
