### PR TITLE
Add examples tests

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
I recently added some [tests at magicgui](https://github.com/napari/magicgui/blob/master/tests/test_docs.py) to make sure that all the examples in the `examples/` directory, and all of the `code-cells` in the docs run without exception or warnings. This adds similar tests here.  Caught a few errors here. (@sofroniewn, is there a better change for removing `opacity` from shapes.add?)

tests run locally now, let's see how CI works.

## Type of change

- [x] new tests

### CODE REVIEW

**Comment by sofroniewn** [comment]
Love this!

> @sofroniewn, is there a better change for removing opacity from shapes.add?

Not really, thought was per shape opacity should be controlled at the `color` level which can be RGBA. I say we just merge this change as is. Something possibly for @kevinyamauchi to consider during color refactoring, but I'd say low priority.

**Review by sofroniewn — APPROVED** [review]

**Comment by tlambert03** [comment]
I'm getting a lot of local segfaults on `interactive_scripting.py`, I decided to delete it, since I think we've generally decided that calling methods of the viewer object is maybe not threadsafe... so perhaps it shouldn't be in the examples anymore (we also have the other two multithreading examples)

**Comment by sofroniewn** [comment]
> I'm getting a lot of local segfaults on interactive_scripting.py, I decided to delete it, since I think we've generally decided that calling methods of the viewer object is maybe not threadsafe... so perhaps it shouldn't be in the examples anymore (we also have the other two multithreading examples)

If possible it would be nice to update it to the newer API and make it thread-safe. Updating data like that is something that a lot of people might want to do so would be great to be able to point them to a nice example

**Comment by tlambert03** [comment]
> If possible it would be nice to update it to the newer API and make it thread-safe. Updating data like that is something that a lot of people might want to do so would be great to be able to point them to a nice example

agreed.  I updated and added back.  It was helpful, it was _still_ causing some "post-test" segfaults because after the tests run successfully, the worker was getting deleted.  I made some changes to `qthreading` to avoid the segfault and show a useful warning instead by catching that `RuntimeError`.  And also made sure to use our internal `get_app()` qApp, which waits for workers to gracefully finish before quitting the app.  much better now

**Comment by sofroniewn** [comment]
Ok nice! Examples are looking great now. We've gotten twice (i clipped rerun) a fail in linux 3.7 on
```
  napari/utils/_tests/test_magicgui.py::test_magicgui_returns_image Fatal Python error: Segmentation fault
```
not sure if there's a funny interaction going on between these tests and those tests

**Comment by tlambert03** [comment]
yeah... I saw that :/  I've seen it before, and it's slightly bothering me, so I'm gonna leave this for now and come back to it soon (after gui widget stuff is done)

**Review by jni — APPROVED** [review]
I :heart: this so much. Thanks @tlambert03!!!

The idea is we wait to merge until we figure out that segfault, right? Or is this valuable enough that we want to merge now?

**Comment by tlambert03** [comment]
> The idea is we wait to merge until we figure out that segfault, right? Or is this valuable enough that we want to merge now?

glad you like.  I think valuable yes, but not urgent. (the good news is that it really didn't reveal a lot of problems in our examples!).  I think the changes in `qthreading` here are important, so if I can't figure out why linux 3.7 is failing soon, I'll skip it in CI, we can merge, and I'll continue to work on it

**Comment by tlambert03** [comment]
ready here too @sofroniewn

**Comment by sofroniewn** [comment]
Ok nice, looks good. I think fine to skip, we can revisit later! Will merge now

**Pull request merged**
