### PR TITLE
change selected menu header background color

### PR DESCRIPTION
**Pull request by boonepeter**
# Description

On Windows, the background color of the highlighted menu makes the text hard to see:
Annotation 2019-12-18 155715

I made a small change to the stylesheet to make it match the selected item value:
Annotation 2019-12-18 161758

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
# References

# How has this been tested?

- [x] Only tested on windows. 
## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Looks great, thanks for the fix!

**Comment by sofroniewn** [comment]
I just added a release note for this PR so that we can include it in our `0.2.7` release which I plan to make imminently. I plan to merge this afternoon

**Comment by boonepeter** [comment]
Great!

**Comment by sofroniewn** [comment]
@boonepeter if you were interested, we could use some help with our switching of themes - see this issue https://github.com/napari/napari/issues/669 where we have problems with incomplete updates etc.

**Comment by boonepeter** [comment]
Cool, I'll take a look when I have some time!

**Pull request merged**
