### PR TITLE
fix bug on moving clims slider

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description

This PR fixes a bug that caused an error on moving the clims slider.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [x] `examples/add_image.py`

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Comment by kne42** [comment]
What error exactly?

**Comment by sofroniewn** [comment]
Appologies, should have put in more detail. If you currently try and move the slider you generate the following error

```python
WARNING: Traceback (most recent call last):
  File "/Users/nicholassofroniew/Github/napari/napari/layers/_image_layer/view/controls.py", line 36, in clim_slider_changed
    layer._qt_controls.clim_slider_update()
TypeError: clim_slider_update() missing 1 required positional argument: 'event'
```

This PR adds an argument `None` to this callback

**Review by kne42 — APPROVED** [review]
Dunno if that's necessarily best practice but I'll give an approval anyways :P

**Comment by sofroniewn** [comment]
Agreed, we might want to revisit this

**Pull request merged**
