### PR TITLE
Fix typo in perfmon patcher

### PR DESCRIPTION
**Pull request by kevinyamauchi**
# Description
This PR fixes a small typo in the perfmon patcher (`module.__name___` -> `module.__name__`).

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Thanks for that fix @kevinyamauchi, it looks like it wasn't caught in #1550 either, cc @pwinston.

**Comment by pwinston** [comment]
@kevinyamauchi good find. That's weird though because it ran okay, wouldn't the old version have been an error? Doesn't matter I guess, good to have it fixed. Thanks.

**Comment by kevinyamauchi** [comment]
> That's weird though because it ran okay, wouldn't the old version have been an error?

For me, it was on a code path that was only executed when the thing being profiled was a function. Patching class methods worked fine!

**Comment by pwinston** [comment]
Thanks, that makes sense. I probably never traced functions. I'm going to create a very simple perfmon test for #1550. Not sure if I'll test the Patcher, but at least make sure it can create a trace JSON at all. We can add more tests over time. Tests are great, but if more people use it that will also create a good feedback loop.

**Comment by sofroniewn** [comment]
> I'm going to create a very simple perfmon test for #1550. Not sure if I'll test the Patcher, but at least make sure it can create a trace JSON at all. We can add more tests over time. 

Thanks @pwinston that sounds great! I'm going to merge this now as the fix seems uncontroversial, but absolutely agree with the following too

> Tests are great, but if more people use it that will also create a good feedback loop.

and thanks again for the catch @kevinyamauchi!

**Pull request merged**
