### PR TITLE
increase screenshot performance

### PR DESCRIPTION
**Pull request by kne42**
Remove unnecessary double call of `QImg2array`.

### CODE REVIEW

**Comment by tlambert03** [comment]
This is a duplicate of #1109... @sofroniewn mentioned that he was a bit wary of this approach at the time, but it's been a while I can't remember the details.

**Comment by sofroniewn** [comment]
> @sofroniewn mentioned that he was a bit wary of this approach at the time, but it's been a while I can't remember the details.

I tried pretty hard to make this work a long time ago (maybe around the vispy 0.5->0.6 transition), but it was always buggy - i.e. didn't handle things like opacity, z-ordering, and blending correctly. I think the offscreen rendering is a pretty different code path from what we normally use, so taking the pixels from the canvas frame seemed easiest at the time. I know that that vispy was working on this too, and so maybe everything is fixed now, in which case it's ok - see my comments here https://github.com/napari/napari/pull/1109#issuecomment-608506085. So I definitely don't have any objections, but I just want us to check (and maybe add tests) for all the necessary usecases - for example does `add_shapes.py` work as expected? If that works well, that's already a great step forward!!!

**Comment by kne42** [comment]
Huh, that's weird, it turns out that `canvas.render()` is different from `QImg2array(canvas.native.grabFramebuffer()`, and I have no idea why. It's under the same circumstances as all the other bugs, e.g. when you have a transparent layer. There's still another way to slightly increase performance so I'll change this PR to that.

**Review by sofroniewn — APPROVED** [review]
LGTM! Thanks!!

**Pull request merged**
