### PR TITLE
Change shortcuts `_mark_conflicts` logic to always compare between strings representations of shortcuts

### PR DESCRIPTION
**Pull request by dalthviz**
# References and relevant issues

Related to #7059 #6204 #7113

# Description

While checking PR #7113 I noticed that the mark conflicts logic was not detecting conflicts properly. From what I have checked seems like the action manager shortcuts lists ends up having a mix of `KeyBinding` instances and string representations of `KeyBinding`s.

Also, recalling some related work, I think some discussion about the `mark_conflicts` logic was done over PR #6204 (https://github.com/napari/napari/pull/6204/files/f2e39a83f64c6720b6b386b98cb999a86c9704fa#r1348933980) and a commit with some changes was also done there (https://github.com/napari/napari/pull/6204/commits/5ffb23748ab7718da2b7bc4be31c63850cd732dd).

This follows a similar implementation path and does some changes to the conflicts logic to always use a standard string representation to compare shortcuts when looking for conflicts. This also extends the current test that checks the `_mark_conflicts` logic to do the check using the different representations a shortcut could have which are encapsultated by the `KeyBindingLike` type (a `KeyBinding` instance itself, its `str` representation or its `int` representation).

### CODE REVIEW

**Review by DragaDoncila — APPROVED** [review]
This is awesome @dalthviz - a huge improvement over the previous state of things which seems to basically just never detect conflicts haha.

Couple of points, but I think they're probably for future PRs because as I say, this is already a massive improvement:

- Conflicts are only detected within a single panel, but not across panels. I think conflicts between different layer types is ok, as only one layer will be active. However, if possible, we should try to detect conflicts with the `Viewer` keybindings?
- If I edit a shortcut and then hit `Cancel` on the left of the preference pane, the changed shortcuts are not reset. This is the same as on `main` so happy to keep it as is for now, but I'm not sure if that's what a user would expect

Perhaps @psobolewskiPhD has ideas on those last two points? In the meantime I am heartily approving!

**Comment by DragaDoncila** [comment]
@dalthviz will we need to change anything here after #7113? I assume no because of the `.qt` bit that calls `str` on the keybinding? But just wanted to double check

**Comment by dalthviz** [comment]
> @dalthviz will we need to change anything here after https://github.com/napari/napari/pull/7113? I assume no because of the .qt bit that calls str on the keybinding? But just wanted to double check

I don't think so. Merging #7113 shouldn't affect the changes done here :+1:

**Comment by psobolewskiPhD** [comment]
> * If I edit a shortcut and then hit `Cancel` on the left of the preference pane, the changed shortcuts are not reset. This is the same as on `main` so happy to keep it as is for now, but I'm not sure if that's what a user would expect

I tested this and it's surprising to me! 
I would expect `Cancel` to discard my changes -- it does for e.g. theme change.
I think this should be considered a bug.

**Comment by psobolewskiPhD** [comment]
@DragaDoncila I tried setting a Labels keybind to one that conflicts with the viewer and it did flag it as a conflict. I think that is correct behavior -- on main without this PR this doesn't work.

**Review by psobolewskiPhD — APPROVED** [review]

**Comment by DragaDoncila** [comment]
> @DragaDoncila I tried setting a Labels keybind to one that conflicts with the viewer and it did flag it as a conflict. I think that is correct behavior -- on main without this PR this doesn't work.

Yep, you're right. I must've just tried two different layer types. I agree that the current behaviour is correct and we don't need to do anything further there.

> I would expect Cancel to discard my changes -- it does for e.g. theme change.

I thought the same. Let's pick this up in a separate PR. Opened #7143 to track.

**Pull request merged**
