### PR TITLE
Small changes to points defaults.

### PR DESCRIPTION
**Pull request by brisvag**
# Description
During EuroScipy2022 (and in previous occasions) I helped people with using `Points` for the first time. Invariably, there's issues with visualization that are awkward to explain and solve:
- point size is crazy off-scale
    - see #4705 for more discussion on this
    - #4790 should solve the most egregious issues with this
- points are invisible or hard to see, due to the transparency issues in vispy + antialiasing, which basically makes things disappear into the background
    - note that antialiasing applies both between the point and the background *and the __face__ and the __edge__* of the point, so this can take up to 2  pixels with `antialiasing = 1` (afaik).

The second issue is exacerbated by the presence of the `edge`, and made even worse by the default color of the edge, which is the same as the background. Note also that everything above is *much* worse in 3D than in 2D, due to depth being important and transparency being draw-order-dependant rather than depth-dependant.

So, I suggest some changes to mitigate the issue until we solved it upstream:
- reduce the size of the edge
- make it a color different from the background in both themes

Even better for visibility would be to
a. default the edge size to 0 (thickness of antialiased area is reduced)
b. or even disable antialiasing

I would be in favour of `a`, unconvinces about `b`; It would be nice to hear opinions from users! @haesleinhuepf @psobolewskiPhD, not sure who else uses points regularly.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by DragaDoncila** [comment]
> So, I suggest some changes to mitigate the issue until we solved it upstream:
>
> reduce the size of the edge
> make it a color different from the background in both themes

1000% agree. I've been working with ~10,000 points in both 2D slices and in 3D, and points disappear all the time. I would also be in favor of simply removing the edge as you suggest, if it has a significant impact on the antialiasing effects.

**Comment by haesleinhuepf** [comment]
Hey @brisvag ,

thanks for spending so much time on this. Also reconsider the solution proposed in #4705 to simply things:

```
points_layer.size = np.asarray(viewer.dims.range).max() * 0.01
```

Thanks again! I'm sure the final solution will make end-users happy 🌞

Best,
Robert

**Comment by psobolewskiPhD** [comment]
I dig these defaults. 
Honestly, I'm not sure why point needs an edge in the first place. A point is a point?

**Review by andy-sweet — APPROVED** [review]
Changing default values seems fine to me, if they help mitigate this issue. Setting the default `edge_width` to be 0 seems a bit more extreme, but I defer to users here. If some users were relying on these defaults (which seems fairly unlikely), the fix is easy and informative.

Seems like we have some generally positive user feedback too, so I think this is good to merge for 0.4.17 whenever you're ready @brisvag.

I don't understand how this interacts with #4790 or, when combined, if they actually fix #4705. My guess is not quite and there is still some fairly complex discussion to be had, and that's unlikely to be resolved for 0.4.17.

**Comment by brisvag** [comment]
> Honestly, I'm not sure why point needs an edge in the first place. A point is a point?

I agree; in my opinion, the optimal use of the `Markers` visual would be to use the `edge` as an indication of selection, which would halve the current memory usage (since we actually use *another* `Markers` just for selection)... But I feel like that's a strong opinion, and I can imagine some people are using the edge as an actual way of convey data information.

> I don't understand how this interacts with https://github.com/napari/napari/pull/4790 or, when combined, if they actually fix https://github.com/napari/napari/issues/4705. My guess is not quite and there is still some fairly complex discussion to be had, and that's unlikely to be resolved for 0.4.17.

Both this and #4790 are small incremental changes that should remove the absolute worst case scenarios summarizable with "WTF WHERE ARE MY POINTS?", but none fully solve #4705. As you guessed, for that we probably need some sort of `unset` value for `Points.size` and special handling of this value when the layer gets assigned to a viewer the first time (following @haesleinhuepf 's suggestion above).

**Comment by psobolewskiPhD** [comment]
> I agree; in my opinion, the optimal use of the `Markers` visual would be to use the `edge` as an indication of selection, which would halve the current memory usage (since we actually use _another_ `Markers` just for selection)... But I feel like that's a strong opinion, and I can imagine some people are using the edge as an actual way of convey data information.

This is how I expected it to work when I first played with Points layers. Point has a color and selection has a color—the edge. Otherwise, whats the differences between a point and a shape?

**Comment by brisvag** [comment]
> Otherwise, whats the differences between a point and a shape?

Performance and versatility I would say :) Points are more performant, but shapes let you do whatever you want.

**Comment by andy-sweet** [comment]
> Seems like we have some generally positive user feedback too, so I think this is good to merge for 0.4.17 whenever you're ready @brisvag.

Actually, as [instructed by the release guide](https://napari.org/dev/developers/release.html#nine-days-before-release-two-days-before-release-candidate), I should ideally be the only one merging at the moment. I'll merge this after 24 hours unless I hear otherwise @brisvag

**Comment by Carreau** [comment]
I restarted the failing test as it appears it was spurious failures.

> I'll merge this after 24 hours

That is a long 24h...

**Comment by andy-sweet** [comment]
> That is a long 24h...

I did say *after* 24 hours 😛 , but thanks for the reminder!

**Pull request merged**
