### PR TITLE
check if opengl file exists

### PR DESCRIPTION
**Pull request by Czaki**
This PR partially address #2629 and improve OpenGL install step with check if it is really installed 

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
works for me, thanks @Czaki

**Comment by jni** [comment]
Thank you @Czaki! Do I understand correctly that this doesn't actually change the behaviour, just fails earlier? And if so, does that mean that the CI failures are sporadic?

**Comment by Czaki** [comment]
This checks if OpenGL DLL is present on the filesystem. So it makes fails earlier and in the proper place. 

This type of CI fails may be caused by two things. Update of URL (like current situation) or network problem. 

It produces better error information than:
```
  FileNotFoundError: Could not find module 'opengl32' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by jni** [comment]
> Update of URL (like current situation)

but then why did CI pass here?

**Comment by tlambert03** [comment]
cause @larsoner fixed it upstream

**Comment by Czaki** [comment]
> but then why did CI pass here?

because bug was already fixed 
https://github.com/napari/napari/issues/2629#issuecomment-829146080

**Comment by jni** [comment]
ooooh. Thank you both! Too many streams. :sweat_smile: And thank you @larsoner!

**Comment by larsoner** [comment]
I would love to take credit but it was all @GuillaumeFavelier in https://github.com/pyvista/gl-ci-helpers/pull/6 :)

**Pull request merged**
