### PR TITLE
A rough sketch of integrating midi controll (WIP)

### PR DESCRIPTION
**Pull request by bnikolic**
Maps dimension sliders to midi controlls. The QT<->midi connection is
after https://www.alexallmont.com/midi-responsive-qt/

# Description
Allows MIDI control of the dimension sliders, thus allowing navigation of a multi-dim dataset without distraction of hunting around with the mouse. 

This is an initial sketch. Some things which need to be done:

1. Allow user selection of midi controller to use 
2. One set of rotaries for single step while other set for faster navigation through the dimensions (can be layer 1 and layer 2)
3. Ideally a MIDI-map design equivalent to keymap so that midi controllers can be flexibly mapped to various UI functions. (E.g. Gamma, min, max would be very useful for me)
4. Non QT5 implementation?

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — COMMENTED** [review]
Thanks for creating this @bnikolic - i had seen your tweet here https://twitter.com/web_bn/status/1362730259909660677 and followed you discussion with @jni. I'm including the video again for anyone who missed it. 

https://user-images.githubusercontent.com/6531703/109394865-0f516f00-78de-11eb-88be-e8651d72736a.mp4

I think it would be really cool to try and turn this into a [napari plugin](https://napari.org/docs/dev/plugins/index.html) rather than a direct contribution to napari (though having the PR here will make it much easier). I see this as an example of a custom hardware integration that others might want to copy too.

One option would be to try and use our GUI hook https://napari.org/docs/dev/plugins/hook_specifications.html#gui-hooks

**Comment by jni** [comment]
@sofroniewn Yeah I agree that this should probably be a plugin, I just wanted someplace to discuss the code and figure out how to build that, since the code was actually a commit on napari. I think it's ok to have this WIP PR be that discussion space for now. Once I get my x-touch I'll see if I can turn it into a plugin.

**Comment by jni** [comment]
And thank you @bnikolic for developing this and opening the PR! I :heart: it!

**Comment by tlambert03** [comment]
I think we'd need a new hook spec for this to be a plugin... it doesn't require a widget, so it would be weird to have to add a dock widget to connect the necessary events to the dims slider.  It's more like a mouse callback...

**Comment by jni** [comment]
@tlambert03 having said that, I think all of the functionality should be configurable, so a widget for configuration would be welcome I think. =) Here's my to-do list that I hope to get to soon:

- knobs move the sliders at different speeds.
- first row of buttons toggles layer visibility
- second row of buttons is for functionality, e.g. paint mode, pan-zoom, etc. Maybe this is even configurable to custom functions.
- physical slider controls opacity of selected layer
- buttons on right, handily labeled "layer" with up and down arrows, select next/previous layer.

😃

**Comment by tlambert03** [comment]
> so a widget for configuration would be welcome I think

I agree!  we do need some sort of gui configuration... but I'm still not sure that should be the responsibility of an action-binding plugin (via `provide_dock_widget), but rather something that would hook through the putative shortcut manager (#2284), and have an auto-generated GUI something like the one in VSCode:

Untitled

(and, of course, a key/mouse-binding plugin should be able to work whether or not a widget has been opened)

Anyway, this is all sort of external to this particular feature... but as this may be one of the first shortcut-heavy plugins, it's worth a little discussion :)

**Comment by sofroniewn** [comment]
> but rather something that would hook through the putative shortcut manager (#2284), and have an auto-generated GUI something like the one in VSCode:
> 
> Anyway, this is all sort of external to this particular feature... but as this may be one of the first shortcut-heavy plugins, it's worth a little discussion :)

I love this! Would be a great first use case!

**Comment by tlambert03** [comment]
Hey @bnikolic, wondering if you might be able to convert this to an example (and put it in `examples/` folder).  
It's a very cool use case, and would be nice to have this merged somewhere, but it will probably take a _lot_ more discussion to actually modify the viewer model and `QtViewer` as is done here.  So I'd say:

1. import from `qtpy` instead of `PyQt5`
2. put your `MidiReceiver` in a new example file.
3. instantiate the receiver directly in the example file (rather than in `QtViewer`)
4. create a `Viewer` instance in the example file and connect your `process_message` signal to a callback that operates on the viewer instance (rather than adding a method to `ViewerModel`.

sound good?

**Comment by jni** [comment]
@bnikolic thank you again for getting this started! This is now a plugin at https://github.com/jni/napari-midi. There'll be ongoing development there if you want to have a look, update some code, or just use it! (Since I know you have an X-touch mini :joy:)

**Pull request closed without merging**
