### PR TITLE
fix toggle ndisplay z-order points

### LINKED ISSUE #1462: 2d->3d->2d points z-ordering bug
## 🐛 Bug

2d->3d->2d z-ordering bug using `examples/add_points.py`

## To Reproduce

1. Run `examples/add_points.py`
2. Click 3D rendering button
3. Click 2D rendering button
4. Observe points that were in front of image are now behind image.

## Expected behavior

Points should retain correct z-order

## Environment

Last commit 0179c0dad1d93326388d3ab0f768e4ef028b3f09

## Additional context

Identified in https://github.com/napari/napari/pull/1374#issuecomment-659233743

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
Closes #1462 by fixing z-ordering change when toggling ndisplay for images (bug introduced in #1445) and for points where we were previously using the node create destroy approach we wanted to move away from in #1445.

I will add two screenshots test for this - but I'm hoping we might have fixed our windows CI bug too! We'll see!!

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
🥳 I think out windows CI bug is finally fixed @napari/core-devs!!! Looks like it was the same vispy create/ destroy but it was happening on Points layer too!! This needs a couple screenshot tests, but then we might be golden!!

**Comment by sofroniewn** [comment]
Fix for #1467 now included with screenshot test. I might also want to add a non-screenshot lest looking at the order parameter on the node as is mentioned in #1467 by @tlambert03, but that will have to come tomorrow!

**Review by jni — APPROVED** [review]
@sofroniewn so awesome!!! 🎉 

I'll approve but I'll let you self merge in case you want to add to this PR before merging.

**Comment by sofroniewn** [comment]
I've now added one more test and fixed a merge conflict. Will merge once tests pass

**Comment by sofroniewn** [comment]
Windows test still failed on CI :-( I'm merging anyway, as while I had hoped this PR would fix that, it looks like we still might have windows CI/ vispy issues .... i guess we'll have to keep looking into them.

**Pull request merged**
