### PR TITLE
Check remove_selected

### PR DESCRIPTION
**Pull request by brisvag**
# Description
While working on #3625 I realized that we were missing a proper check to make sure that removing a selection of points correctly removes the attributes at the corresponding index. This PR adds a test for that.

In doing so, I noticed that `edge_width` does not allow setting an array, despite vispy using an attribute, so I created #3995.

Does a test like this make sense? Am I missing anything?

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by brisvag** [comment]
Note that this should be updated when merging #3625 .

**Review by alisterburt — APPROVED** [review]
test looks good, very good to add if not already covered!

**Review by sofroniewn — APPROVED** [review]
LGTM! Might be of interest to @andy-sweet too

**Comment by brisvag** [comment]
Self reminder to update this if/when #3625 and #3999 are merged!

**Pull request merged**
