### PR TITLE
restore numpy 2.0 constraints

### LINKED ISSUE #6871: [test-bot] pip install --pre is failing
The --pre Test workflow failed on 2024-06-17 00:23 UTC

The most recent failing test was on windows-latest py3.12 pyqt6
with commit: d9576dea8a7905291cd12c325d6f618eb5454cb0

Full run: https://github.com/napari/napari/actions/runs/9539972024

(This post will be updated if another test fails, as long as this issue remains open.)

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues
closes #6871

# Description

Restore NumPy 2.0 constraints as it crashed our pre tests because vispy incompatibility. It also crashes `napari-plugin-manager` tests (see https://github.com/napari/napari-plugin-manager/pull/55). 

I think that we should not remove it until tests on separate branches pass.

### CODE REVIEW

**Comment by jni** [comment]
I think @brisvag is working on a np2-compatible vispy release right now... Can we wait a bit to see if that fixes it? (And @brisvag can you confirm this? 🙏)

**Comment by Czaki** [comment]
We may merge this, and relax constraint in one or two days when vispy is released. Then we could test if any other package creates a problem

**Comment by jni** [comment]
Ok. It's certainly annoying to have all the CI failing. 😅

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
I'll merge this quickly so we can get on with other PRs. It's easy to revert if needed.

**Pull request merged**
