### PR TITLE
Fix copy/paste of points

### LINKED ISSUE #5786: Copy and paste multiple points doesn't work
I'm trying to copy and paste multiple points on Napari, but it doesn't work.
I have searched in _Points layer_ shortcuts menu, but copy and past commands missed.

How to fix?

Version: 
**napari**: 0.4.17rc8
**Python**: 3.8.16 | packaged by conda-forge | (default, Feb 1 2023, 15:53:35) [MSC v.1929 64 bit (AMD64)]

Thank you in advance

### PR DESCRIPTION
**Pull request by andy-sweet**
# Fixes/Closes

Closes #5786

# Description
The issue here is actually caused by copying constant color values used for text, which causes issues because a single value has `ndim > 0`.  This PR fixes the issue by specifying the dimensionality of a single color value when copying values.

It might be worth reconsidering the implementation here and/or whether constant encodings are worth handling as a specific optimized case like this. But I think it's worth getting this PR in before a longer consideration.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# How has this been tested?
- [x] modified an existing test to reproduce the bug, then fixed it
- [x] all other tests pass with my change
- manually tested this by copying and pasting lots of points

### CODE REVIEW

**Comment by brisvag** [comment]
I'm a bit confused, can you explain the change to test?

**Comment by andy-sweet** [comment]
> I'm a bit confused, can you explain the change to test?

Sorry, the implementation comment in the test is not clear. Does the following help?

```
    # Use an index of 4 to ensure that constant color values, which are
    # RGBA 4-vectors, are handled correctly when copied, unlike in bug:
    # https://github.com/napari/napari/issues/5786
```

By trying to copy at an index of 4, we reproduce the bug in #5786, which is caused by the combination of two things.

1\. Style encodings share the same code to handle scalar style values (e.g. strings) and non-scalar ones (e.g. RGBA colors).
2\. There is some special casing to handle constant encodings, so we avoid storing/manipulating an array of values.

In the long term, I wonder if (2) is really worth it, since that is the major cause here and I think vispy will end up storing an array of RGBA color values anyway.

**Comment by brisvag** [comment]
ok, makes sense; yeah vispy ends up with rgba, so it's definitely fine to not special-case, but no need to do it here :P

**Comment by andy-sweet** [comment]
@brisvag: since you've already taken a look and this is small, do you mind reviewing? I updated the explanatory comment in the test as above.

**Review by brisvag — APPROVED** [review]

**Pull request merged**
