### PR TITLE
Fix progressbar segfaults in test

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR fix deterministic segfaults during running tests on my local machine. I think that it could fix it also on CI. 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

@sofroniewn @tlambert03

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
Awesome.  thank you so much for looking into this!  This all makes sense, particularly the `deleteLater()`.  

very minor comment: if you like, you can use `make_napari_viewer(show=True)` ... 

looks like we got one fail on the pip install test... but I think that's an unrelated failure that we sometimes get (the segfault at the end of a successful test).

maybe if all other tests pass, we should run them a couple times?

**Comment by Czaki** [comment]
This PR does not fix segfault at the end of the test run. 
It even happens when running test locally without `xvfb` 

Here end of the log from my desktop

```
[xcb] Unknown request in queue while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3.8: ../../src/xcb_io.c:149: append_pending_request: Assertion `!xcb_xlib_unknown_req_pending' failed.
Fatal Python error: Aborted

Current thread 0x00007f5a07a62740 (most recent call first):
<no Python frame>
[1]    153849 abort (core dumped)  CI=1 pytest napari
```

**Comment by Czaki** [comment]
there is a problem with `MIN_REQ`   
```
napari/_qt/_tests/test_threading.py .....Fatal Python error: Segmentation fault
```

**Comment by tlambert03** [comment]
awesome that nothing else failed though.  will rerun a couple times

**Comment by Czaki** [comment]
@tlambert03 could you restart again?

**Comment by tlambert03** [comment]
it's interesting.  I've restarted a number of times now.  I no longer see that qt_notifications error anymore... but we do consistently see the min-reqs error now.

**Comment by Czaki** [comment]
I could reproduce it locally...

From my terminal:
```
======================================================================================= ERRORS =======================================================================================
_________________________________________________________________ ERROR at teardown of test_add_layer[Image-data1-3] _________________________________________________________________
TEARDOWN ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
StopIteration
```

But I cannot promise how much time I could spend on debugging it. 

A also have problem with `test_multichannel_dask_array` faliture

```
====================================================================================== FAILURES ======================================================================================
____________________________________________________________________________ test_multichannel_dask_array ____________________________________________________________________________

    def test_multichannel_dask_array():
        """Test adding multichannel dask array."""
        viewer = ViewerModel()
        np.random.seed(0)
        data = da.random.random((2, 10, 10, 5))
        viewer.add_image(data, channel_axis=0)
        assert len(viewer.layers) == data.shape[0]
        for i in range(data.shape[0]):
            assert viewer.layers[i].data.shape == data.shape[1:]
>           assert isinstance(viewer.layers[i].data, type(data))
E           AssertionError: assert False
E            +  where False = isinstance(array([[[0.18722244, 0.3598777 , 0.62570796, 0.56056966, 0.45481825],\n        [0.13954979, 0.14048273, 0.11438004, 0.9....98847445, 0.22780785, 0.54694169, 0.7296056 ],\n        [0.5356861 , 0.66645397, 0.5906914 , 0.59228675, 0.69606446]]]), <class 'dask.array.core.Array'>)
E            +    where array([[[0.18722244, 0.3598777 , 0.62570796, 0.56056966, 0.45481825],\n        [0.13954979, 0.14048273, 0.11438004, 0.9....98847445, 0.22780785, 0.54694169, 0.7296056 ],\n        [0.5356861 , 0.66645397, 0.5906914 , 0.59228675, 0.69606446]]]) = <Image layer 'Image' at 0x7fa69bbca910>.data
E            +    and   <class 'dask.array.core.Array'> = type(dask.array<random_sample, shape=(2, 10, 10, 5), dtype=float64, chunksize=(2, 10, 10, 5)>)

napari/components/_tests/test_multichannel.py:204: AssertionError
```
Maybe You meet it already ealier?

**Review by sofroniewn — APPROVED** [review]
LGTM! Great if we've narrowed down to just the minreq failing. I'd be happy to merge this now and keep the investigation going elsewhere

**Comment by Czaki** [comment]
@tlambert03 @sofroniewn I do not understand why but it looks like also problems with `MIN_REQ` are caused by `test_progress.py`. Without running it I cannot reproduce the error on my local machine. 

cc: @DragaDoncila

**Comment by tlambert03** [comment]
It looks like subclassing `tqdm` for our `progress` may have introduced a number of difficulties here.  We can certainly try to work through them (it would ultimately be a good exercise for shoring up our support for more generic python threading models).  But it might also be worth taking a step back on tqdm for now.  Particularly since we've put it only in the qt namespace anyway, we're not exactly pushing at as something that should be used like tqdm.  One thing we could try here is to go back to @DragaDoncila's original implementation that _didn't_ subclass from tqdm (making sure to keep the same API wherever they overlap).  That would mean that we don't get the "time until finished" prediction for now... but we could always re-introduce tqdm later.

@sofroniewn, @DragaDoncila ?

**Comment by DragaDoncila** [comment]
I want to preface this entire message by saying I don't yet understand the interaction between `test_progress` and other tests that was leading to the failures fixed here by @Czaki, and nor do I understand how subclassing `tqdm` is creating these other seemingly unrelated issues. So whatever I say should be taken with a big grain of salt.

> We can certainly try to work through them (it would ultimately be a good exercise for shoring up our support for more generic python threading models). But it might also be worth taking a step back on tqdm for now. 

I think we definitely should try to work through these difficulties, but I don't think it should be done on a 'live' released version of napari. If we're not sure what's going on, but we know it's a direct result of subclassing `tqdm`, then we should not subclass `tqdm`, for now, and work on reintegrating the subclassing sans these odd test failures for the next release.

However, I'm also conscious that we've been working on this release for a while, and this would only slow us further. So my question is - @tlambert03  @Czaki what is the potential impact to the user of the `min_req` test failures (or of the mechanism behind these failures)?

>  One thing we could try here is to go back to @DragaDoncila's original implementation that didn't subclass from tqdm (making sure to keep the same API wherever they overlap).

This seems like the safest choice, and I could start working on this immediately and have a PR up probably by the end of today if not early tomorrow morning AEST reverting the subclassing and keeping the remaining API. If we choose the other option of figuring out the complexities with `tqdm` then I'm not sure how long it would take me, since as I say, I don't yet understand what could be happening. 

I defer to more experienced and knowledgeable individuals on which option seems the best way forward right now.

**Comment by Czaki** [comment]
> I want to preface this entire message by saying I don't yet understand the interaction between `test_progress` and other tests that was leading to the failures fixed here by @Czaki, and nor do I understand how subclassing `tqdm` is creating these other seemingly unrelated issues. So whatever I say should be taken with a big grain of salt.

I think that the problem is caused by Threads spawned by tqdm (at least part of them). Part of these threads are still alive when the `progress` object is destroyed and tries to interact with it.

I think that source of the problem is that by default `tqdm` GUI is matplotlib. Matplotlib has Qt backend so `tqdm` could create some QWidgets, which are not controlled (and cleaned) from tests. But this is only intuition.

**Comment by tlambert03** [comment]
> I think that the problem is caused by Threads spawned by tqdm (at least part of them). Part of these threads are still alive when the `progress` object is destroyed and tries to interact with it.

I think you might be right about this part... but we could test that theory by setting a class attribute of `monitor_interval = 0` on our subclass.  (see [here](https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/std.py#L255) in tqdm source).  That would prevent the creation of the tqdm monitor thread that happens [here](https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/std.py#L568).

> I think that source of the problem is that by default `tqdm` GUI is matplotlib. Matplotlib has Qt backend so `tqdm` could create some QWidgets, which are not controlled (and cleaned) from tests. But this is only intuition.

I disagree with this part...  We're not touching the native tqdm gui or matplotlib here or anything.   The only result of setting`gui=True` on the base tqdm class is the prevention of screen printer creation [here](https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/std.py#L1103-L1107).  The matplotlib part has been moved to an [entirely different subclass](https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/gui.py#L26) that is not being used here.

**Comment by tlambert03** [comment]
@Czaki ... heads, up: I just pushed to your pr here to test the monitor_interval theory a bit.  this will prevent thread creation by tqdm

**Comment by Czaki** [comment]
> I think you might be right about this part... but we could test that theory by setting a class attribute of `monitor_interval = 0` on our subclass. (see [here](https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/std.py#L255) in tqdm source). That would prevent the creation of the tqdm monitor thread that happens [here](https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/std.py#L568).

I test it locally earlier and does not work for the first part. But I think that it is not all things spawned.

**Comment by tlambert03** [comment]
> But I think that its not all thinks spawned.

not sure what this means... are you saying that you think it's still spawning threads?  I just tested it, put some print statements in the tqdm source code where threads get created... and setting `monitor_interval` to 0 makes them go away...

**Comment by Czaki** [comment]
> > But I think that its not all thinks spawned.
> 
> not sure what this means... are you saying that you think it's still spawning threads? I just tested it, put some print statements in the tqdm source code where threads get created... and setting `monitor_interval` to 0 makes them go away...

When I try to find a workaround for `test_progrange` another than create viewer instance I test `monitor_interval = 0` and it does not help. There is still a crash in Qt processing events by Qt. 
The problem disappear when I set `disable=True` which disable second part of `tqdm` constructor.

**Comment by tlambert03** [comment]
> When I try to find a workaround for test_progrange another than create viewer instance I test monitor_interval = 0 and it does not help. There is still a crash in Qt processing events by Qt.

that may be... but the fact that no threads are being created definitely throws a wrench in your theory: "I think that the problem is caused by Threads spawned by tqdm"  ... wouldn't you say?

**Comment by Czaki** [comment]
`monitor_interval = 0` disable only Monitor thread. I'm not sure if this is only one thread.

**Comment by Czaki** [comment]
ops.
```
  napari/_qt/_tests/test_threading.py .....Fatal Python error: Segmentation fault
```

**Comment by tlambert03** [comment]
> I'm not sure if this is only one thread.

easily determined... and I am  :)
I looked through the source. [Tmonitor](https://github.com/tqdm/tqdm/blob/master/tqdm/_monitor.py#L15)
 is the only `threading.Thread` and  `tqdm.__new__` is the only place it's instantiated.  So definitely no threads if you set `monitor_interval` to 0.

So that theory is out, and so is the matlab Qt theory...  

I believe that setting `disabled=True` had an impact... and that's probably an important observation.  but I'm no longer all that confident that any of the theories proposed here have anything to do with it.

**Comment by Czaki** [comment]
> I believe that setting `disabled=True` had an impact... and that's probably an important observation. but I'm no longer all that confident that any of the theories proposed here have anything to do with it.

Maybe you are right. I do a quick review and found that set `disable=True` remove the progress bar from the list of instances https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/std.py#L997 

This could be also achieved by call `close` https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/std.py#L1272 on the progress bar. I need to go now, but one could test it. 

But this intuition may also be bad.

**Comment by DragaDoncila** [comment]
> This could be also achieved by call close https://github.com/tqdm/tqdm/blob/f86104a1f30c38e6f80bfd8fb16d5fcde1e7749f/tqdm/std.py#L1272 on the progress bar. 

This, coupled with your comment about `progrange` earlier made me check that test and I think you're right - I thought we were either calling `close` explicitly or using the progress bars within a context manager but this is the one test where we don't.

Is it as simple as changing the `progrange` test to this:

```python
def test_progrange():
    with progrange(10) as pbr:
        with progress(range(10)) as pbr2:
            assert pbr.iterable == pbr2.iterable
```

**Comment by tlambert03** [comment]
well spotted!  just pushed the change

**Comment by DragaDoncila** [comment]
Ok so that did not address the issue... although I do still think we should keep that change. Do you think explicitly calling `close` would have any effect?

**Comment by tlambert03** [comment]
i've got some stuff working locally.  seems the combination of monitor_interval=0 and _not_ testing `set_description` will do it.  we can punt on figuring out what's going on with that later... will post more later

**Comment by sofroniewn** [comment]
Looks like this is back to just `min_req` failing. Shall we merge? Fine to wait till tomorrow too!!

**Comment by jni** [comment]
I'm going to merge to see if I can get #2723 to only fail on minreq too. Further experimentation can happen in subsequent PRs. Thanks @Czaki, @tlambert03, and @DragaDoncila for all your persistence with this! 👏👏👏

**Pull request merged**
