### PR TITLE
Fix labels mapping cache by filling it with background, not 0

### LINKED ISSUE #6578: Incorrect brush drawing rendering in the direct mode
### 🐛 Bug Report

I haven't been following napari for a while, but today I decided to try the latest main branch and it turned out that the brush drawing in the direct mode is broken as it can be seen in the video below:

https://github.com/napari/napari/assets/5459767/f486534a-04ee-492d-9bc4-a753e926b7aa

I haven't dug into it, but I suspect it is related to the big changes in the color mapping code that were introduced in #6439, #3308

### 💡 Steps to Reproduce

1. Add the following colors to `examples/add_labels.py`:
```python
color = {1: 'white', 2: 'blue', 3: 'green', 4: 'red',
         5: 'yellow', 6: 'pink', 7: 'orange', 8: 'blue', None: 'magenta'}
# add the labels
label_layer = viewer.add_labels(label_image, name='segmentation', color=color)
```
2. Launch `examples/add_labels.py`

### 💡 Expected Behavior

_No response_

### 🌎 Environment

napari: 0.1.dev3200+gbb785f3.d20240108
Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.29
System: Ubuntu 20.04.6 LTS
Python: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.23.0
SciPy: 1.10.0
Dask: 2023.3.2
VisPy: 0.14.1
magicgui: 0.7.2
superqt: 0.6.1
in-n-out: 0.1.7
app-model: 0.2.4
npe2: 0.7.3

OpenGL:
  - GL version:  4.6.0 NVIDIA 525.147.05
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 2560x1440, scale 1.0
  - screen 2: resolution 1920x1080, scale 1.0

Settings path:
  - /home/konstantin/.config/napari/usr_5c0e77c46be77719bc1c0a5ec9c64b94d2a2e50c/settings.yaml
Plugins:
  - napari: 0.1.dev3200+gbb785f3.d20240108 (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

### 💡 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues

closes #6578
updates example to mitigate #6579

# Description

Because unknown values are mapped to 0 in direct mode, filing the cache with 0 leads to artifacts as reported in #6578. In this PR, the mapped cache is instead filled with the result of mapping the background to the correct dtype.

### CODE REVIEW

**Review by jni — APPROVED** [review]
@Czaki I've pushed some minor changes, but otherwise this LGTM.

**Comment by jni** [comment]
(Ideally, we should add a test here. But I'm a fan of not requiring improvements that weren't there before, so imho this can be merged without it.)

**Comment by jni** [comment]
Hmm, @Czaki this was a simple change, I think it is better to merge this and then optimize on top?

**Comment by Czaki** [comment]
If You want we could reopen it and merge, then I resolve conflicts in #6583. But without fast merge it will block #6583

**Comment by jni** [comment]
Yeah, I would prefer that, I think a fast merge is ok, especially since it closes a bug and no longer 😉 closes the performance issue. Do you have ideas for testing this, btw? I think a robust test here is more important/urgent than the performance issues, since they have an easy workaround by using a reduced dtype.

**Pull request merged**
