### PR TITLE
Add vortex optical flow example

### PR DESCRIPTION
**Pull request by jni**
# Fixes/Closes

Add example of optical flow to the gallery, based on scikit-image.

Screenshot 2023-07-06 at 8 08 33 pm

<details>

<summary>

Epilepsy warning: the movie has some bright/dark flashing.

</summary>

https://github.com/napari/napari/assets/492549/e34a8872-919f-45e5-ab84-f467f24fa310

</details>

I can remove the reverse phi stuff if people think it's too annoying/dangerous. But it's cool, thought I'd pull up a flashback from my postdoc 😂

### CODE REVIEW

**Review by kephale — APPROVED** [review]
This is a useful example. The flashing during playback should be opt-in.

**Comment by jni** [comment]
I was wondering how I would make it opt-in @kephale... Do I just add both the normal contrast frames and the concatenated frames and make the concatenated version invisible? I could even add *only* the reverse contrast frames with an offset. But I worry both those options will be confusing...

I could also get rid of it altogether... But it's fun to see, no? 😃

**Comment by kephale** [comment]
I could see something like this helping in the long term: https://github.com/napari/napari/issues/6045

An short-term alternative is to use a colormap for `vortex_phi` like `twilight` that wraps around the color values.

**Comment by kephale** [comment]
Ok, poked a little more and I'm leaning to:

```
import numpy as np
from skimage.data import vortex
from skimage.registration import optical_flow_ilk
from scipy.ndimage import zoom

import napari

#######################################################################
# First, we load the vortex image, and then we create an inverted
# "negative" image. For the illusion, we concatenate them end-to-end.

stretch_factor = 5

vortex_im = np.asarray(vortex())
vortex_im = zoom(vortex_im, (stretch_factor, 1, 1), order=1)
vortex_neg = np.max(vortex_im) - vortex_im
vortex_phi = np.concatenate((vortex_im, vortex_neg), axis=0)
```

The vector lines need tweaking to be visible, but it still has the cool visual effect with less strobing. However, I would still be pretty tempted to not show `vortex_neg`.

https://github.com/napari/napari/assets/400105/7d43c59e-9929-40bc-af04-83abdda00ed3

**Comment by jni** [comment]
@kephale 

> An short-term alternative is to use a colormap for vortex_phi like twilight that wraps around the color values.

Then you would lose the illusion which is the whole point of the thing! 😂 The effect only works when you invert the contrast of the whole image. The only way to make it less stroby is to use a different image that has ~50% white pixels. And I'm not 100% convinced it would work anyway. I'm happy to drop it, I just thought it was a cute application and wanted to write it down somewhere. 😃 I'll do the standard vortex here and save the reverse-phi for my (long neglected) napari-demos repo. 

Also what on earth did you do to my vectors 😂

**Comment by kephale** [comment]
https://github.com/napari/napari/assets/400105/89c9a179-4c3a-4f56-9b23-8a002ab514de



This seems to keep a balance between maintaining the illusion and having a gentle transition.

Yeah, vectors are super borked right now.

**Comment by jni** [comment]
@kephale @napari/core-devs I've removed the reverse-phi illusion because (a) it was a bit controversial and (b) anyway it made the example more complicated than it needed to be.

The reverse-phi demo lives on at https://github.com/jni/napari-demos/blob/main/vortex.py

Since @kephale already approved this and it doesn't affect the main code in any way, I'm going to add the "ready-to-merge" label.

**Comment by Czaki** [comment]
@jni could you fix milestone?

**Comment by Carreau** [comment]
This got the "Ready-to-merge" label 2 days ago and got no objections. Merging to move the queue forward. 

Thanks.

**Pull request merged**
