### PR TITLE
[Maint] Exclude pyqt6 6.6.1 on macOS in  pyproject.toml

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# References and relevant issues
Due to the intermittent seg fault, for example opening images or switching to 3D: https://github.com/napari/napari/issues/6550
See also: https://github.com/napari/napari/issues/6550#issuecomment-1997671924

# Description
Excludes the PyQt6 6.6.1 on macOS only. Should be fixed when 6.6.2 is released.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Review by Czaki — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Pull request merged**
