### PR TITLE
Bugfix/Add affine to base_dict via _get_base_state()

### LINKED ISSUE #4450: Labels-to-Image conversion does not preserve transform
## 🐛 Bug

It seems that the conversion between `Labels` and `Image` loses the transform associated with the layer.

## To Reproduce

1. Add a `Labels` layer to the viewer with `Viewer.add_labels(..., affine=affine)`
2. In the viewer, right-click on the `Labels` layer and `Convert to Image`
3. The transform is lost

## Expected behavior

Upon conversion, the image should re-appear in the same place as the mask was

## Environment

napari: 0.4.16.dev101+g2648c307
Platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.4 LTS
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.6
SciPy: 1.8.0
Dask: 2022.04.1
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 510.54
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.16.dev101+g2648c307

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description
This PR adds `affine.affine_matrix` to the `base_dict` generated by `_get_base_state()`.
This function is called by the `_convert` layer actions, so this ensures that converted layers retain the affines of the original, fixing https://github.com/napari/napari/issues/4450

Try the following in the napari console:
```python
import numpy as np

from skimage.data import binary_blobs
viewer.add_image(binary_blobs(64, volume_fraction=.2, n_dim=3), affine=np.array([[1, -1, 4], [2, 3, 2], [0, 0, 1]]))

from napari.layers._layer_actions import _convert
_convert(viewer.layers, type_="labels")
```
On `main` the labels layer will be square, with the affine not applied. With this PR, the labels layer will be transformed.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# References
Closes https://github.com/napari/napari/issues/4450

# How has this been tested?
- [x] locally running `pytest` on `test_layer_actions.py ` results in all pass.
- [x] fixed `test_serialize` to account for the extra property in `test_attrs_arrays`. Now all pass.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
Hmmm, the npe2 writer test is failing:

```
  __________________________________ test_write __________________________________
  
  mock_pm = <npe2._plugin_manager.PluginManager object at 0x7fab2b5bc7f0>
  
      def test_write(mock_pm: PluginManager):
          # saving an image without a writer goes straight to npe2.write
          # it will use our plugin writer
          image = Image(np.random.rand(20, 20), name='ex_img')
          _npe2.write_layers('some_file.tif', [image])
          mock_pm.commands.get.assert_called_once_with(f'{PLUGIN_NAME}.my_writer')
      
          # points won't trigger our sample writer
          mock_pm.commands.get.reset_mock()
          points = Points(np.random.rand(20, 2), name='ex_points')
          _npe2.write_layers('some_file.tif', [points])
          mock_pm.commands.get.assert_not_called()
      
          # calling _npe2.write_layers with a specific writer contribution should
          # directly execute the writer.exec with arguments appropriate for the
          # writer spec (single or multi-writer)
          mock_pm.commands.get.reset_mock()
          writer = mock_pm.get_manifest(PLUGIN_NAME).contributions.writers[0]
          writer = MagicMock(wraps=writer)
          writer.exec.return_value = ['']
          assert _npe2.write_layers('some_file.tif', [points], writer=writer) == ['']
          mock_pm.commands.get.assert_not_called()
          expected_args = ('some_file.tif', *points.as_layer_data_tuple()[:2])
  >       writer.exec.assert_called_once_with(args=expected_args)
  
  napari/plugins/_tests/test_npe2.py:117: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  /opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/unittest/mock.py:931: in assert_called_once_with
      return self.assert_called_with(*args, **kwargs)
  /opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/unittest/mock.py:917: in assert_called_with
      if actual != expected:
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = call(args=('some_file.tif', array([[0.55468781, 0.28705152],
         [0.70657471, 0.41485687],
         [0.36054556, 0.82...ue,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True])}))
  other = call(args=('some_file.tif', array([[0.55468781, 0.28705152],
         [0.70657471, 0.41485687],
         [0.36054556, 0.82...ue,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True])}))
  
      def __eq__(self, other):
          try:
              len_other = len(other)
          except TypeError:
              return NotImplemented
      
          self_name = ''
          if len(self) == 2:
              self_args, self_kwargs = self
          else:
              self_name, self_args, self_kwargs = self
      
          if (getattr(self, '_mock_parent', None) and getattr(other, '_mock_parent', None)
                  and self._mock_parent != other._mock_parent):
              return False
      
          other_name = ''
          if len_other == 0:
              other_args, other_kwargs = (), {}
          elif len_other == 3:
              other_name, other_args, other_kwargs = other
          elif len_other == 1:
              value, = other
              if isinstance(value, tuple):
                  other_args = value
                  other_kwargs = {}
              elif isinstance(value, str):
                  other_name = value
                  other_args, other_kwargs = (), {}
              else:
                  other_args = ()
                  other_kwargs = value
          elif len_other == 2:
              # could be (name, args) or (name, kwargs) or (args, kwargs)
              first, second = other
              if isinstance(first, str):
                  other_name = first
                  if isinstance(second, tuple):
                      other_args, other_kwargs = second, {}
                  else:
                      other_args, other_kwargs = (), second
              else:
                  other_args, other_kwargs = first, second
          else:
              return False
      
          if self_name and other_name != self_name:
              return False
      
          # this order is important for ANY to work!
  >       return (other_args, other_kwargs) == (self_args, self_kwargs)
  E       ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
  
  /opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/unittest/mock.py:2537: ValueError
```

Sounds like it's failing to compare the affine matrices with each other because they are arrays. I don't know what the best way to fix would be. CC @ppwadhwa (who wrote the tests), @tlambert03

**Comment by jni** [comment]
btw, thank you @psobolewskiPhD, I am loving your PRs! 😊

**Comment by tlambert03** [comment]
> I don't know what the best way to fix would be. CC @ppwadhwa (who wrote the tests), @tlambert03

argh, yeah I think this is one of those cases where we'd have to special case numpy arrays .  The `assert_called_once_with` method (provided by the `Mock` being used in the test here) isn't nuanced enough to use `array_equal` for numpy arrays.   So the options are 
1) don't use the mock 'assert_called_once_with' method, and instead, manually compare the mock's [`call_args_list`]( https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.call_args_list) with the `expected_args` in the failing test here
2) just do a much less thorough test, possibly don't even check the called args at all (i.e.  just a smoke test)

the first option would be better, but turns what was a very simple PR into a slightly more detailed lesson in mocks :)

**Comment by tlambert03** [comment]
sorry for empty comment, updated above

**Comment by jni** [comment]
@tlambert03 could we use a subclass of Mock that uses `array_equal` for arrays?

**Comment by tlambert03** [comment]
That's a good idea 👍

**Comment by tlambert03** [comment]
took a very quick look at this.  It's doable, but not quite as easily accessible to a subclass as I'd like.  I'd be completely fine with modifying the last few lines of the offending `test_write` function here  (in `_tests/test_npe2.py`) to be:

```python
    assert _npe2.write_layers('some_file.tif', [points], writer=writer) == ['']
    mock_pm.commands.get.assert_not_called()
    writer.exec.assert_called_once()
    assert writer.exec.call_args_list[0].kwargs['args'][0] == 'some_file.tif'

```

**Comment by jni** [comment]
Ok I've made #4457 with that change, thank you @tlambert03!

@psobolewskiPhD once that is merged, we can update this with main and get it in! 😊

**Review by jni — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
Sorry, been crazy busy.
Can't say I'm following the thread—this PR somehow broke seemingly unrelated tests? 🤯

**Review by sofroniewn — APPROVED** [review]
All tests passing now here - thanks all!! I will merge 🚀

**Pull request merged**
