### PR TITLE
Add numpydoc to default dependencies

### LINKED ISSUE #597: Need to manually install numpydoc -- version 0.2.1
## 🐛 Bug

Not sure if you are aware but after updating napari to version 0.2.1, I had to manually install numpydoc, which I didn't need before. 

## To Reproduce

Not have numpydoc installed

### PR DESCRIPTION
**Pull request by jni**
Fixes #597

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by AhmetCanSolak — APPROVED** [review]

**Comment by jni** [comment]
Will merge/feel free to merge once CI passes.

**Comment by jni** [comment]
Thanks @AhmetCanSolak for the lightning review! :joy:

**Comment by sofroniewn** [comment]
should I release `0.2.1.1` right away?

**Comment by jni** [comment]
0.2.2

**Pull request merged**
