### PR TITLE
Try to upload pytest json report as artifact.

### PR DESCRIPTION
**Pull request by Carreau**
Mostly I want to investigate why tests are taking forever on CI,
like up to 45 minutes. It's hard with just printing the slowest 10
durations, as this may be dues to some test having for example many
parameters.

With this I should be able to download the artifact and analyse them.

### CODE REVIEW

**Comment by Carreau** [comment]
The goal being to create something like the following (interactive), that show us which groups of test(s) potentially across platforms are taking the most time. 
Screen Shot 2022-05-12 at 17 07 21

Here we see that likely we want to optimise test_add_layer, and zooming in show us that most of the time is spent there because of the large number of parameters:


Screen Shot 2022-05-12 at 17 10 08

**Comment by Carreau** [comment]
This allowed me to find #4521 that greatly speedup the test suite.

**Comment by Carreau** [comment]
To try, you can head to the test suite summary, download the artifacts. 
And drag and drop the resulting files on this page: 

https://carreau.github.io/pytest-json-report-viewer/

You will get a breakdown you can explore.

**Review by Czaki — APPROVED** [review]

**Comment by Carreau** [comment]
Self merging again, we can refine later.

**Pull request merged**
