### PR TITLE
Fix canvas none after layer deletion

### LINKED ISSUE #1157: Deleting layer throws error and viewing area is empty
## To Reproduce

1. Load images or create other layers in `napari`
2. Select layer and click trash button, or drag to trash
3. Viewing area goes black and following trace is printed:

```
Traceback (most recent call last):
  File "XXXX\lib\site-packages\vispy\app\backends\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "XXXX\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "XXXX\lib\site-packages\vispy\util\event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "XXXX\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "YYY\napari\napari\_vispy\vispy_base_layer.py", line 234, in on_draw
    self.layer.scale_factor = self.scale_factor
  File "YYY\napari\napari\_vispy\vispy_base_layer.py", line 131, in scale_factor
    transform = self.node.canvas.scene.node_transform(self.node)
AttributeError: 'NoneType' object has no attribute 'scene'
```

I checked out various commits, and narrowed it down to `f9ca768` (#1053 Fix pyramid clipping). 

Perhaps @sofroniewn might have the best idea.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.2.12+61.g5c30662
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
Qt: 5.14.1
PySide2: 5.14.1
NumPy: 1.18.1
SciPy: 1.4.1
Dask: 2.12.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 441.45
MAX_TEXTURE_SIZE: 32768

Plugins:
- mat-images: 0.1.0
```

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
Closes #1157 by catching if `node.canvas` is `None` before trying to use it, and adds a test to check this does not get used after a layer is deleted.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by sofroniewn** [comment]
Tests are failing due to a CI issue with the `view.canvas.events.draw()` call - this passes fine locally and is needed to trigger the original bug. I need to look into this more

**Comment by sofroniewn** [comment]
hmm - this isn't going so well, looks like it passes on mac, but fails on linux pyqt5 and fails on windows. the windows test doesn't surprise me as vispy fails there too so the canvas draw command fails. We added in #1053 some `skipif` statements for windows for tests like that. Maybe @tlambert03 can weigh in here with ideas on how to maybe fix this?

**Comment by sofroniewn** [comment]
So I can't figure out how to write a test that detects the bug pre-merge but also passes all of our CI due to vispy errors, so I have added a skip on the test. Given how bad the current bug is - deleting a layer on master will through an error and that this PR fixes it I think we should merge the PR and then revisit this in the future.

Thoughts @jni @tlambert03?

**Comment by tlambert03** [comment]
That’s fine with me. Does the test work on Mac?  If so, maybe just skip on Linux and windows and open an issue?

**Review by tlambert03 — APPROVED** [review]

**Comment by sofroniewn** [comment]
Have made skip conditional on windows/ linux we'll see how this goes ...

**Comment by sofroniewn** [comment]
Tests are all passing, merging now - can revisit for better testing in the future

**Pull request merged**
