### PR TITLE
Update build_docs workflow

### PR DESCRIPTION
**Pull request by aganders3**
# Description
This updates the Build PR Docs workflow to match [recent changes in `napari/docs`](https://github.com/napari/docs/pull/5).

Maybe there's a better way to sync these workflows between repos - e.g. this repo can get the workflow from the docs repo - but for now this should fix CI.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# How has this been tested?
Tested workflow in my fork with a successful run: https://github.com/aganders3/napari/actions/runs/3686819198

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
Let's get this in quick so we unblock the CI.

**Review by Czaki — APPROVED** [review]

**Comment by Czaki** [comment]
As the lack of this will fail all existing workflows, I will merge this immediately.

**Comment by Czaki** [comment]
I see that also build docs on main requires update https://github.com/napari/napari/actions/runs/3696253441/jobs/6259704620

**Comment by aganders3** [comment]
Looks like there's an approved but unmerged PR for this already: https://github.com/napari/docs/pull/70

**Pull request merged**
