### PR TITLE
Use app-model `KeyBinding.to_text` and `KeyCode.os_symbol` over `Shortcut` logic

### PR DESCRIPTION
**Pull request by dalthviz**
# References and relevant issues

Part of #7059

# Description

* Use the work done at https://github.com/pyapp-kit/app-model/pull/211
* Bump app-model constraint to >=0.2.8
* Alternative to PR #7093 (without doing any major refactor to the shortcut widget logic)

### CODE REVIEW

**Comment by dalthviz** [comment]
@napari-bot update constraints

**Comment by dalthviz** [comment]
@napari-bot update constraints

**Comment by dalthviz** [comment]
@napari-bot update constraints

**Review by lucyleeow — APPROVED** [review]
LGTM!

**Review by DragaDoncila — APPROVED** [review]
Looks good to me! Pulled it down and played with it on Mac and Linux - and discovered the Escape symbol in the process lol.

**Comment by lucyleeow** [comment]
Thanks @dalthviz (my first merge on napari :tada: )

**Pull request merged**
