### PR TITLE
Interactive tracks

### PR DESCRIPTION
**Pull request by JoOkuma**
# Description

This PR adds an interactive mode to the `Tracks` layer.
The user can switch to the interactive mode with a checkbox in the layer controls. However, it doesn't offer any additional functionality to the existing UI and its functionalities can only be accessed through code for now. 
Because my goal with this PR is to expose a new API (`InteractiveTrackManager`) for on-the-fly changes to the tracks graph so plugins can use it to edit tracks, and later these plugins might be merged into napari.

In summary, the interactive mode converts the `TrackManager` to an `InteractiveTrackManager` that exposes a few new methods:
- `add`:  to add a new node to the tracks graph;
- `remove`: to remove an existing node;
- `link`:  to link two existing nodes;
- `unlink`: to unlink a set of nodes;
- `update`: to update a node position and/or `features`.

Since this PR introduces a new data structure to store the tracks data we benchmark (using Intel MacBook Pro 13") the new `InteractiveTrackManager` against the existing `TrackManager`. 

We compare the construction with serialization (necessary only in the interactive mode) performance with datasets of multiple sizes, the number of tracks, and if they're already sorted in the expected ordering.

This experiment is to check if the `InteractiveTrackManager` could replace the existing manager completely by being faster in every instance (not the case).

### TrackManager

```       
              ========= ============ ============= =========== ============
              --                         sorted / n_tracks
              --------- ---------------------------------------------------
                 size    False / 10   False / 100   True / 10   True / 100
              ========= ============ ============= =========== ============
                 100      581±0μs       531±0μs      577±0μs     516±0μs
                 1000     2.00±0ms      1.21±0ms     1.57±0ms    1.25±0ms
                10000     32.1±0ms      9.15±0ms     21.7±0ms    8.19±0ms
                100000    1.19±0s       282±0ms      1.28±0s     191±0ms
               1000000     failed       24.3±0s       failed     24.0±0s
              ========= ============ ============= =========== ============
```

### InteractiveTrackManager
```         
               ========= ============ ============= =========== ============
              --                         sorted / n_tracks
              --------- ---------------------------------------------------
                 size    False / 10   False / 100   True / 10   True / 100
              ========= ============ ============= =========== ============
                 100      3.52±0ms      11.3±0ms     3.28±0ms    11.2±0ms
                 1000     7.04±0ms      21.1±0ms     7.01±0ms    20.2±0ms
                10000     51.2±0ms      64.2±0ms     51.5±0ms    60.4±0ms
                100000    476±0ms       462±0ms      485±0ms     448±0ms
               1000000    4.83±0s       4.78±0s      4.52±0s     4.53±0s
              ========= ============ ============= =========== ============
```

The `InteractiveTrackManager` is slower except with 100k nodes and 10 tracks or 1mi nodes.

I profiled the `InteractiveTrackManager` code and saw that most of the time is spent allocating the `Node`s so I checked that the initialization time could be greatly reduced by pre-allocating a pool of `Node`s, but I'm not sure if it is worth the increase in the complexity of the code.

The real advantage of the `InteractiveTrackManager` is that it only needs to serialize the data (convert to the default tabular format), while the `TrackManager` needs to reload everything from scratch after any change to the data.

Here is the benchmark of the serialization:
```        
              ========= ============ ============= =========== ============
              --                         sorted / n_tracks
              --------- ---------------------------------------------------
                 size    False / 10   False / 100   True / 10   True / 100
              ========= ============ ============= =========== ============
                 100      315±0μs       327±0μs      299±0μs     455±0μs
                 1000     1.18±0ms      1.11±0ms     1.25±0ms    1.65±0ms
                10000     12.2±0ms      10.3±0ms     11.8±0ms    12.0±0ms
                100000    134±0ms       123±0ms      117±0ms     106±0ms
               1000000    1.12±0s       1.15±0s      1.15±0s     1.16±0s
              ========= ============ ============= =========== ============
```

The serialization is only computed when the data is requested after a change in the graph, and most of the requests are for the visualization of the tracks.
Later, we could update the `Track` layer slicing and update the `TrackVisual` so we transverse only the nodes in a specific time window (this is already supported), further reducing the serialization time to a fraction of this and maybe achieving real-time performance with 1mi plus nodes datasets.

### Caveats

I decided to not keep track of the original track ids because as the user splits (merges) the tracks, new tracks are generated (removed) and their new ids would be arbitrary. So if the user wants to recover the original track ids they need to call `relabel_track_ids` and provide the mapping. Track ids not present in the mapping are given the next available id.

The `get_value` and `track_labels` methods return the node id in the interactive mode while the default mode returns the track id. This affects the displayed labels in the UI. I decided to change this because it avoids serializing the data and when we are correcting tracks our interaction is at the node level and not at the track level. For example, a node id could be mapped to a segment in a label layer, and this information is lost at the track-id level.

During interactive mode, the `data`, `graph`, and `features` setters are disabled because they must be supplied at once with the `set_data` method.

## Type of change
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
It implements some of the points mentioned in #3861, and it adds some functionality discussed in #3779.
It's also a step forward to closing #3111 because the `InteractiveTrackManager` can be initialized without any tracks, but I haven't checked if the vispy `TrackVisual` works as expected.

# How has this been tested?
- [X] Added new tests cases for the new class trying to cover most of the edge cases.
- [X] Added a new benchmark to compare its performance with the default TrackManager.
- [X] The interactive mode works with the existing tracking examples.
- [X] It passes the existing tracks test.

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

cc @quantumjot @jni @DragaDoncila

### CODE REVIEW

**Comment by JoOkuma** [comment]
I changed the variable `interactive_mode` to the existing `enable` as suggested by @alisterburt.

**Comment by quantumjot** [comment]
Hi @JoOkuma - this looks exciting! I'm going to take a look at the PR over the next couple of weeks and try to provide some feedback for you from our perspective.

**Comment by alisterburt** [comment]
a little extra context on @JoOkuma's name change

because we already use `layer.interactive` to control whether the scene can be manipulated the name `interactive` might be a little confusing, `editable` is used in the points layer so we reuse here

https://github.com/napari/napari/blob/dbf0fbc62e9bdd974cddfdf9be49085918992cb5/napari/layers/points/points.py#L1286-L1291

**Comment by jni** [comment]
Hi @JoOkuma!

This is very exciting! Thanks for making the PR. 😊 

I've only had a fast pass so far. My biggest concern is going with a custom graph data structure as opposed to something standard in the ecosystem such as networkx. Have you explored that idea at all? As far as I can tell, a networkx DiGraph would do everything you need here with minimal (if any) performance cost, and you'd get some traversal algorithms for free. (Not sure yet whether they would suit your purposes directly.) In addition to having some built-in algorithms, another advantage of using nx is that more users will be familiar with the data structure, so more users would be able to contribute improvements in the future.

Coincidentally, the [ELEPHANT](https://elifesciences.org/articles/69380) paper just came out, and I found this [supplementary file](https://github.com/mastodon-sc/mastodon/blob/master/doc/trackmate-graph.pdf), describing their space-efficient and editable graph data structure, very interesting. I wouldn't say we need to emulate it straight away, but it is something we should keep in mind as a possible target to implement as we iterate and aim for very fast performance.

I also would like to get this PR to a point where we don't need to maintain two separate managers. From what I understand of the current implementation, given the caching of the serialization (this is a clever way to make a minimal PR, btw! 👏), the time costs measured in your benchmarks are one-time costs, and subsequent operations (e.g. slicing around in the volume) should be identical between the two managers? If that is the case, I personally would favour only keeping the new stuff.

**Comment by grlee77** [comment]
Hi @JoOkuma, I took an initial look and made some minor performance refactor suggestions in JoOkuma/napari#1 that give up to 25% reduction in initialization time with size=1,000,000 on my system. I have not yet looked into potential larger scale reorganizations as mentioned by @jni in the prior comment.

**Comment by JoOkuma** [comment]
@grlee77 Thanks for the PR, I left a comment on the PR itself.

@jni I was concerned with NetworkX because it depends on matplotlib.

Also, I tried using it before in some other applications and it was really slow. But it might be worth the shot because our implementation is entirely in python as well.

I'm not sure if you have any experience with [igraph](https://igraph.org/), it's much faster [1] but I'm not sure how portable it's. Additionally, our graph transverse operation for serialization is custom because the tracks can have splits and merge so there might not be any benefits in using a C library if we do this in Python.

[1] https://www.timlrx.com/blog/benchmark-of-popular-graph-network-packages-v2

**Comment by JoOkuma** [comment]
I forgot to answer this.

> From what I understand of the current implementation, given the caching of the serialization (this is a clever way to make a minimal PR, btw! clap), the time costs measured in your benchmarks are one-time costs, and subsequent operations (e.g. slicing around in the volume) should be identical between the two managers? If that is the case, I personally would favour only keeping the new stuff.

Slicing is identical if the data didn't change. If the user updated the data the new implementation only needs to serialize the data, so it's much faster (3rd table vs 1st table).

I'll try to implement the slicing of the tracks in the next couple of days so the slicing should get even faster.

**Comment by jni** [comment]
@JoOkuma 

> I was concerned with NetworkX because it depends on matplotlib.

Um, no it doesn't?

https://github.com/networkx/networkx/blob/main/setup.py#L165

and:

```
 $ conda create -n nx python=3.10
Collecting package metadata (current_repodata.json): done
Solving environment: done

[SNIPPED]
 
 $ conda activate nx
 $ pip install networkx
Collecting networkx
  Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 4.7 MB/s 
Installing collected packages: networkx
Successfully installed networkx-2.6.3
```

Conversely, I am much more concerned about igraph because it depends on compiled code.

**Comment by JoOkuma** [comment]
@jni Uhm..., I thought [default](https://github.com/networkx/networkx/blob/main/requirements/default.txt) was required by default.

**Comment by jni** [comment]
> Also, I tried using it before in some other applications and it was really slow. But it might be worth the shot because our implementation is entirely in python as well.

And yes, my main point is that I suspect your custom implementation will probably be equally slow. But maybe not! But we should check it out anyway.

> I thought default was required by default.

Interesting! Evidently not — probably some relic from earlier versions?

**Comment by JoOkuma** [comment]
I updated the benchmarks to reflect more closely what I expect the tracking data to be like --- more tracks, 100 was too few for 1mi plus nodes. When `n_tracks` is greater than 10 times `size` I reduce the `n_tracks`.

In these scenarios, the existing manager initialization is not as bad, but it's still not adequate for 1mi plus nodes.

IMPORTANT: different computer from the previous benchmark.

## Initialization benchmark

### TrackManager
```
             ========= ========== ========== ==========
              --                    n_tracks            
              --------- --------------------------------
                 size       10        100        1000   
              ========= ========== ========== ==========
                 500     1.18±0ms   1.00±0ms   2.45±0ms 
                 5000    7.82±0ms   8.12±0ms   12.8±0ms 
                50000    313±0ms    57.6±0ms   37.6±0ms 
                500000   38.7±0s    4.23±0s    821±0ms  
               5000000    failed     failed    52.0±0s  
              ========= ========== ========== ==========
```

### InteractiveTrackManager
```
              ========= ========== ========== ==========
              --                    n_tracks            
              --------- --------------------------------
                 size       10        100        1000   
              ========= ========== ========== ==========
                 500     5.83±0ms   24.2±0ms   12.4±0ms 
                 5000    24.4±0ms   33.6±0ms   99.2±0ms 
                50000    136±0ms    144±0ms    303±0ms  
                500000   1.34±0s    1.33±0s    1.46±0s  
               5000000   13.4±0s    13.5±0s    13.9±0s  
              ========= ========== ========== ==========
```

I also updated the `_view_data` method so only a `time_window` is serialized given the current time point and the tail (head) length when using the `InteractiveTrackManager`.

## Serialization benchmark (given a window)

```
              ========= ========== ========== ========== ========== ==========
              --                             time_window                      
              --------- ------------------------------------------------------
                 size       10         50        100        200        400    
              ========= ========== ========== ========== ========== ==========
                 500     686±0μs    1.01±0ms   762±0μs    995±0μs    1.51±0ms 
                 5000    1.56±0ms   4.60±0ms   4.75±0ms   4.67±0ms   5.01±0ms 
                50000    1.46±0ms   5.27±0ms   10.0±0ms   18.9±0ms   38.5±0ms 
                500000   1.60±0ms   5.51±0ms   10.1±0ms   19.2±0ms   39.9±0ms 
               5000000   1.70±0ms   5.82±0ms   11.0±0ms   19.9±0ms   39.1±0ms 
              ========= ========== ========== ========== ========== ==========
```

I think this would be enough to interact and update the canvas in real-time.

I still need to do some additional things:
- [ ] test implementation with NetworkX;
- [ ] `track_color` given a view needs to be implemented (disabled for testing);
- [ ] `_extent_data`, `_slicing_indices` and `_ndim` are forcing the data to be serialized and need to be fixed;
- [ ] write tests to `_view_data`.

### Remarks

Our tracks' data format is convenient for the user but is not very performant. Other tools such as TrackMate have their own file format. I like how it's but we should take this into consideration when it takes a few seconds to load a very large dataset in pure python.

**Comment by sofroniewn** [comment]
@JoOkuma I was wondering if you could give us an update on the status of this PR when you get the chance. thanks!! cc @jni

**Comment by JoOkuma** [comment]
Hi @sofroniewn, I need to rework a couple of things on this PR. I added additional features that I'm using on my plugin that should not be added to napari. 

While using this fork on our datasets a few things got clear to me:
- The existing TracksManager should be replaced, it's very slow to large datasets taking more than 40 minutes to load with 2 million + nodes, depending on the number of tracks. Therefore, using it as an intermediate for the InteractiveTracksManager isn't a good option.
- The tracks data format (table) could be reworked, it contributes to the slow initialization of the tracks layer, and actions (e.g. add node, split tracks) yield arbitrary changes to the table, adding complexity to following the nodes and tracks ids.

For the first item, I need to make sure that this new implementation is on par with the performance of the existing TracksManager.
**I think we're not that far from this.**

Regarding the data format, I think we should pick a graph library and format to be our standard (relevant to #4274). My discussion with @jni and @DragaDoncila about this stopped at: networkx is slow; scipy csgraph could be an option and the coordinates information could be supplied through the layer's features.
**This is blocking me.**

**Comment by JoOkuma** [comment]
@sofroniewn, I think we should close this PR. I'm working on the [napari-graph](https://github.com/napari/napari-graph) in my spare time and it will be a better solution.

With the recently ranged slice, I think it might be doable to have a single graph layer for tracks and graphs, we'll see.

**Comment by sofroniewn** [comment]
> @sofroniewn, I think we should close this PR. I'm working on the [napari-graph](https://github.com/napari/napari-graph) in my spare time and it will be a better solution.

ok sounds good - will close now, we can always reopen

**Pull request closed without merging**
