### PR TITLE
Bump vispy to 0.13

### LINKED ISSUE #5530: Qt6: WARNING: skipping QEventPoint when using trackpad (maybe macOS only?)
## 🐛 Bug

When using Qt6 backend, while mousing using a trackpad, such as adding Points to a Points layer, a warning is generated, occasionally/randomly:
```
WARNING: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=873.796,480.551 gbl=873.796,480.551 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-873.796,-480.551 last=-873.796,-480.551 Δ 873.796,480.551) : no target window
12:40:45 WARNING skipping QEventPoint(id=1 ts=0 pos=0,0 scn=873.796,480.551 gbl=873.796,480.551 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-873.796,-480.551 last=-873.796,-480.551 Δ 873.796,480.551) : no target window
```
First reported in the Qt6 tracking issue:
https://github.com/napari/napari/issues/3880#issuecomment-1000927698

This occurs on both PyQt6 and PySide6, it seems to be related to an upstream Qt6 issue:
https://bugreports.qt.io/browse/QTBUG-103935?gerritReviewStatus=All

It may be a macOS only issue or a trackpad only issue and it appears that the warning is harmless (see the qt.io thread). The suggested solution is to unsetting `WA_AcceptTouchEvents`, which is upstream of napari in vispy.

## To Reproduce

On a computer using a trackpad, such as mac laptop:

1. install Qt6 backend (pyqt6 or pyside6)
2. `pip install napari` (no [all] to use the Qt6 backend)
3. open Astronaut sample image
4. make a labels or points layer — this reliably triggers the warning at least once.

This can also be reproduced with just vispy using for example the `turntable_box.py` example and mousing around.

## Expected behavior

No warning, even if it's harmless.

## Environment

 Qt6 (pyqt6 or pyside6), macOS 13.2 arm64, laptop, using trackpad.

## Additional context

This needs to be fixed upstream in vispy. 
The key code is here:
https://github.com/vispy/vispy/blob/c0d7457a7b1717d47baa8b8622faa2c67bbe4be0/vispy/app/backends/_qt.py#L413-L423

Based on the Qt thread linked above and docs, TouchEvents are intended for touchscreens, while gestures should be handled using QtNativeGestureEvent:
https://doc.qt.io/qtforpython/PySide6/QtGui/QNativeGestureEvent.html#more

### PR DESCRIPTION
**Pull request by brisvag**
# Description
Bump vispy to 0.13 to get some extra features. Relevant changes are:

- vispy/vispy#2465, which can improve performance dramatically for `mip`-style projections in volumes by stopping the ray cast early if the max clim was already reached
- a couple improvements to touchaped gestures (vispy/vispy#2456, vispy/vispy#2483)

Reverted defaults of `Markers.scaling` also mean that we need to add a couple lines in napari to maintain the same behaviour ( see vispy/vispy#2359 and #5312 if you want to dive deeper).

cc @aganders3 who did much of the vispy work :)

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@brisvag need to bump the constraints files to get CI to run.

**Comment by Czaki** [comment]
Right now, you need to open PR from a branch in napari repo or manually recalculate constraints. Or enable update requirements workflow in your repository.

**Comment by brisvag** [comment]
> Or enable update requirements workflow in your repository.

Is this a repo setting that I can somehow enable, or does it require changing the code temporarily to trigger the workflow on non-napari repo?

**Comment by jni** [comment]
@brisvag I think you just need to change the settings on your fork to run Actions. Here are the conditions under which the constraints-updater runs:

https://github.com/napari/napari/blob/acddda2000ef6498731c4687cfb5ac60e378a68a/.github/workflows/upgrade_test_constraints.yml#L9-L17

So I *think* that if you turn on actions on your fork, this one will run, and when you push to this branch (you might need to make a trivial change to setup.cfg and undo it), you should get a PR against it from the bot. I think!

**Comment by brisvag** [comment]
Almost worked,  but it seems I need to provide a token. Not sure what token it should be? @Czaki ?

**Comment by brisvag** [comment]
Thanks @Carreau; I was trying to set up the action on my branch, but got stuck... I still want to figure this out for the future, so I'll have a call later with @Czaki!

**Comment by Carreau** [comment]
No problem, I ended up just editing the file by hand and setting to 0.13.0, I know the both will update automatically later if needs be. I'm mostly trying to get CI to run to see if there is anything missing :-)

**Comment by brisvag** [comment]
ok, contraints updated via the bot! It includes a bunch of other stuff but that's normal, simply new versions coming up.

**Review by Carreau — APPROVED** [review]

**Pull request merged**
