### PR TITLE
[WIP] PropertyView (evented properties #2)

### PR DESCRIPTION
**Pull request by brisvag**
# Description
This is an alternative implementation of #4417, fruit of a fruitful chat with @tlambert03 and some more playing around. Properties are cool, y'all!

I call it an alternative implementation, but while it's trying to solve the same problem, the approach is completely different. Instead of hijacking the `EventedModel.__getattribute__` and using self-referring events to update it, in this PR I subclassed `property` to create a `property_view` (no events involved).

This property returns a `PropertyView` object, which should behave exactly like the original object, except that it even when it's recursively indexed, it will upstream any of the changes to the `property_view.setter` and thus update the original object. In practice, it feels the same as #4417, but without events and duplications.

cc @jni and @sofroniewn , I know you were interested!

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
_very_ cool stuff @brisvag.

Couple thoughts as I dig into it.
1. it seems like `PropertyView` really is tuned for sequences.  (i.e. cases where `viewed` has `__getitem__` and `__iter__`).  I wonder if that should somehow be made a little more explicit?  That is, maybe a `PropertyView` should only ever be returned by `property_view.__get__` or `PropertyView.__getitem__` if the return value is actually an iterable, otherwise just return the item itself (since no more nesting is even possible)?
2. I feel like the parameters passed to `__init__` itself holds a bit too much "logic" so to speak. While I was making [docstrings](https://github.com/brisvag/napari/pull/6) to try to follow the flow here, I noted that [3 of the 4 parameters](https://github.com/brisvag/napari/pull/6/files#diff-7654feb93d842c748c427edcac178336587316596e853079a0c358a45ed78958R14-R24) required an "if this then that" when describing what they might mea; specifically, "if this `PropertyView` was the result of a `__getitem__` call.  (similarly, there's a lot of `if self._prop is None` that has to check this stuff later).  That has a code smell to me.  I'm not immediately sure what the solution is, but i kinda wonder if this isn't related to the first point (i.e. making PropertyViews for non-iterables doesn't really make sense anyway?)

**Comment by brisvag** [comment]
I was planning to expand it so that getattr also returns a view. Not sure if it's doable, but in principle it should. And then you can do the same infinite nesting with attributes.

I agree that the init parameters are clunky... I'll think about it more :)

**Comment by brisvag** [comment]
so... The monster keeps growing :)

>     1. it seems like `PropertyView` really is tuned for sequences.  (i.e. cases where `viewed` has `__getitem__` and `__iter__`).  I wonder if that should somehow be made a little more explicit?  That is, maybe a `PropertyView` should only ever be returned by `property_view.__get__` or `PropertyView.__getitem__` if the return value is actually an iterable, otherwise just return the item itself (since no more nesting is even possible)?

Two things solve this:
- I'm now using `wrapt.ObjectProxy`, which means all the iter/add/eq stuff works as if the proxy wasn't there.
- both `getattribute` and `getitem` (and their `set` counterparts) use the same logic, which means any kind of nesting should be accounted for.

>     2. I feel like the parameters passed to `__init__` itself holds a bit too much "logic" so to speak. While I was making [docstrings](https://github.com/brisvag/napari/pull/6) to try to follow the flow here, I noted that [3 of the 4 parameters](https://github.com/brisvag/napari/pull/6/files#diff-7654feb93d842c748c427edcac178336587316596e853079a0c358a45ed78958R14-R24) required an "if this then that" when describing what they might mea; specifically, "if this `PropertyView` was the result of a `__getitem__` call.  (similarly, there's a lot of `if self._prop is None` that has to check this stuff later).  That has a code smell to me.  I'm not immediately sure what the solution is, but i kinda wonder if this isn't related to the first point (i.e. making PropertyViews for non-iterables doesn't really make sense anyway?)

I think this makes more sense now. The first ancestor holds a reference to the the property (since it needs to call the setter with its *full* value), and everything else holds a reference to the parent view, as well as the index/attribute needed to access itself.

I also added automatic hookup of nested evented objects to this pr, so I could showcase in the example what this is meant for: the ability to nest any object as deep as wanted and use their property setters, while always updating the top object and emitting the appropriate event.

Is it a monster? Kinda. Was it fun to come up with? :+1: Worth it? :100: 😆

**Comment by jni** [comment]
Crazy stuff! :joy: I *think* I like it??? I'd love for this PR to hook up *one* thing to the machinery to see it in action, e.g. `dims.point`?

**Comment by sofroniewn** [comment]
> I'd love for this PR to hook up one thing to the machinery to see it in action, e.g. dims.point?

Yeah this is super interesting to me too - I think it would be nice to see something like this as well to fully grasp whats going on here. I think that my concerns about dynamically creating evented objects are no longer there now which is great, but I just want to make sure!!

**Comment by brisvag** [comment]
Closing with all the related PRs since this is likely not worth pursuing before pydantic v2.

**Pull request closed without merging**
