### PR TITLE
Un-set unified title and tool bar on mac (Qt property)

### LINKED ISSUE #5529: Qt6: visual error: non-theme border around LayerControlsContainer and Console (maybe macOS only?)
## 🐛 Bug

Using Qt6 backends there are borders around the LayerControls dock widget and the Console dock widget (when open). If the napari theme matches the OS theme, the border is very subtle, so you may need to toggle theme to see. 
Dark theme (OS light theme)
image
Light theme (OS light theme)
image

It's the padding pixels that use color from underneath the widgets. If one undocks the widgets, the issue disappears. Also during undocking, once removed from the dock, one can briefly see that the area beneath the widget is the same color as the problem border, before the theme color kicks in. 

This was originally reported in the Qt tracking issue:
https://github.com/napari/napari/issues/3880

## To Reproduce

1. in a fresh env, install pyqt6 or pyside6
2. `pip install napari` (no [all] to use the Qt6 backend)
3. open the viewer and open the console

## Expected behavior

The border should remain consistent with the napari theme.

## Environment

PySide6, arm64 macOS 13.2, napari `main` (post Qt6 fix PRs)

## Additional context

This may be macOS specific.

### PR DESCRIPTION
**Pull request by aganders3**
# Description
This one is a bit weird, but here goes. This fixes the background "behind" the QtViewerDockWidgets being the wrong color (something from the system theme). I think this was actually the root cause of the issues seen in #5529 and addressed separately in #5526. I could go either way then on whether to include the changes in #5526 as well.

Anyway this removes a property that was set to fix an intermittent problem quite a while ago. It seems the behavior of this property actually changed in Qt5, and it is supposedly not compatible with windows that contain Open GL content.

### Before this change
Screenshot 2023-02-06 at 12 12 18 PM

### After this change
Screenshot 2023-02-06 at 12 24 58 PM

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# References
https://github.com/napari/napari/pull/245
https://github.com/napari/napari/issues/239
https://github.com/napari/napari/issues/5529
#5526

# How has this been tested?
- [x] I checked my changes work with both PySide and PyQt backends on Qt6, and PyQt on Qt5

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
For me this works perfectly and it's quite simple.
I wonder if this will mess something up on some sort of minimum requirements install?
But from reading the old threads, it's clear that the original issue wasn't easy to trigger, because none of the other mac users at the time had the issue.

One thing that makes this better is that the background when undocking is set by the napari theme and not OS theme. Now, I prefer to have napari and OS synced, but if you don't and you try to undock a widget it will look horrible. The other PR does not fix that on my end with pyside6.

Maybe @dalthviz has some insight, as original qss 🧙‍♂️ ?

**Comment by aganders3** [comment]
> One thing that makes this better is that the background when undocking is set by the napari theme and not OS theme.

Yeah this is what I set out to fix with this one.

I can go either way about including the changes from the other PR in addition. They still make sense to me, but I think with this change they're not strictly necessary. I'll happily defer to the resident Qt experts!

**Review by Czaki — APPROVED** [review]

**Comment by brisvag** [comment]
> I wonder if this will mess something up on some sort of minimum requirements install?

We do have minreq in our tox matrix, so we should be good on that front :)

**Comment by dalthviz** [comment]
Maybe for an older Qt5 version like 5.6 or 5.9 or older MacOS versions was necessary to set that property for some reason? I think this solution makes sense :+1: (it's always nice to find a one liner solution for multiple problems and even better if it is done by removing code :) )

**Comment by psobolewskiPhD** [comment]
Man these tests failing pyqt5/python 3.8 are a bummer :(
At least the dims ones would pass if rerun!
When do we drop python 3.8? 👀

**Review by psobolewskiPhD — APPROVED** [review]

**Comment by Czaki** [comment]
> Man these tests failing pyqt5/python 3.8 are a bummer :(

this is not a problem with python 3.8 I observed it also on other python version.

**Comment by psobolewskiPhD** [comment]
Based on the above approvals and the comment from @dalthviz I think this is ready to merge.
Starting the clock—I use pyside6 in my dev env, so this is a QoL issue for me!

**Review by dalthviz — APPROVED** [review]

**Pull request merged**
