### PR TITLE
Fix teardown of menus to prevent widget test leaks

### LINKED ISSUE #3431: Exceptions on menu close
## 🐛 Bug

`closeEvent` of `NapariMenu` is called on every hide of the menu, not when destroying viewer.

```
~/Projekty/napari/napari/_qt/menus/_util.py in closeEvent(self=<napari._qt.menus.window_menu.WindowMenu object>, event=<PyQt5.QtGui.QCloseEvent object>)
    151             ax.setData(None)
    152 
--> 153         self._INSTANCES.remove(self)
        self._INSTANCES.remove = <built-in method remove of list object at 0x7f39156d2980>
        self = <napari._qt.menus.window_menu.WindowMenu object at 0x7f3829a831f0>
    154         super().closeEvent(event)

ValueError: list.remove(x): x not in list
```

## To Reproduce

1. open viewer 
2. open one menu two times
3. see exception

## Expected behavior

Opening menu multiple times should not produce exceptions

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:
napari: 0.4.12.dev40+g4c554cec2
Platform: Linux-5.11.0-36-generic-x86_64-with-glibc2.2.5
System: Ubuntu 21.04
Python: 3.8.3 (default, Sep 3 2021, 01:19:46) [GCC 10.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.19.5
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.8.1

OpenGL:
- GL version: 4.6.0 NVIDIA 470.63.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.4
- napari-allencell-segmenter: 1.1.2
- napari_nucleaizer: 0.1.8
- ome-types: 0.2.9
- platelet-unet-watershed: 0.0.1
- scikit-image: 0.4.12.dev40+g4c554cec2
- svg: 0.1.5
## Additional context

Bug introduced in  #3363 @goanpeca

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Fixes #3431

# How has this been tested?

- [x] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by goanpeca** [comment]
@Czaki could you test this PR?

Thanks!

**Comment by Czaki** [comment]
> @Czaki could you test this PR?
> 
> Thanks!

Works for me.

**Comment by goanpeca** [comment]
There seem to be some segfaults on windows, but I do not think they are related to the PR as I have seem them on other PRs, but need to check.

**Comment by Czaki** [comment]
you may check if adding `qtbot.wait(50)` like in #3427 will help.

**Comment by goanpeca** [comment]
Thanks @Czaki, trying now

**Comment by Czaki** [comment]
from my observation, In the most common cases, failure is caused by some test that was already marked as completed.

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Pull request merged**
