### PR TITLE
setup css basics

### PR DESCRIPTION
**Pull request by kne42**
# Description
Set up CSS basics by creating a central point to change stylesheet settings. See `resources/stylesheet.qss`.

Additionally, set up `QResources` in `resources/res.qrc`. This file must be compiled every time a change is made with `pyrrc5 -o qt.py res.qrc`. File paths can then be made with the reference point `:/path/to/file` (`:/` is replaced by the location of `res.qrc`). See https://doc.qt.io/qt-5/resources.html for more information.

Unintuitively, you must import this module (which is already imported into `resources`) in EVERY file you want to use these shortcuts in for it to work.

# QSS tips

QSS is generally similar to CSS, with the exception of how classes are handled. Qt classes effectively behave as new element types (i.e. `my-new-element { ...; }`) while there is no direct equivalent to a CSS class (`.my-class { ...; }`).

However, this can be achieved with properties:
```css
*[my-class="true"] {
  ...;
}
```

```python
def __init__(self):
    ...
    self.setProperty('my-class', True)
    self.style().unpolish(self)
    self.style().polish(self)
```

Properties are also useful when communicating custom states to the CSS:
```css
*[my-class="true"] {
  ...;
}

*[my-class="true"][action-state="disabled"] {
  ...;
}
```

# References
- see #13
- https://doc.qt.io/qt-5/stylesheet-syntax.html

### CODE REVIEW

**Comment by sofroniewn** [comment]
As discussed in person, having the stylesheets get set in the `Viewer` will probably be better, as means they will work in the notebooks or if someone wants to embed the viewer in something else they can use those styles or overwrite them

**Comment by kne42** [comment]
This is ready for re-review @sofroniewn 

What are people's thoughts on potentially parsing/creating macros to go from CSS to QSS?

**Comment by sofroniewn** [comment]
Hi @kne42 this is looking great! It seems like it’s a bit of a pain to recompile the `res.qrc` file every time, but it's fine, we should just make sure we add these instructions to our docs for people who want to contribute new resources.

For the `_markers_layer/view/controls.py` the old stylesheets are still being used. Can you delete all the `self.setStyleSheet(styleSheet)` lines and delete the `button_style` function as these are no longer needed. Once this is done I think it is good to merge. Then will be ready for our design team to get to work ;-) @freeman-lab 

As to generating QSS from CSS I'm a little concerned that we might be taking on a lot of engineering effort for little gain and that there could be real complexity in some corner cases which are not so relevant to us. I'd say if you start restyling with the QSS but get to the point where you feel blocked and want a CSS converter then we can investigate more, but I wouldn't take this on until then. I tried to do some googleing to see if one was already out there but couldn't find one.

**Review by sofroniewn — APPROVED** [review]
Looks good to me!

**Pull request merged**
