### PR TITLE
Fix QtPoll to poll when camera moves

### PR DESCRIPTION
**Pull request by pwinston**
# Description

I was thinking of creating a webmon/tile-viewer video but I saw performance was very laggy. This fixes that problem. The problem was a regression (during my own work in December). It originally did work.

* Fixes QtPoll so it polls when the camera is zooming or panning.
* Dragging the mouse starves out timer messages, so it was preventing polling.
* With the fix we poll if camera moves OR the timer goes off, so always.
* We also use the `IntervalTimer` to prevent duplicate polls.

## Type of change
- [x] Bug-fix in experimental code

# How has this been tested?
- [x] Manual testing with webmon and tile viewer

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by tlambert03** [comment]
> The problem was a regression, it used to work a while back.

once you're ready to take this out of draft, can you add some tests to make sure we don't regress again in the future?

**Comment by pwinston** [comment]
It regressed during my work at some point. Not something someone else broke afterwards.

But yes, it would be really nice to have some async/octree tests to guard against something breaking those things. Since no one might notice for a long time. I don't think it will be easy, but I will try to think of something. But it might be bigger/different than this PR.

**Comment by sofroniewn** [comment]
> I don't think it will be easy, but I will try to think of something. But it might be bigger/different than this PR.

Thanks, I think some form of test, even if it is small, is important.

**Comment by pwinston** [comment]
I marked this ready for review. I have a video I'm working on (and README) that will walk people through how to modify Napari to add some new shared memory messages and then explain how to modify webmon to add a new page.

Adding a async/octree test is a great idea but it's separate from this change, and will require significant effort.

Also I saw the perfmon test pass was folded in to the main pass. Is the intention that async/octree also is done in the main pass? That will require more work as well.

Also I've run with this change a bunch of times to test it.

**Review by sofroniewn — APPROVED** [review]

**Pull request merged**
