### PR TITLE
Layer abstraction

### PR DESCRIPTION
**Pull request by kne42**
Introduces a standard for layers, a way to register them as convenience methods on `Viewer`s, and a better programmatic management system.

- layers must inherit from `gui.layers.Layer` and call `super().__init__(visual_node)` with their central/controlling visual node
- layers must override methods `_get_shape`, `_refresh`, and property `data`
- layers may override methods `_set_view_slice`, `_after_set_viewer`,  and property `_qt`
- `add_*` methods can be automatically added to `Viewer`s by using the function/decorator `gui.layers.add_to_viewer`
- `gui.layers.LayerList` provides a list-like interface to add and remove layers, as well as providing the `swap` and `reorder` methods to programmatically change the rendering order of layers

Note: ordering system used in this PR introduces an opacity-related bug: see vispy/vispy#1541

### CODE REVIEW

**Comment by royerloic** [comment]
What if a layer does not define the notion of 'shape' -- that's very much an image-centric concept.
I would suggest that in that case, you simply ignore that layer for the purpose of computing the
max shape parameters... In general, pay attention to the generality of a layer's base properties,
an devise elegant strategies that address this. Luckily, many properties -- such as opacity -- exist for all layers...

**Comment by kne42** [comment]
@royerloic Actually I would like to require some sort of required API that helps us determine the shape of the layer (perhaps even by slice but this may be costly in terms of memory) so that we can show a visual selection rectangle on the gui to allow users to move, scale, and rotate the visual.

**Comment by royerloic** [comment]
Ok, makes sense. Maybe my question really is: what units do we have for 'shape' if the units is pixels of images that would work, assuming that we use the same units for the coordinates of other layers...
So, in fact if we think about a 'points' layer, you could set the shape to be (1000,1000) or (123,456), that would then help understand how to position the pints within a bounding box... But that also means that we need to know more that just with and height... We actually need (x, y, width, height) to be able to really make sense of the point coordinates -- note that (x,y) is a corner of the box.... Of course from that bounding box, the shape is trivially inferred. In most cases (x,y) will be (0,0), but it does not have to be (even in stacked mode! we want to keep the coordinates of the points relative to the box!).  I am actually realising all this while I write.

Important: just as for image layers, other layers can have different shapes, but can be stacked together nevertheless, using the bounding box info...

**Comment by kne42** [comment]
Ah, perhaps we should instead just require them to provide their `ndim`s and some function that returns `(x, y, width, height)` given a set of indices (like in `_set_view_slice`)?

**Comment by royerloic** [comment]
Asking for the shape works, and should not depend on slicing.
You would return the shape as (width, height) and the coordinates
of the points used for drawing would be (x-x0, y-y0) assuming
the bounding box is (x0, y0, width, height) …

Slicing would only display objects that are entirely or intersect with
the viewing plane — unless max projection mode is used in which 
case all objects are displayed as projection… 

Yeah, just realising that slicing and objects are an interesting topic.
Nothing really hard actually, but very interesting… We can start
simple and see how it goes…

**Comment by jni** [comment]
why can't we infer the shape to be the min and max of the data? This should be super fast. If we want to allow offsets, we can add `origin=(0,) * ndim` as the default, but settable by new layers.

**Comment by royerloic** [comment]
Imagine you ‘mark’ two places in an image,
you can’t use the min and max values for x and y 
to define the bounding box, because that would
effectively move these marks —always— on the
borders of the image. You need to know the 
boundaries independently of the actual point 
locations…

**Comment by jni** [comment]
Oh you mean because you are doing all this crazy resizing/moving around inside the canvas that I told you was a bad idea? =P

**Comment by royerloic** [comment]
actually it is unrelated.
the problem exists even with just a single layer.

**Comment by jni** [comment]
Ok I'm gonna wait till our meeting to discuss since I feel some drawing is required. =)

**Comment by royerloic** [comment]
The key but subtle difference between an image and a list of points,
is that an image has pixels that completely fill its ‘frame', 
whereas a list of points does not necessarily have
points on its ‘frame’ border. For example, you might not always
have a point with x=0 or y=0… So we can’t use min and max
to define the ‘frame’ for list of points, lines etc…, 
it must be explicitly provided.
But that’s perfectly fine, that does not cause any trouble,
In fact it avoids problems down the line… 
most of the time the frame will correspond to the pixel coordinate 
range.  

And then this leads to avoiding using a fix coordinate frame 
for coordinates for the list of points, but instead we do everything
relative to the frame. Anyway, gets a bit technical but it is 
important to get this right from the start. In practice that means
that you could use any range of values [0,1] or [0,width] and it
all works nicely because we use a relative scheme. Makes it 
also much easier to have different units like pixels or microns
or whatever…

**Comment by sofroniewn** [comment]
I'm looking through the PR right now and ran into a problem not sure what I'm missing. When I run the following code the opacity and colormap changes work fine, but I get an error message when trying to change the clims. It's nice that when I change the opacity etc. the gui window automatically updates

```
window = gui.imshow(patch)
layer = window.layers[0]
layer.opacity = .5
layer.colormap = 'viridis'
layer.clim = (0,100)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-e8219f68bee2> in <module>()
      3 layer.opacity = .5
      4 layer.colormap = 'viridis'
----> 5 layer.clim = (0,100)

TypeError: clim() takes 1 positional argument but 2 were given
```

**Comment by kne42** [comment]
Thanks for poking around, you found a bug! There’s a line below
`@clim.setter` that should be `def clim(self, clim):`. I’ll push a fix when
I get back to my laptop which won’t be for a while so if you want you can
go ahead and change it in your branch.

**Comment by sofroniewn** [comment]
Thanks! No rush. I also think I've encountered the opacity bug you mentioned at the top of the thread, and saw your chats in vispy. Looks like it is being handled there

**Comment by sofroniewn** [comment]
Is there a remove layer / delete layer function? Would be nice.

Also might be nice to be able to create an empty window, could be with something like `window = gui.imshow()`

Another thing that might be nice is if you pass a list of images `window = gui.imshow([A, B])` then you get two layers with A and B inside them respectively

Also is it worth including the concept we talked about on thursday where if we call `window=gui.imshow(A, layers=[2,3])` where `dim(A)=5` say, then we'd get a collection of 3D images all as different layers. I guess an argument against this is that a simple reshape and list comprehension would generate a list of arrays that could then be passed to imshow if the behaviour in the above point is supported. A pro though is this is something people might want to do often for color-channel dimensions and it could be a convenience to do it inside imshow. I can really see it both ways.

Also unclear to me why `window.add_image(image, meta)` and `gui.imshow(image, meta=None, multichannel=None, **kwargs)` take different inputs, it would seem to me that they should take the same, and that we might as well have `window.add_image(image, meta=None, multichannel=None, **kwargs)`

**Comment by kne42** [comment]
> Is there a remove layer / delete layer function? Would be nice.

Yes, right now this is implemented as `Viewer.layers.remove(layer)`.

> Also might be nice to create an empty window, could be with something like `window = gui.imshow()`

Good point but this isn’t the PR for that. It’ll come later in a specific PR addressing the API.

**Comment by sofroniewn** [comment]
> Yes, right now this is implemented as `Viewer.layers.remove(layer)`.

ok nice, i get it now, it's just like any list, i can use `remove` or maybe easier `pop` with a coordinate. thanks it works for me

**Review by royerloic — APPROVED** [review]
Great work Kira!

**Pull request merged**
