### PR TITLE
Update allowed selected_label range when data dtype changes

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues
extracted from  #6471

# Description

When the data dtype changes for a labels layer, the allowed values for the selector in QtLabelsControls should be updated accordingly. This PR connects the relevant events and adds a test.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Hmm. Fresh env but with pyqt6 python 3.11
When I try to start napari with this branch I get:
```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/__main__.py", line 573, in main
    _run()
  File "/Users/piotrsobolewski/Dev/napari/napari/__main__.py", line 343, in _run
    viewer._window._qt_viewer._qt_open(
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/qt_viewer.py", line 926, in _qt_open
    self.viewer.open(
  File "/Users/piotrsobolewski/Dev/napari/napari/components/viewer_model.py", line 1203, in open
    layers = self._open_or_raise_error(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/components/viewer_model.py", line 1266, in _open_or_raise_error
    _path = paths[0]
            ~~~~~^^^
IndexError: list index out of range
```
If I checkout main it's fine.

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
@psobolewskiPhD given that everything is green, I suspect there is something wrong with your installation, rather than the PR...

Why is it even trying to open anything??? 🤔

**Comment by jni** [comment]
This works for me. It's a little wonky in that e.g. if I:

- run `examples/add_labels.py`
- set the selected label to 700
- then convert the datatype to int8

The selected label doesn't change. Only when I click - does it switch down to 126.

Incidentally, I am *not allowed* to switch the dtype from signed to unsigned, and it just fails silently to convert if I click on uint8 instead of int8. I'll raise an issue about that.

**Comment by Czaki** [comment]
> given that everything is green, I suspect there is something wrong with your installation, rather than the PR...

Peter stactrace contains untested code. 



> Why is it even trying to open anything??? 🤔

Because it always try to do this... 

@psobolewskiPhD spot bug introduced by #6467

He just does not have the latest main pulled locally.

**Comment by psobolewskiPhD** [comment]
eep, yeah sorry about that, I pulled down fresh main and get the same error on main--which there is already a PR to fix. Code looks OK but I like to be able to play with GUI elements.

**Comment by Czaki** [comment]
> Incidentally, I am _not allowed_ to switch the dtype from signed to unsigned, and it just fails silently to convert if I click on uint8 instead of int8. I'll raise an issue about that.

Could you describe it in more detail? It converts successfully in my case (but the menu is not refreshed).

**Comment by jni** [comment]
> Could you describe it in more detail? It converts successfully in my case (but the menu is not refreshed).

Ah, checking the menu is all I was doing. But it's surprising that the menu refreshes for the same-kind (signed/unsigned) switch, but not signed->unsigned, right? 🤔

**Pull request merged**
