### PR TITLE
add helpful error on multichannel IndexError

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
@jacksonmaxfield reported a cryptic error in  https://forum.image.sc/t/what-would-cause-a-stopiteration-on-napari/39388
The `StopIteration` error is caused when `add_image` is used with a `channel_axis` that has a length greater than the length of the iterator for one of the keyword arguments used.  This PR catches that error and provides a more interpretable error message:
```pytb
IndexError: Error adding multichannel image with data shape (1, 4, 2, 614, 614).
Requested channel_axis (3) had length 614, but the 'name' argument only provided 2 values.
```

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# How has this been tested?

- [x] added a test to catch the case when the length of the iterator doesn't match n_channels

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jni — APPROVED** [review]
@tlambert03 this looks great to me!

Do you have any idea why there's a Linux 3.6 failure?

**Comment by tlambert03** [comment]
That’s the `test_nbscreenshot` segfault I was mentioning on Zulip. It’s been happening periodically and I don’t know why. I tried to fix it in a couple PRs a while back but it still crops up from time to time

**Comment by tlambert03** [comment]
Reran and it went away

**Review by sofroniewn — APPROVED** [review]
LGTM! Thanks!!

**Pull request merged**
