### PR TITLE
Fix pan zoom scaling

### LINKED ISSUE #1579: pan/zoom broken for multiscale images with scale= parameter
## 🐛 Bug

When viewing a multiscale image, setting the scale on the viewed dimensions to anything other than 1, 1 causes the pan/zoom to break.

```python
import napari
import dask.array as da

with napari.gui_qt():
    v = napari.view_image(
        [da.random.random((10000, 10000)), da.random.random((5000, 5000))],
        scale=[10, 10],
    )
```

See the screengrab video. The jumps are just me scrolling.

https://imgur.com/a/UpzyOC6

When you click and drag, the coordinates displayed in the status bar change while dragging. 🤷

### PR DESCRIPTION
**Pull request by liu-ziyang**
# Description
Address pan/zoom jump

## Type of change
- Bug-fix (non-breaking change which fixes an issue)

# References
closes #1579 
replace #1654

# How has this been tested?

- manually verified that the behavior is fixed
- all tests pass with my change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Amazing @ziyangczi That's great. Adding a test maybe tricky. You could try one based on screenshots like are in here which take screenshots and do zooms https://github.com/napari/napari/blob/master/napari/_vispy/_tests/test_vispy_multiscale.py

I'll give this a test later today. Maybe @jni can test too as he originally raised #1579

Also looks like the test fails are dask related which I've made an issue for in #1656, if you had any ideas around that it would they would be much appreciated too!!

**Comment by liu-ziyang** [comment]
> Amazing @ziyangczi That's great. Adding a test maybe tricky. You could try one based on screenshots like are in here which take screenshots and do zooms https://github.com/napari/napari/blob/master/napari/_vispy/_tests/test_vispy_multiscale.py
> 
> I'll give this a test later today. Maybe @jni can test too as he originally raised #1579
> 
> Also looks like the test fails are dask related which I've made an issue for in #1656, if you had any ideas around that it would they would be much appreciated too!!

I may need some help understanding the rationale behind the coordinate transform, as well as possible impact on other pieces of the code to justify this code change, I still don't understand exactly what this does, other than it fixed the reported issue 😃

**Comment by DragaDoncila** [comment]
Just tested this locally and it works great! Thanks @ziyangczi 🙌

**Comment by liu-ziyang** [comment]
@sofroniewn yeah adding test for this one is tricky. maybe we can skip for this one liner.

But I do have a question though, if we commit this code change, how is the data translated to the world coordinate without the rescaling? do we need to add the scaling somewhere else to avoid another bug?

**Comment by sofroniewn** [comment]
> But I do have a question though, if we commit this code change, how is the data translated to the world coordinate without the rescaling? do we need to add the scaling somewhere else to avoid another bug?

The `tile2data` and `data2world` transforms now get combined here https://github.com/napari/napari/blob/master/napari/_vispy/vispy_base_layer.py#L162-L164, and I think what's happening is that scaling is getting applied twice, whereas before we needed to apply it in this part of the code.

This code only gets used in the multiscale case, so I think it is fine to merge if it has been checked there.

I did look and it seems like using translate parameter also causes a bug that is neither fixed nor made worse by this PR, see

```python
with napari.gui_qt():
    v = napari.view_image(
        [da.random.random((10000, 10000)), da.random.random((5000, 5000))],
        scale=[10, 10], translate=[1000, 100], 
    )
```

maybe @ziyangczi we can look into trying to fix that too before merging this one? i'll have a look in the code now and see if anything looks off. note in this case black starts appearing at the top of the screen as you zoom in

**Comment by sofroniewn** [comment]
Looking at it more I'm now worried that with scale/ translate parameters present the `corner_pixels` calculation happening here might not be accurate https://github.com/napari/napari/blob/master/napari/_vispy/vispy_base_layer.py#L202 (i.e. it assumed no scale/ translates). If that is wrong then these other calculations will be off too.

Ultimately all this code will go away with the finishing touches on our world coordinates and the octree work, but still would be good to fix now if we can!!

**Comment by liu-ziyang** [comment]
> > But I do have a question though, if we commit this code change, how is the data translated to the world coordinate without the rescaling? do we need to add the scaling somewhere else to avoid another bug?
> 
> The `tile2data` and `data2world` transforms now get combined here https://github.com/napari/napari/blob/master/napari/_vispy/vispy_base_layer.py#L162-L164, and I think what's happening is that scaling is getting applied twice, whereas before we needed to apply it in this part of the code.
> 
> This code only gets used in the multiscale case, so I think it is fine to merge if it has been checked there.
> 
> I did look and it seems like using translate parameter also causes a bug that is neither fixed nor made worse by this PR, see
> 
> ```python
> with napari.gui_qt():
>     v = napari.view_image(
>         [da.random.random((10000, 10000)), da.random.random((5000, 5000))],
>         scale=[10, 10], translate=[1000, 100], 
>     )
> ```
> 
> maybe @ziyangczi we can look into trying to fix that too before merging this one? i'll have a look in the code now and see if anything looks off. note in this case black starts appearing at the top of the screen as you zoom in

I think I identified the translate issue, it is a different bug as you found on the vispy base layer where it shouldn't include the offset in transformation. However there is a phantom update on the transform node value and caused the scaling to jump on micro scale, I am chasing it down now

**Comment by liu-ziyang** [comment]
I think I figured the phantom update out, it is actually related to async loading and how we compute translation:
we use the transformation to figure out our canvas corner: 
https://github.com/napari/napari/blob/master/napari/_vispy/vispy_base_layer.py#L162-L164, and we use the canvas corner to figure out the translation: https://github.com/napari/napari/blob/master/napari/layers/image/image.py#L557-L561.
However because there is a lag between when events are fired off and processed, you will see a phantom update of the coordinates because one part will be behind while visual is updating...
Given our current setup I don't think we can easily fix this, one workaround that I can think of is to always loads slightly more data in the slice than we have to, this way we avoid having a visual flash in users' eyes even though the corner coords and slice would still bounce around..

**Comment by sofroniewn** [comment]
> I think I figured the phantom update out, it is actually related to async loading and how we compute translation:
we use the transformation to figure out our canvas corner:

Hmm, ok interesting. Can you role back to an old commit before any of the async stuff merged, maybe the 0.3.6 release tag and check if the problem is the same then. I wonder if the problem is strictly with the "async" PR code vs just how/ when we are doing that update, which maybe asynchronous in a slightly looser sense

**Comment by sofroniewn** [comment]
I wonder if the `offset` was needed to account for the corner coords bouncing around.

I think that we might want to merge with the offset left in and the `scale` fixed, that is at least real progress and then after #1660 merges we can redo the corner calculation to avoid this code path entirely. This will be much easier as we'll finally have a real world coordinate system that is the same for every layer

**Comment by liu-ziyang** [comment]
> I wonder if the `offset` was needed to account for the corner coords bouncing around.
> 
> I think that we might want to merge with the offset left in and the `scale` fixed, that is at least real progress and then after #1660 merges we can redo the corner calculation to avoid this code path entirely. This will be much easier as we'll finally have a real world coordinate system that is the same for every layer

that sounds fine to me, I am pretty sure we need to remove the offset to fix the translate bug, but it technically is a different bug. so we can file and address later

**Review by sofroniewn — APPROVED** [review]
Ok, this looks good now - at least we have fixed the scale issue. We'll address the translate issue in followup PRs after #1660 has merged cc @jni

**Pull request merged**
