### PR TITLE
Fix deleting points data in viewer

### LINKED ISSUE #2382: Deleting points data is broken with an index error
## 🐛 Bug

Using git bisect I tracked the problem to #2204 (sorry @kevinyamauchi 😬), which broke resetting of a Points layer data, which now raises an IndexError (see below).

## To Reproduce

```python
import numpy as np
import napari

viewer = napari.Viewer()
points = np.random.random((4, 2)) * 4

pts_layer = viewer.add_points(points)
pts_layer.data = np.zeros([0, 2])
```

raises:

```pytb
Traceback (most recent call last):
  File "test-points-delete.py", line 8, in <module>
    pts_layer.data = np.zeros([0, 2])
  File "/Users/jni/projects/napari/napari/layers/points/points.py", line 422, in data
    self._edge._remove(
  File "/Users/jni/projects/napari/napari/layers/utils/color_manager.py", line 330, in _remove
    self.colors = np.delete(self.colors, selected_indices, axis=0)
  File "/Users/jni/projects/napari/napari/utils/events/evented_model.py", line 154, in __setattr__
    getattr(self.events, name)(value=after)  # emit event
  File "/Users/jni/projects/napari/napari/utils/events/event.py", line 550, in __call__
    self._invoke_callback(cb, event)
  File "/Users/jni/projects/napari/napari/utils/events/event.py", line 567, in _invoke_callback
    _handle_exception(
  File "/Users/jni/projects/napari/napari/utils/events/event.py", line 565, in _invoke_callback
    cb(event)
  File "/Users/jni/projects/napari/napari/_vispy/vispy_points_layer.py", line 41, in _on_data_change
    edge_color = self.layer._view_edge_color
  File "/Users/jni/projects/napari/napari/layers/points/points.py", line 1187, in _view_edge_color
    return self.edge_color[self._indices_view]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Interestingly, the below doesn't have any issues:

```python
import numpy as np
import napari

points = np.random.random((4, 2)) * 4

pts_layer = napari.layers.Points(points)
pts_layer.data = np.zeros([0, 2])
```

Which suggests that it's the event callback system that's broken, *not* the points layer itself. That would explain why this got past testing.

## Expected behavior

The color elements should be removed together with the data.

## Environment

```
napari: 0.4.6.dev45+geaa54747.d20210303
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.2 (default, Mar 26 2020, 10:43:30)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.2
SciPy: 1.5.1
Dask: 2021.01.1
VisPy: 0.6.5.dev320+gc275797b

OpenGL:
  - GL version:  2.1 ATI-3.10.19
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2048x1152, scale 2.0
  - screen 2: resolution 1536x960, scale 2.0

Plugins:
  - affinder: 0.1.dev16+g189efd8
  - animation: 0.1.dev78+g5716ec8
  - btrack-reader: 0.1.0
  - console: 0.0.3
  - napari-sentinel-zip: 0.2.2
  - ome_zarr: 0.0.18.dev0
  - s3zarr: 0.0.2
  - svg: 0.1.4
  - tracks: 0.0.2
```

### PR DESCRIPTION
**Pull request by jni**
# Description

Closes #2382 

Calling `_set_view_slice` in the data setter resets the `_indices_view` array, averting disaster. This PR also adds a test that fails before the PR.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Great job catching this and with the quick fix! I'm not sure about making the extra call to `set_view_slice`, it's not really something we want to do as `set_view_slice` will get called anyway at the end of the function (it's a bit buried but will happen in the refresh call inside the update_dims call). So we're really calling it twice now when we only want to call it once.

The alternative is to get a bit better with our blockers to prevent vispy drawing during the intermediate updates. I've made an alternative PR here https://github.com/jni/napari/pull/7 to you PR curious what you @jni and @kevinyamauchi think.

**Comment by jni** [comment]
@sofroniewn I've merged your PR. I'm not sure what the right fix is — I agree that calling set_view_slice was problematic but I feel like both solutions paper over the fact that our slicing doesn't generalise well to arbitrary attributes. *but*, we are not going to fix that issue in this PR! LOL So I suggest that getting *either* fix in is fine, and yours is probably the better version. :+1: So :+1: to merge this solution from me!

**Review by liu-ziyang — APPROVED** [review]
It looks good to me, looks like the scope for this PR is only moving the blocker out and instead of blocking on specific things it block all events during update

**Comment by sofroniewn** [comment]
Ok, yeah sounds good! Happy to merge now, and then we can improve more later

**Comment by kevinyamauchi** [comment]
Sorry, just getting caught up on this! Thanks for the fixes, @jni and @sofroniewn . I agree that we need to improve our slicing of arbitrary attributes (e.g., text and properties).

**Comment by sofroniewn** [comment]
>  I agree that we need to improve our slicing of arbitrary attributes (e.g., text and properties).

Yes definitely. We might want to revisit #1908 soon, which would change how we do points slicing, something I was thinking of in the context of https://github.com/napari/napari/issues/1775#issuecomment-716719156

**Pull request merged**
