### PR TITLE
Automatically add PR type label with GHA based on description

### PR DESCRIPTION
**Pull request by Czaki**
# Description

I improve action that examines the PR description to add. Labels based on PR description. 

This modifies existing actions instead of creating separate ones to keep code in one place and fo not have code duplication. Also, to reduce setup time. 

## Type of change

- [x] Maintenance (changes required to run napari, tests, & CI smoothly)

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
LOL it is very ironic that the label checker is failing here 🤣 

@Czaki re discussion in #6092, I suggest that the categories should not be a checklist but just a bullet list, and people only need to delete elements, rather than fill in a `- [ ]`, which often results in the malformed `- [x ]` (extra trailing space). I do think that the changes in #6092 are in a good direction and we can rejigger this one to use a simpler standard. e.g. a single `- type: bugfix` line somewhere would be enough?

**Comment by psobolewskiPhD** [comment]
Following up on the bullets vs. check boxes, maybe the comments should explicitly state that it's good to delete unneeded elements?
For the benefit of a new contributor who might not be sure how scared the template is—or isn't?

**Comment by Czaki** [comment]
> @Czaki re discussion in #6092, I suggest that the categories should not be a checklist but just a bullet list, and people only need to delete elements

And if a person does not delete elements, should all labels be added? Such action needs to depend on user action, not lack of effort.

> rather than fill in a `- [ ]`, which often results in the malformed `- [x ]` (extra trailing space).

It is not a problem to handle this, also this action may fix such malformation.  

> rejigger this one to use a simpler standard. e.g. a single `- type: bugfix` line somewhere would be enough?

and how contributors will discover this?

**Comment by brisvag** [comment]
As mentioned elsewhere: given the valid concerns from #6042, I would rather remove these checks altogether from the CI. Instead, have those checks happen at a later stage (on merge, or on release, daily...)

**Comment by Czaki** [comment]
> As mentioned elsewhere: given the valid concerns from #6042, I would rather remove these checks altogether from the CI. Instead, have those checks happen at a later stage (on merge, or on release, daily...)

and you will take personal responsibility for adding labels to each omitted PR?

**Comment by Czaki** [comment]
close in favor of #6158

**Comment by Czaki** [comment]
yep

**Pull request closed without merging**
