### PR TITLE
Highlight widget

### PR DESCRIPTION
**Pull request by ppwadhwa**
# Description

Adds a custom widget for highlight weight to be used in the preferences dialog.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

https://user-images.githubusercontent.com/54282105/111381213-63e14200-8673-11eb-81f0-faac85f6f062.mov

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tlambert03** [comment]
ooo!  you got the sharp star edges! :)

**Comment by ppwadhwa** [comment]
> ooo! you got the sharp star edges! :)

Yes!  I discovered you could specify the joint type between lines.  :)

**Review by sofroniewn — APPROVED** [review]
Looks beautiful! Love it.
 
Let me know if you need any help wiring up the dialog to the hightlight thickness in a follow up PRs

**Comment by ppwadhwa** [comment]
> Looks beautiful! Love it.
> 
> Let me know if you need any help wiring up the dialog to the hightlight thickness in a follow up PRs

Thanks, @sofroniewn!  I'll be sure to reach out.  :)

**Pull request merged**
