### PR TITLE
Use `QLargeIntSpinBox` from superqt, remove internal one

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
removes the `QtLargeIntSpinBox` from our code and uses the one in `superqt` (which is the same implementation)

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]
🚀

**Review by alisterburt — APPROVED** [review]
looks good!

**Review by Carreau — APPROVED** [review]
Does that introduce a minimum version of superqt ? 
It does not seem so as I see it is present in 0.2.0 which is the earliest version present in PyPI, but still want to check.

**Comment by tlambert03** [comment]
> Does that introduce a minimum version of superqt ?

nope, this one has been there for a bit. in any case, we're already pinned on 0.2.2, and it's definitely in there.

**Comment by Carreau** [comment]
> nope, this one has been there for a bit. in any case, we're already pinned on 0.2.2, and it's definitely in there.

Ok, well, let's get that in then.

**Pull request merged**
