### PR TITLE
Adds subfolder organization to gallery.

### PR DESCRIPTION
**Pull request by melissawm**
Co-authored-by: chili-chiu <89602983+chili-chiu@users.noreply.github.com>

# Description
Adds a basic sub-folder organization to the gallery. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
This is based on @chili-chiu's suggestions for categories.

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by melissawm** [comment]
One thing I've noticed is that the right-hand sidebar doesn't show for me on a regular laptop screen, only on a larger screen or when I reduce the page to 90% zoom. With these changes, it's the right-hand sidebar that is updated:

Screen Shot 2022-04-07 at 7 01 36 PM

**Comment by jni** [comment]
Thanks for this @melissawm @chili-chiu!

Here are my thoughts on the current attempt and things I would do differently. Obviously it would be good to get a bit more consensus before following up on my suggestions below... CC @sofroniewn @kevinyamauchi 

1. Virtually all of the examples in "analysis" should be moved to "visualization". The vast majority are very simple visualizations and contain no "analysis" (which I define as "extracting knowledge, e.g. in the form of some kind of data table, from images"). The most obvious example is `examples/analysis/add_image.py`, but they are all on this spectrum.
2. (could be later PR) "visualization" then becomes huge. Assuming we only want one level of nesting, we might want "visualization - basic" and "visualization - advanced", or "2D", "3D", "nD", and "advanced". Probably going through the list my preference would be "basic 2D", "basic nD" and "advanced".
3. In (current) visualization, I think "set_theme" should be moved out to e.g. "other/misc" or "customizing napari" or something like that.
4. "cursor_ray" should also be moved out of visualization. In scikit-image we would have this in "applications", which contain deeper-dives into particular concepts.
5. Anything that involves the user clicking to add or remove data should go under "annotation". e.g. paint-nd.py, bbox-annotator.py
6. shapes_to_labels.py could potentially go in analysis! :joy: 
7. I'd move interactive/multithreading/live/progress bar to something like "live update" or "multithreading", rather than big data, as they are relevant in many small data contexts.
8. axes and time stamps/fps are no longer experimental I think, so they might go in a folder called "display" maybe?
9. "gui" by and large is right as far as I'm concerned.

**Comment by melissawm** [comment]
Just as a note, I'm trying to investigate adding tags to examples instead of using subgalleries. This would allow examples to have more than one category. This is not possible with the current sphinx gallery but it could be implemented with a custom directive, would probably just take a bit more effort.

**Comment by chili-chiu** [comment]
> Thanks for this @melissawm @chili-chiu!
> 
> Here are my thoughts on the current attempt and things I would do differently. Obviously it would be good to get a bit more consensus before following up on my suggestions below... CC @sofroniewn @kevinyamauchi
> 
> 1. Virtually all of the examples in "analysis" should be moved to "visualization". The vast majority are very simple visualizations and contain no "analysis" (which I define as "extracting knowledge, e.g. in the form of some kind of data table, from images"). The most obvious example is `examples/analysis/add_image.py`, but they are all on this spectrum.
> 2. (could be later PR) "visualization" then becomes huge. Assuming we only want one level of nesting, we might want "visualization - basic" and "visualization - advanced", or "2D", "3D", "nD", and "advanced". Probably going through the list my preference would be "basic 2D", "basic nD" and "advanced".
> 3. In (current) visualization, I think "set_theme" should be moved out to e.g. "other/misc" or "customizing napari" or something like that.
> 4. "cursor_ray" should also be moved out of visualization. In scikit-image we would have this in "applications", which contain deeper-dives into particular concepts.
> 5. Anything that involves the user clicking to add or remove data should go under "annotation". e.g. paint-nd.py, bbox-annotator.py
> 6. shapes_to_labels.py could potentially go in analysis! 😂
> 7. I'd move interactive/multithreading/live/progress bar to something like "live update" or "multithreading", rather than big data, as they are relevant in many small data contexts.
> 8. axes and time stamps/fps are no longer experimental I think, so they might go in a folder called "display" maybe?
> 9. "gui" by and large is right as far as I'm concerned.

Thanks for the thorough feedback @jni!

Regarding 1/2, I agree that 'analysis' is not the right term. 
I used it for examples showing 'how to interact with data' broadly, in order to not have almost everything under 'visualization' as you pointed out in 2. There could be a more appropriate term, or they could be grouped differently. 
Some don't fit into nD categories, perhaps basic/advanced would be a good way? Happy to hear others' thoughts!

Agree with the rest :)

**Comment by sofroniewn** [comment]
This looks like it's off to a great start. Thanks @melissawm and @chili-chiu and thanks for comments @jni - i largely agree with the direction all of this is going

> Regarding 1/2, I agree that 'analysis' is not the right term.
I used it for examples showing 'how to interact with data' broadly, in order to not have almost everything under 'visualization' as you pointed out in 2. There could be a more appropriate term, or they could be grouped differently.
Some don't fit into nD categories, perhaps basic/advanced would be a good way? Happy to hear others' thoughts!

I'd probably put the basic things like `add_image` and `nD_image` into visualization. We could do `visualization/basic` and only include single layer/ simple data ones `visualization/multidimensional` for all the `nD` examples, and `visualization/advanced` for the rest.

I like `applications` and `annotations` as potential folders too.

It might be nice to add an `examples/README.md` page to this PR too which defined the folders. Something like

```
Visualization: This folder contains examples where the primary purpose is to look at some form of imaging data
Annotation: This folder contains examples where the user is able to annotate imaging data
Analysis: This folder contains examples where some form of knowledge (e.g. in the form of some kind of data table or statistics) is extracted from imaging data
```

But with much better descriptions (those shouldn't be relied on, but are just illustrative)

That could then help make it clear where everything, including new contributions should go

**Comment by chili-chiu** [comment]
Taking the suggestions above, here are the folder definitions that we can add to readme.md (and perhaps also as the guide page for gallery on napari.org):

- analysis: Examples of information extraction from images
- GUI: Examples related to Qt, magicgui, and plugin implementation
- visualization - basic: Visualization examples with single layer/ simple data 
- visualization - nD: nD visualization examples
- visualization - advanced: advanced visualization examples
- interactivity: Multi-threading, multi-scale images, and other examples addressing napari interactivity
- experimental: Examples with functions not in the released version of napari
- historical: Examples with deprecated functions or functions have been implemented in napari

If this sounds reasonable, I will reorganize examples accordingly :)

**Comment by sofroniewn** [comment]
Looking good @chili-chiu, thanks - I made some minor changes to hopefully add more clarity. Maybe @jni can take a look too

- analysis: Examples of information extraction from imaging data
- GUI: Examples related to Qt, magicgui, and plugin graphical user interfaces
- visualization - basic: Visualization examples with single layer/ simple data
- visualization - nD: n-dimensional visualization examples
- visualization - advanced: advanced visualization examples
- interactivity: Multi-threading, multi-scale images, and other examples addressing napari interactivity
- experimental: Examples with functions not in the released version of napari
- historical: Examples with deprecated functions or functions have been implemented in napari

**Comment by jni** [comment]
Yay! Thanks @chili-chiu those sound great. The only one I'm not sure about is "multi-scale images" in "interactivity", I think I would put those in advanced visualization in general? But maybe I'm missing something about our specific examples.

**Comment by chili-chiu** [comment]
> Yay! Thanks @chili-chiu those sound great. The only one I'm not sure about is "multi-scale images" in "interactivity", I think I would put those in advanced visualization in general? But maybe I'm missing something about our specific examples.

My initial thinking was that the existence of multi-scale images is to address slow rendering with larger datasets - thus under "interactivity". I don't have a strong preference either way. 

There may be other examples that could fit in more than one bucket as well, so the tag @melissawm mentioned will be very useful 😀

**Comment by sofroniewn** [comment]
> My initial thinking was that the existence of multi-scale images is to address slow rendering with larger datasets - thus under "interactivity". I don't have a strong preference either way.

It makes sense to me how you're thinking, but maybe let's start with multi-scale in with the advanced visualization as hopefully the user isn't really focused on the rendering speed/ interactivity there but more that it is a large complex dataset. We can definitely revisit this though once we see everything in place. Very easy to change later

**Comment by chili-chiu** [comment]
After discussing with @melissawm, we will wait until the tags function is implemented to update this PR.

**Comment by Carreau** [comment]
This PR have not been active for quite some time. 

In order to keep the list of PRs short and easier to work with, I am going to tag this PR as [stale](https://github.com/napari/napari/pulls?q=is%3Apr+label%3Astale+is%3Aclosed) and close it.

Feel free to reopen and remove the "stale" label when work on this PR resumes. 
If you do not have the permissions to do so, feel free to request help from one of the maintainer to reopen and remove the `stale` label .

**Pull request closed without merging**
