### PR TITLE
Add viewer keybinds to select & show only next/prev layer and to toggle visibility of unselected

### LINKED ISSUE #2166: Viewer toggle mode
## 🚀 Feature
It would be useful to be able to toggle between different image layers by clicking on the image layer.

## Motivation

The viewer currently has a `stack` mode where images in different layers can be blended together, and a `grid` mode where images in different layers are displayed side-by-side.

## Pitch

It would be useful to be able to compare features across different image layers in the same position of the ND dataset by toggling between the layers, displayed at full opacity, by clicking on the desired layer. In this new `toggle` viewer mode, only the selected layer is visible, and all other layers are hidden.

## Alternatives

Currently, this can be achieved by first hiding all layers using the eye icon. Then one layer is made visible. To make another layer visible, the user will first hide the old layer, and then unhide the new layer. This process is not convenient as it involves a lot of mouse clicks.

### LINKED ISSUE #5253: "Show only this layer" menu / double-click action
## 🚀 Feature
If you have many layers open, it would be convienient if here was a menu such as "Show only this layer, hide all others"

## Motivation

For showing just one layer, it is complicated because you need to hide many other layers.

## Pitch

To spare time of users, it would be great if some convenience menus for this existed.

## Alternatives

The course attendee who reported that also proposed to use a mouse double-click on any layer to "show only this layer"

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# References and relevant issues
Closes: https://github.com/napari/napari/issues/2166
Closes: https://github.com/napari/napari/issues/5253

# Description
As requested, this PR adds keybindings to enable selecting and showing only the next/previous layer in the layer list. By default these are bound to Shift-Option-Up and -Down (see note below)
Additionally, to complement this and the existing `Toggle visibility of selected layers` (default `V`), I added a keybinding for `Toggle visibility of unselected layers` (default shift-V, because alt-V clashed on Windows).

Edit: to prevent skipping layers due to Up/Down firing double, I capture Up/Down with modifiers from QtLayerList so they are handed by the viewer only and not by Qt. The alternative is to not do that and not have the keybinding advance the selection, but this only works if Up/Down are used, but someone might want to use W/S or some other non-arrow binding, which would make it fail.

Note: it's more logical and natural feeling to have the `Select & show only next/prev` be just Alt-Up and Alt-Down instead of Shift-Option-Up. However, Alt-Up and Alt-Down change the focus of sliders. I suspect this is a much less frequently used set of keybinds, so would be tempted to change it to use Left Right, since left right keys are already are used for manipulating sliders, it makes it more intuitive for up/down to manipulate layer list and left/right to manipulate sliders.
Shift-Up/Down can't be used either, because it's multi selection.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
CC: @jnahlers & @jni What do y'all think of this? I think it basically does what was requested.
What do y'all think of the up/down arrow modifiers? As I mentioned, I used this branch for a bit and plain Alt-Up/Alt-Down was much more natural with the other keybinding. Plus it mimics Photoshop and the existing Alt-click behavior. 
Since this won't be in until 0.5.0 maybe changing the slider focus keybind is OK?

**Comment by brisvag** [comment]
The up-down keybindings give me big *code smell* feelings... It sounds like they're trying to do what [spaces was trying to solve](https://napari.org/dev/naps/3-spaces.html). Not saying that they shouldn't go in, just that they're probably a patch on a deeper problem ^^'

**Comment by psobolewskiPhD** [comment]
> The up-down keybindings give me big _code smell_ feelings... It sounds like they're trying to do what [spaces was trying to solve](https://napari.org/dev/naps/3-spaces.html). Not saying that they shouldn't go in, just that they're probably a patch on a deeper problem ^^'

I thought spaces were meant to handle differing coordinate systems? This is just related to e.g. fluorescence multichannel data where you want to see a single channel without blending. Both QuPath and Fiji have an easy way to isolate one channel and it's a very common first step in exploratory analysis.
See also this description from Talley https://github.com/napari/napari/issues/2550 
In napari I do this all the time using the `alt-click` mouse binding I added, but that's not actually released yet. But using this PR it's been really handy to just flip through layers and get that effect. 
The cherry on the top would be Talley's requested greyscale toggle, which actually shouldn't be hard I don't think, just not sure of the UI aspect (checkbox, preference, keybinding ...).

**Comment by brisvag** [comment]
> This is just related to e.g. fluorescence multichannel data where you want to see a single channel without blending

You're right, classic problem of only thinking of my use case :P Ignore my comment then!

**Comment by psobolewskiPhD** [comment]
hehe, I'm 💯 guilty of that all the time! 
I think the diversity of use cases for napari is part of what makes some of these things tricky but also what makes it fun.

**Comment by jnahlers** [comment]
@psobolewskiPhD Just had a chance to try this PR. I'm seeing some odd behaviour on my end...
- `alt-V` first opens the View dropdown in the Menubar. If I keep `alt` held down and then hit `v` again it toggles the unselected visibility. I guess this is a clashing shortcut?
- For some reason `ctrl+alt+up`/down is jumping two layers at a time! If there is only one layer possible (i.e. if the 'cursor' [the grey dashed outline] is on the second layer and I press up) then only the cursor moves up, but the selection is unchanged.

**Comment by psobolewskiPhD** [comment]
> @psobolewskiPhD Just had a chance to try this PR. I'm seeing some odd behaviour on my end...
> 
> * `alt-V` first opens the View dropdown in the Menubar. If I keep `alt` held down and then hit `v` again it toggles the unselected visibility. I guess this is a clashing shortcut?

I'm going to guess you're on windows? Alt toggles the ability to access menus via letters. So I guess that's the issue. Can you try using the Preferences  > Shortcuts pane to rebind it to say Shift-V and see how it works? 

> * For some reason `ctrl+alt+up`/down is jumping two layers at a time! If there is only one layer possible (i.e. if the 'cursor' [the grey dashed outline] is on the second layer and I press up) then only the cursor moves up, but the selection is unchanged.

I was worried about that, but it didn't happen for me on my mac locally. I guess both the new keybinding and the native up arrow are firing? If you make like 4 new empty points layers and go bottom to top, with it skipping does it still correctly show just the one layer?
And can you try rebinding to something else, see if that works?
image

Could you maybe post your `napari --info` just so I know what Qt you have too?
Thanks for the feedback!
:heart:

**Comment by jnahlers** [comment]
@psobolewskiPhD Yes I'm on Windows... which means I get to stress test all the Mac/Linux developer's PRs 😄.

```
napari: 0.5.0a2.dev486+g4d60a7ce
Platform: Windows-10-10.0.19045-SP0
Python: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.2
SciPy: 1.11.4
Dask: 2023.12.0
VisPy: 0.14.1
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3
```
Rebinding Alt-V to Shift-V makes it work as expected. Option/Alt-Shift-Up/Down sounds reasonable? 

Is the goal to make layer selection similar to file selection in a file manager? Not directly related to the PR, but it bothers me a bit that Shift does not work like in a file manager. If you click on a layer, and then press `shift-down` it will add the next layer down to the selection, but then pressing `shift-up` doesn't _remove_ the layer again as it would in most any file manager.

**Comment by psobolewskiPhD** [comment]
> Not directly related to the PR, but it bothers me a bit that Shift does not work like in a file manager. If you click on a layer, and then press `shift-down` it will add the next layer down to the selection, but then pressing `shift-up` doesn't _remove_ the layer again as it would in most any file manager.

I agree, I also ran into this while testing this PR and found it strange.
What appears to happen is that the set of selected layers can only be expanded. So if you have say 10 layers and start in the middle do Shift-Up 3 times, then you have to do Shift-Down 4 times to select the lower layer. But you will not reduce the set.
It's not just file managers, it's not consistent with selecting lines in a text editor.
This is being handled by Qt, but should go in an issue so we can keep track of the behavior. It should be fixable on our end by catching the modifier and handling it in napari.

**Comment by psobolewskiPhD** [comment]
@jnahlers 
I updated the default for toggle-others-vis to Shift-V
And the Arrow behavior is now bound to Option-Shift-Up/Down.
I capture Up/Down with modifiers to prevent native Qt use so the double jump should be eliminated.
(This same strategy can be used to fix the Shift-Up/Down behavior!)
How does it feel now?

**Review by jni — APPROVED** [review]

**Review by melonora — DISMISSED** [review]
Feature looks good! But please have a doc PR ready before merging:)

**Pull request merged**
