### PR TITLE
Update napari console dependency

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
Updates our napari console dependency - was needed because of #3274

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by jni — APPROVED** [review]

**Comment by goanpeca** [comment]
@sofroniewn could you update it here as well ?

https://github.com/napari/napari/blob/master/binder/environment.yml#L15 ?

**Comment by sofroniewn** [comment]
> @sofroniewn could you update it here as well ?

done

It also looks like we might now be getting some test fails. They might have started in #3277 cc @jaimergp @tlambert03, hopefully not too hard to figure out!!

**Comment by jaimergp** [comment]
> It also looks like we might now be getting some test fails.

I think it comes from #2991:

[Error](https://github.com/napari/napari/pull/3297/checks?check_run_id=3468254701#step:7:30):

```
Template does not support 3.9

[napari] Generating application template...
Using app template: https://github.com/beeware/briefcase-windows-msi-template.git
```

We might need to stick to 3.8 on Windows?

--edit-- 

More info on why [the template does not support 3.9](https://github.com/beeware/briefcase-windows-msi-template/issues/9):

* The template relies on Python.net (https://github.com/beeware/briefcase/issues/557#issuecomment-765736817)
* Python.net does have some initial support for 3.9 but [they didn't release wheels yet due to unresolved crashes](https://github.com/pythonnet/pythonnet/issues/1389). This doesn't look like a trivial fix, so I'd say we rollback to 3.8 on Windows if possible. AFAIK the push for 3.9 was mainly driven by the MacOS updates. I'll put a PR.

**Comment by sofroniewn** [comment]
> We might need to stick to 3.8 on Windows?

Thanks for fix over there!!

**Pull request merged**
