### PR TITLE
Add matplotlib colormaps and set magma as default

### PR DESCRIPTION
**Pull request by jni**
# Description
This PR adds support for all the matplotlib colormaps and sets magma as the default for grayscale image layers.

I also tried `viewer.layers[0].cmap = 'inferno'` and it instantly updated! Maybe everyone else reading this is already used to the magic of Napari but I'm still in the amazed phase. =D

I'll also note that `python examples/layers.py` results in

```pytb
 $ python examples/layers.py 
/home/jni/miniconda3/envs/cf/lib/python3.6/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
Traceback (most recent call last):
  File "examples/layers.py", line 84, in <module>
    viewer.show()
AttributeError: 'Viewer' object has no attribute 'show'
```

but I consider fixing that beyond the scope of this PR.
## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update (@jni says: ?)

# How has this been tested?
I ran `demo.py` without issue and `layers.ipynb` which verified that the default colormap and another colormap from matplotlib both worked.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality  :arrow_left: this is definitely true :stuck_out_tongue: 
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (?)
- [ ] I have added tests that prove my fix is effective or that my feature works (?)

### CODE REVIEW

**Comment by freeman-lab** [comment]
Love this in theory! Is anyone else at all concerned about taking on `matplotlib` as a hard dependency? It's a pretty heavy package, and there's something about keeping the dependencies minimal, especially if there are other ways to provide most / all of the colormaps via vispy. Maybe somehow make optional or a plugin or something?

**Comment by royerloic** [comment]
Should be trivial to rip-off just the colormaps and add our own curated ones...
I second @kne42 that we should avoid such a heavy dependency if all we need
is LUTs...

**Comment by royerloic** [comment]
Sorry, I means I second @freeman-lab lol.

**Comment by kne42** [comment]
Agree with @freeman-lab and @royerloic. Also not sure what you’re bringing up about the error – we have no `layers.py` example.

**Comment by AhmetCanSolak** [comment]
> Should be trivial to rip-off just the colormaps and add our own curated ones...
> I second @kne42 that we should avoid such a heavy dependency if all we need
> is LUTs...

I would love to hear about how to not get whole matplotlib as a dependency.

**Comment by jni** [comment]
> I would love to hear about how to not get whole matplotlib as a dependency.

@AhmetCanSolak here you go... ;)

There is definitely a lot of trimming from the vendored code that could be done, but I'd rather keep it around as unmodified as possible anyway, as this will make it easier to apply later patches from mpl if we decide we need them.

Anyway, this is working great with `layers.ipynb`, but `markers.ipynb` is failing with `AttributeError: 'Window' object has no attribute 'add_markers'`. I'll let @sofroniewn comment on that one... ;)

**Comment by sofroniewn** [comment]
Have just started trying to run this with the `layers.ipynb` and run into the following error message. Has anyone else encountered this? Will try and debug

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/Github/napari-gui/napari_gui/layers/_image_layer.py in vispy_or_mpl_colormap(name)
     45         try:
---> 46             mpl_cmap = getattr(cm, name)
     47         except AttributeError:

AttributeError: module 'napari_gui.layers.vendored.cm' has no attribute '/'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-2-4a9b4ebebc6b> in <module>()
----> 1 from napari_gui import imshow
      2 window = imshow(data.camera())

~/Github/napari-gui/napari_gui/__init__.py in <module>()
      1 from .util.misc import imshow
----> 2 from .elements import Window, Viewer
      3 
      4 from ._version import get_versions
      5 __version__ = get_versions()['version']

~/Github/napari-gui/napari_gui/elements/__init__.py in <module>()
     13 from ._window import Window
     14 from ._viewer import Viewer
---> 15 from ._layer_list import LayerList
     16 from ._control_bars import ControlBars
     17 from ._dimensions import Dimensions

~/Github/napari-gui/napari_gui/elements/_layer_list.py in <module>()
      3 
      4 from vispy.util.event import EmitterGroup, Event
----> 5 from ..layers._base_layer import Layer
      6 
      7 from .qt import QtLayerPanel

~/Github/napari-gui/napari_gui/layers/__init__.py in <module>()
      8 
      9 from ._base_layer import Layer
---> 10 from ._image_layer import Image
     11 from ._markers_layer import Markers
     12 from ._register import add_to_viewer

~/Github/napari-gui/napari_gui/layers/_image_layer.py in <module>()
     54 
     55 AVAILABLE_COLORMAPS = {k: vispy_or_mpl_colormap(k)
---> 56                        for k in matplotlib_colormaps + list(color.get_colormaps())}
     57 
     58 

~/Github/napari-gui/napari_gui/layers/_image_layer.py in <dictcomp>(.0)
     54 
     55 AVAILABLE_COLORMAPS = {k: vispy_or_mpl_colormap(k)
---> 56                        for k in matplotlib_colormaps + list(color.get_colormaps())}
     57 
     58 

~/Github/napari-gui/napari_gui/layers/_image_layer.py in vispy_or_mpl_colormap(name)
     46             mpl_cmap = getattr(cm, name)
     47         except AttributeError:
---> 48             raise KeyError(f'Colormap "{name}" not found in either vispy '
     49                            'or matplotlib.')
     50         mpl_colors = mpl_cmap(np.linspace(0, 1, 256))

KeyError: 'Colormap "/" not found in either vispy or matplotlib.'
```

**Comment by sofroniewn** [comment]
Also, not unexpected that `markers.ipynb` is broken, I never fixed that one on the last merge of stuff, sorry. I think we can just delete it though as there are markers examples in the `layers.ipynb` - gets at a broader discussion we need to have around fixing our demos and "test" notebooks

**Comment by sofroniewn** [comment]
Error from above is because right now on my machine

```python
print(matplotlib_colormaps)
['/', 'U', 's', 'e', 'r', 's', '/', 'n', 'i', 'c', 'h', 'o', 'l', 'a', 's', 's', 'o', 'f', 'r', 'o', 'n', 'i', 'e', 'w', '/', 'G', 'i', 't', 'h', 'u', 'b', '/', 'n', 'a', 'p', 'a', 'r', 'i', '-', 'g', 'u', 'i', '/', 'n', 'a', 'p', 'a', 'r', 'i', '_', 'g', 'u', 'i', '/', 'l', 'a', 'y', 'e', 'r', 's', '/', 'm', 'a', 't', 'p', 'l', 'o', 't', 'l', 'i', 'b', '_', 'c', 'm', 'a', 'p', 's', '.', 't', 'x', 't']
```

This is because there is a typo where 
```python
with open(_matplotlib_list_file) as fin:
    matplotlib_colormaps = [line.rstrip() for line in _matplotlib_list_file]
```
should be
```python
with open(_matplotlib_list_file) as fin:
    matplotlib_colormaps = [line.rstrip() for line in fin]
```
inside `colormaps.py`

**Comment by sofroniewn** [comment]
Overall looks great Juan - a couple questions / comments

Right now what is the difference between a layers `colormap` and `cmap` property, why do we need both and why are there differences in the setters? This might be a question for @kne42

Also, is it possible or can we make a way to get the name of the colormap (as a string) back from the colormap property on the layer - which is a vispy colormap object. Ideally that object would just have a name property (that could be empty). We sort of need this information somewhere to know how to update the drop-down menu if someone changes the colormap from the notebook, or to prevent the default from being hardcoded in two locations (right now if you open the dropdown menu it still lists the default as `hot` but `magma` is actually in use.

Also, I think there will be lots of people (certainly in the bio field) that want to be able to select one of the six basic colormaps 

> Blues - black to blue
> Reds - black to red
> Greens - black to green
> Magenta - black to magenta
> Yellow - black to yellow
> Cyan - black to cyan

which we can't do right now. It's easy to create and set these colormaps - i.e.
`layer.cmap = Colormap([(0, 0, 0, 1), (1., 0., 1., 1.)])`
but I think we want them as drop-down options. I'd also argue that the current list of colormaps has too many that people won't want to use - but I'm ok with trying to trim it down at a later date.

Finally we'll always want to support custom colormaps passed like the one above, but in that case how should we update the drop-down menu? Does it need an entry like `custom` or a blank space such that when a colormap without a name is passed it displays that instead. This can be a separate thing to implement, but wanted to flag it now

**Comment by jni** [comment]
Oops! Apologies for adding commits after testing! Such a rookie mistake! Fixing now. (Although @sofroniewn you probably have push commits to my branch, are you aware of this?) There is also the github suggested changes feature: https://help.github.com/articles/commenting-on-a-pull-request/#adding-line-comments-to-a-pull-request

**Comment by jni** [comment]
> Right now what is the difference between a layers colormap and cmap property, why do we need both and why are there differences in the setters? This might be a question for @kne42

Correct, I didn't want to mess with the design here. Let's keep this self-contained.

> Also, is it possible or can we make a way to get the name of the colormap (as a string) back from the colormap property on the layer - which is a vispy colormap object.

Is this working before this PR? If not, then I suggest raising as an issue. The main question is whether the vispy colormap object currently has a name field. If not, then we need to decide whether to add such a thing (maybe upstream), or to maintain the mapping ourselves. Probably I prefer the former.

> Also, I think there will be lots of people (certainly in the bio field) that want to be able to select one of the six basic colormaps.

I think this is something that can happen in a future PR also.

> Finally we'll always want to support custom colormaps passed like the one above, but in that case how should we update the drop-down menu?

A name field required by the colormap objects would solve this also.

**Review by sofroniewn — APPROVED** [review]
Looks go to me now, agreed that the other changes I mentioned can come in future PRs and there's something to trying to keep PRs small and getting them merged more quickly :-)

**Comment by kevinyamauchi** [comment]
@jni, thanks for this! I think it is good to go. My only comment is that as @sofroniewn said, the GUI's colormap list should update to reflect changes made in the notebook. I also agree that is out of the scope of this PR. However, for some reason I don't have the ability to approve this PR. Do we have to update from master before we can review? Or maybe I don't have permissions?

**Comment by kne42** [comment]
@kevinyamauchi To submit a review you should click on the "Files changed" tab and then the green "Review changes" button.

**Comment by kevinyamauchi** [comment]
> @kevinyamauchi To submit a review you should click on the "Files changed" tab and then the green "Review changes" button.

Thanks! Pre-coffee brain... XD

**Review by kevinyamauchi — APPROVED** [review]
Looks good to me! Thanks!

**Comment by jni** [comment]
🚀 🎉

**Pull request merged**
