### PR TITLE
refactor theme setting

### PR DESCRIPTION
**Pull request by kne42**
# Description
- add more general `palette` property and make `theme` a wrapper around it (as a preset)
- include all themes as a class variable
- move theme/palette setting to ViewerModel and make event-based

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
see #253

# How has this been tested?

- [x] all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — CHANGES_REQUESTED** [review]
The code looks fine, but the range slider is getting the wrong color in the dark theme. If you run `add_image` on master you get this

image

If you run it on this PR you get this 

image

See how the color is lighter - not sure what's causing that. Maybe @freeman-lab has an idea

**Comment by sofroniewn** [comment]
I really like how simple `Viewer` is now, nice job. If you can fix the range slider coloring then we can merge. Maybe @freeman-lab also wants to double check the rest of the stylings are ok too

**Comment by kne42** [comment]
I've fixed the clims but the dimensions sliders are still not up-to-date. However, this is a bug present on master and this PR is not meant as a bug-fix.

Aforementioned fix is non-trivial without disrupting what this PR meant to clean up. Would recommend that we fix this by making the range slider style based on a stylesheet.

**Review by sofroniewn — APPROVED** [review]
This all looks good to me, confirmed that it is currently working. Fixing the dims sliders in a followup PR makes sense too

**Pull request merged**
