### PR TITLE
Try to track down mac test failures.

### PR DESCRIPTION
**Pull request by Carreau**
This tries to track down macs test failures which happen because of a
timeout in teardown for things that _should_ be relatively fast.

I believe i've narrowed it down to VisPyCanvases not being properly
cleaned after test, and down the rabit hole I went.

 - Make viewer a context manager to not have to closes things every
 time. Not sure we want to keep.
 - Canvas seemed to stay around too long, I haven't completely fixed
 that one yet but one referer is the QtViewer
 - QtViewer stay arround at least because of a bound method.

This does not make much changes locally, it make the timing a little bit
more consistant and less time is spent in teardown, so I hope this will
help CI.

Still draft but I'll use that to sync between my computers.

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
just a quick note @Carreau ... this overlaps a fair amount with #3184.  This is more minimal (both in scope and LOC), so if you hit on something good, let's merge it.  but it will probably have a lot of conflicts over there, so I might wait to see where this lands

**Comment by Carreau** [comment]
Ah thanks, yess I'll look into #3184, and try to avoid many conflicts, mostly I want to make sure the test suite passes.

**Comment by tlambert03** [comment]
Yep, that's a higher priority!  Do whatever works :)

**Comment by Carreau** [comment]
TODO: Extract 736e79f into it's own commit.

**Comment by sofroniewn** [comment]
@Carreau now that we merge #3890 can we close this?

**Pull request closed without merging**
