### PR TITLE
Fix tox `passenv` setup for `DISPLAY` and `XAUTHORITY` environment variables

### PR DESCRIPTION
**Pull request by dalthviz**
# Description

Seems like now tox raises an error for space-separated environment variables set with the `passenv` config. This was affecting PR #5437

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [ ] all tests pass with my change
- [ ] I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Comment by dalthviz** [comment]
This could be also affecting PR #5440

**Comment by andy-sweet** [comment]
My guess is this may be cause by the recent major release of `tox-gh-actions`: https://github.com/ymyzk/tox-gh-actions/releases/tag/v3.0.0

Given the release notes suggest there may be breaking changes, we may want to consider pinning that dependency which is installed in `.github/workflows/test_pull_requests.yml` and maybe elsewhere.

But if tests pass here, I'm down to just merge this.

Thanks @dalthviz!

**Review by andy-sweet — APPROVED** [review]
I'm going skip the usual 24 hour merge protocol here so that PR/main tests can start passing again. The change here appears super simple and also trivial to revert.

We may want to follow up by pinning `tox-gh-actions`, but that can come later.

**Comment by andy-sweet** [comment]
I cancelled and restarted the long running test, which is likely due to the issues we had recently: https://github.com/napari/napari/issues/5433#issuecomment-1362957919

After this PR is merged, I'll write a PR to effectively revert #5414, though not sure if that will entirely solve things.

**Comment by andy-sweet** [comment]
> I cancelled and restarted the long running test, which is likely due to the issues we had recently: [#5433 (comment)](https://github.com/napari/napari/issues/5433#issuecomment-1362957919)

Well, that really doesn't want to pass now. I'm very skeptical that this PR is actually having an effect - unless the env vars were not being passed properly before?

I fine to either merge this as, or adding some pytest skip marks to the offending tests `qt_dims: test_not_playing_after_ndim_changes, test_not_playing_after_ndisplay_changes, test_play_button` and rerun things. Any thoughts @dalthviz ?

**Comment by andy-sweet** [comment]
Decided that I'm just going to go ahead and merge this. Will follow up with a PR to revert/skip the problematic tests.

**Comment by psobolewskiPhD** [comment]
For the record, here's the documentation for tox 4:
https://tox.wiki/en/latest/upgrading.html#changed-ini-rules

so for tox 4, commas can be used.
line breaks are safe for tox 3 and tox 4

**Pull request merged**
