### PR TITLE
Add npe2 plugins to plugins installed list 

### PR DESCRIPTION
**Pull request by ppwadhwa**
# Description

The npe2 plugins will be added to the list of installed plugins on the plugins dialog.  

Addresses part of https://github.com/napari/napari/issues/3685

### CODE REVIEW

**Review by tlambert03 — COMMENTED** [review]
on the right track!  couple comments:

1. can add the try: `import npe2` stuff to https://github.com/napari/napari/blob/main/napari/plugins/_npe2.py, and make an `iter_manifests` convenience function there that you use here?

```py
from napari.plugins import _npe2

for manifest in _npe2.iter_manifests():
    distname = manifest.distribution  # see next comment
    if distname ...
```

2. Note that `manifest.name` (i.e. what you're grabbing when you loop through `_manifests.keys()`) is technically not exactly the same as the distribution name, which is what we're trying to show in the plugin window.  For example, if the package was `scikit-image`, the manifest name would be `scikit_image`.  I _think_ (but am open to discussion) that we want to show the package name here exactly as they would see it on PyPI.   That may mean that you need to add a new field (it can be a private field) to the `PluginManifest`, so we can know how the package named itself before our `name` normalization changed a dash to an underscore.  cc @nclack @Carreau

**Comment by nclack** [comment]
We talked about this elsewhere, but I think the thing to do is just treat 'name' as distribution name, and never do the underscore transformation.  We'll have to change the regex on command id.

**Comment by ppwadhwa** [comment]
@tlambert03 I added in the helper function.  I have not done anything with the distribution name yet.  I used the normalized name for now.  I can change this based on what is decided for the `name` vs `distribution_name`.  

what do you think of the changes I made?

**Comment by ppwadhwa** [comment]
I have disabled the enable/disable checkbox for npe2 plugins on the plugins dialog for now.  The enabled/disabled state could be taken care of in another PR.  what do you all think?  

In this image, pam_test2 is the npe2 plugin.  I tried to darken the checkbox a bit to show its disabled.  @isabela-pf What do you think of this--
Screen Shot 2021-11-26 at 10 31 34 PM

Screen Shot 2021-11-29 at 11 27 24 AM

**Review by goanpeca — APPROVED** [review]
Looks good @ppwadhwa, thanks for working on this 🚀

**Comment by nclack** [comment]
@ppwadhwa I test the uninstall button and it doesn't really work. Could you disable it also?

>  I tried to darken the checkbox a bit to show its disabled

I'm not very familiar w qss but one approach I've seen is to use the opacity to indicate a control is disabled. This way it looks ok on dark and light themes.

**Comment by tlambert03** [comment]
> @ppwadhwa I test the uninstall button and it doesn't really work. Could you disable it also?

can we get it to work rather than disable?

**Comment by isabela-pf** [comment]
@ppwadhwa thanks for summoning me! 🧙 

In terms of disabled button styling, I went looking around in the napari viewer to see what disabled UI currently does and surprisingly could not find any in the main UI (only in OS styled areas). This is probably because I don't use napari like the rest of y'all, so if anyone has examples of disabled buttons or other UI I'd love to check them out for this PR and for reviewing others in the future.

In general, lower opacity is a common way of showing disabled buttons, so this seems appropriate to me unless there's another way disabled napari buttons currently appear. How much did you darken it, just for my reference?

**Comment by sofroniewn** [comment]
> > @ppwadhwa I test the uninstall button and it doesn't really work. Could you disable it also?

> can we get it to work rather than disable?

Agreed, it would be nice to avoid a regression here. Do we know why it isn't working?

**Comment by ppwadhwa** [comment]
@tlambert03 @nclack @sofroniewn 

As discussed in the community meeting today, the uninstall button does work to uninstall npe2 plugins.  It will not update the UI when that happens.  As per the plugin meeting on Wednesday, I have inserted a pop up window to notify the user when a npe2 plugin is installed/uninstalled that napari needs a restart in order for changes to take affect.  This pop up is temporary until we figure out how to handle installing clean up for npe2 plugins.

Let me know what you think...


https://user-images.githubusercontent.com/54282105/144556249-3e6563e1-4da0-4240-a08f-43d06fb8da3a.mov

**Comment by ppwadhwa** [comment]
And just to make sure I didn't miss anything-- we are still leaving the enable/disable checkbox disabled here, right?

**Comment by nclack** [comment]
> we are still leaving the enable/disable checkbox disabled here

yes

**Comment by sofroniewn** [comment]
Ok great! That looks good to me!! Looks like we've got test fails independent of this PR (which have been flagged in #3747). Let's wait till those are fixed and then we can merge this once all tests are passing. Thanks!!

**Review by sofroniewn — APPROVED** [review]

**Pull request merged**
