### PR TITLE
Deploy docs workflow

### PR DESCRIPTION
**Pull request by codemonkey800**
# Description

This updates the deploy docs workflow to push the built docs into `gh-pages` after building. This also configures the concurrency setting to allow only one docs build at a time so that stale, overlapping builds get cancelled.

After this is merged, there are a few more steps we'll need to do to make the docs go live: #4151 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# References

- #4047 
- #4147 
- #4151

# How has this been tested?

- Tested this deployment on my fork: https://codemonkey800.github.io/napari

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM! Super excited for this 🚀

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
Thanks all! I intend to merge this and complete the remaining steps in #4151 on Tuesday morning Australia time, ie ~2pm Monday Eastern. I'm not sure about the Google Calendar secrets step, nor about the calendar status in the new docs, so it would be good if @codemonkey800 and @neuromusic can be around to help me make sure I don't botch this transition :sweat_smile:

**Comment by codemonkey800** [comment]
@jni the calendar should be working in the latest version right now:

https://github.com/napari/napari-sphinx-theme/pull/74
https://napari.org/napari-sphinx-theme/demo/kitchen-sink/calendar.html

we'll need to use the new `napari-calendar` directive and add the secrets to the repo. let me know when you're ready and I can share the calendar secret with you

**Comment by codemonkey800** [comment]
you could also create a Google Calendar API key yourself if you wanted to keep the API keys separate for the theme docs site vs the napari docs

**Comment by jni** [comment]
@codemonkey800 I'm around, can you DM me the API user/key on Zulip or Signal (I DMd you my phone number on Zulip)

**Comment by jni** [comment]
> calendar should be working in the latest version right now:

This is **SUPER AMAZING** btw!!! :blush: :blush: :blush:

**Pull request merged**
