### PR TITLE
Integrated plugin dialog with install/uninstall & remote discovery

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
As mentioned in https://github.com/napari/napari/pull/1289#issuecomment-640995785, I'm working on a more integrated plugin dialog:

Untitled

Features include:
- finds available plugins by naming convention on PyPI
- finds available plugins on github, even without naming convention (such as `ome-zarr`) based on these conditions (This was the best I could do without a PyPI trove classifier):
   - they have the literal string "napari plugin" in the readme
   - they have a `setup.py` or `setup.cfg` file that declares a "`napari.plugin`" entry_point
   - they are published on PyPI with development status Alpha or greater.
- pip install/uninstall in background process with stdout feedback in the GUI. (paths and environment variables preserved so this would work in a bundle)
- detects outdated plugins and offers update button.
- integrated plugin sorter
- integrated error report (plugins with errors show a clickable warning icon that slides out the report).

(The checkbox next to each plugin will be used to activate/deactivate a plugin without actually uninstalling it)

This requires some changes to napari-plugin-engine that are not yet merged, so if you want to test this locally, you'll need to checkout the [napari-plugin-engine/refactor-discovery](https://github.com/tlambert-forks/napari-plugin-engine/tree/refactor-discovery) branch

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Carreau** [comment]
You could try to request a trove classifier to the PyPI team, pytest has one.

**Comment by jni** [comment]
> You could try to request a trove classifier to the PyPI team

Yeah, I found a comment to the effect that we need ~10 third party plugins before they'll consider adding a Trove classifier. We're almost there but not quite!

**Comment by sofroniewn** [comment]
> This requires some changes to napari-plugin-engine that are not yet merged, so if you want to test this locally, you'll need to checkout the napari-plugin-engine/refactor-discovery branch

hi @tlambert03 I was going to try and give this some review today, but ran into errors on launch with npe `0.1.5` and `0.1.7`. I also couldn't find that branch you mention above. If you let me know how to get started with this one I can do a review and hopefully we can get it in for 0.3.8 :-)

Also let me know if there's anything in particular you want feed back on/ want me to check out, sorry it has sat here for so long!!

**Comment by tlambert03** [comment]
> hi @tlambert03 I was going to try and give this some review today, but ran into errors on launch with npe `0.1.5` and `0.1.7`. I also couldn't find that branch you mention above. If you let me know how to get started with this one I can do a review and hopefully we can get it in for 0.3.8 :-)


hmm, that branch has actually been merged and released.  I just tested this again with `napari-plugin-engine-0.1.7` and it worked.  can you reinstall npe, making sure you're not on a local install, and then tell me what error you're getting?

**Comment by sofroniewn** [comment]
> hmm, that branch has actually been merged and released. I just tested this again with napari-plugin-engine-0.1.7 and it worked. can you reinstall npe, making sure you're not on a local install, and then tell me what error you're getting?

So turns out I get the same I get the same error with `napari --info` and I get that with npe `0.1.7` on master too, so looks like something is probably wrong in my environment .... (I only updated from npe `0.1.5` for testing this PR) 

Here is error message from launching plugin dialog

```python-traceback
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/qt_main_window.py", line 311, in _show_pip_install_dialog
    self.plugin_dialog = QtPluginDialog(self._qt_window)
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/dialogs/qt_plugin_dialog.py", line 307, in __init__
    self.setup_ui()
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/dialogs/qt_plugin_dialog.py", line 377, in setup_ui
    self.plugin_sorter = QtPluginSorter(parent=self.h_splitter)
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/widgets/qt_plugin_sorter.py", line 274, in __init__
    for name, hook_caller in plugin_manager.hooks.items():
  File "/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/napari_plugin_engine/manager.py", line 876, in __getattribute__
    self._manager.discover()
  File "/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/napari_plugin_engine/manager.py", line 237, in discover
    path, entry_point, prefix
  File "/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/napari_plugin_engine/manager.py", line 191, in iter_available
    include_uninstalled=bool(self.discover_prefix),
  File "/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/napari_plugin_engine/manager.py", line 1085, in iter_available_plugins
    if name == prefix or (not name.startswith(prefix)):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Probably something simple, I'll trying looking more into too, sorry!!!

**Comment by tlambert03** [comment]
oh, actually, that looks like you have a package in your environment somewhere for which `importlib_metadata` can't even determine the name.   An unusual situation, perhaps, but a bug in npe nonetheless.  Will fix.

**Comment by sofroniewn** [comment]
Not sure if it is related to this PR, but when I open the dialog I get the following messages - sounds like it could be related to our error icon PR?

```
WARNING: Cannot open file ':/themes/dark/warning.svg', because: No such file or directory
WARNING:vispy:Cannot open file ':/themes/dark/warning.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/warning.svg', because: No such file or directory
WARNING:vispy:Cannot open file ':/themes/dark/warning.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/info.svg', because: No such file or directory
WARNING:vispy:Cannot open file ':/themes/dark/info.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/info.svg', because: No such file or directory
WARNING:vispy:Cannot open file ':/themes/dark/info.svg', because: No such file or directory
```

**Comment by tlambert03** [comment]
run `rm napari/resources/_qt_resources*` to regenerate your resources

**Comment by sofroniewn** [comment]
Functionality works great, and design looks good. Only comment there is we might want to hide the checkbox on the left until it does something - I know that's waiting on #1183 but for now might as well hide it, then a follow up PR can show it and enable the turning on and off.

I will go through code now, but I think we should be able to merge this soon, which will be a great addition!!

Can you also comment on the one failing test
```
E       AttributeError: module 'napari.plugins.pypi' has no attribute 'VERSION_CACHE'
```

**Review by sofroniewn — APPROVED** [review]
This looks good to me!

Last question is if we want to preserve the linedit box that is currently there in either its own dialog in the menubar or integrate a linedit box into the current one? 

Screen Shot 2020-09-14 at 2 30 54 PM

I guess one reason for having the lineedit box is that you could install whatever you want with it if you know its name, just to add dependencies. One reason you might want to do this in the bundled app is if we one day let you drag/ drop `.py` files into the app and run them, this would let you add dependencies without adding plugins. This might also be a reason though why not to enable this ...

Maybe for now we just keep both, that linedit could stay `Install/ Uninstall Package(s)` and then this new dialog could be `Install/ Uninstall Plugins(s)` and we can sort this out later. Thoughts @tlambert03 @jni?

**Comment by tlambert03** [comment]
I'm agnostic on the presence of the open-ended line edit.  I can see it being useful for the bundle, _and_ potentially problematic (particularly the uninstall part).  If we do keep it though, I think the two dialogs are too similar to have them both in the menu.  Probably rather just add it to the new dialog

**Comment by sofroniewn** [comment]
> I'm agnostic on the presence of the open-ended line edit. I can see it being useful for the bundle, and potentially problematic (particularly the uninstall part). If we do keep it though, I think the two dialogs are too similar to have them both in the menu. Probably rather just add it to the new dialog

Fair enough, agreed two dialogs is probably too confusing. I have a moderate preference towards keeping the lineedit, particularly now at the beginning when we don't know if the discovery mechanism will find everything etc, i could just see it coming in handy. We could add it in between the status and available plugins in this dialog. If it proves to be more trouble than it is worth or not needed then we could remove in the future. Happy to defer to @jni for a third opinion though.

**Comment by sofroniewn** [comment]
I'd love to get this PR merged as it adds a lot of really nice functionality. I've updated this PR to fix merge conflicts and a test which looks outdated and reviewed the code. It all looks good to me, and the functionality works as expected, but I'm running into one problem which is a seg fault after opening the new dialog only when launching with pythonw on a mac (which for me happens when I just launch `napari` from the command line)

```
/Users/nsofroniew/opt/anaconda3/bin/pythonw: line 3: 70931 Segmentation fault: 11  /Users/nsofroniew/opt/anaconda3/python.app/Contents/MacOS/python "$@"
```

I've confirmed that the problem occurs with the running of
```python
        # fetch available plugins
        self.worker = create_worker(iter_napari_plugin_info)

        def _handle_yield(project_info):
            if project_info.name in already_installed:
                self.installed_list.tag_outdated(project_info)
            else:
                self.available_list.addItem(project_info)

        self.worker.yielded.connect(_handle_yield)
        self.worker.finished.connect(self.working_indicator.hide)
        self.worker.start()
```

But I've been unable to make further progress. Any ideas or help here would be much appreciated. If we get this figured out then I think we can merge!

**Comment by sofroniewn** [comment]
hi @tlambert03, thanks for pushing the update! This will now close #1792 I think. 

I'm running into an error now though
```python-traceback
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/qt_main_window.py", line 376, in _show_plugin_install_dialog
    self.plugin_dialog = QtPluginDialog(self._qt_window)
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/dialogs/qt_plugin_dialog.py", line 290, in __init__
    self.setup_ui()
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/dialogs/qt_plugin_dialog.py", line 360, in setup_ui
    self.plugin_sorter = QtPluginSorter(parent=self.h_splitter)
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/widgets/qt_plugin_sorter.py", line 279, in __init__
    if not hook_caller.spec.opts.get('firstresult', False):
AttributeError: 'NoneType' object has no attribute 'opts'
```
which can be fixed by making it  `if hook_caller.spec and not hook_caller.spec.opts.get('firstresult', False):`, but I'm not sure if that will now lead to the desired behavior. It could be because I have a plugin that has a hook impl which isn't defined in this branch of napari (I'm using it in the very WIP #1800), but I'm not sure.

I'm also still running into the pythonw segfault described above, any tips or advice on how to fix that one would be deeply appreciated!

**Comment by tlambert03** [comment]
yeah, i'm still working on it (there are some other remaining issues as well).  will look at the pythonw issue.  
your issue above definitely seems unrelated to this and likely related to whatever you're doing with the hookspec (specifically, you might get that error if you're registering a hook implementation that doesn't have a hookspec?)

**Comment by sofroniewn** [comment]
> yeah, i'm still working on it (there are some other remaining issues as well). will look at the pythonw issue.

Thanks!!

> your issue above definitely seems unrelated to this and likely related to whatever you're doing with the hookspec (specifically, you might get that error if you're registering a hook implementation that doesn't have a hookspec?)

Yes, I think that's correct, its because i was making a plugin with a new hook implementation to test out #1800, but then when I switched back to this branch the hook spec wasn't there any more, but the plugin which is in another repo was still registered. I know this is a bit of a weird case, and am not sure if we want to raise a dedicated error somewhere else, but we might want to let that pass here somehow. I don't see this as being super common though

**Comment by tlambert03** [comment]
> I know this is a bit of a weird case, and am not sure if we want to raise a dedicated error somewhere else, but we might want to let that pass here somehow. I don't see this as being super common though

yeah, it's technically allowed within the plugin framework (to have an implementation without a spec) ... so it's a bug in the plugin_sorter and shouldn't raise an error.

**Comment by tlambert03** [comment]
cleaned things up, this is ready enough (can polish it up later).  @sofroniewn, I haven't been able to reproduce the segfault on two different computers/environments.  I confirmed that it was indeed using the `pythonw` executable ... but can't get it to happen.  might need some more info on that.  also, have you tried a clean environment?

**Comment by sofroniewn** [comment]
> cleaned things up, this is ready enough (can polish it up later). @sofroniewn, I haven't been able to reproduce the segfault on two different computers/environments. I confirmed that it was indeed using the pythonw executable ... but can't get it to happen. might need some more info on that. also, have you tried a clean environment?

pythonw is working for me in a clean env, with both pyside2 and pyqt5. I think it's fine to merge and press on, sorry for not checking that sooner!

Ok I think this is good to go, I love the little loading gif, very nice!!

Screen Shot 2020-10-31 at 5 19 27 PM

I'll wait till tomorrow morning my time to merge, but let me know if you want more time to do anything else on it etc

**Comment by tlambert03** [comment]
> but let me know if you want more time to do anything else on it etc

nope, good by me.

**Comment by tlambert03** [comment]
oh, one problem I found (for later PR to follow up on): there might be an issue with the subprocess environment when installing plugins that need to build wheels... such as lazy-openslide. (don't know why yet... but wanted to note that)

**Comment by sofroniewn** [comment]
> there might be an issue with the subprocess environment when installing plugins that need to build wheels... such as lazy-openslide. (don't know why yet... but wanted to note that)

Ah yes, i was unable to install `napari-lazy-openslide` - good to note, can be for a followup

**Pull request merged**
