### PR TITLE
use npe2api in plugin install dialog

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This PR uses [npe2api](https://github.com/napari/npe2api) for the builtin plugin installer

discussed a bit last night with @jni, @sofroniewn, and @neuromusic 

See more about npe2api in the readme linked above.   This is a dramatically faster way to fetch info due to the pre-indexed summary here: https://npe2api.vercel.app/api/summary.  It also includes availability at conda forge, which is pre-fetched and stored in the npe2api repo.  There is still a lag when loading plugins, but it's mostly caused at this point by running the `filter` command in the plugin widget after every single plugin is added: this can be changed in a future PR, but I don't want to do it here as it would have more impact on the hub-based api.

@goanpeca and @jaimergp, you might be interested in the conda endpoints now available there:
- https://npe2api.vercel.app/api/conda is a mapping of pypi plugin name to `conda_channel/package_name`
- and for any key that has a value in that map, you can get the full conda info at `/api/conda/pypi_name` for example: https://npe2api.vercel.app/api/conda/napari-animation

### CODE REVIEW

**Comment by jaimergp** [comment]
This is awesome @tlambert03! Thank you so much! I am sure @goanpeca will love it.

One question about the `/api/conda/<pypi_name>` endpoint: how do you populate this database? From the anaconda.org API or are you fetching the CDN'd repodata.json? Asking because we need to account for repodata patches, which might not appear on anaconda.org API responses.

**Comment by neuromusic** [comment]
quick question on conda support:

Does npe2api assume that the conda-forge package name is the same as the PyPI name? Are other conda channels supported?

When we added conda support to the napari hub API per @goanpeca's request, we made sure to give plugin devs a way to specify other naming conventions (and other conda channels): https://github.com/chanzuckerberg/napari-hub/issues/464

**Comment by tlambert03** [comment]
>  how do you populate this database? From the anaconda.org API or are you fetching the CDN'd repodata.json? 

yeah, currently from the API.  You can [see that code here](https://github.com/napari/npe2api/blob/e239ea3f9c835734cacb073c427ba92de86b33a1/scripts/reindex.py#L40-L52), and feel free to suggest changes.  More than happy to incorporate them

**Comment by tlambert03** [comment]
> Does npe2api assume that the conda-forge package name is the same as the PyPI name? 

Not exactly, but it currently [searches](https://github.com/napari/npe2api/blob/e239ea3f9c835734cacb073c427ba92de86b33a1/scripts/reindex.py#L47) for 1) an exact name match, 2) lowercase with delimiters as dashes 3) lowercase with delimiters as underscores

The resulting map (from pypi name to `conda_channel/conda_name`) is then available at https://npe2api.vercel.app/api/conda

> Are other conda channels supported? ... we made sure to give plugin devs a way to specify other naming conventions

currently, I'm only searching on `conda-forge`,  It would be trivial to add support for plugins to directly provide a conda channel and conda name... but I think that information should probably go in a standard ecosystem file like `pyproject.toml` or in the manifest itself `napari.yaml`

**Comment by tlambert03** [comment]
> When we added conda support to the napari hub API per @goanpeca's request, we made sure to give plugin devs a way to specify other naming conventions (and other conda channels): [chanzuckerberg/napari-hub#464](https://github.com/chanzuckerberg/napari-hub/issues/464)

also, looks like no one has implemented this yet ...
https://cs.github.com/?scopeName=All+repos&scope=&q=path%3A.napari%2Fconfig.yml+%22conda%22
https://cs.github.com/?scopeName=All+repos&scope=&q=path%3A.napari-hub%2Fconfig.yml+%22conda%22

so perhaps now is a good time to not add that to `.napari` but rather to something non-hub specific

**Comment by jaimergp** [comment]
There are some pypi<->conda-forge mappings already out there, in case you need to use them:

* https://github.com/regro/cf-graph-countyfair/blob/master/mappings/pypi/grayskull_pypi_mapping.yaml
* https://github.com/conda-incubator/grayskull/blob/main/grayskull/strategy/config.yaml

**Comment by tlambert03** [comment]
> There are some pypi<->conda-forge mappings already out there, in case you need to use them:

thanks @jaimergp ... I just did a double check to see if grayskull had any of the keys that did _not_ find a conda package using the simple heuristic [mentioned above](https://github.com/napari/napari/pull/4893#issuecomment-1202841769), but nothing showed up.  So it looks like at this point, we're probably successfully finding every plugin that actually has a conda equivalent.

**Review by liu-ziyang — APPROVED** [review]
The code change here to replace pypi API with npe2api seems reasonable to me. I am interested to explore potential collaboration between hub API and npe2api in the future

**Comment by tlambert03** [comment]
I'll merge this in a day or so unless anyone requests more time to review

**Pull request merged**
