### PR TITLE
[WIP] Tiled labels painting

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR contains #2403 (which should be merged first) and will allow for painting into a single scale tiled image. Right now it triggers redraw on all the tiles in the current field of view, so if you are zoomed out it is slow, but if you are zoomed in then it is very fast, and independent of the size of the image. We can try being more clever about this too, but ultimately this should allow painting into very large images like many people want!

### CODE REVIEW

**Comment by sofroniewn** [comment]
Ok, I have been able to get this working by disabling some cleanup stuff. It's def not ready to merge, but it does fundamentally work.

For too big to fit in RAM data we can use tensorstore like @DragaDoncila and @jni did as follows

```python
"""
Painting on an image pyramid of pathology slide
"""
import os
import tensorstore as ts
import numpy as np
import dask.array as da
import napari
import zarr

file_name = './data/camelyon16/tumor_001.zarr'
labels_file = './data/camelyon16/tumor_001_annotation.zarr'
pyramid = [da.from_zarr(file_name + '/' + str(i)) for i in range(10)]

if os.path.exists(labels_file):
    labels_temp = zarr.open(labels_file, mode='r')
    metadata = {
            'dtype': labels_temp.dtype.str,
            'order': labels_temp.order,
            'shape': labels_temp.shape,
            'chunks': labels_temp.chunks,
            }
else:
    metadata = {'dtype': '<u4',
                'shape': pyramid[0].shape[:-1],
                'order': 'C',
                'chunks':(64, 64),
                'compressor': {'id': 'blosc'}}


dir, name = os.path.split(labels_file)
labels_ts_spec = {
    'driver': 'zarr',
    'kvstore': {
    'driver': 'file',
    'path': dir,
    },
    'path': name,
    'metadata': metadata,
}

labels = ts.open(labels_ts_spec, open=True, create=True).result()

# create an empty viewer
viewer = napari.Viewer()

# add the pyramid
viewer.add_image(pyramid, name='slide')
viewer.add_labels(labels, name='annotations')
viewer.camera.zoom = 0.5
viewer.layers[1].display.show_grid = False
napari.run()
```

and then paint into it

Screen Shot 2021-03-16 at 9 17 35 PM

After we get #2403 merged this PR will be easier to work with

**Comment by sofroniewn** [comment]
I've cleaned up the diff. This PR still has some work to do though around performance.

I'll also note that the multilayer/ multichannel performance is still suboptimal. That's maybe a separate issue, but I'm noting it here now too

**Review by Carreau — APPROVED** [review]

**Comment by DragaDoncila** [comment]
Pulled this down and had a play just then - working great for me!

**Comment by sofroniewn** [comment]
Nice! It still needs a little clean up, right now we're not throwing away unseen chunks anymore, there was an issue with multiple layers that broke things with that code still in place, so i'd like to look into cleaning up a couple loose ends before merge

**Comment by sofroniewn** [comment]
This approach of removing the cancel of unseen hurts performance. We should instead fix the issues described in #2862 and then revisit this work

**Pull request closed without merging**
