### PR TITLE
Directly set author of commit in vendored workflow

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR set direct author of a commit in vendored update workflow to avoid assigning random users to commits. 

obraz

### CODE REVIEW

**Review by Carreau — APPROVED** [review]

**Comment by Carreau** [comment]
Marking as ready-for-merge as this does not touch napari API.

**Comment by psobolewskiPhD** [comment]
I added label and milestone, but the check still fails (re-ran it to be safe)?

**Comment by Carreau** [comment]
> I added label and milestone, but the check still fails (re-ran it to be safe)?

I think the checker looks for the value of the _event_ not the actual one on the PR, so rerunning does not help. So you often need to remove the label and re-add it for it to work.

**Comment by Czaki** [comment]
> I think the checker looks for the value of the _event_ not the actual one on the PR, so rerunning does not help. So you often need to remove the label and re-add it for it to work.

This is true, but this allows us to not maintain the separate script.

**Pull request merged**
