### PR TITLE
Add QtViewerPushButton to qt public interface

### PR DESCRIPTION
**Pull request by Czaki**
# Description
Add QtViewerPushButton to qt public interface. 
## Type of change

- [x] New feature (non-breaking change which adds functionality)

# References

# How has this been tested?

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Comment by Czaki** [comment]
Maybe all button should be importable from `napari.qt`

**Comment by sofroniewn** [comment]
> Maybe all button should be importable from napari.qt

I'm really not sure about this. Things were made private intentionally because we didn't want to guarantee API stability around things that might be rapidly evolving. Rather than just make things public now, if we are serious about this we should go through and carefully evaluate what classes we want to expose and for what reasons and clean things up.

Thoughts @jni?

**Comment by tlambert03** [comment]
@Czaki, can you comment on why you want them?  They're just _very_ thin wrappers around `QPushButton`... do you want to instantiate a button?  or are you wanting it for an `isinstance` check?

**Comment by Czaki** [comment]
@tlambert03 To got same icons to control viewer as napari. Napari qss is connected with its name. Of course I can create class with same name, but it may case some stupid fail in future (connected with refactoring of napari code).

**Comment by tlambert03** [comment]
so it's about styling?  and what are you hoping to gain by having it be public?  is it that you want your program to fail quickly if we change the name (so that you can fix it), or is it that you _don't_ want the name to be changed... and by making it public you hope it will be less likely?

**Comment by Czaki** [comment]
> is it that you want your program to fail quickly if we change the name (so that you can fix it),

Exactly this. This can be found using automated test. 

So I can still import it from private module. But it is not best practices to use private part of third party packages.

**Comment by tlambert03** [comment]
> But it is not best practices to use private part of third party packages.

yes this is of course true, but that is an implicit contract more than an unbreakable rule.  And in this case, we didn't make it public for exactly the reason that we don't _want_ to give the impression that it's stable.  If all you want is a quick error message for an automated test, then you should feel free to import the private class.  It will serve the same purpose for you whether it's private or not, but if we make it public, then _napari_ is making a statement about stability.

I think a better longterm plan is to move away from class-name based qss selectors, and decide on `#objectName` conventions instead... though that of course requires some agreement

**Comment by Czaki** [comment]
Ok. So I close this PR.

**Comment by tlambert03** [comment]
I do think this would make for a good issue though, if you'd like to open one.  We definitely should have a conversation about what the napari "style API" might look like, and it would be nice to keep this on the radar

**Comment by Czaki** [comment]
@tlambert03 #1332

**Pull request closed without merging**
