### PR TITLE
Pin PySide2 and PyQt5 at <5.15

### LINKED ISSUE #1312: Pyside 5.15.0 breaking buttons?
## 🐛 Bug

just found that all instances of `QtModePushButton` weren't working for me.  (like the "add layer" buttons)
Screen Shot 2020-05-29 at 11 13 35 AM

I had pyside 5.15.0 in my environment, and downgraded to 5.14.2 and they worked again...

Can someone else confirm this? 

If so... we should probably release a patch that pins pyside2 < 5.15

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
We need to do some more testing on Qt 5.15 before we open it up in our requirements.  Definitely some things broken at the moment (though tests are passing)

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References
https://www.qt.io/blog/qt-for-python-5.15.0-is-out

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jni** [comment]
I guess we want to fix this on our end and then it doesn't matter if it's `<` or `!=`. BUT, if we do want to fix this on our end, then we should remove the "fixes #" above. =)

**Comment by jni** [comment]
And if we would rather wait and see, then we should do `!=`

Either way we should probably add a test for this... Would that be hard? Sorry I am a noob at the Qt testing stuff...

**Comment by tlambert03** [comment]
it's actually quite tricky to test!  The strange thing is that the button does not seem to be emitting a signal when clicked, but let me try to mock it.  might take some time, so I'll do it in another PR, and this one can go in

**Comment by tlambert03** [comment]
yeah: `napari/_qt/_tests/test_qt_buttons.py::test_push_button` _should_ be catching this but it doesn't ... might need to actually mock a click at a specific part of the screen

**Comment by tlambert03** [comment]
oh man... if you programmatically run `viewer.window.qt_viewer.layerButtons.newPointsButton.click()`, it adds a points layer... but actually clicking on it has no effect.

**Review by sofroniewn — APPROVED** [review]
LGTM! Will merge with approval in zulip from @jni too

**Pull request merged**
