### PR TITLE
Fixes broken tutorials links

### PR DESCRIPTION
**Pull request by HagaiHargil**
# Description
Fixes broken links in the README.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Review by kne42 — APPROVED** [review]
Nice catch, thanks for the fix!

**Comment by tlambert03** [comment]
while we're editing the readme... we might want to update the **installation** section to mention python 3.8?  Can you do that @HagaiHargil ?

**Comment by kne42** [comment]
oh and could you also change all instances of `napari.github.io` to `napari.org` please? I'll update the website once this is merged :)

**Review by sofroniewn — APPROVED** [review]
Looks good to me, I will merge

**Pull request merged**
