### PR TITLE
Refine and cleanup DeprecationWarnings.

### PR DESCRIPTION
**Pull request by Carreau**
1) all warnings should mention a version, either since when things are
   deprecated, or when they will be removed. Otherwise they are not
   actionable by users or future devs without looking through git
   history, which nobody does and then get never cleaned up.

2) Things that we say we would removed have not been removed, and thus
   removing them.

(2) seem to indicate that in (1) we should not try to say things about
the future, and it's better to use version when things are deprecated as
this is factual and we can change our mind

### CODE REVIEW

**Comment by andy-sweet** [comment]
Thanks for pushing this towards some consistency @Carreau !

I think we only just pushed a change that ensure that `DeprecationWarnings` are issued in napari? So I'm a little worried that we're removing some things without warning to some people.

Also, one other thing that comes to mind is that targeting removal of deprecated things in patch versions seems aggressive - given napari's current version numbering, I'd prefer to target minor version changes. And I think we should try to include the target version of removal. So maybe we can delay the removals until 0.5?

Also, I think we're trying to follow the numpydoc style guide (though I'm not sure), in which case we may also want to consistently update the docstrings to include a deprecation note. Though this seems like a lower priority.

**Comment by Czaki** [comment]
> (2) seem to indicate that in (1) we should not try to say things about
> the future, and it's better to use version when things are deprecated as
> this is factual and we can change our mind

I do not agree. For me as a plugin maintainer who would like to support more than one napari version, it is really important until which version of napari my code will work. It allows me to plan when I need to focus on updating my plugin.

**Comment by Carreau** [comment]
> I think we only just pushed a change that ensure that `DeprecationWarnings` are issued in napari?

I'm not even sure this has been done yet. 

> [...] Deprecated things in patch versions seems aggressive [...]

We had much bigger changes in patch versions, maybe it's time to do less patch release and more minor ones? Napari 0.4.0 was released in 2020...

> I do not agree. For me as a plugin maintainer who would like to support more than one napari version, it is really important until which version of napari my code will work. It allows me to plan when I need to focus on updating my plugin.

Well then we should stick to the removal plan. And then I think the information of since when it is deprecated is as useful if not more, because by the time we publish napari 0.6.31, if you see "foo is deprecated in favor of bar and removed in 0.6.61", you have no clue since when it's deprecated and since when bar is avail. So really you want:

1) since when things get deprecated. 
2) since when the replacement is available.
3) Potentially when the deprecation will become an error.

My comment of these three, most of the time 1 and 2 are the same, and when people include 3 in the message most of the time it is not respected. See for example what is in this PR with multiple things marked as removal several versions ago. 

I think a good middle ground is to have a clear deprecation policy (say deprecated features stay for **at least** X minor versions). That way you can state something factual (deprecated since Y), and provide guarantees to consumers. 

For napari, I don't particularly care as long as every deprecation warning have a version somewhere, for either deprecation or removal.

**Comment by Czaki** [comment]
If we assume that everything is deprecated until the next major release and one release before the major release we do not deprecate anything I will agree. But a common thing in napari history was deprecating things in minor releases. 



> My comment of these three, most of the time 1 and 2 are the same, and when people include 3 in the message most of the time it is not respected.

Good example of deprecation without replacement is `_qt_viewer`.

And as I remember most of the deprecations that touch me was respecting the time of removal.

**Comment by Carreau** [comment]
https://github.com/napari/napari-console/pull/19 will need to be released first, as the warnings were silenced.

**Comment by Carreau** [comment]
Let's start with #4757 that only contains update to messages to add "since X.y.z", that should be non-controversial.

**Comment by tlambert03** [comment]
> > [...] Deprecated things in patch versions seems aggressive [...]

> We had much bigger changes in patch versions, maybe it's time to do less patch release and more minor ones? Napari 0.4.0 was released in 2020...

yeah, definitely.  though we three numbers and two dots, our versioning has almost zero semantics :joy:. i'm in favor both of just deprecating things in patch releases (if we stick with our current version bumping hesitations) and being more willing/less scared of minor releases

**Comment by sofroniewn** [comment]
I have now merged #4757 to keep this going. @Carreau if you can clean up and fix merge conflicts that would be great. It would be nice to get this in, including dropping the deprecated API.

First thing in the Readme is

> We're developing napari in the open! But the project is in an alpha stage, and there will still likely be breaking changes with each release.

and I feel like we've worked very hard to have give these warnings the past two years, but we have to still keep moving forward

**Pull request closed without merging**
