### PR TITLE
Move the docs downloading screenshots to LFS

### PR DESCRIPTION
**Pull request by DragaDoncila**
# Description
@jni this PR adds the three recently committed pngs to LFS. It doesn't rewrite history (obviously), but it at least changes them to pointers from now on. 

I think I did it right? I just added them to `git lfs` and then made sure they were listed in `git lfs ls-files` 🤷‍♀️ 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
Hmmm something seems to be wrong — it should also say "LFS file not shown" in the diff. But I would not be shocked *at all* to find that GH doesn't render a normal->LFS move correctly. Will check this out locally later today to make sure it works properly for me.

**Comment by Carreau** [comment]
That seem correct to me:

```bash
$ cat <(find . -name '*.png'|sed 's/\.\///g') | grep -v -f <(git lfs ls-files -n | grep '.png'|sort )
napari/resources/logo.png
```

**Review by jni — APPROVED** [review]
Yup, checked this out and it works...

Why is the CI broken though?

**Comment by jni** [comment]
Ok, the failing docs issue is caused by #4995, so I'm going to merge. I guess the rest aren't running because no non-docs files are touched. Neat!

**Pull request merged**
