### PR TITLE
PR: Remove extra box on plugin dialog

### LINKED ISSUE #3232: Remove extra search box on plugin dialog
## 🚀 Feature

Now that plugin dialog is uniform in displaying packages on both installed and non-installed plugins, we could move to use a singe search box.

Screen Shot 2021-08-24 at 1 50 45 PM

## Motivation

Simplify UI :) 

## Pitch

No need for two separate boxes if we can filter using a single one #2345 

## Additional context

Thanks @Carreau for suggesting this on the dev meeting!

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Fixes https://github.com/napari/napari/issues/3232

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

napari

### CODE REVIEW

**Review by tlambert03 — COMMENTED** [review]
looks good to me.  but I wonder if the LineEdit should now on its own line above Installed Plugins, with a label that says "Search plugins" or something.  (as it is, it looks like you'd be searching the installed plugins)

**Review by tlambert03 — APPROVED** [review]

**Comment by goanpeca** [comment]
>but I wonder if the LineEdit should now on its own line above Installed Plugins, with a label that says "Search plugins" or something. (as it is, it looks like you'd be searching the installed plugins)

Indeed, this does not need to go for 0.4.11, we can ask for design feedback on the issue :)

**Comment by sofroniewn** [comment]
> Indeed, this does not need to go for 0.4.11, we can ask for design feedback on the issue :)

Yeah i might go even further and just make one box list/ that had all plugins with installed ones on top? Not sure if others thing that's good/ bad - but let's give this one a bit more thought before merge

**Comment by goanpeca** [comment]
An option changing the wording to `filter...`

Screen Shot 2021-08-25 at 11 23 54 AM

**Review by Carreau — APPROVED** [review]
+1 we can refine further later.

I'm even wondering if we could have a single List with both installed and installable ListItems. There is a strong enough visual distinction (checkbox, + button color and text) and AFAIU they won't appear in both list anyway right ? But that can be for later if we agree on it.

**Comment by sofroniewn** [comment]
> I'm even wondering if we could have a single List with both installed and installable ListItems. There is a strong enough visual distinction (checkbox, + button color and text) and AFAIU they won't appear in both list anyway right ? But that can be for later if we agree on it.

Yup I agree here too.

Ok sounds like there's a lot of consensus to merge this though. I'll make a call depending on if we need to make new rc or not (if yes, i will merge)

**Pull request merged**
