### PR TITLE
CI: loosen min scipy requirement.

### PR DESCRIPTION
**Pull request by Carreau**
Otherwise min-requires CI fails

### CODE REVIEW

**Comment by tlambert03** [comment]
See also #4310.  Didnt dig into test fails there yet though

**Comment by Carreau** [comment]
Ah, sorry I skmmed PR but missed it. closing.

**Comment by Carreau** [comment]
I can't push on #4310 so reopening here to test some things.

**Comment by sofroniewn** [comment]
I just merged #4310 as it seemed a good step, you can keep iterating here though to fix everything

**Comment by Carreau** [comment]
This now remove meshzoo, I think an alternative would be #4325

**Comment by Carreau** [comment]
Note, I asked there `https://github.com/meshpro/meshzoo/issues/93` is the removal of older meshzoo packages was purposefull.

**Comment by tlambert03** [comment]
This approach would probably be my preference

**Comment by Carreau** [comment]
the author re-published meshzoo 0.9.9, but 0.9.9 also have a min numpy of 1.20.0

**Comment by brisvag** [comment]
I added meshzoo for just a couple examples a while back; It's not that important and can probably be replaced by something else, since all it does is generate a sphere mesh in both examples. I would rather drop that than mess up our numpy deps!

**Comment by sofroniewn** [comment]
> I added meshzoo for just a couple examples a while back; It's not that important and can probably be replaced by something else, since all it does is generate a sphere mesh in both examples. I would rather drop that than mess up our numpy deps!

Yeah we can hardcode a sphere mesh. I'd rather do that than drop the examples entirely. I think my preference here would be dropping meshzoo, but replacing their mesh in the examples with another mesh. We could even use skimage to generate the mesh from a sphere - see https://scikit-image.org/docs/dev/auto_examples/edges/plot_marching_cubes.html.

Maybe longer term we could add a mesh to skimage data - that would be cool cc @jni @grlee77

**Comment by Carreau** [comment]
closed by #4329

**Pull request closed without merging**
