### PR TITLE
Move Labels utility functions to labels_util.py

### PR DESCRIPTION
**Pull request by kevinyamauchi**
# Description
As discussed in #761, this PR moves the `interpolate_coordinates()` from /napari/util/misc.py to napari/labels/labels_utils.py and adds a test for `interpoloate_coordates()`. This refactor moves the `interpolate_coordinates()` into a more clearly named file and closer to the code that depends on it.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# References
This is the first of a series of PRs addressing #761 

# How has this been tested?
- [x] Added a test for `interpolate_coordinates()` in `/napari/layers/labels/tests`
- [x] Tested `/examples/add_labels.py` and `/examples/nD_labels.py`

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Looks great! Love the added test. I will let sit a little in case anyone has any additional requests and will then merge. I know you have a bunch of PRs planned so I don't want to let each one sit too long to create backup, so if @kne42 or @jni took a quick look too at some point that might be nice

**Review by sofroniewn — COMMENTED** [review]
Minor comment @kevinyamauchi I think we tend to use `util` instead of `utils`, i.e. see `shape_util.py` instead of `shape_utils.py` and here you have gone with `labels_utils.py`. I actually may prefer `utils`, but regardless we should be consistent. What do @jni and @kne42 think?

**Comment by sofroniewn** [comment]
We should probably also have it be `shapes_util(s).py` instead of `shape_util(s).py` for consistency too, so clearly we have some naming consistency issues across the board.

**Comment by jni** [comment]
LOL I am totally indifferent to the conventions discussed above. =)

**Comment by jni** [comment]
Too easy! Thanks for the tiny, self-contained PR, @kevinyamauchi! afaic this is ready to be merged.

**Review by jni — APPROVED** [review]

**Comment by sofroniewn** [comment]
:-) I’ll let @kevinyamauchi respond and pick the convention and then merge

**Comment by kevinyamauchi** [comment]
Thanks for the reviews, @jni and @sofroniewn ! I have a slight preference for `*_utils.py`, so I will keep that :). I will add a note in #761 to update `shape_util.py` to `shapes_utils.py`.

**Pull request merged**
