### PR TITLE
add logo

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR adds a png of the napari logo to the repo

### CODE REVIEW

**Comment by sofroniewn** [comment]
logo

**Review by jni — APPROVED** [review]

**Comment by sofroniewn** [comment]
I've got the svg now @jni - should I add that too?

**Comment by sofroniewn** [comment]
the svg has the text in it - i could delete the text, or might as well just keep it, or we go without the svg. i don't mind

**Comment by jni** [comment]
Let's keep the text, no big deal to remove it later if needed.

**Comment by jni** [comment]
Actually, I just saw that it's 1MB! Yikes! Let's not put it in yet. =\

**Comment by sofroniewn** [comment]
Ok, will merge this without the svg version of the logo, just the png - thanks @jni

**Pull request merged**
