### PR TITLE
Add toggle status view menu items

### PR DESCRIPTION
**Pull request by lucyleeow**
# Fixes/Closes

Ref: https://github.com/napari/napari/pull/4826#discussion_r989734035

# Description

Adds toggle status to view menu items: `Toggle Play`, `Toggle Fullscreen` and `Toggle Menubar` . These were not added as part of view menu app model migration PR as they did not exist in main and thus decided to be out of scope of that PR

# References

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Maintenance (changes required to run napari, tests, & CI smoothly)
- [ ] Enhancement (non-breaking improvements of an existing feature)
- [ ] Documentation (update of docstrings and deprecation information)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by DragaDoncila — APPROVED** [review]
Thanks for this one @lucyleeow. Can confirm `Toggle Play`, `Toggle Fullscreen` and `Toggle Menubar` are now showing the checkmarks in the menu as expected on Mac and Ubuntu (didn't check Windows). Can you please update the description to mention these three items specifically, as some of them e.g. the axes already had the `ToggleRule`s so they haven't changed.

**Comment by lucyleeow** [comment]
@DragaDoncila is this ready to go in?

**Comment by lucyleeow** [comment]
mypy error fixed by #6230

**Comment by DragaDoncila** [comment]
@lucyleeow yep, I've added the ready-to-merge label and will merge in 24 hours!

**Comment by melonora** [comment]
There is currently a test failing due to `_pref_dialog` being able to be `None` in which case `_list` does not exist. See fix for this [here #6216](https://github.com/napari/napari/pull/6216/files#diff-bba32f24d9521c1fd114e940534c88a661d3f3400db6c153ba296cc4f2a866b3)

**Review by psobolewskiPhD — APPROVED** [review]
Makes sense to me, thanks.

Note: testing this did remind me of that on macOS we get double Full Screen toggle in the View menu, which I'd previously reported.
https://github.com/napari/napari/issues/5092#issuecomment-1252882551
It's wierd.

Here, toggling the native macOS full screen don't trigger the check-mark toggle status.
Very niche case, doubt anything can be done about it here.

**Comment by psobolewskiPhD** [comment]
I *very* rarely use full screen, so hard for me to say. 
But native macOS, the bottom one `Enter Fullscreen`, doesn't get a check, instead it switches to `Exit Fullscreen`.
This works in napari too.
But the napari fullscreen doesn't know that happened? 
As noted in the other issue, I don't get where that extra native menu item comes from. But it's there, so maybe best to just hide the non-native one on macOS.

**Comment by lucyleeow** [comment]
> so maybe best to just hide the non-native one on macOS.

Good idea, we can do that with 'when', I will open an issue for that to keep track.

**Comment by DragaDoncila** [comment]
Yep, agreed - we should just hide the non native option on Mac. Looks like the test failure here is a timeout

**Comment by lucyleeow** [comment]
I'll put up a PR for https://github.com/napari/napari/issues/6240, hopefully an easy fix

**Comment by psobolewskiPhD** [comment]
> I'll put up a PR for #6240, hopefully an easy fix

Had me very confused...
```
╰─ gh pr checkout 6240                                           (napari-dev) ─╯
GraphQL: Could not resolve to a PullRequest with the number of 6240. (repository.pullRequest)
```
That's no PR, that's an issue!
🤣

**Comment by lucyleeow** [comment]
Weird 6240 seems the right number for me:

image

**Pull request merged**
