### PR TITLE
documentation fix for #3792

### PR DESCRIPTION
**Pull request by keredson**
# Description

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
https://github.com/napari/napari/issues/3792

# How has this been tested?
doc change - no testing needed

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] [n/a] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] [n/a] I have added tests that prove my fix is effective or that my feature works
- [ ] [n/a] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by sofroniewn** [comment]
Hi @keredson, thanks for starting this PR! We've actually just trimmed down some of the details on installation in the readme (see #3833) and so this might actually belong in our more detailed installation tutorial at https://napari.org/tutorials/fundamentals/installation.html. What does @GenevieveBuckley think?

**Comment by tlambert03** [comment]
actually, sorry I missed this one.  This is something we discussed and are not going to merge.  See https://github.com/napari/napari/issues/3792 for discussion

**Comment by keredson** [comment]
@sofroniewn nice!  a note:

> While not strictly required, it is highly recommended to install napari into a clean virtual environment using an environment manager like conda or venv.

i'd consider revising this to say "conda or another venv is required", since it's known to not work without and as a project it's been decided not going to fix or document.  making the conda requirement explicit will save time/confusion.

similarly:
> Python package distributions of napari can be installed via pip, conda-forge, or from source.

should be "can be installed via pip (via conda-forge), or from source" to make it clear it's not "pip or conda/forge".

**Comment by tlambert03** [comment]
I'd say "unsupported" rather than required. As you found, it's possible, and others have installed napari on embedded systems without a virtual env.  So it's not required.  But each non isolated environment will come with its own needs, as you found

**Pull request closed without merging**
