### PR TITLE
[WIP] Remove `tqdm` inheritance from `progress` objects

### LINKED ISSUE #2940: Refactor progress bars to not inherit from `tqdm`
Many of the issues we've been seeing with tests are a result of the ProgressBar widgets leaking and not being tightly coupled with the viewer.

While working on #2931 and #2656 it's become evident that at least part of the complexity lies in `tqdm` and its complex refresh logic. We can maintain most if not all of the functionality we currently have without inheriting from `tqdm`. I think this will give us more control over the ProgressBars, and also give us a chance to more tightly couple the viewer and ProgressBars to avoid some of the issues we've been seeing.

### PR DESCRIPTION
**Pull request by DragaDoncila**
# Description
As proposed in #2940 this PR decouples our `progress` object from `tqdm` while maintaining the vast majority of the functionality and without changing the public interface to the object.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# References
Closes #2940

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by sofroniewn** [comment]
I have now merged #2656 can you rebase this @DragaDoncila to include those changes, then i think this will be ready for review right?

**Comment by DragaDoncila** [comment]
@sofroniewn I've merged changes from master but will still need to do a bit of tidy up and fix one of the threading tests before this is ready for review. I should have this done tomorrow morning Australia time.

**Comment by sofroniewn** [comment]
See some discussion here https://github.com/sofroniewn/waver/pull/5#discussion_r666692376 in might actually be nice to keep the tqdm behavior as originally conceived

**Comment by DragaDoncila** [comment]
> See some discussion here [sofroniewn/waver#5 (comment)](https://github.com/sofroniewn/waver/pull/5#discussion_r666692376) in might actually be nice to keep the tqdm behavior as originally conceived

following this discussion, and some further brainstorming/discussion with @jni , I will pause progress on this (heh) until we decide on a longer term vision for the progress bar architecture.

**Comment by jni** [comment]
Closing in favour of #3439

**Pull request closed without merging**
