### PR TITLE
Bump napari console to ensure users get latest bug fixes

### PR DESCRIPTION
**Pull request by brisvag**
# Description
`napari-console` received several updates and bug fixes lately, but we didn't bump the requirement here in napari. While not stricly *required*, these bug fixes are nice to have and might fly under the radar especially for those who like me mostly use the main branch and don't constantly do a full update of the deps. (see #6436 #6437)

The risk of conflicts arising from this is basically zero, given that no one other than napari is likely to depend on napari-console.

cc @Czaki

### CODE REVIEW

**Comment by brisvag** [comment]
@napari-bot update constraints.

**Comment by Czaki** [comment]
I think that update constraints is obosolete

**Review by Czaki — APPROVED** [review]

**Comment by brisvag** [comment]
> I think that update constraints is obosolete

What do you mean? I missed some new trick? :)

**Review by psobolewskiPhD — APPROVED** [review]

**Comment by Czaki** [comment]
> What do you mean? I missed some new trick? :)

We do not have an upper bound on constraints files. So, constraints files already point to `napari-console==0.0.9`

Regenerate constraints are required when you change the upper bound or update the list of banned (`!=`) releases.

**Pull request merged**
