### PR TITLE
Do not clone repository to subdirectory in examples test

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Test of examples starts failing as tox no longer discover tox.ini in a subfolder and/or do not allow non-defined environments

https://github.com/tox-dev/tox/pull/3089

### CODE REVIEW

**Comment by brisvag** [comment]
IIRC the subdirectory thing was in order to ensure it was indeed the recently pulled code that was being used correctly... Is that not a concern here? Or maybe I'm getting confused :P

**Comment by Czaki** [comment]
> IIRC the subdirectory thing was in order to ensure it was indeed the recently pulled code that was being used correctly... Is that not a concern here? Or maybe I'm getting confused :P

All other tests are performed without cloning to subdirectory. Also, test on the main branch (comprehensive) are done without it. For me it looks like unnecessary complexity. 

Other possible workarounds is to run test from subdirectory (change invoke command)

**Comment by brisvag** [comment]
I guess it's fine then :shrug:

**Review by brisvag — APPROVED** [review]

**Comment by Czaki** [comment]
Could I merge it without waiting?

**Comment by jni** [comment]
@Czaki did you miss a line maybe?

Screenshot 2023-08-22 at 11 01 27 pm

Anyway, it looks like it was added in #5439. I'm not sure why — the previous usage was in the pip install section because installing with git+https: would pull down LFS files.

**Comment by Czaki** [comment]
I miss. But the test are at least working :P

I will fix it in #6156

**Pull request merged**
