### PR TITLE
Better bound magicgui viewer

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This PR would take advantage of much improved parameter binding behavior from https://github.com/napari/magicgui/pull/95/

The behavior would be that when someone annotates a magicgui function with `(viewer: napari.Viewer)` no widget is shown (by default) and the `widget.viewer` parameter will use a callback to find its viewer necessary (returning `None` if the widget has not been added as a dock widget)

Tests will fail until magicgui 0.2.5 ... but we might want to make sure there are no lingering issues in the 0.4.3rc0 that need addressing as well

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
This seems reasonable, can you add a simple `example/magic_with_viewer.py` or something similar that someone can run to see this in action - doesn't have to do anything fancy.

**Comment by tlambert03** [comment]
> This seems reasonable, can you add a simple `example/magic_with_viewer.py` or something similar that someone can run to see this in action - doesn't have to do anything fancy.

added

**Review by sofroniewn — APPROVED** [review]
Great! I'm approving now, but we should wait till the `0.2.5` release to merge. I'm feeling pretty good about that so would say go ahead whenever. We should also add a release note to this. I can do it before merge

**Comment by tlambert03** [comment]
@sofroniewn, working now

**Comment by sofroniewn** [comment]
Release note added, will merge after tests pass!

**Pull request merged**
