### PR TITLE
add custom final condarc to bundle

### LINKED ISSUE #4396: Find how to lock .condarc file for bundle app
## 🧰 Task

With the bundle updates using conda/mamba, we need to ensure that condarc configuration from user space (`/Users/someuser/.condarc`) does not interfere with the conda/mamba that exists inside the bundled app installation.

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

This prevents users' conda configuration from interfering with the bundle's conda configuration.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Closes #4396 

# How has this been tested?

- [ ] resulting installation has its own condarc file, with the expected `conda config` output

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Comment by jni** [comment]
@jaimergp I've updated the PR description with a one-line explanation that summarises my understanding. Please update/elaborate/fix if that's somehow incorrect!

**Review by jni — APPROVED** [review]

**Comment by sofroniewn** [comment]
This now has a conflict - i think with #4444. If you can fix @jaimergp then i will merge, thanks!

**Comment by jaimergp** [comment]
Conflicts have been fixed!

**Comment by sofroniewn** [comment]
Thanks!! Will get this in now

**Pull request merged**
