### PR TITLE
Relativize some imports

### PR DESCRIPTION
**Pull request by brisvag**
# Description
I noticed that there were a couple of absolute `from napari...` imports scattered here and there, so I did a grep and replaced them anywhere where it seemed reasonable. There are still a couple places where it's absolute, cause I wasn't sure if it was on purpose (`conftest.py` for example?) but I'm happy to fix those as well if necessary.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by goanpeca** [comment]
Thanks for the fixes @brisvag 

>There are still a couple places where it's absolute, cause I wasn't sure if it was on purpose (conftest.py for example?) but I'm happy to fix those as well if necessary.

I think that anything related to tests and pytest should always use absolute imports.

**Comment by goanpeca** [comment]
I also think the `benchmarks` should remain absolute, since they are there for convenience but not distributed with napari, so eventually could live somewhere else.

**Review by goanpeca — COMMENTED** [review]
Looks good!

Left some comments :)

**Comment by andy-sweet** [comment]
Is there any reason to prefer relative over absolute imports other than being concise? In my experience, the conciseness rarely saves lines and often just means my poor brain has to jump up a few directories to work out where that module is. Note that [PEP 8 generally recommends absolute imports](https://peps.python.org/pep-0008/#imports), though also clarifies relative imports can be fine too. I don't feel strongly here, but am curious about the preference.

**Comment by brisvag** [comment]
For it's for:
- consistency: I don't like having ajust a couple of absolute ones, it seems they refer to an external package
- brevity

I agree that it can be confusing, but really the problem there is that we're not very good at naming modules... we have `utils` in a bunch of places :P

**Comment by Czaki** [comment]
I'm against this change. I would even change all imports starting with more on dot to absolute import. The only reason is that gthub interface doe not follow relative import 

Absolute import screenshot:
image

Relative import screenshot:
image

So relative imports make it harder to review someone's changes or respond to someone's questions as I first need to launch IDE, follow imports, and when found the source, go to browser and determine all links to be in response. Thi is even more problematic, when I need to switch branch from currently working.

**Comment by brisvag** [comment]
Those are good points. I just feel like consistency is valuable here, so maybe we should consider switching to absolute everywhere :P

**Comment by brisvag** [comment]
https://github.com/MarcoGorelli/absolufy-imports

**Comment by Czaki** [comment]
> [MarcoGorelli/absolufy-imports](https://github.com/MarcoGorelli/absolufy-imports)

I just want to post the same link. 

At this moment, I do not found a tool that allows doing relative import in the same package, but not from parent packages.

**Comment by goanpeca** [comment]
I think is consistency is very importante. I do not have an argument for relative imports, I prefer absolute ones :) 

So all in for making the absolute, or just uniform if not absolute. 🚀

**Pull request closed without merging**
