### PR TITLE
Add python 3.9 test

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR would add a python 3.9 test. Right now just on linux and including everything. I'm curious what will succeed/ fail.

Relevant to https://github.com/napari/napari/pull/1958#issuecomment-734957240 cc @tlambert03 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by sofroniewn** [comment]
Well, looks like we couldn't even get py3.9 installed! Maybe that was obvious to everyone else, but I just wanted to try!! 😄

**Comment by tlambert03** [comment]
> Well, looks like we couldn't even get py3.9 installed! Maybe that was obvious to everyone else, but I just wanted to try!! 😄

try removing all of the conda version pins:
`conda install -y -n base conda=4.8.3` -> `conda update -y -n base conda`

**Comment by sofroniewn** [comment]
> try removing all of the conda version pins:
conda install -y -n base conda=4.8.3 -> conda update -y -n base conda

still no dice

**Comment by tlambert03** [comment]
> still no dice

oh! try replacing `conda install -y python=$PY_VER` with `conda install -y -c conda-forge python=$PY_VER`

**Comment by tlambert03** [comment]
ok, now we're seeing the same sort of install errors that I've been seeing locally with 3.9.  Specifically scikit-image seems to be throwing ` No module named 'numpy'` if numpy isn't already installed.  You can probably tinker from here, but try adding `conda install numpy` before installing scikit image.

something like this is probably very safe:
```
conda install -y numpy
conda install -y numcodecs scikit-image
python -m pip install --retries 3 -r requirements/test.txt
python -m pip install -e .[pyside2] $PIP_FLAGS
#etc...
```

**Comment by sofroniewn** [comment]
Looks like vispy 0.6.6 was released last week https://pypi.org/project/vispy/0.6.6/, which contains the `3.9` patch https://github.com/vispy/vispy/compare/v0.6.5...v0.6.6

**Comment by jni** [comment]
Cool, do you want to push an empty commit here to see if it works?

**Comment by sofroniewn** [comment]
Looks like this is going great, only windows 3.9 failing!!

**Comment by sofroniewn** [comment]
As discussed with @tlambert03 this would be superseded by #2051

**Comment by sofroniewn** [comment]
Superseded by #2051

**Pull request closed without merging**
