### PR TITLE
move colormaps from layers folder to resources folder

### LINKED ISSUE #152: Move vendored colormaps to resources folder
I think we should move the folder `_vendored` and the files `matplotlib_cmaps.txt` and `colormaps.py` to the `resources` folder as I don't think they belong in the `layers` folder which otherwise contains our individual layer folders and some mechanics for adding new layers

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description

Resolves #152.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [x] run examples scripts

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Review by kne42 — APPROVED** [review]
LGTM! Don't forget to change `MANIFEST.in`. While you're at it, please also rename all instances of `napari_gui` to `napari` in there :)

**Review by royerloic — CHANGES_REQUESTED** [review]
Ressource folders are almost always reserved for non-code files such as icons, images, text files, etc...
I see a lot of python code going into the ressource folder, which i am not sure makes sense.
I am perfectly happy with colormaps living in a napari.colormaps package.

What would make sense to move to ressources is any text file (non .py) that would describe colormaps, if there is such a thing...

**Comment by sofroniewn** [comment]
Ok, that sounds reasonable - does @jni want to weigh in before I move anything again?

**Comment by jni** [comment]
He does not. =P But he agrees with @royerloic's general gist. =)

**Comment by sofroniewn** [comment]
@royerloic how about a `colormaps` folder inside the `util` folder?

**Comment by sofroniewn** [comment]
Have now moved to `util` folder. If @royerloic approves and tests pass he can merge

**Comment by royerloic** [comment]
You are going to hate me...
I would simply have the colormaps in:
napari.colormaps

util packages usually contain utility methods and classes used internally multiple times.
If we forsee people adding colormaps by invoking classes or methods from this colormaps
package, I would really expose it as 'napari.colormaps'. 

It is not a big deal at this point, we can revisit that later.

**Review by royerloic — APPROVED** [review]

**Comment by kne42** [comment]
IMO seeing as how these colormaps are specific to image layers, they should live in th3 `_image_layer` folder. Users who want to add more should add a new entry to `Image.colormaps`.

**Comment by jni** [comment]
Totally possible to colormap points, lines, shapes... =)

**Comment by jni** [comment]
(even desirable)

**Comment by sofroniewn** [comment]
These are all good points, we also need to curate the list of colors available for the marker `edge_color` and `face_color` which right now is a giant list. We might want to that inside a `napari.colors` or `napari.colormaps` too.

I will leave this PR for now, but we can revisit when we address some of our other color related issues like #97 

We might also want to look at the organisation of `util` again too, including the `misc.py` which is a bit of a grab bag right now.

**Pull request merged**
