### PR TITLE
[WIP]: NAP-4 async slicing prototype 

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description
This is a prototype PR that implements a version of the current technical design proposal in [NAP-4](https://github.com/napari/napari/pull/4892) for the image and points layers.

This should not be merged into napari, but should be useful to understand what a rough implementation of that proposal could look like in terms of code, behavior, and performance.

### CODE REVIEW

**Comment by kephale** [comment]
I wanted to share that I tested loading data from IDR/OMERO with the current commit of this PR and it works. I used https://github.com/kephale/nesoi/blob/main/examples/big_idr_test.py which is basically doing the same thing as `napari-omero`. This is an example of a napari plugin that required the previous `ASYNC` implementation to work which  works properly with the new async prototype.

napari_async_slicing_data_from_IDR
Figure: An animated gif of running the linked script in napari with the async slicing prototype which streams data from the IDR OMERO server. The napari window stays interactive instead of freezing.

**Comment by brisvag** [comment]
Awesome! We definitely need a little spinner to let the user know something is happening xD

**Comment by kephale** [comment]
I have now also tested this prototype with `napari-imaris-loader` and it works as expected!

**Comment by andy-sweet** [comment]
Closing this, which will continue to serve as a reference as we implement this work, but there's no need for it be to open.

**Pull request closed without merging**
