### PR TITLE
Split canvas color from theme

### PR DESCRIPTION
**Pull request by Czaki**
# Description

As discussed in #2074 this PR split canvas color from the theme. Some type of data looks better with black background (for example multichannel confocal data).

I need to use the light theme because part of QWidgets after applying the napari style are illegible. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
I'm adding this to `0.4.4` if it's ok that we spend a little time thinking about this. One thing I'd like to think about is us adding a small `Canvas` object, so we could do `viewer.canvas.color = ...` and `viewer.canvas.size ...` etc. One question though is what we'll do when we have multiple canvases, should we then have a list there etc?

**Comment by Czaki** [comment]
> I'm adding this to `0.4.4` if it's ok that we spend a little time thinking about this.

I'm ok with this. 

> One question though is what we'll do when we have multiple canvases, should we then have a list there etc?

I think that in the case of multiple canvases it will be one of the smallest changes. But maybe it is a good point to start a discussion.

**Review by tlambert03 — COMMENTED** [review]
I'm seeing @jni's comment now that looks to have prompted this PR:

> I do agree with you that medium-term we probably want to avoid the canvas background from being managed by the theme, as it is something more fundamental to the visualization itself

so it looks like there's support behind this split...
I certainly like the ability to override the theme canvas (as needed by @czaki), but I'm not so sure I agree that it needed to be completely unsettable in the theme.  Would there be a way to allow both while still satisfying your use case @Czaki?

**Comment by sofroniewn** [comment]
> I certainly like the ability to override the theme canvas (as needed by @Czaki), but I'm not so sure I agree that it needed to be completely unsettable in the theme. Would there be a way to allow both while still satisfying your use case @Czaki?

yeah, it would be great if we could do this without adding `viewer.canvas_color`, which I don't think we'll want in long term. I'm going to bump this to 0.4.5 as it probably needs more discussion.

**Comment by Czaki** [comment]
> yeah, it would be great if we could do this without adding `viewer.canvas_color`, which I don't think we'll want in long term. I'm going to bump this to 0.4.5 as it probably needs more discussion.

So could we also bump #2074 functions by one version? Also #2140 will not be solved fast. 

I strongly prefer to have option to set background to black for confocal data even with light theme.

**Comment by tlambert03** [comment]
> I strongly prefer to have option to set background to black for confocal data even with light theme.

this part is great.  I too would like the possibility of overriding the theme.  I'd just like us to be able to do it as an _override_ ... not just to discontinue support for theme canvas colors altogether

**Comment by Czaki** [comment]
> this part is great. I too would like the possibility of overriding the theme. I'd just like us to be able to do it as an _override_ ... not just to discontinue support for theme canvas colors altogether

But this force to manually overwrite after every theme is toggled.

**Comment by tlambert03** [comment]
> But this force to manually overwrite after every theme is toggled.

does it? You don't think we can come up with any way to default to the theme color, but once an override has been provided, use it?
i feel like we can probably come up with _something_ ... such as `viewer._canvas_override` or something like that.

**Comment by Czaki** [comment]
> `viewer._canvas_override`

I could implement something like this, but I prefer to make it public attribute 

From user interface it may be a list of basic colors in a view menu?

**Comment by sofroniewn** [comment]
> So could we also bump #2074 functions by one version? Also #2140 will not be solved fast.

Those PRs are already set for `0.4.6`, so should be fine to leave (normal policy would have been two releases so for `0.4.5` for something changed in `0.4.3` but you made them three when added which I think was fine). We can resolve this during next release though.

> I could implement something like this, but I prefer to make it public attribute

I don't want to add a public attribute that we know we will change, especially when it seems like there are deeper issues at play like #2140.

**Pull request closed without merging**
