### PR TITLE
Add scikit-image[data] to install_requires, because it's required by builtins

### LINKED ISSUE #5328: Bug: Samples, including Cells (3D) don't load after `pip install napari` (or napari[pyside], etc.), due to lack of pooch
## 🐛 Bug

`pip install napari` — used when one wants to not have pypi PyQt5 backend, that is installed by `napari[all]` — does not install `pooch` which is needed by scikit-image to make all Sample images work, including `cells3d()` which we have on the napari.org homepage and in the viewer getting started docs.
Note that all `napari[all]` does is install PyQt5 backend and use `scikit-image[data]` which is just `scikit-image` plus `pooch` to make dataset downloads work.
Also note that this issue affects: 
1. all macOS arm64 users who cannot use `napari[all]` due to lack of pyqt5 arm64 wheels on pypi 
2. anyone with pyqt or pyside2 from conda-forge 
3. anyone using Qt6 experimentally 
And finally, the plugin best practices specifically caution against requiring pyqt5, so in this case napari is going against it's own best practices by bundling a feature (sample data) with a specific Qt backend (pyqt5 from pypi).

## To Reproduce

1. Make a conda env
5. Install a Qt backend, using pip or conda
6. `pip install napari` (or `pip install napari[pyside]`
7. Either use the File > Open Sample and choose Cells (3D) or use:
```
import napari
viewer = napari.Viewer()
viewer.open_sample('napari', 'cells3d')
```

## Expected behavior

All of the samples should work, regardless of choice of Qt backend.

## Environment

```
napari: 0.4.17
Platform: macOS-12.6-arm64-arm-64bit
System: MacOS 12.6
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ]
Qt: 6.3.2
PySide6: 
NumPy: 1.23.4
SciPy: 1.9.3
Dask: 2022.10.2
VisPy: 0.11.0
magicgui: 0.6.0
superqt: 0.4.0
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.1

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Plugins:
  - napari: 0.4.17 (77 contributions)
  - napari-console: 0.0.6 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)
```

## Additional context

napari installed via conda is not affected (ie. `conda install napari` properly includes pooch)

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description

This PR adds `scikit-image[data]` to the `install_requires` of `napari`, because it's required by `builtins` to ensure all the Sample data in File > Open Samples actually work. 
`builtins` doesn't have it's own dependencies/requirements, because while it works as a plugin, it's not installed as such. 

Note: at the moment,  `scikit-image[data]` is just `pooch` a small pure python package, whose dependencies are already part of the napari requirements list. I didn't add `pooch` directly, because if `scikit-image[data]` changes how samples are loaded, then we're covered and  `scikit-image[data]` is what `builtins` requires, so if in the future `builtins` is spun-off to an installed plugin, then this dependency can be removed.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Closes #5328

#4706 suggests ultimately moving to `builtins` as it's own repo as a plugin, then could have it's own requirements and this would not be needed.

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [x] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by goanpeca** [comment]
Looks good @psobolewskiPhD !

Any chance we could add a test to catch this in the future?

**Comment by psobolewskiPhD** [comment]
> Looks good @psobolewskiPhD !
> 
> Any chance we could add a test to catch this in the future?

Sample data is tested:
https://github.com/napari/napari/blob/7e6197212e2c1b1d507b6b5c14b5739691454b87/napari/plugins/_tests/test_sample_data.py
but CI installs `pooch` as part of `testing` install requirements:
https://github.com/napari/napari/blob/cd5c3147a13a42304a6e26a56f516bdc8b879557/setup.cfg#L110-L123

So I'm not sure how to test this specific interaction.

(not sure why pooch is higher there than what scikit-image requires, maybe pooch is also used for some other test?)

**Comment by goanpeca** [comment]
Got it! Thanks for digging it :)

**Review by goanpeca — APPROVED** [review]

**Comment by andy-sweet** [comment]
> (not sure why pooch is higher there than what scikit-image requires, maybe pooch is also used for some other test?)

I think it's because pooch added progress bars in v1.6.0: https://github.com/fatiando/pooch/releases/tag/v1.6.0

For the relativity small scikit-image data these aren't too important, unless you're on a slow connection. But as files get larger, having some messaging around progress becomes almost required. We added [some examples like that](https://github.com/napari/napari/blob/main/examples/dev/slicing/ebi_empiar_3D_with_labels.py) in `examples/dev` to help drive forward the async slicing efforts.

**Review by Czaki — APPROVED** [review]

**Pull request merged**
