### PR TITLE
Add `block` to viewer.show

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
as per https://forum.image.sc/t/wait-for-napari-window-to-close-to-advance/52328/3 
this adds a `block` parameter to `napari.run()` that will block even if ipython has the event loop.  It seems to work ok in ipython, but when I try in jupyter, it works the first time, but any subsequent cells after using `block=True` seem to hang indefinitely

### CODE REVIEW

**Comment by tlambert03** [comment]
worth adding again:
a much more natural approach here (at least as far as the qt part is concerned) would be to attach the blocking behavior to the `viewer.window` itself (via `viewer.show()`) rather than trying to add another level to the global event loop:

```python
# so rather than this
viewer = napari.Viewer()
napari.run(block=True)

# we would have this:
viewer = napari.Viewer()
viewer.show(block=True)
```

where `block=True` would be the equivalent of `QDialog` [open](https://doc.qt.io/qt-5/qdialog.html#open) or [exec](https://doc.qt.io/qt-5/qdialog.html#exec) instead of [show](https://doc.qt.io/qt-5/qwidget.html#show)...

but, I can't see a way to extract ourselves from the `Viewer(show=True)` problem without a pretty big breaking change...  I guess we could put `block=True` on the viewer itself?

**Comment by sofroniewn** [comment]
Hmm, yeah I need to think about all this. I don't mind `napari.run(block=True)`, but it still is all a little confusing. Maybe something we can change in `0.5.0`?

**Comment by tlambert03** [comment]
i changed this PR to `viewer.show(block=True)`.  It's probably where the logic for blocking on a particular viewer belongs anyway (as opposed to the global QApplication and `napari.run`).   So, in IPython/Jupyter, you can do this:

```python
import napari

for i in range(4):
    viewer = napari.Viewer(title=f'viewer {i}')
    viewer.show(block=True)
```

I guess it might be _slightly_ confusing, since you don't use `show` for anything other than blocking (and the "showing" part of `viewer.show` is happening by default even if you don't call viewer.show) ... but if eventually make `viewer.show` the canonical way to show the viewer, it would still work then  too.

**Review by goanpeca — APPROVED** [review]

**Review by sofroniewn — APPROVED** [review]
This LGTM, I'm fine with current approach. Maybe @jni wants to look before final merge, unless @tlambert03 you've had more ideas here too.

**Comment by tlambert03** [comment]
> unless @tlambert03 you've had more ideas here too.

nope, this is a decent start as far as I'm concerned

**Pull request merged**
