### PR TITLE
fix pip-missing-reqs step

### PR DESCRIPTION
**Pull request by Czaki**
# Description
after changes in pip 20.1 task for missing requirements fail. 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References
https://github.com/r1chardj0n3s/pip-check-reqs/pull/23

# How has this been tested?

- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Comment by Czaki** [comment]
@sofroniewn @tlambert03 This fix #1160 result (until next pip changes).

**Review by tlambert03 — APPROVED** [review]
awesome.  thank you @Czaki!

**Comment by Czaki** [comment]
Because I see that maintainer stop working with package, then I decide to pin pip version for this check. So I'm not sure if approach from #1160 is best, but I have a little of time, so I prepare PR to `pip-check-reqs`

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Pull request merged**
