### PR TITLE
Fix wrong working interpolation of labels in 3d

### LINKED ISSUE #6595: [main] 3D rendering of labels has wrong colors (mostly label 1, brown)
### 🐛 Bug Report

3D rendering of labels is broken, label colors are not displayed properly:
image

Git bisect points to ca2d186e1e908a19c5a34c932215ebc86afed88d

0.4.18 and 0.4.19rc3 are both fine.

### 💡 Steps to Reproduce

Script:
```
import napari
from skimage import data
from scipy import ndimage as ndi

blobs = data.binary_blobs(length=128, volume_fraction=0.1, n_dim=3)
labeled = ndi.label(blobs)[0]
viewer = napari.Viewer()
viewer.add_labels(labeled, name='blob ID')
viewer.dims.ndisplay = 3
```
Or use the super new `Balls 3D` sample!

### 💡 Expected Behavior

The 3D labels should still use the proper label colors.

### 🌎 Environment

napari: 0.5.0a2.dev520+gec90e5c3c
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.11.7 | packaged by conda-forge | (main, Dec 15 2023, 08:41:36) [Clang 16.0.6 ]
Qt: 6.6.0
PyQt6: 
NumPy: 1.26.3
SciPy: 1.11.4
Dask: 2023.12.1
VisPy: 0.14.1
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml
Plugins:
ERROR:npe2.manifest.schema:napari.manifest -> 'napari_animation' could not be imported: The name field in the manifest ('napari-animation') must match the package name ('napari_animation')
  - napari: 0.5.0a2.dev495+gd507dd64e (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

### 💡 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues
closes #6595

# Description

Set interpolation for rendering of 3D data for labels.

### CODE REVIEW

**Review by jni — APPROVED** [review]

**Review by brisvag — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
Everything is fixed on my end.
For my own edification, what's the advantage of--as far as I can tell--hard-coding this on the vispy side rather than putting it back in _ImageBase for the Labels layer to get?

**Comment by brisvag** [comment]
I guess the question is: does non-nearest label interpolation make any sense? I would say maybe yes ("smoother" boundaries), but we don't have an implementation for it now, so I don't see why exposing it on the napari side. Or am I misunderstanding the question?

**Comment by Czaki** [comment]
> For my own edification, what's the advantage of--as far as I can tell--hard-coding this on the vispy side rather than putting it back in _ImageBase for the Labels layer to get?

Because this cange do not come from changes in `_ImageBase` but in `VispyLabelsLayer` where `VispyLabelsLayer` stop setting interpolation for Vispy node. 

At this moment, there is no interpolation for Labels. Previous implementation just hard-code interpolation as nearest.

**Comment by psobolewskiPhD** [comment]
> I guess the question is: does non-nearest label interpolation make any sense? I would say maybe yes ("smoother" boundaries), but we don't have an implementation for it now, so I don't see why exposing it on the napari side. Or am I misunderstanding the question?

Thanks both of you.
BTW I actually had a user ask why labels in 3D were so blocky, so there might be some interest in other interpolation options for labels. Worth an issue?

**Comment by Czaki** [comment]
> BTW I actually had a user ask why labels in 3D were so blocky, so there might be some interest in other interpolation options for labels. Worth an issue?

None of the current kernels allow doing this as far as I know. But maybe @brisvag has some idea for smoothing.

**Comment by brisvag** [comment]
In 2d it might be doable, in 3d it's super tricky, you can't just make a kernel cause interpokating between labes gives nonsense results... But sure, an issue is always good!

**Comment by Czaki** [comment]
Would it be possible to do majority voting kernel?

**Comment by brisvag** [comment]
> Would it be possible to do majority voting kernel?

I didn't know the term, but I guess that makes sense...

**Pull request merged**
