### PR TITLE
Add Peter Sobolewski (@psobolewskiPhD) to list of Core Developers

### PR DESCRIPTION
**Pull request by Czaki**
# Description

## Type of change

- [x] Documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by Czaki** [comment]
@andy-sweet I would love to see thin in 0.4.17 be part of stable docs.

**Comment by andy-sweet** [comment]
> @andy-sweet I would love to see thin in 0.4.17 be part of stable docs.

I will make it so.

**Review by andy-sweet — APPROVED** [review]
Thanks for the catch before release.

**Comment by jni** [comment]
Thanks @andy-sweet!

As an aside though, @melissawm and I are looking at implementing the two-repo docs solution in such a way that we can update any version's docs independently of the release cycle, so it's not as big of a worry now to make sure the docs are up to date — if all goes to plan we'll soon be able to just update them!

**Comment by kevinyamauchi** [comment]
Woo! Welcome, @psobolewskiPhD ! Thank you for all of your contributions to the napari community.

**Pull request merged**
