### PR TITLE
Fix plugin settings restore and schema_version validation error in preferences dialog

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This fixes items 3 and 4 from #3206 ... probably want to get this in for 0.4.11

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Review by goanpeca — APPROVED** [review]

**Comment by sofroniewn** [comment]
@tlambert03 it looks like this PR broke our docs building with the following error - see

```python-traceback
Run python docs/update_docs.py
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runner'
Traceback (most recent call last):
  File "docs/update_docs.py", line 164, in <module>
    create_preferences_docs()
  File "docs/update_docs.py", line 134, in create_preferences_docs
    if not issubclass(field.type_, BaseModel):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
Error: Process completed with exit code 1.
```

Any chance @tlambert03 @goanpeca @jaimergp for a quick fix here. I think this is the last thing needed before I can make the next rc

**Comment by tlambert03** [comment]
yep, I mentioned the fix in https://github.com/napari/napari/pull/3296#issuecomment-908831386

will take care of it

**Comment by tlambert03** [comment]
https://github.com/napari/napari/pull/3305

**Pull request merged**
