### PR TITLE
Reset all dims to be rollable

### LINKED ISSUE #6792: When all layers are removed, all roll locks should be removed
> Personally, I think when the LayerList goes to zero the locks should be removed, but I won't block on this point because I expect strong pushback on this from other core devs.

This could be done easily in [`Dims.reset`](https://github.com/napari/napari/blob/f9709d8a9eed8f1ab41596d71b7b29ee4390f64e/napari/components/dims.py#L377), which is called [in `ViewerModel` when the layers change and there are none of them](https://github.com/napari/napari/blob/f9709d8a9eed8f1ab41596d71b7b29ee4390f64e/napari/components/viewer_model.py#L489).

So I don't have an issue with this side-effect because there are existing related side-effects when removing the last layer.

@Chris-N-K : we've already asked so much of you here, so this is a non-blocking request. If you feel like adding it when making the latest updates, go for it! Otherwise, @psobolewskiPhD and I can make a follow up PR.

_Originally posted by @andy-sweet in https://github.com/napari/napari/issues/5986#issuecomment-2025530604_

### PR DESCRIPTION
**Pull request by andy-sweet**
# References and relevant issues
Closes #6792 

# Description
This is a follow-up to #5986 that resets all dimensions to rollable when all layers are removed.

Given that this not necessarily a bug and more of a preferred behavior, I did not add a test to cover it to avoid future maintenance of that test.

### CODE REVIEW

**Comment by andy-sweet** [comment]
@psobolewskiPhD : I added you as a reviewer because you made the request here. No rush and feel to pass it to someone else.

**Review by psobolewskiPhD — APPROVED** [review]
I had a long think about whether this is actually expected/desired behavior, which I left as a comment on the issue:
https://github.com/napari/napari/issues/6792#issuecomment-2030970297

Ultimately, I think it is, because TLDR: the viewer "forgets" about the dims other than the 2 right-most, so this PR ensures consistent behavior.

**Comment by andy-sweet** [comment]
As always, thanks for thinking this through @psobolewskiPhD !

Based on the current behavior of napari, I agree with those thoughts. I think some of those behaviors around dims could be improved in the future, but until then this seems good enough to me.

@Chris-N-K : I also added you as a reviewer in case you don't agree with the logic above.

**Comment by Chris-N-K** [comment]
@andy-sweet with pleasure.
I think a consistent behavior would be best. So either the state should be kept for all axes or for none.
Which way is best depends on the use case and is to discuss.
I personally would like it if the rollable state of axes would persist, maybe even after closing the viewer.
In this case one could add a reset button to reset all axes at once.
Currently the for none is probably a lot easier to implement.

**Comment by psobolewskiPhD** [comment]
I think `preserve lock state for all dims` is a reasonable feature request Issue, could add a checkbox to the widget or something.

**Comment by andy-sweet** [comment]
> I personally would like it if the rollable state of axes would persist, maybe even after closing the viewer.
> In this case one could add a reset button to reset all axes at once.

Closing the viewer has lots of side effects (that maybe it shouldn't), but I think you're also implying that the state would also persist after removing all the layers. E.g. this would be desirable

```python
viewer = napari.Viewer()
viewer.add_layer(...)
viewer.add_layer(...)
viewer.dims.axis_labels = ("t", "z", "y", "x")
viewer.dims.rollable = (False, True, True, True)
viewer.dims.roll()
viewer.layers.clear()
viewer.dims.axis_labels  # => ("t", "z", "y", "x")
viewer.dims.rollable  # => (False, True, True, True) 
```

but after this PR we get

```python
...
viewer.layers.clear()
viewer.dims.axis_labels  # => ("y", "x")
viewer.dims.rollable  # => (True, True) 
```

Unfortunately, I think `Dims` currently has a fundamental limitation there because it only keeps track of the maximum number of dimensions across all layers until there are no layers when it hits the reset behavior used here.

> I think a consistent behavior would be best. So either the state should be kept for all axes or for none.

I agree that I like consistency. My strong intuition is that this PR is the way to go for now because I'm concerned that patching more complex behavior on `Dims` (which is central component in napari) for which it wasn't initially designed is probably going to cause a maintenance headache and surprise bugs.

Interestingly, the only attribute that survives the reset is `Dims.axis_labels`, though again it gets cut to the last two labels to match `Dims.ndim` so it's inconsistent and doesn't seem particularly useful.

### Long term thoughts

I do think this discussion is useful for setting up longer term work and redesign in napari. I've long wanted to redesign `Dims` to better set us up for multi-canvas views/slices of different layers. See [NAP-9 for some related discussion](https://napari.org/dev/naps/9-multiple-canvases.html).

For example, I can imagine a canvas presenting a view over a number of layers. State like `rollable` and `axis_labels` would be state associated with that view and could persist independently on layers. The layers would also have their own axis names, so generating views would be a matter of corresponding the axis names. `Dims` would not be directly coupled to layers, only when generating views/slices.

For example, if we just had one canvas, the above example might look something like the following

```python
viewer = napari.Viewer()
viewer.add_layer(...)
viewer.add_layer(...)
viewer.dims = ("t", "z", "y", "x")
viewer.dims.t.rollable = False
viewer.dims.roll()
viewer.layers.clear()
viewer.dims  # => ("t", "z", "y", "x")
viewer.dims.t.rollable  # => False 
```

I have no idea when this work might get done, but I'm still holding out some hope :)

**Comment by Chris-N-K** [comment]
I think for now resetting everything after complete layer removal is the best approach.
My other suggestion was more of a desired longterm goal.

**Pull request merged**
