### PR TITLE
Bump numpy version

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Bump numpy version 1.17 because nan parameters of nan_to_num is introduced in this version. 
Bug introduced in #1360

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html

https://github.com/napari/napari/blob/ea0fc9ca29d730808b1a66a8710679ee0fbe7ab5/napari/components/layerlist.py#L230-L231

https://travis-ci.com/github/4DNucleome/PartSeg/jobs/380612109 line 663
# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Comment by jni** [comment]
Gah. Thank you for spotting this @Czaki.

According to [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html), we should continue to support 1.16 until January. So I think the correct fix is to bump to 1.16 and write our own nan_to_num.

We should also add a "minimum requirements" build to our test matrix to avoid these issues in the future. We do this with an env var in scikit-image, see here:

https://github.com/scikit-image/scikit-image/blob/73a8dbf0128e8832b15d86c88c9304bc1280aa71/tools/travis/before_install.sh#L60-L64

**Comment by Czaki** [comment]
Ok. I created #1613 PR which should work with 1.16.

I do not see sh script in napari and do not familiar with cirrus yaml so cannot fast prepare such task. But simple If in yaml should be enough.

**Comment by Czaki** [comment]
```python 
import os
from configparser import ConfigParser

config = ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), "..", "setup.cfg"))

minimum_requirements = config["options"]["install_requires"].replace(">=", "==")

with open(os.path.join(os.path.dirname(__file__), "minimal-req.txt"), "w") as f_p:
    f_p.write(minimum_requirements)
    f_p.write("\n")
```

I tes nowt such code in my project to generate minimum requirements during test base on setup.cfg

**Comment by sofroniewn** [comment]
Ok, thanks for the fix in #1613, agreed testing minimum versions sounds good, and I'm very open to different ways to do it in our CI, but that script from @Czaki looks like a good place to start

**Comment by Czaki** [comment]
new version of script (with python dependecies)

```python
import os
from configparser import ConfigParser

config = ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), "..", "setup.cfg"))

minimum_requirements = config["options"]["install_requires"].replace(">=", "==")
minimum_qt = config["options.extras_require"]["pyqt"].replace(">=", "==")

with open(os.path.join(os.path.dirname(__file__), "minimal-req.txt"), "w") as f_p:
    f_p.write(minimum_requirements)
    f_p.write(minimum_qt)
    f_p.write("\n")
```

**Comment by sofroniewn** [comment]
This can now be closed as #1613 and #1617 will supersede it

**Pull request closed without merging**
