### PR TITLE
Don't validate defaults on `EventedModel`

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This one is rather crazy and took me a long time to debug, and it's equally hard to explain.   @brisvag cued me into this when using the event debugger, and noticing that cursor event objects didn't know their "source"

### problem

all `EventedModel` types used as subfields on pydantic Models are losing their `event.source`.  For example, see here, where `viewer.cursor.events` doesn't have a source, but a plain `Cursor` object _does_.

```python
In [1]: v = napari.Viewer()

In [2]: v.cursor.events.source

In [3]: from napari.components.cursor import Cursor

In [4]: c = Cursor()

In [5]: c.events.source
Out[5]: Cursor(position=(1.0, 1.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>)
```

### rough explanation

Ultimately, this is the combined result of `validate_all=True` used on `EventedModel`  (which "validates defaults" upon object creation, and which can result in the creation of a new object for that field)... **_combined_** with the fact that `events.Emitter` stores the source as a `weakref.ref` (right [here](https://github.com/tlambert03/napari/blob/d710c9425275a68d179df9e2ed101c2e7f58f2c6/napari/utils/events/event.py#L370)).  It appears that the object is getting garbage collected during the default validation before it even has time to exist.  

The problem is fixed _either_ by using `validate_all=False` in the `EventedModel` config, or by storing a strong reference as `Emitter.source`.  

That strong reference seems like a very bad idea, so this PR avoids validating defaults on EventedModels.  This just means that we can't be lazy when we declare a model... and the default or default_factory we provide should actually be correct.

### mre

The following script is the most minimal reproducible example I could make.  It uses no napari objects, just mocks the bare minimum.  I'm putting it here so that if we ever want to undo this change, this script can be used as a test case.

<details>

```python
from pydantic import BaseModel, Field, PrivateAttr
from typing import Any, ClassVar, Set
import weakref


class EmitterGroup:
    def __init__(self):
        self.source = None

    @property
    def source(self) -> Any:
        return None if self._source is None else self._source()

    @source.setter
    def source(self, s):
        self._source = None if s is None else weakref.ref(s)



class EventedModel(BaseModel):

    # add private attributes for event emission
    _events: EmitterGroup = PrivateAttr(default_factory=EmitterGroup)
    __slots__: ClassVar[Set[str]] = {"__weakref__"}

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._events.source = self

    @property
    def events(self):
        return self._events


class Cursor(EventedModel):
    x: int = 1


class Mod(BaseModel):
    curs: Cursor = Field(default_factory=Cursor)

    class Config:
        validate_all = True


obj = Mod()

print(id(obj.curs.events.source), id(obj.curs))
print("Are same?: ", obj.curs.events.source is obj.curs)
```

</details>

### CODE REVIEW

**Comment by sofroniewn** [comment]
Yikes, sounds like a tricky one to hunt down. I don't love that we cant validate our models on creation anymore - that felt like a really nice thing to have and it's a shame to loose. On the other hand, making a bunch of strong references doesn't sound ideal either. I'm not quite sure what alternatives might exist.

One thing I'm curious about - could we add some tests that basically validated all our defaults? That might at least let us know if we've done something bad before we merge the code.

**Comment by tlambert03** [comment]
> I don't love that we cant validate our models on creation anymore - that felt like a really nice thing to have and it's a shame to loose

Yeah, it was convenient... though, from a typing perspective, incorrect!  We had a bunch of lines essentially assigning something that didn't match types (relying on an implicit conversion to do the job).  So, I can also see the merits here of just using proper values directly.

Its not that you can't validate models on creation at all, it's just the fields where we've supplied a default value (ie, init values are still validated)

As for tests, I actually think that we're relatively well covered.  As you'll notice, I had to fix each default to make tests pass.  So as long as the model itself has a test, Im not sure we need to go farther?

**Comment by tlambert03** [comment]
It's conceivable that we could find a way to do this by rigging the way the weakref gets created or further modifying the `Model.__new__` somehow.  But after a while this is all I came up with

**Review by alisterburt — COMMENTED** [review]
Wow, good find! 

I can't seem to add a suggestion outside of the diff, my only comment would be that it might be worth noting in the `EventedModel` docstring that default values should be correctly typed as it would be easy to miss, something like

```
Note:  default Field values are not converted by default (#4138) and should be correctly typed.
```

**Comment by tlambert03** [comment]
Sure, will add.

Also, just want to point out that `False` is the pydantic default for `validate_all` ... so we're just going back to the pydantic default here.

**Review by alisterburt — APPROVED** [review]
Thanks for adding! LGTM :)

**Review by brisvag — APPROVED** [review]
This all makes sense to me, and will remove the confusion I had with the event debugging. Good spelunking job @tlambert03 :)

**Review by sofroniewn — APPROVED** [review]
Ok, good points all around - let's give this a go.

@tlambert03 is the python 3.10 fail unreleated or specific to this PR - can you check that out before we merge. I havn't seen it elsewhere. Thanks!!

**Comment by tlambert03** [comment]
unrelated... it's `RuntimeError: Error while fetching file https://raw.githubusercontent.com/vispy/demo-data/main/orig/triceratops.obj.gz.` in `test_examples[surface_normals_wireframe.py]` ... just an external download timeout

**Pull request merged**
