### PR TITLE
refactor npe2 widget name to display_name

### PR DESCRIPTION
**Pull request by nclack**
# Description
This updates napari for napari/npe2#51 which changes the widget "name" field to "display_name"

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
ugh, this is definitely necessary, but reminds me that I hate the fact we're using a display name as a key.

something to think about... people don't often use `window.add_plugin_dock_widget`... but if they do, this comes into play.  Display name doesn't make for a good key here

**Comment by nclack** [comment]
gah. I forgot to do buitins

**Comment by goanpeca** [comment]
>ugh, this is definitely necessary, but reminds me that I hate the fact we're using a display name as a key.

What are the options here?

**Comment by nclack** [comment]
> > ugh, this is definitely necessary, but reminds me that I hate the fact we're using a display name as a key.
> 
> What are the options here?

with respect to npe2 we could use the command id or some part of it, I think? 

I imagine that's out of scope for this PR though.  @tlambert03 should we create an issue for this?

**Comment by tlambert03** [comment]
Yep, push on!

**Review by goanpeca — APPROVED** [review]

**Pull request merged**
