### PR TITLE
Make flash effect feel more instant

### PR DESCRIPTION
**Pull request by marlene09**
This PR is a fix for issue #3000 by moving the peak of the flash closer to the beginning of the animation. 
This PR was worked on during the SciPy2021 sprints with @alisterburt

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
LGTM!

**Review by alisterburt — APPROVED** [review]
great job @marlene09 and congratulations on your first PR!! 🎉
@jni are you happy with the way this has been implemented?

**Review by tlambert03 — APPROVED** [review]

**Review by jni — APPROVED** [review]
🚀

**Comment by marlene09** [comment]
> LGTM!

:)

**Pull request merged**
