### PR TITLE
Update colortransform when building texture

### LINKED ISSUE #1585: interaction between visibility and contrast limits
## 🐛 Bug

I've just found a funny bug where there appears to be an interaction between the visibility and contrast limits

## To Reproduce

1.  napari.view_image(np.random.random((200, 200)), contrast_limits=[0, 10])
2. move clim slider to be [0, 2]
3. toggle visibility off/ on
4. notice that after toggle image is very saturated. adjusting slider a tiny bit causes image to look good again

clim_bug

## Environment

last commit https://github.com/napari/napari/commit/62a046de2e5009f0c9137e3fd3999fbf902928ca

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
fixes #1585
fixed upstream in https://github.com/vispy/vispy/pull/1911

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jni — APPROVED** [review]
Thanks @tlambert03! Is there an easy way to test for this? Maybe with a screenshot?

**Comment by tlambert03** [comment]
> Thanks @tlambert03! Is there an easy way to test for this? Maybe with a screenshot?

lemme give it a shot

**Comment by tlambert03** [comment]
oh man... I don't even want to know why this doesn't work.  buuut, there seems to be some sort of race condition here making this very hard to test.  if I run the entire following code block at once, it passes, but if I run it in two chunks (where marked), or if I manually change the contrast limits, it fails

```python
    import numpy as np, napari
    viewer = napari.Viewer()
    layer = viewer.add_image(np.random.random((200, 200)), contrast_limits=[0, 10])
    visual = viewer.window.qt_viewer.layer_to_visual[layer]

    # if pause right here, then this fails, showing the weird contrast phenotype
    layer.contrast_limits = (0, 2)
    screen1 = viewer.screenshot()
    visual._on_data_change()  # this is the the problematic method when toggling visibility 
    screen2 = viewer.screenshot()
    assert np.allclose(screen1, screen2)
```

I also tried putting in a `qtbot.wait()` or a `time.sleep` there, but it still didn't fail the test on the current master.  So I'm actually not immediately sure how to get the failing test at the moment!

**Comment by tlambert03** [comment]
ok, I found a test that works (fails on master, passes here).  It's not pretty – testing for screenshot equality ended up being weirder/harder than expected – but it gets the job done

**Review by sofroniewn — APPROVED** [review]
LGTM! Thanks!!

**Pull request merged**
