### PR TITLE
Make docked widgets of `qt_viewer` lazy

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Currently, all Qt controls for napari viewers are created in the `QtViewer` constructor. 
So they are created even if they are not used (for example, in additional viewers in #4665 or PartSeg). this is not optimal and may create as a parent for widget is not set.

As the next planned release (0.4.17) should not be breaking release, and I'm not sure where they should live, change them into the lazy attributes. So all code will work, but they will be created on demand. 

Maybe in 0.5.0 they should be moved to the main window, but then it will require adding their constructor to the public `qt` API to keep the possibility of embedding them in a custom GUI.  

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by sofroniewn — COMMENTED** [review]
I don't have huge objections to this - it adds some complexity, and it would be great to know if more tools rather than just partseg needed this before committing, but it has relatively little cost too. @jni @tlambert03 thoughts?

**Comment by Czaki** [comment]
It may be also useful if someone would like to use additional `QtViewer` instance like in https://github.com/napari/napari/blob/main/examples/multiple_viewer_widget.py

**Comment by Carreau** [comment]
Rebased to try to fix the conflicts and tests.

**Review by tlambert03 — APPROVED** [review]
I like it,  thanks @Czaki.  Can you just add return type annotations on the new properties so other places in the code still know what they are

**Pull request merged**
