### PR TITLE
Close napari window on Ctrl+C without geting window focus

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR is the continuation of #1494. As matplotlib PR https://github.com/matplotlib/matplotlib/pull/13306 is finally merged then, as promised, I port it to napari codebase. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

https://github.com/matplotlib/matplotlib/pull/13306
the final solution for #1493

# How has this been tested?

- [x] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
wow, that's some clever magic there.
Can you add a link to the original matplotlib issue (https://github.com/matplotlib/matplotlib/pull/13306/) in the code so that someone stumbling on it knows where we got it?

**Comment by Czaki** [comment]
I do not understand. But I will try to debug this under windows.

**Review by sofroniewn — APPROVED** [review]
Nice!

**Review by goanpeca — APPROVED** [review]

**Comment by Czaki** [comment]
It works on windows, but I do not know how to test this without termination of whole test session.

**Pull request merged**
