### PR TITLE
Documentation: Adding tutorials to main napari repository

### LINKED ISSUE #3529: Migration proposal between repositories
## 📚 Documentation

Hello, folks

During the latest docs working group and community meetings we have been discussing a strategy to unify documentation for napari in a way that
1. Makes it easier to run doctests and CI
2. Makes it easier for contributors to know where to contribute

### Current situation

As of now, this is the workflow as I understand it:
1. The Tutorials live on the napari.github.io repo, as they were migrated there from the old tutorials repo. See https://github.com/napari/napari.github.io/tree/main/tutorials
2. All the other parts of the documentation live on the main napari repo (the one where this issue lives) and are copied over to napari.github.io via [the `copy-docs.py` script](https://github.com/napari/napari/blob/main/docs/copy-docs.py)
3. This `copy-docs.py` script also generates a `_toc.yml` file that is copied over to napari.github.io, where it is used to generate the napari.org website table of contents.
4. All of the theme and website tooling lives at napari.github.io

### Proposal

The proposal is to move the Tutorial content to the main napari repo and unify the parts of the documentation that are copied over to napari.github.io. This means
- People contributing docs should only post issues and PRs to one repo, napari/napari
- We can run CI on all the docs, including the tutorials
- Anything related to website (design, tooling, infrastructure) should go into napari/napari.github.io

### Notes

- With this strategy, it might be more complicated to get actual documentation previews on napari/napari. Because the docs are built with the theme that lives on another repo, one option might be to have a CI image with a frozen version of the website that is only updated occasionally. Personally, I think that is good enough for docs CI, and I strongly advocate for having some sort of preview when submitting docs content to napari/napari.
- The alternative would be to move all the docs to napari.github.io. This might simplify preview, but the actual API documentation would still need to live on napari/napari and we would have a split anyway.

Does this sound like a reasonable plan? Happy to hear thoughts and concerns.

### PR DESCRIPTION
**Pull request by melissawm**
# Description

This PR is the last part of the docs reorganization explained in napari/napari.github.io#176 and #3529 . A second part, to make sure the two repos are synced, is here napari/napari.github.io#305

It copies over all tutorial content from napari/napari.github.io to this repo. No actual content has been changed, except for links and image targets. After this PR is merged, all documentation contribution can be proposed against napari/napari, keeping the napari/napari.github.io repo only for theme and website-related issues/PRs. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) **This requires a change in napari/napari.github.io too; after that is done everything should work correctly.**
- [ ] This change requires a documentation update

# How has this been tested?

- [x] the docs build correctly

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

Closes #3529

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
thanks @melissawm!

**Review by neuromusic — APPROVED** [review]
LGTM

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Comment by jni** [comment]
@sofroniewn @neuromusic the whole reason tutorials was a different repo was to avoid bloating the main repo with pngs and gifs. A git clone of napari has gone from a 25MB download / 94MB disk usage (my remote, a few commits behind this one, `git@github.com:jni/napari`) to 184MB download / 365MB disk usage (this remote), in a single commit. What's more, this change is irreversible, even if we revert this commit, without changing the public history. Not to say anything of additional changes to the screenshots that will undoubtedly be necessary.

Nevertheless, I think it is worth doing that (rewriting the history), as only one additional commit has made it in. We should freeze new merges until we come to a decision, as every merge is a potential history rewrite.

**Comment by jni** [comment]
This is the procedure we would need to follow, for the record:
- git clone the current repo
- [remove the commit from the history](https://stackoverflow.com/questions/30893040/git-remove-commit-from-history)
- remove the branch protection from main
- `git push --force-with-lease`
- restore the branch protection

The consequence is that people who cloned the repo between the merge and the restored branch will end up with inconsistent histories and will have to deal with that. This is a fairly radical move so I'm happy to discuss, but I think we should discuss it.

**Comment by tlambert03** [comment]
> A git clone of napari has gone from a 25MB download / 94MB disk usage (my remote, a few commits behind this one, git@github.com:jni/napari) to 184MB download / 365MB disk usage (this remote), in a single commit.

Oh I can't believe I forgot that detail.  I agree with @jni, this is a big deal. And one that might be worth some radical changes to keep repo size reasonable.

If the solution required to keep all of the docs together in one place is a third repo (napari-docs), I'd be ok with that

**Comment by melissawm** [comment]
OOf. Sorry about that folks - it's on me. I should have checked and warned you before. Please let me know if you need me to do any of the steps above or if you'd rather take care of it.

**Comment by tlambert03** [comment]
> OOf. Sorry about that folks - it's on me

you and the three of us who also approved it! :joy:   don't worry, definitely not your fault.  :) everything is fixable

**Comment by sofroniewn** [comment]
I apologize also as the one that clicked merge, and did it without going a full 24 hours at which point we could have caught this.

I think removing the commit and doing the steps mentioned here makes sense https://github.com/napari/napari/pull/3815#issuecomment-994674958

I believe we'll also have to revert https://github.com/napari/napari.github.io/pull/305 which merged after this.

I guess we'll also have to try our "GitHub issues hosting" approach where we upload all the images to the issue and then use links. Does that seem feasible @melissawm?

**Comment by jni** [comment]
Here's the discussion @sofroniewn is talking about:

https://napari.zulipchat.com/#narrow/stream/298358-working-group-documentation/topic/how.20to.20add.20screenshots.2C.20gifs.2C.20and.20mp4s.20to.20docs/near/264815479

@neuromusic raised valid concerns about the long-term sustainability of the model, but I think it's ok for now. Our long-term goal is to dynamically generate screenshots and animations using publicly available data, so I think this is an ok placeholder for now.

Another alternative with only slightly more overhead is to put the files in a separate gh-pages repo and serve them from there.

**Comment by neuromusic** [comment]
oof indeed :D

if we're changing history anyway, we should consider instead leaving this merge in place and use (as @nclack suggested in the docs working group meeting) GitLFS for screenshots and static images.

there's a bit of configuration overhead for contributors _who need to add screenshots_ but otherwise, it should be transparent for the vast majority of contributions... its only when contributors need to touch/add the relevant files that they need the client and we can document this in the docs contributing guide that @DragaDoncila has developed (and has been waiting on this PR series to land)

**Comment by sofroniewn** [comment]
Right now I'm waiting on merging new PRs until this gets resolved, so addressing is high priority. I'm fine with either reverting and fixing history or continuing to merge new PRs.

**Comment by jni** [comment]
Ok, it is done:

Screen Shot 2021-12-16 at 6 54 31 pm

If anyone git-pulled or cloned between **Wed Dec 15 03:25:00 2021 -0300** (when this PR was merged) and **Thu Dec 16 18:53:50 2021 +1100** (when I force-pushed), they will need to either:

- delete their clone and start again, or
- follow the instructions below to delete their main branch and replace it with the current main.

@neuromusic leaving the PR and removing the files and switching to git-lfs wouldn't have solved the bloated repo issue. Once the merge is in, those objects are in the history forever (unless you rewrite history).

Anyway, have you used git-lfs? I have used it in a few projects and have found it painful to work with, so I would prefer the gh-pages solution.

### instructions for resetting main

- first, rename main, because you can't delete a branch if you have it checked out:

```
git switch main --create that-bad-timeline-where-biff-gets-the-almanac
```

- then, delete main:

```
git branch -D main
```

- finally, fetch the new main and switch to it:

```
git fetch upstream main
git checkout --track upstream/main
```

**Comment by brisvag** [comment]
> Anyway, have you used git-lfs? I have used it in a few projects and have found it painful to work with, so I would prefer the gh-pages solution.

I agree, I have used it before and it's a bit of a pain, mostly because it feels like you never know if you're doing things right or wrong. Also, there's all sorts of hosting limits and whatnot to keep track of, if you want to use github's hosting system. If instead you want to use an external hosting system: why not simply use links? Had I known the trick of gh-issues/pages i probably would have gone that route the first time.

**Comment by neuromusic** [comment]
@jni yes, I have used it.

> (unless you rewrite history)

that was my proposal... use BFG to rewrite this commit to use LFS and unbloat the repo. no worries if this is the path you prefer, though.

**Comment by melissawm** [comment]
This doesn't prevent any further work on the reorg, so we can take the time
to find a definitive solution that works best for napari. I will just
submit another PR to fix the events reference API docs and after that do
some research on possible solutions.

**Pull request merged**
