### PR TITLE
Disable arm64 installers temporarily

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

See https://napari.zulipchat.com/#narrow/stream/215289-release/topic/0.2E4.2E17/near/305192690 and https://github.com/napari/packaging/pull/36

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by Czaki** [comment]
it looks working but should target 0.4.17 branch

**Comment by jaimergp** [comment]
Check status for commit [df8dfd2](https://github.com/napari/napari/pull/5252/commits/df8dfd26a1ab856914375a2c10adb58d3795399d) to see how arm64 is now disabled. @andy-sweet

**Comment by jaimergp** [comment]
Hm, this diff is huge? I'll start from scratch.

**Comment by psobolewskiPhD** [comment]
@jaimergp it's the `docs` that were moved to the napari/docs repo.

**Pull request closed without merging**
