### PR TITLE
Drop additional perfmon test pass

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
As discussed in https://github.com/napari/napari/pull/2051#discussion_r550333758 this PR would drop the need for an additional pass through our tests with the `NAPARI_PERFMON` env var set. This will reduce our overall test time as there is some overhead for spinning up an new env with that var set, and it might make enabling/ disabling perfmon with our systems config a bit easier after something like #1183 merges as it reduces everything to a single `get_perf_config` call.

It was a little tricky as there were a variety of global vars set in the file inits before (which would be set before I could monkeypatch the env var in pytest), but I'm now using an `lru_cache` with `maxsize=1` to capture the env var once, but have that capture be after the file inits are called.

I also had to do a little to avoid circular imports etc.

It would probably good to get a little more independent testing of this in case I messed anything up, but I think it's good to go.

## Type of change

- [x] Refactor (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by sofroniewn** [comment]
Hmm, running into some test failures on CI here. I suspect it is something to do with creating/ destroying the QApplication which was done to provide the modified app for tracing. This is done with `convert_app_for_tracing`. The first test with this doesn't pass and subsequent ones fail too.

All `_qt` tests pass locally for me, though I do wonder after the perf test if we now have the modified QApp for the rest of our tests, which might not be so desirable ...

**Comment by sofroniewn** [comment]
Comment here https://github.com/napari/napari/blob/v0.4.2/napari/_qt/tracing/qt_event_tracing.py#L35-L36 implies we have to do this creating/ destroying before creating any other Qt elements, but then I'm not sure why it passes locally.

I can create another method that would return a `QApplication` if given a `QApplicationWithTracing` to go in the other direction, but this would be easier if we didn't have to make/ destroy the QApp

**Comment by sofroniewn** [comment]
Very cool to see here the "headless" test pass, but the Qt tests fail :-) Was expected in this case, but such a nice addition from the recent cleanup @tlambert03!!!

**Comment by tlambert03** [comment]
> Very cool to see here the "headless" test pass, but the Qt tests fail :-) Was expected in this case, but such a nice addition from the recent cleanup @tlambert03!!! 

Awesome!

**Comment by sofroniewn** [comment]
Looked into this a little more and deleting/ creating the QApp during tests does seem really tricky (or possibly not going to work), see some discussion on this here https://github.com/pytest-dev/pytest-qt/issues/37. Note sure how to proceed yet

**Comment by sofroniewn** [comment]
Here is some discussion around the original choice to create/ delete the app as monkey patching notify didn't work https://stackoverflow.com/questions/62180549/how-can-i-monkey-patch-pyqts-qapplication-notify-to-time-events

**Comment by sofroniewn** [comment]
Ok, I think I've made some progress by creating a fixture that just gets called once to create the custom QApp, see instructions here https://pytest-qt.readthedocs.io/en/latest/qapplication.html#testing-custom-qapplications. I'm still getting some test failures on CI, but I have a little more hope now that we can figure this out

**Comment by tlambert03** [comment]
> Ok, I think I've made some progress by creating a fixture that just gets called once to create the custom QApp

Great work!
I made a slight change to turn `qapp` into a module-scoped fixture, which seemed to have fixed the segfaults on PyQt5.  Pyside2 still wasn't working though, which turned out to be an issue with the way `shiboken2.delete(app)` works (or rather, doesn't work?).  Through some trial and error, I found that calling `QApplication.instance()` _after_ calling `shiboken2.delete(app)` is necessary to be able to create another QApplication.  See https://bugreports.qt.io/browse/PYSIDE-1470

Then somehow figured out that we need to call `delete_app` in the `qapp` fixture before creating the modified app... but _only_ on PySide2.  It's working now for both backends on mac, and windows, but pyside2 is still struggling on linux.

Ultimately, my main goal here was just getting rid of the `--use-perfmon` marker, which will definitely happen, and if I can't figure out pyside2 on linux, we can also just skip that module for pyside2 on linux

**Comment by tlambert03** [comment]
ok, skipped pyside2 on linux on CI.  I can't even reproduce the segfault on linux with Pyside2 if I log into my work linux box, so I'm not too worried about it.  very happy with this now.
@sofroniewn, the only question I had was about exchanging `perf.USE_PERFMON`, which I felt was rather clear as a boolean for `get_perfmon_config`.  Is there something else that swap is useful for?

**Review by tlambert03 — APPROVED** [review]

**Comment by sofroniewn** [comment]
> ok, skipped pyside2 on linux on CI. I can't even reproduce the segfault on linux with Pyside2 if I log into my work linux box, so I'm not too worried about it. very happy with this now.

Amazing, yes, I think the skipping along with the comments is fine. Great work.

> @sofroniewn, the only question I had was about exchanging perf.USE_PERFMON, which I felt was rather clear as a boolean for get_perfmon_config. Is there something else that swap is useful for?

I needed `get_perfmon_config` because otherwise the env variable in `perf.USE_PERFMON` was getting set before I was able to mock it in the test I needed it (as it was happening on imports). I also prefer `perf.USE_PERFMON` but couldn't figure out how to get it working. If you can please do change it. I'd say that goes for this whole PR, I played with things till I got it working but am not wedded to any of the particular details

**Comment by tlambert03** [comment]
ok, was able to revert most of the USE_PERFMON stuff.  The key monkeypatch here is patching `napari._qt.perf.qt_event_tracing.perf.perf_timer` (which is what `QApplicationWithTracing` is going to use) rather than `napari.utils.perf.perf_timer`.  (Named importation creates a new name for the object. If you then replace the object at it's original namespace the "new" imported name is unaffected)

**Comment by sofroniewn** [comment]
> ok, was able to revert most of the USE_PERFMON stuff. The key monkeypatch here is patching napari._qt.perf.qt_event_tracing.perf.perf_timer (which is what QApplicationWithTracing is going to use) rather than napari.utils.perf.perf_timer

Very nice! This is a much much nicer approach, well done. The changes here to the actual perf system are now much much less, which I like, and we dropped the extra test pass. This is a great outcome and I will merge now!! Thanks for your help

**Pull request merged**
