### PR TITLE
MAINT: Fix vendoring script and track closest commit.

### PR DESCRIPTION
**Pull request by Carreau**
For two on the vendored file, try to track the closes version. None of the files are exact match, in particular imports were modified by absolute importify, but this should allow to at least track the modification that were done in a later pass, and later update them.

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by Czaki** [comment]
> in particular imports were modified by absolute importify

We could revert this absolutely. That was my bad that Ido not revert this when add vendored to excluded paths

**Comment by Carreau** [comment]
That's fine, those were not the only changes, and most of these files will need manual modification anyway to work on napari. Here it's just one step so that once we know were all the file come from we can decide what to do.

**Review by Czaki — APPROVED** [review]

**Comment by brisvag** [comment]
Still think absolutify should be reverted though :)

**Comment by Czaki** [comment]
> Still think absolutify should be reverted though :)

Globally or in a vendor only? in #5590 the TID rule from ruff is used instead of absolutiify and allows for better configuration.

**Comment by brisvag** [comment]
Definitely vendor only!

**Comment by Carreau** [comment]
thanks.

**Pull request merged**
