### PR TITLE
Keep shading light for Surface fixed relative to camera

### PR DESCRIPTION
**Pull request by brisvag**
# Description

Currently, if `Surface` shading is set to `flat` or `smooth`, the light is fixed in *data space*. This makes it hard to see any features on the "shadow" side of the surface.

This PR updates the light position every time the camera moves, in order to always keep it "behind the camera on the top right". We could potentially expose this at some point, but this is a net positive compared to what we have now.

Here's the difference between this PR (above) and main (below):

https://github.com/napari/napari/assets/23482191/9be5ebe4-7751-40f7-900c-c5765bf2c7bd

https://github.com/napari/napari/assets/23482191/39ce8f22-2694-4488-b26c-cbf097fc0526

I'm not 100% on the implementation, because I had to add a connection between the camera and the layers, which is normally not there, so it's entangling things a bit more... But I'm not sure there's a smarter way to deal with it. One good thing is that the layer *model* is not involved at all, so this is not increasing the "layer state" burden.

# References

- #2407

### CODE REVIEW

**Comment by aganders3** [comment]
Thanks for doing this! I noticed it during testing of textured surfaces but used napari-threedee to work around it. I agree it should probably be the default though. For what it's worth I think [this is the the relevant code from napari-threedee](https://github.com/napari-threedee/napari-threedee/blob/c67421b8d343b3f6f15bc18d78df8e5cf6d94487/src/napari_threedee/visualization/lighting_control.py#L51) if you'd like to compare.

**Comment by brisvag** [comment]
Basically the same idea; main difference is that napari-threedee is using only the view direction (basically, as if you had a head lamp on), but here I'm setting the light at an angle (as if you had a tall friend on your right with a head lamp :P).

**Comment by brisvag** [comment]
> There's a little bug with textured surfaces. I suspect it might not be a new bug, just exposed by the new light behaviour:
> lighting_bug.mp4

@aganders3 I can't really wrap my head around the issue with the middle cow here. Testing in just vispy seems to work perfectly fine, so the vertex-based coloring should be capable of handling flat/smooth shading just fine. Any ideas? Otherwise, I propose we merge as is (or at most expose an option to set "fixed light" or "follow camera"?)

**Comment by aganders3** [comment]
I just got to play with this and I think I figured it out. It's not a problem with the vertex values, it was a problem with *multiple* vertex values as the plasma cow has an extra dimension on the values. This comes through when converting the camera directions from world into data coords. It think moving the "reverse" operation to *after* the indexing fixes it.

```diff
diff --git a/napari/_vispy/layers/surface.py b/napari/_vispy/layers/surface.py
index a7bbb64ec..bbb7bea03 100644
--- a/napari/_vispy/layers/surface.py
+++ b/napari/_vispy/layers/surface.py
@@ -199,11 +199,11 @@ class VispySurfaceLayer(VispyBaseLayer):
         ):
             # convert to data coords and flip xyz for vispy
             camera = event.source
-            up = self.layer.world_to_data(camera.up_direction)[::-1]
-            view = self.layer.world_to_data(camera.view_direction)[::-1]
+            up = self.layer.world_to_data(camera.up_direction)
+            view = self.layer.world_to_data(camera.view_direction)
             dims_displayed = self.layer._slice_input.displayed
-            up = np.array(up)[dims_displayed]
-            view = np.array(view)[dims_displayed]
+            up = np.array(up)[dims_displayed][::-1]
+            view = np.array(view)[dims_displayed][::-1]
             # combine to get light behind the camera on the top right
             self._light_direction = view - up + np.cross(up, view)
```

**Comment by brisvag** [comment]
Awesome @aganders3, works perfectly! Pushed the change, no more outstanding issues :)

**Comment by brisvag** [comment]
>     1. I wonder whether it would not be a lot of extra work to add a View menu toggle, "light follows camera", that would let you turn this behaviour on and off at will. This would be nice because users would then have a mechanism for placing the light somewhere in the scene and then leaving it there.

Saving the position I guess would require a bit more work to get it exposed on the viewer (or canvas, or camera) model. This is definitely something we want, but I thought it's easier to go step by step. Alternatively we could add a simple toggle (maybe in experimental settings) just so we can let poeple disable this if the don't like it?

>     2. Lots of untested lines... :sweat_smile: It's probably reasonably easy and effective to use the qt viewer tests to add a surface layer, set the shading mode, and move the camera around a couple of times?

And check just that the value is propagated to the `VispyLayer`? Yes, we could do that.

---

Btw, I remove the transformation from world coordinates... that was actually wrong, cause camera up and down directions are already in "scene" space. Testing with heavily rotated layers seems to work as intended now, but was broken before.

**Review by kephale — APPROVED** [review]

**Comment by Czaki** [comment]
Does this should be cherry-picked to 0.4.18?

**Comment by brisvag** [comment]
> Does this should be cherry-picked to 0.4.18?

not sure if this is still a question, but if so, I would say it can go in; there's no breaking changes, just a visual improvement.

**Comment by jni** [comment]
I caught up with @Czaki yesterday, who has limited time for the next couple of weeks, so I suggest we feature-freeze 0.4.18 and leave this for 0.5.0.

**Pull request merged**
