### PR TITLE
Clean dangling widget in test 

### PR DESCRIPTION
**Pull request by Czaki**
# Description

in `test_making_plugin_dock_widgets` we test if the widget is correctly removed from napari viewer but do not ensure that it is deleted. 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
This is the nasty error we see everywhere right? Let's get it in asap :P

**Comment by Czaki** [comment]
> This is the nasty error we see everywhere right? Let's get it in asap :P

Yes, It is try to fix this.

**Comment by brisvag** [comment]
Looks liek you got it, nice!

**Comment by Czaki** [comment]
> Looks liek you got it, nice!

I will restart the tests a few times to ensure.

**Comment by psobolewskiPhD** [comment]
Is this one to maybe waive the 24 hr clock and just get merged?

**Comment by Czaki** [comment]
The problem that I see is that all min req tests are timeout

**Comment by Czaki** [comment]
> The problem that I see is that all min req tests are timeout

Ok. Bug is unrelated to this PR. It is our bad minimum requirement configuration. It stuck on the dependency resolver.

**Comment by Czaki** [comment]
@brisvag @psobolewskiPhD, what did you think about this. Could I merge this with the hanged minimum requirement test?

**Comment by psobolewskiPhD** [comment]
Hmm, I mean it's definitely progress? 
Still results in the ❌ but maybe a more easily ignored ❌?

**Comment by brisvag** [comment]
Yes, let's merge. The minreq failure is unrelated and we sould handle it elsewhere, but at least this solves the other test failures.

**Pull request merged**
