### PR TITLE
Add "select all" to points and shapes layer

### LINKED ISSUE #2353: Add option for changing point size with no points selected to change the sizes of all points.
## 🚀 Feature

As in the title.

## Motivation
I see the appeal of having variable sized points, but for my use case I would like all points to be same the size.

## Pitch

I would like the `point size` slider to change the size of all points if None are selected.

Alternatively, the points layer could have a mode that enforces all points to have the same size and the point size slider affects their size regardless of whether or not they are selected or visible on the current slice.

## Alternatives
I get over myself and just remember to select the points when I resize them (this is not so bad of an outcome :grinning: )

## Additional context
I think I expected the point size to be equivalent to the `s` argument to a matplotlib scatter plot.

### PR DESCRIPTION
**Pull request by mstabrin**
# Description

I propose to add a new checkbox "select all" for the points and shapes layer.
If checked, changes to the colors, size, and edge_width are propagated to influence all points/shapes of the respective layer. 

image
image

## Type of change
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# References

Similar ideas have been mentioned here:
https://github.com/napari/napari/issues/702
https://github.com/napari/product-heuristics-2020/issues/19
closes https://github.com/napari/napari/issues/2353

# How has this been tested?

- [X] the test suite for my feature covers all properties of Shapes and Points covered by my change
- [X] all tests pass with my change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
@mstabrin Thanks for the suggestion! However, I don't think this is the correct implementation — selection with a checkbox is a very non-standard UX design. Note that you might have missed that there is already a keyboard shortcut for this, "A".

I think the correct fix is to add an edit menu with all the standard edit menu choices, such as "Edit > Select all" "Edit > Cut/Copy/Paste", etc. However, I think that @tlambert03's app-model refactor (#4784) is probably a prerequisite for this. @tlambert03 what do you think? Is it worth adding an "ad-hoc" edit menu now or should we wait for app model to land?

In the meantime, I propose closing this PR as I don't see the tick box as the correct implementation in any context.

A final comment: in the early days of napari I made the point that since napari isn't a typing app, we could use keyboard shortcuts without modifiers, such as "V" (toggle visibility) and "A" (select all), in the style of Gmail/Fastmail and others. I still think that's the right model for *most* shortcuts (e.g. the mode changes for labels layer on 1-5), *but*, for standard shortcuts such as cut/copy/paste/select all that appear across almost all apps, I think we should use the standard Ctrl/Cmd+key. The main issue that this PR addresses is that the shortcut is not discoverable. But using a standard shortcut from ~all apps addresses discoverability quite well.

**Comment by mstabrin** [comment]
@jni Thank you for your input :) Maybe we can talk about the behavior of the "A" shortcut.
I am working a lot with 3D point layers in large volumes, i.e., up to 4kx4kx4k.
The "A" shortcut seems not to select all points of the layer, but only of the current visible slice.
Maybe I should look into the "A" shortcut implementation then? :)
It appears that multi-selection on non-visible slices should be supported?

**Comment by mstabrin** [comment]
And we can close this PR :)

**Comment by jni** [comment]
Ah! Damn. Yeah that's difficult, because we need a visual indicator of what's happening across slices. My suggestion after thinking about it for 10s: 😂

- Cmd-A select all points in this slice, raise notification "Selected [n] points in this slice, use Cmd-Shift-A to select all points on layer."
- Cmd-Shift-A select all points, raise notification "Selected [n] points across all slices, including [m] points not currently visible"

Ok I'll close this but we can keep discussing here until we come up with a path forward.

**Comment by mstabrin** [comment]
@jni I made a suggestion based on your suggestion at PR #4809.
I also added a "deselect" option in case the points are already selected similar to other Control-A behaviors in other software.

**Pull request closed without merging**
