### PR TITLE
Remove 3D multiscale warning

### LINKED ISSUE #5588: Multiscale 3D rendering warning should happen once only
When I switch to 3D view in a multiscale array, I get the following warning:

```pytb
/Users/jni/projects/napari/napari/layers/image/_slice.py:113: UserWarning: Multiscale rendering is only supported in 2D. In 3D, only the lowest resolution scale is displayed!
```

This is fine, except the warning happens on *every* slice event:

```pytb
...
/Users/jni/projects/napari/napari/layers/image/_slice.py:113: UserWarning: Multiscale rendering is only supported in 2D. In 3D, only the lowest resolution scale is displayed!
/Users/jni/projects/napari/napari/layers/image/_slice.py:113: UserWarning: Multiscale rendering is only supported in 2D. In 3D, only the lowest resolution scale is displayed!
/Users/jni/projects/napari/napari/layers/image/_slice.py:113: UserWarning: Multiscale rendering is only supported in 2D. In 3D, only the lowest resolution scale is displayed!
/Users/jni/projects/napari/napari/layers/image/_slice.py:113: UserWarning: Multiscale rendering is only supported in 2D. In 3D, only the lowest resolution scale is displayed!
...
```

That's a fraction of the console output, and the toast pop-up on the canvas just keeps popping as you interact with the viewer.

@kephale is making good progress to help us get rid of that warning altogether, but in the meantime, a quick fix would be to set a flag for whether we've warned already, and not warn if so.

### PR DESCRIPTION
**Pull request by jni**
# Fixes/Closes

Closes #5588

# Description

This bugs me all the time. Ultimately I would rather get bug reports from
people expecting proper 3D multiscale rendering (rare in our community) than
seeing this warning non-stop, or having to constantly cherry-pick this commit
into my current working environment.

I also expect @kephale's work will make this redundant soon anyway, so in the
meantime, I just want the warning gone. Hopefully others agree that it does not
add enough value to be kept around.

## Type of change
- [x] Enhancement (non-breaking improvements of an existing feature)

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Review by GenevieveBuckley — APPROVED** [review]
I'm on board with this. It's not useful to have lots of warnings that people should just get in the habit of ignoring.

**Review by Carreau — APPROVED** [review]

**Comment by GenevieveBuckley** [comment]
> Also good with this. Though we should also strongly consider not using `catch_warnings` anywhere given its side-effects are the underlying cause here and could spam other warnings in frequently hit code paths.

Should your comment  be made into an issue @andy-sweet ?

**Comment by psobolewskiPhD** [comment]
Blerg. Big drawback of this is that by not warning a user at all/ever , they will not know they can potentially improve the display with their choice of lowest multiscale level.

**Comment by jni** [comment]
Yeah, sorry, just as a reminder: this happened because there is no way *not* to spam the viewer, due to a (still open) bug in CPython.

**Pull request merged**
