### PR TITLE
Fix key error issue of action manager

### LINKED ISSUE #5535: [Minor bug] Key errors when using functionality of label layer
## 🐛 Bug

In Napari when having created a label layer and upon switching to either erase, paint, fill, picker or zoom, a key error is given. 
This is due to the key not being present in the _actions dictionary of the ActionManager of napari.utils. One example of the error is
afbeelding
 
In this case the key should have been napari:activate_labels_paint_mode (see image below). Also for the other cases adding labels in the keyword would fix this issue. The functionality does not seem to have changed. Transform, erase, .... seem to still work, thus it seems to be a minor bug. It seems to be introduced with the recent merge of #4894.
afbeelding

## To Reproduce

1. Start Napari
2. Create labels layer
3. Switch to either one of the modes described above.

## Expected behavior

No key errors.

## Environment

napari: 0.4.17rc4.dev180+gd7b22b19.d20230125
Platform: Windows-10-10.0.22621-SP0
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:51:29) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.4
SciPy: 1.9.3
Dask: 2022.11.0
VisPy: 0.12.1
magicgui: 0.6.0
superqt: 0.4.0
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.1

OpenGL:
- GL version: 4.6.0 NVIDIA 526.98
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Settings path:
- C:\Users\w-mv\AppData\Local\napari\napari_e081f750b90253ee1b4c7328e2bd7ed6bfeabc20\settings.yaml

### PR DESCRIPTION
**Pull request by melonora**
# Description
Fixes the issue described in #5535. Due to the action manager bindings being incorrect, key errors were thrown when using the functionality of the labels layer.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
#5535 

# How has this been tested?

Passed the tests in napari.layers and manually tested

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by melonora** [comment]
Errors fail due to known memory leak issue not caused by these code changes.

**Review by Czaki — APPROVED** [review]

**Review by psobolewskiPhD — APPROVED** [review]

**Comment by Czaki** [comment]
starting 24h clock

**Comment by goanpeca** [comment]
Thanks for working on this @melonora.

---

@Czaki do you have some ideas how we could tests this to catch any typos in the future ?

**Comment by Czaki** [comment]
As I understand, we plan to move out of action manager to app_model. 

And as I understand the app model approach allows to validation action existence on binding.

**Pull request merged**
