### PR TITLE
Remove toggle theme from drop down menu. 

### LINKED ISSUE #2450: Remove toggle theme option
## 🐛 Bug

Since there can be more than 2 themes, this option should be removed.

Screen Shot 2021-03-22 at 10 54 03 AM

## To Reproduce

1.
2.
3.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

@liaprins-czi your advice is greatly appreciated :)

### PR DESCRIPTION
**Pull request by ppwadhwa**
# Description

Remove theme toggle option from view menu.  Add in keybinding to cycle through available themes.

Fixes #2450 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Carreau** [comment]
LGTM, two questions on the longer term:
 - Do we want a keybinding ? I'm guessing users rarely toggle theme, and shortcut are getting rare?
 - Need to find a better way to bind shortcut that do not need a viewer (i'll think about that in the action manager).

**Review by sofroniewn — APPROVED** [review]
This looks good to me, and seems like a fine PR to merge as is, but I do appreciate the point from @Carreau that we might want to drop keybinding eventually too. If so then I think we could add a deprecation warning and do in another PR, but now might be a good time for @jni or @tlambert03 to weigh in on that. I'm fine delaying though, it doesn't feel urgent

**Comment by ppwadhwa** [comment]
@sofroniewn I can add a warning, if you'd like.  I included the keybinding because of the discussion in #2450.  I will wait for a confirmation either way.

@Carreau I agree that binding this shortcut seems like a job for the action manager.  :)

**Comment by tlambert03** [comment]
The theme shortcut is one of the the ones that I use... so if it's easy enough to keep it, I'd like that.  But I would probably get over it if/when it's time for it to go :)

**Comment by sofroniewn** [comment]
Ok, I think let's leave for keybinding for this PR (thanks for making sure to keep it @ppwadhwa), but as we continue to reorganize our keybindings we'll keep in mind that this is one we might eventually drop/ make opt in.

**Review by tlambert03 — APPROVED** [review]
This is good by me, thanks @ppwadhwa.  I'm approving, but one minor request: i think we should probably remove the `ViewerModel._toggle_theme` method, as it won't be used anymore after this (and it was really only there for that QAction anyway).

**Comment by ppwadhwa** [comment]
> This is good by me, thanks @ppwadhwa. I'm approving, but one minor request: i think we should probably remove the `ViewerModel._toggle_theme` method, as it won't be used anymore after this (and it was really only there for that QAction anyway).

thanks, @tlambert03 !   That was a good catch.  I removed it.  :)

**Comment by jni** [comment]
:pray: :tada:

**Pull request merged**
