### PR TITLE
two small path improvements

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
two small tweaks the i think will improve various lingering bugs in the bundle and in icon building.

I _think_ the first one may be behind what @will-moore  saw in https://github.com/napari/napari/pull/1289#issuecomment-658656172

and the second may fix some issues with building icons in a bundled environment

### CODE REVIEW

**Comment by sofroniewn** [comment]
Changes look fine in theory to me, but there's one failing test `test_path_pollution` which should either be fixed or changed before merge. Happy to merge after that!

**Comment by tlambert03** [comment]
@Czaki, can you take a look at this?  I'm not exactly sure what `test_path_pollution` test is doing by monkeypatching `sys.executable`.  This PR tries to call the `pyside-rcc` or `pyrcc5` scripts with the python interpreter that was used to execute the program (rather than whatever they put in the header... which may come from a CI environment)... but it's failing your test and I'm not sure why.

**Comment by Czaki** [comment]
> @Czaki, can you take a look at this? I'm not exactly sure what `test_path_pollution` test is doing by monkeypatching `sys.executable`. This PR tries to call the `pyside-rcc` or `pyrcc5` scripts with the python interpreter that was used to execute the program (rather than whatever they put in the header... which may come from a CI environment)... but it's failing your test and I'm not sure why.

I monkeypatch `sys.executable` because python dir is added at begin of a path which prevents calling mock script (but does not workaround problem with pyenv) 

Bellow, I add a workaround of the python problem 

```
diff --git a/napari/resources/test_resources.py b/napari/resources/test_resources.py
index 47b0ff2d..56aad2b3 100644
--- a/napari/resources/test_resources.py
+++ b/napari/resources/test_resources.py
@@ -29,24 +29,30 @@ def test_path_pollution(tmp_path, monkeypatch, capfd):
     executable_path = shutil.which(executable_name)
     (tmp_path / "path").mkdir()
     with open(tmp_path / "path" / "pyrcc5", "w") as f_p:
-        f_p.write("#! /usr/bin/env bash\n\n")
-        f_p.write("echo Fake pyrcc5 executable\n")
-        f_p.write("exit 10")
+        f_p.write("#! /usr/bin/env python\n\n")
+        f_p.write("import sys\nprint('Fake pyrcc5 executable')\n")
+        f_p.write("sys.exit(10)")
 
     with open(tmp_path / "path" / "pyside2-rcc", "w") as f_p:
+        f_p.write("#! /usr/bin/env python\n\n")
+        f_p.write(f"import sys, subprocess\nsubprocess.check_call(['{executable_path}'] + sys.argv[1:])\n")
+
+    with open(tmp_path / "path" / "python", "w") as f_p:
         f_p.write("#! /usr/bin/env bash\n\nset +x\n")
-        f_p.write(f"{executable_path} $@\n")
+        f_p.write(f"{sys.executable} $@\n")
 
     (tmp_path / "path" / "pyrcc5").chmod(0o777)
     (tmp_path / "path" / "pyside2-rcc").chmod(0o777)
+    (tmp_path / "path" / "python").chmod(0o777)
 
     monkeypatch.setenv(
         "PATH", os.pathsep.join([str(tmp_path / "path"), os.environ["PATH"]])
     )
-    monkeypatch.setattr(sys, "executable", str(tmp_path / "python"))
+    monkeypatch.setattr(sys, "executable", str(tmp_path / "path" / "python"))
     build_pyqt_resources(str(tmp_path / "resources.py"))
     assert (tmp_path / "resources.py").exists()
 
     if platform.system() != "Windows":
         captured = capfd.readouterr()
         assert "Fake pyrcc5 executable" in captured.out
```


> I _think_ the first one may be behind what @will-moore saw in [#1289 (comment)](https://github.com/napari/napari/pull/1289#issuecomment-658656172)

This log comes from building numcodecs wheels. A few days ago numcodecs wheels are published on pypi.

**Comment by tlambert03** [comment]
I know it comes from building wheels... but if a computer is able to build wheels outside of the bundle, then it should be able to build inside of the bundle.  The PATH problem in that log above is fixed by this PR...

**Comment by Czaki** [comment]
Ok. I see that I wrong understand the code. If patch which I provide works for you?

**Comment by tlambert03** [comment]
I'll try it in a bit.  Thanks for the help!

**Comment by tlambert03** [comment]
looks like tests are passing every but windows now @Czaki
https://cirrus-ci.com/task/6365823591776256?command=test#L1559

**Comment by Czaki** [comment]
Skip this test on windows.

**Comment by tlambert03** [comment]
ready @sofroniewn

**Review by sofroniewn — APPROVED** [review]
Looks good to me! Thanks both, I will merge now!!

**Pull request merged**
