### PR TITLE
Use `delete` instead of `get`method for delete `ready to merge` label

### LINKED ISSUE #7159: Upgrade test constraints is failing to remove `ready to merge` label
## 🧰 Task

Upgrade test constraints is failing with following stacktrace:

```python
Traceback (most recent call last):
  File "/home/runner/work/napari/napari/tools/create_pr_or_update_existing_one.py", line 348, in <module>
    main()
  File "/home/runner/work/napari/napari/tools/create_pr_or_update_existing_one.py", line 335, in main
    create_pr_with_push(branch_name, access_token)
  File "/home/runner/work/napari/napari/tools/create_pr_or_update_existing_one.py", line 141, in create_pr_with_push
    update_own_pr(pr_number, access_token, branch_name, repo)
  File "/home/runner/work/napari/napari/tools/create_pr_or_update_existing_one.py", line 175, in update_own_pr
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/napari/napari/issues/7138/labels/ready%20to%20merge

```

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues

closes:  #7159

documentation: https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#remove-a-label-from-an-issue 

# Description

### CODE REVIEW

**Review by lucyleeow — APPROVED** [review]
Thanks

Actually, with `delete` if the label is not present, do you get the 404 error still?

**Comment by Czaki** [comment]
> Actually, with `delete` if the label is not present, do you get the 404 error still?

I do not remember which code, but I got an error response (4xx code)

**Comment by lucyleeow** [comment]
> I do not remember which code, but I got an error response (4xx code)

So would the `response.raise_for_status` still result in an error, even if you use delete?

**Comment by Czaki** [comment]
> So would the `response.raise_for_status` still result in an error, even if you use delete?

No, because above, I check if label is already assigned to PR.

**Pull request merged**
