### PR TITLE
Test bundle installation in CI

### LINKED ISSUE #3602: Test bundle installation on CI?
## 🧰 Task

Right now we have CI to test that the bundles can be _created_ across platforms, but we do not try to install them and see if at least we can get the `napari --help` output. We can always check the bundles locally and run the installation (which can take a few mins), but right now we don't have a consistent check protocol across OSs.

Thoughts? Is this a good idea or overkill?

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Closes https://github.com/napari/napari/issues/3602

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — COMMENTED** [review]
Looks like "Conda / Create packages (pull_request)" CI is failing - I suspect that should be fixed before merge. Error message is

```
RuntimeError: conda-smithy version (3.18.0) is out-of-date (3.19.0) in conda-smithy's environment. Exiting.
```

**Comment by jaimergp** [comment]
I think that was a temporary issue because the CI just happened to run between CDN syncs after a new conda-smithy release. Re-running now and seems to work.

**Comment by jaimergp** [comment]
`osx-arm64` is having issues due to Anaconda.org being flakey today (error 500 here and there). It's not relevant since this PR only adds a testing phase _after_ the installers are created, but we can't run arm64 code, so it would be skipped on that platform. The other platforms are all passing successfully! So this is ready for review @sofroniewn!

**Review by sofroniewn — COMMENTED** [review]
> osx-arm64 is having issues due to Anaconda.org being flakey today (error 500 here and there). It's not relevant since this PR only adds a testing phase after the installers are created, but we can't run arm64 code, so it would be skipped on that platform.

Do we think that long term this will be stable? It might be better to disable test rather than have it failing sporadically and confusing people when they see tests fail

**Comment by sofroniewn** [comment]
> Do we think that long term this will be stable? It might be better to disable test rather than have it failing sporadically and confusing people when they see tests fail

Oh my bad, that is independent of this PR, i get it now. I will approve then - thanks!!

**Review by sofroniewn — APPROVED** [review]

**Review by tlambert03 — APPROVED** [review]

**Review by liu-ziyang — APPROVED** [review]
Looks great! thanks for adding this! 

one thought though: as the build pipeline becomes heavier, we may want to tweak our CI to run it less frequently, as most PRs shouldn't break the bundle and may not require CI to trigger this whole flow

**Comment by jaimergp** [comment]
> we may want to tweak our CI to run it less frequently

Absolutely. I was thinking of something like label-based on PRs, nightlies only on `main`. But we can discuss that in a separate PR.

**Pull request merged**
