### PR TITLE
Fixes gallery ToC

### LINKED ISSUE #4963: DOC Sidebar ToC missing in gallery examples
## 📚 Documentation
In the dev version of the docs, the sidebar ToC is missing when you click on any of the gallery examples (https://napari.org/dev/gallery/add_image.html#):

image

Sidebar ToC is present in the stable version of the docs (https://napari.org/stable/gallery/add_image.html#):

image

Do you think it could have something to do with https://github.com/napari/napari/pull/4936 @melissawm ?

### LINKED ISSUE #5057: Gallery ToC shows both tags and individual examples
## 📚 Documentation
After merging PR #4975 we now have both tags and the original example list shown on the left-hand side
image
Since we can already browse all examples with image tiles, removing the text list and only keeping the tags could make the navigation cleaner.

### PR DESCRIPTION
**Pull request by melissawm**
# Description

- Orders gallery by example title
- Restores left sidebar for individual example pages 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
Closes napari/napari#5057 
Closes napari/napari#4963

This PR also depends on napari/docs#85

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by melissawm** [comment]
Before:

before

After:

after

**Comment by psobolewskiPhD** [comment]
Merged main, should fix tests...

**Comment by melissawm** [comment]
~Moving into draft until https://github.com/napari/docs/pull/85#issuecomment-1374833105 is resolved.~ This is good to go!

**Review by psobolewskiPhD — APPROVED** [review]
I tested this with the docs PR as well
https://github.com/napari/docs/pull/85#issuecomment-1379310485
works as advertised!

**Pull request merged**
