### PR TITLE
colormap presention in dropdown list

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Add colormap presentation to dropdown menu. 

dropdown_napari

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# References

I base on my own code from PartSeg 

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
This is looking really nice @Czaki - following the discussion with @jni here in the zulip https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Dropdown.20colobar/near/216544204 I can take this over and tweak some of the stylings. I might also put the new class in its own file as well. Thanks very much for this!!

**Comment by Czaki** [comment]
I also have some idea how to implement searching using a name, when not all names are visible by default. 

But maybe this should be placed in another PR after finish this? 
There is some split on all, and showed colormap list?

But I will be happy with all visuall tweaks.

**Comment by sofroniewn** [comment]
> I also have some idea how to implement searching using a name, when not all names are visible by default.
>
> But maybe this should be placed in another PR after finish this?

Yes, I'd work on that in a new PR. You can see some previous discussion of that here when we used to have a long list of colors for points and shapes. Same concept applies though, and we'd probably want that to be a reusable piece of functionality. https://github.com/napari/napari/issues/268

**Comment by Czaki** [comment]
If this class will be part of public API (exported by qt module) I will try to use it in PartSeg to unify user experience. 

In general, it could be useful for a person who would like to build on top of napari tool where a user does not control a list of layers (fixed formatting for some data type).

**Comment by sofroniewn** [comment]
This was really easy to work with, great job @Czaki. I've update the PR now to make the boxes thinner and smaller as @jni suggested. I think this is now good enough visually to merge, but i encourage @jni and others to try it out and give feedback before we merge.

> If this class will be part of public API (exported by qt module) I will try to use it in PartSeg to unify user experience.
> 
> In general, it could be useful for a person who would like to build on top of napari tool where a user does not control a list of layers (fixed formatting for some data type).

I've left this as private for now, we might end up tweaking the visual styles a bit more of this over the next few releases as we get more user feedback, so I don't want you to have to constantly be updating things if we change them a bit based on that user feedback.

Here is the current look

Screen Shot 2020-11-15 at 11 48 40 AM

One thing I noticed is that the background color of the selected row isn't changed, instead the border of the colormap is highlighted in black. I think i probably preferred the look of having the background color of the selected row change. Is that possible to preserve @Czaki ? I don't think we'd then need both border highlighting and background color changing

image

**Comment by Czaki** [comment]
> One thing I noticed is that the background color of the selected row isn't changed, instead the border of the colormap is highlighted in black. I think i probably preferred the look of having the background color of the selected row change. Is that possible to preserve @Czaki ? I don't think we'd then need both border highlighting and background color changing

The main problem is to know this highlight color. As I understand it is named ``{{primary}}` in qss files. But Qt does not allow to simply check this color. 

I do some workaround using super call. @sofroniewn Could you check now? 

There is still no ✓ showing current one. It is a problem? 

I increase height of entry, because lower part of 'g', 'y' etc letters are cutted on ubuntu. I also need to increase the length of entry, because `twilight_shifted` does not fit.

**Review by sofroniewn — APPROVED** [review]
Looks great to me, thanks for that change @Czaki!

Here is how it looks now which I like.

Screen Shot 2020-11-15 at 1 03 05 PM
 
I'm approving, will wait to merge until others have commented. Thanks again

**Review by jni — APPROVED** [review]
I love this so much! Thanks @Czaki! (And @sofroniewn for the finishing touches!)

**Pull request merged**
