### PR TITLE
Enabe tags in gallery examples.

### PR DESCRIPTION
**Pull request by melissawm**
# Description

This PR enables tags for the examples in the gallery using the [sphinx-tags extension](https://github.com/melissawm/sphinx-tags).

Co-authored-by: chili-chiu <89602983+chili-chiu@users.noreply.github.com>

EDIT: Here's the link to the built artifacts https://github.com/napari/napari/suites/7950693509/artifacts/339488705

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Reference

Supersedes #4372

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by Carreau — APPROVED** [review]

**Comment by lucyleeow** [comment]
Not sure if the path is just wrong but when clicking on one of the tags in an example page I got this error:
```
File not found

Firefox can’t find the file at /home/runner/work/napari/napari/docs/_build/_tags/visualization-basic.html.

    Check the file name for capitalisation or other typing errors.
    Check to see if the file was moved, renamed or deleted.
```

Also had a look for a `_tags/` dir in the built docs and could not find it...

Note this is looking at the CI built docs.

**Comment by jni** [comment]
I have the same issue as @lucyleeow, @melissawm. The tags show up on each page, which is great, but clicking on the tag I get a 404. Do you know what the issue is?

**Comment by melissawm** [comment]
Hm ok, I'll take a look - probably something related to the paths in CI. Can either of you build the docs locally and see if that works? It does for me.

**Comment by melissawm** [comment]
Ok I got it - should have an update of sphinx-tags to solve that soon, will ping when that's done.

**Comment by melissawm** [comment]
Ok - as far as I can tell this is now working as expected, please let me know if you see something that should be fixed. Thanks!

**Review by lucyleeow — APPROVED** [review]
LGTM! I haven't gone through the tags for every example but assume you and chi-li went through that extensively!

**Comment by alisterburt** [comment]
Thanks for the PR @melissawm and the reviews @jni and @lucyleeow ! It will be great to see this on napari.org for 0.4.17 next week.

Based on discussion and @lucyleeow's approval this looks ready to go but I wasn't sure where to find the built artefact for the current version... I got [to here](https://github.com/napari/napari/runs/8147875655?check_suite_focus=true#step:7:32) - I don't want to merge without double checking here, could someone point me to the docs built from this PR?

Side note, if we have versioned docs anyway would there be any mechanism for having docs from PRs labelled 'documentation' accessible from napari.org in the time between releases so we can easily see the docs built with specific changes? cc @melissawm @GenevieveBuckley @lucyleeow

**Comment by psobolewskiPhD** [comment]
> I wasn't sure where to find the built artefact for the current version... I got [to here](https://github.com/napari/napari/runs/8147875655?check_suite_focus=true#step:7:32) - I don't want to merge without double checking here, could someone point me to the docs built from this PR?

Yeah @melissawm the link in the OP is broken for me. Anyhow, @alisterburt you can follow the instructions here 😉 
https://napari.org/dev/developers/documentation/index.html#preview-your-document

Otherwise, just click on the Checks tab at the top and then click Build docs in the left panel and then click `docs` at the bottom of the new right panel to get the zip.

**Review by alisterburt — APPROVED** [review]
that's embarrassing 🙈 thanks @psobolewskiPhD ! I've taken a look and this seems good to go, thank you for the fantastic work @melissawm!

**Comment by lucyleeow** [comment]
> that's embarrassing see_no_evil thanks @psobolewskiPhD !

No it isn't, I just added that bit to the documentation the other day! The previewing docs is still not ideal and there is more discussion about easier previewing (without having to download the docs) here: https://github.com/napari/napari/issues/3572

**Comment by melissawm** [comment]
Thank you all! Yes - I should have updated the link in the description, as it changes when new workflow runs are executed.

I can definitely propose a solution for the docs preview using CircleCI, but will follow with the discussion over at #3572.

Cheers!

**Comment by alisterburt** [comment]
Great, thanks again!

**Comment by Czaki** [comment]
> CircleCI

why did we need to use another CI provider?

**Comment by psobolewskiPhD** [comment]
For what it's worth, i recently did a link fix on numpy repo and they have a **slick** docs thing that replies to the PR with the good-to-go docs so you can just click and browse.

**Comment by melissawm** [comment]
Yes @psobolewskiPhD that is CircleCI. Over at #5014 I am trying another solution using github actions. That will link to the zip containing the docs artifacts that you can then download and open locally.

**Pull request merged**
