### PR TITLE
Avoid importing xarray (and other array libs) for equality checkers

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
@cgohlke [pointed out](https://github.com/napari/napari/issues/758#issuecomment-786885653) that xarray is importing pkg_resources, and [we import xarray here](https://github.com/napari/napari/blob/68822f8f2ef618cc727442bc5c1a35e70198aa64/napari/utils/misc.py#L419-L425)).  So this PR uses a namespaces to check for subclassing instead of importing.  It's a little riskier, but I added a test that should notify us if any of these packages change their namespacing.

@cgohlke, thank you _so_ much for continuing to notify us about slow imports! 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tlambert03** [comment]
just added a [test for import times](https://github.com/napari/napari/pull/2325/files#diff-346ce7662b3ec9e6931480735ed0f9597dc1e7e267c73859a47f0a6fcec04d89R5-R15).  it fails on master and passes here.  I set a "threshold" of 1 second import time (master is ~1.25 seconds, this PR is 0.75 seconds).  I also make sure that `pkg_resources` wasn't imported

**Comment by tlambert03** [comment]
... yeah I figured that would never work :joy: ... just testing for `pkg_resources` now

**Comment by sofroniewn** [comment]
Looks like the import time test is failing on our 3.7 min_req test. Not sure what's different there yet or if we want to skip there/ bump a dependency?

**Comment by tlambert03** [comment]
> ...failing on our 3.7 min_req test.  Not sure what's different there yet or if we want to skip there/ bump a dependency?

interestingly, what's different there is that `pkg_resources` is being imported somewhere.  That might actually be due to previous versions of other libraries that @cgohlke has since fixed :) like https://github.com/vispy/vispy/pull/1781.  Will skip

**Comment by sofroniewn** [comment]
doesn't look like the test actually got skipped on minreq, not sure why though

**Comment by tlambert03** [comment]
Oh I bet I need to pass the min_req env var through in tox.ini

**Review by sofroniewn — APPROVED** [review]
Ok, this looks great now, will merge tomorrow unless hearing otherwise from anyone

**Pull request merged**
