### PR TITLE
Clean up layer slicer before integration with viewer

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description
This cherry picks the simpler changes over from the more complex integration PR (#5377), which include the following.

- Rename `LayerSlicer.slice_layers_async` to `LayerSlicer.submit`. Also make the parameters keyword only for extra clarity.
- Don't submit an empty request to the executor and return `None` in this case.
- Clarify and add to some of the `LayerSlicer` docstrings.
- Test and implement `LayerSlicer.shutdown` to cancel and wait for all futures.
- Some other fixes that were picked up during integration.

## Type of change
This mostly a private API refactor/rename.

# How has this been tested?
- [x] all tests pass with my change

### CODE REVIEW

**Comment by andy-sweet** [comment]
@brisvag : I assigned you to review this, which is mostly a simple/uncontentious subset of #5377. Sorry for the double-work, but we want to clarify that the more complex changes #5377 aren't going to introduce some long-term changes that we're going to regret later. Pulling these simple changes out should make the integration PR much clearer.

**Comment by kcpevey** [comment]
This is a great idea. Looks good to me :)

**Review by brisvag — APPROVED** [review]
Looks good to me; just to make sure: is there anything that I might be missing which is different from what was in #5377 and requires extra attention?

**Comment by andy-sweet** [comment]
Thanks for the quick review!

> Looks good to me; just to make sure: is there anything that I might be missing which is different from what was in #5377 and requires extra attention?

Good idea. [This diff should capture the differences in #5377 from this as a base](https://github.com/andy-sweet/napari/compare/clean-up-layer-slicer...andy-sweet:napari:async-integrate) (note that the async-integrate branch uses this branch as a base, then has a single commit that copies the changes from #5377 to make the comparison clean).

I did catch a few missed name changes in the tests, so I pushed a new commit with those.

Otherwise, all the other changes are some docstring/formatting differences, and then the real integration points + tests, which this PR does not attempt.

Therefore, I'll merge this after 24 hours unless I hear otherwise.

**Pull request merged**
