### PR TITLE
Run PNG crush on all Pngs.

### PR DESCRIPTION
**Pull request by Carreau**
That should about decrease teh size of the Png assest by 30%,
Not only decreasing the size of git lfs, but also the size of the assets
when viewing the website, which is always good for slow connection.

```
$ git lfs ls-files  | cut -f2 -d '*' |grep png | xargs  du -c | grep total
43296	total

$ git co HEAD~1
...

$ git lfs ls-files  | cut -f2 -d '*' |grep png | xargs  du -c | grep total
64224	total
```

This was run to decrease the PNG size:

```
$ git lfs ls-files  | cut -f2 -d '*'| xargs ls -S | grep png  | xargs -L1 pngcrush -brute -ow
```

Note the unlike its sibling PR that converts gif to webm (which is a
lossy process), this should be a lossless process, at least with respect
to pixels, not sure WRT metadata.

### CODE REVIEW

**Comment by Carreau** [comment]
Note that MacOS UI seem to not like when you run `pngcrush -brute`
Screen Shot 2022-03-06 at 16 51 25
.
I'm also sort-of submitting this PR blind, so sorry for typoes, I might have to restart (hopping the computer will restart)

Screen Shot 2022-03-06 at 16 56 50

**Comment by jni** [comment]
> Note that MacOS UI seem to not like when you run pngcrush -brute

What does this mean exactly? And isn't this a deal breaker?

**Comment by jni** [comment]
Also, as noted in #4207, I don't want to invalidate our lfs cache right before release, so I will look at this again in a couple of days after 0.4.15.

**Comment by Carreau** [comment]
> What does this mean exactly? And isn't this a deal breaker?

No, just a warning if someone else want to run the same commands later. I'm going to guess libpng or similar have some internal state that get modified by pngcrusher and affects font rendering (also it only affects web-things not native UI).

After a restart all is good, and viewing the png themselves don't trigger that.

**Comment by sofroniewn** [comment]
@jni should we revisit now as 0.4.15 is out?

**Review by sofroniewn — APPROVED** [review]
Nice work here @Carreau! As noted on #4027 it might be good to add this to our contributing guide cc @DragaDoncila so that we can keep png size low. Thanks!!

**Pull request merged**
