### PR TITLE
Ci cache reset

### PR DESCRIPTION
**Pull request by liu-ziyang**
# Description
Reset cache on mac 3.7

## Type of change
Nothing changed

# References
https://github.com/napari/napari/issues/1527

### CODE REVIEW

**Comment by liu-ziyang** [comment]
I tested this on this branch to run on mac with python 3.7 (this change has been rolled back reset --hard) 
When I tested it, CI was indeed rerunning pip install instead of using a existing matching, however I cannot guarantee this happens too on master, because branches was not running 3.7 before
Worst case scenario we would have to merge the 2 commits in this PR separately, which themselves individually are pretty harmless and cancels out each other anyway

**Comment by liu-ziyang** [comment]
supposedly, we just need ci to think the build process is different, it looks like it uses a way to identify (during the PIP cache step it says it matches a hash) so ones we modify anything, the cache would be invalidated, so we are going to attempt change a harmless config flag (retry number) and trick ci to run the new flow and invalidate the existing cache, and maybe revert it if desired later

**Review by sofroniewn — APPROVED** [review]
> supposedly, we just need ci to think the build process is different, it looks like it uses a way to identify (during the PIP cache step it says it matches a hash) so ones we modify anything, the cache would be invalidated, so we are going to attempt change a harmless config flag (retry number) and trick ci to run the new flow and invalidate the existing cache, and maybe revert it if desired later

Thanks for that explanation @ziyangczi - this does indeed seem harmless and if this does the trick that's great!! We can then revert in a follow up PR.

I'll merge shortly unless @tlambert03 has additional ideas. I did look into if the cache could be reverted in the CI UI as @jni asked, but I couldn't see a way.

I wonder if @ziyangczi should look into the github actions proposal from @tlambert03 in #1307 as a long term approach.

**Comment by tlambert03** [comment]
> I wonder if @ziyangczi should look into the github actions proposal from @tlambert03 in #1307 as a long term approach.

fwiw, [that branch](https://github.com/napari/napari/compare/master...tlambert03:feature/github-tests) is still mostly in good shape.  Just updated and tests are mostly passing: https://github.com/tlambert03/napari/runs/986291638?check_suite_focus=true

needs a bit of love on windows, and needs isort added to CI.  (and a discussion as to whether people are ok with using tox as I've done there, or prefer not to)

**Comment by sofroniewn** [comment]
Unfortunately @ziyangczi this approach has not succeeded - see 
image

What do you recommend @ziyangczi we try next?

**Comment by liu-ziyang** [comment]
I took a look at 1307, I think we should move forward with the migration, I can take over the branch if desired. I can help with the windows test part.

regarding tox, We can talk about it in the next meeting, I don't think it is a deal-breaker, I personally would hope we do not use a tool to facilitate testing on different environments because it introduced some complexity/dependency in ci, and can be tricky later if breaks, etc

**Comment by liu-ziyang** [comment]
regarding the cirrus ci fix, I think the most viable fix would be updating some dependency in our pip file to force a new dependency installation process. I can't find any doc from cirrus explaining how they match the pip cache so we can find a way to work around it or any tutorial to do so manually.

**Comment by tlambert03** [comment]
> because it introduced some complexity/dependency in ci

would be curious to know what difficulties you ran into... I actually added it there because, combined with [tox-gh-actions](https://github.com/ymyzk/tox-gh-actions) I found that it actually simplified testing on CI with a variety of environments (and as a bonus, makes it much easier to test a matrix of environments locally, such as testing both pyside/pyqt on py3.6-3.x just by running `tox`)

**Comment by liu-ziyang** [comment]
> > because it introduced some complexity/dependency in ci
> 
> would be curious to know what difficulties you ran into... I actually added it there because, combined with [tox-gh-actions](https://github.com/ymyzk/tox-gh-actions) I found that it actually simplified testing on CI with a variety of environments (and as a bonus, makes it much easier to test a matrix of environments locally, such as testing both pyside/pyqt on py3.6-3.x just by running `tox`)

not any difficulties immediately, but in my opinion, that is too much magic for the CI setup. I would argue CI should be the pure dumb code setup. If we need to test out on a matrix of setups, I would rather just flush out the code completely instead of trying to be smart and optimize it. I have had enough nightmares dealing with "smart" CIs, the pip cache is certainly the most recent one :) 
That being said, though I would not be setting up such a thing in my own project, I don't think this is a deal-breaker that we need to bang out head in arguing whether to have it or not, we can improve our CI setup later anyway since this is nothing relevant to our "business model", I am more concerned about what is the difference in cost than the tox. Hoping github is nice enough to allow us using it for free?

**Pull request merged**
