### PR TITLE
Add some tests for help menu actions

### PR DESCRIPTION
**Pull request by dalthviz**
# References and relevant issues

Part of #6941 

# Description

Add some tests for help menu actions (About dialog trigger)

# Notes:

* Seems like there is another test related with help actions at `napari._qt._qapp_model._tests.test_help_menu_urls.py` should things be unified in a single test file (`test_help_menu.py`)?

### CODE REVIEW

**Comment by lucyleeow** [comment]
* `napari._qt._qapp_model._tests.test_help_menu_urls.py` - I would add this test to `test_help_menu.py`
* Maybe we could add a test that just pings each `HELP_URLS` and just makes sure we don't get a 404?

**Comment by dalthviz** [comment]
> Maybe we could add a test that just pings each HELP_URLS and just makes sure we don't get a 404?

Checking more in detail the test that was at `test_help_menu_urls.py` I think it is already doing that:

https://github.com/napari/napari/blob/e67baa79984f4657fabfffc11550da4d4a2a5d9f/napari/_qt/_qapp_model/_tests/test_help_menu.py#L13-L19

So the test goes through all the URLs and tries to do a HEAD request to check if the URL is valid by raising a `HTTPError` in case a bad HTTP status is returned from the request (`4xx` or `5xx` status codes). The only URL that is not checked is the release URL since it is invalid when running napari from a dev release/in dev mode (`https://napari.org/{VERSION}/release/release_dev.html`)

**Review by lucyleeow — APPROVED** [review]
Thank you!

(and yes you are right, I read too quickly and missed the parameterization)

**Review by DragaDoncila — APPROVED** [review]
Love you work @dalthviz ❤️

**Pull request merged**
