### PR TITLE
Accept NAP-2: Distributing napari with conda-based packaging

### PR DESCRIPTION
**Pull request by jni**
# Description

This PR updates the NAP-2 metadata to reflect its status as accepted! :tada:

### CODE REVIEW

**Comment by jni** [comment]
CC @goanpeca @jaimergp @tlambert03 @sofroniewn @potating-potato 🙏

**Review by tlambert03 — APPROVED** [review]

**Review by jaimergp — APPROVED** [review]

**Review by sofroniewn — APPROVED** [review]

**Review by liu-ziyang — APPROVED** [review]
hooray!

**Comment by jni** [comment]
Normally this should take 7 days, but given the unanimous support in #4602 and above, I propose we count the discussion period there and go ahead and merge?

**Comment by tlambert03** [comment]
doing it.  :)

**Comment by jaimergp** [comment]
As per NAP-2, can I request the creation of the `napari/packaging` repo to start migrating the conda CI infra there?

**Comment by tlambert03** [comment]
All set

**Pull request merged**
