### PR TITLE
Remove scaling of highlight width, fix showing shapes for uneven coordinates

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues

This PR is created as result of debug https://github.com/napari/napari/issues/6627#issuecomment-1914804363
As 0.4.19 branch has fewer problems than #6628 is created for 0.4.19. 

# Description

Fix logic for selecting of visible shapes based on idea from #2289. It is lucky that we do not hit this earlier. 

Removes scaling of width of markers border (this is same like in #6628)

To improve readability, this update `ShapesVisual` to have named subvisuals.

### CODE REVIEW

**Comment by brisvag** [comment]
> Fix logic for selecting of visible shapes based on idea from #2289. It is lucky that we do not hi this earlier.

Ahhh! Nice! We did hit this somewhere in zulip a few days ago, it's great you found the issue. Let's get this in asap!

**Review by brisvag — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
The script from the issue gives me something strange:
image
But if I hit `Home` and scroll to the right slice, I see the shape and can interact with it just fine.

**Comment by Czaki** [comment]
@psobolewskiPhD When I merge main into this branch, it looks fixed

**Comment by psobolewskiPhD** [comment]
If I add `viewer.reset_view()` after the scale setting for loop then everything is gucci.

**Comment by Czaki** [comment]
> If I add `viewer.reset_view()` after the scale setting for loop then everything is gucci.

Yes. I found such a line in my script instance. I will take a look at what happens here.

**Pull request merged**
