### PR TITLE
Update translation strings checks

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — COMMENTED** [review]
LGTM! We've got two test failing in the action manager as the translations not quite right. Once those are fixed then I think will be good to merge!

```python-traceback
 =================================== FAILURES ===================================
  __________________________ test_bind_multiple_action ___________________________
  
  action_manager = <napari.utils.action_manager.ActionManager object at 0x7f7e7af75880>
  
      def test_bind_multiple_action(action_manager):
          """
          Test we can have multiple bindings per action
          """
      
          action_manager.register_action(
              'napari:test_action_2', lambda: None, 'this is a test action', None
          )
      
  >       action_manager.bind_shortcut('napari:test_action_2', 'X')
  
  napari/utils/_tests/test_action_manager.py:38: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  napari/utils/action_manager.py:363: in bind_shortcut
      self._update_gui_elements(name)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <napari.utils.action_manager.ActionManager object at 0x7f7e7af75880>
  name = 'napari:test_action_2'
  
      def _update_gui_elements(self, name: str):
          """
          Update the description and shortcuts of all the (known) gui elements.
          """
          if name not in self._actions:
              return
          buttons = self._buttons.get(name, set())
          desc = self._actions[name].description
      
          # update buttons with shortcut and description
          if name in self._shortcuts:
              shortcuts = self._shortcuts[name]
              joinstr = (
                  ' '
  >               + trans._p('or', msgctxt='<keysequence> or <keysequence>')
                  + ' '
              )
  E           TypeError: _p() got multiple values for argument 'msgctxt'
  
  napari/utils/action_manager.py:274: TypeError
  _______________________ test_bind_unbind_existing_action _______________________
  
  action_manager = <napari.utils.action_manager.ActionManager object at 0x7f7e7ba82e20>
  
      def test_bind_unbind_existing_action(action_manager):
      
          action_manager.register_action(
              'napari:test_action_1', lambda: None, 'this is a test action', None
          )
      
  >       assert action_manager.bind_shortcut('napari:test_action_1', 'X') is None
  
  napari/utils/_tests/test_action_manager.py:49: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  napari/utils/action_manager.py:363: in bind_shortcut
      self._update_gui_elements(name)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <napari.utils.action_manager.ActionManager object at 0x7f7e7ba82e20>
  name = 'napari:test_action_1'
  
      def _update_gui_elements(self, name: str):
          """
          Update the description and shortcuts of all the (known) gui elements.
          """
          if name not in self._actions:
              return
          buttons = self._buttons.get(name, set())
          desc = self._actions[name].description
      
          # update buttons with shortcut and description
          if name in self._shortcuts:
              shortcuts = self._shortcuts[name]
              joinstr = (
                  ' '
  >               + trans._p('or', msgctxt='<keysequence> or <keysequence>')
                  + ' '
              )
  E           TypeError: _p() got multiple values for argument 'msgctxt'
  
  napari/utils/action_manager.py:274: TypeError
  =============================== warnings summary ===============================
```

**Comment by goanpeca** [comment]
>LGTM! We've got two test failing in the action manager as the translations not quite right. Once those are fixed then I think will be good to merge!

Fixed!

**Comment by Carreau** [comment]
Had conflicts, rebased.

**Comment by goanpeca** [comment]
Thanks @Carreau

**Review by Carreau — APPROVED** [review]

**Comment by Carreau** [comment]
Remaining failure seem random. Merging.

**Pull request merged**
