### PR TITLE
[WIP] Don't pin ipykernel

### PR DESCRIPTION
**Pull request by jni**
# Description

Thanks to updates in pip, napari would no longer run in an environment where ipykernel 5.1.2 was installed. This addresses that issue.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
The pin was needed because I think we broke on `5.1.2` - potentially only on mac osx. I'll look into it, but unless they have fixed things the console won't work

**Comment by jni** [comment]
@sofroniewn (a) can you check, (b) can you check whether pip can do platform-specific pins? The console seems to be working fine on Linux, and (c) even then, you can do `ipykernel>=5.1.1,!=5.1.2` which allows upgrades through, should the issue be fixed. Indeed the CI seems to back (a), though. Have you raised an issue with ipykernel?

**Comment by sofroniewn** [comment]
I will look into it - here is the PR #482 and discussion where we did the pinning. I'm not sure an issue has been raised, or if it just just a mac OSX CI issue. I imagine so as I probably had it working on my laptop before we pinned. The issue does still seem to be present though judging from our failing tests

**Review by sofroniewn — APPROVED** [review]
I've now dropped support for multiple kernels with multiple viewers, which was buggy anyway (you can still have multiple viewers, the later ones just won't get a console) and should allow our tests to pass on osx - but without pinning ipykernel. We shall see, if the tests pass then I will merge.

I saw at least one person at the course i was teaching have install problems because of the pinning!!

**Comment by sofroniewn** [comment]
Our tests are still failing - now likely due to our kernels not actually shutting down in the way I expect. I have made an issue here - https://github.com/jupyter/qtconsole/issues/385 to discuss

**Comment by jni** [comment]
@sofroniewn new release 5.1.3 of ipykernel, on first glance some of those updates might be relevant:

https://github.com/ipython/ipykernel/blob/master/docs/changelog.rst

**Comment by sofroniewn** [comment]
I will had tried the latest master of ipykernel recently (after some of those updates) and it still didn't fix it, but I will try with the new release too

**Comment by kne42** [comment]
5.1.2 and 5.1.3 are still causing too many open files errors for me. if we want to stop pinning it, we could set it as an inclusive range between 5.0.0 and 5.1.1

**Comment by sofroniewn** [comment]
@kne42 the pinning has been causing install problems for some users. I'm not sure that range will fix them. I think we only run into the problem during our tests and it seems a shame to cause install problems just for our tests. I'm not quite sure what's best

**Comment by kne42** [comment]
@sofroniewn ah, right, I completely forgot that this only causes errors in our tests! In that case, we should unpin `ipykernel` from the default requirements and add it to the dev requirements and our 
CI instead with a comment explaining why.

**Comment by sofroniewn** [comment]
That’s a great idea @kne42! - do you want to create a fresh PR doing that and then I will close this one.

**Comment by sofroniewn** [comment]
Even better would be to only change the version for our osx tests as then at least Linux will still be tested against latest. What does @jni think

**Comment by kne42** [comment]
@sofroniewn sure! I recently reran the tests on this PR and they are failing even with `ipykernel==5.1.3` on every platform so I'm guessing it's more widespread than MacOS but maybe @jni can verify as an actual Linux user

**Comment by kne42** [comment]
Since @jni has not responded yet, I will go ahead and create a new PR.

**Comment by sofroniewn** [comment]
@kne42 as we just discussed on the video chat, I think the work @shanaxel42 is doing in #769 might fix this bug in our tests and then we won't need to worry about pinning anywhere

**Comment by sofroniewn** [comment]
This has now been superseded by #784 and can be closed

**Pull request closed without merging**
