### PR TITLE
napari cli: enable --with option for npe2 widgets

### LINKED ISSUE #3805: napari cli: enable --with option for npe2 widgets
## Description

Right now trying to launch an  npe2 dock widget from the cli fails. For example:

```sh
napari --with napari-animation
```

(with napari-animation installed as an npe2 plugin)

gives

```
Traceback (most recent call last):
  File "/Users/nclack/opt/miniforge3/envs/dev-napari-npe2-console/bin/napari", line 33, in <module>
    sys.exit(load_entry_point('napari', 'console_scripts', 'napari')())
  File "/Users/nclack/src/CZI/napari/napari/__main__.py", line 449, in main
    _run()
  File "/Users/nclack/src/CZI/napari/napari/__main__.py", line 327, in _run
    viewer.window.add_plugin_dock_widget(pname)
  File "/Users/nclack/src/CZI/napari/napari/_qt/qt_main_window.py", line 655, in add_plugin_dock_widget
    widget_name = list(plugin_manager._dock_widgets[plugin_name])[0]
KeyError: 'napari-animation'
```

## References

I ran into this while looking into this comment from @jni.  This issue focuses on the idea of pre-loading a plugin widget using the `--with` option, but doesn't address the `napari path/to/file.npy`.  See discussion below for more.

> Can we update this to be a single command that "executes" the plugin? e.g. `napari path/to/file.npy`? That's not a super 
> interesting example, but I always have to look up the equivalent command for pre-loading a plugin widget.

_Originally posted by @jni in https://github.com/napari/napari/pull/3769#discussion_r767255994_

### PR DESCRIPTION
**Pull request by nclack**
# Description

Enables `napari --with <plugin>` for npe2 widgets.

This requires #3798 for this to work.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# References

closes #3805 
depends on #3798

# How has this been tested?
By hand:
1. convert `napari-animation` to and npe2 plugin and install as such.
2. From a terminal `napari -vv --with napari-animation`

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tlambert03** [comment]
can you merge in master?

**Review by tlambert03 — COMMENTED** [review]
looks good to me, but merge in main and cleanup the lint.  see also https://github.com/napari/napari/issues/3805#issuecomment-991966226 ... this may not actually close 3805

**Comment by nclack** [comment]
these test errors also look unrelated?

**Comment by sofroniewn** [comment]
@nclack can you update from main so all tests are passing and then we can merge this, thanks!!

**Review by tlambert03 — APPROVED** [review]

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Pull request merged**
