### PR TITLE
Prevent fail bundle when have other name than napari

### PR DESCRIPTION
**Pull request by Czaki**
# Description

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
This looks good to me @Czaki - I assume this allows you to create your own bundled app using napari, is that the case? Are you using briefcase too? I'm just curious how that is working for you. We'll get this merged before 0.3.8

**Comment by sofroniewn** [comment]
I just updated the release notes to include this PR

**Comment by Czaki** [comment]
I still use pyinstaller. Without this change I got something like this  (this log is from napari 0.3.7 but similar one is from 0.3.8rc0)

```
  File "napari/plugins/__init__.py", line 10, in <module>
  File "napari/utils/misc.py", line 27, in running_as_bundled_app
  File "importlib_metadata/__init__.py", line 575, in metadata
  File "importlib_metadata/__init__.py", line 215, in from_name
importlib_metadata.PackageNotFoundError: No package metadata was found for napari
[930886] Failed to execute script launcher_main
```

I have plan to switch to briefcase but not have enough time for this now. 
Current briefcase release does not allow to do this. I create first PR to fix briefcase: https://github.com/beeware/briefcase/pull/475.
But it may need more PR. (Current release is older than this PR merge)

**Comment by sofroniewn** [comment]
> I still use pyinstaller. Without this change I got something like this (this log is from napari 0.3.7 but similar one is from 0.3.8rc0)

Ok thanks, good to know!

**Pull request merged**
