### PR TITLE
Try to speedup tests.

### PR DESCRIPTION
**Pull request by Carreau**
It seem that a large part of our slow test are spent in gc.collect.
Here we try to be a bit more lenient on how aggressive we are at
collecting garbage, and only collect all generation every 50 passes.

The youngest generation is 0, and the older 2, so by asking to collect
up to generation 1, we should catch most of the leaks.

Locally this reduces the total time of `test_add_layer` by 25% (from 80+s to ~60s). This test is one of the major consumer of CI time as it represent ~37% of our test test suite. 

All in all this should I guess speedup out test suite by at least ~10%, but may have the drawback of making the detection of leaked widget a bit less reliable.

### CODE REVIEW

**Comment by Carreau** [comment]
Note: the next bottleneck in test suite is `viewer.close()`, which itself is limited by `self.layers.clear()`, which itself is limited by `self.event.removed(...)`.

**Comment by goanpeca** [comment]
Awesome :) 

Have we tried using https://github.com/pytest-dev/pytest-xdist already 🤔 ?

**Comment by Carreau** [comment]
> Awesome :)
> 
> Have we tried using https://github.com/pytest-dev/pytest-xdist already 🤔 ?

I think that will just decrease wall time not CPU time. The other possibility is to split pyqt/pyside into their own matrix.

**Comment by Carreau** [comment]
Super non scientific copy-past of timing.
```
                                     Pr#4518   This.
PR Test / ubuntu-latest 3.8             50m -> 27m
PR Test / ubuntu-latest 3.9             52m -> 25m
PR Test / ubuntu-latest 3.10            37m -> 26m
PR Test / windows-latest 3.8 pyqt       23m -> 15m
PR Test / windows-latest 3.8 pyside     33m -> 19m
PR Test / macos-11 3.9 pyqt             34m -> 25m
PR Test / ubuntu-18.04 3.8 min_req      49m -> 31m
PR Test / ubuntu-18.04 3.8 async-pyqt-py38-linux    22m -> 13m
PR Test / ubuntu-18.04 3.8 headless-py38-linux       3m ->  2m
PR Test / ubuntu-latest 3.9 pip install             21m -> 11m
```

**Review by tlambert03 — APPROVED** [review]
woah, timings look awesome @Carreau

**Comment by Carreau** [comment]
Thanks, one this and the other one that create json reports are merged I hope to be able to spend more time to reduce the test suite time to reasonable time. In particular if test add layers still takes too much of the test suite time I'm thinking on test it only on linux, as it's gui independant and thus _should_ not be affected by the Gui/OS.

**Comment by Czaki** [comment]
You may also check the impact of coverage calculation for every test run. Maybe only part of the test run should collect coverage information. 

I also experienced that sometimes waiting on qt signals take really long on CI.

**Comment by Carreau** [comment]
Ok, going to self-merge.

**Pull request merged**
