### PR TITLE
patch ipython excepthook in gui_qt eventloop

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
here's a small quality of life improvement when using a napari Viewer in an `ipython --gui qt` event loop, when an exception occurs.  

Before this PR:

```python
In [1]: import napari

In [2]: v = napari.Viewer()

# do something to cause an exception...

Traceback (most recent call last):
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/_qt/widgets/qt_viewer_buttons.py", line 58, in _ras
    raise ValueError("ERRR")
ValueError: ERRR

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

after this PR:
```python
In [1]: %gui qt

In [2]: from napari import Viewer

In [3]: v = Viewer()

# do something to cause an exception...

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Dropbox (HMS)/Python/forks/napari/napari/_qt/widgets/qt_viewer_buttons.py in _ras()
     56         )
     57         def _ras():
---> 58             raise ValueError("ERRR")
     59         self.newLabelsButton.clicked.connect(_ras)
     60         layout = QHBoxLayout()

ValueError: ERRR
```

There is an [open discussion](https://github.com/ipython/ipython/issues/10057) (though it's 5 years old) at IPython that I commented on earlier, so this may eventually go in upstream, but wanted to note it here too just in case.  This can wait until after 0.4.3

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tlambert03** [comment]
actually @Carreau ... if you have a moment to take a look at this, I'd be curious to get your thoughts. 

The patch upstream would be to put the following code block right [here](https://github.com/ipython/ipython/blob/3587f5bb6c8570e7bbb06cf5f7e3bc9b9467355a/IPython/terminal/pt_inputhooks/qt.py#L29) after (QApp creation) in `IPython.terminal.pt_inputhooks.qt`.

```python
        def _patch_excepthook():
            shell = get_ipython()
            if shell:
                sys.excepthook = shell.excepthook
        QtCore.QTimer.singleShot(0, _patch_excepthook)
```

it's been working fine for me, but I'm not certain if there are caveats to calling `get_ipython()` in the `inputhook` function

**Comment by Carreau** [comment]
Calling `get_ipython()` is fine, it will be no-op if there is already an IPython instance running.  

If there need to be a change in IPython we can push for it. My main concern with patching excepthook is if many things try to patch it.

**Comment by sofroniewn** [comment]
No rush/ pressure, but just looking through PRs and wondering what the status/ plan for this one is @tlambert03?

**Comment by tlambert03** [comment]
It's ready to go, just waiting on some feedback.  I like the result a lot when working in IPython.  It could be argued that it belongs upstream... @Carreau can weigh in on that.  If he and @jni are ok with it, I'd like to have it in

**Comment by tlambert03** [comment]
if anyone is wanting more history on this, see my comments starting here: https://github.com/ipython/ipython/issues/10057#issuecomment-754209074

**Comment by Carreau** [comment]
I'm fine with whatever you believe is necessary upstream; some of that code predes me by quite a bit, and qt was never my expertise (I usually just wave my hand running around and merge if it does seem to fix things) ; We can even iterate as I release IPython once a month.

**Comment by tlambert03** [comment]
ok, I'll submit a PR and we can discuss it there.  It's probably the "correct" place for it.

**Comment by tlambert03** [comment]
upstream PR: https://github.com/ipython/ipython/pull/12842

**Comment by tlambert03** [comment]
merged upstream

**Pull request closed without merging**
