### PR TITLE
Refactor imports: allow local import only for subpackages

### PR DESCRIPTION
**Pull request by Czaki**
# Description

The idea of This PR is to improve workflow when using GitHub to navigate over code (for example, when answering some questions). 

Absolute import screenshot:
image

Relative import screenshot:
image

## Type of change

- [x] Refactor

# References

alternative to #5113

This PR uses https://github.com/Czaki/absolufy-imports, my fork of https://github.com/MarcoGorelli/absolufy-imports that allow for local import only in subpackages as author reject idea of include such changes in his code and this keep code easier to read https://github.com/MarcoGorelli/absolufy-imports/issues/34 

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by brisvag** [comment]
In principle, my work on #5113 was mostly for consistency, so I'm ok with this as well, and this has the added bonus of making using github easier, so I'm in favor of this one!

**Comment by jni** [comment]
I don't love this, tbh. To me relative imports make more sense semantically, "import from this directory hierarchy", while absolute imports could *in principle* refer to an installed package. I understand that in practice this makes little difference, which is why I won't put my foot down here, but I'd like to hear from more than one or two devs before merging.

Re: GH, it's not compelling to me that a limitation in their code-browsing tools should dictate our code style, unless it also makes sense independently. Again, if everyone else favours absolute imports everywhere, that's fine.

Also, I don't really understand the rationale for "absolute everywhere, except for sister files + subdirectories" — why not just go to absolute, period?

**Comment by kephale** [comment]
I really like being able to jump to definitions and references directly in GH. I use those features all the time.

However, I would agree that changing in response to GH's indexing limitations is not a great argument. One reason is that GH's code indexing has pretty consistently improved over time, so I suspect they might be able to handle relative imports at some point.

**Comment by Czaki** [comment]
> Re: GH, it's not compelling to me that a limitation in their code-browsing tools should dictate our code style, unless it also makes sense independently. Again, if everyone else favours absolute imports everywhere, that's fine.

for me above two dots make it hard to navigate manually. Especially when we have modules like utils in multiple subackages. 

> Also, I don't really understand the rationale for "absolute everywhere, except for sister files + subdirectories" — why not just go to absolute, period?

After moving the whole directory, it still will work. 
Also, I run fully absolute, and it looks not so good when there is a depth of four or more packages. 

I could prepare a PR with such refactor also.

**Comment by psobolewskiPhD** [comment]
I'm totally out of my depth, so I shouldn't even say anything, but:
I copy-paste code to see what it does and learn stuff. The `...` imports are hard for me to `get` when I read the code and don't work when I copy-paste them to ipython.
So if this means more `from napari.foo.bar import foobar`, then at least for me this would be a big plus.
But, I'm probably doing it wrong and again, way out of my depth, so please feel free to disregard based on the feedback of actual adults in the room.

**Comment by kephale** [comment]
@Czaki yes, very true about the `utils` submodules. With relative imports I have been confused about `napari.utils` and `napari.layers.utils` on multiple occasions.

**Comment by goanpeca** [comment]
My 2 cents:

I usually find it harder to read code that uses relative imports, also copy pasting code, and doing refactors is just messy with relative imports. I would favor going full absolute. GH will probably eventually fix the issue but I still find it harder to work with relative imports overall.

**Comment by jni** [comment]
No, thank you for chiming in @psobolewskiPhD! The readability of code is a primary concern, even/especially for newcomers! (Thanks also @kephale and @goanpeca who chimed in while I was typing this 😂) So that's a good argument for this PR for me. 🙏

**Comment by jni** [comment]
I'm also curious whether the same people think we should go full-absolute? For me, the mixture is a bit jarring. And the arguments about copy-pasting etc. point to full-absolute.

**Comment by liu-ziyang** [comment]
I like working with absolute import myself, especially for larger projects. I don't think the verbosity in this project is at a level where absolute import is intolerable. 

That said, I think the steering council should govern coding styles like these that don't have right or wrong answers after hearing from the community. I will comply with whatever style the steering council ends up deciding.

**Comment by Czaki** [comment]
close in favour of #5318

**Comment by jni** [comment]
> One reason is that GH's code indexing has pretty consistently improved over time, so I suspect they might be able to handle relative imports at some point.

LOL:

https://twitter.com/maximedegreve/status/1590415616921698305

**Comment by Czaki** [comment]
I do not see relative to be supported (in announcements).

**Pull request closed without merging**
