### PR TITLE
Update missing translations for 0.4.8

### PR DESCRIPTION
**Pull request by jni**
# Description

In the missing translations panel, I'm not 100% sure which strings need translating vs which don't, e.g. in the preferences UI schema:

```
napari/_qt/dialogs/preferences_dialog.py
****************************************
25:	'highlight_thickness'
25:	'highlight'
```

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @jni thanks for working on this thise those should be excluded as those refer to configuration of which widget to use for a specific setting, so no string that is actually visible to the user.

Screen Shot 2021-05-06 at 11 04 19 AM

**Comment by sofroniewn** [comment]
From @goanpeca looks like for

```
napari/utils/action_manager.py
******************************
String:		'Action names need to be in the form `package:name`, got {name}'
Variables:	'delayed'
```

should be `deferred` not `delayed`

**Comment by sofroniewn** [comment]
> should be deferred not delayed

I just did this one

**Comment by goanpeca** [comment]
Thanks @jni and @sofroniewn will add the remaining fixes :)

**Comment by goanpeca** [comment]
It seems I cannot push to directly this PR 🤔

**Comment by goanpeca** [comment]
Will make a PR against Juan's

**Comment by goanpeca** [comment]
Created https://github.com/jni/napari/pull/8 @jni

**Comment by jni** [comment]
Wow good morning and thanks for tackling this @goanpeca! 😅

**Comment by jni** [comment]
So the windows failure is weird, it says windows-py38-pyqt failed, but actually all the tests passed 🤷. The ubuntu/min req I've seen before, gonna see if I can reproduce it locally:

```
  ______________ ERROR at teardown of test_add_layer[Image-data3-2] ______________
  TEARDOWN ERROR: Exceptions caught in Qt event loop:
  ________________________________________________________________________________
  StopIteration
  ________________________________________________________________________________
  
  ---------- coverage: platform linux, python 3.7.10-final-0 -----------
  Coverage XML written to file coverage.xml
  
  ============================= slowest 5 durations ==============================
  3.95s call     napari/plugins/_tests/test_plugins_misc.py::test_plugin_discovery_is_delayed
  3.76s call     napari/layers/utils/_tests/test_layer_utils.py::test_calc_data_fast_uint8
  1.84s call     napari/_tests/test_with_screenshot.py::test_changing_image_attenuation
  1.54s call     napari/_tests/test_with_screenshot.py::test_z_order_image_points_after_ndisplay
  1.50s call     napari/_tests/test_with_screenshot.py::test_changing_image_colormap
  =========================== short test summary info ============================
  ERROR napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Image-data3-2]
```

**Comment by tlambert03** [comment]
>   ______________ ERROR at teardown of test_add_layer[Image-data3-2] ______________
>   TEARDOWN ERROR: Exceptions caught in Qt event loop:


this one has also been happening a lot

**Comment by jni** [comment]
Hooray! Totally different one locally 😂 

```
______________ ERROR at teardown of test_add_layer[Image-data0-2] ______________

qtbot = <pytestqt.qtbot.QtBot object at 0x7fb211980310>

    @pytest.fixture
    def _strict_qtbot(qtbot):
        """A modified qtbot fixture that makes sure no widgets have been leaked."""
        from qtpy.QtWidgets import QApplication

        initial = QApplication.topLevelWidgets()
        prior_exception = getattr(sys, 'last_value', None)

        yield qtbot

        # if an exception was raised during the test, we should just quit now and
        # skip looking for leaked widgets.
        if getattr(sys, 'last_value', None) is not prior_exception:
            return

        QApplication.processEvents()
        leaks = set(QApplication.topLevelWidgets()).difference(initial)
        # still not sure how to clean up some of the remaining vispy
        # vispy.app.backends._qt.CanvasBackendDesktop widgets...
        if any([n.__class__.__name__ != 'CanvasBackendDesktop' for n in leaks]):
>           raise AssertionError(f'Widgets leaked!: {leaks}')
E           AssertionError: Widgets leaked!: {<PyQt5.QtWidgets.QWidget object at 0x7fb1f6c54700>}

napari/utils/_testsupport.py:37: AssertionError
============================= slowest 5 durations ==============================
2.30s call     napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Image-data0-2]
0.41s teardown napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Image-data0-2]
0.37s call     napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Tracks-data12-3]
0.35s call     napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Vectors-data8-2]
0.35s call     napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Labels-data4-2]
=========================== short test summary info ============================
ERROR napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Image-data0-2] - As...
```

**Comment by jni** [comment]
Since they are unrelated I might suggest that we merge this one and make issues for these failures.

**Review by sofroniewn — APPROVED** [review]
Sounds good, LGTM, let's merge!!

**Comment by jni** [comment]
FYI at least on my mac, I just made a minimum requirements env and the tests passed, so at least it appears to be a CI-only issue. Which makes it harder to debug but won't 🤞 affect users. I'll try on my Linux laptop later.

**Pull request merged**
