### PR TITLE
Fix settings reset breaking connections (creating a new instance of nested sub-models)

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This fixes the bug that @ppwadhwa observed with the new settings in https://github.com/napari/napari/pull/3120#issuecomment-891850219, and adds a test.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# How has this been tested?

- [ ] the test suite for my feature covers cases x, y, and z
- [ ] all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM! Maybe @ppwadhwa can take a quick look before merge too, thanks!!

**Comment by ppwadhwa** [comment]
Sure thing!   I will check it out this evening!

**Comment by ppwadhwa** [comment]
@tlambert03 For the most part, changing the settings on the preferences dialog is working great.  I am seeing something weird with the playback settings.  If I change the playback settings loop mode in preferences, it will not be able to save in settings.  When you close napari, you get a `RepresenterError: ('cannot represent an object', <LoopMode.BACK_AND_FORTH: 'back_and_forth'>)`.

The traceback is much longer, but I didn't want to include the whole thing.  Hopefully, you can reproduce the problem.

**Comment by Carreau** [comment]
> If I change the playback settings loop mode in preferences, it will not be able to save in settings. When you close napari, you get a `RepresenterError: ('cannot represent an object', <LoopMode.BACK_AND_FORTH: 'back_and_forth'>)`.
> 
> The traceback is much longer, but I didn't want to include the whole thing. Hopefully, you can reproduce the problem.

I do not get the traceback, and you do not need to chose napari to get the issue (just changing the value of loop mode causes and issue with setting file to disappear). This problem is also present on master. 

So I think that 1) this fix the issue, and 2) should be a separate issue.

**Comment by Carreau** [comment]
See #3158 as a followup.

**Comment by ppwadhwa** [comment]
thanks, @Carreau, for looking into it!

**Pull request merged**
