### PR TITLE
Use text opacity to signal that widget is disabled

### PR DESCRIPTION
**Pull request by Czaki**
# Fixes/Closes

Closes #

# Description

In this PR I add "trying" of text on disabled widgets. 

obraz

# References

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
@Czaki should this be marked as draft for now or is your idea to get this merged like this?

**Comment by Czaki** [comment]
It is enough for me to achieve my targets (visible disable buttons that using text icons).

**Comment by psobolewskiPhD** [comment]
The qss makes sense, but do you have an example or snippet to test?

**Comment by Czaki** [comment]
Current developer branch of PartSeg. 
Napari > plugins > PartSeg widgets > Label Selector > Select label tab. 

With 
image

without 

image


But if you need, I could prepare something shorter today evening.

**Review by jni — APPROVED** [review]

**Review by alisterburt — APPROVED** [review]

**Pull request merged**
