### PR TITLE
Evented viewer take 2

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR builds on and supersedes #1489 by moving our viewer over to be an evented dataclass. 

Unfortunately I'm running into the following error right now. 

```python-traceback
(base) czirwc1macos2701:napari nsofroniew$ python examples/add_labels.py
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/event_loop.py", line 79, in gui_qt
    yield app
  File "examples/add_labels.py", line 28, in <module>
    viewer = napari.view_image(image, name='coins', rgb=False)
  File "/Users/nsofroniew/GitHub/napari/napari/view_layers.py", line 9, in view_image
    (where <layer_type> is replaced with one of the layer types):
  File "/Users/nsofroniew/GitHub/napari/napari/components/viewer_model.py", line 743, in add_image
    self.layers.append(layer)
  File "/Users/nsofroniew/opt/anaconda3/lib/python3.7/_collections_abc.py", line 971, in append
    self.insert(len(self), value)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/containers/_evented_list.py", line 159, in insert
    self.events.inserted(index=index, value=value)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/event.py", line 510, in __call__
    if blocked.get(cb, 0) > 0:
TypeError: unhashable type: 'Viewer'
```

I wonder if @tlambert03 has any ideas why this might be happening.

I also ran into some problems with the `layers` import being shadowed by the layers attribute on dataclass, which forced me to rename some stuff.

I've got a couple other PRs in progress like #1952 and #2003 which are trying to simplify the viewer too, we'll see what merges first.

## Type of change

- [x] Refactor (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by tlambert03** [comment]
hmm, I'm not getting that unhashable error locally... have you changed stuff since posting this?

**Comment by sofroniewn** [comment]
> hmm, I'm not getting that unhashable error locally... have you changed stuff since posting this?

not that i'm aware of!! that's super interesting, I will look in more, thanks.

**Comment by tlambert03** [comment]
my first thought is that one of the attributes on the ViewerModel isn't hashable, and may need to be skipped in the `__hash__` using [`field(..., hash=False)`](https://docs.python.org/3/library/dataclasses.html#dataclasses.field)

... in comparison to #1489, some of the new stuff on the model may not be hashable
```
camera: Camera = Camera()
cursor: Cursor = Cursor()
grid: GridCanvas = GridCanvas()
scale_bar: ScaleBar = ScaleBar()
```

Do you specifically need all of those to be in the `__init__` signature?  Or can they just  be class vars?

**Comment by sofroniewn** [comment]
> Do you specifically need all of those to be in the __init__ signature? Or can they just be class vars?

No huge need, but I want them as part of the `asdict`. I tried moving things into the post init https://github.com/napari/napari/pull/2005/commits/ace6ba0ded0d1dba152aa610d629943e79cbad2a but it didn't help.

Super strange that it works for you. I'm on my mac python 3.7

**Comment by tlambert03** [comment]
> No huge need, but I want them as part of the asdict. I tried moving things into the post init ace6ba0 but it didn't help.

ah... then they'll need to be hashable anyway probably! :) lemme try py3.7.  Did you have to do any action to get the error?  or just happened immediately

**Comment by sofroniewn** [comment]
> lemme try py3.7. Did you have to do any action to get the error? or just happened immediately

nothing, just on launch, running an example script.

Also very curious if you understand why I had to drop usage of `layers.Layer` and `layers.Image` (see the diff). If I tried then it instead found what i would have thought of as `self.layers` the actual layer list instance

**Comment by tlambert03** [comment]
aha!  I get the issue on python3.7.  
this ought to make for some fun digging 😅

**Comment by tlambert03** [comment]
ok... couple options here (I recommend reading the bit on the `unsafe_hash` option in the [dataclass docs](https://docs.python.org/3/library/dataclasses.html#module-level-decorators-classes-and-functions)):

simplest option is to add this method to `ViewerModel`:

```python
def __hash__(self):
    return id(self)
```

I can't say I've exhaustively though through the ramifications of that, but I think it should be ok and it doesn't seem to break tests on master.

**Comment by tlambert03** [comment]
> Also very curious if you understand why I had to drop usage of layers.Layer and layers.Image (see the diff). If I tried then it instead found what i would have thought of as self.layers the actual layer list instance

This is because you've declared a class variable (`ViewerModel.layers`) that shadows the globally imported `layers` variable.  When python evaluates the `ViewerModel` class (and the type annotations in its methods), there is not yet an instantiated "self"... but since you are inside of a class definition, there _is_ a `locals()` namespace that can shadow `globals()`.  Running this code might help explain:
```python
x = 1

class A:
    def __init__(self):
       self.x = 2

    print("in A ... x =", x)
    print(locals())

class B:
    x: int = 2

    print("in B ... x = ", x)
    print(locals())
```
prints: (note the `'x': 2` part in the second dict)
```
in A ... x = 1
{'__module__': '__main__', '__qualname__': 'A', '__init__': <function A.__init__ at 0x7fef4819b1f0>}
in B ... x =  2
{'__module__': '__main__', '__qualname__': 'B', '__annotations__': {'x': <class 'int'>}, 'x': 2}
```

and if you want to get even deeper here, note that this _only_ happens because you declared a _default value_ for layers.  type annotations alone don't set class attributes:
```python
class C:
    x: int

    print("in C ... x =", x)
    print(locals())
    print(hasattr(C, 'x'))
```

prints: (note the absence of `'x': 2` here)
```
in C ... x = 1
{'__module__': '__main__', '__qualname__': 'C', '__annotations__': {'x': <class 'int'>}}
False
```

**Comment by sofroniewn** [comment]
I've just updated this with the latest changes and the hash suggestion from @tlambert03 (it looks like it's working!!!).

I still want to do some fiddling with how the other evented dataclasses are initialized on this object, but I think it's going well, and could provide an alternative to #2007 and #2006.

I think I'd still like to improve on #1952 and am not sure what to do about #2003

**Comment by sofroniewn** [comment]
I'm hopeful that we can get #2013 and #2018 merged and then this PR will be very simple!!

**Comment by sofroniewn** [comment]
This will be superseded by #2066

**Pull request closed without merging**
