### PR TITLE
Move `_mock_app` fixture to `_testsupport.py` and add it to `make_napari_viewer`

### PR DESCRIPTION
**Pull request by DragaDoncila**
# References and relevant issues
See [zulip thread](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/command.20'napari.2Eget_reader'.20already.20registered) for discussion.

# Description
Prior to this PR, running tests with the `make_napari_viewer` fixture **outside of napari** was failing due to shared instances of the `NapariApplication`. In internal tests, we `autouse` the `_mock_app` fixture, so each test had its own new instance.

To make sure `make_napari_viewer` behaves the same in our internal tests as it does externally, this PR moves the `_mock_app` fixture to the same file as `make_napari_viewer` and adds `_mock_app` to `make_napari_viewer` explicitly. We also remove the `autouse` flag in favour of explicitly adding `_mock_app` to tests that require the `NapariApplication` - note that tests using `make_napari_viewer` will still use to the mock application without needing to be changed.

### CODE REVIEW

**Review by lucyleeow — APPROVED** [review]
LGTM!

**Comment by DragaDoncila** [comment]
Hmm looks like a real failure - will take a look and ping for reviews after I fix it

**Comment by psobolewskiPhD** [comment]
I can confirm this fixes the issue I was having, documented in the zulip thread.

**Comment by DragaDoncila** [comment]
The errors we're seeing are only occurring on npe2 0.7.2 and 0.7.3, but not the latest two releases. The tests fail consistently when run in the terminal, but I can't get any of them to fail when debugging, to figure out exactly what's happening. I'm going to bump the npe2 min req to 0.7.4 :woman_shrugging:

**Comment by lucyleeow** [comment]
Clutching at straws, do you think https://github.com/napari/npe2/pull/325/files could be related?

**Review by jni — APPROVED** [review]

**Comment by lucyleeow** [comment]
It would be nice to follow up with an update to the app-model docs, to say that `_mock_app` is not autouse: https://napari.org/dev/developers/architecture/app_model.html#mock-app

**Comment by DragaDoncila** [comment]
@lucyleeow good point have opened [docs/#403 ](https://github.com/napari/docs/pull/403) to address

**Review by Czaki — APPROVED** [review]

**Pull request merged**
