### PR TITLE
[WIP] Console

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR is complementary to #421 and focuses on the getting the Qt aspects of embedding the console. Right now though it creates a new ipython console and provides the current `ViewerModel` as a variable called `viewer`. Nothing else is provided. See here:

console

Right now it can't be launch from `IPython` as it gets the following error
```python
MultipleInstanceError: Multiple incompatible subclass instances of InProcessInteractiveShell are being created.
```
But we can work on that

I'm also still having some problems with the sytlesheets, but I'll work on those

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jni** [comment]
See my comment in https://github.com/napari/napari/pull/421#issuecomment-514896018

**Comment by jni** [comment]
(But, in general, it's very cool that you have the in-process console working in the UI!!!)

**Comment by sofroniewn** [comment]
@jni I've been able to get this working with a `jupyter notebook` where there's now complete memory sharing between the notebook and our console.

**Comment by sofroniewn** [comment]
This has been superseded by #443

**Pull request closed without merging**
