### PR TITLE
Use conda-forge/napari-feedstock source on main

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

## Type of change

- [X] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Now that https://github.com/conda-forge/napari-feedstock/pull/32 is merged, the workflow can use `conda-forge/napari-feedstock` as the recipe source, instead of my fork.

This allows us to finalize goal number 5 in https://github.com/orgs/napari/projects/10

# How has this been tested?

- [ ] PR passes and artifacts are uploaded as usual

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Awesome! Nice work here @jaimergp - I will merge tomorrow unless hearing otherwise

**Comment by jaimergp** [comment]
Perfect!

**Comment by sofroniewn** [comment]
@jaimergp the "[ubuntu-latest 3.9 pip install](https://github.com/napari/napari/runs/5691416512?check_suite_focus=true#logs)" fail is independent of this PR right? can you confirm before I merge (we've got a bunch of failing tests right now and I don't want to make things worse!!)

**Comment by jaimergp** [comment]
@sofroniewn Yup, unrelated. I re-ran it just in case and it hasn't found the same issue, so we are good to go!

**Review by jni — APPROVED** [review]

**Pull request merged**
