### PR TITLE
use python 3.9 for mac tests until numcodecs 3.10 wheels are available

### PR DESCRIPTION
**Pull request by tlambert03**
perhaps one way to fix tests for mac?

### CODE REVIEW

**Comment by tlambert03** [comment]
Cc @Jni, @napari/core-devs ... would be nice to have our ci passing again

**Review by Czaki — APPROVED** [review]
did you know why test fain on python 3.10?

**Comment by psobolewskiPhD** [comment]
Looks like no numcodecs wheel on 3.10?
I believe the next release of numcodecs will have 3.10 wheels.

**Comment by tlambert03** [comment]
> Looks like no numcodecs wheel on 3.10?
> I believe the next release of numcodecs will have 3.10 wheels.

Yeah it’s numcodecs related… but didn’t dig deeper.  There used to be wheels right? So I wonder whether something changed with GitHub mac envs.  In any case, it’s not important that we specifically test 3.10 on mac

**Comment by psobolewskiPhD** [comment]
I don't think so?
I don't think numcodecs release supports 3.10 at all yet—on macOS atleast?
https://github.com/zarr-developers/numcodecs/issues/326#issuecomment-1158400148

**Comment by tlambert03** [comment]
I dunno... it was working a few days ago on 3.10: https://github.com/napari/napari/runs/6917162090?check_suite_focus=true

**Comment by jni** [comment]
As noted in the numcodecs thread linked by @psobolewskiPhD, the GHA runner itself changed. It doesn't look like there were ever wheels for 3.10 for the current release, so I presume it was compiling fine on the previous runner and something changed in the new runner. (Again, looking at the list, it seems it's as innocuous as Python 3.10.4 -> 3.10.5, but that's where I stop looking! 😅)

At any rate, I'm happy to temporarily downgrade to 3.9 for now.

**Pull request merged**
