### PR TITLE
Make test log easier to read by removing `-v` from pytest call

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues

https://github.com/napari/napari/pull/6979#discussion_r1642597787

# Description

Currently, with over 4029 tests, printing a single line per test makes the log non-readable and for me, it is harder to find which test is failing. 

Verbose output is useful for debugging when test fail with segfault, but then it could be enabled in such a PR.

### CODE REVIEW

**Review by jni — APPROVED** [review]
I'm fine with this change, but we should wait a bit to hear some opinions from other core devs.

**Comment by jni** [comment]
(I'm removing the 0.5.0 milestone because I want to start using that for ready-to-merge PRs *or* PRs/issues blocking release, so that we have a good read on what needs to be done for release. Once we move this to ready-to-merge, we can add it back.)

**Comment by brisvag** [comment]
No strong opinions here.

**Comment by Czaki** [comment]
For more context. To see report about what happen wrong in PR without `-v` it is enough to scroll 372 lines 
obraz

Without it is 4151 and multiple waiting until github load next part of log (see position on slider on right).



https://github.com/napari/napari/assets/3826210/6bb03c84-0c87-432d-ae6d-7782c723abe4

**Review by psobolewskiPhD — APPROVED** [review]
I like this, I've found the verbose really annoying on phone app. This should make life easier.

@jni Isn't 0.5 milestone fine?
We're using 0.5.0 as the release one.

**Comment by jni** [comment]
> Isn't 0.5 milestone fine?

does that still pass the milestone check? 🤔 my goal was for it not to pass that check if the r2m label was added.

**Pull request merged**
