### PR TITLE
Add `_json_encode` method API for EventedModel serdes

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
Thinking about serialization and deserialization of EventedModel objects, I wanted to avoid having to manage a bunch of different `JSON_ENCODERS` dicts (like, from `Array`, and perhaps from the colormanager stuff in #2204, and probably for serialization of the new `Selection` object in #2293).  This PR introduces an internal API for adding serdes support for custom fields:

here's a "well behaved" object:
```python
class MyObj:
    def __init__(self, a: int, b: str) -> None:
        self.a = a
        self.b = b

    def __eq__(self, other):
		# alway nice to provide your equality operator
        return self.__dict__ == other.__dict__

    def _json_encode(self):
		# this method should return an object that works
		# as input to `json.dumps` _not_ the output of json.dumps itself
        return self.__dict__

	# pydantic stuff

    @classmethod
    def __get_validators__(cls):
        yield cls.validate_type

    @classmethod
    def validate_type(cls, val):
        # validator should be able to whatever the output of
		# _json_code is, in this case, it's a dict.
        if isinstance(val, dict):
            a = val.get('a')
            b = val.get('b')
        elif isinstance(val, MyObj):
            return val
        # perform additional validation here
        return cls(a, b)

```

In `EventedMetaclass.__new__`, any discovered `_json_encode` methods will be added to the `json_encoders` for that particular model.

Finally, at the top of `evented_model`, `_BASE_JSON_ENCODERS` is a dict of encoders for types _outside_ of napari (such as np.ndarray).

cc @sofroniewn 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
Great idea, @tlambert03 ! This will indeed be useful for #2204.

**Review by sofroniewn — APPROVED** [review]
This seems fine to me, I guess the alternative syntax would have been to subclass the config, grab the existing json encoder and manually add to it? Maybe that seems simpler in my head than it actually would be in code, but aside from that is there any advantage? Do you happen to have an example of what the old syntax is, just to see how painful it would have been? If too painful to even write, don't worry, but just trying to get a sense for what is gained. Does it additionally solve other issues (apologies if this is a dumb question, my brain is a little fried right now, long day!)

**Comment by sofroniewn** [comment]
I just looked at https://github.com/napari/napari/pull/2293/files#r581257788 a little more, definitely helps see how the new syntax will be nicer. We should be able to merge this tomorrow!!

**Comment by tlambert03** [comment]
> I guess the alternative syntax would have been to subclass the config, grab the existing json encoder and manually add to it? Maybe that seems simpler in my head than it actually would be in code, but aside from that is there any advantage?

Yeah, this kinda goes back to my comment about remembering the distinction between "models vs fields" [here](https://github.com/napari/napari/pull/2293#discussion_r581256411).  It's the _model_ that has the config with the list of json_encoders (a mapping of type to encoder callable), but it's the _field_ (i.e. the type itself) that knows how to encode itself.  So the alternative syntax here is either to add the encoder to _every_ model that uses a particular field:

```python
class MyObj:
    ...

MyObjEncoder = {MyObj: lambda x: x.__dict__}

class ModelA(ParentModel):
    o: MyObj

    class Config(ParentModel.Config):
		json_encoders = {**ParentModel.Config, **MyObjEncoder}

class ModelB(ParentModel):
    o: MyObj

    class Config(ParentModel.Config):
		json_encoders = {**ParentModel.Config, **MyObjEncoder}    
```

or to add the encoder to every model (via the base EventedModel) "just in case" it runs into that field... 

```python
from somewhere import SOME_ENCODER

class ParentModel:
	class Config:
		json_encoders = SOME_ENCODER
```
this is what we're currently doing, but at the moment, we only have a single JSON_ENCODERS dict that we import from the custom `Array`.  Once we start adding more custom _field_ types (not models), then we need to somehow combine all of those encoder dicts in `evented_model.py`, which means importing and merging encoder dicts from every other file that _may_ be used in any other model that inherits from `ParentModel`:
```python
from somewhere import SOME_ENCODER
from somewhere_else import SOME_ENCODER as ANOTHER_ENCODER
from yet_another import SOME_ENCODER as YET_ANOTHER

ENCODERS = {**SOME_ENCODER, **ANOTHER_ENCODER, **YET_ANOTHER}

class ParentModel:
	class Config:
		json_encoders = ENCODERS
```

So, the point of this PR is to say: _during class creation_ (i.e. in the metaclass `__new__` method), if a model uses a field that provides an encoder via the `_json_encode` method, go ahead and add it to the model Config.

Anyway, I just want to re-emphasize the difference between [fields](https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types) and [models](https://pydantic-docs.helpmanual.io/usage/models/).  It's great to have this excellent `EventedModel` base class hammer, but not every custom type is an appropriate nail :)  Some things (particularly small/focused classes that come with their own carefully crafted event system like the evented containers, or things that don't need events unless they are part of some _other_ model) are better off as fields, and I think we should definitely make sure that we're building components that behave nicely as pydantic fields, like the `MyObj` example in the first post.

**Comment by sofroniewn** [comment]
> Anyway, I just want to re-emphasize the difference between fields and models.

Ok, I'm back with the plot again. Love this! It was actually something that when I wrote the `Array` field I was thinking - the serialization information (and eq information) should live on that field itself.

I'll merge this now, and as we use it more I'm sure we'll be even more grateful. Thanks for the long explanation too, it definitely helped.

**Pull request merged**
