### PR TITLE
Skip axes with size 1 in roll operation

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Described in #1664. Prevent from black screen when image has dimension of size 1. 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have added tests that prove my fix is effective or that my feature works

@sofroniewn I'm not sure if my test are enough. Maybe some additional case should be added?

### CODE REVIEW

**Comment by sofroniewn** [comment]
> @sofroniewn I'm not sure if my test are enough. Maybe some additional case should be added?

It looks right now like we don't have any tests for roll, so can you maybe split this one into two. The first one `nsteps` are all large and you can just check that we iterate through all axes as expected.

The second test should check that we skip an axis if nsteps is `1` for that axis and should have a name/ doc string that makes it clear that is what we are testing.

How does that sound?

**Comment by Czaki** [comment]
> How does that sound?

Ok, I will add something like this tomorrow.


Did you understand macos test fail?

**Comment by sofroniewn** [comment]
> Did you understand macos test fail?

Mac OS fail is unrelated to this PR, we have an issue discussing it in #1656 - it relates to the latest dask release, which we need to fix asap.

Windows test is also unrelated to this PR and CI related

**Comment by Czaki** [comment]
> > Did you understand macos test fail?
> 
> Mac OS fail is unrelated to this PR, we have an issue discussing it in #1656 - it relates to the latest dask release, which we need to fix asap.
> 
> Windows test is also unrelated to this PR and CI related

So why not pin working version until solution was found?

**Comment by sofroniewn** [comment]
> So why not pin working version until solution was found?

The issue seems to be more about a timeout on our test failing rather than napari not working with the latest version of dask, so i'm not sure we need to pin, but if we go much longer without finding a solution we might need to. I can try looking at this more tonight/ tomorrow. Maybe @jni can too

**Comment by sofroniewn** [comment]
no rush on this @Czaki, but in case it got lost in chat about out CI/ tests - which should now be resolved, i'm still waiting on splitting the test into two before merge, if that's still ok!!

**Comment by Czaki** [comment]
@sofroniewn Done. I expand a little test.

**Review by sofroniewn — APPROVED** [review]
LGTM! thanks for the additional tests, I will merge once tests pass!!

**Pull request merged**
