### PR TITLE
add missing QSpinBox import in Labels layer controls

### LINKED ISSUE #2618: QSpinBox import missing in Labels layer controls
## 🐛 Bug

I think the QSpinbox import was accidentally removed from the labels layer controls in #2608 . There is a remaining QSpinBox for the ndim attribute.

https://github.com/napari/napari/blob/ad752649a44debc928d4a8c48527e96f5220a495/napari/_qt/layer_controls/qt_labels_controls.py#L115

## To Reproduce

1. Run the `add_labels.py` example

```python
Traceback (most recent call last):
  File "/Users/kyamauch/Documents/napari/examples/add_labels.py", line 30, in <module>
    label_layer = viewer.add_labels(label_image, name='segmentation')
  File "<string>", line 5, in add_labels
  File "/Users/kyamauch/opt/miniconda3/envs/napari/lib/python3.7/_collections_abc.py", line 971, in append
    self.insert(len(self), value)
  File "/Users/kyamauch/Documents/napari/napari/components/layerlist.py", line 85, in insert
    super().insert(index, new_layer)
  File "/Users/kyamauch/Documents/napari/napari/utils/events/containers/_selectable_list.py", line 63, in insert
    super().insert(index, value)
  File "/Users/kyamauch/Documents/napari/napari/utils/events/containers/_evented_list.py", line 179, in insert
    self.events.inserted(index=index, value=value)
  File "/Users/kyamauch/Documents/napari/napari/utils/events/event.py", line 573, in __call__
    self._invoke_callback(cb, event)
  File "/Users/kyamauch/Documents/napari/napari/utils/events/event.py", line 599, in _invoke_callback
    cb_event=(cb, event),
  File "/Users/kyamauch/Documents/napari/napari/utils/events/event.py", line 593, in _invoke_callback
    cb(event)
  File "/Users/kyamauch/Documents/napari/napari/_qt/layer_controls/qt_layer_controls_container.py", line 118, in _add
    controls = create_qt_layer_controls(layer)
  File "/Users/kyamauch/Documents/napari/napari/_qt/layer_controls/qt_layer_controls_container.py", line 49, in create_qt_layer_controls
    return controls(layer)
  File "/Users/kyamauch/Documents/napari/napari/_qt/layer_controls/qt_labels_controls.py", line 115, in __init__
    ndim_sb = QSpinBox()
NameError: name 'QSpinBox' is not defined

Process finished with exit code 1
```

## Environment

napari: 0.4.3.dev241+g0b1bdac.d20210412
Platform: Darwin-19.6.0-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.7.9 (default, Aug 31 2020, 07:22:35) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 INTEL-14.7.12
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- console: 0.0.3
- scikit-image: 0.4.3.dev241+g0b1bdac.d20210412
- svg: 0.1.4

### PR DESCRIPTION
**Pull request by kevinyamauchi**
# Description
This PR adds back in a missing import in the Labels layer controls (issue described in #2618 )

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# References
Fixes #2618 

# How has this been tested?
- [ ] all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
Thank you @kevinyamauchi!

**Comment by clbarnes** [comment]
Oops, my bad, thanks for catching it! I had thought it was only used for cases now covered by the LargeIntSpinBox. Surprised that got through CI.

**Comment by tlambert03** [comment]
> Surprised that got through CI.

Me too! 🤨

**Comment by kevinyamauchi** [comment]
All good! Thanks for adding the `LargeIntSpinBox`, @clbarnes !

**Pull request merged**
