### PR TITLE
Add test for theme changing

### LINKED ISSUE #669: switching themes causes incomplete updates
## 🐛 Bug

The 'light' theme for napari is looking pretty terrible these days:

Screen Shot 2019-11-09 at 8 58 44 pm

We should update it and make sure that any PRs that touch the UI are tested with both themes.

Also worth noting that the base layer needs to have blending mode "translucent" — with additive, you get a totally white canvas. Perhaps it's a chance to play with inverted LUTs or something, not sure.

Finally, I'm not sure whether there is a way to set the theme globally. I could set it on a Viewer instance, but I could not set it on the `napari.Viewer` class. It seems to me that it should be more of a global than an instance setting.

## To Reproduce

```python
import napari
v = napari.Viewer()
v.theme = 'light'
```

This crashes:

```python
import napari
napari.Viewer.theme = 'light'
v = napari.Viewer()
```

This makes sense because it replaces a property with a text string! But I couldn't find how else to set the theme.

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
closes #669 and adds a test to make sure that >99.5% of the pixels in a screenshot have changed when switching between dark and light themes. 

## Type of change

- [x] Test

# How has this been tested?

- [x] takes two screenshots and looks for the ratio of non-equal pixels between dark/light themes

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
This is great, but test is currently failing. I think we need to add the `show=True` to the making of the viewer and then with windows and CI skip like we do here https://github.com/napari/napari/blob/master/napari/_tests/test_with_screenshot.py#L7-L10. I might move this test to the `test_with_screenshot.py` folder too, just to keep all those tests together. Thoughts?

**Comment by tlambert03** [comment]
> This is great, but test is currently failing. I think we need to add the show=True to the making of the viewer and then with windows and CI skip like we do here 

I think it works ok without showing... it was failing because the [ratio of non-different pixels](https://cirrus-ci.com/task/6231021521731584?command=test#L1136-L1137) was _slightly_ higher on CI than it was locally. I just tweaked the algorithm, and it's working now.

> I might move this test to the test_with_screenshot.py folder too, just to keep all those tests together. Thoughts?

I kinda like keeping the theme test where it already was in `test_viewer`...  it _uses_ the screenshot as a tool, but it is not testing the screenshot in any way... so it feels a bit out of place in the screenshot file.

**Comment by sofroniewn** [comment]
> I think it works ok without showing... it was failing because the ratio of non-different pixels was slightly higher on CI than it was locally. I just tweaked the algorithm, and it's working now.

ah nice, my bad. i thought we needed to show for all screenshots (see below)

> I kinda like keeping the theme test where it already was in test_viewer... it uses the screenshot as a tool, but it is not testing the screenshot in any way... so it feels a bit out of place in the screenshot file.

the tests in screenshot file also just use screenshot as a tool (mainly for vispy rendered things). i maybe misunderstood what we needed to `show` and there could be some things in that file that don't actually need to `show`.

**Review by sofroniewn — APPROVED** [review]
LGTM! thanks for adding

**Pull request merged**
