### PR TITLE
Guard multi-threaded access to napari's global dask cache

### LINKED ISSUE #5591: Async slicing: dask cache error when multiple layers share data
@andy-sweet As mentioned directly already, I've started testing this new async branch with our OME-Zarr data and ran into some issues with multi-channel data I'll report here in a bit more detail:

I'm using a 3 channel OME-Zarr dataset like this little test set here: https://zenodo.org/record/7120354
I installed this branch and the `napari-ome-zarr` plugin v0.5.2. I launch napari, then set the `_force_sync` to False from the napari console and drag & drop the Zarr plate into napari.

The first channel gets loaded correctly and can be browsed in the awesome async mode. But it then hits this issue when trying to load the additional channels in the OME-Zarr file (=> they become additional layers in napari):
```
~/mambaforge/envs/napari-dev-default-ome/lib/python3.10/site-packages/dask/cache.py:56, in Cache._posttask

     55 def _posttask(self, key, value, dsk, state, id):
---> 56     duration = default_timer() - self.starttimes[key]
        key = ('from-zarr-0424ef0e6522743e819a0000fe7dc515', 1, 0, 0, 0)
        default_timer = <built-in function perf_counter>
        self.starttimes = {}
        self = <dask.cache.Cache object at 0x1036dff70>
     57     deps = state["dependencies"][key]
     58     if deps:

KeyError: ('from-zarr-0424ef0e6522743e819a0000fe7dc515', 1, 0, 0, 0)
```
In the full stacktrace, it's downstream of self._load_slice(slice_data).

Sometimes, it loads 2 channels and fails for the third, sometimes it loads just one channel and fails for the second.

_Originally posted by @jluethi in https://github.com/napari/napari/issues/5377#issuecomment-1439869471_

### PR DESCRIPTION
**Pull request by andy-sweet**
# Closes / Fixes

Closes #5591

# Description
Each layer has an attribute `dask_optimized_slicing`, which is a context manager which provides temporary configuration and caching of dask computations when `Layer.data` is a dask array. The cache is an instance of `dask.cache.Cache` and is shared across all napari layers. However, it [is not thread safe](https://github.com/dask/distributed/issues/2372#issuecomment-441747606). This is problematic when several layers share the same underlaying dask array as in #5591.

With the current approach to async slicing, it's possible to do some slicing on the main thread (e.g. with `Layer.refresh` in `Layer.__init__`) and some on the slicing thread. This can cause a key error in the dask cache since the key in question is derived from the underlying dask array and multi-threaded access is not guarded (see #5591 for one reproducing case).

The fix here is a crude one: we simply guard all access to the shared dask cache with a shared re-entrant lock. This shouldn't have many performance implications for async slicing because it mostly works on one thread anyway (especially if #6008 is merged). But since `Layer.dask_optimized_slicing` is public, it's possible this could have implications for others than depend on that.

An alternative fix could be to write our own `Cache` that extends `dask.callbacks.Callback`, but adds some internal thread safety or at least avoids key collisions for specific task runs (e.g. by adding a UUID to the key used in the `starttimes` dict). I avoided this for now since it is more complicated, but am open to opinions.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# How has this been tested?
- [x] all tests pass with my change

I mostly tested this manually by changing `_LayerSlice._force_sync = False` and running napari with [the dataset provided in the linked issue](https://zenodo.org/record/7120354). Before the change, I could fairly reliably reproduce the error (especially after running `sudo purge` on macOS to purge the file cache), and could not reproduce it afterwards. I tried to write a test to reproduce the issue consistent, but couldn't immediately think of a way to pause execution mid-dask-task in the right way.

### CODE REVIEW

**Comment by brisvag** [comment]
> Another fix could be to move all slicing to the slicing thread by replacing more/all internal usage of `Layer.refresh` (which immediately updates slice state) with `Layer.reload` (which emits an event that the viewer responds to).

What are the downsides to this? If I understand correctly, this sounds more like the "right direction", embracing async fully.

**Comment by andy-sweet** [comment]
> > Another fix could be to move all slicing to the slicing thread by replacing more/all internal usage of `Layer.refresh` (which immediately updates slice state) with `Layer.reload` (which emits an event that the viewer responds to).
> 
> What are the downsides to this? If I understand correctly, this sounds more like the "right direction", embracing async fully.

I have two concerns.

1. `Layer.refresh` changes state on the layer independently of the viewer, whereas `Layer.reload` doesn't. None of that state is public (as far as I know), but lots of other functionality is dependent on it. The only use of `Layer.reload` so far is in the drawing loop when the viewer must be present. My plan was to incrementally change these, fixing tests and bugs as they come up.
2. Since `Layer.refresh`, `Layer.set_view_slice`, and `Layer.dask_optimized_slicing` are public, others may be using these on the main thread, which could cause the same interleaving problems this fixes.

(1) worries me more than (2) since it will have an effect when async is off (as it currently is).

**Comment by Czaki** [comment]
Please remember that in the main thread, there should be no waiting on the release of the lock as it may lead to a total freeze of GUI.

**Comment by andy-sweet** [comment]
> Please remember that in the main thread, there should be no waiting on the release of the lock as it may lead to a total freeze of GUI.

Do you mean deadlock? I can't see how the changes here could cause that within the napari codebase, so any more information would be useful. Others might be doing fun stuff with dask and other locks outside of napari, but that's out of our control.

The dask computation could take a long time, but that's true independent of these changes. I.e. it will cause `main` to freeze right now. And the lock is only held while this occurs and the cache is updated.

**Comment by Czaki** [comment]
> Do you mean deadlock

No. But the whole change of async API is to prevent GUI freezing because of waiting on a slow data sources. 
And if you add locks and wait in the main thread, it may reintroduce it. The proper approach is to try to lock it and if fails then process events waiting in the Qt event queue.

**Comment by andy-sweet** [comment]
> > Do you mean deadlock
> 
> No. But the whole change of async API is to prevent GUI freezing because of waiting on a slow data sources. And if you add locks and wait in the main thread, it may reintroduce it. The proper approach is to try to lock it and if fails then process events waiting in the Qt event queue.

Thanks for clarifying. And agreed. That's one of the reasons I avoided locks in the design I proposed for async slicing. As for your proposed solution, it's a good idea, but it also increases the coupling with Qt and its event loop - maybe there's a way to abstract that?

Also, like @brisvag mentioned, eventually all slicing should occur on the slicing thread, so this fix wouldn't be needed then (outside of external public access). My plan was to take incremental steps towards doing all slicing off the main thread and improve things gradually. But maybe there's some appetite to get things done all at once despite the bigger risk.

**Comment by aganders3** [comment]
In the mean time - what about something like this? For this specific instance the locked resource is just a cache, so it shouldn't be strictly _necessary_ for any thread to have it. This may instead block the main thread with a compute-heavy task that misses the cache, but at least it would not be waiting for a lock.

Of course it would be a shame if the slicing thread misses the lock for a fast operation on the main thread, potentially doing a lot of extra work. I'm not sure if it's too expensive to change the timeout depending on the thread.

```diff
diff --git a/napari/utils/_dask_utils.py b/napari/utils/_dask_utils.py
index 44c2be359..46bb3da79 100644
--- a/napari/utils/_dask_utils.py
+++ b/napari/utils/_dask_utils.py
@@ -152,7 +152,13 @@ def configure_dask(data, cache=True) -> DaskIndexer:
     @contextlib.contextmanager
     def dask_optimized_slicing(memfrac=0.5):
         opts = {"optimization.fuse.active": False}
-        with dask.config.set(opts) as cfg, lock, _cache as c:
-            yield cfg, c
+        if lock.acquire(timeout=0.05):
+            try:
+                with dask.config.set(opts) as cfg, _cache as c:
+                    yield cfg, c
+            finally:
+                lock.release()
+        else:
+            yield None, None
 
     return dask_optimized_slicing
```

Also (totally unrelated) - what is `memfrac` doing here?

**Comment by andy-sweet** [comment]
> In the mean time - what about something like this? For this specific instance the locked resource is just a cache, so it shouldn't be strictly _necessary_ for any thread to have it. This may instead block the main thread with a compute-heavy task that misses the cache, but at least it would not be waiting for a lock.
> 
> Of course it would be a shame if the slicing thread misses the lock for a fast operation on the main thread, potentially doing a lot of extra work. I'm not sure if it's too expensive to change the timeout depending on the thread.
> 
> ```diff
> diff --git a/napari/utils/_dask_utils.py b/napari/utils/_dask_utils.py
> index 44c2be359..46bb3da79 100644
> --- a/napari/utils/_dask_utils.py
> +++ b/napari/utils/_dask_utils.py
> @@ -152,7 +152,13 @@ def configure_dask(data, cache=True) -> DaskIndexer:
>      @contextlib.contextmanager
>      def dask_optimized_slicing(memfrac=0.5):
>          opts = {"optimization.fuse.active": False}
> -        with dask.config.set(opts) as cfg, lock, _cache as c:
> -            yield cfg, c
> +        if lock.acquire(timeout=0.05):
> +            try:
> +                with dask.config.set(opts) as cfg, _cache as c:
> +                    yield cfg, c
> +            finally:
> +                lock.release()
> +        else:
> +            yield None, None
>  
>      return dask_optimized_slicing
> ```

Thanks for the idea. Though I always have a bit of a negative reaction to adding durations - though this one is a non-functional change right? Checking if we're on the main thread seems pretty cheap (on my somewhat modest laptop):

```python
In [1]: import threading

In [2]: %timeit threading.current_thread() == threading.main_thread()
242 ns ± 4.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

I have a [WIP PR](https://github.com/andy-sweet/napari/pull/52) where I may move all slicing to the slicing thread, so I'm probably going to try that before making this PR ready to merge.

> Also (totally unrelated) - what is `memfrac` doing here?

The way I read it I think `memfrac` here is unused. Instead `_DEFAULT_MEM_FRACTION` is used to set the size of the cache by default, unless the dask cache size setting has been explicitly set.

**Comment by aganders3** [comment]
Thanks - I noticed after playing with this that you have a potentially better fix in progress, so no worries if you want to just put this out of your head until you might need it :).

I'm not sure what you mean by non-functional change. Im also generally averse to adding timeouts and sleeps - the duration here is really optional or arbitrary. If it's that cheap to check you could set the main thread to not block at all and just proceed to do its operations without the cache/fuse context if the lock is not available, but allow the slicing thread to block indefinitely.

**Comment by andy-sweet** [comment]
> I'm not sure what you mean by non-functional change.

Sorry, by non-functional the result should always be the same regardless but the timing of the result might change depending on this check (i.e. some slices may take longer than others even if the cache has a result). But it should never change the value of the result itself.

**Comment by aganders3** [comment]
Ah, yeah that was my thinking. The cache is really more like a "nice to have" resource than a requirement.

**Comment by andy-sweet** [comment]
Closing this since #5591 was fixed in a different way.

**Pull request closed without merging**
