### PR TITLE
DOC Fix add image examples

### PR DESCRIPTION
**Pull request by lucyleeow**
# Description
Uses `add_image` instead of `view_image` as per the text and title of the example.

Addresses #4911

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by Carreau** [comment]
I have no objections to this, but for me that raises the question of the utility of having `add_*` and `view_*`, and/or if we should advertise both methods in general.

So I'm going to approve, but let someone else make the decision of merging.

**Review by Carreau — APPROVED** [review]

**Comment by lucyleeow** [comment]
Thanks @Carreau 

I also thought about `add_*` vs `view_*` and now that I have read more of the examples I think the `view_*` would be better.

`view_*` us generally used. The times where `add_*` is used in examples is when a viewer has already been created. In the getting started/[napari viewer tutorial](https://napari.org/stable/tutorials/fundamentals/viewer.html) page we also first introduce `view_image` and later mention that you can create an empty viewer then add images.

I will amend these examples to use `view_*` but happy to take suggestions/opinions.

**Review by Carreau — APPROVED** [review]

**Comment by lucyleeow** [comment]
Thanks @Carreau !

**Comment by kandarpksk** [comment]
I'm only noticing this now, but my original intent with #4911 was to get an example for add_image to understand how to open an empty viewer and then open an image. Maybe it makes sense to have another example to illustrate the case I'm describing.

**Comment by psobolewskiPhD** [comment]
I agree, the napari.org homepage shows how to use viewer.view_image to open a viewer with an image. Using add_image is the more typical use case, because you want to add something to an existing viewer.
So the syntax of creating a viewer—with a name—and then reusing the viewer is pretty key.

**Comment by Carreau** [comment]
Is it worth opening an issue to discuss whether the convenience of `view_*` is worth the user's confusion, and the added complexity to maintain/update codebase and docs ?

**Comment by lucyleeow** [comment]
A quick solution to this:

>  add_image to understand how to open an empty viewer and then open an image

is that we could amend this example: https://napari.org/stable/gallery/get_current_viewer.html , adding to the end how to add an image layer after getting the current viewer.

**Comment by jni** [comment]
@Carreau 

> Is it worth opening an issue to discuss whether the convenience of view_* is worth the user's confusion, and the added complexity to maintain/update codebase and docs ?

I feel like #4693 is that issue? 😊 

> > add_image to understand how to open an empty viewer and then open an image
> 
> is that we could amend this example: [napari.org/stable/gallery/get_current_viewer.html](https://napari.org/stable/gallery/get_current_viewer.html) , adding to the end how to add an image layer after getting the current viewer.

I don't think that's a good solution because creating a viewer is a key step in Python. I don't like `get_current_viewer` as a general pattern, it's more of a last ditch attempt in cases where we *really* need to deal with state, such as plugins, which don't have access to the full runtime. In Python code using napari, we should always create the viewer, or get it as input to our functions.

But I'm hoping imshow followed by deprecation of `view_` will go a long way here.

**Comment by lucyleeow** [comment]
I'm not sure https://github.com/napari/napari/issues/4693 addresses:

> Using add_image is the more typical use case, because you want to add something to an existing viewer.

for the above, we could amend the 'Add image' example to ~explain how to add another image to the existing viewer~ create an empty viewer first and then add an image layer. Or make another example on how to add an image layer to an existing viewer?

**Comment by jni** [comment]
Back in the very early days, if I remember correctly, our README had something like, "Here's how you make a viewer, which is the main object to interact with in napari. To add an image, you then use the "add_image" method. Because this is such a common pattern, we made a shortcut with the `view_image` function." So we should rework that with `imshow` and it should be pretty much on the front page imho.

**Comment by lucyleeow** [comment]
> So we should rework that with imshow and it should be pretty much on the front page imho.

Maybe this documentation update should be part of: https://github.com/napari/napari/pull/4928 ?

**Comment by Carreau** [comment]
Maybe #4693 addresses that, but is it really that bad to have 2 lines instead of 1 ?

**Comment by jni** [comment]
LOL Fair point @Carreau but I think the answer is yes, especially in interactive use. In code I always do `fig, ax = plt.subplots()`, but in IPython sessions I often just do `plt.plot` or `plt.imshow()`. I would appreciate if those gave me back the figure and axes to be honest! 😃 This also relates to #4740 — we really want to be able to offer a quick, light way to look at nd-images.

@lucyleeow 

> Maybe this documentation update should be part of: https://github.com/napari/napari/pull/4928 ?

Maybe but I'd say let's leave it until after. Scope creep in PRs is a pain for contributors. Typically if someone proposes a new thing in a PR and we're not sure about it, I'll ask for docs updates because it helps clarify the utility. In this case I'm really quite sure about it! 😂

**Pull request merged**
