### PR TITLE
Forward port of release note updates for 0.4.16rc2 and rc3

### PR DESCRIPTION
**Pull request by jni**
I made these changes in the v0.4.16x branch made for the 0.4.16 release (see discussion in [this Zulip thread](https://napari.zulipchat.com/#narrow/stream/215289-release/topic/0.2E4.2E16.20schedule/near/280157582)), this brings them forward to main.

### CODE REVIEW

**Comment by Czaki** [comment]
I do not see #4537

**Review by tlambert03 — APPROVED** [review]

**Comment by tlambert03** [comment]
> I do not see #4537

It didn't have the 0.4.16 milestone label on it.  (I merged it, so should have added it).  I've just added the milestone label... but it should be added here too

**Comment by jni** [comment]
Oops! I'll push rc3 shortly with that one too.

**Comment by jni** [comment]
Ok rc3 has been released with 4 more commits, including imageio v2, and I've updated these notes. Hopefully this is ready to merge.

**Comment by cnstt** [comment]
There were also some fixes in the documentation about alt text (#4502, #4473), but it is probably not useful to notify users about this bugfix as it was just a rendering issue with the documentation.

**Comment by Carreau** [comment]
rebased to fix conflicts.

**Comment by jni** [comment]
@cnstt thank you for those fixes! They are not in the 0.4.16 branch, which branched off from main before those changes came in. Since they are not critical bug fixes, they will appear in the release after this one.

**Comment by cnstt** [comment]
> @cnstt thank you for those fixes! They are not in the 0.4.16 branch, which branched off from main before those changes came in. Since they are not critical bug fixes, they will appear in the release after this one.

No problem at all, just wanted to ask in case it had been useful to notify about those fixes in the changelog :laughing:

**Pull request merged**
