### PR TITLE
Fix minreq tests

### PR DESCRIPTION
**Pull request by alisterburt**
This PR should fix the minimum requirements tests problems from #2045 

The problem was that pandas 1.2.0 was released on the 26th December which came with an increase in numpy version dependency to 1.16.5. The napari minimum numpy version is 1.16.0.

I added a script similar to the `tools/minreq.py` script called `tools/minreq_test.py` which updates the testing requirements to pin the pandas version to 1.1.5, which has a lower numpy requirement than our 1.16.0.

I also added the running of this script to the CI workflow config

### CODE REVIEW

**Comment by alisterburt** [comment]
hmm, looks like this didn't work as expected on the CI despite appearing to work locally, looking into it

**Comment by alisterburt** [comment]
I had to make sure the script was called prior to installation of the test requirements which makes sense, the tests now get further (no import error for the numpy/pandas business) but get the magicgui segfault you mentioned in #2045 

edit: not sure where the segfault was mentioned, it's not #2045 but in any case, here's where it happens https://cirrus-ci.com/task/5121762927050752?command=test_pyside2_with_coverage#L1219

**Comment by sofroniewn** [comment]
Thanks for this attempt @alisterburt - alternatively could we just bump our min numpy dependency to `numpy>=1.16.5`. It's only a patch release change for numpy and so should be backwards compatible with `1.16.0`, it just looks like they fixed a bug in `1.16.5` which was essential for pandas to move forward.

If @tlambert03/ @jni are ok with bumping to `numpy>=1.16.5` maybe @alisterburt you can make a new PR which does only that and we then close this PR. Thoughts?

**Comment by alisterburt** [comment]
sounds good, I've put the PR there ready in case the others agree!

**Comment by sofroniewn** [comment]
Closed by #2050

**Pull request closed without merging**
