### PR TITLE
Add napari CLI to launch a viewer for input images

### PR DESCRIPTION
**Pull request by jni**
# Description

```
napari *.tif
```

now launches a napari viewer with all the images concatenated along the z axis.

Lots of edge cases are not taken into account here but thought I'd get this started!

## Type of change
- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
This would now make file io something part of this repo, which I'm not 100% sure about curious how others feel? I think if we do support this we should also look into supporting drag-and-drop of `.tif` into an already open viewer to easily add images.

I had previously thought that file io would all be in a separate repo and a plugin but I'm open to this.

If I just type in napari does it open an empty viewer?

**Comment by jni** [comment]
We could make all io optional, with a helpful error message if no io library is available.

To clarify the motivation for this PR, it's the tweet posted by @freeman-lab:
https://twitter.com/vallens/status/1105957771252400128

=)

Coordinating this over multiple repos would be challenging, I think.

> If I just type in napari does it open an empty viewer?

No, it will demand an input argument, but it will do so nicely. =) (ie it will print the usage string, not crash)

**Comment by sofroniewn** [comment]
How do you feel about adding drag / drop support into the viewer in the future? If so then having io in the repo makes sense (as does supporting opening an empty viewer with no images to start with).

The question then might be how far do we go in supporting input formats - i.e. can I drag and drop a zarr file too? Or data for a shapes layer / markers layer?

**Comment by sofroniewn** [comment]
For the image reading do you think we should use [imageio](https://github.com/imageio/imageio) instead of `skimage.io`?

I guess you sort of answered the `no` to multiple repos which is fine for now, though I could see including `imageio` / `skimage.io` in a separate [napari-io](https://github.com/napari/napari-io) repo that would also include `zarr` / `dask` as a dependency for loading big files, and any code for doing io on our shapes / markers layers as one way to go, otherwise all those things might need to be dependencies of this main repo, but they aren't used for anything other than io. Could still make sense to keep it all in one place for now and then factor out later if needed

**Comment by freeman-lab** [comment]
To summarize an in person discussion (which unfortunately @jni couldn't join!) there was general consensus that the CLI is super cool but should maybe live in a separate repo / package called `napari-cli`. The suggested design is that `napari-cli` depends on `napari` as a requirement, and additionally depends on a few io libraries. It will give us a place to play with the UX around file format handling. But it won't require us adding significant new dependencies to `napari`, or require keeping the `cli` and the library in perfect sync.

Here's a diagram we drew showing this relationship, and how it could be a model for a future standalone `napari-app` similarly consuming the library. The diagram also shows how the io stuff could get modularized out into a `napari-io` library that `napari-cli` and `napari-app` depend on.

Screen Shot 2019-04-11 at 4 52 33 PM

Thoughts @jni ? I know you have some aversion to having too many repos =p

**Comment by jni** [comment]
@freeman-lab yes, it is indeed unfortunate that I wasn't there to nip this conversation at the bud! =P

More seriously, I actually don't mind that structure, I think it's a good idea, as long as we can figure out the packaging so that `pip install napari[all]` brings down napari and napari-cli together. I want it to be super easy to install the napari cli viewer.

Also I might call it `napari-command`.

Side note: I don't want us to start another io package — we should contribute whatever we need to one of:
- skimage io
- imageio
- PIMS
- zarr/n5

**Comment by sofroniewn** [comment]
How about `napari-command-line`?

I agree we can use this repo to figure out exactly what io support we need and then see if we can integrate those changes into existing repos where it makes sense. We might still end-up with some shared loading code between the app and the cli but we can try and keep it at a minimum

**Comment by jni** [comment]
@sofroniewn well, it's a command. The command line takes commands and executes them. =)

**Pull request closed without merging**
