### PR TITLE
Add favicons and configuration for Sphinx docs

### LINKED ISSUE #4897: Icon for napari in web-browser
Can we make it so napari logo appears in my web-browser as a little icon instead of the default gray globe when you're at napari.org - like how the github logo appears when you're on github.com

image

It's just a detail, but i think it's a nice touch :-)

cc @codemonkey800 @melissawm

### PR DESCRIPTION
**Pull request by aganders3**
This adds support for showing a napari logo as a "favicon" (browser tab icon) on the docs page.

Based on discussion in #4897 a logo silhouette was preferred over full-color. This PR adds a few assets and configures them in the header according to what I could find for current favicon best practices:
* An SVG that detects light mode and dark mode and switches the fill color accordingly (for Chome, Firefox, etc.)
    * `<link rel="icon" href="_static/favicon/logo-silhouette-dark-light.svg" type="image/svg+xml">`
* A 192x192 black-on-transparent PNG (for Safari) - setting `sizes="any"` is needed for Chrome to prefer the SVG
    * `<link rel="icon" href="_static/favicon/logo-silhouette-192.png" sizes="any" type="image/png">`
* A 180x180 full-color PNG with no border for the “apple-touch-icon” (icon for iPhone/iPad “Save to Home Screen” and used by others)
    * `<link rel="apple-touch-icon" href="_static/favicon/logo-noborder-180.png" sizes="180x180" type="image/png">`

### macOS Safari and Chrome Dark Mode
Screen Shot 2022-10-05 at 11 27 39 AM

### macOS Safari and Chrome Light Mode
Screen Shot 2022-10-05 at 11 26 18 AM

### iOS “Save to Home Screen”
Simulator Screen Shot - iPhone 14 - 2022-10-03 at 21 09 31

N.B. this also adds a dependency on [sphinx-favicon](https://pypi.org/project/sphinx-favicon/) for the documentation building step.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# References
closes #4897

https://stackoverflow.com/questions/54639192/change-the-favicon-of-the-sphinx-read-the-docs-theme/54665517#54665517
https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

# How has this been tested?
Tested documentation building and serving locally.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- N/A I have added tests that prove my fix is effective or that my feature works
- N/A If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
This looks awesome 🤩 
Hopefully someone clicks the things needed to make CI run so we can download and checkout the built docs.

**Comment by liu-ziyang** [comment]
The assets probably need to be added to git lfs instead.

**Comment by aganders3** [comment]
Thanks @potating-potato - that's what I get for not installing LFS on my new computer 😝

**Comment by liu-ziyang** [comment]
thanks for the quick update! did you happen to miss the darklight one in the migration?
the file changes list correctly shows the other two as "Git LFS file not shown"

**Comment by psobolewskiPhD** [comment]
> thanks for the quick update! did you happen to miss the darklight one in the migration?
> the file changes list correctly shows the other two as "Git LFS file not shown"

Does svg need the LFS treatment? it's just xml right—looks like 14 lines of text.

**Comment by Czaki** [comment]
> Does svg need the LFS treatment? it's just xml right—looks like 14 lines of text.

for me no

**Comment by aganders3** [comment]
Yeah I left the SVG non-lfs on purpose because it now contains style information (which, now that I look at it, could probably be formatted better). You can view as text instead in GitHub as well by clicking the `<>` button to "display the source diff" on the "Files changed" tab.

**Comment by liu-ziyang** [comment]
Ha I didn't see the last logo is an SVG! my bad I saw the first png and assumed all of them are pngs

**Review by psobolewskiPhD — APPROVED** [review]
To me everything looks great! Love it, long overdue!
Code changes make sense based on the docs at https://github.com/tcmetzger/sphinx-favicon
I wish the PR docs comment thingie was working so everyone could more easily see the icons.
Ultimately, I think this one comes down to @jni though, especially given NAP-5 (https://github.com/napari/napari/blob/06a90c7469b20bcd4c741fa84bafee9704b981f0/docs/naps/5-new-logo.md)

**Comment by aganders3** [comment]
I think you can download the docs zip from this page https://github.com/napari/napari/actions/runs/3194057322

I'm not sure why the comment was not posted but I think GitHub Actions was flaky on the day I opened this PR.

**Comment by jni** [comment]
Hi @aganders3 and thank you for this! I love it! I am **so sorry** to make you redo this work but we have been planning a move to a separate repo for the docs (to avoid using LFS which was a huge pain, see #4306, #5216), and we pulled the trigger today, which means that this PR needs to be made against https://github.com/napari/docs now. On the plus side — no LFS! 🙏 

If you have any questions on this please ask on Zulip! Sorry again and I hope that contributing to docs is easier and easier going forward! 🙏

**Comment by aganders3** [comment]
No worries! It should be pretty easy to move over and I understand the motivations for the change.

**Pull request closed without merging**
