### PR TITLE
Enable patch coverage reporting

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR enables patch coverage. It was disabled in #806 without any discussion around this. 
Patch coverage is information on how newly added lines are tested. As napari develops dynamically most often multiple commits are merged during the development and review of a given PR. Then it is hard to read if PR is properly tested and needs an additional manual inspection. 

Maybe a lower target needs to be specified manually if we do not want to block some new contributors with a complex test, but on, the other hand core developers may provide such tests during the review. 

## Type of change

- [x] improve review process by more information from coverage status

# References

https://docs.codecov.com/docs/commit-status#patch-status

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
> It was disabled in #806 without any discussion around this.

The discussion was this (and all of the following discussion in that PR :joy:)

> I certainly don't want to encourage PRs lacking tests, but the status starts to be useless if you know there are relatively "nitpicky" things that might be causing it to show a failed status. It'd be nice if the fail/success status were a direct predictor of whether the PR is ready (or close to ready) to merge or not.

codecov is kinda known to be a bit flaky, and we were definitely getting failures left and right, and that was the solution at the time.  I'm ok with trying this again, but be ready to soften it if our test go ❌ all the time again.

Also, can we set an absolute patch target?  I've never been a fan of threshold for patch cov

**Comment by Czaki** [comment]
> Also, can we set an absolute patch target? I've never been a fan of threshold for patch cov

Yes. We could. 

For me general problem is that the intensive napari development process plus codecov means that I need to codecove the page to see how real the lines from PR are covered. 

Because if patch coverage is low it means that new code is not tested and someone could break it in the future without notifications.

**Comment by tlambert03** [comment]
> Because if patch coverage is low it means that new code is not tested and someone could break it in the future without notifications.

thanks @Czaki, we do understand the purpose of tests, and the implications of untested code :joy: ... the more interesting question when it comes to CI is how best do we strike the balance between code stability and developer burden.  As an example, @DragaDoncila spent about 3 hours one day at the recent hackathon trying to get at a _few_ lines of Qt code, which proved extremely difficult to test (and was almost certainly "fine").  So please keep in mind, this topic isn't trivial, and it isn't new to this PR: we've been trying to tune our degree of testing demands over quite a bit of time.

**Comment by Czaki** [comment]
> So please keep in mind, this topic isn't trivial, and it isn't new to this PR:

But it will give me information that I being a reviewer, could suggest/draft/implement a test. I set the target to 0% to only have information about patch coverage without failure.

**Review by tlambert03 — APPROVED** [review]
> I set the target to 0% to only have information about patch coverage without failure.

this is a good strategy here.  thanks!

**Comment by andy-sweet** [comment]
Agreed that setting the target to 0% seems like a good strategy and that this is useful information to have when reviewing - actually I think it's far more useful than the non-patch coverage stats. So I'm merging this within the next 24 hours if no one else does.

**Pull request merged**
