### PR TITLE
Add binder to repository and badge on README

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [x] Task

### Test it with 

[Binder](https://mybinder.org/v2/gh/goanpeca/napari/enh/binder?urlpath=%2Fdesktop)

Which looks like:

napari

### CODE REVIEW

**Comment by goanpeca** [comment]
This adds binder configuration and badge so napari can be tested right away. On a subsequent PR I will add an action to add a link on PRs so it is possible to test a PR using binder, for users not installing napari from source, etc.

**Review by tlambert03 — APPROVED** [review]
woah! 🤯 

on my first try, the server choked before starting, so I couldn't run it ... but I assume that's unrelated to this setup here.  Very cool @goanpeca

**Comment by tlambert03** [comment]
on my second try, it worked beautifully!  😄

**Review by sofroniewn — APPROVED** [review]
I'm pro binder - let's get this in!! cc @freeman-lab ;-) 🚀

**Comment by sofroniewn** [comment]
Worked perfect for me!

Screen Shot 2021-08-25 at 2 31 31 PM

**Comment by kevinyamauchi** [comment]
This is great! Thanks, @goanpeca !

**Pull request merged**
