### PR TITLE
[WIP] Delay importing RichJupyterClient until use

### PR DESCRIPTION
**Pull request by jni**
Workaround for https://github.com/jupyter/qtconsole/issues/388

### CODE REVIEW

**Comment by jni** [comment]
Not sure this is the prettiest way to do this, but it works! 😬

**Comment by sofroniewn** [comment]
hmm yeah - i'm so not sure about this I think I'd rather move the `shell = get_ipython` into `QtViewer` and then only instantiate QtConsole if we need to and send the shell as one of its input parameters. Thoughts?

**Comment by jni** [comment]
Incidentally, a whole bunch of stuff is broken in this PR, but the tests pass, so when I get around to fixing this, I'll add a bunch of tests for this stuff. =)

**Comment by sofroniewn** [comment]
This has now been superseded by #1055 which makes loading the whole console lazy

**Pull request closed without merging**
