### PR TITLE
add I2K workshop

### PR DESCRIPTION
**Pull request by chili-chiu**
# Description

Add I2K workshop material to the doc. @haesleinhuepf is it ok to link it to your Github repo? It has a lot of great resources.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by alisterburt — APPROVED** [review]
Looks good to me @chili-chiu - thanks for adding!

**Comment by haesleinhuepf** [comment]
Absolutely, yes @alisterburt . If there was a central place for workshop repos, we can also move it there... As you prefer!

**Comment by alisterburt** [comment]
@chili-chiu what do you think about creating a separate github account called `napari-workshops` where any workshop repos could eventually be archived -> this would allow the community to run their workshop independently but centralise things nicely as a resource for future workshop runners!

I think this is better than placing all content in one repo to avoid huge repos :)

cc @kevinyamauchi 

thanks @haesleinhuepf !

**Review by kevinyamauchi — APPROVED** [review]
LGTM! Thanks, @chili-chiu !

**Comment by kevinyamauchi** [comment]
> @chili-chiu what do you think about creating a separate github account called napari-workshops where any workshop repos could eventually be archived -> this would allow the community to run their workshop independently but centralise things nicely as a resource for future workshop runners!

I think it would be nice if we had a repo for consolidating workshop materials. I'm not sure it needs to be a separate org or account. As @alisterburt  said, I think the overall goal of the repo/org would be to create a centralized place for people to contribute and find workshops, so I am happy to do whatever workshop creators feel works best for their workflow. I think this is great discussion and I can start and issue so we can continue it there!

Edit: here's the issue: #4531

**Pull request merged**
