### PR TITLE
Explicit convert color to string when compile resources

### PR DESCRIPTION
**Pull request by Czaki**
# Description

One of the big problems when debugging #4995 for me was that `get_colorized_svg` signature expects color to be a string, and we pass `pydantic.color.Color` to it. So I lost time digging into what could go wrong and why we passed unexpected arguments. 

As follow up we could simply convert color to string before this phase (what is done in this PR) or update the signature of `get_colorized_svg` to assume that we could accept `Color` class also to convert it into a string later. 

I personally prefer the conversion way, but if you think of another way, the signature update is also ok. 

## Type of change

- [x] Refactor

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by andy-sweet — APPROVED** [review]
Looks good to me.

Not that calling `str` on a Pydantic `Color` will return the color name (e.g. cornflowerblue) if its value corresponds to one the known named colors, and otherwise it will return the the hex string that represents the color value.

Based on my understanding [Pydantic supports color names (e.g. cornflowerblue) based on the CSS3 spec](https://pydantic-docs.helpmanual.io/usage/types/#color-type) and [Qt supports color names based on the SVG 1.0 spec](https://doc.qt.io/qt-5/qcolor.html#details), and [these are identical](https://www.w3.org/TR/css-color-3/#svg-color).

If you wanted to bypass that explanation to anyone else, you could use `Color.as_hex` which will always return the hex string (or maybe `Color.as_rgb` which returns the rgb(a) string). But I don't feel strongly here. I'd also be fine with changing type annotations from `str` to `Color`.

**Comment by Czaki** [comment]
This pr reproduce current behaviour when we do implicit conversion by passing color as `format` argument.

**Comment by andy-sweet** [comment]
> This pr reproduce current behaviour when we do implicit conversion by passing color as `format` argument.

Understood. Just pointing out that the behavior of string conversion for Pydantic's `Color` is a little complex, but also entirely reasonable.

**Comment by alisterburt** [comment]
@andy-sweet I see you have approved - would you suggest that we switch to always using hex codes or keep the current behaviour in this PR?

Marked as 'merge for 0.4.17'!

**Review by Carreau — APPROVED** [review]
I don't have any particular preference on use to_hex or str(color).

My thought is that any weird case heisenbug due to str() might be harder to debug and https://en.wikipedia.org/wiki/Robustness_principle
says "be conservative in what you send, be liberal in what you accept", so maybe a small pref on to_hex, but I think the change we hit a corner case if really small.

**Comment by brisvag** [comment]
I agree, there's no need to be magic where users are not involved; I vote for `hex`!

**Review by brisvag — APPROVED** [review]

**Comment by brisvag** [comment]
Multi-approved and simple change. Merging!

**Pull request merged**
