### PR TITLE
Use ruff to format strings to single quotes.

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Based on a discussion from #6386 I updated the ruff configuration to enable `Q000` https://docs.astral.sh/ruff/rules/#flake8-quotes-q rule and configured it to use a single quotes string. 

We have many double quotes string, but less than single quotes. 

This PR does not change the quotation of docstrings (`"""`) and multiline strings (`"""`) as they are already enforced by ruff configuration and could be easy changed. 

to se configuration changes please use: https://github.com/napari/napari/pull/6407/commits/a422ad7515c04c386eb97eea364d60444ba89af5

cc @jni @brisvag

### CODE REVIEW

**Review by jni — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
The single quotes look weird to me, but not needing to use shift is a plus?
Eitherway, being systematic about is good. I assume ruff precommit will autoformat when making new PRs?

How will the process look for open PR? Will a merge of main into an open PR trigger pre-commit to fix? or scream about conflicts? or some other option?

**Comment by Czaki** [comment]
> I assume ruff precommit will autoformat when making new PRs?

yes



> How will the process look for open PR? Will a merge of main into an open PR trigger pre-commit to fix? or scream about conflicts? or some other option?

There may be a scream, and then there will be a need to update pre-commit config to allow pre-commit to fix the problem.

**Comment by psobolewskiPhD** [comment]
Okies, I think we just need to have a clear set of instructions for contributors once this is merged that we can copy-paste into open PRs if it ends up with something screaming or needing to do something extra.

**Comment by Czaki** [comment]
If contributor has `curl` the command could be:

```bash
curl https://github.com/napari/napari/commit/a422ad7515c04c386eb97eea364d60444ba89af5.patch | git apply -
```

Is it ok?

**Comment by jni** [comment]
@Czaki @psobolewskiPhD why wouldn't merging main work?

**Comment by jni** [comment]
Oh sorry I just saw what the commit was pointing to 😅

**Comment by jni** [comment]
@Czaki do you want me to merge this or should I wait or for #6652?

**Comment by Czaki** [comment]
I think that we should wait in #6652

**Review by brisvag — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
Huh, you merged main into this and pre-commit from this branch fired and fixed the quotes?
So I guess if one merged this, then merge main into other PR would make precommit do the work?

**Comment by Czaki** [comment]
if there will be no conflict then yes

**Comment by jni** [comment]
I'm convinced. Gonna merge! 🚀

**Pull request merged**
