### PR TITLE
Change opacity slider to float slider

### LINKED ISSUE #3014: Opacity slider label should be between 0 and 1
## 🐛 Bug

Opacity slider label should be between 0 and 1 not 0 and 100. This will remove need for normalization on slider https://github.com/napari/napari/blob/aade148d8e5cb339bb2981ab4d1081ae5d2747e0/napari/_qt/layer_controls/qt_layer_controls_base.py#L79

image

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
fixes #3014

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Code changes looks good - we've got test fails at `test_mgui_forward_refs` but I think that's probably unrelated to this PR. Was there a new magicgui release @tlambert03?

**Comment by tlambert03** [comment]
> Was there a new magicgui release

no, but working on one today.  will look into it

**Comment by tlambert03** [comment]
>  we've got test fails at test_mgui_forward_refs but I think that's probably unrelated to this PR

it _was_ related!  and the test worked! :)  i don't know how it happened, but somehow this PR deleted a couple strings from `napari.__init__._proto_all_` and it caught it :)

**Comment by sofroniewn** [comment]
huh, crazy! well that's good at least :-)

**Pull request merged**
