### PR TITLE
note on readme about stability added

### PR DESCRIPTION
**Pull request by AhmetCanSolak**
# What does this PR do? Why are doing this? References?
To remove the ambiguity about status of the repository, i added a single line to `README.md` file.

## Type of change
- [X] This change requires a documentation update

## How Has This Been Tested?
- [X] Tested with the most popular markdown render plugin on atom environment.

## Final Checklist:
- [X] My PR is the possible minimum work for the desired functionality
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by royerloic — APPROVED** [review]
We just want to lower expectations here...
the code is still at a prototype stage.

**Review by kevinyamauchi — APPROVED** [review]
Thanks, @AhmetCanSolak ! I agree that it's important to set appropriate expectations.

**Comment by AhmetCanSolak** [comment]
@kne42 is the same problem with CI valid for other PRs too? do we have a patch?

**Comment by kne42** [comment]
This appears to be an issue with Anaconda’s distribution of Python 3.7.

Other reports:
- [StackOverflow: “‘No SSL support included in this python’ Anaconda-python3-smtplib”](https://stackoverflow.com/questions/53541815/no-ssl-support-included-in-this-python-anaconda-python3-smtplib) (4 hours ago)

You can just disable the Windows Py3.7 requirement for now.

**Comment by kne42** [comment]
This PR overlaps with #72. Do you think that there is any way we can make it more clear in there that this project is under heavy development and unstable?

**Comment by AhmetCanSolak** [comment]
you can take the line there too. We just want to publish that single ASAP to readme. No matter how it is merged.

**Comment by kne42** [comment]
@AhmetCanSolak I disabled the buggy test. Feel free to merge when you are ready.

**Pull request merged**
