### PR TITLE
Add placeholder for empty contributable submenus

### PR DESCRIPTION
**Pull request by DragaDoncila**
# References and relevant issues
N/A

# Description
Once NAP-6 launches, some of our submenus might be empty, if the user hasn't installed any plugins that populate a submenu, and we don't have any built-in actions in it either.

On Mac (at least), an empty submenu doesn't fan out into anything, and this can be confusing for the user. Additionally, if we just disable the submenu entirely, on Mac (at least), the submenu itself looks the same, but all items in it are disabled. This is useless for us since we're talking about disabling empty submenus. 

Therefore, in consultation with @jni, this PR adds empty placeholder actions for contributable menus, which are always disabled, and hidden if the menu becomes populated through new action registration. This PR only enables the feature for our own contributable menus, and doesn't handle if a plugin dev contributes an empty menu.

https://github.com/napari/napari/assets/17995243/ec95264f-7e57-4e97-8a1c-024c47687355

# Implementation Stuff

I had significant difficulty finding the dummy `QAction`, once registered, to simply make it invisible, and couldn't think of a convenient way to use the `app-model` `when` clause for this, since the context would be dependent on the state of the menus themselves, and I couldn't figure out what object this context would live on - I thought about the `MenusRegistry` itself, but it felt like it would need a very complex context key, or one context key for each contributable menu, to be able to easily check if it's empty. 

Therefore, this PR implements the feature by fully deregistering the dummy action when menus need updating, and re-registering it only with the needed menus. The nice thing is we only need to use one action. The not nice thing is the deregister/re-register (obviously).

# Trying stuff out

For convenience, I've edited the `qt_main_window` code to add a new, empty `View` submenu and make it contributable. We should obvs remove that when we merge. If you just launch `napari`, you'll see the `Empty` item in the submenu.

Then, if you want to see it disappear, you can run the following code in the console.

```python
from napari._app_model import get_app
from app_model.types import Action

my_action = Action(
    id='napari.new_action',
    title='On The Fly',
    callback=lambda: napari.utils.notifications.show_info("WOOOOOW"),
    menus=[{'id': 'napari/view/contributable_menu'}]
    )

app = get_app()
app.register_action(my_action)
```

# TODO:

- [ ] testing
- [ ] maybe only update the changed menu? would need independent actions
- [ ] remove copious print statements that I've added for Juan to look at
- [ ] more docstrings

### CODE REVIEW

**Comment by lucyleeow** [comment]
Firstly, we should really deal with this: https://github.com/napari/napari/issues/6054

If you did want to go down the context route, could you add it on to `NapariApplication`? We originally wanted to put contexts there, as ideally e.g., layerlist should not know about the app, only the app should know about layerlist.

> On Mac (at least), an empty submenu doesn't fan out into anything, and this can be confusing for the user. Additionally, if we just disable the submenu entirely, on Mac (at least), the submenu itself looks the same, but all items in it are disabled. This is useless for us since we're talking about disabling empty submenus.

Is it possible to use the `when` on the submenu item and just hide the submenu completely when it is empty?

**Comment by DragaDoncila** [comment]
> Firstly, we should really deal with the double app's: https://github.com/napari/napari/issues/6054

Agreed there @lucyleeow. Looks like there's some consensus on that issue?

> If you did want to go down the context route, could you add it on to NapariApplication? We originally wanted to put contexts there, as ideally e.g., layerlist should not know about the app, only the app should know about layerlist.

You could, yes, I just don't think it's going to be a clean thing to implement, because it's essentially a self-referential context on the menu about itself.

> Is it possible to use the when on the submenu item and just hide the submenu completely when it is empty?

Assuming you can get the context keys working, and that's a big if, you could do this, yes. We are less excited about that option because we don't want users' menubar to keep changing from environment to environment. We can also co-opt the empty menu item to for example, suggest installing a plugin or link out to a plugin search or something.

**Comment by lucyleeow** [comment]
> it's essentially a self-referential context on the menu about itself.

But aren't all context self-referential? e.g., the layer list context refers to layer list things?

**Comment by DragaDoncila** [comment]
> But aren't all contexts self-referential? e.g., the layer list context refers to layer list things?

yeah I guess it's more of a meta-context? I mean if we started to spec it out what it would it look like:

- I guess it's a `submenu_context`, perhaps living on the app, and it has a bunch of `SubmenuContextKeys`?
- some examples of those keys would be `is_submenu_empty` - idk how you'd know which submenu we meant, here, so maybe it would have to be like, `is_segment_empty`, `is_filter_empty` etc...?
- the context key getters would be like, functions that count the number of actions within that submenu I guess?
- they would be connected to update on, I guess, `menus_changed` [events](https://app-model.readthedocs.io/en/latest/getting_started/#registry-events)?

Overall I do think the empty item is more user-friendly but just for the sake of teasing out this potential context, I wanted to have this here

**Comment by lucyleeow** [comment]
> Agreed there @lucyleeow. Looks like there's some consensus on that issue?

Yes definitely consensus, just no volunteer to do this *fun* task :eyes: :sweat_smile:

**Comment by jni** [comment]
Hmmm @DragaDoncila this failure unfortunately looks real suspicious and really real. 😂 

https://github.com/napari/napari/actions/runs/9680087697/job/26707476820?pr=6950#step:13:1009

```pytb
  self = <MagicMock name='get_app' id='140180688309600'>, name = 'called'
  value = True
  
      def __setattr__(self, name, value):
          if name in _allowed_names:
              # property setters go through here
  >           return object.__setattr__(self, name, value)
  E           RecursionError: maximum recursion depth exceeded
  
  /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/unittest/mock.py:733: RecursionError
  
  During handling of the above exception, another exception occurred:
  
  >   ???
  
  src/psygnal/_signal.py:1196: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  src/psygnal/_signal.py:1225: in _run_emit_loop_immediate
      ???
  src/psygnal/_weak_callback.py:453: in cb
      ???
  napari/_qt/qt_main_window.py:778: in _toggle_empty_menu_dummy_actions
      am_app.menus.menus_changed.emit(_CONTRIBUTABLES)
  src/psygnal/_signal.py:1176: in emit
      ???
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  >   ???
  E   RecursionError: RecursionError when emitting signal 'menus_changed' with args ({'napari/layers/context'},)
```

So I think we will release 0.5.0a0 without this and just note in the announcement that the empty menus will be fixed before the actual release...

**Comment by DragaDoncila** [comment]
> Hmmm @DragaDoncila this failure unfortunately looks real suspicious and really real. 😂

mmm yeah I hated this approach from the get-go tbh. I think we should look more at whether we can use a `when` on the item instead, so that it always stays registered, but hides and shows as required. This would be the correct implementation anyway

**Comment by jni** [comment]
> mmm yeah I hated this approach from the get-go tbh.

Well, it seems like the canonical approach with event-storms tbh. But the condition is probably insufficient in some way — maybe in the right (stochastic) order of event firings, it results in oscillations (now the menu is empty now the menu is not empty etc). Or maybe we're just not catching one of the equivalence cases...

**Comment by DragaDoncila** [comment]
Closing in favour of #7038.

**Pull request closed without merging**
