### PR TITLE
Fix repeating close dialog on macOS and qt 5.12

### LINKED ISSUE #5335: double command-q no longer quitting
## 🐛 Bug

if you press cmd-q, and then press it again (as the dialog instructs), it doesn't quit... it just opens more dialogs

https://user-images.githubusercontent.com/1609449/201672279-161cef46-63c7-4e6f-879f-82fd2a930d7f.mov

(napari 0.4.17 with `conda create -n env napari`)

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Try to solve (from @tlambert03)

> if you press cmd-q, and then press it again (as the dialog instructs), it doesn't quit... it just opens more dialogs

https://user-images.githubusercontent.com/1609449/201672279-161cef46-63c7-4e6f-879f-82fd2a930d7f.mov

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

closes #5335

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
I can't say I `get` the code, but it does fix the issue in my macOS 12.6 Rosetta-emulated x86 env with pyqt 5.12.3.
👍 @Czaki

**Comment by Czaki** [comment]
I add comments with explanations.

**Comment by psobolewskiPhD** [comment]
OK, I think I see it now. I was writting a question and explained it to myself.
My hangup was that `quit_app` is actually a bool so either False or True so it works with the dict you defined at the beginning in L118.
I'd still rather someone else review this just to be safe,

**Comment by Czaki** [comment]
I could change bool to enum to increase readability if needed.

**Comment by psobolewskiPhD** [comment]
No no, it's me being an imbecile and not comprehending: `self._is_close_dialog[quit_app]`

**Comment by tlambert03** [comment]
nice job @Czaki  :)  (can confirm this fixes it on 5.12 for me)

**Review by tlambert03 — APPROVED** [review]

**Comment by Czaki** [comment]
Would you vote for 0.4.18 bugfix release or could it wait until 0.5.0?

**Comment by tlambert03** [comment]
don't have an opinion

**Comment by Czaki** [comment]
Ok. Will merge after 24h.

**Pull request merged**
