### PR TITLE
Fix zoom for non square image

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Fix zoom for non-square image

Before PR:
before_change

After PR:
after_change

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]

**Comment by sofroniewn** [comment]
Fix looks good, thanks!! Looks like one of our screenshot tests is failing because we hard coded something that assumed the zoom would be in a certain way. Do you think you can fix @Czaki?

**Comment by Czaki** [comment]
Locally pass.

**Comment by Czaki** [comment]
fails looks unrelated. 
MacOS has a problem with the notification manager (looks like missed signall), 
Windows looks like a memory leak in tests reason.

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Pull request merged**
