### PR TITLE
Fix calendar ID

### LINKED ISSUE #4933: DOC Calendar in meeting schedule page empty
## 📚 Documentation

The calendar on the 'meeting schedule' page is empty. I think https://github.com/napari/napari/pull/4914/ was meant to fix but the dev page still shows an empty calendar: https://napari.org/dev/community/meeting_schedule.html

Related - calendar also seems to appear jumbled in safari: https://github.com/napari/napari.github.io/issues/371

### PR DESCRIPTION
**Pull request by codemonkey800**
# Description
Should hopefully fix #4933

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by codemonkey800** [comment]
I'm still unable to build the napari docs locally on my M1 😢 it would be nice to have automatic previews, but in the meantime it would be great if someone (who can build the docs locally) help with testing

**Review by nclack — APPROVED** [review]
lgtm

**Comment by lucyleeow** [comment]
The CI builds the docs and you can download by clicking on: Build Docs / Build & Upload Artifact > Summary (top left) > scroll down and download the docs files.

I did this and the meeting schedule page was still empty. (Note you need to delete `<script src="../_static/redirects.js"></script>` from the html page to view it on a browser)

**Review by melissawm — APPROVED** [review]
This works for me locally, thanks @codemonkey800 !

**Comment by codemonkey800** [comment]
> This works for me locally, thanks @codemonkey800 !

oh wait it does? 🤔 I'm hearing conflicting things from you and @lucyleeow lol. are you able to see the calendar events on your end @melissawm?

**Comment by lucyleeow** [comment]
If it works for @melissawm locally I would just trust that. No idea why it did not work for the CI built docs...maybe it was just me (double checked and the calendar is definitely empty in the CI built docs)? Does the page in the CI built docs work for you @codemonkey800 ?

**Comment by melissawm** [comment]
Oh scratch that - I looked too quickly and didn't realize I was seeing the current week as highlighted, and not actual events. So the calendar does show up but events are not actually showing up. Sorry for the confusion!

**Comment by lucyleeow** [comment]
It's probably worth merging this to correct the calendar ID but keep https://github.com/napari/napari/issues/4933 open as it hasn't fixed the issue. What do others think?

**Comment by Carreau** [comment]
Ok, let's try and leave #4933 open.

**Pull request merged**
