### PR TITLE
Add emacs temporary & local files to .gitignore

### PR DESCRIPTION
**Pull request by kephale**
# Description

The current .gitignore does not support emacs temporary and local files.

## Type of change
- [X] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

N/A

# How has this been tested?

Yes, it works. This is just a change in .gitignore

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas

### Not applicable

- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by Czaki — APPROVED** [review]

**Review by jni — APPROVED** [review]

**Comment by alisterburt** [comment]
Thanks @kephale - merging because two approvals and I can't see any reason this would be contentious

**Comment by kephale** [comment]
Thank you, @alisterburt !

**Comment by Carreau** [comment]
For me on IPython I refuse those as those extension should be in your [global gitignore](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c), not on a per project.

Otherwise I would submit my vim swap and undo file everywhere. 
You can also likely [change the folder emacs save those files](https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files).

**Comment by kephale** [comment]
The global gitignore is a great suggestion, but I definitely would not change the locations where my temp files are saved, too many potential conflicts.

**Comment by Carreau** [comment]
> The global gitignore is a great suggestion, but I definitely would not change the locations where my temp files are saved, too many potential conflicts.

Usually when you change those location those can be mirror the full path. 
For example all my swap files are in  `~/eraseme/vimswapfiles/` and named with their full path, e.g.: `%Users%bussonniermatthias%dev%ipython%IPython%terminal%shortcuts.py.swp`

This also has the advantage that all git-unaware tools (grep, find), don't search those files.

**Comment by kephale** [comment]
Hmm, thank you. I will investigate :)

**Comment by Carreau** [comment]
I hope that help you, at least it makes my life much easier as I never have to update projects' .gitignores :-)

**Pull request merged**
