### PR TITLE
Fix Labels.fill when Labels.data is an xarray.DataArray

### LINKED ISSUE #2374: Fill does not work for xarray data for labels layer
## 🐛 Bug
Using `fill` is broken for the labels layer when backed by an xarray.

It doesn't fill and throws this error:
```
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 443, in mousePressEvent
    self._vispy_mouse_press(
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/vispy/app/base.py", line 181, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/napari/_qt/qt_viewer.py", line 682, in on_mouse_press
    mouse_press_callbacks(layer, event)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/napari/utils/interactions.py", line 101, in mouse_press_callbacks
    next(gen)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/napari/layers/labels/_labels_mouse_bindings.py", line 35, in draw
    layer.fill(layer.coordinates, new_label)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/napari/layers/labels/labels.py", line 776, in fill
    matches = labels == old_label
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/xarray/core/dataarray.py", line 2991, in func
    f(self.variable, other_variable)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/xarray/core/nputils.py", line 73, in array_eq
    return _ensure_bool_is_ndarray(self == other, self, other)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/xarray/core/variable.py", line 2305, in func
    result = Variable(dims, new_data, attrs=attrs)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/xarray/core/variable.py", line 342, in __init__
    self._dims = self._parse_dimensions(dims)
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/xarray/core/variable.py", line 603, in _parse_dimensions
    raise ValueError(
ValueError: dimensions () must have the same length as the number of data dimensions, ndim=2
```

## To Reproduce
```python
from skimage import data
from scipy import ndimage as ndi
import napari
import xarray as xr

with napari.gui_qt():
    blobs = xr.DataArray(data.binary_blobs(length=128, volume_fraction=0.1, n_dim=3), dims=('T','Y','X')).astype(float)
    viewer = napari.view_image(blobs.astype(float), name='blobs')
    labels = xr.DataArray(ndi.label(blobs)[0])
    label_layer = viewer.add_labels(labels)
    label_layer.mode = 'fill'
```
try to fill one of the blobs.

## Expected behavior
Blob is paintbucket filled.

## Environment
```
napari: 0.4.7.dev14+gc473058
Platform: Linux-5.8.0-7630-generic-x86_64-with-glibc2.31
System: Pop!_OS 20.04 LTS
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:34:10) [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- svg: 0.1.4
```

## Additional context
Partial xarray support for the labels layer added in https://github.com/napari/napari/pull/2191 which fixed the behavior when in `paint` mode.

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description

This fixes `Labels.fill` when `Labels.data` is an `xarray.DataArray`. The problem was caused by xarray's read indexing rules, which perform orthogonal indexing (like `np.ix_`) when given a tuple of array-likes that have no dimension labels. This issue was already handled by `Labels.paint`, so we use the same solution for `Labels.fill` by refactoring that small amount of logic into a helper function.

The original error was caused by a memory allocation issue, but writing a failing test with the same underlying cause, but small data was a little tricky. I considered testing the public API of `Labels.undo`, but that actually worked in my example (maybe because the write indexing rules of `DataArray` are not the same as the read indexing ones?), so I tested some internal state instead. I think that's fine in this case, especially as I wrote an explanatory comment.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
Closes #2374

# How has this been tested?
- [ ] new test to cover fill/undo with xarray passes
- [ ] all existing tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — COMMENTED** [review]
fix works great, thanks!

If possible, it'd be preferable not to import xarray greedily just to check whether it's a `DataArray`.  Xarray is slow to import... this was [noted once before](https://github.com/napari/napari/issues/758#issuecomment-786885653), and workarounds were used elsewhere: https://github.com/napari/napari/pull/2325.

anything along the lines of ?
```py
def is_xarray(obj):
    for i in type(obj).mro():
        if i.__module__.startswith('xarray') and i.__name__ == 'DataArray':
            return True
    return False
```

or the logic [here](https://github.com/napari/napari/blob/80a2e0edc8057dca7d39a31af91d93dfe3999500/napari/utils/misc.py#L493-L506) could be generalized?

**Review by tlambert03 — APPROVED** [review]
love the changes.  thanks!

**Comment by andy-sweet** [comment]
> or the logic [here](https://github.com/napari/napari/blob/80a2e0edc8057dca7d39a31af91d93dfe3999500/napari/utils/misc.py#L493-L506) could be generalized?

I did some refactoring and defined a couple of misc helper functions, neither of which are publicly exposed because I'm a private person - please take another look and feel free to suggest any changes. Note that if the array is an xarray, then we still import. Maybe we could skip the `try` block, but I left it for now.

The logic is getting a bit fancy/complex, but one qualitative benefit of this latest change is that the lag when first drawing on a labels layer is now gone (when the array is not an xarray), which must have been due to the slow import and always irked me when demoing stuff.

**Comment by tlambert03** [comment]
> Note that if the array is an xarray, then we still import.

that part i'm not worried about.  If it's an xarray, then presumably xarray will already be in sys.modules, and import will be fast.  It's just the case where someone _hasn't_ used xarray (but it's present in the environment) that I'd like to avoid importing

**Review by sofroniewn — APPROVED** [review]
Wow I love this! And I love that speed up too - so great not to have that xarray import inside the try - it always irked me a little too - nice work @andy-sweet and @tlambert03. I will get this in tomorrow unless hearing otherwise. Test fail is unrelated

**Comment by jni** [comment]
Late to this party but I love it also!

**Pull request merged**
