### PR TITLE
Move help actions under `_qt` and remove lambdas

### LINKED ISSUE #6744: Remove lambdas in help menu actions `_help_actions.py`
We should remove lambdas used in help menu actions in `napari/_app_model/actions/_help_actions.py`.

The callbacks are all calls to `webbrowser.open`. This is a case where having `kwargs` field in actions would be useful. (ref: https://github.com/pyapp-kit/app-model/issues/52)

### PR DESCRIPTION
**Pull request by lucyleeow**
# References and relevant issues
Closes https://github.com/napari/napari/issues/6744
Related: https://github.com/napari/napari/pull/6848#issuecomment-2089374696

# Description
Move all help actions to `_qt/` and remove lambdas and replace with partials.

### CODE REVIEW

**Comment by lucyleeow** [comment]
cc @Czaki @DragaDoncila :pray:

**Review by DragaDoncila — APPROVED** [review]
Works for me! Thanks @lucyleeow ❤️

**Comment by jni** [comment]
I apologise if this is me being a goldfish 🐠, but why are they moved to Qt? I see nothing Qt related in them, and presumably if we have a different front-end one day, these actions can be used unchanged?

**Comment by jni** [comment]
Nope, not me being a goldfish, just me not clicking through, or rather clicking "open in new tab" then not looking. 🤦 

> After discussing with @DragaDoncila, we think all the menu bar actions should be defined in one file in _qt - currently the only non-qt actions are some help menu actions that open a URL. Although these actions technically do not require QT as they are defined for the purpose of living in a menu, it should be considered a 'GUI' action.

**Comment by lucyleeow** [comment]
The new layer menu actions have opened up some questions too. I just about to open a PR to start a discussion about this kind of stuff. Please share your views there @jni !!

**Review by Czaki — APPROVED** [review]

**Comment by DragaDoncila** [comment]
>  I see nothing Qt related in them, and presumably if we have a different front-end one day, these actions can be used unchanged?

Yeah they're not qt related but they **are** only useful with a GUI. Since we don't have a "non qt but defs gui" folder, we've decided to move these here so that they're explicitly considered if a time comes when we want to make them available via a different front end.

I'm not in love with this either, but as Lucy says we've run into this question a few times so I think best is to merge this, and think about the separation of headless-gui-qt a bit more carefully in a broader sense.

**Comment by DragaDoncila** [comment]
@jni I will add ready-to-merge here, but please feel free to request changes if you want more discussion

**Pull request merged**
