### PR TITLE
skeleton for building container images on github CI

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**
# Description
Hi,

Quick and dirty github action to build docker and singularity container,  based on you dockerfile.
Feel free to adapt/teardown/re-use!

Cheers

Tru

### CODE REVIEW

**Comment by liu-ziyang** [comment]
Hi there, thank you for submission! we have a docker hub organization napari, and we can update the workflow to use that organization after I give it a try

**Comment by liu-ziyang** [comment]
May I ask what is the motivation using singularity? I am not quite familiar with it. From the look of it I don't immediately see how we would benefit

**Comment by Carreau** [comment]
> May I ask what is the motivation using singularity ?

Most of the use case I've seen is HPC that don't/can't use docker. it allows a couple of things on HPC I believe that docker can't. Like with docker you must have everything in one image wile singularity you could say I want to run something in Napari+MPI. It's also I believe friendlier with distributed HPC filesystems.

Another way to see that is that Docker is more to run anything anywhere (heterogenous, cloud), while singularity might be better for one thing everywhere (homogeneous HPC).

**Comment by tlambert03** [comment]
> Most of the use case I've seen is HPC that don't/can't use docker. 

yep!  our compute cluster here makes it trivial to use singularity... haven't yet figured out whether it's even possible to use docker

**Comment by truatpasteurdotfr** [comment]
Docker is fine on a developper workstation (as it is mostly single user, and the dev is also a privileged user). Podman, singularity allows a regular user from a centralised system (HPC, department cluster, ...) to leverage the container either from dockerhub (but reguires a user conversion before being used - `singularity build image.sif docker://my/image/`). Providing the pre-converted singularity image allow a direct use, making it more convenient for the end user. Just my 2 cents.

**Comment by tlambert03** [comment]
Sorry this has sat so long @truatpasteurdotfr, we'd like to get this in.  Can you do two things for me?  

1) merge or rebase `main` to resolve the conflicts
2) move the "containers" section that you added to the README lower down, after the `### from source` section.  We'd like it in there, but perhaps not as the first install method. :)

i tried to update for you but wasn't able to push to your branch.  thanks!

**Comment by truatpasteurdotfr** [comment]
yes, sure I will fetch and try to merge :p and submit another PR.

**Pull request closed without merging**
