### PR TITLE
Remove leading b from briefcase macOS support build numbers

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description

This fixes the recent failing actions related to the briefcase-based bundled app.

It seems like the briefcase URL forwarder to AWS changed recently (though I'm not sure where that is configured), which meant that an extra `b` was being added to the S3 URL.

The fix is to remove the `b` prefix from the build numbers in our utility. This may be fragile, but should work for now. If the URL forwarder changes again, we can update accordingly.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

Alternative to #5144 

# How has this been tested?
- [x] I tested the URL forwarding with each of the version/revision combos.
- [ ] I ran `python bundle.py` locally on my mac (Intel, 12.5) with success, then ran the associated bundled app successfully.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
Nice!

**Comment by andy-sweet** [comment]
I tested the macOS artifact, but it failed to install my Intel MacBook Pro (macOS 12.5) with [an error](https://gist.github.com/andy-sweet/e9247b8e26eac1447eb2c0a78bdea2a0) that is related to a combination of [pydantic and the Python version from `sys.version_info`](https://github.com/pydantic/pydantic/blob/1a5b56e1b2020fd74800064d038becf614d64a61/pydantic/typing.py#L394).

Not sure if this is just related to my OS/environment. I have two system-wide installs of `python`

- Apple provided? `/usr/bin/python3`, v3.8.9 
- Homebrew. `/usr/local/bin/python3`, v3.9.10

Would be great if someone else could try.

**Comment by psobolewskiPhD** [comment]
I downloaded the macOS bundle from here:https://github.com/napari/napari/actions/runs/3152777529
(but I'm on arm64, still should be emulated)
Alas, after copy to Applications, I get 'can't be opened' no matter what I do (right-click, double click)

Edit: The error I get is odd, it's just: Application napari cannot be opened. not the usual security concerns. i've tried running it from several locations (desktop, Apps, etc.).

**Comment by andy-sweet** [comment]
> Alas, after copy to Applications, I get 'can't be opened' no matter what I do (right-click, double click)

From memory, I had to right click open twice. The first time Apple said no way. And then they said fine if you really insist. Must be something like security through expected laziness.

**Comment by jaimergp** [comment]
I can't open it on my M1 either, despite accepting the security warnings in System preferences. I can access the .app contents and browse it, even managed to open the bundled `python`, but not napari itself. It gets killed immediately.

I then inspected the `Get Info` option of the contextual menu (right click) and enabled 'Open with Rosetta':

image


This allows napari to run but I do get the same pydantic error:

```
Traceback (most recent call last):
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 565, in <module>
    sys.exit(main())
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 561, in main
    _run()
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 218, in _run
    from napari import Viewer, run
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "napari.app/Contents/Resources/app/napari/_lazy.py", line 48, in __getattr__
    submod = import_module(
  File "napari.app/Contents/Resources/Support/Python/Resources/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "napari.app/Contents/Resources/app/napari/viewer.py", line 8, in <module>
    from .components.viewer_model import ViewerModel
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/components/__init__.py", line 19, in <module>
    from .layerlist import LayerList
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/components/layerlist.py", line 9, in <module>
    from ..layers import Layer
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/__init__.py", line 11, in <module>
    from .base import Layer
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/base/__init__.py", line 1, in <module>
    from .base import Layer, no_op
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/base/base.py", line 14, in <module>
    from npe2 import plugin_manager as pm
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/__init__.py", line 8, in <module>
    from ._dynamic_plugin import DynamicPlugin
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_dynamic_plugin.py", line 19, in <module>
    from ._plugin_manager import PluginManager
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_plugin_manager.py", line 30, in <module>
    from ._command_registry import CommandRegistry
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_command_registry.py", line 10, in <module>
    from .manifest import utils
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/__init__.py", line 2, in <module>
    from .schema import ENTRY_POINT, PluginManifest
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/schema.py", line 18, in <module>
    from .contributions import ContributionPoints
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/__init__.py", line 2, in <module>
    from ._configuration import ConfigurationContribution, ConfigurationProperty
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/_configuration.py", line 5, in <module>
    from ._json_schema import (
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/_json_schema.py", line 84, in <module>
    class _JsonSchemaBase(BaseModel):
  File "pydantic/main.py", line 179, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 395, in pydantic.typing.resolve_annotations
TypeError: __init__() got an unexpected keyword argument 'is_class'
```

So maybe it's a bad version for a dependency?

Let's check `pip list`:

```
[~/Desktop/napari.app/Contents/Resources/Support/bin]$ PYTHONPATH=../../app_packages ./python3 -m pip list
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
app-model                     0.0.9
appdirs                       1.4.4
appnope                       0.1.3
asciitree                     0.3.3
asttokens                     2.0.8
attrs                         22.1.0
Babel                         2.10.3
backcall                      0.2.0
build                         0.8.0
cachey                        0.2.1
certifi                       2022.9.24
charset-normalizer            2.1.1
click                         8.1.3
cloudpickle                   2.2.0
commonmark                    0.9.1
dask                          2022.9.1
debugpy                       1.6.3
decorator                     5.1.1
docstring-parser              0.15
docutils                      0.17.1
entrypoints                   0.4
executing                     1.1.0
fasteners                     0.18
freetype-py                   2.3.0
fsspec                        2022.8.2
HeapDict                      1.0.1
hsluv                         5.0.3
idna                          3.4
imagecodecs                   2022.9.26
imageio                       2.22.0
imagesize                     1.4.1
importlib-metadata            4.12.0
in-n-out                      0.1.5
ipykernel                     6.16.0
ipython                       8.5.0
ipython-genutils              0.2.0
jedi                          0.18.1
Jinja2                        3.1.2
jsonschema                    4.16.0
jupyter_client                7.3.5
jupyter-core                  4.11.1
kiwisolver                    1.4.4
locket                        1.0.0
magicgui                      0.5.1
MarkupSafe                    2.1.1
matplotlib-inline             0.1.6
napari-console                0.0.6
napari-plugin-engine          0.2.0
napari-svg                    0.1.6
nest-asyncio                  1.5.5
networkx                      2.8.6
npe2                          0.6.1
numcodecs                     0.10.2
numpy                         1.19.3
numpydoc                      1.4.0
packaging                     21.3
pandas                        1.4.4
parso                         0.8.3
partd                         1.3.0
pep517                        0.13.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
PIMS                          0.6.1
Pint                          0.19.2
pip                           22.2.2
pooch                         1.6.0
prompt-toolkit                3.0.31
psutil                        5.9.2
psygnal                       0.4.2
ptyprocess                    0.7.0
pure-eval                     0.2.2
pydantic                      1.10.2
Pygments                      2.13.0
PyOpenGL                      3.1.6
pyparsing                     3.0.9
pyrsistent                    0.18.1
PySide2                       5.15.2
python-dateutil               2.8.2
pytomlpp                      1.0.11
pytz                          2022.2.1
PyWavelets                    1.4.1
PyYAML                        6.0
pyzmq                         24.0.1
qtconsole                     5.3.2
QtPy                          2.2.0
requests                      2.28.1
rich                          12.5.1
scikit-image                  0.19.3
scipy                         1.9.1
shiboken2                     5.15.2
six                           1.16.0
slicerator                    1.1.0
snowballstemmer               2.2.0
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.5.1
superqt                       0.3.5
tifffile                      2022.8.12
tomli                         2.0.1
toolz                         0.12.0
tornado                       6.2
tqdm                          4.64.1
traitlets                     5.4.0
typer                         0.6.1
typing_extensions             4.3.0
urllib3                       1.26.12
vispy                         0.11.0
wcwidth                       0.2.5
wheel                         0.37.1
wrapt                         1.14.1
zarr                          2.13.2
zipp                          3.8.1
```

The two packages involved with this (npe2 and pydantic) are using their latest versions so no clue what's wrong.

I looked up the traceback and found an [issue comment that says this was already broken](https://github.com/spyder-ide/spyder/issues/18870#issuecomment-1201806050) for the last release... so _technically_ this issue solved the problem with the CI. The _other_ problem is that the Briefcase bundles (at least on MacOS) are broken for a while now?

**Comment by jaimergp** [comment]
Now to the actual bug, it comes from [this code in `pydantic`](https://github.com/pydantic/pydantic/blob/1a5b56e1b2020fd74800064d038becf614d64a61/pydantic/typing.py#L391-L404):

```python
    for name, value in raw_annotations.items():
        if isinstance(value, str):
            if (3, 10) > sys.version_info >= (3, 9, 8) or sys.version_info >= (3, 10, 1):
                value = ForwardRef(value, is_argument=False, is_class=True)
            else:
                value = ForwardRef(value, is_argument=False)
```

The bundled `python` reports:

```bash
$   ~/Desktop/napari.app/Contents/Resources/Support/bin/python3 -V
Python 3.9.1
```

However, if launched through `napari.app` directly, I can hack the napari startup code and print `sys.version_info` to a file, where we can see:

```
sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)
```

... so there's a disparity between the Python being shipped (and it's standard library!) and the one used to build the `napari` executable. Possibly the one in CI. So I suggest we pin to `3.9.1` in the CI.

Let's see if that fixes it.

**Comment by jaimergp** [comment]
Well, that didn't change much :/ Same error. The `napari` entry point keeps reporting 3.9.12. I wonder where that comes from!

**Comment by jaimergp** [comment]
Ah, they come from the app template, particularly in [this commit](https://github.com/beeware/briefcase-macOS-app-template/commit/d01d66b636967cec84866232ba3367432695ab5c). They updated the 'stubs' so I guess it uses 3.9.12 for that, but the support package we need is on 3.9.1, which is what creates the pydantic error Y_Y

**Comment by jaimergp** [comment]
I have pushed some changes that DO NOT fix the issue; well it does, but it creates other ones :) 

Our only hope now is to see if the recent templates have launchers that support arguments. we are sticking to old revisions because we need `napari` to behave as `python` for the purposes of plugin installations with `pip` (because we use `{sys.executable} -m pip` to do so).

So I'll try to revisit https://github.com/napari/napari/issues/2965 to see if now we have a more modern solution. If not... I suggest dropping Briefcase installers, at least for macOS. They have been broken for a while anyway, apparently, and nobody complained, which is telling us how much they are used.

**Comment by jaimergp** [comment]
Well, removing _every_ workaround for macOS (no old support or template packages, use latest briefcase, etc), leaves us with the **same** error as using templates b5 to b8:

```
Traceback (most recent call last):
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 565, in <module>
    sys.exit(main())
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 561, in main
    _run()
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 327, in _run
    viewer = Viewer()
  File "napari.app/Contents/Resources/app/napari/viewer.py", line 65, in __init__
    _initialize_plugins()
  File "napari.app/Contents/Resources/app/napari/plugins/__init__.py", line 46, in _initialize_plugins
    mf = PluginManifest.from_distribution('napari')
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/schema.py", line 228, in from_distribution
    raise ValueError(
ValueError: Distribution {name!r} exists but does not provide a napari manifest
```

**Comment by jaimergp** [comment]
And `briefcase build` ends up failing with:

```
/Library/Developer/CommandLineTools/usr/bin/codesign_allocate: fatal error: file not in an order that can be processed (link edit information does not fill the __LINKEDIT segment): /Users/jrodriguez/devel/napari/macOS/app/napari/napari.app/Contents/MacOS/napari (for architecture x86_64)
/Users/jrodriguez/devel/napari/macOS/app/napari/napari.app: the codesign_allocate helper tool cannot be found or used
```

:shrug:

**Comment by liu-ziyang** [comment]
Nice detective work everyone!

With NAP-2 I think there is consensus that we will be moving to conda based packaging, I would suggest that as long as we are shipping the conda build we can maybe keep one eye closed on the briefcase build issue for macos, if it turns out to be too complicate to fix

**Comment by andy-sweet** [comment]
Agree with the sentiment here. Was hoping for a quick fix but we couldn't find one. I also could not install the briefcase-based bundle for v0.4.16, so the artifact has likely been broken for a while even when the action was successful.

I may still revert the extra changes here to at least make the action pass again, though based on the error, I doubt that artifact is useful for anyone.

+1 to dropping the briefcase-based installers for v0.5.

**Comment by andy-sweet** [comment]
@jaimergp : I decided to revert your changes, but kept the verbose flag if we want to debug this later. If you think this looks good, approve and I'll merge.

**Review by jaimergp — APPROVED** [review]

**Pull request merged**
