### PR TITLE
[WIP] try more mac test fixes

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
Trying to fix tests - experimental

### CODE REVIEW

**Comment by kne42** [comment]
for this kind of testing I would recommend that you set up cirrus on your account and monitor the branch you push without creating a PR here

**Comment by sofroniewn** [comment]
ah ok, thanks @kne42 - i will try that after these tests finish. For some reason our macosx tests aren't running - I've have some queued for > 2 hours this morning :-( which is why I thought I'd try making a new PR and seeing if they ran

**Comment by kne42** [comment]
cirrus issues per-user limits on how many concurrent tasks they can have running. you probably ran into that or maybe their system was down. I would recommend turning off all tests but one osx one and going from there

**Comment by sofroniewn** [comment]
Ah interesting - I see here https://cirrus-ci.org/faq/ that each `user` (not org / repo) is allowed at most one simultaneous mac os x test - I guess mine are somehow blocking or something is broken :-(

**Comment by sofroniewn** [comment]
closing as test failed (was playing with the time to close the app during testing) and for comments made above about user usage limits

**Pull request closed without merging**
