### PR TITLE
Workaround Qt bug on Windows with fullscreen mode in some screen resolutions/scaling configurations

### LINKED ISSUE #3441: Persistence of full-screen mode confusing, hard to close/minimize
## 🐛 Bug

Issue copied from @optomanishk image.sc: https://forum.image.sc/t/napari-opens-in-full-screen-mode-and-doesnt-function/58286

----

I’m using the usual example code from a jupyter notebook to start napari UI.
Code:

```py
from skimage import data
import napari

viewer = napari.view_image(data.astronaut(), rgb=True)
napari.run()  # start the event loop and show viewer
```

napari opens in this full-screen mode where none of the options (File - View - Window - Plugins - Help) work. There is no close/maximize/minimize button either.

I get this warning:
```
WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1920x1080+1928+31 (frame: 1936x1119+1920+0) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY2". Resulting geometry: 1920x1061+1928+31 (frame: 1936x1100+1920+0) margins: 8, 31, 8, 8 minimum size: 608x520 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=624,559 maxtrack=0,0)
```

----

solved by `napari --reset` ... but it would be nice to avoid that 

related issue: #2971 #3038 #3075 
cc @goanpeca

### PR DESCRIPTION
**Pull request by dalthviz**
# Description

Fixes #3441 

### Before

https://user-images.githubusercontent.com/16781833/207097529-5aa1495a-284f-48c7-8870-563f110bf147.mp4

### After

https://user-images.githubusercontent.com/16781833/207092320-8c3c46c9-f5bd-425a-b0d8-2996f3003739.mp4

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [x] all tests pass with my change
- [x] I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]

**Comment by brisvag** [comment]
Thanks @dalthviz! Anyone with access to a windows machine who could double check? @andy-sweet

**Comment by andy-sweet** [comment]
> Thanks @dalthviz! Anyone with access to a windows machine who could double check? @andy-sweet

Happy to! I just tried reproducing the original bug on `main`, but could not (Windows 10, Qt 5.15.2, PyQt 5.15.4). Is there some precondition I missed (e.g. Window size in settings/preferences)?

**Comment by dalthviz** [comment]
Checked locally with the latest `main` ( b5696770d31cbaa6dc02068b8b8b0a95bdd8a107) and resetted Napari preferences just in case (using `napari --reset`) and I'm able to still reproduce the issue but checking more in detail I'm able to reproduce this only for one of my screens (the one with resolution 1366x768, scale 1.0). My setup info:

```
napari: 0.4.17rc4.dev123+gb5696770
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:29:51) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.4
SciPy: 1.9.3
Dask: 2022.10.2
VisPy: 0.12.1
magicgui: 0.6.0
superqt: 0.3.8
in-n-out: 0.1.5
app-model: 0.1.0
npe2: 0.6.1

OpenGL:
- GL version: 4.5.0 - Build 25.20.100.6444
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1366x768, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Settings path:
- C:\Users\dalth\AppData\Local\napari\napari-dev_4454fdbf170edefe23827a4bf512389a6806af69\settings.yaml
```

Do you have a 1080p screen or one with higher resolution perhaps @andy-sweet ? For the moment I will investigate if something else could be done to enable the fullscreen on low resolution screens (since it seems like it works without changing anything for screens with at least 1080p resolution).

**Comment by andy-sweet** [comment]
Thanks for the extra info @dalthviz ! I was testing at a higher resolution than 1080p, so I'll retry it again after setting it be lower.

**Comment by andy-sweet** [comment]
Actually, I can only reproduce the original error at high resolution (2880x1800) (with 2x magnification) whereas 1920x1200 (with 1.25 magnification) works fine. I can confirm that this branch fixes the issues at high resolution though!

**Review by andy-sweet — APPROVED** [review]
Code changes look good and explanatory comments with links are fantastic. Thanks!

**Comment by andy-sweet** [comment]
I'll merge this after 24 hours unless anyone objects.

**Comment by kcpevey** [comment]
@andy-sweet looks like this one is ready to go :)

**Comment by psobolewskiPhD** [comment]
This is still a problem in the wild -- see image.sc post above -- so I'm going to mark this Bugfix and switch o 0.4.19 milestone.

**Pull request merged**
