### PR TITLE
Make all imports absolute

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This is an alternative to #5308 where all imports are absolute

## Type of change

- [x] Refactor

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

cc @jni @kephale @goanpeca @psobolewskiPhD

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
As I posted in the other thread, as a serious newbie I find the ... imports really confusing. When reading code I'm never sure where the import is from. Worse yet, I copy-paste a lot to try functions and such to see what they return and do, because I'm not good at reading the code. Then the .. imports don't work and I need to figure out what was intended. 
So from my side, as a newbie, relative outsider, and all-around not-very-smart person: 👍

**Review by goanpeca — APPROVED** [review]
Thanks for working on this @Czaki ! 🚀

**Review by jni — APPROVED** [review]
Reading up a bit, it seems that absolute imports are preferred by a large percentage of the Python community, and indeed by our own napari community, so 👍 from me. Thank you @Czaki and also everyone else who has contributed to this discussion!

**Comment by brisvag** [comment]
This is gonna be a nightmare on all open PRs ^^'

**Review by brisvag — APPROVED** [review]

**Comment by Czaki** [comment]
> This is gonna be a nightmare on all open PRs ^^'

pre-commit action will solve most of problems

**Comment by Czaki** [comment]
Lets the conflicts start.

**Pull request merged**
