### PR TITLE
Windows CI: Properly configure OpenGL

### PR DESCRIPTION
**Pull request by kne42**
# Description
Properly install OpenGL on Windows systems in the CI (as cherry-picked from #67).

# How has this been tested?
See #67

### CODE REVIEW

**Comment by sofroniewn** [comment]
Thanks for pushing this! Why don't you think the checks have passed yet? Seems like the linux check is hanging and the other checks havn't run

**Comment by kne42** [comment]
Yeah I forgot I had some emails hanging around asking me to update
permissions so I just fixed that.

**Comment by kne42** [comment]
Looks like Linux Py3.7 is failing due to some `pip`-related bug and both Windows versions are now subject to `conda`'s SSL bug.

**Comment by kne42** [comment]
closing in favor of #104

**Pull request closed without merging**
