### PR TITLE
Fix trim of layer number

### PR DESCRIPTION
**Pull request by Czaki**
# Description

obraz

obraz

allow 14px height of QLineEdit in QtDimSliderWidget
## Type of change

- [x] style-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tlambert03** [comment]
Awesome @Czaki, I just merged your other PR into master.  Want to merge that back into this PR and see if it's all fixed?

**Comment by Czaki** [comment]
looks ok for me: 
obraz

On MacOS also.

**Review by tlambert03 — APPROVED** [review]
way to go.  thanks for doing this.  that was a glaring "blemish" on the GUI.

**Comment by tlambert03** [comment]
any interest in figuring out how to get rid of that white vertical line below the numbers there?  I think that only shows up on windows

**Pull request merged**
