### PR TITLE
[Maint] update pyside6_experimental to be >6.7

### LINKED ISSUE #5644: Qt6, MacOS: Whole window flashes when resizing canvas with layer
## 🐛 Bug

When using napari in a recently installed conda environment with PyQt6, the whole window flashes or flickers to white when resizing the canvas (and maybe in other cases). This does not occur when showing the welcome widget instead of the canvas.

Here's a video that shows when this happens, though ⚠️  be warned that the frequency of the flashing may cause issues for those with photosensitivity ⚠️ , so don't press play unless you're prepared for that.

https://user-images.githubusercontent.com/2608297/226410625-281cc376-8c2f-485c-9340-bd54e5740296.mp4

## To Reproduce

The easiest way to reproduce this is as follows.

- Setup a conda environment with pyqt6 and an editable/dev install of napari.
- Open napari.
- Open any layer (I tried 2D and 3D images, and 2D points).
- Move the separator between the left control panel and the canvas.

Adding the layer and resizing the window also causes the issue, but the flashing is less frequent.

## Expected behavior

I'd expect no flashing/flickering.

## Environment

```
napari: 0.4.17rc4.dev224+g1fcceb42e
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 13.1
Python: 3.10.9 (main, Mar  8 2023, 04:44:36) [Clang 14.0.6 ]
Qt: 6.4.2
PyQt6: 
NumPy: 1.24.2
SciPy: 1.10.1
Dask: 2023.3.1
VisPy: 0.12.1
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2

OpenGL:
  - GL version:  2.1 INTEL-20.2.48
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1920x1080, scale 1.0

Settings path:
  - /Users/asweet/Library/Application Support/napari/napari-dev_94a2c6ecd2bb4e54de7c17f279d1ba0ad46bb93d/settings.yaml
Plugins:
  - napari: 0.4.17rc4.dev224+g1fcceb42e (77 contributions)
  - napari-console: 0.0.7 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)
  - napari-ui-tracer: 0.1.1 (2 contributions)
```

## Additional context

This does not happen with my pyqt5 environment at the same commit of ab885957f, or my pyqt5 environment associated with v0.4.17. Therefore, I assume this is a pyqt6 issue.

### LINKED ISSUE #5657: [Qt6, pyside6]: napari/_qt/_tests_/test_qt_viewer.py failing on pyside6 6.4.3
## 🐛 Bug

pyside6 6.4.3 was released a few hours ago.
Ubuntu 3.10 pyside6 CI is failing on napari/_qt/_tests_/test_qt_viewer.py with set fault.
Running pytest locally with pysdie6 6.4.3 on my mac also fails:
<details>

```
============================= test session starts ==============================
platform darwin -- Python 3.10.9, pytest-7.2.2, pluggy-1.0.0 -- /Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/bin/python3.10
cachedir: .pytest_cache
PySide6 6.4.3 -- Qt runtime 6.4.3 -- Qt compiled 6.4.3
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/piotrsobolewski/Dev/napari/.hypothesis/examples')
rootdir: /Users/piotrsobolewski/Dev/napari, configfile: pyproject.toml
plugins: npe2-0.6.2, qt-4.2.0, hypothesis-6.70.0, napari-plugin-engine-0.2.0, cov-4.0.0, pretty-1.1.1, napari-0.5.0a2.dev51+gfc038f36
collected 58 items                                                             

napari/_qt/_tests/test_qt_viewer.py::test_qt_viewer PASSED               [  1%]
napari/_qt/_tests/test_qt_viewer.py::test_qt_viewer_with_console PASSED  [  3%]
napari/_qt/_tests/test_qt_viewer.py::test_qt_viewer_toggle_console PASSED [  5%]
napari/_qt/_tests/test_qt_viewer.py::test_qt_viewer_console_focus SKIPPED (Tests requiring GUI windows are skipped locally by default. Set NAPARI_POPUP_TESTS=1 environment variable to enable.) [  6%]
napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Image-data0-2] PASSED [  8%]Fatal Python error: Bus error

Current thread 0x0000000208d40140 (most recent call first):
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/_testsupport.py", line 253 in make_napari_viewer
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/fixtures.py", line 917 in _teardown_yield_fixture
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/fixtures.py", line 1030 in finish
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/fixtures.py", line 685 in <lambda>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/runner.py", line 523 in teardown_exact
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/runner.py", line 180 in pytest_runtest_teardown
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/runner.py", line 260 in <lambda>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/runner.py", line 339 in from_call
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/runner.py", line 220 in call_and_report
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/runner.py", line 132 in runtestprotocol
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/main.py", line 324 in _main
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/bin/pytest", line 8 in <module>

Extension modules: pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, yaml._yaml, pvectorc, psutil._psutil_osx, psutil._psutil_posix, markupsafe._speedups, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg._cythonized_array_utils, scipy.linalg._flinalg, scipy.linalg._solve_toeplitz, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_lapack, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy._lib._uarray._uarray, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.fftpack.convolve, skimage._shared.geometry, charset_normalizer.md, lxml._elementpath, lxml.etree, lxml.html.clean, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pandas._libs.ops, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.tslibs.strptime, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, xxsubtype, shiboken6.Shiboken, PySide6.QtCore, PySide6.QtGui, PySide6.QtDataVisualization, numpy.linalg.lapack_lite, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.special.cython_special, scipy.stats._stats, scipy.stats.beta_ufunc, scipy.stats._boost.beta_ufunc, scipy.stats.binom_ufunc, scipy.stats._boost.binom_ufunc, scipy.stats.nbinom_ufunc, scipy.stats._boost.nbinom_ufunc, scipy.stats.hypergeom_ufunc, scipy.stats._boost.hypergeom_ufunc, scipy.stats.ncf_ufunc, scipy.stats._boost.ncf_ufunc, scipy.stats.ncx2_ufunc, scipy.stats._boost.ncx2_ufunc, scipy.stats.nct_ufunc, scipy.stats._boost.nct_ufunc, scipy.stats.skewnorm_ufunc, scipy.stats._boost.skewnorm_ufunc, scipy.stats.invgauss_ufunc, scipy.stats._boost.invgauss_ufunc, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy.stats._statlib, scipy.stats._mvn, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._rcont.rcont, skimage.draw._draw, vispy.visuals.text._sdf_cpu, PySide6.QtWidgets, PySide6.QtTest, pydantic._hypothesis_plugin, PySide6.QtOpenGL, PySide6.QtOpenGLWidgets, PySide6.QtSvg, kiwisolver._cext, zmq.backend.cython.context, zmq.backend.cython.message, zmq.backend.cython.socket, zmq.backend.cython._device, zmq.backend.cython._poll, zmq.backend.cython._proxy_steerable, zmq.backend.cython._version, zmq.backend.cython.error, zmq.backend.cython.utils, tornado.speedups, PySide6.QtPrintSupport (total: 214)
fish: Job 1, 'pytest napari/_qt/_tests/test_q…' terminated by signal SIGBUS (Misaligned address error)

```
</details>

## To Reproduce

1. install pyside6 from pip (6.4.3)
2. install napari from source (.[dev])
3. pytest napari/_qt/_tests/test_qt_viewer.py -v

## Expected behavior

Should pass

## Environment

```
napari: 0.5.0a2.dev51+gfc038f36
Platform: macOS-13.2.1-arm64-arm-64bit
System: MacOS 13.2.1
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
Qt: 6.4.3
PySide6: 
NumPy: 1.24.2
SciPy: 1.10.1
Dask: 2023.3.1
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2

OpenGL:
  - GL version:  2.1 Metal - 83
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/nap-test_7c76622a0687875ccda8795c7fa273700326cf80/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev51+gfc038f36 (77 contributions)
  - napari-console: 0.0.7 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)
```

## Additional context

napari does launch and a few opening and closings of things work.
Also running the test from the vscode `testing` panel makes all tests pass....

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# References and relevant issues
Closes: https://github.com/napari/napari/issues/5657
Closes: https://github.com/napari/napari/issues/5644

# Description
Permits only pyside6 >6.7, so currently 6.7.1 which appears to resolve the test failures -- at least locally for me.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
Bah, different segfault:
https://github.com/napari/napari/actions/runs/9246067031/job/25433325095?pr=6936#step:13:116

This one does pass for me locally though (unlike the viewer one where it segfaulted locally and on ci)

**Comment by dalthviz** [comment]
Just in case, PySide 6.7.2 just got released https://pypi.org/project/PySide6/6.7.2/

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Pull request closed without merging**
