### PR TITLE
Fix sync slicing of not yet visible layers

### LINKED ISSUE #6651: Broken slicing when layers are added with visible=False onto a 3D canvas
### 🐛 Bug Report

If you add a Labels layer when the viewer is in 3D view with `visible=False`, the slice information will be incorrect, and it will not be updated when setting `visible=True` on the layer. This will result in an incorrect display (a 2D slice of data in the 3D space). Additionally, the 2D slice will be used when using get_value which results in the following traceback getting spammed to the terminal/error notifications:

<details>

<summary>

```pytb
File ~/projects/napari/napari/layers/labels/labels.py:1000, in Labels._get_value_ray(self=<Labels layer 'labels'>, start_point=<class 'numpy.ndarray'> (3,) float64, end_point=<class 'numpy.ndarray'> (3,) float64, dims_displayed=[0, 1, 2])
-> 1000 values = im_slice[tuple(clamped.T)]
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

</summary>

```pytb
IndexError                                Traceback (most recent call last)
File ~/projects/napari/napari/components/viewer_model.py:543, in ViewerModel._update_status_bar_from_cursor(self=Viewer(camera=Camera(center=(2.0, 49.5, 49.5), z...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), event=None)
    541 active = self.layers.selection.active
    542 if active is not None:
--> 543     self.status = active.get_status(
        active = <Labels layer 'labels' at 0x1651d2450>
        self.status = {'layer_base': 'labels', 'source_type': '', 'plugin': '', 'coordinates': ' [30 53 40]: 0'}
        self = Viewer(camera=Camera(center=(2.0, 49.5, 49.5), zoom=8.835, angles=(-39.99999999999999, -50.00000000000001, 149.99999999999997), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(9.988404051331976, 50.24342051230364, 46.688696558469374), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=10.0), dims=Dims(ndim=3, ndisplay=3, order=(0, 1, 2), axis_labels=('0', '1', '2'), range=(RangeTuple(start=0.0, stop=4.0, step=1.0), RangeTuple(start=0.0, stop=99.0, step=1.0), RangeTuple(start=0.0, stop=99.0, step=1.0)), margin_left=(0.0, 0.0, 0.0), margin_right=(0.0, 0.0, 0.0), point=(2.0, 49.0, 49.0), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'image' at 0x16cbbf050>, <Labels layer 'labels' at 0x1651d2450>], help='use <7> for transform, use <1> for activate the label eraser, use <2> for activate the paint brush, use <3> for activate the polygon tool, use <4> for activate the fill bucket, use <5> for pick mode', status={'layer_base': 'labels', 'source_type': '', 'plugin': '', 'coordinates': ' [30 53 40]: 0'}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x153e84360>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
        self.cursor.position = (9.988404051331976, 50.24342051230364, 46.688696558469374)
        self.cursor = Cursor(position=(9.988404051331976, 50.24342051230364, 46.688696558469374), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=10.0)
        self.cursor._view_direction = <class 'numpy.ndarray'> (3,) float64
        self.dims = Dims(ndim=3, ndisplay=3, order=(0, 1, 2), axis_labels=('0', '1', '2'), range=(RangeTuple(start=0.0, stop=4.0, step=1.0), RangeTuple(start=0.0, stop=99.0, step=1.0), RangeTuple(start=0.0, stop=99.0, step=1.0)), margin_left=(0.0, 0.0, 0.0), margin_right=(0.0, 0.0, 0.0), point=(2.0, 49.0, 49.0), last_used=0)
    544         self.cursor.position,
    545         view_direction=self.cursor._view_direction,
    546         dims_displayed=list(self.dims.displayed),
    547         world=True,
    548     )
    550     self.help = active.help
    551     if self.tooltip.visible:

File ~/projects/napari/napari/layers/labels/labels.py:1532, in Labels.get_status(self=<Labels layer 'labels'>, position=(9.988404051331976, 50.24342051230364, 46.688696558469374), view_direction=<class 'numpy.ndarray'> (3,) float64, dims_displayed=[0, 1, 2], world=True)
   1510 """Status message information of the data at a coordinate position.
   1511
   1512 Parameters
   (...)
   1529     Dict containing a information that can be used in a status update.
   1530 """
   1531 if position is not None:
-> 1532     value = self.get_value(
        self = <Labels layer 'labels' at 0x1651d2450>
        position = (9.988404051331976, 50.24342051230364, 46.688696558469374)
        view_direction = <class 'numpy.ndarray'> (3,) float64
        dims_displayed = [0, 1, 2]
        world = True
   1533         position,
   1534         view_direction=view_direction,
   1535         dims_displayed=dims_displayed,
   1536         world=world,
   1537     )
   1538 else:
   1539     value = None

File ~/projects/napari/napari/layers/base/base.py:1317, in Layer.get_value(self=<Labels layer 'labels'>, position=<class 'numpy.ndarray'> (3,) float64, view_direction=<class 'numpy.ndarray'> (3,) float64, dims_displayed=[0, 1, 2], world=True)
   1310         view_direction = self._world_to_data_ray(view_direction)
   1311         start_point, end_point = self.get_ray_intersections(
   1312             position=position,
   1313             view_direction=view_direction,
   1314             dims_displayed=dims_displayed,
   1315             world=False,
   1316         )
-> 1317         value = self._get_value_3d(
        self = <Labels layer 'labels' at 0x1651d2450>
        start_point = <class 'numpy.ndarray'> (3,) float64
        end_point = <class 'numpy.ndarray'> (3,) float64
        dims_displayed = [0, 1, 2]
   1318             start_point=start_point,
   1319             end_point=end_point,
   1320             dims_displayed=dims_displayed,
   1321         )
   1322 else:
   1323     value = self._get_value(position)

File ~/projects/napari/napari/layers/labels/labels.py:1032, in Labels._get_value_3d(self=<Labels layer 'labels'>, start_point=<class 'numpy.ndarray'> (3,) float64, end_point=<class 'numpy.ndarray'> (3,) float64, dims_displayed=[0, 1, 2])
   1008 def _get_value_3d(
   1009     self,
   1010     start_point: Optional[np.ndarray],
   1011     end_point: Optional[np.ndarray],
   1012     dims_displayed: List[int],
   1013 ) -> Optional[int]:
   1014     """Get the first non-background value encountered along a ray.
   1015
   1016     Parameters
   (...)
   1029         non-zero value is not encountered, returns 0 (the background value).
   1030     """
   1031     return (
-> 1032         self._get_value_ray(
        self = <Labels layer 'labels' at 0x1651d2450>
        start_point = <class 'numpy.ndarray'> (3,) float64
        end_point = <class 'numpy.ndarray'> (3,) float64
        dims_displayed = [0, 1, 2]
   1033             start_point=start_point,
   1034             end_point=end_point,
   1035             dims_displayed=dims_displayed,
   1036         )
   1037         or 0
   1038     )

File ~/projects/napari/napari/layers/labels/labels.py:1000, in Labels._get_value_ray(self=<Labels layer 'labels'>, start_point=<class 'numpy.ndarray'> (3,) float64, end_point=<class 'numpy.ndarray'> (3,) float64, dims_displayed=[0, 1, 2])
    994 bounding_box[:, 1] += 1
    996 clamped = clamp_point_to_bounding_box(
    997     sample_points,
    998     bounding_box,
    999 ).astype(int)
-> 1000 values = im_slice[tuple(clamped.T)]
        im_slice = <class 'numpy.ndarray'> (100, 100) int32
        clamped = <class 'numpy.ndarray'> (31, 3) int64
   1001 nonzero_indices = np.flatnonzero(values)
   1002 if len(nonzero_indices > 0):
   1003     # if a nonzer0 value was found, return the first one

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

</details>

### 💡 Steps to Reproduce

Here is a fully reproducible example:

```python
import numpy as np
import napari
from scipy import ndimage as ndi

image = np.random.random((5, 100, 100))
labels = ndi.label(image > 0.5)[0]

viewer, imlayer = napari.imshow(image, ndisplay=3)
labels_layer = viewer.add_labels(labels, visible=False)

labels_layer.visible = True

viewer.camera.angles = (-40, -50, 150)

napari.run()
```

Results in:

Screenshot 2024-02-08 at 6 16 54 pm

### 💡 Expected Behavior

When visible is set to true **for the first time**, the slicing information should be updated and the layer should be sliced. (I expect that we don't currently do it so that toggling the visible button is fast and doesn't cause a potentially-expensive reslice every time the visibility is toggled.)

### 🌎 Environment

napari: 0.5.0a2.dev499+g1c055c54f
Platform: macOS-13.6.4-arm64-arm-64bit
System: MacOS 13.6.4
Python: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
Qt: 5.15.11
PyQt5: 5.15.10
NumPy: 1.26.2
SciPy: 1.11.4
Dask: 2023.12.0
VisPy: 0.14.1
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 3200x1800, scale 2.0
  - screen 2: resolution 1800x1169, scale 2.0

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f206df4881e2999baa22e6df448393db299c70d6/settings.yaml
Plugins:
  - cellpose-napari: 0.1.5 (6 contributions)
  - iterseg: 0.1.0 (14 contributions)
  - napari: 0.5.0a2.dev730+g04eb761f1.d20231208 (81 contributions)
  - napari-animation: 0.0.7 (2 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-svg: 0.1.11.dev1+g2542e94.d20231211 (2 contributions)
  - ome-types: 0.4.5 (2 contributions)
  - platetrack: 0.0.5 (2 contributions)

### 💡 Additional Context

Distilled down from this image.sc post:

https://forum.image.sc/t/cellpose-napri-produces-what-looks-like-an-orthogonal-label-layer/91900/7

### LINKED ISSUE #6760: [Main] Unexpected slice display after adjusting hidden layer's slider position
### 🐛 Bug Report

Adjusting the slider while the layer is hidden and then making it visible again displays the previously visible slice, not the slice corresponding to the new slider position.

### 💡 Steps to Reproduce

1. Open sample Cells (3D+2Ch) 
2. Switch off the visibility of one of the layers (ex. nuclei)
3. Move the position of the slider
4. Swich on the visibility of the layer

### 💡 Expected Behavior

I would expect that after switching on the visibility of the layer the correct slice is displayed.

### 🌎 Environment

napari: 0.5.0a2.dev606+gb3e15c51
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:27:34) [MSC v.1937 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.3.1
VisPy: 0.14.2
magicgui: 0.8.2
superqt: 0.6.2
in-n-out: 0.2.0
app-model: 0.2.5
npe2: 0.7.4

### 💡 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by andy-sweet**
# References and relevant issues
Closes #6651, #6760 

# Description
This changes how we handle sync slicing of non-visible layers in the `LayerSlicer` by always slicing all layers using `Layer._slice_dims`. The effect is that `Layer._slice_input` should now always be up-to-date with the state of `ViewerModel.dims`, so that if the layer becomes visible later (without the `Dims` state changing) it has the state necessary to fetch the right data. If the layer is not visible, the logic of `Layer.refresh` ensures we don't actually fetch data since that would be wasteful.

Note that the logic of async slicing's `refresh` is fundamentally different to sync slicing because all it does is notify the `ViewerModel` that it should be refreshed because it assumes it does not have all the state necessary to do slicing (because that's in `Dims`). While that has some disadvantages, I still prefer that logic over the current sync slicing approach, which is to keep the slice state from `Dims` up to date with the corresponding state in the layer, so that it's ready to fetch the right data in the future.

### CODE REVIEW

**Comment by andy-sweet** [comment]
I considered some alternatives here.

(1) Define the same logic for async and sync in `Layer.refresh` by only emitting the `reload` event.
This is closer to what I see as a long term fix. But I avoided it for now because I'm unsure how much people depend on `Layer.refresh` doing something when a layer is in `ViewerModel.layers` (in this fix, nothing would happen).

(2) Return `None` in `Layer._make_slice_request` when `Layer.visible` is `False`.
Like the current fix, `LayerSlicer` would iterate over all layers, but would skip non-visible layers for async slicing. This is pretty similar to the current approach. One longer term benefit is that it would allow other reasons for a layer to decide it does not need to be sliced (e.g. the current view is out of bounds). But it also feels more complicated, so I avoided it for now.

**Comment by dalthviz** [comment]
Hi there, just in case, I think this also helps with #6651

**Comment by psobolewskiPhD** [comment]
Nice catch @dalthviz -- I can confirm that!

**Comment by andy-sweet** [comment]
Thanks @dalthviz ! Somehow, I missed #6651 ...

I think the test case added here is close enough to #6651 , so I won't add another. But I did add that issue to the PR description.

**Review by psobolewskiPhD — APPROVED** [review]
Makes sense to me, thanks for the detailed explanations!

**Review by jni — APPROVED** [review]

**Pull request merged**
