### PR TITLE
pin pyside to 5.15.1

### PR DESCRIPTION
**Pull request by Czaki**
# Description

pin pyside to 5.15.1 version to verify test fail

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Czaki** [comment]
I cannot find, why the bundle fails. It looks a little like an update of the system and bug in briefcase.

**Comment by sofroniewn** [comment]
@Czaki this seems to have fixed the tests, well identified, but the bundle build is failing

**Comment by sofroniewn** [comment]
> I cannot find, why the bundle fails. It looks a little like an update of the system and bug in briefcase.

Sorry, just saw this message. Hmm interesting, can we use an older version of briefcase? I feel like it built last week

**Comment by sofroniewn** [comment]
Yeah, the bundle build fail is unrelated to pyside2 5.12.2, see this example of the build working from the other day with pyside2 5.12.2 https://github.com/napari/napari/runs/1433892649?check_suite_focus=true

I will add a release note and then merge

**Comment by Czaki** [comment]
I do comparision of briefcase build log and do not see difference. Briefcase is pinned.

There is a problem with requested version of system library.

It look like upgrade of host system.

**Comment by sofroniewn** [comment]
> I do comparision of briefcase build log and do not see difference. Briefcase is pinned.
>
> There is a problem with requested version of system library.
>
> It look like upgrade of host system.

Ah ok, I also just realized that this pin is just for our tests!! Sorry I'm clearly a bit off right now. I won't merge just yet :-)

**Comment by liu-ziyang** [comment]
> I do comparision of briefcase build log and do not see difference. Briefcase is pinned.
> 
> There is a problem with requested version of system library.
> 
> It look like upgrade of host system.

I think I have some clue: the working build was using libgdbm.so.3, however the current builds are now looking for libgdbm.so.5

**Comment by liu-ziyang** [comment]
the build issue is fixed on https://github.com/napari/napari/pull/1918, but I am still working on the nightly build, if we want we can merge the PR, and I can patch nightly builds later

**Comment by sofroniewn** [comment]
> the build issue is fixed on #1918, but I am still working on the nightly build, if we want we can merge the PR, and I can patch nightly builds later

If #1918 isn't fully ready can you split it into two PRs, one just fixing build, and then one that will move to on merge + nightly?

**Comment by sofroniewn** [comment]
Ok, I've updated this PR to now include some extra comments and release notes. I will merge if all tests pass

**Comment by sofroniewn** [comment]
I've updated this PR so that it doesn't change how the bundle is built, which I don't think was needed

**Review by sofroniewn — APPROVED** [review]

**Pull request merged**
