### PR TITLE
BugFix: napari does not start with Python v3.11.1: "ValueError: A distribution name is required."

### PR DESCRIPTION
**Pull request by glichtner**
# Description

## Summary
napari does not start with Python 3.11.1 as `importlib.metadata.Distribution` raises `ValueError: A distribution name is required.`

## Solution
The solution is to add an additional check for empty `app_module` in `running_as_bundled_app()` and return False if it is empty.

## Details
* The `from_name()` function of Python's `importlib.metadata.Distribution` has been changed to [check for the emptiness of the `name` parameter](https://github.com/python/cpython/blob/v3.11.1/Lib/importlib/metadata/__init__.py#L560) in Python 3.11.1 (vs 3.11.0; [see updated version here](https://github.com/python/cpython/blob/v3.11.1/Lib/importlib/metadata/__init__.py#L550) vs [previous version](https://github.com/python/cpython/blob/v3.11.0/Lib/importlib/metadata/__init__.py#L546) ). 
* An empty name will now throw a ValueError, preventing napari from starting with Python v3.11.1, as `napari.utils.misc.running_as_bundled_app()` calls `importlib.metadata.metadata()` with an empty `app_module` parameter when running as stand-alone or using pytest. 
* This `app_module` parameter is directly relayed to `Distribution.from_name`, resulting in the following error when running napari with Python 3.11.1 (Ubuntu 22.04.1 LTS; napari pypi release 0.4.17 and github commit 54c1dbf81fb4321637e56156b7bf75f971ad8613 )

```
Traceback (most recent call last):
  File "/home/glichtner/code/test/test/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/__main__.py", line 561, in main
    _run()
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/__main__.py", line 218, in _run
    from napari import Viewer, run
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/_lazy.py", line 48, in __getattr__
    submod = import_module(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/viewer.py", line 8, in <module>
    from .components.viewer_model import ViewerModel
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/components/__init__.py", line 19, in <module>
    from .layerlist import LayerList
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/components/layerlist.py", line 9, in <module>
    from ..layers import Layer
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/layers/__init__.py", line 11, in <module>
    from .base import Layer
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/layers/base/__init__.py", line 1, in <module>
    from .base import Layer, no_op
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/layers/base/base.py", line 28, in <module>
    from ...utils.key_bindings import KeymapProvider
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/utils/key_bindings.py", line 46, in <module>
    from ..settings import get_settings
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/settings/__init__.py", line 6, in <module>
    from ._napari_settings import CURRENT_SCHEMA_VERSION, NapariSettings
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/settings/_napari_settings.py", line 14, in <module>
    from ._plugins import PluginsSettings
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/settings/_plugins.py", line 27, in <module>
    class PluginsSettings(EventedSettings):
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/settings/_plugins.py", line 75, in PluginsSettings
    class NapariConfig:
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/settings/_plugins.py", line 83, in NapariConfig
    if running_as_bundled_app() or running_as_constructor_app():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glichtner/code/test/test/lib/python3.11/site-packages/napari/utils/misc.py", line 67, in running_as_bundled_app
    metadata = importlib.metadata.metadata(app_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 998, in metadata
    return Distribution.from_name(distribution_name).metadata
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 561, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.
```

* The error occurs with Python v3.11.1 on macos, windows and linux (as indicated by my napari's plugin test runs: https://github.com/glichtner/napari-pystackreg/actions/runs/3923263123).
* I have tested the fix on Ubuntu 22.04.1 LTS

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Thanks for the contribution! 
🙏 
I've activated CI and requested reviews from some smart folks!

**Comment by Czaki** [comment]
PR related to this PR: #5439,

EDIT. IT will be nice to add some CI run for python 3.11 to our matrix. Without this we do not know if it is the only bug in 3.11 env.

**Comment by jaimergp** [comment]
This LGTM, but I have a question: under what circumstances is `__package__` set to `None`?

**Comment by Czaki** [comment]
start 24h clock 

> This LGTM, but I have a question: under what circumstances is `__package__` set to `None`?

I do not know, but it is present for a long time. 

This what was changed is `importlib.metadata.metadata` that stops accepting `None` as the argument.

**Review by Czaki — APPROVED** [review]

**Pull request merged**
