### PR TITLE
Apply shown mask to points._view_size_scale

### PR DESCRIPTION
**Pull request by mstabrin**
# Description

This pull request tackles the issue of a dimensional mismatch between `Points._view_size_scale` and `Points._indices_view` in combination with the `Points.shown` property and `Points.out_of_slice_display`.

Steps to reproduce:
1. Open Napari 
2. Open the napari console
3. Type: `viewer.add_points([[0, 0, 0], [1,1,1]], out_of_slice_display=True, shown=[True, False], size=3)`

```
...
File /opt/user_software/miniconda3/envs/napari-tomotwin-debug2/lib/python3.9/site-packages/vispy/visuals/markers.py:725, in MarkersVisual.set_data(self, pos, size, edge_width, edge_width_rel, edge_color, face_color, symbol, scaling)
    723     data['a_edgewidth'] = edge_width
    724 else:
--> 725     data['a_edgewidth'] = size * edge_width_rel
    726 data['a_position'][:, :pos.shape[1]] = pos
    727 data['a_size'] = size

ValueError: could not broadcast input array from shape (2,) into shape (1,)
/opt/user_software/miniconda3/envs/napari-tomotwin-debug2/lib/python3.9/site-packages/ipykernel/kernelbase.py:757: RuntimeWarning: coroutine 'InProcessKernel._abort_queues' was never awaited!
```

The reason for that is that the `Points._indices_view` array is properly adjusted by `shown`, but `Points._view_size_scale` is not, leading to dimensional mismatch in the `Points._view_size` function.

The fix I propose is that the `Points._view_size_scale` array is adjusted in the same way the `Points._indices_view`.

---

---

## Type of change

- [X] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

---

---

# How has this been tested?

- [X] example: all tests pass with my change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

I would like to request some help how to add a test for the desired behavior :) 
Edit: Thanks for the help!

### CODE REVIEW

**Comment by brisvag** [comment]
Hey @mstabrin, welcome :)! Thanks for the PR, and nice catch for the error! For the test, I would suggest to add a new test in [this file](https://github.com/napari/napari/blob/main/napari/layers/points/_tests/test_points.py) to test pretty much the code you posted above :)

**Comment by mstabrin** [comment]
@brisvag Thank you very much for pointing me to the correct file :)

I added a test checking for the corresponding values and if they match the expected behavior.
I adopted the style of the other tests, i.e., testing multiple setups within the same function.

If you need more information / contribution for a merge, please let me know :)

**Review by brisvag — APPROVED** [review]
Great, looks good to me :) Let's see what CI thinks!

**Comment by mstabrin** [comment]
@brisvag Thanks for approving the change :) It looks like I needed to merge the update the branch before it can be merged and a new run of tests is requiered? I remember that the `macos-lastest` test failed, but it did not look like it was related to my changes: https://github.com/napari/napari/runs/6935207582?check_suite_focus=true ?

**Comment by mstabrin** [comment]
@brisvag The main branch is updated faster than the CI is executed :D Do you think we can do something to make the 2 failing tests pass as well?

**Comment by Czaki** [comment]
for MacOS test merge main in this branch. It is fixed in #4707.

**Comment by mstabrin** [comment]
@Czaki Thank you for the information :) I merged again with the main branch.

**Comment by mstabrin** [comment]
@Czaki The Mac issue seems to be resolved :) Thank you! I am not sure why the create package is failing though :/

**Comment by Czaki** [comment]
This fail is also present on main (I have opened issue for this #4714). Lets wait what our conda experts find. 

This is not something blocking for this PR.

**Comment by brisvag** [comment]
Indeed, I think we can just ignore that and go ahead and merge. Thanks @mstabrin!

**Pull request merged**
