### PR TITLE
Multiscale slicing extends beyond shape

### PR DESCRIPTION
**Pull request by perlman**
# Description

This is a tiny fix to prevent multiscale from reading the extents of the data array.

`self.corner_pixels[1]` is set to `array.shape` via `level_shapes`. Adding`1` causes the slicing to extend beyond the array bounds, e.g., if `a.shape=(200,200)`, napari will slice into it as `a[0:201,0:201]`. While slicing beyond bounds is a harmless operation with `numpy`, where the slices are effectively bounded by the array, it causes an exception in tensorstore.

```
import napari
import numpy as np
import tensorstore as ts

multiscale_ts = [
ts.array(np.full(shape=[2, 400, 600], fill_value=200, dtype=np.uint8)),
ts.array(np.full(shape=[2, 200, 300], fill_value=100, dtype=np.uint8))]

napari.view_image(multiscale_ts, multiscale=True)
napari.run()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eric/czi/napari/napari/view_layers.py", line 134, in view_image
    return _make_viewer_then('add_image', args, kwargs)
  File "/Users/eric/czi/napari/napari/view_layers.py", line 119, in _make_viewer_then
    method(*args, **kwargs)
  File "/Users/eric/czi/napari/napari/components/viewer_model.py", line 725, in add_image
    layer = Image(data, **kwargs)
  File "/Users/eric/czi/napari/napari/layers/image/image.py", line 332, in __init__
    self._update_dims()
  File "/Users/eric/czi/napari/napari/layers/base/base.py", line 641, in _update_dims
    self.refresh()
  File "/Users/eric/czi/napari/napari/layers/base/base.py", line 1109, in refresh
    self.set_view_slice()
  File "/Users/eric/czi/napari/napari/layers/base/base.py", line 902, in set_view_slice
    self._set_view_slice()
  File "/Users/eric/czi/napari/napari/layers/image/image.py", line 665, in _set_view_slice
    image = self.data[level][tuple(indices)]
IndexError: Computing interval slice for dimension 1: Slice interval [0, 201) is not contained within domain [0, 200)
```
 

(Relatedly, I will file an issue on tensorstore.)

@sofroniewn I've tried to look through the git history to figure out why one is added to the corner. Do you recall why this was done? I'm worried that I'm missing something obvious...

## Type of change

- [X] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
@perlman looking at the [relevant part in the PR](https://github.com/napari/napari/pull/1673/files#diff-9e4cd2702cfbb10e85a517ed53426c08d163353b58aab0e13609b4375c1e9780), it looks like an np.clip that was keeping things in check was removed. I'd say this is a simple off by one error, not something intentional.

But anyway, tensorstore is actually in our test requirements, so would you like to add your reproducer as a test? ;) Possibly the simplest way is to add that example to `layer_test_data` in `napari/_tests/utils.py`. (But check that this makes tests fail in the main branch.) A lighter-touch way is to add a single test to `napari/_tests/test_viewer.py`.

**Comment by sofroniewn** [comment]
The `+1` could be a left over from a time it might have been needed. It looks like we've got a couple more test fails that usual here in this PR. I'm going to try rerunning again, and they might clear up - but otherwise @perlman can you take a look at them again to make sure there isn't anything unexpected happening. thanks!!

**Comment by perlman** [comment]
Thanks for rerunning the tests.

`ubuntu-18.04 3.8 async-pyqt-py38-linux` breaks on the use of a tensorstore array in the test images. (`test_view[Image-data4-2]`).  I'll dig into this now.

 `macos-latest 3.8 pyqt` has a timeout in `test_z_order_image_points_after_ndisplay` which seems completely unrelated to this PR.

`windows-latest 3.8` blows up in `test_octree_import` in a way that I don't understand:
```
WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1090x661+192+124 (frame: 1106x700+184+93) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1028x661+192+124 (frame: 1044x700+184+93) margins: 8, 31, 8, 8 minimum size: 608x555 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=624,594 maxtrack=0,0)
```

**Comment by sofroniewn** [comment]
> ubuntu-18.04 3.8 async-pyqt-py38-linux breaks on the use of a tensorstore array in the test images. (test_view[Image-data4-2]). I'll dig into this now.

Thanks

> macos-latest 3.8 pyqt has a timeout in test_z_order_image_points_after_ndisplay which seems completely unrelated to this PR.

Yes, that one is failing in other PRs right now.

> windows-latest 3.8 blows up in test_octree_import in a way that I don't understand:

Unfortunately that fails does seem specific to this PR.

Can you update from main too - there might be some other recent PRs that could help too

**Comment by perlman** [comment]
There's definitely a codepath with a tenorstore array & async which results in ImageVisual._data being None.
This is now a separate issue from which this PR was created to address.  ;-)

So far, this has been a great deep dive in the hierarchy of image classes & async hooks. I imagine I'll figure it out shortly.

**Comment by perlman** [comment]
I still haven't quite figured out exactly how async and tensorstore are clashing. 2D viewing is fine; it's the switch to a 3D visual.

I do have a simplified test case now, and suspect it's time to start stepping through the visual code to figure out what's different.

```
import os
os.environ["NAPARI_ASYNC"] = "1"

import napari
import numpy as np
import tensorstore as ts

# This works:
#x = np.full(shape=[20,20,20], fill_value=200, dtype=np.uint8)
# This doesn't:
x = ts.array(np.full(shape=[20,20], fill_value=200, dtype=np.uint8))
viewer = napari.view_image(x, contrast_limits=[0,255])
viewer.dims.ndisplay = 3

napari.run()
```

```
Traceback (most recent call last):
  File "/Users/eric/czi/napari/ts_dim_bug.py", line 13, in <module>
    viewer.dims.ndisplay = 3
  File "/Users/eric/czi/napari/napari/utils/events/evented_model.py", line 151, in __setattr__
    getattr(self.events, name)(value=after)  # emit event
  File "/Users/eric/czi/napari/napari/utils/events/event.py", line 599, in __call__
    self._invoke_callback(cb, event)
  File "/Users/eric/czi/napari/napari/utils/events/event.py", line 631, in _invoke_callback
    _handle_exception(
  File "/Users/eric/czi/napari/napari/utils/events/event.py", line 620, in _invoke_callback
    cb(event)
  File "/Users/eric/czi/napari/napari/_vispy/camera.py", line 139, in _on_ndisplay_change
    self._view.camera = self._3D_camera
  File "/Users/eric/czi/vispy/vispy/util/frozen.py", line 17, in __setattr__
    object.__setattr__(self, key, value)
  File "/Users/eric/czi/vispy/vispy/scene/widgets/viewbox.py", line 111, in camera
    cam.view_changed()
  File "/Users/eric/czi/vispy/vispy/scene/cameras/base_camera.py", line 432, in view_changed
    self.set_range(*args)
  File "/Users/eric/czi/vispy/vispy/scene/cameras/base_camera.py", line 279, in set_range
    bounds = self._viewbox.get_scene_bounds()
  File "/Users/eric/czi/vispy/vispy/scene/widgets/viewbox.py", line 150, in get_scene_bounds
    b = ob.bounds(axis)
  File "/Users/eric/czi/vispy/vispy/visuals/visual.py", line 253, in bounds
    self._vshare.bounds[axis] = self._compute_bounds(axis, view)
  File "/Users/eric/czi/napari/napari/_vispy/vendored/image.py", line 519, in _compute_bounds
    return (0, self.size[axis])
  File "/Users/eric/czi/napari/napari/_vispy/vendored/image.py", line 382, in size
    return self._data.shape[:2][::-1]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by jni** [comment]
@perlman in the interest of moving this PR forward, do you want to either make a specific test, or maybe manually skip that test for the tensorstore data? The async investigation is valuable but can probably come after fixing the main issue. =)

**Comment by perlman** [comment]
Good idea, @jni. The tensorstore tests are now skipped when using async.

I love pytest. :)

I'll tackle async+tensorstore in a separate PR or issue.

Edit: Whoops, didn't realize the array was used in places not decorated with `pytest.mark.parametrize`.

**Comment by sofroniewn** [comment]
Looks like it didn't quite work, still getting fails on async

**Comment by perlman** [comment]
It's been a game of whack a mole as I've (unintentionally) learned how the tests & test data interconnect.

**Review by sofroniewn — APPROVED** [review]
All test passing, looks good! Will merge now!! Thanks

**Pull request merged**
