### PR TITLE
Fix `connect_setattr` to handle single arguments better

### LINKED ISSUE #3321: Contrast limits ValueError
## 🐛 Bug

When I adjust the contrast limits on an image layer via the sliders, I receive a `ValueError`

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/opt/miniconda3/envs/napari-test/lib/python3.8/site-packages/napari/utils/events/event_utils.py in _cb(*value=((0.006301976274698973, 0.1730983406305313),))
     44 
     45     def _cb(*value):
---> 46         setattr(ref(), attr, value)
        global setattr = undefined
        global ref = undefined
        global attr = undefined
        value = ((0.006301976274698973, 0.1730983406305313),)
     47 
     48     emitter.connect(_cb)

~/opt/miniconda3/envs/napari-test/lib/python3.8/site-packages/napari/layers/intensity_mixin.py in contrast_limits(self=, contrast_limits=((0.006301976274698973, 0.1730983406305313),))
     74     @contrast_limits.setter
     75     def contrast_limits(self, contrast_limits):
---> 76         validate_2_tuple(contrast_limits)
        global validate_2_tuple = .func at 0x7fe1a54b58b0>
        contrast_limits = ((0.006301976274698973, 0.1730983406305313),)
     77         self._contrast_limits_msg = (
     78             format_float(contrast_limits[0])

~/opt/miniconda3/envs/napari-test/lib/python3.8/site-packages/napari/utils/validators.py in func(obj=((0.006301976274698973, 0.1730983406305313),))
     61             )
     62         if not len(obj) == n:
---> 63             raise ValueError(
        global ValueError = undefined
        global trans._ = >
        global deferred = undefined
        global number = undefined
        global n = undefined
        global obj_len = undefined
        global len = undefined
        obj = ((0.006301976274698973, 0.1730983406305313),)
     64                 trans._(
     65                     "object must have length {number}, got {obj_len}",

ValueError: object must have length 2, got 1
```

## To Reproduce

1. Open napari (0.4.11.rc3)
2. load grayscale image
3. adjust contrast limits from the GUI

## Expected behavior

The clims should be adjusted

## Environment

napari: 0.4.11rc3
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.11 (default, Aug 6 2021, 08:56:27) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.08.1
VisPy: 0.8.1

OpenGL:
- GL version: 2.1 INTEL-14.7.17
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.11rc3
- svg: 0.1.5

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
fixes #3321

the `connect_setattr ` convenience function added in #3217 needed a slight tweak

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]
🚀

**Review by Czaki — APPROVED** [review]
My proposition for an additional test. 

```python
from napari.utils.events.event_utils import connect_setattr, connect_no_arg


def test_weakref_wrapper():

    class Dummy:
        def __init__(self):
            self._count1 = 0
            self.count2 = 0
            self.fun = None

        @property
        def count1(self):
            return self._count1

        @count1.setter
        def count1(self, value):
            if isinstance(value, typing.Sequence):
                self._count1 = len(value)
            else:
                self._count1 = 1

        def set_count2(self, *args):
            self.count2 = len(args)

        def connect(self, fun):
            self.fun = fun

        def disconnect(self, fun):
            self.fun = None


    obj = Dummy()
    connect_setattr(obj, obj, "count1")

    obj.fun(1)
    assert obj.count1 == 1

    obj.fun(1, 2)
    assert obj.count1 == 2

    obj.fun((1, 2, 3))
    assert obj.count1 == 3

    connect_no_arg(obj, obj, "set_count2")
    obj.count2 = 2

    obj.fun(1, 2, 3, 4, 5)
    assert obj.count2 == 0
```

**Review by sofroniewn — APPROVED** [review]
LGTM!

@Czaki if you feel strongly about that test can you make a dedicated PR for it and we can review it there, thanks!!

**Comment by Czaki** [comment]
> @Czaki if you feel strongly about that test can you make a dedicated PR for it and we can review it there, thanks!!

I prefer to have some test which not depends strongly on the whole viewer. Maybe I even will try to add something more detailed.

**Comment by tlambert03** [comment]
> I prefer to have some test which not depends strongly on the whole viewer. Maybe I even will try to add something more detailed.

yep, unit tests are always welcome.  agreed can come later.  Also, the test added here doesn't use the full viewer... just an [image layer and QtBaseImageControls](https://github.com/napari/napari/pull/3324/files#diff-8efbd8b51e3c5d63c31ea03bba498f86a215780a5ad2851421928c9a3669ac29R116-R117)

**Pull request merged**
