### PR TITLE
Labels paintbrush now takes anisotropy into account

### PR DESCRIPTION
**Pull request by jni**
# Description

Before:

Screen Shot 2021-07-01 at 10 00 12 am

After:

Screen Shot 2021-07-01 at 9 56 50 am

### CODE REVIEW

**Comment by jni** [comment]
Sorry for the rush/short notice, but could someone review/approve this? I could really use this with some collaborators tonight, would be great to have in the nightly bundle build...! CC @tlambert03 @sofroniewn

**Review by tlambert03 — APPROVED** [review]
not a part of the code i'm intimately familiar with.  but pulled it, played with it, liked it. :)  all seems good to me!

**Comment by jni** [comment]
Thank you @tlambert03! I'm going to merge now, if anyone encounters any issues please let me know and I can fix/revert. 🙏

**Comment by sofroniewn** [comment]
Just gave it a try and seems good to me too. I guess you only did circle brush, but we're removing square anyway after #2942 anyway, so that's fine

**Pull request merged**
