### PR TITLE
Add event for moving points

### PR DESCRIPTION
**Pull request by DragaDoncila**
# Description
This PR adds a new event for moving points.

The event emits the index and coordinates of the point/s being moved.

@jni has mentioned that perhaps we would want to make this a subset of the data event e.g. 

```python
self.events.data(
    value=self.data,
    type='move',
    idx=index,
    coord=coord
)
```
For now I emit a data event alongside the move event. @sofroniewn I'm curious what you think and whether there's something you'd prefer.

I also wasn't sure where (if anywhere) to add tests for this event.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by sofroniewn** [comment]
I'm not sure yet about the `move` event. Should we also then have `add` / `remove`? Maybe `data` is enough? Would be good to standardize this with shapes too - see #720.

Maybe we could make a comprehensive proposal for object editing and then see what we'll need at the end of all this?

**Comment by DragaDoncila** [comment]
@sofroniewn looking at #720 as well, I definitely see the need for a targeted discussion on events, and standardising them across the board.

> Maybe data is enough?

I don't think this is sufficient without at least adding a specifier to the `data` event e.g. `"move"`, `"add"`, etc, because for `shapes` and `points` (at least), that requires the user to resort to a linear scan of the data to see what's changed.
One advantage of diversifying the `data` event over adding new events is that it would be backwards compatible so that may well be the way forward.

I'd love to look at this in more depth in the coming sprint maybe.

**Comment by sofroniewn** [comment]
> I'd love to look at this in more depth in the coming sprint maybe.

Sorry that this has been sitting here @DragaDoncila, we definitely should do this. Maybe @jni can weigh in here too

**Comment by DragaDoncila** [comment]
> > I'd love to look at this in more depth in the coming sprint maybe.
> 
> Sorry that this has been sitting here @DragaDoncila, we definitely should do this. Maybe @jni can weigh in here too

@sofroniewn probably best to look at this in the context of #2809 - once we have a consensus there we can implement across both layers (Shapes and Points). We could possibly even close this until then?

**Comment by jni** [comment]
As mentioned in #2809, I suggest *just* emitting `.data` as a first step, and *then* emitting `.data(**specifiers)` as a future step — the latter is backwards compatible with the former.

**Comment by DragaDoncila** [comment]
This should be closed as it was superseded by #2992

**Pull request closed without merging**
