### PR TITLE
Support python 3.10

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
run our tests on py3.10 ... only pyqt5's wheels work at the moment (pyside2 puts you back to 5.13, which has some casting issues), so only testing that.

### CODE REVIEW

**Comment by goanpeca** [comment]
`TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer` do we need to some casting @tlambert03 🤔 

```python-traceback

  napari/_qt/_tests/test_qt_notifications.py ..                            [  0%]
  napari/_qt/_tests/test_app.py sF                                         [  0%]
  napari/_qt/_tests/test_plugin_widgets.py .......FFF                      [  0%]
  napari/_qt/_tests/test_prune_qt_connections.py .                         [  0%]
  napari/_qt/_tests/test_qt_notifications.py .F
  
  =================================== FAILURES ===================================
  ___________________________ test_run_outside_ipython ___________________________
  
  qapp = <PySide2.QtWidgets.QApplication(0x55a9a9ba9520) at 0x7f0e431201a0>
  monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f0e1aa0d090>
  
      @slow(30)
      def test_run_outside_ipython(qapp, monkeypatch):
          """Test that we don't incorrectly give ipython the event loop."""
          assert not _ipython_has_eventloop()
  >       v1 = Viewer(show=False)
  
  napari/_qt/_tests/test_app.py:37: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  napari/viewer.py:57: in __init__
      self._window = Window(self, show=show)
  napari/_qt/qt_main_window.py:411: in __init__
      self._qt_window = _QtMainWindow(viewer)
  napari/_qt/qt_main_window.py:76: in __init__
      self.qt_viewer = QtViewer(viewer, show_welcome_screen=True)
  napari/_qt/qt_viewer.py:194: in __init__
      self.dims = QtDims(self.viewer.dims)
  napari/_qt/widgets/qt_dims.py:58: in __init__
      self._update_nsliders()
  napari/_qt/widgets/qt_dims.py:131: in _update_nsliders
      self._create_sliders(self.dims.ndim)
  napari/_qt/widgets/qt_dims.py:185: in _create_sliders
      slider_widget = QtDimSliderWidget(self, dim_axis)
  napari/_qt/widgets/qt_dims_slider.py:90: in __init__
      self._create_play_button_widget()
  napari/_qt/widgets/qt_dims_slider.py:168: in _create_play_button_widget
      self.play_button = QtPlayButton(
  napari/_qt/widgets/qt_dims_slider.py:502: in __init__
      self.popup = QtPopup(self)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <napari._qt.dialogs.qt_modal.QtPopup(0x55a9aaddcb80, name="QtModalPopup") at 0x7f0e1a8fe040>
  parent = <napari._qt.widgets.qt_dims_slider.QtPlayButton(0x55a9aaddc6d0) at 0x7f0e1a8fcd00>
  
      def __init__(self, parent):
          super().__init__(parent)
          self.setObjectName("QtModalPopup")
          self.setModal(False)  # if False, then clicking anywhere else closes it
  >       self.setWindowFlags(Qt.Popup | Qt.FramelessWindowHint)
  E       TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
  
  napari/_qt/dialogs/qt_modal.py:41: TypeError
  __________________________ test_plugin_widgets_menus ___________________________
  
  test_plugin_widgets = None
  make_napari_viewer = <function make_napari_viewer.<locals>.actual_factory at 0x7f0e1a9d0040>
  
      def test_plugin_widgets_menus(test_plugin_widgets, make_napari_viewer):
          """Test the plugin widgets get added to the window menu correctly."""
  >       viewer = make_napari_viewer()
  
  napari/_qt/_tests/test_plugin_widgets.py:84: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  napari/_qt/qt_main_window.py:76: in __init__
      self.qt_viewer = QtViewer(viewer, show_welcome_screen=True)
  napari/_qt/qt_viewer.py:194: in __init__
      self.dims = QtDims(self.viewer.dims)
  napari/_qt/widgets/qt_dims.py:58: in __init__
      self._update_nsliders()
  napari/_qt/widgets/qt_dims.py:131: in _update_nsliders
      self._create_sliders(self.dims.ndim)
  napari/_qt/widgets/qt_dims.py:185: in _create_sliders
      slider_widget = QtDimSliderWidget(self, dim_axis)
  napari/_qt/widgets/qt_dims_slider.py:90: in __init__
      self._create_play_button_widget()
  napari/_qt/widgets/qt_dims_slider.py:168: in _create_play_button_widget
      self.play_button = QtPlayButton(
  napari/_qt/widgets/qt_dims_slider.py:502: in __init__
      self.popup = QtPopup(self)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <napari._qt.dialogs.qt_modal.QtPopup(0x55a9a9cb2520, name="QtModalPopup") at 0x7f0e1aa0bf40>
  parent = <napari._qt.widgets.qt_dims_slider.QtPlayButton(0x55a9a9cb1e90) at 0x7f0e1aaefc80>
  
      def __init__(self, parent):
          super().__init__(parent)
          self.setObjectName("QtModalPopup")
          self.setModal(False)  # if False, then clicking anywhere else closes it
  >       self.setWindowFlags(Qt.Popup | Qt.FramelessWindowHint)
  E       TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
  
  napari/_qt/dialogs/qt_modal.py:41: TypeError
  Error: 1m_______________________ test_notification_display[ERROR] _______________________
  CALL ERROR: Exceptions caught in Qt event loop:
  ________________________________________________________________________________
  TypeError: 'PySide2.QtCore.Qt.Alignment' object cannot be interpreted as an integer
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/tmp/.tox/py310-linux-pyside/lib/python3.10/site-packages/superqt/_eliding_label.py", line 86, in sizeHint
      flags = int(self.alignment() | Qt.TextFlag.TextWordWrap)
  SystemError: <class 'int'> returned a result with an exception set
  ________________________________________________________________________________
```

**Comment by tlambert03** [comment]
Yep, saw that thanks,  working on it

**Comment by tlambert03** [comment]
all set

**Review by goanpeca — APPROVED** [review]
🥳

**Review by sofroniewn — APPROVED** [review]
All tests are passing. Incredible! Love it!!

**Pull request merged**
