### PR TITLE
Mask image from points layer

### LINKED ISSUE #3132: Feature: make mask from points with sizes
## 🚀 Feature
Similar to how we can convert shapes to masks, I'd like to be able to generate masks from a points layer with sizes.  In `skimage` my (probably very crappy) implementation is something like this:

(where the last column of `blobs` is the `size` parameter in the points layer)

```py
def blobs2mask(blobs, shape, grow=2) -> np.ndarray:
    """Create mask for `blobs` (coordinates, with radii) with `shape`."""
    from skimage import draw

    mask = np.zeros(shape, bool)
    for *c, r in blobs:
        coords = draw.disk(c[-2:], r + grow, shape=shape[-2:])
        if len(c) == 3:
            mask[c[0]][coords] = True
        else:
            mask[coords] = True

    return mask
```

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description
Work in progress to generate one binary mask image from a Points layer.

This is mostly working and should work with n-dimensional data, though I've only tested on 2D and 3D data. Here's an example of some points drawn on the 2D binary blobs data.

Screen Shot 2021-08-12 at 12 05 10 PM

The rasterized blobs are a little smaller than the vispy points, which doesn't surprise me because I'm still a little confused about how `Points.size` interacts with `Layer.scale`.

Also note that the blobs are not as spherical as they could because the implementation I'm currently using is handling the continuous nature of the point coordinates. We could instead lock each point to an exact pixel, in which case the blobs would be as spherical as possible for a given resolution, but then they will be slightly offset, which seems worse.

It's easy enough to handle layer transforms on the point coordinates, but I'm unsure how to transform the spheres in the mask image. Should they always be spherical in the data? Or should they sometimes be elliptical if the source image they were defined from has an anisotropic scaling (e.g. `scale=(2,1)) and are expected to be loaded back into napari as an image layer  with the same anisotropic scaling (so that they are rendered as spherical by vispy). If that doesn't make much sense, I'm happy to jump on a video chat to demonstrate.
@tlambert03 : it would be useful to understand the use cases better here. E.g. is it the case that there is typically a reference image we could use to define how the mask values will be sampled?

## Type of change
- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
Closes #3132 

# How has this been tested?
- [x] example: newly added tests cover the main use cases

This is a strict API addition and the method should have no side-effects, so it shouldn't break anything else. I also played around manually with this in napari, mostly with success (except for the blob scaling mentioned above).

I also wrote a quick timing benchmark. Here are the results on my 2020 Intel Macbook Pro:

```
[ 50.00%] ··· ============ ========== ========== ========== ========== ========== ========== =========== =========== =========== =========== =========== ===========
              --                                                                    num_pixels / point_size                                                         
              ------------ -----------------------------------------------------------------------------------------------------------------------------------------
               num_points   128 / 10   128 / 20   256 / 10   256 / 20   512 / 10   512 / 20   1024 / 10   1024 / 20   2048 / 10   2048 / 20   4096 / 10   4096 / 20 
              ============ ========== ========== ========== ========== ========== ========== =========== =========== =========== =========== =========== ===========
                   16       2.31±0ms   2.41±0ms   2.34±0ms   3.26±0ms   3.07±0ms   3.02±0ms    2.65±0ms    3.18±0ms    3.02±0ms    3.77±0ms    5.68±0ms    6.39±0ms 
                   64       6.16±0ms   7.18±0ms   7.58±0ms   7.66±0ms   7.96±0ms   8.29±0ms    7.25±0ms    8.93±0ms    8.41±0ms    10.8±0ms    10.3±0ms    12.8±0ms 
                  256       23.0±0ms   26.3±0ms   23.1±0ms   28.3±0ms   25.1±0ms   29.3±0ms    27.3±0ms    32.1±0ms    31.4±0ms    36.4±0ms    32.9±0ms    43.5±0ms 
                  1024      96.6±0ms   112±0ms    91.4±0ms   114±0ms    95.3±0ms   109±0ms     94.1±0ms    118±0ms     112±0ms     132±0ms     121±0ms     155±0ms  
                  4096      363±0ms    418±0ms    361±0ms    435±0ms    373±0ms    432±0ms     366±0ms     434±0ms     388±0ms     444±0ms     432±0ms     512±0ms  
                 16384      1.40±0s    1.68±0s    1.41±0s    1.81±0s    1.52±0s    1.70±0s     1.45±0s     1.72±0s     1.48±0s     1.72±0s     1.58±0s     2.15±0s  
                 65536      6.62±0s    7.30±0s    6.39±0s    7.49±0s    6.70±0s    7.87±0s     5.87±0s     6.89±0s     5.72±0s     7.98±0s     7.04±0s     7.27±0s  
              ============ ========== ========== ========== ========== ========== ========== =========== =========== =========== =========== =========== ===========
```

When we have less than 10000 points, the current implementation takes less than about 0.5s for a 2D 4096x4096 pixel with point sizes of 20. For more points, it can take just over a second or maybe several seconds. But overall, this seems acceptable.

I also plan to write and run a benchmark for 3D points (and maybe even 4D), and will probably also measure memory.

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by andy-sweet** [comment]
Actually, after some testing, I'm not sure the transform components are being handled correctly. But feedback on whether this general direction looks good would still be appreciated.

**Comment by andy-sweet** [comment]
Those transform issues should be fixed now, though I'm still unsure how to properly scale the radii of the rasterized blobs.

**Comment by tlambert03** [comment]
this is fantastic.  So thorough and impressive :)
Haven't tried it out yet, but the code looks like what I was wanting.   will play with it directly soon.

> Also note that the blobs are not as spherical as they could because the implementation I'm currently using is handling the continuous nature of the point coordinates.

personally, I'm not that concerned about this because – unfortunately – most real-world use cases of this for me would likely be anisotropic anyway: the z-radius would be larger than the lateral radius.  I definitely don't think we need to implement the option for anisotropic masks at first... that's just to say that imperfect spheres are fine :)

> @tlambert03 : it would be useful to understand the use cases better here. E.g. is it the case that there is typically a reference image we could use to define how the mask values will be sampled?

Yeah: for me a typical use case would be to use blob detection to find coordinates/radii of spots in an image, then make a mask that i can use to go back to the original image and measure something (intensities, etc).  

so, take a raw image like this

KIC16_1_30min_005_003

detect points (ignore the lines, but you can see the points layer in there as small circles)

KIC16_1_30min_005_002

... and then convert points to mask and go back to the original image to continue.  For certain samples, I find this gives me a more accurate mask than just thresholding the spots to begin with.

**Review by alisterburt — COMMENTED** [review]
Looking good @andy-sweet !! 

> It's easy enough to handle layer transforms on the point coordinates, but I'm unsure how to transform the spheres in the mask image. Should they always be spherical in the data? Or should they sometimes be elliptical if the source image they were defined from has an anisotropic scaling (e.g. `scale=(2,1)) and are expected to be loaded back into napari as an image layer with the same anisotropic scaling (so that they are rendered as spherical by vispy).

I think I would expect spheres in this case, I'm sure someone will come along expecting the opposite though? 🤷🏼‍♂️ 

Just want to highlight that inferring things based on `Points.size` could cause issues because of problems described in #2894 (more low level details at  vispy/vispy#2078)

**Comment by andy-sweet** [comment]
I cleaned this up, added more tests, and also added some 3D benchmarks, so I think this is ready for review now.

I added an `isotropic_output` argument that controls whether the balls in the output mask will be isotropic (in the data/pixel space), which defaults to be `True` because I think that covers the expected use cases from @alisterburt and @tlambert03. In general, defining the radii scaling is complex, so I tried to add a lot of implementation comments and tests to cover that behavior. In order to simplify things a little, I'd also be OK with removing this argument and always using `True`.

The biggest open question I have is how the user should specify the output mask shape and space.

This is currently controlled by the `shape: tuple` and `data_to_world: Affine` arguments.

The `shape` argument is consistent with `Shapes.to_mask`. I decided not to default to a shape defined by `Layer._extent_data` because we also need to take into account the scaled radii of the output points to understand the true extent of the rendered balls.

The `data_to_world` affine transform defines the data-to-world transform for the output mask image. By default it is the same as `Points._data_to_world`, which effectively means that all the transform stuff cancels. However, there's no obvious way for a user to set this unless they construct this from an `Affine` or `CompositeAffine` because `_data_to_world` is a hidden property of `Layer`.

I think a better alternative might be replace `shape` and `data_to_world` with `ref_image: Image`, which I think should cover most of the real usages (i.e. the points are annotations on an image layer in napari), and makes the API very simple (e.g. `points_mask = points_layer.to_mask(image_layer)`. However, then Image becomes a dependency of Points, which is not ideal.

Alternatively we can make the arguments `shape, scale, translate, rotate, shear, affine`, which is consistent with `Layer` construction and doesn't add any new dependencies. But it likely makes common usage more verbose (e.g. `points_mask = points_layer.to_mask(shape=image_layer.data.shape, scale=image_layer.scale, translate=image_layer.translate, ...)`.

**Comment by andy-sweet** [comment]
And here are the benchmark results on my Intel Macbook Pro (2020).

```
(napari-dev) ➜  napari git:(3132-mask-from-points) ✗ asv dev -b PointsToMaskSuite       
· No executable found for python 3.7
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Benchmarking existing-py_Users_asweet_software_miniconda3_envs_napari-dev_bin_python
[ 50.00%] ··· benchmark_points_layer.PointsToMaskSuite.time_to_mask                                                                                                                                                                                                                                                                                                     ok
[ 50.00%] ··· ============ ================= ========== ==========
              --                                   point_size     
              ------------------------------ ---------------------
               num_points      mask_shape        5          10    
              ============ ================= ========== ==========
                   64          (256, 256)     7.69±0ms   7.10±0ms 
                   64          (512, 512)     7.28±0ms   12.5±0ms 
                   64         (1024, 1024)    8.99±0ms   8.22±0ms 
                   64         (2048, 2048)    15.5±0ms   12.9±0ms 
                   64       (128, 128, 128)   18.7±0ms   16.0±0ms 
                   64       (256, 256, 256)   30.5±0ms   18.9±0ms 
                   64       (512, 512, 512)   13.4±0ms   21.1±0ms 
                  256          (256, 256)     25.2±0ms   31.2±0ms 
                  256          (512, 512)     30.0±0ms   27.8±0ms 
                  256         (1024, 1024)    27.8±0ms   61.6±0ms 
                  256         (2048, 2048)    54.7±0ms   50.6±0ms 
                  256       (128, 128, 128)   42.6±0ms   72.7±0ms 
                  256       (256, 256, 256)   46.3±0ms   70.4±0ms 
                  256       (512, 512, 512)   48.5±0ms   77.8±0ms 
                  1024         (256, 256)     112±0ms    110±0ms  
                  1024         (512, 512)     112±0ms    119±0ms  
                  1024        (1024, 1024)    113±0ms    119±0ms  
                  1024        (2048, 2048)    125±0ms    118±0ms  
                  1024      (128, 128, 128)   148±0ms    219±0ms  
                  1024      (256, 256, 256)   166±0ms    241±0ms  
                  1024      (512, 512, 512)   216±0ms    282±0ms  
                  4096         (256, 256)     414±0ms    514±0ms  
                  4096         (512, 512)     373±0ms    424±0ms  
                  4096        (1024, 1024)    378±0ms    411±0ms  
                  4096        (2048, 2048)    395±0ms    423±0ms  
                  4096      (128, 128, 128)   517±0ms    812±0ms  
                  4096      (256, 256, 256)   522±0ms    817±0ms  
                  4096      (512, 512, 512)   586±0ms    899±0ms  
                 16384         (256, 256)     1.44±0s    1.50±0s  
                 16384         (512, 512)     1.46±0s    1.51±0s  
                 16384        (1024, 1024)    1.44±0s    1.55±0s  
                 16384        (2048, 2048)    1.39±0s    1.58±0s  
                 16384      (128, 128, 128)   1.93±0s    3.62±0s  
                 16384      (256, 256, 256)   2.57±0s    3.32±0s  
                 16384      (512, 512, 512)   2.57±0s    3.88±0s  
              ============ ================= ========== ==========
```

I made the benchmarks a little easier to make them run quicker, but they include 3D results now. The current implementation's time complexity mostly scales with the number of the points, and less with the size of the points and the image. Would also be good to try this out on some real data.

**Comment by andy-sweet** [comment]
Also, I deliberately ignored the option to control which dimensions should inflate, extrude, or collapse the balls because my sense is that is worth adding when it's needed. I think a common use case for that will be when one dimension in an image corresponds to time, in which case we should likely either extrude (if the points are stationary) or collapse (if the points move) the balls.

**Review by sofroniewn — APPROVED** [review]
This looks great to me. I'm fine with the current API - agreed things like excluding / projecting along some dims can come later in a follow up PR

> The rasterized blobs are a little smaller than the vispy points, which doesn't surprise me because I'm still a little confused about how Points.size interacts with Layer.scale.

I'm still seeing this too - i dug in a little more and it looks like the points themselves aren't rendering right, they are all too big! My hunch is by a factor of `sqrt(2)`. I.e make a point of size 10 and it's actually 14 pixels when overlaid on an image, could be a vispy bug / inconsistency. Maybe we make an issue now though and look into this in a different PR

**Comment by andy-sweet** [comment]
> I'm still seeing this too - i dug in a little more and it looks like the points themselves aren't rendering right, they are all too big!

Yep, see #2894 for some discussion around that. I don't feel like vispy is guaranteeing that size should correspond to the diameter of the disc marker, but we may still want to work around it.

**Comment by sofroniewn** [comment]
> Yep, see #2894 for some discussion around that. I don't feel like vispy is guaranteeing that size should correspond to the diameter of the disc marker, but we may still want to work around it.

Ok nice, I completely missed that issue! Let's get this in then. I'll wait till tomorrow morning in case anyone has any additional comments and if not will then merge. Great work here @andy-sweet!!

**Pull request merged**
