### PR TITLE
Use pytest-pretty for better log readability 

### PR DESCRIPTION
**Pull request by Czaki**
# Description

To see how this pytest plugin improves readability,, please take a look at the project readme. 
https://github.com/samuelcolvin/pytest-pretty/

## Type of change

- [x] Maintenance 

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by brisvag** [comment]
Using it locally for a while, really nice. Is it normal that the output is not as colored as locally in the CI? https://github.com/napari/napari/actions/runs/4068523779/jobs/7007170050#step:8:580 versus https://github.com/samuelcolvin/pytest-pretty/#prettier-summary-of-a-test-run

**Comment by Czaki** [comment]
> Using it locally for a while, really nice. Is it normal that the output is not as colored as locally in the CI? [napari/napari/actions/runs/4068523779/jobs/7007170050#step:8:580](https://github.com/napari/napari/actions/runs/4068523779/jobs/7007170050#step:8:580) versus [samuelcolvin/pytest-pretty#prettier-summary-of-a-test-run](https://github.com/samuelcolvin/pytest-pretty/#prettier-summary-of-a-test-run)

I don't know. It may be worth asking the author about it in the issue. Maybe the detection of coloring ability fails.

But also notice that coloring breaks raw log view:
obraz

**Comment by aganders3** [comment]
It's using rich for output, which will accept [`FORCE_COLOR`](https://rich.readthedocs.io/en/stable/console.html#environment-variables) environment variable to get color output in CI. I'm not sure if this variable might affect other programs, but without it there may need to be a change in `pytest-pretty`.

Also for viewing raw logs this extension seems to work well to interpret color formatting:
https://github.com/laurent22/github-actions-logs-extension

**Comment by Czaki** [comment]
> Also for viewing raw logs this extension seems to work well to interpret color formatting:
> [laurent22/github-actions-logs-extension](https://github.com/laurent22/github-actions-logs-extension)

Also cating/less in terminal works. But this still does not solve the problem that when you download log to analyze them it is messed up by color codes and you need to clean such files first.

**Comment by brisvag** [comment]
> It's using rich for output, which will accept [`FORCE_COLOR`](https://rich.readthedocs.io/en/stable/console.html#environment-variables) environment variable to get color output in CI

shall we try that in this PR and see how that goes?

**Comment by Czaki** [comment]
@brisvag As you wish https://github.com/napari/napari/actions/runs/4082925205/jobs/7037838500#step:8:584

**Review by brisvag — APPROVED** [review]
Nice! Easier to navigate IMO; let's hear from others though, this is still yet another small dependency :P

**Comment by psobolewskiPhD** [comment]
So comparing that link to
https://github.com/napari/napari/actions/runs/4085681197/jobs/7043972756
The top part of the tox stuff looks better for sure, easier to parse with the color/syntax highlighting. The meat and potatoes of tests running (the dots) is the same. Then on the end the summary is different:
Live: https://github.com/napari/napari/actions/runs/4085681197/jobs/7043972756#step:8:634

The new way is definitely more brief, which when tests are passing is probably fine? Ironically it may be better to make some test fail to asses? 😂

**Review by goanpeca — APPROVED** [review]
Love this change  🚀

**Comment by Czaki** [comment]
start 24h clock

**Pull request merged**
