### PR TITLE
move all requirements to extras

### LINKED ISSUE #1602: Add testing optional extras to napari setup.cfg
## 🚀 Feature

When testing a release candidate, I always have to install extras from the repo, including testing extras. It would be excellent to be able to install them with `pip install napari[all,testing]`.

The relevant lines are here:

https://github.com/napari/napari/blob/42d26d66a82fbd00b9db3515c0d10e16f76a284f/setup.cfg#L70-L78

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
closes #1602 by adding testing (and 'dev') to extras.
now you can do any of the following:

```
pip install napari[testing]  # napari and testing tools
pip install napari[all,testing]  # napari and testing tools with default backend
pip install napari[dev]  # both of the above with additional dev tools like pre-commit
```

requirements.txt is just a pointer to `pip install -e .[dev]`

I'm not 100% sure how this is going to work with cirrus caching... but since it looks like we were only caching the test requirements anyway, we can just remove that if it's an issue.

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Love this, thanks @tlambert03! Love that `pip install -e . [dev]` works too.

I was just looking at our [contributing guide](https://github.com/napari/napari/blob/9a9b0fc815521d297bdfb95063045cd4005ac856/docs/source/developers/CONTRIBUTING.md#setting-up-a-development-installation). That still recommends `pip install -r requirements.txt` which is basically the same (up to the difference described in that great post you linked), so that doesn't need to change, but I'm just making sure.

I'm curious about why you decided to move docs to `docs/requirements.txt`. One the one hand I like it because it keeps that stuff separate but on the other if people might need to build docs locally would they need it too? I guess the fact that I never build docs locally means I probably don't need that stuff so readily.

Anyway, all this looks great to me! Can merge promptly

**Comment by tlambert03** [comment]
sorry didn't respond before merge :)

> Love this, thanks @tlambert03! Love that `pip install -e . [dev]` works too.

yeah that's nifty

> I was just looking at our [contributing guide](https://github.com/napari/napari/blob/9a9b0fc815521d297bdfb95063045cd4005ac856/docs/source/developers/CONTRIBUTING.md#setting-up-a-development-installation). That still recommends `pip install -r requirements.txt` which is basically the same (up to the difference described in that great post you linked), so that doesn't need to change, but I'm just making sure.

yeah, don't have strong feelings on that.  I feel like `pip install -r requirements.txt` is so ingrained, that I left it in as an "alias".  Some virtualenv setups also take advantage of requirements.txt, so i do think it should stay

> I'm curious about why you decided to move docs to `docs/requirements.txt`. One the one hand I like it because it keeps that stuff separate but on the other if people might need to build docs locally would they need it too?

that was sort of convention as well.  I've often seen docs requirements go there (and even though we're not using it, it's a requirement for things like readthedocs...) So it seemed like the right spot.  But it's true, anyone wanting to build docs would need to do `pip install -r docs/requirements.txt` instead of `pip install -r requirements/docs.txt`.  I refrained from adding `pip install napari[docs]` since we don't distribute the docs source in the sdist... so that actually wouldn't work in some cases

**Comment by sofroniewn** [comment]
Thanks for the answer, and sorry for not waiting, maybe I was a little trigger happy now! Just getting going for the day :-)

**Comment by tlambert03** [comment]
pull the triggers!! :)

**Pull request merged**
