### PR TITLE
consolidate npe2 stuff into one module

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
As we've developed npe2, we've scattered a number of npe2 adapters with `try import npe2` across many files.  This PR consolidates those into a single file that is safe to import.  It doesn't try to change any behavior (with the exception of fixing one bug in the dock widget implementation).

This will make it a lot easier to see what's being covered by tests and what's not

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by nclack — COMMENTED** [review]
I really like how pulling things into a module cleaned things up.  I left some comments.  I'll go through it again and do some testing in the morning.

**Comment by goanpeca** [comment]
Love the clean up @tlambert03 !

**Comment by tlambert03** [comment]
> I left some comments.

hmm... I'm not seeing any comments @nclack

**Comment by nclack** [comment]
> I'm not seeing any comments

oof.  I really liked how the code cleaned up and the use of the decorator. The moved functions don't have really consistent names but that's a nit.

**Comment by tlambert03** [comment]
> The moved functions don't have really consistent names but that's a nit.

yeah, I waffled with whether the function or the module should have npe2 in it ... :joy: what would you think about removing npe2 from all the function names, but using them internally from the module?

eg:

instead of 
```py
from ..plugins._npe2 import npe2_widget_iterator
npe2_widget_iterator()
```

we do 

```py
from ..plugins import _npe2
_npe2.widget_iterator()
```

**Comment by tlambert03** [comment]
> what would you think about removing npe2 from all the function names, but using them internally from the module?

i did this "optimistically"... tell me if you disagree

**Comment by nclack** [comment]
> removing npe2 from all the function names, but using them internally from the module

I love it. You read my mind.

**Review by nclack — APPROVED** [review]

**Pull request merged**
