### PR TITLE
Allow resizing left dock widgets

### PR DESCRIPTION
**Pull request by brisvag**
# Description
This PR stemmed from #4195 and includes some things that are now removed from there. Specifically, it removes constraints from `qss` and `qt_viewer` so that the left dock widgets can now be resized.

I think of this a straight up bug fix, but I know that @alisterburt didn't like the look of the `QSplitter` that now appears between the canvas and the layer controls. We can add some changes to the style sheets to make that prettier, so please suggest changes, as I'm not at all familiar with how style sheets work.

Worth noting is that this currently causes the layer controls to take up more space than necessary, while the layerlist is squished at the bottom. Ther emust be some other size setting lost in some oher file, but I don't know how to even start looking for it :P

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @brisvag thanks for working on this.

Regarding your comments, here is my 2 cents:

>Worth noting is that this currently causes the layer controls to take up more space than necessary, while the layerlist is squished at the bottom. There must be some other size setting lost in some other file, but I don't know how to even start looking for it :P

I think it looks ok, we could simply make sure the control layer is smaller by default when we start napari, so that it looks like this:


Screen Shot 2022-04-12 at 2 24 12 PM
(that is like a 40/60 ratio between control layer and layer list)

>I think of this a straight up bug fix, but I know that @alisterburt didn't like the look of the QSplitter that now appears between the canvas and the layer controls. We can add some changes to the style sheets to make that prettier, so please suggest changes, as I'm not at all familiar with how style sheets work.

You could add something like:

`_qt/qt_resources/styles/02_custom.qss`
```css

/* ------------- Window separator --------- */

QMainWindow::separator {
  width: 4px;
  background: transparent;
  border: none;
}    

QMainWindow::separator:hover {
    background: {{ foreground }};
}

QMainWindow::separator:horizontal {
    image: url(":/themes/{{ name }}/horizontal_separator.svg");
}

QMainWindow::separator:vertical {
    image: url(":/themes/{{ name }}/vertical_separator.svg");
}
```

I uploaded the test svg I used.
horizontal_separator

---

I think we really need some help from @isabela-pf to get this right, but that can give you some pointers in the meantime

-----

It looks like this now with that QSS

napari

---

Also maybe add a screenshot to the PR description once you get something going :)

**Comment by brisvag** [comment]
Love it! @alisterburt , what are your thoughts? Looking forward to seeing @isabela-pf 's magic especially :)

**Comment by sofroniewn** [comment]
@brisvag I just gave this a try - I don't mind it. Here is what it looks like for me

image

I agree the splitter could be nicer though, and maybe we go with the version from @goanpeca unless @isabela-pf has been working on something.

One question, is this blocking for #4195? Which I was quite excited about. It would be nice to figure out a way to press on with that one too

**Comment by jni** [comment]
I really like @goanpeca's designs, would happily merge if you add them to this PR @brisvag!

**Comment by brisvag** [comment]
Ok, will merge @goanpeca 's changes. However, I think we should use the same separator for vertical, just rotated 90%. Is there a way to do this in code, to avoid adding a rotated version of the svg?

I found [this stuff online](https://stackoverflow.com/questions/33186431/rotate-svg-path-using-css), but I coudln't make it work for `qss` so far. Suggestions @goanpeca @isabela-pf ?

**Comment by brisvag** [comment]
If I understand correctly, `transform` is not part of the subset of `css` that `qss` implements. So, I have made a rotated version of the separator and added it to the repo. This is mergeable, I think!

**Comment by brisvag** [comment]
Actually, one more thing missing:

> I think it looks ok, we could simply make sure the control layer is smaller by default when we start napari, so that it looks like this:
> 
> Screen Shot 2022-04-12 at 2 24 12 PM
>
> (that is like a 40/60 ratio between control layer and layer list)

Again, I know nothing of `qss`, so how does one do this? :P

**Comment by goanpeca** [comment]
Hi @brisvag I will look into making the top controls panel smaller by default and paste the suggestion here. Thanks!

Please use these versions of the files :)

vertical_separator

horizontal_separator

**Comment by goanpeca** [comment]
@brisvag you could add this snippet to the end of the `Viewer.__init__` on the `_qt/qt_main_window.py` file
```python

        if show:
            self.show()
            # Ensure the controls dock uses the minimum height
            self._qt_window.resizeDocks(
                [
                    self._qt_viewer.dockLayerControls,
                    self._qt_viewer.dockLayerList,
                ],
                [self._qt_viewer.dockLayerControls.minimumHeight(), 10000],
                Qt.Vertical,
            )
```

This is temporary, as we still would like to preserve the geometry of the main window if we change it. Thoughts @jni, @sofroniewn ?

**Comment by jni** [comment]
I don't understand the question @goanpeca! Can you draw me a picture? :sweat_smile:

**Comment by brisvag** [comment]
Done! Here's how it looks now:


https://user-images.githubusercontent.com/23482191/164676324-18e2a6e6-4efb-4d9e-b541-d2135562bfdd.mp4

**Review by jni — APPROVED** [review]
:heart:

**Comment by goanpeca** [comment]
Looks great @brisvag ! 

---

> I don't understand the question @goanpeca! Can you draw me a picture? 😅

@jni I mean that if someone arbitrarily changes the layout and size of docks (manually) we would want to preserve that on subsequent restarts, right?

The code snippet I suggested will always try to shrink the controls dock to its minimum height on every restart which would override any manually set geometry of the docks. So maybe we could only do this resize on first napari launch (we have a setting for `first_run`).

Still something we could look into later. Want to have the form layout PR moving :)

**Review by sofroniewn — APPROVED** [review]
@brisvag do these svg's need to be added to the git-lfs @brisvag? (cc @jni)

Looks great otherwise and is good to go! We can press on with further refinements in the form PR. Thanks

**Comment by brisvag** [comment]
AFAIK svgs don't need to be in lfs, especially these tiny ones that take less than a kb.

**Comment by sofroniewn** [comment]
> AFAIK svgs don't need to be in lfs, especially these tiny ones that take less than a kb.

Lol - good point, thanks!!

**Comment by brisvag** [comment]
Remonder for when this is merged: check out [this list of issues](https://github.com/napari/napari/pull/4195#issuecomment-1084340953), cause some of them might be closable!

**Comment by alisterburt** [comment]
merging now because it looks so good and we've got multiple approvals! 🥳

**Comment by isabela-pf** [comment]
I don't know how I missed being tagged this many times, but I clearly did. Sorry about that. 

Is there an existing issue you'd like me to follow up on icons for the resizing area, or can I make one?

**Comment by brisvag** [comment]
No worries! Feel free to open one :)

**Comment by jni** [comment]
@sofroniewn Btw, we decided that files needed to run napari (such as the logo) would never be in lfs regardless of size, only docs files. Otherwise you would end up with a broken napari if you git clone and don't have lfs installed.

**Pull request merged**
