### PR TITLE
Add stretch to vertical dock widgets

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This adds a vertical stretch to the inner layout of dock widgets if they don't already have a widget that has an "expanding" vertical size policy.

### CODE REVIEW

**Comment by tlambert03** [comment]
I think the failing tests here will be fixed by the next magicgui release... so let's hold on this one

**Comment by sofroniewn** [comment]
Thanks for getting this started! I can wait till the next magicgui release to review, but love the direction

**Comment by tlambert03** [comment]
this is kinda turning out to be a bit hairier than I want it to be.  To add stretch we either need to directly modify the widget that the user provides to us (e.g. look into their widget for a layout and add a stretch), or we need to wrap their widget in another QWidget with its own layout that has the user widget and a stretch item.  The problem with the former is that it's kinda invasive, and is may well break with unanticipated user widgets.  The problem with the latter is that a) we now need to special case a few widgets we _don't_ want to have wrapped (like our internal dock widgets), and b) it buries the "real" widget yet another level deeper, breaking things like `viewer.window.remove_dock_widget(my_widget)` unless we add recursive child widget searching.  
I don't love either idea really, so I'm wondering if maybe we shouldn't just put it back on the user providing the widget to add their own stretch.

**Comment by sofroniewn** [comment]
hmm ok, tricky, we can put this on the back burner for a little

**Comment by goanpeca** [comment]
>I don't love either idea really, so I'm wondering if maybe we shouldn't just put it back on the user providing the widget to add their own stretch.

It might be the solution, but having the all the things spread looks bad in general, so even if adding the stretch for the is a bit invasive, I do not see devs doing that manually unless docs and examples are very explicit about it.

**Comment by sofroniewn** [comment]
> It might be the solution, but having the all the things spread looks bad in general, so even if adding the stretch for the is a bit invasive, I do not see devs doing that manually unless docs and examples are very explicit about it.

@goanpeca if we do go with adding the stretch ourselves what approach do you think we should take?

**Comment by tlambert03** [comment]
> even if if adding the stretch for the is a bit invasive ...

yeah, i'm not sure it's ok to start directly modifying the widgets that plugins give us.  We may break some assumptions that they are making about their layouts?  I agree it's ugly, hence opening this PR... but I'm reluctant to start changing the actual objects that users give us

**Comment by goanpeca** [comment]
> We may break some assumptions that they are making about their layouts

Is there a way to know things come from magic gui or it is a very custom widget?

I see no issues in managing widgets that were autogenerated.

Either approach would be fine for me as long as we applied it to autogenerated guis?

**Comment by tlambert03** [comment]
this isn't really about manual vs autogeneration.  The point is, if someone uses `viewer.window.add_dock_widget(whatever_widget_they_made)` (which is essentially the same mechanism as `viewer.window.add_plugin_dock_widget`), then if they've just used a regular QWidget/QBoxLayout strategy, it will likely have the default size policy and stretch factors that will spread the widgts.  So, as mentioned in https://github.com/napari/napari/pull/2154#issuecomment-767149328, the options are to either _directly_ modify their widget (which is what this PR does, checking first to see if the user has a non-default size policy)... or, to wrap the widget in a second widget that has a layout with a stretch....  In which case we may need to special case a few things.  

that was the situation last I checked... ideas welcome

**Comment by goanpeca** [comment]
I do not have a better suggestion besides going over all the existing plugins and making an issue or PR that adds a stretch to them if it makes sense and then also update docs and examples to always include the stretch for examples.

Besides that, I would use option 1 on anything that is external, maybe add an option on the `viewer.add_dockwidget(widget, add_vertical_stretch=True, add_horizontal_stretch=False)` 🤷🏼 

And we would use `add_vertical_stretch` on external plugins. Make it `True` by default and use it with `False` on anything internal (console, layers, etc.?)

**Comment by tlambert03** [comment]
> Besides that I would use option 1 on anything that is external, maybe add an option on the viewer.add_dockwidget(widgte, add_vertical_stretch=True, add_horizontal_stretch=False) 🤷🏼 And we would use add_vertical_stretch on external plugins. Make it True by default and use it False on anything internal (console, layers, etc.?)

that's actually my favorite so far! :) so simple 😂

**Comment by tlambert03** [comment]
updated

**Review by goanpeca — APPROVED** [review]
Thanks for the updates @tlambert03 🚀 

LGTM!

**Review by jni — APPROVED** [review]
Just tried this out with affinder (using `napari --with affinder`! 🎉) and it's lovely! No comments on the code, good to merge afaic!

**Comment by jni** [comment]
I'll aim to merge this later in the day if no one raises any objections.

**Review by sofroniewn — APPROVED** [review]
LGTM! Do we want a horizontal stretch too? Maybe not as critical. Can come later. I say merge when ready!!

**Comment by jni** [comment]
I think horizontal is much less needed in a vertical side bar.

**Comment by sofroniewn** [comment]
> I think horizontal is much less needed in a vertical side bar.

Ah i meant horizontal for when the widget is docked horizontally, agreed would be weird to mix/ match. But also not something that needs to be addressed now. Can come later if people want it

**Pull request merged**
