### PR TITLE
modified multiple images overlaid figure

### PR DESCRIPTION
**Pull request by pranathivemuri**
# Description
modified multiple images overlaid figure
Illustrates code in Readme better
also fixes the axis issue with 3D stack

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References
https://github.com/napari/napari/issues/385 and https://github.com/napari/napari/issues/386

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — CHANGES_REQUESTED** [review]
The screenshot doesn't seem to render as nicely as the others (i.e. it's missing the shadow) and has some extra lines at the top. Maybe @freeman-lab knows how to improve

**Comment by kne42** [comment]
you can achieve this effect by pressing Command+Shift+4, then Space, and clicking on the window (OSX only)

**Comment by pranathivemuri** [comment]
let me know if this image looks better!

**Review by sofroniewn — APPROVED** [review]
New image looks great, thanks @pranathivemuri! I will merge

**Pull request merged**
