### PR TITLE
test: Speed up test_viewer tests, split out pyqt5/pyside2 tests again

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
Been playing with test speed locally and found that one of the biggest offenders was `test_viewer`, specifically `add_layers`.  It had a 3-factor parametrization (looked like two, but was three due to the keybindings for loop), meaning it was running many hundreds of times, each creating a new viewer (expensive).  When running tests locally with xdist, all of my CPUs would be on full blast right up until it hit `test_viewer::add_layer`, at which point something choked, and all the processes crawled to a halt.  By removing that parametrization it sped right through the test.  

I know it's slightly nicer to be able to test each key binding it isolation, but i think we need `make_napari_viewer` to be better in order for that to work here.  This compromise (in addition to parallelizing pyside2/pyqt5 envs) has been getting tests back down to around 10 mins in testing over in my fork.  lets' see how it does here

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by Czaki** [comment]
> I know it's slightly nicer to be able to test each key binding it isolation, but i think we need `make_napari_viewer` to be better in order for that to work here.

Why cannot use the `for` loop inside the test? If the only problem is creating a viewer then we could perform all tests in one function.

**Comment by tlambert03** [comment]
> Why cannot use the for loop inside the test? If the only problem is creating a viewer then we could perform all tests in one function.

that's exactly what I do in this PR:

https://github.com/napari/napari/pull/4646/files#diff-2f6774df0d680526db5a476cc0af220133923ce304335a69fea889cd55e335baR94-R95

**Review by Czaki — APPROVED** [review]
I finally understand and like this changes

**Comment by tlambert03** [comment]
as an aside, this PR includes a couple changes to let `pytest-xdist` work.  However, I don't think we should turn it on.  For posterity, [here](https://github.com/napari/napari/runs/6803297120?check_suite_focus=true) is a run with it on.  If anything it shaves no more than about 10% off the time (there's only 2 cpus available on GHA), and it comes at the cost of possible concurrency failures.

Using locally on my computer though, it _flies!_  with the entire test suite `pytest -n auto napari` wrapping up in 1m34sec ... compared to 3:47 without xdist.  So it's definitely nice to have as a local option

**Comment by Carreau** [comment]
Ha, good occasion to use https://pytest-viewer.fly.dev/gh/napari/napari/pull/4646

Screen Shot 2022-06-09 at 09 39 02

Test add_layers goes from using 28% of the test suite to 5%, next offender (after test_examples, being test_mgui).

**Review by Carreau — APPROVED** [review]

**Pull request merged**
