### PR TITLE
Enable string quote formatting for black

### PR DESCRIPTION
**Pull request by brisvag**
# References and relevant issues
Setting up for #6383.

# Description
On request from @czaki, splitting out the bulk of formatting changes from #6383, which come in the vast majority from enabling the string quote formatting (enforcing double quotes).

This makes it easier to spot what `ruff-format` does differently from `black`.

### CODE REVIEW

**Review by Czaki — CHANGES_REQUESTED** [review]
Only to block merge before 0.4.19 release

**Comment by Carreau** [comment]
83sgzn

**Review by Carreau — APPROVED** [review]

**Review by jni — CHANGES_REQUESTED** [review]
(**Edit:** *apologies that this post was so cranky. Leaving here to not whitewash — if people want to 'Hide' that's fine — but please [see below](https://github.com/napari/napari/pull/6386#issuecomment-1780604381) for an apology and a more reasonable review.* :pray:)

Original review:

------------------------

Can we just **not** do this, please???

Apologies in advance for the rant. I woke up too early and I'm therefore more prone to crankiness. But this PR and #6383 make me cranky.

Leaving aside that maybe the `-S` flag was included in our config for a reason and it might be worthwhile to look into the reason, this PR will add an enormous amount of churn to 75 open PRs. We are already drowning in maintenance — just click on the maintenance tag to find 75 PRs merged in the past three weeks. That's 25 PRs per week just spinning our wheels. Do we really want to add to that? I'm already mostly tuned out because of burnout and I wholeheartedly thank @Czaki and @Carreau among others for taking on the bulk of it. But we should aim to decrease their load, not add to it because a cool new formatter was released (checks notes), *in beta*, *two days* ago.

I ran black on the *entire repo* on my machine and it took 1.2 seconds. On the whole repo. Is ruff's speed really going to be worth the churn caused by the formatting differences? How many invocations until we make up for the work of pointlessly updating 75 in-flight PRs? (I am not counting CI invocations because this is so far off being our CI bottleneck as to be on another planet.)

I'll finish by reposting the evergreen essay [Choose Boring Technology](https://mcfunley.com/choose-boring-technology) ([archive.org link](https://web.archive.org/web/20230823215156/https://mcfunley.com/choose-boring-technology)). As mentioned above, the ruff formatter has been in *beta* for *a couple of days*. It's absolutely *not* boring by any stretch. It will probably continue to change and evolve as they tweak things. Can we not muster the patience to at least wait until 1.0 to adopt it? Or even just until you can configure not formatting strings so we can avoid this pre-PR altogether???

I love your work Lorenzo ❤️ but I would very much appreciate it if you simply closed this PR and also #6383, and experimented with rufffmt in new projects only. 🙏 Maybe even add it to the cookiecutter! Whatevs. But napari is the wrong project to do this in.

**Comment by Carreau** [comment]
I approve of the feeling.

Though I _think_ we should find a way to progressively migrate the string to be formatted.
We could try to use https://pypi.org/project/darker/ that only apply formatting to changed code. 

On the other hand, the "churn" on other PRs should be relatively easily fixable by running black on the HEAD of the PR. But indeed we _do_ have to do it to 75 PRs.

(I'd also love to have a few focus weeks with a soft moratorium on New PRs and finishing/closing existing ones)

**Comment by jni** [comment]
I've received private feedback that my post above was a tad much, which I recognise. I sincerely apologise for letting emotion seep into my review. 🙏 

Here's what I should have written:

-----------------------------

Hi folks,

- Since it takes black just ~1.2s (on my machine) to run on the full repo, switching to ruff for speed does not seem to provide a huge benefit to our infrastructure.
- Additionally, ruff-format is still in beta. There are many changes in the horizon for ruff format (see [the beta feedback discussion on the ruff repo](https://github.com/astral-sh/ruff/discussions/7310)), so I don't think we should migrate until the formatter has settled.
- Indeed, once it has settled, it may well be that it can drop-in replace black with much more minimal changes and less disruption.
- Regarding our black configuration skipping string formatting: this was intentional, because PEP8 allows either quote style, and single quotes have historically been preferred in the community, I think simply because they are easier to type. Indeed, they *remain* easier to type, so I would like to keep the single quote default, unless we have strong reasons not to.

Given all of the above, I would prefer to close this PR and #6383 for now. We could perhaps revisit them once `ruff format` is more mature.

**Comment by Czaki** [comment]
> Regarding our black configuration skipping string formatting: this was intentional, because PEP8 allows either quote style, and single quotes have historically been preferred in the community, I think simply because they are easier to type. Indeed, they _remain_ easier to type, so I would like to keep the single quote default, unless we have strong reasons not to.

At this moment, we have mixed-string quotations. Not a single quote. Ruff formatter allows to define if use single or double quote. 
From my perspective, I prefer a double quote, as my background is C/C++/Java where a single quote is a single `char` not a string (`char *`).

In the context of using formatter with a string normalisation argument which is easier to type is no longer valid. You could type one type of quotation and formatter will normalize them to have a uniform codebase. 

> Though I _think_ we should find a way to progressively migrate the string to be formatted. We could try to use [pypi.org/project/darker](https://pypi.org/project/darker/) that only apply formatting to changed code.
> 
> On the other hand, the "churn" on other PRs should be relatively easily fixable by running black on the HEAD of the PR. But indeed we _do_ have to do it to 75 PRs.

To fix multiple problems with testing we need to switch to src layout. Doing such a switch will require doing the same thing with 75 PR. So making another change that may need assistance at the same time will not increase the amount of work to do.

**Comment by brisvag** [comment]
I definitely agree that the big quote migration would be an awful pain; I did talk about this in the community meeting yesterday, and I had no intention to no-scope this PR and merge it... maybe communicating that clearly by marking the PRs as draft would have saved you some stress @jni :wink: 

My intention here was mostly to see if and what would have to change between black and ruff, and potentially report back (the open beta's purpose is to get feedback, after all, and how better than to run it on a complex repo like napari). So this PR is just a trick to make that diff easier on the other PR.

As for the quotes themselves: I'm all for single quotes, that's what I type all the time, but I agree with @Czaki that it doesn't really matter once you have a formatter. IMO we could wait to see if they add this option back in, and think about it again then, I really don't feel strongly about this.

**Comment by Carreau** [comment]
> To fix multiple problems with testing we need to switch to src layout. Doing such a switch will require doing the same thing with 75 PR

I don't think so as git should recognize file moves – as long as moving to src layout _only_ move the files, it will resolve the conflicts by itself.

> In the context of using formatter with a string normalisation argument which is easier to type is no longer valid. You could type one type of quotation and formatter will normalize them to have a uniform codebase.

I agree. Especially if you have a formatter set up as a editor hook. I personally have darker set up, so regardless of the project, it autoformat only what I type.

**Comment by jni** [comment]
@brisvag It doesn't make sense to open this PR if you just want to show the ruff diff — you can just split the #6383 into multiple commits and show the diff of one commit. Wanna do that? (ie this one can indeed be closed.)

At any rate the comments read like @Czaki and @Carreau were on various parts of the spectrum of merging this "soon".

For future endeavours, maybe making a PR on your own fork and posting on #general on Zulip would be a potentially better way to achieve this?

>> In the context of using formatter with a string normalisation argument which is easier to type is no longer valid. You could type one type of quotation and formatter will normalize them to have a uniform codebase.
>
> I agree. Especially if you have a formatter set up as a editor hook. I personally have darker set up, so regardless of the project, it autoformat only what I type.

I tried it but didn't like having the editor hook because it can end up reflowing my code in front of my eyes and I lose my flow. Without the hook, it also happens reasonably often that I'm trying to do a partial commit (as opposed to `git commit -a`), at which point black reformatting gets annoying — I have to go hunt down the chunks again that black reformatted as opposed to the stuff I didn't stage for other reasons. So, I prefer to rely on my nose rather than the autoformatter for those reasons.

I understand that these are small complaints. But it's death by a thousand cuts with the napari dev chain. And anyway, if y'all don't care one way or another (autoformat ftw!), let's do single quotes yeah? 😃😉

**Comment by brisvag** [comment]
Yeah agree with single quotes if we do go in that direction!

**Pull request closed without merging**
