### PR TITLE
Convert example notebooks to markdown

### PR DESCRIPTION
**Pull request by kne42**
## Description
- add [`jupytext`](https://github.com/mwouts/jupytext) to requirements
- convert IPython notebooks to markdown using [`jupytext`](https://github.com/mwouts/jupytext)
- add IPython notebooks (`.ipynb`) to `.gitignore`
- delete `examples/slider.py` (did not belong there)
- add `README` in `examples` folder promoting usage of [`jupytext`](https://github.com/mwouts/jupytext)
- use `pytest` to automatically generate tests for examples

- convert `examples/demo.py` to markdown
- improve content & presentation of examples (including organization & naming)

### CODE REVIEW

**Comment by kne42** [comment]
Tests are failing on Windows because somehow `scipy` isn't installed despite being required by `scikit-image`. CI traceback is [here](https://cirrus-ci.com/task/5277574722748416).

@jni Have you ever encountered this before?

**Comment by kne42** [comment]
Perhaps the simplest solution is to remove `scikit-image` as a dependency.

We can replace it with other dummy images either pre-generated from `gui.utils` or `numpy` arrays like in `examples/demo.py`.

**Comment by sofroniewn** [comment]
I think at some point in time it will be nice to have real images, including 3D / 4D / 5D ones to look at in our examples, but they don't have to come from skimage

**Comment by jni** [comment]
I'd like to point everyone to the [pooch](https://www.leouieda.com/blog/introducing-pooch.html) library for fetching data files. =)

**Review by royerloic — APPROVED** [review]
Looks great!

**Comment by sofroniewn** [comment]
This looks great - just gave it a try. I think it will make managing the notebooks much easier. One comment - on the `examples/README.md` do you want to add some extra info about the need to configure `jupytext`, i.e. setting
```
c.NotebookApp.contents_manager_class = "jupytext.TextFileContentsManager"
```
Could say look at `jupytext` for installation instructions and include a link to the [installation section](https://github.com/mwouts/jupytext#installation).

Agreed also that we should refactor some of the examples etc. and think about using `pooch` for getting data, but that can be another PR.

Happy to give an approving review if needed

**Comment by kne42** [comment]
@sofroniewn regarding an explicit `jupytext` requirement, I think that, as a Markdown document, it serves its purpose just fine. The reference to `jupytext` was primarily to let people know that the files are all `jupytext`-compatible.

In the future, I think it would be more useful to include screenshots of the effect that each line has on the GUI.

As for using `pooch`, I think that belongs more in the [`napari-data` repository](https://github.com/Napari/napari-data), which will attach itself as an IO plugin.

**Comment by sofroniewn** [comment]
Ok fine, that makes sense. People that want to use `jupytext` can look into it more from the link

**Review by sofroniewn — APPROVED** [review]
Looks good to me

**Comment by kne42** [comment]
Note: developers should add the following line to their `.jupyter/jupyter_notebook_config.py` to prevent metadata from being written to text files (see https://github.com/mwouts/jupytext/commit/167e9bce75ead19ddfccc7f1a059c2d8d88c6a21):
```python
c.ContentsManager.additional_metadata_on_text_files = False
```

**Comment by sofroniewn** [comment]
This PR has been superseded by #128. We will also be moving the notebook example to the docs, see #138 for discussion. We can then decide if we want to add the `jupytext` dependency or not. Additionally we are now improving our testing infrastructure in new PRs that are still to come.

**Pull request closed without merging**
