### PR TITLE
Internationalisation testing.

### PR DESCRIPTION
**Pull request by Carreau**
# Description

Handle multiline strings, either joined strings, or continuation lines
with backslash.

Also _start_ moving the information into a json file to be allow auto
updating. `python tools/test_strings.py` will autoregenerate the json file to at least autoremove some of the entries.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by Carreau** [comment]
I'm still unsure this will be correct. In particular if what I did here is enough to get the strings in the PO files.

**Comment by goanpeca** [comment]
Hi @Carreau thanks for looking into this.

I can check the po files generation and see if things are working as expected.

Also, if the plan is now to allow this

```python

        trans._(
            "this"
            "will"
            "work"
        )
````

or  (I do not like this code style BTW) 
```python
        trans._(
            "this" /
            "will" /
            "work"
        )
```

Then should we start changing a few strings so they conform to whatever line length we are using?

The one line "solution" was just easy and simple at that time, but if we can overcome that now, we should start reverting those single line strings into multi line ones, hopefully without thew use of `/` concatenation.

**Comment by Czaki** [comment]
> or (I do not like this code style BTW)
> 
> ```python
>         trans._(
>             "this" /
>             "will" /
>             "work"
>         )
> ```

Black will prevent this code style.

**Comment by Carreau** [comment]
That would be `\`, not `/`. This allow both with `\`, or nothing. 
My main concern if whether those multiline strings get properly extracted for translations.

**Comment by goanpeca** [comment]
>That would be \, not /. This allow both with \, or nothing.

Sure, my bad :)

>My main concern if whether those multiline strings get properly extracted for translations.

Yep they do.

**Review by goanpeca — APPROVED** [review]

**Pull request merged**
