### PR TITLE
Make napari robust to image & labels containing NaN or Inf values

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
# Description
This pull request allows us to see where NaN pixel values break things in napari/vispy. This is related to the discussion at https://github.com/napari/napari/issues/1310. It's for convenience, so that anyone can see the pytest results from the CI, without having to run pytest locally.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
As an initial summary, we're seeing these tests break so they would be good places to start:

```
=========================== short test summary info ============================
FAILED napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Image-data4-2] - A...
FAILED napari/_qt/_tests/test_qt_viewer.py::test_add_layer[Labels-data7-2] - ...
FAILED napari/_tests/test_adding_removing.py::test_add_remove_layer_external_callbacks[Labels-data7-2]
FAILED napari/_tests/test_view_layers.py::test_view[Image-data4-2] - Assertio...
FAILED napari/_tests/test_view_layers.py::test_view[Labels-data7-2] - TypeErr...
```

**Comment by GenevieveBuckley** [comment]
We should see these tests passing after https://github.com/napari/napari/pull/3494 is merged.

Should I mark these tests XFAIL, and then https://github.com/napari/napari/pull/3494 can unmark them there?

**Comment by jni** [comment]
We should update this to try `np.min` before `nanmin` for performance reasons. If min returns nan, then switch to nanmin.

**Comment by GenevieveBuckley** [comment]
Updated. @jni can I get you to look over this and check it is what you meant. You have a better sense of the performance implications than I do.

If everything's good, then we're just waiting until after https://github.com/napari/napari/pull/3494 is merged before we merge this PR

**Comment by MosGeo** [comment]
#3494 is now merged. Looking forward for this one :)

**Comment by brisvag** [comment]
As mentioned in #1310, there seems to still be something to do, but we're on the right track :)

**Comment by brisvag** [comment]
I think this can be closed.

**Pull request closed without merging**
