### PR TITLE
Use imageio v2 api to silence Deprecation Warning

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR switch to directly use imageio v2 API to prevent test fail because of deprecation warnings. 
```
  E       DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning dissapear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
```

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

https://github.com/napari/napari/runs/6449319602?check_suite_focus=true#step:9:101

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]

**Comment by jni** [comment]
@Czaki is the pytest update intentional?

**Comment by Czaki** [comment]
> @Czaki is the pytest update intentional?

Yes, but version selection was arbitrary. I remember that I have a problem with the napari test on the old pytest, but cannot find which version is problematic. 

Also, the current pytest-faulthandler package is a dummy package to ensure pytest is in version at least 5.0. 

feel free to revert if you think that this needs more checks.

**Comment by tlambert03** [comment]
going to merge.  I don't see pytest version bump as problematic (and easily revertible since it's not a runtime dep)

**Comment by jni** [comment]
@Czaki not more checks but it would be nice to separate concerns in general. Given the context it looked like it was related to the new imageio version but from the sound of it it's a completely different issue.

**Pull request merged**
