### PR TITLE
Move to Python 3.9 in the bundled application

### PR DESCRIPTION
**Pull request by alisterburt**
# Description
This PR would move us up to Python 3.9 for the bundled app - see discussion in #2898 

I need to check that this works in CI, build works fine locally.

@Czaki mentioned in #2898 that we should annotate this as `x86_64` now...
It seems like the `x86_64` string should be added here
https://github.com/napari/napari/blob/804cebee7c0f60fcec1513f5908638c8330deaa2/bundle.py#L180-L183

and the corresponding artifact upload here should be modified to upload the right file
https://github.com/napari/napari/blob/804cebee7c0f60fcec1513f5908638c8330deaa2/.github/workflows/make_bundle.yml#L64-L68

I'm not exactly sure how to detect the architecture on CI and add this info here, that should probably be added before this PR is merged and I would appreciate any nudges in the right direction

---
Some info from sleuthing, cibuildwheel now supports [building wheels for M1](https://cibuildwheel.readthedocs.io/en/stable/#what-does-it-do) on github actions by cross compilation on macOS intel CI

I guess this will also be relevant if we start to release M1 wheels given [exciting recent progress](https://forum.image.sc/t/issue-with-downloading-napari-on-mac-m1-chip/53961/10?u=alisterburt)

### CODE REVIEW

**Comment by Czaki** [comment]
Napari does not continental any code which need compilation (c extensions) so there is no need to provide separate m1 wheel.

Cibuildwheel is a tool to building qheels for packages with compiled extensions.

**Comment by sofroniewn** [comment]
@jaimergp what are your thoughts on this? Also @jni @tlambert03 - i know folks are running into this problem, so we should probably go ahead and merge no? Could even do for 0.4.11?

**Comment by jaimergp** [comment]
I could only test my patches on 3.9, so I guess this should work now that #3266 is merged. I'll make sure to test the bundle artifacts once they are ready too.

**Review by sofroniewn — APPROVED** [review]
Ok nice, I think we should merge. @tlambert03 @jni agreed? Or any concerns?

**Review by tlambert03 — APPROVED** [review]
haven't tested... but very much want 3.9, so fine with me :)

**Comment by sofroniewn** [comment]
Ok nice, let's get this in then!!

**Pull request merged**
