### PR TITLE
Add npe2 to install requires

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This PR adds npe2 to dependencies.

Since we have public docs up about npe2, we should probably require npe2 in napari as well (since ultimately, it's not whether the plugin developer has it installed, but whether the end user has it installed that determines whether a plugin writer can use it)

Note: this means we need to get it on conda forge before the next release.  

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by sofroniewn** [comment]
> This PR adds npe2 to dependencies.

Makes sense to me

> Note: this means we need to get it on conda forge before the next release.

Do you have a sense of timing here? We can discuss in zulip, but I had been thinking it might be nice to start the `0.4.13` release process this week.

**Review by nclack — APPROVED** [review]
looks good (modulo test failures)

**Comment by tlambert03** [comment]
https://github.com/conda-forge/staged-recipes/pull/17441

**Comment by tlambert03** [comment]
@nclack, there's another issue here that we have to deal with, and that's plugin support (specifically `napari-svg`).  This relates to a new issue I created https://github.com/napari/npe2/issues/80

Basically, our code that tested to see if `npe2` was importable before naming the "svg" plugin `SVG = 'napari-svg'` doesn't work unless napari-svg itself is ready to update, otherwise we get 

```
E           ValueError: There is no registered plugin named 'napari-svg'.
E           Plugins capable of writing layer._type_string layers are: {'builtins', 'svg'}
```

So, i know we discussed that in the past, but we probably need to take a closer look at it now before we can merge this

**Comment by nclack** [comment]
> doesn't work unless napari-svg itself is ready to update

The tests pass using napari-svg `master`. Will deploying that to pypi solve the problem?

**Comment by tlambert03** [comment]
It will solve the tests here yea, but see the issue linked.  It then means that there's a hard cutoff of versions for napari svg.  Users must use napari 0.4.13 with the next version of svg and must use <=0.4.12 for previous versions.  As a required plugin, that feels like a recipe for a lot of incompatibilities

**Comment by nclack** [comment]
> It then means that there's a hard cutoff of versions for napari svg.

I gave napari-svg both entry points. I think that means it will be backwards compatible. At least in my hands, tests pass with the master branch of napari-svg on 0.4.12 and latest. On 0.4.12 it treats it as an npe1 plugin since writer integration hadn't landed yet.

**Comment by tlambert03** [comment]
Does it not show up twice in the plugins dialog?

**Comment by nclack** [comment]
> Does it not show up twice in the plugins dialog?

It does not :) v0.4.12 was early enough we wouldn't list npe2 plugins at all. It also happens we didn't have writer support in v0.4.12 (though readers were in).

**Comment by sofroniewn** [comment]
Will napari-svg be an issue? Or is that now ok? If @tlambert03 you can update this from main, then if all tests pass I think we can merge as npe2 is now on conda-forge i believe too

**Comment by tlambert03** [comment]
we need to release a new napari-svg for tests to pass here... this isn't ready yet.  will ping, but go ahead and do what you have to without it

**Comment by nclack** [comment]
> Will napari-svg be an issue?

napari-svg should be ready to deploy.  Once it's updated on pypi we should be gtg.

**Comment by sofroniewn** [comment]
> napari-svg should be ready to deploy. Once it's updated on pypi we should be gtg.

ok great - let me know if you need my help for this

**Comment by tlambert03** [comment]
`test_reader_plugin_can_return_null_layer_sentinel` failing... but with odd permission error.  passes locally. is this a github issue?

**Comment by sofroniewn** [comment]
> test_reader_plugin_can_return_null_layer_sentinel failing... but with odd permission error. passes locally. is this a github issue?

Weird I've not seen this before. I'm not sure what update in background? I will try re-running tests now

**Comment by nclack** [comment]
This is a different failure but `ubuntu-18.04 3.7 min_req` installed `napari-svg==0.1.4` instead of latest 0.1.6.  Thanks for doing the pypi deploy btw.

**Comment by sofroniewn** [comment]
> Thanks for doing the pypi deploy btw.

Wasn't me - maybe @tlambert03?

**Comment by tlambert03** [comment]
ok, got a headless test pass here.  Assuming all the rest pass, will merge

**Comment by sofroniewn** [comment]
All tests are passing here - amazing work @tlambert03 I will get this in now!! 🚀

**Pull request merged**
