### PR TITLE
Speed up points selection and selection display

### PR DESCRIPTION
**Pull request by matthias-us**
# Description

Refactored point selection and selection display code, specifically where selected points are compared against points in currently viewed slice. For large numbers of points in layer (50K+), this brings the time to complete a selection from ~5msec/point to <0.5µsec/point (~25sec --> ~2.5msec) for a 5K-point selection.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# References

# How has this been tested?

- [x] ran in made-up test cases (100K points, 5+ slices) with GUI selection
- [x] ran in case where points are selected both in GUI and programatically

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kevinyamauchi — APPROVED** [review]
Hey @matthias-us ! Thanks for this PR. I was able to reproduce the slow selection issue on master and can confirm this change fixes it. I played around with it using the `add_points.py` and `add_points_with_properties.py` examples and everything seems to be working well. Thanks again!

**Review by sofroniewn — APPROVED** [review]
wow @matthias-us this is incredible, I just tried this out for 50K points and the difference goes from being unusable to interactive, thanks so much for this contribution, and thanks @kevinyamauchi for the quick turn around on review.

I will merge this now and get it in for the 0.3.8 release!

**Comment by sofroniewn** [comment]
I've also update our `0.3.8` release notes. Normally this wouldn't be necessary, we generate release notes right before we make a release, but right now we're already in the final testing of the release candidate and this seems like a significant and safe enough improvement to squeeze in. Thanks again, I'll merge once test pass!

**Comment by matthias-us** [comment]
> wow @matthias-us this is incredible, I just tried this out for 50K points and the difference goes from being unusable to interactive, thanks so much for this contribution, and thanks @kevinyamauchi for the quick turn around on review.
> 
> I will merge this now and get it in for the 0.3.8 release!

Thank you for this incredible tool! I'm 

> wow @matthias-us this is incredible, I just tried this out for 50K points and the difference goes from being unusable to interactive, thanks so much for this contribution, and thanks @kevinyamauchi for the quick turn around on review.
> 
> I will merge this now and get it in for the 0.3.8 release!

Thanks for this incredible tool!! Working with point data on top of images and doing interactive plotting/selection in a notebook. May be posting some questions regarding point/shape selection events in the future.

**Comment by sofroniewn** [comment]
>Thanks for this incredible tool!! Working with point data on top of images and doing interactive plotting/selection in a notebook. May be posting some questions regarding point/shape selection events in the future.

Thanks, yes - i was immediately thinking that there might be some ways to speed up shapes selection/ editing after seeing this syntax too. I know @kevinyamauchi has been doing some profiling of shapes in #1562 which has already led to some improvements. Feel free to open up a new issue or continue discussion there after this PR merges

**Comment by kevinyamauchi** [comment]
> Thanks for this incredible tool!! Working with point data on top of images and doing interactive plotting/selection in a notebook. May be posting some questions regarding point/shape selection events in the future.

Awesome! As @sofroniewn said, please feel free to open issues and make comments as you see fit. Thanks again, @matthias-us!

**Pull request merged**
