### PR TITLE
Use a Weak Counter to track blocked events.

### PR DESCRIPTION
**Pull request by Carreau**
The Collection Counter is not weak, and was keeping around reference to
Camera._on_zoom_changed, with itself contain a reference to Camera,
down to the whole VisPyCanvas blocks, that was thus not freed.

Something along

... Viewer -> Camera ->EmitterGroup ... -> _block_counter -> _on_xxx_changed
(of Camera) -> VisPyCamera -> PanZoomCamera -> (A mess we want to
release).

Note that the event emitter usually support `(obj, 'meth')` instead of `obj.meth` for weak refs.
But that does not seem to be the case for blocker. I'm wondering if we
should try to detect when someone try to connect bound methods.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [x] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
_really_ good catch here.

**Comment by Carreau** [comment]
> _really_ good catch here.

I think I went up to 23 level up in the reference graph, to understand what's going on, and that you start leaving the Vizpy reference cycle after 18 levels. I was at the point were I was considering writing a D3.js render for objgraph in order to be able to hide/collapse/extand trees and figuring out what was going on.

I'm still a bit disappointed by the mac CI still failing, and the test suite not boing faster..

**Comment by tlambert03** [comment]
> I was at the point were I was considering writing a D3.js render for objgraph in order to be able to hide/collapse/extand trees and figuring out what was going on.

lol 

> I'm still a bit disappointed by the mac CI still failing, and the test suite not boing faster..

baby steps.  ready for merge here?

**Comment by Carreau** [comment]
Yes. One step at a time as long as it does not break another thing I'm happy.

This is basically a single commit of #3629 to make it digestible in the end.

**Pull request merged**
