### PR TITLE
Fix use of scaling in vispy points

### PR DESCRIPTION
**Pull request by brisvag**
# References and relevant issues
In #6025, the vispy update broke the efforts from #5312. This is actually because the changes in vispy apparently do not handle the `scaling` kwarg properly at initialization. We can fix it here by not passing it.

I can't believe this has been wrong for so long, and I somehow never connected this issue that kept bugging me with that PR... but here we are.

# Description
Try the following on main and here and move the camera around:
```py
import napari
import numpy as np
v = napari.Viewer(ndisplay=3)
pl = v.add_points(np.array([[1, 1, 1], [10, 10, 10]]), scale=[1, 5, 5])
pv = v.window._qt_viewer.canvas.layer_to_visual[pl]
```
This fixes two things:
- point sizes being all messed up by scaling
- the anisotropic scale rotation wobblyness you see above

This returns to the correct, pre-#6025 situation.

### CODE REVIEW

**Review by andy-sweet — APPROVED** [review]
This fixes the point-size issue in the description which I also bumped into in https://github.com/napari/napari/issues/6914. 

Code changes also look fine, as I understand that we want point sizes to only be dependent on `Points.size` and not `Points.scale`.

I don't see any wobble on `main` with the given example, so I cannot vouch for that. Maybe I'll defer to @psobolewskiPhD on that?

**Comment by brisvag** [comment]
This is what I see on main with the code above (fresh env, ensure vispy's up to date):


https://github.com/napari/napari/assets/23482191/80917a02-2e28-4fee-8b42-2fce84f3444b

**Comment by andy-sweet** [comment]
> This is what I see on main with the code above (fresh env, ensure vispy's up to date):

My env was a fresh napari dev install. But I was able to reproduce now, but only when I'm zoomed out.

**Comment by brisvag** [comment]
Should be good to go then :)

**Pull request merged**
