### PR TITLE
[WIP] Use npe2 shim/adaptor for npe1 plugins. remove npe1 plugin code!

### PR DESCRIPTION
**Pull request by tlambert03**
# Description

**not to be merged before the next release.**

This PR removes a huge amount of plugin related code without losing much functionality at all, and gaining a very noticeable speedup in time to load napari.

The idea here (in conjunction with https://github.com/napari/npe2/pull/86, which this PR requires) is that npe2 acts as a shim/adaptor for npe1 plugins.  The first time napari runs with this PR:

1. the npe2 plugin manager detects the presence of npe1 plugin entry points (no npe1 plugin manager discovery happens at all)
2. it creates a "mock" PluginManifest for each npe1 plugin (including nothing but the package name)
3. when we would normally import and inspect npe1 plugins (at viewer creation), this imports them and completes the contributions in the manifest, then caches it.
4. _napari now only needs to deal with the npe2 interface_, and no longer depends on napari-plugin-engine

the next time napari loads, it can use the cached contributions and avoids all imports and side effects until a plugin is specifically launched.  loading significantly faster and delaying all plugin side-effects until they are specifically requested by the user.

The main things that remain to be implemented are enable/disable of a plugin (honestly, I see that as a somewhat low priority since it has such an easy workaround of restarting napari).

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
I love this @tlambert03!

**Comment by sofroniewn** [comment]
Amazing @tlambert03 let me know when this is ready for final review!

**Comment by tlambert03** [comment]
just an update, this is "functionally" working at this point in concert with https://github.com/napari/npe2/pull/86

this has been updated to include #4086 ... after that gets approved and https://github.com/napari/npe2/pull/86 goes in, I'll finish cleanup of this PR, and get tests working again

**Comment by tlambert03** [comment]
will break this into multiple PRs.  #4564 is the first one. making this opt-in

**Pull request closed without merging**
