### PR TITLE
Add subtractive blending

### PR DESCRIPTION
**Pull request by kevinyamauchi**
# Description
This PR adds subtractive blending, inspired by discussion in #3374 and [this image.sc thread](https://forum.image.sc/t/multi-channel-composite-view-with-inverted-luts-in-imagej-fiji/61163).

In subtractive blending, blending is performed by subtracting the color values from the foreground layer from the color values of the background layer. Here's how the blending is implemented: given layer B is in front of layer A, `color_A = [1, 1, 1]`, `color_B = [1, 0, 1]`, `alpha_A = 1`, and `alpha_B = 0.5`, the rendered color is: `color_A - alpha_B * color_B = [1, 1, 1] - 0.5 * [1, 0, 1] = [0.5, 1, 0.5]`.

For a primer on OpenGL blending see here: https://learnopengl.com/Advanced-OpenGL/Blending

### example
To get an intuition for how this works, you can try this example and switch between blending modes and light/dark theme. Note how when switching between additive+dark and subtractive+light, the colors are inverted (i.e., magenta <-> green and white <-> black).

<details>
  <summary>example code</summary>

```python
import napari
import numpy as np

im_row = np.linspace(0, 1, 100)

# create a left to right gradient
im_0 = np.tile(im_row, (100, 1))

# create an up to down gradient
im_1 = np.tile(im_row.reshape(100, 1), (1, 100))

# overlay the gradients and see how they overlay
viewer = napari.view_image(im_0, colormap='magenta', blending='additive')
viewer.add_image(im_1, colormap='green', blending='additive')

napari.run()
```
</details>

additive + black canvas:
Screenshot 2022-01-04 at 18 46 23

subtractive + white canvas:
Screenshot 2022-01-04 at 18 46 41

## Type of change
- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
From discussion in #3374. I'm not sure if we should close it after this merges.

# How has this been tested?
- [x] all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
cc @psobolewskiPhD, @alisterburt, @Czaki, and @jni.

**Review by alisterburt — APPROVED** [review]
Looks good, exciting to have and nice and clean!

**Comment by psobolewskiPhD** [comment]
Ok, so it took me a moment to "get it" as at first I tried inverted LUTs and got nothing neither additive not subtractive in Light mode. But switching to conventional versions of the LUTs worked!
```
I_Forest = Colormap([[1, 1, 1], [0, 0.6, 0]])
I_Blue = Colormap([[1, 1, 1], [0, 0, 1]])
I_Bordeaux = Colormap([[1, 1, 1], [0.8, 0, 0.2]])

Forest = Colormap([[0, 0, 0], [0, 0.6, 0]])
Blue = Colormap([[0, 0, 0], [0, 0, 1]])
Bordeaux = Colormap([[0, 0, 0], [0.8, 0, 0.2]])
```
(test file from this post by @cleterrier https://forum.image.sc/t/multi-channel-composite-view-with-inverted-luts-in-imagej-fiji/61163/3?u=psobolewskiphd)
image

I feel like my intuition is to use inverted LUT on the white background canvas of Light mode. So it's a bit confusing, but plus is that the same LUTs then work in Dark mode with just the change to additive:
image

Another option is to use subtraction like this:
```
subtractive': dict(
        depth_test=False,
        cull_face=False,
        blend=True,
        blend_func=('ONE_MINUS_SRC_COLOR', 'src_alpha'),
        blend_equation=('func_reverse_subtract'),
```
The issue is clipping at saturation, but otherwise inverted LUTs look good:
image

**Comment by psobolewskiPhD** [comment]
BTW I just realized in Dark mode inverted LUTs don't work in additive mode--it's the opposite effect, where everything adds to 255, 255, 255 so it's pure white. Not sure how I never noticed that before, I guess because my images are all single channel.

Edit: it feels like GL_MAX and GL_MIN could put in some work here:
```
GL_MIN: takes the component-wise minimum of both colors: C¯result=min(Dst,Src)
GL_MAX: takes the component-wise maximum of both colors: C¯result=max(Dst,Src)
```
But they appear not to be supported by vispy? Seems like they would need to be added here:
https://github.com/vispy/vispy/blob/ef982591e223fff09d91d8c2697489c7193a85aa/codegen/headers/gl2.h

Edit2: I was able to implement GL_MIN and GL_MAX in vispy:
https://github.com/psobolewskiPhD/vispy/tree/Add_GL_MIN_GL_MAX

GL_MIN for inverted LUT (I_ above) on Light mode looks good:
image
(Of course with a conventional, black LUT you get a black square since min of black is black).
Edit3: In Dark mode the MIN works well too with inverted LUT as long as you set the bottom layer to `opaque`. Likewise, in Light mode MAX works with dark LUTs as long as you set the bottom `opaque`.
The flaw of GL_MIN and GL_MAX is they apparently disregard alpha, no  matter what's in `blend_func`, which makes sense, but makes for a bit of a bummer.

Edit4: In case anyone wants to try `min` you need the vispy from above and here's my napari branch:
https://github.com/psobolewskiPhD/napari/tree/feature/min-blending

**Comment by sofroniewn** [comment]
@kevinyamauchi am i right that you still wanted to make some updates to this after last community meeting? no rush, but i just wanted to check you weren't waiting for this to merge

**Comment by kevinyamauchi** [comment]
Thank you for all of the great follow-up @psobolewskiPhD !

> subtractive': dict(
>        depth_test=False,
>        cull_face=False,
>        blend=True,
>        blend_func=('ONE_MINUS_SRC_COLOR', 'src_alpha'),
>        blend_equation=('func_reverse_subtract'),

I think this is close, but not quite what we want. The `blend_func`sets function used to calculate the factor the source/destination color is multiplied by. This is why there is strange behavior as the R/G/B values approach 1 or 0. For example, blending `[0, 1, 0]` (source) on top of a white canvas`[1, 1, 1]` (dest) would give 

    [1, 1, 1] - [1, 0, 1] * [0, 1, 0] = [1, 1, 1]  - [0, 0, 0] = [1, 1, 1]

and blending `[0, 0, 0]` (source) on top of a white canvas`[1, 1, 1]` (dest) would give 

    [1, 1, 1] - [1, 1, 1] * [0, 0, 0] = [1, 1, 1]  - [0, 0, 0] = [1, 1, 1]

I think it would be nice if we could set the _color_ to `(1 - color)`, but I don't think we can do it with blending. I think we could do that with a frag shader filter, but I'm not sure that makes sense to do.

> Edit: it feels like GL_MAX and GL_MIN could put in some work here:

I agree that it would be be nice to add max/min. Perhaps you can make a follow-up PR once your vispy PR lands 😉 

## next steps
I propose two paths forward for this PR:

1. We merge as is (addressing any comments that arise during final review)
2. We decide that this is not the right approach and we should either wait for min/max blending or some other approach

I am in favor of (1), as I think this is helpful mode and it doesn't block an other improvements to blending on a white canvas. If folks think it's too confusing, I think we can (and probably should anyway) add a blending explanatory document. However, if people feel this is not helpful or a step in the right direction, I am totally fine with closing this PR!

**Review by sofroniewn — APPROVED** [review]
I'm good with approach (1) and merging now. As this has already been approved by @alisterburt I will go ahead and merge promptly. We can then make improvements for subsequent releases!!

**Comment by sofroniewn** [comment]
What does @psobolewskiPhD think?

**Comment by psobolewskiPhD** [comment]
Sorry, first week back; been crazy busy.
I put most of my thoughts here: https://github.com/napari/napari/discussions/3914

For me the absolute most important thing is avoiding the blank square in Light theme when opening an image.
I think this PR is a really clean but  *partial* solution.
Still it is a solution, so go with it? and if we find other blending modes that are better or whatnot, there will be future PRs?
This PR does make conventional LUTs that people likely use in Dark theme work nicely in Light mode (assuming it will be made the default there, else you will still get the bizarre blank square).
The color inversion is a bit disorienting, but one can pre-correct for it.

BTW: @kevinyamauchi I'm not sure your faux code is right there. I think that `'ONE_MINUS_SRC_COLOR'` *is* `1-color`, but the issue is that it's used as a factor, so I think it's doing:
`([1, 1, 1]-[R, G, B]) * [R, G, B, A]` for `src` R, G, B in the `reverse_subtract` equation.

**Comment by sofroniewn** [comment]
Thanks for weighing in again @psobolewskiPhD 

> The color inversion is a bit disorienting, but one can pre-correct for it.

@kevinyamauchi is there a way to address this in this PR before merge? Even if the final thing isn't perfect, it seems like it would be nice not to have folks have to learn this and then change it on them in the next release

**Review by sofroniewn — CHANGES_REQUESTED** [review]
This was discussed during team meeting thursday, and folks felt that we shouldn't merge with the requirement to use the inverse colormaps. Hopefully we can get this ready for 0.4.14 without too much trouble though

**Comment by kevinyamauchi** [comment]
> This was discussed during team meeting thursday, and folks felt that we shouldn't merge with the requirement to use the inverse colormaps. Hopefully we can get this ready for 0.4.14 without too much trouble though

That makes sense to me. I don't think it's worth rushing for this release. 

> BTW: @kevinyamauchi I'm not sure your faux code is right there. I think that 'ONE_MINUS_SRC_COLOR' is 1-color, but the issue is that it's used as a factor, so I think it's doing:

Sorry, I think my wording wasn't super clear,  @psobolewskiPhD ! I agree that is how `one_minus_src_color` works and I think that is what the examples show. In the first example, the color being blended on the white background was green (`[0, 1, 0]`) so the factor is `1 - [0, 1, 0]` or `[1, 0, 1]`. In any case, I think we are on the same page.

**Comment by kevinyamauchi** [comment]
> For me the absolute most important thing is avoiding the blank square in Light theme when opening an image.
I think this PR is a really clean but partial solution.
Still it is a solution, so go with it? and if we find other blending modes that are better or whatnot, there will be future PRs?
This PR does make conventional LUTs that people likely use in Dark theme work nicely in Light mode (assuming it will be made the default there, else you will still get the bizarre blank square).
The color inversion is a bit disorienting, but one can pre-correct for it.

Thanks for writing up #3914, @psobolewskiPhD ! I with your breakdown of the issues. In particular, I think we need to address whether we should/should not blend with the canvas and whether or not the canvas color should change with theme before we decide what to do with blending modes and colormaps. In light of that, I will close this PR (we can always resurrect it if needed)  and let's continue the conversation in #3914. Thanks for the feedback everyone!

**Pull request closed without merging**
