### PR TITLE
add information about screen resolution

### PR DESCRIPTION
**Pull request by Czaki**
# Description

As there are shown reports of problems with interface look I think that it may be a good idea to add more information to the napari info dialog. 

Currently, this PR adds information about the screens resolutions and scale 
I think that also Linux distribution name should be added.  
MacOS codename could be also nice. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
> Currently, this PR adds information about the screens resolutions and scale

Very nice idea!! I like this a lot, especially in the `try` statement

> I think that also Linux distribution name should be added.
> MacOS codename could be also nice.

I'm open to these things too, if they can be done in a safe way and the list doesn't start containing unnecessary info

**Review by sofroniewn — APPROVED** [review]
This looks good to me, I think screen resolution is useful for debugging DPI issues etc. and the try and catch seems pretty safe to me, but I'd love to hear from either @tlambert03 or @jni before merge just in case I'm missing something.

I think things like the linux distribution/ macos code name can come in their own PR.

We should be able to get this in for 0.4.3.

I've also rearranged it slightly and this is what I now see

```
napari: not-installed
Platform: Darwin-19.6.0-x86_64-i386-64bit
Python: 3.7.0 (default, Jun 28 2018, 07:39:16)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.1
PyQt5: 5.14.1
NumPy: 1.19.1
SciPy: 1.4.1
Dask: 2.29.0
VisPy: 0.6.5.dev2+g9e0822db

OpenGL:
  - GL version:  2.1 INTEL-14.7.8
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen #1: resolution 1440x900, scale 2.0

Plugins:
  - animation: 0.1.dev0
  - dv_reader: 0.2.4
  - dzi-zarr: 0.1.0
  - io-test: 0.0.1
  - lazy-openslide: 0.1.2
  - napari_plugin_engine: 0.1.8
  - ome_zarr: 0.0.17
  - svg: 0.1.4
  ```

or 
 
Screen Shot 2021-01-02 at 1 11 06 PM

both of which I think look good!

**Review by tlambert03 — APPROVED** [review]
nice!

**Comment by Czaki** [comment]
I forgot about this. And getting names and versions is much more complicated than this so the next PR is a good idea.

**Pull request merged**
