### PR TITLE
Fix NAP-3 table of contents

### PR DESCRIPTION
**Pull request by melissawm**
# Description
The table of contents for the NAPs index page is showing headers for NAP-3:

Screen Shot 2022-07-27 at 12 08 36 AM

The top-level headers on NAP-3 are h1, which conflicts with the h1 for the other ToC items. 

This PR fixes this, with the following result:

Screen Shot 2022-07-27 at 12 08 57 AM

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by jni — APPROVED** [review]

**Review by brisvag — APPROVED** [review]
Whoops, thanks for the fix!

**Comment by jni** [comment]
That is so cool that the full test suite doesn't run when it's only a docs fix! Thank you to whoever got that working, I missed it! 😂

**Comment by brisvag** [comment]
#4555 :smirk: There's probably more we could do, but this saves so much time already!

**Comment by jni** [comment]
🙏 !

**Pull request merged**
