### PR TITLE
Exclude tests and vendored modules from code coverage

### PR DESCRIPTION
**Pull request by Czaki**
# Description

In this PR there is the exclusion of tests and vendored modules from code coverage reports. This allows us to better see the impact of PR on napari code coverage. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by Carreau** [comment]
FYI there are also ways to tweak how coverage get reported by codecov by tagging some path to be part of lieb, test, vendors... https://github.com/ipython/ipython/blob/af37d7b2206fa3c3520b304011b4294fa3019da2/codecov.yml

Codecov will then report each individually.

**Review by Carreau — APPROVED** [review]
Approved, but maybe reenable test and show test/library separately as a test result in codecov in. subsequent PR ?

**Comment by Czaki** [comment]
> Approved, but maybe reenable test and show test/library separately as a test result in codecov in. subsequent PR ?

I do not know about this option. I will test it first in the side project.

**Comment by Czaki** [comment]
> FYI there are also ways to tweak how coverage get reported by codecov by tagging some path to be part of lieb, test, vendors... [ipython/ipython@`af37d7b`/codecov.yml](https://github.com/ipython/ipython/blob/af37d7b2206fa3c3520b304011b4294fa3019da2/codecov.yml)

I test this with PartSeg and it really nice allows to trace how it impacts different modules (for example napari may have a separate project for Qt part. 

But badge still will report coverage that includes tests. And test lines should not be counted when reporting total project coverage.

**Comment by jni** [comment]
I don't have strong opinions here but fyi Ned Batchelder, who created coverage.py, recommends including tests in coverage statistics:

https://nedbatchelder.com/blog/202008/you_should_include_your_tests_in_coverage.html

**Comment by jni** [comment]
(vendored modules are another thing)

**Comment by Carreau** [comment]
> And test lines should not be counted when reporting total project coverage.
... And
> Ned Batchelder, who created coverage.py, recommends including tests in coverage statistics:

I think I tend to agree with Juan here, I've too often see tests that for X or Y reason are not run. So I see test coverage as useful.

The badge may show the full coverage, CI should show multiple lines :

Screen Shot 2022-05-30 at 10 01 24

Ok, in the above it's not completely working, but it should be possible.

**Comment by Czaki** [comment]
> I don't have strong opinions here but fyi Ned Batchelder, who created coverage.py, recommends including tests in coverage statistics:

I read and understand arguments. My main problem is that when I'm looking at the coverage badge I would like to see application coverage to know how the code that I may interact with is tested.  But I do not see the option to get coverage information only for code so I left decision for main maintainers.

**Comment by Czaki** [comment]
Ma

**Comment by Czaki** [comment]
close as  #4595 was merged

**Pull request closed without merging**
