### PR TITLE
Fix `_get_tooltip_text` signature, add docstrings

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR fix bug introduced in #3710 (Wrong signature for  `_get_tooltip_text` and add missed entries in functions docstring

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by Czaki** [comment]
failures looks unrelated to this PR

**Review by sofroniewn — APPROVED** [review]
LGTM! Can you update from main, then tests should pass. Also do you think this can get a test that would have caught this bug? Thanks!!

**Comment by sofroniewn** [comment]
> Also do you think this can get a test that would have caught this bug?

@Czaki is there a test that would have caught the wrong function signature? I'm surprised that it wasn't caught by our tests. If you can add a test then i think we can merge this. thanks!!

**Comment by Czaki** [comment]
> is there a test that would have caught the wrong function signature? I'm surprised that it wasn't caught by our tests

we do not have any test for tooltip, there are only tests for status. I will add some test

**Comment by Czaki** [comment]
test added. It is simple call of `_on_cursor_position_change`, which call `_get_tooltip_text` for every layer type.

**Review by sofroniewn — APPROVED** [review]
LGTM! thanks for adding the test

**Pull request merged**
