### PR TITLE
Float/unfloat plugin dockwidgets on first show

### LINKED ISSUE #3624: Docked widgets are resizeable outside of their enclosure
## 🐛 Bug

While checking out how to address #3620, I found out this:

https://user-images.githubusercontent.com/23482191/141996124-b45e4cbf-052d-479d-8943-ea3c0bfc984f.mp4

## To Reproduce

Click and drag just a tiny bit to the right of the resizing handle of the right side area.

## Environment

```yaml
napari: 0.4.12rc1.dev12+g99e61c4e
Platform: Linux-5.14.15-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.10.0
VisPy: 0.9.1

OpenGL:
- GL version: 4.6.0 NVIDIA 495.44
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-molecule-reader: 0.1.dev2+g06b598e.d20210914
- napari-properties-plotter: 0.2.0
- ndtiffs: 0.1.1
- ome-types: 0.2.9
- scikit-image: 0.4.9
- svg: 0.1.5
```

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Fixes #3624

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by goanpeca** [comment]
It seems that after a float/unfloat operation it no longer happens, so I added this programmatically on first registration 🤷🏼 

@brisvag could you check it works :) ?

Thanks!

**Comment by tlambert03** [comment]
Wow! How'd you figure out this solution... how does the float/unfloat fix it?

**Comment by goanpeca** [comment]
>Wow! How'd you figure out this solution...

I wished I had a better answer,... I tried some stuff until I bumped into this one.

>how does the float/unfloat fix it?

I have no idea!

**Review by tlambert03 — APPROVED** [review]

**Comment by brisvag** [comment]
What! Yep, looks like it's solved :rofl:

**Review by brisvag — APPROVED** [review]

**Pull request merged**
