### PR TITLE
test: [Automatic] Constraints upgrades: `dask`, `hypothesis`, `imageio`, `napari-svg`, `pandas`, `pint`, `pydantic`, `pytest-cov`, `tensorstore`

### PR DESCRIPTION
**Pull request by jni**
This PR is automatically created and updated by this napari GitHub Action:
https://github.com/napari/napari/tree/main/.github/workflows/upgrade_test_contraints.yml
It ensures that dependencies are tested with the most recent version.

The updated packages are:

 * coverage
 * dask
 * hypothesis
 * imageio
 * napari-svg
 * pandas
 * pint
 * pydantic
 * pyqt6-qt6
 * pytest-cov
 * pytest-metadata
 * pyzmq
 * requests
 * tensorstore
 * typing-extensions

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
How is `PR Test / ubuntu-latest 3.9 pyside6 (pull_request) Successful in 19m` possible when I get: `RuntimeError: Napari is not expected to work with PySide6 >= 6.3.2 on Python < 3.10` ?
The python 3.10 pyside6 test fails are because 6.5.1 didn't fix the issue in 6.5.0 which we have blocked, related to: https://github.com/napari/napari/issues/5703

**Comment by Czaki** [comment]
In context of python <3.10 this line is responsible https://github.com/napari/napari/blob/bd69fd21a5b2a2112ff13b78ee88e96e13064ee7/tox.ini#L83

**Comment by psobolewskiPhD** [comment]
Derp I get it now. 
Anyhow, we probably need to set <6.5.0 for now, instead of !6.5.0.

**Review by Czaki — APPROVED** [review]

**Comment by Czaki** [comment]
I think that we should relax this policy. But we should discuss this in whole core-dev team. 

But as I understand if you are second core dev that accepts it we should be able to merge it without breaking the rules.

**Review by brisvag — APPROVED** [review]

**Pull request merged**
