### PR TITLE
[WIP]: add tabs to layer controls

### PR DESCRIPTION
**Pull request by ppwadhwa**
# Description

This is very much a WIP right now.  I am putting tabs in place in the layer controls panel.  Currently, only the points layer has tabs.
The icons used here are placeholders, the organization into different tabs still needs to be done, and styling needs to be completed.

Addresses the tabs discussion in #3975 .  

For reference, this is the look I am working toward:
Screen Shot 2022-04-12 at 4 10 05 PM

vs. current state:

Screen Shot 2022-04-13 at 11 52 11 PM

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by brisvag** [comment]
Looks cool @ppwadhwa! However, I have no idea about what is planned to go in which tab :P is there a discussion about this somewhere that I missed?

Worth mentioning that we might step each other's toes a bit with this and #4195!

**Comment by goanpeca** [comment]
Thanks for working on this @ppwadhwa!

---

>Worth mentioning that we might step each other's toes a bit with this and https://github.com/napari/napari/pull/4195!

Indeed @brisvag, I think the work is complementary :)

**Comment by ppwadhwa** [comment]
> Looks cool @ppwadhwa! However, I have no idea about what is planned to go in which tab :P is there a discussion about this somewhere that I missed?
> 
> Worth mentioning that we might step each other's toes a bit with this and #4195!

Thanks for linking that PR @brisvag !  I think the work will be complimentary also.  

This one is still very much in the beginning stages---there has not been a discussion yet about what should go in each tab, or icons for those tabs, etc.  This work was started by the discussion in #3975 , which I realize I didn't link yet (will do that now!).   I know @isabela-pf  was going to think about the tabs organization, but if you have thoughts on how to organize the tabs, please share!  

Also, that issue (#3975) was originally opened to expose translation and scale to the user via a GUI.  I have added those elements to a tab here, but not actually "hooked" them up to anything.  That is to another to-do item.

**Comment by alisterburt** [comment]
just a thought - I imagine having to flick back and forth between tabs could be a bit cumbersome, we see this in #4346 where to control the plane we need to select the image layer but to paint we need the labels layer active

As long as we can provide a whole set of controls for a given tab, and controls can be in multiple tabs at once then I'm super excited! It would be so cool for plugins to be able to define a set of controls visible at a given time and have this be available as a layer controls tab :)

**Comment by isabela-pf** [comment]
> I know @isabela-pf was going to think about the tabs organization, but if you have thoughts on how to organize the tabs, please share!

This is true, and I want to second the call for thoughts. I haven't gotten to wrap my brain around this well and come up with proposals, so I'll be sure to share them around when they exist. And thanks @alisterburt for that feedback!

> I imagine having to flick back and forth between tabs could be a bit cumbersome

My current thought is that layer controls switch automatically based on which layer is selected as they already do, so this wouldn't be a matter of needing to switch both a selected layer and the relevant controls. But that the tabs provide room to sort the growing list of layer controls in the viewer so it isn't just one long list. 

Is that what you meant? I'm not even confident that what I said makes sense based on my (limited) knowledge of how napari operates. 😆

> whole set of controls for a given tab

Would you mind clarifying this? Do you mean the whole set of controls available for that layer in one tab, or something else?

> It would be so cool for plugins to be able to define a set of controls visible at a given time and have this be available as a layer controls tab

Yes! That would be a fantastic result to reach for!

**Comment by alisterburt** [comment]
> Would you mind clarifying this? Do you mean the whole set of controls available for that layer in one tab, or something else?

Yes, this is what I meant 🙂

**Comment by kcpevey** [comment]
@ppwadhwa have you been able to make any more progress with this? Is there anything you're blocked on or a question that someone can help with?

**Comment by jni** [comment]
This PR is out of date given the work in #5358, so I'm going to close it. Sorry that we never got it over the line. If anyone wants to pick this up again, they should feel free to take the code and open a new PR with it. 🙏

**Pull request closed without merging**
