### PR TITLE
feat: Add right click menu position to copy spatial information

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues
depends on https://github.com/pyapp-kit/in-n-out/pull/110

# Description

Currently, we do not provide any mechanism to adjust spatial information from GUI. 
This PR add option to copy information from one layer to list of another one (selection). 

https://github.com/napari/napari/assets/3826210/4152aa06-00cf-4360-826f-5f6959328e02

Currently, it only copies `scale` and `translate`, as I would like to ask if you are happy with such workflow. 

This workflow requires opening a modal window to select the source layer. 

It is part of #6780

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
I dig it, I mean the contextual menu position should be moved down and I would add `...` to mark that modal will open, but it looks cool.
Could consider putting this in a submenu along with `reset scale & transform` to go back to 1, 1, 1.

Thinking out loud about other approaches:
- could try to do a `Copy` action on a layer that would grab that info and then offer a `Apply` action you could use on any other layers. I think it could be a bit more handy if you have many layers, but not sure on the implementation side how tricky it would be.
- use a `Set scale as global` action, that would apply the selected layer's scale to all layers -- this is probably the most common use case? (Could be handy programmatically too, TBH) Again, maybe in a submenu with `reset`

**Comment by Czaki** [comment]
> Edit: with this I'd probably also suggest a `Set scale..` which pops a modal to enter the scale, again the most common use case. 

I have planned to do this in separate PR for editing spatial properties.

> Transform can be done in GUI now, but not setting scale.

How? 

> could try to do a `Copy` action on a layer that would grab that info and then offer a `Apply` action you could use on any other layers. I think it could be a bit more handy if you have many layers, but not sure on the implementation side how tricky it would be.

It may be implemented using json (copy json to the clipboard and paste it back). But it may be difficult to discover. But maybe I have wrong image in my head and it could be obvious to to discover??

**Comment by psobolewskiPhD** [comment]
> But it may be difficult to discover.

No more difficult to discover than any other layer list contextual menu item?
I think right-click copy and then paste/apply are pretty common actions across OS's too-and MS Office apps for sure.
🤷

**Comment by Czaki** [comment]
Close in favor of #6864 base on feedback of community meeting

**Pull request closed without merging**
