### PR TITLE
Rename viewer_factory -> make_test_viewer, don't return view

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
Following discussion in https://github.com/napari/napari/pull/1378#discussion_r445459570, this is what it would look like to change `view, viewer = viewer_factory()` to `viewer = make_test_viewer()`

thoughts?  @jni @sofroniewn 

## Type of change

- [x] tests refactor 

# How has this been tested?

- [x] all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Love it, this looks great to me!

**Comment by sofroniewn** [comment]
Following merge of #1378 this needs to be updated, and dedicated testing doc should be updated too

**Review by jni — APPROVED** [review]
Yep, really happy with this!

**Comment by tlambert03** [comment]
ready when tests pass

**Pull request merged**
