### PR TITLE
Fix `io.magic_imread()` in `__main__.py`

### LINKED ISSUE #623: io.magic_read not updated in __main__.py
## 🐛 Bug

Call to `io.magic_read()` on line 56 of `__main__.py` not updated to `io.magic_imread()` after #601 

## To Reproduce

1. Running `napari some_file.png` from command line

I'm happy to open this one line change Pull Request, or it can be done by one of the maintainers

### PR DESCRIPTION
**Pull request by hectormz**
# Description

Updates name change of `magic_imread` (from old `magic_read`) in `__main__.py`

## Type of change

- [X] Bug-fix (non-breaking change which fixes an issue)

# References

This closes #623 

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Looks good to me. @jni We might want to add a test to catch this in the future, but for now I will merge

**Comment by hectormz** [comment]
@sofroniewn I thought about adding a test for this when I filled out your PR template. But I've never made a test checking for console outputs/failures

**Comment by sofroniewn** [comment]
I'm not sure either, maybe @jni has a good idea. We can add it in a followup PR though, I am merging now. Thanks again

**Comment by jni** [comment]
@hectormz thank you so much for the fast fix!

**Comment by jni** [comment]
Re testing, I remember @kne42 used a QTimer in the context manager to launch napari and shut it down. We could bring it back and do something similar to call `main.__main__`:

```python
with napari.gui_qt(timeout='1s'):
     argv = [...]
     napari.main.__main__(argv)
     assert [something relevant]  # =P
```

I'll work on this in the coming days.

**Comment by hectormz** [comment]
Not sure if this or the referenced `pytest` plugin is helpful:

https://www.scivision.dev/pytest-check-console-script/

One difference is that `napari` running successfully needs to be killed afterwards or with a time limit

**Pull request merged**
