### PR TITLE
feat: add codespace

### PR DESCRIPTION
**Pull request by tlambert03**
# Description

Any interest in this PR supporting [GitHub codespaces](https://github.com/features/codespaces)?

It's pretty slick actually, it lets you click the code button at the top right of a repo:

Screen Shot 2022-06-01 at 6 44 16 AM

and when you create a new code space, this PR would set up your (remote docker) environment to be immediately ready to start coding/testing.  It works both in a web browser, but even better, it works [natively in the desktop app](https://code.visualstudio.com/docs/remote/codespaces) (meaning someone could work on napari, create a branch, add a feature/bugfix, _test it_ without having to do any install, then submit a PR). 

of course, it comes at the cost of yet another top level dotfolder :joy:

You can see an example with psygnal, for which I already set it up.  Click the code button and create a code space (recommend doing it locally in vscode): https://github.com/tlambert03/psygnal

### CODE REVIEW

**Review by jni — APPROVED** [review]
Love it!

**Comment by Czaki** [comment]
Hm. Fast going through codespace documentation does not show free codespace hours for open source? 

https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-codespaces

Did you find some other information, or setup this may introduce additional costs for the napari organization?

Or we base on this phase: 

> Personal accounts are not currently billed for Codespaces usage. 

And it means that people could use it on their fork?

I personally used gitpod.io which provide 50 free hours per month for free user. https://www.gitpod.io/pricing

**Comment by tlambert03** [comment]
> Personal accounts are not currently billed for Codespaces usage.

yeah, it's a bit unclear if that's forever... and yes, I think that means the devcontainer here will set someone up if they use it on their fork.

I played with gitpod.io too.  it's also nice.  If github decides to remove the free personal usage, I'll probably consider it more :)

**Comment by Czaki** [comment]
> I played with gitpod.io too. it's also nice. If github decides to remove the free personal usage, I'll probably consider it more :)

so before merge please check repository settings to avoid additional costs.

**Comment by tlambert03** [comment]
> please check repository settings to avoid additional costs.

can you clarify what exactly you want me to be checking?

**Comment by Czaki** [comment]
> can you clarify what exactly you want me to be checking?

if payment limits for codespace in napari settings is set to 0.

**Comment by tlambert03** [comment]
It is.  Turns out that’s the default

**Review by Czaki — APPROVED** [review]

**Pull request merged**
