### PR TITLE
Async refresh when experimental setting is on

### LINKED ISSUE #5591: Async slicing: dask cache error when multiple layers share data
@andy-sweet As mentioned directly already, I've started testing this new async branch with our OME-Zarr data and ran into some issues with multi-channel data I'll report here in a bit more detail:

I'm using a 3 channel OME-Zarr dataset like this little test set here: https://zenodo.org/record/7120354
I installed this branch and the `napari-ome-zarr` plugin v0.5.2. I launch napari, then set the `_force_sync` to False from the napari console and drag & drop the Zarr plate into napari.

The first channel gets loaded correctly and can be browsed in the awesome async mode. But it then hits this issue when trying to load the additional channels in the OME-Zarr file (=> they become additional layers in napari):
```
~/mambaforge/envs/napari-dev-default-ome/lib/python3.10/site-packages/dask/cache.py:56, in Cache._posttask

     55 def _posttask(self, key, value, dsk, state, id):
---> 56     duration = default_timer() - self.starttimes[key]
        key = ('from-zarr-0424ef0e6522743e819a0000fe7dc515', 1, 0, 0, 0)
        default_timer = <built-in function perf_counter>
        self.starttimes = {}
        self = <dask.cache.Cache object at 0x1036dff70>
     57     deps = state["dependencies"][key]
     58     if deps:

KeyError: ('from-zarr-0424ef0e6522743e819a0000fe7dc515', 1, 0, 0, 0)
```
In the full stacktrace, it's downstream of self._load_slice(slice_data).

Sometimes, it loads 2 channels and fails for the third, sometimes it loads just one channel and fails for the second.

_Originally posted by @jluethi in https://github.com/napari/napari/issues/5377#issuecomment-1439869471_

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description

This makes `refresh` attempt async slicing by default when its corresponding experimental flag is on. In that case, the many internal calls to `Layer.refresh` will be executed asynchronously via the viewer rather than directly in the layer. This is especially helpful when a layer is initialized and added to the viewer, which can trigger many blocking calls to `refresh` some of which can now be cancelled. As `Layer._slice_dims` is always on the sync path, that forces the refresh to be synchronous.

In most usage of napari this should be enough to avoid #5591 because if the experimental flag is on and the layer supports async, then all slicing should occur on the slicing thread. If the flag is off or the layer does not support async, then all slicing occurs on the main thread.

However, #5591 could still be triggered if a user flips the experimental flag while async slicing is occurring. So this PR does not entirely close #5591, though something like #5610 should.

# References

Related to #5591 but does not close it.

### CODE REVIEW

**Comment by andy-sweet** [comment]
@jni : added you as a reviewer because we'd discussed something like this before. See the PR description for my thoughts on this.

I also attempted a different approach to this in https://github.com/andy-sweet/napari/pull/52/files similar to something we had discussed in the past. That's much more complex, but it does a much better job of unifying the sync and async paths. Probably needs a bit more work and some performance optimization before it could be merged though, whereas this is simple enough.

**Comment by andy-sweet** [comment]
Converted to draft because after some shower thoughts, I think I might be able to make https://github.com/andy-sweet/napari/pull/52 solve both issues.

**Comment by jni** [comment]
Hahaha every office should get easy and convenient showers installed. Shower thoughts are the source of so much innovation! 😂 🧠🚿💭

**Comment by andy-sweet** [comment]
@jni : I decided to make this ready for review because it's simple, likely fixes #5591 in most real cases, and also provides some other performance/laziness benefits from `main`.

By contrast https://github.com/andy-sweet/napari/pull/52 makes lots of changes for a variety of different reasons. They may be worth pursuing, but probably don't change too many fundamentals.

**Review by jni — APPROVED** [review]

**Pull request merged**
