### PR TITLE
Update github issues templates with links to image.sc and zulip 

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
small update to our issues templates.  I was inspired by the [pip issues](https://github.com/pypa/pip/issues/new/choose), which adds a couple nice linkouts.  So i removed the questions template and instead link to image.sc, and also add a zulip link

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM

**Review by jni — APPROVED** [review]
I’m totally fine with this, though @sofroniewn i thought you didn’t want the chat link to be super prominent? But I’m fine with it.

**Comment by jni** [comment]
Sorry, I also want to say it’s a great template, @tlambert03 ! Love the emojis and the redirection to image.sc.

**Comment by sofroniewn** [comment]
Yeah, that's correct @jni - and i did think about it - i guess i felt like if the person has already opened an issue here maybe it's ok .... i trust you and @tlambert03 here too

**Comment by jni** [comment]
Done. =D

**Pull request merged**
