### PR TITLE
Hide points individually - OLD

### PR DESCRIPTION
**Pull request by brisvag**
# Description
Proposal PR, which adds a new attribute to `Points` called `hidden`. It accepts a boolean array which is then used to hide/show individual points. Addresses #2666.

Note that this PR includes the changes in #3333 (which makes it easier to work with the vispy module), but that shold soon be merged on its own.

Simple example:

https://user-images.githubusercontent.com/23482191/134655377-97ab7dd8-1630-4963-be35-fec0a1cfc82a.mp4

<details>
<summary> Code </summary>

```python
#!/usr/bin/env python3

import napari
import numpy as np
from magicgui import magicgui


points = np.random.rand(100, 3) * 100
colors = np.random.rand(100, 3)
some_value = np.random.rand(100)

v = napari.Viewer(ndisplay=3)
v.add_points(points, face_color=colors, properties={'some_value': some_value})


@magicgui(
    auto_call=True,
    threshold={'widget_type': 'FloatSlider', 'min': 0, 'max': 1}
)
def slider(layer: napari.layers.Points, threshold: float):
    layer.hidden = layer.properties['some_value'] < threshold


v.window.add_dock_widget(slider)

napari.run()
```

</details>

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# References
#2666

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
That demo is *badass* @brisvag! This is a nice solution to the visibility issue. Can you update this to make the diff more reasonable? Thanks!

**Comment by jni** [comment]
Wow it's tiny now :joy: Thanks @brisvag!

Looks like some tests are failing. I also think (open to suggestions) that it would be better to use `shown` instead of `hidden`, as *most* of the ecosystem (with the notable exception of `numpy.ma`) has moved to a "True means active/displayed/processed" convention, so I think that would be most consistent with the rest of napari/scikit-image/scipy/etc.

I also hesitate to say this :joy: but probably hidden/shown can be treated as a 1-bit visual channel, which means it might fall into the purview of properties-based display. We can potentially cross that bridge later anyway thought.

**Comment by brisvag** [comment]
Actually, it's even smaller than this :P This PR inadvertently included also the spherical marker changes I just added on #3430, which is a significanlty bigger thing. We should maybe wait for that before we merge this.

I agree with the `shown` change, that makes sense to me. I don't get the last part: what do you mean by `1-bit visual channel`? It definitely should be linkable to properties :)

**Comment by jni** [comment]
> I don't get the last part: what do you mean by 1-bit visual channel? It definitely should be linkable to properties :)

That's all I meant. :smiley: I guess more specifically: we have/will have "colormaps"/"colorcycles" which map continuous and categorical values to the "color" visual channel, which can display many bits of information. We would also need, say, "thresholding map" and "set membership map" to map continuous / categorical variables to a boolean (1 bit) value. Once we have those we can say something along the lines (terrible API, just for illustration):

```python
viewer.add_points(
    data,
    properties=properties,  # has a "confidence" column in [0, 1]
    shown={
        'source': 'confidence',
        'mapping': {
            'type': 'thresholding',
            'condition': '>',
            'value': 0.5,
        },
    },
)
```

By the way, @andy-sweet, seeing the above dictionary made me think (apologies if this was obvious, I just haven't thought about it this way until now): if we have a pydantic class hierarchy for this sort of mapping, perhaps the "simple", "human-facing" API is just dictionaries corresponding to the pydantic fields? Though I guess "type" doesn't fit into that model... Perhaps it could?

**Comment by andy-sweet** [comment]
> if we have a pydantic class hierarchy for this sort of mapping, perhaps the "simple", "human-facing" API is just dictionaries corresponding to the pydantic fields?

Yep, that's effectively what is happening in [PR #3327](https://github.com/napari/napari/pull/3327) - the user passes in a `dict` and Pydantic matches the first type of model (out of the ones defined in a `Union`) that can be constructed with those field names and values. If none can, it will error.

However, this approach does mean you have to be careful/deliberate about the names/types of fields you give the models, and the order in which they appear in the `Union`.

> Though I guess "type" doesn't fit into that model... Perhaps it could?

I think it could fit in at least a couple of ways.

1. It affects the behavior of its corresponding class instance (e.g. maybe it's an Enum and some method does something differently depending on its value).
2. It's a constant that has a one-to-one correspondence with its class name, but helps us resolve some of the potential ambiguities described above when Pydantic tries to parse the dictionary. I think @tlambert03 showed something similar using `Literal`.

**Comment by brisvag** [comment]
On second thought, it might be cleaner and even more performant to simply slice in napari and send less points to vispy, rather than doing this in the shader and having to send more data to the gpu.

**Comment by sofroniewn** [comment]
I think we can close this as it will be superseded by #3625

**Pull request closed without merging**
