### PR TITLE
Update menu sorting tests still using `mock_app` and `get_app` instead of `mock_app_model` and `get_app_model`

### PR DESCRIPTION
**Pull request by dalthviz**
# References and relevant issues

CI over main is failing due to the issue this PR fixes

# Description

Since PR #7269 and PR #7266 where being worked on in parallel merging both caused some tests to fail (due to their usage of `mock_app` and `get_app`)

### CODE REVIEW

**Review by lucyleeow — APPROVED** [review]
Lets get this in!

**Review by psobolewskiPhD — APPROVED** [review]
thanks! fixes some failing tests, so lets merge asap

**Comment by lucyleeow** [comment]
Do you want to merge now (once CI green) then @psobolewskiPhD  ?

**Comment by psobolewskiPhD** [comment]
@lucyleeow heck no! I'm merge-averse, unless egged on in a zoom call 😅

**Comment by lucyleeow** [comment]
@jni likes pushing the green button, lets ping him

**Comment by psobolewskiPhD** [comment]
It's blue for me!

**Comment by DragaDoncila** [comment]
@lucyleeow @psobolewskiPhD y'all are shocking 😂 I'm merging now

**Comment by DragaDoncila** [comment]
Thanks @dalthviz, obviously I'm *too* trigger happy with the merge button since I created one PR and reviewed the other 🫣

**Comment by lucyleeow** [comment]
I do recall thinking that the 2 PRs would conflict but forgot to say anything about it!

**Comment by jni** [comment]
Came here investigating the failure in #7251 and I deeply enjoyed the discussion above 😂❤️

**Pull request merged**
