### PR TITLE
Simplify the colormaps list and add the single-color colormaps

### LINKED ISSUE #97: Add basic colormaps
## 🚀 Feature

As discussed in #89 it would be nice to add some standard colormaps that people might want to use (particularly in biology) like the following:

> Blues - black to blue
Reds - black to red
Greens - black to green
Magenta - black to magenta
Yellow - black to yellow
Cyan - black to cyan

It might also be nice to add some standard diverging ones too like red to blue through white or red to blue through black - though I don't think we want to try and make an exhaustive list

Similarly looking through the list of colormaps now it seems like there are some that could be removed as they are less popular

### PR DESCRIPTION
**Pull request by jni**
# Description

Fixes #97 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Do you want to fix the `examples/set_colormaps.py` so that it now uses the built in colormaps - or is it nice to have an example of setting custom colormaps? I could go either way, but if we want the latter we should probably have an example that no longer just uses the built-ins

I'm also still not completely sure we need all the remaining ones like `twilight` and `twilight-shifted` - did you intentionally leave those ones in there as we know they are useful?

I also find the order of the list confusing now, can you maybe make it alphabetical?

Finally, how would you feel about adding some two color diverging ones, like RdBl (or RdWBl) that start at a color, pass through black / white, then go to a color. Do we have a theory on how we want to handle these?

**Comment by jni** [comment]
> Do you want to fix the examples/set_colormaps.py so that it now uses the built in colormaps - or is it nice to have an example of setting custom colormaps? I could go either way, but if we want the latter we should probably have an example that no longer just uses the built-ins

I still want that example. I agree that different cmaps from defaults might be useful but then the example should be totally reworked — I don't think it should hold that PR. It still illustrates the use case.

> I'm also still not completely sure we need all the remaining ones like twilight and twilight-shifted - did you intentionally leave those ones in there as we know they are useful?

These are cyclical colormaps that have been designed to be perceptually uniform. I think that's a very useful alternative to hsv (the usual cyclical colormap). Think of a "phase" or "orientation" image where black is down, white is up, blue is right, and red is left. Much more intuitive than hsv.

> I also find the order of the list confusing now, can you maybe make it alphabetical?

Yes, good point.

> Finally, how would you feel about adding some two color diverging ones, like RdBl (or RdWBl) that start at a color, pass through black / white, then go to a color. Do we have a theory on how we want to handle these?

Yeah Ok, I'll add back RdBl, I think that's the best there is currently, though it's not a "modern" one like viridis and twilight.

**Comment by jni** [comment]
@sofroniewn please have a look at the diverging colormaps [here](https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html). I think the best one is `PiYG`, which is what I've left on there. Let me know if you have a different preference. None of them go through black, interestingly.

**Comment by jni** [comment]
This should be ready for merging — leaving the example for future work

**Comment by sofroniewn** [comment]
`PiYG` is fine for now, we can always add more in the future after #268 is implemented. I'll merge

**Pull request merged**
