### PR TITLE
[WIP] Create executable using pyinstaller and tests  on azure pipelines.

### PR DESCRIPTION
**Pull request by Czaki**
# Description
During prepare of embedding napari in my application I would like to identify all possible problem connected with napari. So I apply test scheme and pyinstaller build scheme to napari. 

From my projects I have bad experience with using pyinstaller on anaconda. Now I prefer to use CPython distribution. 

1. This PR can boost #496 or replace it (napari related things are bring from this PR). 
2. PR is to add information about problem connected with napari on azure pipelines (OpenGL on windows - I need help with this)
3. Introduce tox. 

result of build can be seen here https://dev.azure.com/bokota/open%20source%20contrib/_build?definitionId=8&_a=summary

PyInstaller support of PySide2 is worst than PyQt5. I need to change backend on macos and windows, because PySide2 base build fails during time of execution. It looks like it need additional hooks for PySide2. (Here you see why I look for PyQt5 support)

Even If it will not be finally merged to napari please keep it until all problems are fixed:

- [ ] OpenGl test on windows
- [ ] Icons problem on linux. 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# References

# How has this been tested?

Download result of pipeline on each system and test if it launch. 

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

@sofroniewn can you look on this. Did you know who can help with OpenGl?

### CODE REVIEW

**Comment by tlambert03** [comment]
Thanks again for all the great PRs @Czaki,
I realize it doesn't look like there is much activity at #496, but I've actually been working on it a lot over the last few days in my branch: https://github.com/napari/napari/compare/master...tlambert03:pr/sofroniewn/496
I have it working with pyside2 in that branch, and I've been trying to come up with a strategy to allow people to extend it with plugins after bundling (see #1074).  It'd be nice if we could keep all of the pyinstaller activity on the #496 thread rather than creating a new one.  (It's a major feature that we're all very excited to include, but there's a lot of moving parts)

are you proposing here that we add azure pipelines to our tests?  or is this just something you're working on on the side for your project?

Regarding OpenGL in virtualized environments... there is a lot to be said there.  I would recommend starting with https://github.com/napari/napari/issues/799#issuecomment-565859004, https://github.com/napari/napari/issues/896#issuecomment-577321885, https://github.com/napari/napari/issues/886, and perhaps [this one](https://github.com/vispy/vispy/issues/78) at Vispy.  I can't claim I fully understand it... but after looking into it for a while it definitely seems like a hard problem due to limited support for openGL2.0 on many virtualized window servers.  I think  [virtualGL](https://www.virtualgl.org/) might be a potential solution ... but it will take some research.

**Comment by Czaki** [comment]
> I realize it doesn't look like there is much activity at #496, but I've actually been working on it a lot over the last few days in my branch: https://github.com/napari/napari/compare/master...tlambert03:pr/sofroniewn/496
I have it working with pyside2 in that branch, and I've been trying to come up with a strategy to allow people to extend it with plugins after bundling (see #1074). It'd be nice if we could keep all of the pyinstaller activity on the #496 thread rather than creating a new one. (It's a major feature that we're all very excited to include, but there's a lot of moving parts)

I agree, but there are few reasons:
1) I'm not a maintainer of napari, so I only can create PR to PR or leave comment. First solution is weak for this moment because #496 need to be rebased. This PR have few important difference, which may be hard form me to explain in comments so I decide to create PR to show it.
2) This PR base on CPython, not Anaconda.
3) I switch to PyQt5 backend which is better supported by PyInstaller. 
4) I force to create `napari/resources/_qt_resources_*.py` during bundling time (versioner create some problems)

But I will be happy if both cases. If this PR is merged or if strong part of this PR will be moved to #496. 

> are you proposing here that we add azure pipelines to our tests? or is this just something you're working on on the side for your project?

Hard question.
Running on  azure pipelines allow to use CPython, current solution base on Anaconda. It can make difference. 
I would like to have at least information about deal with OpenGL in documentation. 

So I try to solve OpenGL problem basing on your links.

**Comment by tlambert03** [comment]
@Czaki, now that we've closed #496 and #1289 is pretty much working, is it ok with you if we close this PR?

**Comment by Czaki** [comment]
Briefcase looks promising. I do not understand why its ceeate installer on Windows.

But as i chcek pyinstaller is not compatible with napari plugin system. So close this PR.

If briefcase works well with napari I propably would ask few qestions on zulip because i still think if I could apply it to my software.

**Comment by tlambert03** [comment]
>  I do not understand why its create installer on Windows.

as opposed to something like a portable executable?  I assume they went with the .msi installer as the default bundler because it lets you integrate nicely into the start menu, and adds an uninstaller, etc... but I don't know much about the various windows install methods.  I will point out that the code is pretty nicely organized such that that if you wanted a different type of bundle, you can probably create a new template for it (it would go in [this folder](https://github.com/beeware/briefcase/tree/master/src/briefcase/platforms/windows))

> If briefcase works well with napari I propably would ask few qestions on zulip because i still think if I could apply it to my software.

sure,  happy to share what we've learned.  There's some good discussion in #1074 and #1289, and you can try the [latest bundles](https://github.com/napari/napari/pull/1289#issuecomment-647062277) as an example if you'd like.

**Pull request closed without merging**
