### PR TITLE
Do not start notification timer if window is not active.

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues
alternative to #7114

# Description

In this PR, we prevent to start fade out timer for notification dialog if the parent window is not active one.

### CODE REVIEW

**Comment by Czaki** [comment]
@psobolewskiPhD could you check this if this solves your problem?

**Comment by psobolewskiPhD** [comment]
Yeah this works.
Can test using the plugin manager -- just go offline and it will give a warning notification.
I don't think this is an alternative to #7114 rather a complement. They two work together well.

**Comment by DragaDoncila** [comment]
I am +1 on this regardless of what we decide on in 7114. I pulled it down to play with it, and trying out @psobolewskiPhD's suggestion with going offline and using the plugin manager I found that the warning **never** gets dismissed? I thought it was because I hovered over it so I made sure to move the plugin manager and everything but the warning persisted. Is it just PEBCAK? Also I think test failures are possibly related?

**Comment by Czaki** [comment]
Yes. Currently, the implementation does not start timer again after getting focus, as user may want to review multiple one. 
I may think to change this. For example, starting timer for top one, and when it disappears, start the next timer.

**Review by willingc — APPROVED** [review]
Makes good sense. Thanks.

**Comment by willingc** [comment]
@Czaki @psobolewskiPhD Do you wish to move this PR and #7114 forward together? Both seem like good additions.

**Comment by Czaki** [comment]
I have mixed feelings for #7144. It happens, that if I work with mouse bindings, I generate sometimes hundreds of warnings with one mouse move. 

I do not want to need to manually close all of them.

**Comment by willingc** [comment]
> I have mixed feelings for https://github.com/napari/napari/pull/7144. It happens, that if I work with mouse bindings, I generate sometimes hundreds of warnings with one mouse move.

Probably makes sense to land this PR and further discuss the other PR.

**Comment by DragaDoncila** [comment]
> For example, starting timer for top one, and when it disappears, start the next timer.

I think this is a good idea... Otherwise we're back to the same issue as in #7114, where if you get spammed with a warning/error you have to dismiss each one, right?

**Comment by DragaDoncila** [comment]
@Czaki I thought you were going to make the change where you start the timer on the topmost notification once the window becomes active again? But if you want to do that in a follow-up PR that's fine just lmk and I'll approve

**Comment by Czaki** [comment]
> @Czaki I thought you were going to make the change where you start the timer on the topmost notification once the window becomes active again? But if you want to do that in a follow-up PR that's fine just lmk and I'll approve

Such change will be more complex, I prefer to merge this one and start separate PR, as there may be discussion about implementation.

**Review by DragaDoncila — APPROVED** [review]
Sounds good @Czaki let's get this in and iterate then! Would be good to add a test eventually once we move to the one-by-one dismissal.

**Pull request merged**
