### PR TITLE
Remove sphinx dependency from defaults dependecies

### PR DESCRIPTION
**Pull request by JoOkuma**
# References and relevant issues
Discussed in [zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/napari.20sphinx.20dependency)

# Description
Removes sphinx pinned dependencies from napari default dependencies.

### CODE REVIEW

**Comment by JoOkuma** [comment]
cc @melissawm, she added this line previously.
I hope this doesn't break anything.

**Comment by psobolewskiPhD** [comment]
Tested this following: https://napari.org/dev/developers/documentation/index.html
- checked out this pr
- made clean 3.10 env
- `pip install .[dev]`
- got sphinx 7.2.6
then went to my docs repo:
- `python -m pip install -r requirements.txt`
- got sphinx 4.5.0, but also: 
```
sphinx_design                 0.4.1
sphinx_external_toc           0.3.1
...
myst-nb                       0.17.2
myst-parser                   0.18.1
```
(all of which are fine with sphinx <6 so maybe the <5 in docs and theme isn't needed anymore either, see https://github.com/napari/napari-sphinx-theme/issues/121 )
- did `make docs`
waited a while while napari popped up over and over...
got a buncha warnings, but everything built ok?
We'll see if CI does build right.

**Comment by psobolewskiPhD** [comment]
Rendered docs on CI look fine too as far as I can tell:
https://output.circle-artifacts.com/output/job/2bd1c144-ca88-44cd-8512-d0173aa5282a/artifacts/0/napari-docs/docs/_build/gallery.html

**Comment by psobolewskiPhD** [comment]
Oh, I don't think this change is actually being used by CI. Need to update the constraints.

**Comment by JoOkuma** [comment]
> Oh, I don't think this change is actually being used by CI. Need to update the constraints.

@psobolewskiPhD is that done automatically or should I update it?

**Comment by Czaki** [comment]
For automatic upgrade, it requires #6211, but if it is not merged fast then it will require manual intervention.

**Comment by Czaki** [comment]
@napari-bot update constraints

**Review by melissawm — APPROVED** [review]
This is safe here, and the actual constraint can be then enforced in the docs repo. Thanks @JoOkuma !

**Comment by Czaki** [comment]
@JoOkuma Could you update PR with output of @napari-bot update constraints ?

**Comment by JoOkuma** [comment]
Thanks for the heads up @Czaki, I didn't realize it had to be done.

**Comment by Czaki** [comment]
> Thanks for the heads up @Czaki, I didn't realize it had to be done.

it is required to validate if test pass after bump sphinx versions

**Comment by Carreau** [comment]
This got the "Ready-to-merge" label 2 days ago and got no objections. Merging to move the queue forward. 

Thanks.

**Comment by jni** [comment]
@Czaki @melonora is there a reason not to backport this to 0.4.19?

**Comment by Czaki** [comment]
Allow people to use newer sphinx since 0.4.19?

**Comment by jni** [comment]
Yes. I think upper pins can be very harmful when solving environments, so it's important to avoid them unless they're truly necessary.

**Comment by Czaki** [comment]
But I prefer to not cherry-pick this (because of constraints). but will introduce this change in 0.4.19

**Pull request merged**
