### PR TITLE
Vispy 0.14

### PR DESCRIPTION
**Pull request by brisvag**
# Description

Just a simple bump to our vispy dependency, now that 0.14 is out. This comes with a few fixes and new features relevant for napari:

- Fix for wrong spherical marker depth: https://github.com/vispy/vispy/pull/2506
- Fix for wrong shading of surfaces with flipped normals: https://github.com/vispy/vispy/pull/2493
- picking filters for mesh and markers by @aganders, which can now be used in napari to drastically speed up our get-status: https://github.com/vispy/vispy/pull/2500

### CODE REVIEW

**Comment by Czaki** [comment]
I'm working on fix update dependencies workflow, but now you need to manually bump vispy in requirements or wait a few days.

**Comment by Czaki** [comment]
@brisvag It looks like we need to bump minimum numpy version for this PR.

**Comment by brisvag** [comment]
I don't understand what changed/which version we should then get... This error is not very helpful :/

**Comment by Czaki** [comment]
@napari-bot update constraints

**Comment by jni** [comment]
@brisvag did you really make this PR from your main branch? That is a rookie mistake! 😂

**Comment by brisvag** [comment]
> @brisvag did you really make this PR from your main branch? That is a rookie mistake! 😂

Lol, I was hoping to get away with it without anyone noticing xD Anyways I never use the main branch on my fork, so it doesn't bother me much in the end :P

**Comment by brisvag** [comment]
After digging, finally found the problem and opened a vispy PR to hopefully fix it: vispy/vispy#2535

**Comment by brisvag** [comment]
@napari-bot update constraints

**Review by Czaki — APPROVED** [review]

**Pull request merged**
