### PR TITLE
Bump python from 3.9 to 3.12 in pre-release tests

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues

Spotted in https://github.com/scikit-image/scikit-image/issues/7385: as many packages follow [SPEC0](https://scientific-python.org/specs/spec-0000/), they have already dropped 3.9 and may soon drop 3.10 from their builds. This means that we cannot detect pre-release issues if those packages update and we are only testing on 3.9. This PR bumps the pre-release testing to the latest Python version as of this writing.

# Description

Use python 3.12 in pre-release tests. Drop pyside2 as it does not support never python.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Maybe worth adding PyQt6 to the matrix?

**Comment by Czaki** [comment]
PyQt6 is failing with modifiers test

**Comment by Czaki** [comment]
@dalthviz It is failing on test that you have introduced. Did you have any idea what may happens?

**Comment by dalthviz** [comment]
Thanks for the ping! I checked locally on macOS with Python 3.12 and PyQt6 6.6.1 but seems like there the tests related with the shortcuts editor widget work :thinking: . Some suggestions though:

* Increase  `timeout` for the `waitUntil` checking for widget focus.
* Change check for widget focus to something that uses a `waitSignal` with the [`QApplication.focusChanged`](https://doc.qt.io/qt-6/qapplication.html#focusChanged) signal when doing the qtbot click/double click. Also, we could get a reference to the line edit widget with that instead of relying on `QApplication.focusWidget()`

If I do a PR from my fork to your branch fork would that trigger a CI run to check if something of the above helps @Czaki ?

**Comment by Czaki** [comment]
> If I do a PR from my fork to your branch fork would that trigger a CI run to check if something of the above helps @Czaki ?

I think we should try

**Comment by dalthviz** [comment]
Created PR https://github.com/Czaki/napari/pull/37

**Comment by psobolewskiPhD** [comment]
I'm having a hard time figuring out which packages have prerelease versions installed? It doesn't appear to be PyQT6 anyways...

**Comment by Czaki** [comment]
@psobolewskiPhD Our only macOS test for PR is against pyqt5. So it may not be related to pre-release. But merging failing workflow is not the best idea.

**Comment by psobolewskiPhD** [comment]
Oh I didn't realize that we had no pyqt6 tests on macOS.

**Comment by psobolewskiPhD** [comment]
I'm on 3.12 pyqt6 and the tests also pass locally for me ☹️

**Comment by Czaki** [comment]
Hm. At this moment, I think that we should exclude PyQt6 and macOS case from this PR to get half working workflows and move fixing to separate PR? 

@psobolewskiPhD @dalthviz?

**Comment by dalthviz** [comment]
> I think that we should exclude PyQt6 and macOS case from this PR to get half working workflows and move fixing to separate PR?

Makes sense to me and also happy to help with checking a fix for the PyQt6 + macOS case in a follow up PR :+1:

**Review by jni — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
I'm fine with this, but does it makes sense to xfail those tests on macOS instead, so some testing is run? Could help us ID -- issues like this one? -- in advance.

**Comment by Czaki** [comment]
> I'm fine with this, but does it makes sense to xfail those tests on macOS instead, so some testing is run? Could help us ID -- issues like this one? -- in advance.

I think that we should have pre-release "working" as fast as possible and then think how to fix it in followup PR.

**Review by psobolewskiPhD — APPROVED** [review]

**Comment by Czaki** [comment]
@dalthviz most probably will have time to play with a problematic case at the end of next week. So feel free to try earlier if you wish.

**Pull request merged**
