### PR TITLE
Only show main window on linux once event loop starts

### LINKED ISSUE #2233: Missing user warning - qt event loop should be started before launching napari
## 🐛 Bug

Failing to use the `%gui qt` magic in ipython/jupyter before launching napari no longer shows you a handy warning message explaining 

## To Reproduce

1. `conda create -n napari-testenv python=3.7 pip`
2. `conda activate napari-testenv`
3. Start `ipython` and then import napari and show the viewer.
```python
import napari
viewer = napari.Viewer()
```

You'll see this blank, black napari window (not what we want), and there is no error message explaining that the user should try to use `%gui qt` before starting napari.

napari-black-screen

## Expected behavior

I expected a warning message to be printed to the terminal, telling the user that they should start the qt loop (with `%gui qt` or similar) before starting napari.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.2.4.dev736+g79ab358
Platform: Linux-5.8.0-41-generic-x86_64-with-debian-bullseye-sid
System: Ubuntu 20.04.2 LTS
Python: 3.7.9 | packaged by conda-forge | (default, Dec 9 2020, 21:08:20) [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.1
SciPy: 1.6.0
Dask: 2021.02.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen #1: resolution 1920x1080, scale 1.0
- screen #2: resolution 1920x1080, scale 1.0

Plugins:
- svg: 0.1.4
```
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
fixes #2233.
I think this fixes the black box that @GenevieveBuckley saw in #2233 by delaying the showing of the MainWindow on linux until the event loop starts.  tested on ubuntu 20.04

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
I don't think this actually fixes https://github.com/napari/napari/issues/2233

It stops the black window from popping up, sure. But https://github.com/napari/napari/issues/2233 is about the lack of warning displayed to the user if they make a common mistake (forgetting `%gui qt`). There is no window, but there is also no error message - and we want a helpful hint to guide users to the right way to do things.

**Comment by GenevieveBuckley** [comment]
To give you an example, I've checked out this branch and then tried a very basic "hello world" type workflow.

```python
import napari
from skimage.data import camera
viewer = napari.Viewer()
viewer.add_image(camera())
```

If I start ipython and then the qt event loop with `%gui qt`, the example works as expected.

If I start ipython, **but do not start the qt event loop**, then the example doesn't show me any kind of error & also does not display any napari window. I'd expect to see an error message here, like the one we used to have. 

EDIT: I don't think it's helpful that you can force the napari window to appear with `napari.run()` in the second situation, for the reasons described earlier - it blocks you from continuing to the ipython console.

**Comment by jni** [comment]
@GenevieveBuckley 

> EDIT: I don't think it's helpful that you can force the napari window to appear with napari.run() in the second situation, for the reasons described earlier - it blocks you from continuing to the ipython console.

Are you sure about this? With this PR, on a totally new environment and with no IPython profile, your example does not block and I am able to call `napari.run()`:

napari-no-qt
napari-run

Having said that, while trying to reproduce your issue, I *did* encounter this bizarre behaviour: if I try to *quit IPython* without calling `napari.run()`, the viewer gets created anyway!

napari-exit-from-ipython

It's like we've decided, "goddammit, if you called me you better look at me, you ain't leavin' till you do so!" :joy: @tlambert03 any ideas? :joy:

**Comment by GenevieveBuckley** [comment]
Wait, you can use the ipython console after calling `napari.run()`? While the napari window is still open, you haven't closed it?

Your second screenshot there looks very much like my "blocked" state, so I'm not sure what you did to get the next ipython terminal line to become available. (It is possible I'm tired and starting to do silly things)

**Comment by jni** [comment]
> Wait, you can use the ipython console after calling napari.run()? While the napari window is still open, you haven't closed it?

No, no, at that point, the terminal blocks. But this is expected. Similarly, if you run a `with napari.gui_qt()` context, the context blocks you until you close the viewer. Also, if you run `plt.imshow(image); plt.show()`, the terminal will block. But they always block while the user is interacting with a different UI element. The `%gui qt` magic is *always* required for interactivity.

Right, I just reread your original message and I misunderstood it. Sorry about that. **Edit** I had thought you were writing that your terminal was blocking after `add_image`, not after `napari.run()`.

Yes, the above is expected behaviour, and *should* work this way. I guess you are saying, if you're in IPython, you should always warn users to use `%gui qt`. I guess that can be argued, but it's a different issue from the black window. matplotlib does *not* warn users, to give one example of current practice...

**Comment by tlambert03** [comment]
> But #2233 is about the lack of warning displayed to the user if they make a common mistake (forgetting %gui qt). There is no window, but there is also no error message - and we want a helpful hint to guide users to the right way to do things.

@GenevieveBuckley, I commented on this in https://github.com/napari/napari/issues/2233#issuecomment-775020218, but it seems to have gotten lost in the ensuing conversation.  The central point here is that it is _no longer a mistake to forget `%gui qt`_ and that's why the error message was removed.  It used to be a "mistake" because you need to create a QApplication before you instantiate a widget, but we now create that application automatically before instantiating the widget.

I personally feel rather strongly that having  `napari.gui_qt` was a mistake in the first place (it conflated the concepts of "creating a QApplication" and "running a QApplication"), and I don't believe there should be an error if you simply want to create a napari viewer but never look at it.  (Please do have a look through the comment I linked to at https://github.com/napari/napari/pull/2056#discussion_r550924887 as it explains that concept in greater detail)  This has huge implications for running headless, or for trying to use napari to coordinate a data pipeline.  You just don't always need to call `app.exec_` (and, in fact, you only _need_ to create an application, as `%gui qt` does, if you want to visually look at the viewer).

I understand that people are "used" to the way it was, where it was an error to try to create a viewer without having called `%gui qt` or `napari.gui_qt`, but for all the reasons explained in https://github.com/napari/napari/pull/2056#discussion_r550924887, I think that's an unfortunate historical detail, not something we should be aiming for, and I don't believe it should be there.

> If I start ipython, but do not start the qt event loop, then the example doesn't show me any kind of error & also does not display any napari window. I'd expect to see an error message here, like the one we used to have.

you could say the same thing about `matplotlib.pyplot.figure()` ... why doesn't _it_ show my anything until I call `plt.show()`?  The reason there is the same... it's not an error to simply create an object that may eventually be viewable. We shouldn't force napari into a "headfull" state.  `% gui qt`, `napari.gui_qt` and `napari.run` (or hey, even just `QApplication.instance().exec_()` all work to show the viewer and start the event loop, but I don't think it should be an error just to create a Viewer without asking to see it.

> Are you sure about this? With this PR, on a totally new environment and with no IPython profile, your example does not block and I am able to call napari.run():

@jni, don't you have `%gui qt` in your ipython profile?  If so, nothing will ever block for you.  `napari.run()` _should_ block if run in IPython without using `%gui qt` ... (see explanation in https://github.com/napari/napari/pull/2056#discussion_r550924887)

> I guess you are saying, if you're in IPython, you should always warn users to use %gui qt. I guess that can be argued, but it's a different issue from the black window. matplotlib does not warn users, to give one example of current practice...

I think this is the crux of it.  I feel relatively strongly that it was a mistake in the first place...  If you look at the error itself and what was raising it,  it becomes clearer

https://github.com/napari/napari/blob/35c9fa19a58d0b6245cdfb186a2e085612dfc729/napari/_qt/qt_main_window.py#L74-L90

We were raising an error if there was no `QApplication.instance()` before the viewer was created, _not_ if they created a viewer without running the event loop with `QApplication.exec()` ... unfortunately, the error message used the phrase "napari requires a Qt event loop to run."... which is unrelated to why that error message needed to be in `Window.__init__`.  So again, i think it's a feature, not a bug, that that error message has been removed.

**Comment by jni** [comment]
@tlambert03 

> @jni, don't you have %gui qt in your ipython profile? If so, nothing will ever block for you. napari.run() should block if run in IPython without using %gui qt ... (see explanation in #2056 (comment))

No, it was a misunderstanding, I thought @GenevieveBuckley meant that her code blocked *before* she could call `napari.run()`. See:

> With this PR, on a totally new environment and with no IPython profile

and

> Right, I just reread your original message and I misunderstood it. Sorry about that. Edit I had thought you were writing that your terminal was blocking after add_image, not after napari.run().

Actually I just set up a new DL PC today and tried the example there, no bashrc, no IPython profile, nothing. Actually btw I decided to experiment with mamba, the pure C++ implementation of conda, and it is insanely fast. Faster than pip now.

At any rate, @tlambert03 did you see:

> Having said that, while trying to reproduce your issue, I did encounter this bizarre behaviour: if I try to quit IPython without calling napari.run(), the viewer gets created anyway!

and the accompanying screenshot? Can you reproduce that? (IPython then quits *after* I close the viewer. Again, this is with no IPython profile, no bashrc, nothing, brand new machine+env)

**Comment by tlambert03** [comment]
>  no IPython profile 

my bad, sorry

> I decided to experiment with mamba,

oh yeah.  ♥️ 👍

> Can you reproduce that? 

will try later, somehow lost my network driver in ubuntu, so I need to fix it to use again :/

**Comment by GenevieveBuckley** [comment]
> I guess you are saying, if you're in IPython, you should always warn users to use `%gui qt`. I guess that can be argued, but it's a different issue from the black window. 

Yes, this is exactly what I'm saying. The black window is irrelevant to this point.

Edit: I see, we want to change this. I'm going to go look at those discussions now. Sorry I missed that, looks like that was something that happened while I was on leave & I didn't see when I got back.

**Review by sofroniewn — APPROVED** [review]
This LGTM! Should we get it in now @tlambert03 I see now downsides. Maybe you can rebase and then more tests will pass?

**Comment by sofroniewn** [comment]
This now has some conflicts/ test fails since the merging of other PRs

**Pull request closed without merging**
