### PR TITLE
 Fix performance issues 2 - contextmanager preventing updates

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR contains contextmanager from #1945 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality) 
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
This was discussed during the dev meeting today, and it was felt that if we could reduce the time complexity of adding layers to be linear and not quadratic that might mean that we wouldn't need this blocker. I will look into this when i have time

**Comment by Czaki** [comment]
> This was discussed during the dev meeting today, and it was felt that if we could reduce the time complexity of adding layers to be linear and not quadratic that might mean that we wouldn't need this blocker. I will look into this when i have time

Such improvement will work with adding a layer, but I do not see how it could help when do, for example, a massive update of layer properties. Maybe some linear of size cacehe (tree) may help.

**Comment by Czaki** [comment]
I check a few things. I think that the best option could be using the range tree as a cache. This allows us to do most of the queries and changes in logarithmic time.

Did the current signal mechanism allow to provide also previous values? Or it could be good to add the UUID parameter to the past of the class?

**Comment by nclack** [comment]
@Czaki I'm closing this for now as a potentially stale PR.  I opened issue #3549 to track the work which continues to be important!  It looks like the approach here should be reassessed after @andy-sweet's updates to the property system.

**Pull request closed without merging**
