### PR TITLE
Add perfmon directory for shared configs and tools

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description

This adds a dot/hidden `.perfmon` directory to the top of the repo, which stores configs and tools associated with [performance monitoring as described on napari.org](https://napari.org/stable/howtos/perfmon.html?highlight=perfmon). Storing these in the repo makes it easier to reproduce monitoring experiments and results by standardizing configurations and tooling. In particular, I could imagine asking some napari users to use some of these tools to share measurements recorded with this tool to help us better understand napari's performance in the wild.

I'm planning to use these to help understand how running slicing in napari asynchronously affects certain measurements (e.g. the time spent in `Layer.refresh`), which is why I added a config for that here. But I could imagine other areas and configs being use in the future.

The run tool is a simple wrapper that makes it easier to run one of the named configs stored in the repo. The plot/compare tools plot the outputs of this command to generate plots like the following.
 
perfmon-slicing-set_view_slice

I guess this could live outside of the repo, but I thought I'd create this PR and share to see other people think this would be useful.

## Type of change
- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Part of https://github.com/napari/napari/issues/4795

# How has this been tested?
- [x] tested manually

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by Czaki** [comment]
why hidden and why not in resources or tools?

**Comment by liu-ziyang** [comment]
would be good to include a readme in this folder, whether hidden or not, to document usage

**Review by sofroniewn — COMMENTED** [review]
> why hidden and why not in resources or tools?


agreed - i'd probably put inside `tools/perfmon`. If it's inside tools I'm fine with it not being hidden.

> would be good to include a readme in this folder, whether hidden or not, to document usage

agreed

Otherwise looks great. I havn't tried, but I like concept

**Comment by sofroniewn** [comment]
oh also - looks like manifest test is failing and needs to be fixed before merge

**Comment by liu-ziyang** [comment]
@perlman can you please take this PR from here? thanks!

**Review by liu-ziyang — APPROVED** [review]
LGTM!

**Pull request merged**
