### PR TITLE
Add convenience input validation for Labels colormaps

### LINKED ISSUE #6967: We should allow dict and list input to Labels.colormap
## References

ome/napari-ome-zarr#109

## 🚀 Feature

When designing the new labels colormaps API (#6542), we inadvertently forgot about an early design goal of napari: inputs should never be *required* to be exotic objects. *Optional* exotic objects is ok! For example, it should be ok to extract metadata automatically from an xarray. *But* users should not be *required* to provide xarray objects instead of numpy arrays.

In #6542, the new Labels colormaps API requires colormaps to be wrapped in either a CyclicLabelColormap object or a DirectLabelColormap object. This is a problem because now plugins *must* depend on and import from napari in order to provide colormap information. Which I think is pretty terrible!

I propose that if users pass in `add_labels(data, colormap={1: 'red', 2: 'blue'})`, we should automatically construct a DirectLabelColormap for them, and if they do `add_labels(data, colormap=['red', 'blue'])`, we should construct a CyclicLabelColormap for them.

This is also a nice API improvement even when just working with napari directly.

### PR DESCRIPTION
**Pull request by jni**
Closes #6967

From that issue:

When designing the new labels colormaps API (#6542), we inadvertently forgot about an early design goal of napari: inputs should never be required to be exotic objects. Optional exotic objects is ok! For example, it should be ok to extract metadata automatically from an xarray. But users should not be required to provide xarray objects instead of numpy arrays.

In #6542, the new Labels colormaps API requires colormaps to be wrapped in either a CyclicLabelColormap object or a DirectLabelColormap object. This is a problem because now plugins must depend on and import from napari in order to provide colormap information. Which I think is pretty terrible!

I propose that if users pass in add_labels(data, colormap={1: 'red', 2: 'blue'}), we should automatically construct a DirectLabelColormap for them, and if they do add_labels(data, colormap=['red', 'blue']), we should construct a CyclicLabelColormap for them.

This is also a nice API improvement even when just working with napari directly.

**Edit:** In addition to the above, this PR pulls out the numba-accelerated functions from `napari/utils/colormaps/colormap.py` into their own module. This is because the `disable_jit` fixture requires reloading of modules, which can break the relationship between object instances and their classes. See comments starting at https://github.com/napari/napari/pull/7025#issuecomment-2185870081.

### CODE REVIEW

**Comment by jni** [comment]
CC @Czaki @psobolewskiPhD I'd love a fast review/merge here so we can include it in 0.5.0a0. 🙏

**Comment by jni** [comment]
Screenshot 2024-06-24 at 5 58 27 PM

wth I thought I did everything right this time 😂

**Comment by jni** [comment]
```pytb
          if not isinstance(colormap_like, int):
  >           assert isinstance(
                  _normalize_label_colormap(colormap_like), LabelColormapBase
              )
  E           AssertionError: assert False
  E            +  where False = isinstance(CyclicLabelColormap(colors=ColorArray([[1., 0., 0., 1.],\n            [0., 0., 1., 1.]], dtype=float32), name='custom',...zero'>, controls=array([0. , 0.5, 1. ], dtype=float32), use_selection=False, selection=0, background_value=0, seed=0.5), LabelColormapBase)
  E            +    where CyclicLabelColormap(colors=ColorArray([[1., 0., 0., 1.],\n            [0., 0., 1., 1.]], dtype=float32), name='custom',...zero'>, controls=array([0. , 0.5, 1. ], dtype=float32), use_selection=False, selection=0, background_value=0, seed=0.5) = _normalize_label_colormap(['red', 'blue'])
  
  napari/utils/colormaps/_tests/test_colormap.py:531: AssertionError
```

(a) Do I not understand how isinstance works?
(b) This test actually passes locally... 🤔

**Comment by Czaki** [comment]
> (b) This test actually passes locally... 🤔

It passes if you execute the given test. It fails if you executed the whole file. 

The problem is caused by `_disable_jit` fixture that reloads

**Comment by jni** [comment]
> The problem is caused by _disable_jit fixture that reloads

??? Sorry can you explain this? (Why would the above test fail that way?)

**Comment by jni** [comment]
I dislike that there's some nonlocal effects happening here — I'd like to understand the effects rather than ac1443d which makes the tests harder to follow or modify in the future. Why is the fixture being called multiple times by my adding of a test, and why is calling it multiple times a problem — can that be fixed instead?

**Comment by jni** [comment]
Had a call with @Czaki who explained the issue. Basically, `isinstance(obj, Class)` was failing because at some point during testing, we reload the whole `colormaps` module — so `LabelColormapBase` is no longer the `LabelColormapBase` that `obj` knew and loved, but an impostor doppelganger from a parallel universe.

The reason for this reload is that, in order to measure coverage of numba-compiled functions, we need to disable the numba jit compiler, *after* things have already compiled and imported.

The solution is implemented by @Czaki (🙏!) in 03d3f0c: moving all numba function to their own module, so that *only* that module is reloaded, not the full colormaps.py module.

**Comment by brisvag** [comment]
> The reason for this reload is that, in order to measure coverage of numba-compiled functions, we need to disable the numba jit compiler, _after_ things have already compiled and imported.

I remember this biting me in the back many times in ipython with `%autoreload`... Nasty one to track down if you've never seen it.

**Comment by jni** [comment]
Ok, this is ready for review and needs to be merged before 0.5.0a0 so I would appreciate a review! Ideally from someone other than @Czaki since he contributed a major chunk of it, but I'm happy to say that I reviewed your work @Czaki and you reviewed mine. 😉 I'll just update the description to include the accelerated_cmap fix.

**Comment by jni** [comment]
@brisvag if you can review (🙏), it's probably best to review the first three commits:

https://github.com/napari/napari/pull/7025/files/7f95d020489c3ad645b9d86341cb66951df99e5e

and the last four commits:

https://github.com/napari/napari/pull/7025/files/7f95d020489c3ad645b9d86341cb66951df99e5e..ad687a45c152f2e031730dda9e851d93e7a98e9d

separately, as they do different things. I actually started splitting them out into a separate PR, but they touch the same files so it would be super annoying to figure out the merge conflicts.

**Review by brisvag — APPROVED** [review]
All makes sense to me :)

EDIT: yeah I found the split as well!

**Comment by psobolewskiPhD** [comment]
@jni
I met with a user today and showed the labels with features example:
https://napari.org/stable/gallery/add_labels_with_features.html#sphx-glr-gallery-add-labels-with-features-py
Should we update it with the simplication from this PR?
Just pass the dict directly?
```
label_layer = viewer.add_labels(
    label_image,
    name='segmentation',
    features=label_features,
    colormap=colors,
)
```
Or maybe just add a comment that in lieu of passing `DirectLabelColormap` one can just pass a dict?

**Comment by jni** [comment]
Yeah, I'm sorry I didn't update the example — I think it makes sense to update it to use the dict directly *and* add a comment, "internally, this gets converted to a `napari.utils.colormaps.DirectLabelColormap`".

**Pull request merged**
