### PR TITLE
FEAT: Tier One Java support.

### PR DESCRIPTION
**Pull request by Carreau**
I think that at least for about the next 24 hours, this should be merged
in master even if reverted on April 2cd.

In the long run, I think napari should ship with at least 1 image
dataset from the same source as the one I add here as an easter-egg.

# Description

Q: What does this pull request (PR) do? Why is it necessary?
A: You now why, just look at the diff.

Q: Tell us about your new feature, improvement, or fix!
A: This is a clear design improvement.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
It should always had first tier java support

- [x] This change requires a documentation update
We may want to replace all instances of the "napari" string in docs.

# How has this been tested?

Does it really needs tests ?

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
☕️

**Review by liu-ziyang — APPROVED** [review]
LGTM!

**Review by nclack — COMMENTED** [review]
Committing a jpg?  Going to need another repo for that.

**Comment by Carreau** [comment]
I'll let someone in US merge so that AU wakes up to Juan face, and we can revert in 48h or so :-)

**Comment by liu-ziyang** [comment]
by any chance we can include an ascii art instead of jpg? we can probably leave it permanently in the code base as an easter egg anyway

**Comment by jni** [comment]
Hi all, I appreciate the sentiment and ImageJuan is genuinely funny 😂, but to me it's not worth adding another image to the history forever. ([discussion here](https://github.com/napari/napari/pull/3815#issuecomment-994581764)). Yes it's only 50kb but storage creep is a thing.

I've deleted the commit from main history (in consultation with @sofroniewn), so if any of you have pulled in the meantime, please reset your main branches.

Genuinely sorry to be the party pooper here!!! 😬

**Comment by DragaDoncila** [comment]
Dw @jni you're not a party pooper. This will live on forever in my memory, and in this screen recording which I've thoughtfully uploaded to your favorite file hosting service.

https://user-images.githubusercontent.com/17995243/161183426-ffed9a91-88aa-4152-a86c-d8e0ea4ab99e.mov

**Comment by Carreau** [comment]
> Hi all, I appreciate the sentiment and ImageJuan is genuinely funny 😂, but to me it's not worth adding another image to the history forever. ([discussion here](https://github.com/napari/napari/pull/3815#issuecomment-994581764)). Yes it's only 50kb but storage creep is a thing.
> 
> I've deleted the commit from main history (in consultation with @sofroniewn), so if any of you have pulled in the meantime, please reset your main branches.
> 
> Genuinely sorry to be the party pooper here!!! 😬

No worries, I would have love for it to live a few more hours to got notified for april fools days by a few other people.

**Pull request merged**
