### PR TITLE
Work around numpy's string casting deprecation.

### LINKED ISSUE #2791: pre color test fail from numpy 1.21
## 🐛 Bug

Our pre-tests are currently failing - it's a fairly innocuous fail, so no need to rush a release, but we should fix them. The test is passing an intentionally invalid  `color = ('a', 1, 1, 1)` which is now raising a warning that didn't used to happen. I'm not quite sure how we want to fix, I can see many different ways - but given that no-one should really pass a color with a string in it as long as we do something reasonable I don't mind

```python-traceback
  _________________________ test_invalid_colors[color6] __________________________
  
  color = ('a', 1, 1, 1)
  
      @pytest.mark.parametrize("color", invalid_colors)
      def test_invalid_colors(color):
          with pytest.raises((ValueError, AttributeError, KeyError)):
  >           transform_color(color)
  
  napari/utils/colormaps/_tests/test_color_to_array.py:50: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  napari/utils/colormaps/standardize_color.py:65: in transform_color
      return _color_switch[colortype](colors)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  colors = ('a', 1, 1, 1)
```
...
```python-traceback
  >           color_array = np.atleast_2d(np.asarray(colors))
  E           FutureWarning: Promotion of numbers and bools to strings is deprecated. In the future, code such as `np.concatenate((['string'], [0]))` will raise an error, while `np.asarray(['string', 0])` will return an array with `dtype=object`.  To avoid the warning while retaining a string result use `dtype='U'` (or 'S').  To get an array of Python objects use `dtype=object`. (Warning added in NumPy 1.21)
```

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description
Works around some deprecated behavior in `numpy.asarray`, so that we continue to handle most color conversion cases without any change in behavior.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
closes #2791

# How has this been tested?
- [x] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Thanks for the fix! I'm good with this change. If this helps us avoid a confusing error message and so leads us towards a better one then I think it's the right way to go. For anyone wanting more context, see exchange in #2825. @jni do you have additional thoughts?

**Comment by sofroniewn** [comment]
Surprisingly this is actually causing another test to fail! not quite sure why, but that should be fixed before merge

**Comment by andy-sweet** [comment]
My initial change caused the valid `(None, 'green')` test case to fail, so I changed the logic a little to explicitly use `dtype=object` if some of the elements are strings, which is described as the future behavior of `numpy.asarray` in the deprecation note, and is handled by our code that follows.

I don't really like my solution because it adds a little bit of extra logic to the code, so I also don't mind just ignoring the warning in the test and dealing with the change in behavior when the deprecation is enforced. But I also don't want to spend too much time thinking about this either.

**Comment by sofroniewn** [comment]
> I don't really like my solution because it adds a little bit of extra logic to the code, so I also don't mind just ignoring the warning in the test and dealing with the change in behavior when the deprecation is enforced. But I also don't want to spend too much time thinking about this either.

I completely get you. I think it's ok though. I'll put this in the awaiting merge pipeline now, and if no one raises any concerns will merge as is. All tests are passing and it is an improvement

**Pull request merged**
