### PR TITLE
Add dock icon

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
adds the napari logo to the running application icon... cause who doesn't want this?

Screen Shot 2019-11-28 at 7 13 11 AM

I added the logo.png to `napari/resources/` ... so if this is to be merged, we should discuss whether that's an ok location for that.

side note:  in previous applications, I have used the following code in windows... but it's not strictly necessary for the icon to show up.  I can't remember now why I had to do it.  but here's the [windows docs](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-setcurrentprocessexplicitappusermodelid)
```python        
if sys.platform.startswith("win32"):
    import ctypes

    id_ = f"napari.napari.{__version__}"
    ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(id_)
```

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?
Tested on mac and windows... not yet on linux

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
@tlambert03 love this functionality, will give it a try now - but I think I already added the logo to the repo in #674 to the exact location you mentioned. Does it not show up for you / is there a reason we need to add it again?

**Comment by tlambert03** [comment]
in my repo, the logo is in `resources` at the top level... and I'm not sure that gets shipped with the pypi package?  I put it in `napari/resources`

**Review by sofroniewn — APPROVED** [review]
Ah thanks!!! Let's drop the copy at the top level then. No need for it to be there twice, and shipping with the repo is what we'll want when we make it an icon for the application etc.

I can confirm the functionality works great for me on mac. I am approving, but we should let @jni test on linux before we merge. This is so nice to have

**Comment by tlambert03** [comment]
Just tested successfully on Ubuntu 18.04

**Comment by sofroniewn** [comment]
Ok nice, this has been tested on all major systems - will merge

**Comment by sofroniewn** [comment]
Ah wait - I just saw @tlambert03 you also moved `screenshot-add-image.png` into the main repo. I think this can remain outside the repo - no need for us to distribute that image with the main package. Can you move it back and revert the path change in the readme. Then I will merge

**Comment by sofroniewn** [comment]
Also @tlambert03 curious if you want to weigh in on #567 at some point in time

**Review by sofroniewn — CHANGES_REQUESTED** [review]
see request above for only moving `logo.png` and not `screenshot-add-image.png` into the main repo

**Comment by tlambert03** [comment]
all set!  will weigh in on 567 over there.

**Comment by sofroniewn** [comment]
Thanks so much, will merge once the tests pass!

**Review by sofroniewn — APPROVED** [review]
Thanks so much, will merge once the tests pass!

**Comment by sofroniewn** [comment]
The windows fails here are independent of this PR so I am going to merge

**Pull request merged**
