### PR TITLE
Fix off-by-one bug in extent of Image and Labels layers

### PR DESCRIPTION
**Pull request by grlee77**
# Description

This PR follows up on #3318, which was resolved in #3320 by manually setting size to 1 when it was close to 0. The underlying cause for size=0 with singleton dimensions was not addressed in #3320, though. With the change in the first commit here, size will not be 0 in the case of singleton dimensions in `Image` or `Labels` layers. Justification for the change is given in this prior comment https://github.com/napari/napari/issues/3318#issuecomment-910818247. This change seems desirable to me, but if there is a good reason to not update this extent, please let me know.

Subsequent commits are mainly updating expected ranges by 1 element in tests or other methods as needed for consistency with the change in the first commit. Hopefully, these have all been caught by the test cases, but I tried to also check for any additional usage of `extent` or `Dims.set_range/Dims.range` that might need updated.

In terms of interactive testing, I verified that:

- the dimension sliders still seem to operate over the correct range
- viewing multiple layers in grid mode looks equivalent to before (there are no weird gaps or overlaps in the tiled layers)

This change should be transparent to Napari users. 

It is possible there could be plugins using `Dims.range`, `Dims.set_range` or `Layer.extent` which assume the prior behavior and would now have an off-by-one error.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

It should be non-breaking in terms of Napari itself, but possibly breaking to downstream plugins using `Dims.range` or `Layer.extent`.

It is probably easiest to review the commits here sequentially rather than as a whole.

# References
Related to discussion around this comment: https://github.com/napari/napari/issues/3318#issuecomment-910818247

# How has this been tested?

- [x] all existing tests pass with my change
The expected result sometimes had to be incremented by 1 element to account for the change in range/extent.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

(entirely new test cases were not added, but expected ranges were updated in existing ones)

### CODE REVIEW

**Comment by grlee77** [comment]
On closer look at the history, `Dims.range` was actually using an open interval previously, but was changed to a closed interval in #1696 (related issue #1686). ~This PR is basically undoing that PR (although the `shape` property in that PR had already previously been removed).~ **edit**: after more recent commits there is a 0.5 pixel offset in world coordinates, so not equivalent to reverting the prior PR. There is still a change back to an open interval, though.

Going back to the old behavior would mean still having the issue that for singleton dimensions, `scene_size` in the following code block would still be 0:
https://github.com/napari/napari/blob/5a43dc595f42f077286eb6cbb29b59ac79266767/napari/components/viewer_model.py#L265-L269
(`ViewerModel.camera.center` also differs since it is calculated based on `scene_size`)

**Comment by grlee77** [comment]
The camera center is not currently getting set correctly here. (It is off by 1/2 a pixel spacing). An easy test case for this is saving the following single pixel test data:
```Python
import numpy as np
np.save('/tmp/one_pixel.npy', np.ones((1, 1)))
```
and then opening that file with the napari viewer. After this PR, the square will no longer be centered properly in the display. 

This can be fixed by shifting the `corner` calculation from:
https://github.com/napari/napari/blob/5a43dc595f42f077286eb6cbb29b59ac79266767/napari/components/viewer_model.py#L270
to use instead:
```Python
corner = extent[0] - self.layers.extent.step[np.asarray(self.dims.displayed)] / 2
```

However, perhaps that corner calculation should remain as is, but `extent` should be shifted by 1/2 step instead?

For this one pixel image the `main` branch gives:

    scene_size = (0.0, 0.0)
    viewer.camera.center = (0.0, 0.0)
    viewer.layers[0].extent.world = array([[0., 0.],
                                           [0., 0.]])
    viewer.dims.range = ((0.0, 0.0, 1.0), (0.0, 0.0, 1.0))

whereas for this PR as of (6c8dcfd ) it was:

    scene_size = (1.0, 1.0)
    camera_center = (0.5, 0.5)
    viewer.layers[0].extent.world = array([[0., 0.],
                                           [1., 1.]])
    viewer.dims.range = ((0.0, 1.0, 1.0), (0.0, 1.0, 1.0))


but perhaps it should be (as in later commit a28200e):

    scene_size = (1.0, 1.0)
    camera_center = (0.0, 0.0)
    viewer.layers[0].extent.world = array([[-0.5, -0.5],
                                           [ 0.5., 0.5]])
    viewer.dims.range = ((0.0, 1.0, 1.0), (0.0, 1.0, 1.0))

**Comment by jni** [comment]
> but perhaps it should be:
> 
> ```
> scene_size = (1.0, 1.0)
> camera_center = (0.0, 0.0)
> viewer.layers[0].extent.world = array([[-0.5, -0.5],
>                                        [ 0.5., 0.5]])
> viewer.dims.range = ((0.0, 1.0, 1.0), (0.0, 1.0, 1.0))
> ```

Yup, that looks right to me @grlee77. Thank you very much for this PR, the massive simplification of the code suggests that it's moving things in the right direction. :+1: The main thing I'm worried about is whether everything works "as expected" with fractional scales. I expect that the reason things were the way they were is because an arange with parameters (0, 5*np.pi, np.pi) (or similar) might end up inadvertently including the endpoint and cause an index error. So we'll need safeguards around that.

**Comment by psobolewskiPhD** [comment]
I wonder if this can be related to the 1-px canvas border around images (when zoomed in for example):
https://github.com/napari/napari/issues/3357

**Comment by grlee77** [comment]
Re: @jni:  This has been updated now as discussed in https://github.com/napari/napari/pull/3381#issuecomment-920876625

The offset by -0.5 elements is implemented by [overriding _get_extent_world to have an offset as shown here](https://github.com/napari/napari/pull/3381/files#diff-9e4cd2702cfbb10e85a517ed53426c08d163353b58aab0e13609b4375c1e9780R420-R421) in `_ImageBase` so that it will apply only to `Image` and `Layer` classes. There is no corresponding offset for other layer types such as points or surfaces. 

This results in the camera center being identical to how it was before this PR and the one pixel image opens up centered within the viewer window as desired.


Re: @psobolewskiPhD
> I wonder if this can be related to the 1-px canvas border around images (when zoomed in for example):
#3357

Unfortunately that behavior remains the same as before (I think it is actually a 2 pixel border, though?). I tried to look around a bit to see where it is coming from, but did not succeed so far. I think we may need someone with more VisPy expertise to take a look.

**Comment by grlee77** [comment]
Following up on discussion in the working group on center vs. corner of voxel for the origin (This PR keeps the world coordinate origin at a pixel center). A prior discussion around this was in #2778.

For further examples from medical imaging field:

1.) The [DICOM standard](http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.7.html#sect_C.7.6.2.1.1): 

> Image Position (0020,0032) specifies the x, y, and z coordinates of the upper left hand corner of the image; it is the center of the first voxel transmitted. 

The NIFTI format (popular in neuroimaging software) [states](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h):
> The (x,y,z) coordinates refer to the CENTER of a voxel.

This pixel center origin convention is also documented in the [ITK docs](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html#images) and [3D Slicer docs](https://www.slicer.org/wiki/Coordinate_systems).

**Review by jni — APPROVED** [review]

**Review by sofroniewn — APPROVED** [review]
Very nice! Great job going through and catching all these - I fully agree with the fix. Let's keep an eye out in case there are any similar other errors lurking anywhere. Will merge now

**Pull request merged**
