### PR TITLE
[WIP] Add devcontainer / docker-compose / gitpod configurations for Linux development

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

Adding this option for quick Linux debugging on those machines that cannot run a VM (or if they can, with poor performance). I'll be using this to test the Linux bundles.

It uses Gitpod docker images for VNC. It runs x11vnc and exposes that through a novnc server on port 6080. A regular VNC client can also connect via 5900.

Several ways of using these changes:

* Using remote containers on VS Code
* Using Github Codespaces
* Using GitPod on this branch
* Running `docker compose run napari`

Try now:

[Open in Gitpod](https://gitpod.io/#github.com/napari/napari/pull/3633)

> Current limitation on MacOS: Docker Compose won't expose the ports for some reason. You can still build the images with `docker compose build`, but the container must be run with `docker run -it -p 5900:5900 -p 6080:6080 napari_napari /usr/bin/python3 -m napari`.

Pending implementation details:
* Mount and install the local copy of the repo on Docker compose
* Install the cloned repo on Gitpod
* Optimize image size a bit (Gitpod docker image contains way too much stuff)

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] Run GitPod online and open novnc on sidepanel
- [ ] Run Codespaces online (no idea if novnc is accessible here)
- [ ] Run docker-compose locally and open novnc in your browser (`localhost:6080`)
- [ ] Run VSCode remote containers locally and open novnc in your browser (`localhost:6080`)

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by sofroniewn** [comment]
@jaimergp I see this is still in draft mode. Any interest in marking it ready for review and getting it merged? I'm going through old PRs and trying to get the numbers of open ones down, thanks!! :-)

**Comment by liu-ziyang** [comment]
I see us having a singularity build on top of our docker build effort, I wonder if it is possible to consolidate to one build instead of having multiple builds that we need to worry about, by any chance we can close this or replace the singularity with this?

**Comment by sofroniewn** [comment]
The singularity build just came in through a community contribution. We've also had a lot of requests around the docker build. I think it would be nice to continue to support both. We might want to consolidate them inside a single folder though and add a dedicated readme with additional instructions and context

**Comment by jaimergp** [comment]
I want to work on this once I am done with the bundle pinning stuff!

**Comment by jaimergp** [comment]
Looks like we have `.devcontainer` support already which is good enough. Closing this for now.

**Pull request closed without merging**
