### PR TITLE
host docs

### LINKED ISSUE #473: Hosted docs
## 📚 Documentation

I think now would be a good time for us to start hosting our API docs on a public site. I view this as complimentary to, but connected to our current [tutorials page](https://napari.github.io/napari-tutorials/)

Using readthedocs is fine with me, I don't know if CZI will pay to remove adds, but that would be reasonable. Alternatively there is https://github.com/freeman-lab/minidocs made by our very own @freeman-lab or direct integration with our tutorials page.

Thoughts @kne42 @AhmetCanSolak @jni?

### PR DESCRIPTION
**Pull request by kne42**
# Description
- clean up doc building process
- push to [napari.github.io](https://github.com/napari/napari.github.io) repo for hosted docs (closes #473)

### CODE REVIEW

**Comment by kne42** [comment]
you can find the docs at https://napari.github.io/dev/

once we get a real website we may choose to change the repo name to `docs` or something

additionally, before merge, I will overwrite the repo since these docs (for example purposes) came from a PR

**Review by sofroniewn — APPROVED** [review]
This looks great - poking through the docs themselves it's clear we've got a lot of work to do there, but that can come now.

Also for now it's nice to have all of our doc strings generated - but I could imagine in the future we might want to hide or at least put somewhere else out `_qt` and `_vispy` doc strings. Will that be possible?

**Comment by kne42** [comment]
@sofroniewn yes, we can either generally turn off documentation for privatized modules or specifically ignore these files

**Comment by kne42** [comment]
I just noticed that the commit message is not properly capturing the version so I'll fix that before merge as well

edit: done

**Pull request merged**
