### PR TITLE
Vectors as Vispy Lines (rather than meshes)

### PR DESCRIPTION
**Pull request by brisvag**
# Description
As mentioned in [this zulip conversation](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/vectors.20as.20meshes), depicting vectors as meshes was a choice made a while back based on a few issues that might not exist anymore (see #215, #214). This PR reverts that change; please check it out (especially with OSX) and see if any weird artifacts occur.

If everythign is fine, this PR drastically simplifies the housekeeping work that napari needs to do, as well as making vector visualization more consistent (no changes based on point-of-view).

Antialiasing *could* be activated, but is currently disabled due to the [transparency issues in vispy](https://github.com/napari/napari/issues/3343#issuecomment-923888197).

If this gets approved, I would wait to first merge #3333 and fix conflicts here.

## Type of change

- [x] Change of backed visual (non-breaking change)

# References
- #214
- #215

# How has this been tested?

- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Comment by jni** [comment]
@brisvag would you mind showing some before/after screenshots here?

**Comment by brisvag** [comment]
I notice now that there are a few significant differences with this method:
- line width is in screen space (so inconsistent in data space)
- and can only be changed by integers (rounded up)

As far as I can tell, this are intrinsic limitations of GL lines. They might be solvable using the [`agg` method](https://github.com/vispy/vispy/blob/b51142565883037de6f19d0c31386e72b4fd762b/vispy/visuals/line/line.py#L374), but that's currently unable of doing segments, and might be significantly worse in performance.

I think these changes are significant enough that this can't replace the current mode. However, I can see this being an alternative depiction mode. Maybe we could think about this :)

Here's a screen capture (left is main, right is this PR):

https://user-images.githubusercontent.com/23482191/135226381-62a847cc-6f11-4920-bd1c-8d4689d914dd.mp4

**Comment by jni** [comment]
@brisvag so one question is whether we could tie the vector size to the camera distance, ie do the screen->data scaling manually and updating the visuals as the camera zoom level changes, and whether that would still be simpler/more performant than the current vector/mesh approach. What do you think?

Personally I don't have a strong opinion here, but I do think that vector width scaling in data (world) coordinates is a valuable thing to have and should be the default.

**Comment by brisvag** [comment]
Not sure on the first one... Zooming happens all on the vispy canvas, not sure how hackable that would be, nor how performant.

Actually, i have a half-implemented cylinder impostor visual thst might work for this and do what we need, though not sure on the performance.

**Comment by kevinyamauchi** [comment]
Just getting caught up, but a couple of thoughts that may or may not be useful...

> Not sure on the first one... Zooming happens all on the vispy canvas, not sure how hackable that would be, nor how performant.

I think this is probably not super useful because it doesn't work with perspective, but this is how the vispy Markers visual used to get the scaling:

https://github.com/vispy/vispy/blob/d901f6430784416bacb028e1ff450a3640400e44/vispy/visuals/markers.py#L614-L628

Can you calculate the width in data units by transforming a vector of known length from data to canvas coordinates (the same technique for setting the point width as you implemented in Markers)?

**Comment by brisvag** [comment]
> Can you calculate the width in data units by transforming a vector of known length from data to canvas coordinates (the same technique for setting the point width as you implemented in Markers)?

Yes, that's exactly what I did in my cylinder impostor approach. That won't work with opengl lines, cause the size is a gl "global" variable (https://github.com/vispy/vispy/blob/545abddf3cf5d7e672cb48fe8e68779fc338cc2d/vispy/visuals/line/line.py#L345)

**Comment by sofroniewn** [comment]
@brisvag this now has a couple conflicts. Also how are you feeling about it given some of the caveats above? Do you still think this is the better approach and want to press on?

**Comment by brisvag** [comment]
I don't think it's the better approach at this point. In *might* be worth introducing an "alternative visual" for layers, but this would need some more architerctural changes. I think we can maybe close this PR for now, but keep it in mind for the future. 

To summarise:

---
PROS:
- screen-space width: this is often better, as vector width is more often than not just a visualization parameter than data.
- no POV-dependant visualization: these meshes look weird as you rotate them, since they are made of flat planes.
- faster (in theory, I have not tested)

CONS:
- no way to maintain data-space width, in those cases where this is what a user wants
- width limited to integer pixels, which limits options

Alternatives:
- expand the `agg` drawing method of `Linevisual` to work with segments (might be bad on performance, but looks good)
- use a custom made visual (I have some prototype, but it needs polishing and might not solve all the issues).

**Comment by sofroniewn** [comment]
Ok thanks for summary. Maybe some of those cons can be fixed upstream and then we can revisit. Thanks for the summary. I will close now

**Pull request closed without merging**
