### PR TITLE
support conda-style (pyside2-)rcc locations

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

I ran into same error as #3713 while testing new features in the bundle. conda's pyside will place their binaries in `$CONDA_PREFIX/bin`,  not `$SITE_PACKAGES/pyside2`. This adds the needed logic to search there as well.

However, `$CONDA_PREFIX/bin` will also list `qt`'s `rcc`, which is not compatible with pyside's in version 5.12 (`-g` flag missing). This means we need to try `pyside2-rcc` first, and _then_ `rcc`. I am unaware of the impact of this change beyond conda's so please review carefully!

We can also list the possible paths explicitly in the loop, like:

* `$SITE_PACKAGES/pyside2/rcc`
* `$SITE_PACKAGES/pyside2/pyside2-rcc`
* `$CONDA_PREFIX/bin/pyside2-rcc`
* `$CONDA_PREFIX/bin/rcc`

I also added more explicit output in the exception to understand what's going on with the error.

## Type of change

- [X] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [?] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [X] Bundled napari opens successfully with this change

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
This looks good, thanks!

As a sidenote here, we'll eventually need to drop run-time resource compilation via rcc altogether, since it's no longer included in PyQt6.  See https://github.com/napari/napari/pull/3707 ... but this PR is a quick and easy change in the meantime!

**Comment by Carreau** [comment]
+1, do you want to add a dummy test, checking that when importing  `executables` from `_icon` "pyside" is first ? 
It would be easy in a refactor to assume the order is not important.

**Comment by jaimergp** [comment]
Had to refactor a bit but there it is, @Carreau!

**Comment by jaimergp** [comment]
I am seeing `AttributeError: 'int' object has no attribute 'shape'` errors that I guess are unrelated to this PR.

I hope the conditional xfail on `ModuleNotFoundError` is ok!

**Comment by jaimergp** [comment]
This is passing now @Carreau @tlambert03 

I need this merged to test new changes in the installers, so if it can be merged today, that would be awesome!

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Pull request merged**
