### PR TITLE
Add a MousemapProvider

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR is a fully backwards compatible PR to add a mousefunc provider to be a little more like our keymap provider that can be reused in a variety of objects. We have a couple proposals like #793 and #1048 that would improve our mouse bindings. This PR doesn't do that, and is backwards compatible. It is just done to clean things up before making the viewermodel evented.

I also fix what to me is a bug in our dims scrolling where we use the `1` / `y` value, which is up and down, instead of the `0` / `x` value, which is left and right, and much more natural for me where scrolling moves left to right for a horizontal scroll bar.

It would be nice if there were ways to bind mouse functions to the class instead of the instance, but we don't support that yet. It might be important for the pydantic refactor though.

## Type of change

- [x] Bug-fix/ Refactor (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by sofroniewn** [comment]
~~Ok, I undid a dims scroll direction change to make~~ this PR 100% backwards compatible. Doesn't look like much, but will clean things up a little

**Comment by sofroniewn** [comment]
@tlambert03 can you give this a quick review - it's 100% backwards compatible and internal, so low risk. One of the last `0.4.3` PRs

**Review by tlambert03 — APPROVED** [review]
looks good!  can help make class-bound callbacks later if you need

**Comment by sofroniewn** [comment]
> looks good! can help make class-bound callbacks later if you need

Thanks!! We'll want to revisit this when we do #2066 and I'm not sure yet what the best solution will look like

**Pull request merged**
