### PR TITLE
remove: napari.qt.progress (deprecated in 0.4.11)

### LINKED ISSUE #6250: Remove napari/qt/progress.py
## 🧰 Task

`napari/qt/progress.py` has been deprecated since 4.11 and can be removed.

It should be a good issue for a new contributor and will increate coverage %-age.

### PR DESCRIPTION
**Pull request by AmirAflak**
Closes #6250

### CODE REVIEW

**Comment by Carreau** [comment]
@Czaki I'm not sure if there is a specific label for things that have been deprecated, and are removed. `Breaking change` explicitly mention deprecation, but so is `deprecation`.

**Comment by Czaki** [comment]
> @Czaki I'm not sure if there is a specific label for things that have been deprecated, and are removed. `Breaking change` explicitly mention deprecation, but so is `deprecation`.

I'm not sure, so I put this under maintenance, as I understand that breaking change happens during marking the module as deprecation.

**Comment by Carreau** [comment]
This got the "Ready-to-merge" label 2 days ago and got no objections. Merging to move the queue forward. 

Thanks.

**Review by Carreau — APPROVED** [review]

**Comment by Carreau** [comment]
Well, this needed a rebase / merge with master before merge. So I've done so and will retry to merge in an hour or so.

**Pull request merged**
