### PR TITLE
Rename Napari-GUI to napari

### LINKED ISSUE #147: Use of the word GUI in the repo
## ❓ Questions and Help

Right now we still have this alias folder `napari_gui` in the repo. This probably relates to how the pip install was being handled. Now that we have renamed the repo we can rename how we do the pip install. It is not clear to me also how this relates to #139 and Name Space Packages. Maybe @kne42 has thoughts on how to proceed

### PR DESCRIPTION
**Pull request by jni**
# Description
Fixes #147 

This renames napari-GUI to napari everywhere in the repo **except** in the PyPI badges, which should be updated when we upload the latest version.

I've verified that all the examples run with this change, and that the package installs locally as "napari". (This last thing was not as trivial as one might think! =P)

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) **SO** breaking! :joy:
- [x] This change requires a documentation update [CC @AhmetCanSolak :wink:]

# How has this been tested?
- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Hmm it's a little awkward right now that the `pip install napari` won't work (right?) and it is on our readme - is it worth mentioning that right now, or maybe as soon as this PR is merged are we going to push a release so that `pip install napari` at least does something?

**Comment by jni** [comment]
A very good point! I'm not fussed. We always want that "one more feature" in a release, but we might as well make one after this merges, then update the README badges.

**Comment by sofroniewn** [comment]
Yeah I'd say better to push a release so there is at least something that works, and then we can always push another again soon once some of that viewer API work is done

**Review by sofroniewn — APPROVED** [review]
Checks look like they are passing and this looks good to me

**Pull request merged**
