### PR TITLE
Fix SSL Cert error for external libraries used in the bundle

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This fixes the issue that @tischi saw here:
https://forum.image.sc/t/ssl-error-opening-an-image-from-url-with-skimage/59874/15

where `urllib.request.urlopen` called in a library outside of napari's control (here, scikit-image) fails with `SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)`

I had solved this for our own download needs in the bundle with the code here: 
https://github.com/napari/napari/blob/c28b47a05ae1ef64432ff37c2d246ea056828e30/napari/plugins/pypi.py#L24-L25

but this installs it globally using public methods in `urllib.request` (that I just wasn't aware of earlier).

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
tested locally, and this isn't quite working yet, but it's because `running_as_bundled_app` no longer seems to work, and the reason is that the `METADATA` file currently produced is extremely minimal, and lacks the stuff (like `Briefcase-Version`) that is "supposed" to be in there as per https://briefcase.readthedocs.io/en/latest/how-to/access-packaging-metadata.html?highlight=briefcase-version.  I'm going to make this default behavior for now, and open an issue about fixing `running_as_bundled_app`

**Comment by tlambert03** [comment]
this is all set.  tested locally to make sure it fixes  https://forum.image.sc/t/ssl-error-opening-an-image-from-url-with-skimage/59874/15

**Review by sofroniewn — APPROVED** [review]
Code looks good! Looks like we're getting a bunch of CI fails popping up, but I think they are unrelated to this PR, I'm seeing them on others too - could be a new IPython release? Not sure

**Comment by sofroniewn** [comment]
I'm going to merge this now, thanks!!

**Comment by tischi** [comment]
Thanks guys ❤️ ! Could you please ping me once I could try it out in the bundled app?

**Comment by tlambert03** [comment]
Bundles are created nightly, and for each release.  So tomorrow, you can try the nightly build:

https://github.com/napari/napari/releases/tag/latest

**Comment by tischi** [comment]
Works now for me! Thanks!!

**Pull request merged**
