### PR TITLE
Set focus on `QtViewer` object after creating main window

### PR DESCRIPTION
**Pull request by DragaDoncila**
# Description
Initially noted in #4628, our custom keybindings don't work when napari first launches, unless you first click on something inside the window. @ctrueden was investigating a separate issue [in this zulip thread](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/More.20keyboard.20focus.20fun) and found that it's actually the activity dialog button in the status bar that has focus. 

I initially tried just clearing the focus from the button, the status bar and the activity dialog, but for some reason that doesn't work? So instead I've set the focus at the end of `_QtMainWindow.__init__` to the `QtViewer`. I've confirmed this addresses the issue with our custom shortcuts not working. I have no idea if this is a sane thing to do though, so I'm opening in draft and pinging @tlambert03.

@ctrueden @gselzer does this fix your issue with the search bar of your plugin?

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
yeah, this is an unfortunate side effect of the fact that for now, we still go through vispy for our keybindings to have any effect (that is, there are no application global Qt keybindings, one has to activate a widget which has been connected to the qtcanvas, which then passes all of _its_ key events into the vispy canvas!)

If this works, it's a fine workaround for me.  Ultimately, I would like to extract our key-press events from the `QtViewer` object specifically.

**Comment by Czaki** [comment]
Maybe in showEvent?

**Comment by gselzer** [comment]
@DragaDoncila this change does indeed fix our keybinding. Thank you for the quick response time!

**Comment by DragaDoncila** [comment]
> Maybe in showEvent?

@Czaki sorry I'm afraid I'm not sure what you mean. Can you expand a bit?

**Comment by Czaki** [comment]
There may happen multiple things between widget creation and its shows. As there is no test for this and it may be not simple to create such test then this feature may silently fail. Dellaing set focus to showEvent (method called by qt on widget show) reduce propability that something between constructor and show will stole focus.

**Comment by DragaDoncila** [comment]
> Dellaing set focus to showEvent (method called by qt on widget show) reduce propability that something between constructor and show will stole focus.

Ahh I see, yes I think that's a good point. Will try that. Thank you!

**Comment by DragaDoncila** [comment]
So @Czaki just to be clear I've now moved the `setFocus` call to `_QtMainWindow.show`. I assume that's what you meant as I wouldn't expect we need to override the `showEvent` method itself.

**Comment by Czaki** [comment]
Yes. When I write first comment the call was in constructor.

**Comment by DragaDoncila** [comment]
> If this works, it's a fine workaround for me. Ultimately, I would like to extract our key-press events from the QtViewer object specifically.

Yeah agree @tlambert03 it would be nice if we didn't have to do this. In the interim. @gselzer and @ctrueden have confirmed this addresses their issue, and I've confirmed this fixes the bug with our keybindings not working before clicking somewhere, so I'll move this out of draft.

**Review by tlambert03 — APPROVED** [review]

**Pull request merged**
