### PR TITLE
Add and/or update documentation alt text

### PR DESCRIPTION
**Pull request by isabela-pf**
# Description

This is the second PR of its kind! If it helps, the previous changes from the previous event can be found at #4375

This PR adds or updates existing documentation alt text to be more descriptive. In particular, it describes the images in relation to the surrounding text they illustrate rather than describing them more generally. You may also find help in our discussion on the [collaborative working PR](https://github.com/isabela-pf/napari/pull/5).

We did not get to add or update all alt text in the documentation; this PR contributes only a selection.

⚠️ I am seeing a merge conflict and will need guidance on how to fix it. Thank you in advance!

## Type of change

This is a change to images in the documentation, but does not require a documentation update as far as I know.

# References

Continues fixing #3540

This work was done as a part of an event! You can find more info about the event and what resources we used on the [alt text workshop agenda](https://hackmd.io/rz-GeCi9RXixQdn5d4DEPg?both).

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@isabela-pf I think the issue is that as of https://github.com/napari/napari/pull/5216 all of those docs are now here:
[napari/docs](https://github.com/napari/docs)
I'm not sure what the best path is for you to `move` this PR, @jni @melissawm any advice?

**Comment by Carreau** [comment]
That likely won't be easy, I think we need to export a git patch, and import it in another repo. I can give it a shot

**Comment by Carreau** [comment]
See https://github.com/napari/docs/pull/12

It should conserve most of the history and I'll describe here how I ended up doing it. 


```
# in napari repo, check this PR
$ git checkout origin/pull/5240

# export patches for all the commits in this PR, 4f68ba.... being the parent of 14c9b14...
$ git format-patch 4f68baf9694fa74f440b446875aec0e5d2538e5c
```

This create all those files:

```
$ ls -1 *.patch
0001-Add-white-space-for-images-diff.patch
0002-Add-missing-images-to-diff.patch
0003-Apply-event-alt-text.patch
0004-Copy-edits-and-clean-up.patch
0005-Remove-white-space-placeholders.patch
0006-Remove-typos-and-white-space.patch
```

Close and get into the napari/docs repository. 

```
$ git branch port-pr
$ got co port-pr
$ git am ../path/to/napari/repo/*.patch
$ git push ...
```

And make the PR.

This one was pretty straightforward, once you find the rights incantations it almost seem easy.

**Comment by psobolewskiPhD** [comment]
@Carreau WOW!
For a total neophyte, can you clarify how/where you got:
```
# export patches for all the commits in this PR, 4f68ba.... being the parent of 14c9b14...
$ git format-patch 4f68baf9694fa74f440b446875aec0e5d2538e5c
```

Also, `git co` gives me an error, I assume this is equivalent to `git checkout` or using `gh pr checkout 5240`?

**Comment by Carreau** [comment]
> `git co` gives me an error, I assume this is equivalent to `git checkout`

Yes, it is an alias. I have  the following in my global config:

```
[remote "origin"]
   fetch = +refs/pull/*/head:refs/remotes/origin/pull/*
[alias]
    co = checkout
```

This means that 1) when I fetch I always fetch the head of all the PR, and can just use normal git command to check them out/diff. For example `git diff origin/pull/2994` works.

You mean `4f68ba.... being the parent of 14c9b14...` ?

Well, 
```
$git log --oneline --graph
* 2cdbe6c18 (HEAD, origin/pull/5240) Remove typos and white space
* 060424c5b Remove white space placeholders
* 189940781 Copy edits and clean up
* 5b7e6c3ad Apply event alt text!
* aea8cb6f8 Add missing images to diff
* 14c9b14ea Add white space for images diff 
* 4f68baf96 (tag: v0.4.17rc3) 

```
And find by hand, 
or 

```
$ git show 14c9b14~1 | head
commit 4f68baf9694fa74f440b446875aec0e5d2538e5c
Author: Andy Sweet <andrew.d.sweet@gmail.com>
Date:   Tue Sep 27 10:39:57 2022 -0700

    Update release notes for v0.4.17rc3 (#5147)

    * Update release notes automatically

    * Update docs/release/release_0_4_17.md
    *
```

If it's why format-patch / am,  well hum, I know they exists since hum... along time, and documentation, trial/error, stackoverflow google ? 

https://git-scm.com/docs/git-format-patch for example.

**Comment by psobolewskiPhD** [comment]
> You mean `4f68ba.... being the parent of 14c9b14...` ?

Yes, this was what I was wondering about.
Thanks for the detailed explanation and patience! 🙏 ❤️

**Comment by andy-sweet** [comment]
@isabela-pf : closing because this has been superseded by https://github.com/napari/docs/pull/12 in `napari/docs`. Feel free to reopen if that's incorrect.

**Pull request closed without merging**
