### PR TITLE
Revert changes to scikit-image test API

### PR DESCRIPTION
**Pull request by alisterburt**
Reverts napari/napari#3974

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
Sure, how come?

**Comment by alisterburt** [comment]
sorry for lack of info, got sidetracked as I was adding it - noticed a [test fail on minreq](https://github.com/napari/napari/runs/4858537137?check_suite_focus=true#step:9:615) because of the scikit-image API change (multichannel -> channel_axis) in the tests. Didn't know whether the best approach was to skip this test on minreq or bump the scikit-image requirement so opened the PR to discuss 🙂 

edit: also felt bad for merging with a failed test without noticing 😆

**Comment by alisterburt** [comment]
fail on the actual PR is here https://github.com/napari/napari/runs/4855071683?check_suite_focus=true#step:9:620

**Comment by alisterburt** [comment]
probably to close in favor of #3980

**Comment by tlambert03** [comment]
Ah I see, ok, let's just undo the change of the channel_axis parameter, (let the warning stay), but leave the rest of the previous PR

**Comment by tlambert03** [comment]
(And not bump the dep)

**Comment by alisterburt** [comment]
Perfect, makes sense, thanks! Will merge once CI is done

**Pull request merged**
