### PR TITLE
add PyGithub to dev dependencies

### PR DESCRIPTION
**Pull request by sofroniewn**
This PR adds PyGithub to our dev dependencies as it is needed to generate release notes

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]

**Comment by sofroniewn** [comment]
Just realized I need to add `twine` to this too - will do soon

**Comment by sofroniewn** [comment]
@jni is adding these ok with you? I see no harm

**Comment by jni** [comment]
I'm happy to be quite lackadaisical with our dev reqs. I do however wonder whether there should be yet another reqs file, `release.txt`. Essentially 90-99% of napari devs will never require this...

**Comment by sofroniewn** [comment]
Nice suggestion, I have moved these two to their own file `release.txt` and indicated their requirement in our release notes. I will merge once tests pass.

**Comment by sofroniewn** [comment]
unrelated to this PR, it looks like we're now only running one test per OS - was that an intentional change or did it just start happening @tlambert03 @kne42?

**Comment by tlambert03** [comment]
definitely not intentional.  in `master` seems like [this](https://github.com/napari/napari/pull/810) was the first one that didn't check other versions.  will try to figure out what's going on

**Comment by tlambert03** [comment]
looks like [all the tests are actually running](https://cirrus-ci.com/build/6039251208110080), but the [github view](https://github.com/napari/napari/pull/809/checks?check_run_id=354747389) on the checks is not showing it.

might be an issue with cirrus' implementation of the [checks API](https://developer.github.com/v3/checks/)?

**Comment by tlambert03** [comment]
cirrus is on it: https://github.com/cirruslabs/cirrus-ci-docs/issues/546

**Comment by tlambert03** [comment]
cirrus should be fixed now

**Pull request merged**
