### PR TITLE
WIP: Multiscale array class

### PR DESCRIPTION
**Pull request by jni**
# Description

This is meant to supercede #3560. Ultimately, I think it might be useful enough to pull out into its own package that the broader community can adopt.

This PR introduces a MultiScaleData class that behaves like a NumPy array, but works in multiple scales. This simplifies a lot of `if multiscale` code by delegating array slicing to the class rather than to specific chunks of code.

The downside is that slicing is ~num-levels times more expensive, because we compute slices for *all* resolution levels rather than just one. However, I think this can probably be optimised by making some operations lazy (ie we don't slice the lower resolutions until we ask for a specific slice), and anyway, async slicing and octrees can effectively alleviate this issue. But I wanted to check that people like this approach before going down that rabbit hole.

The *upside*, in addition to simplifying some code, is that this should give us multiscale painting, which is a pretty friggin massive upside if you ask me!

I still need to fix some tests, was having issues with local testing, but wanted to get this up for discussion.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by jni** [comment]
... and, I need to fix my black pre-commit????

**Comment by jni** [comment]
The [changes in image.py](https://github.com/napari/napari/pull/3715/files#diff-9e4cd2702cfbb10e85a517ed53426c08d163353b58aab0e13609b4375c1e9780R602) are a nice example of the code simplification you can get by using this class.

**Comment by tlambert03** [comment]
this is awesome!  how would you feel about merging #3560 with the plain `__getitem__`, since this pretty much just adds more features right?  Would let us review a little easier

**Comment by jni** [comment]
@tlambert03 I dunno. It doesn't just add more features, it removes all of the list compatibility stuff. But, on the plus side, it does let us focus on the breaking changes. It's just that #3560 *does* have breaking changes, it just tries hard to hide them, while this one lays it all bare.

Anyway, I can be talked into either approach.

**Comment by jni** [comment]
Oh and this of course breaks a lot of the fancy functionality in #3560 (getting the "current level" given the max size), since it implements its own, incompatible, fanciness. I guess, in short, that I'd be ok with merging them in sequence *within the same release*.

**Comment by tlambert03** [comment]
> It's just that #3560 does have breaking changes, it just tries hard to hide them,

what were they again?  (just so I'm clear :joy:)
by the way... I was referring to #3560, _without_ your  `__getitem__`/`__setitem__` stuff.  Just like a regular list, as it was in #2683 ...

**Comment by jni** [comment]
Does it have .append()? If a user checks "isinstance(layer.data, list)", will it still work? Etc =P

**Comment by tlambert03** [comment]
It was (explicitly) immutable, because our current mutiscale data was essentially broken if you edited anyway.

**Comment by tlambert03** [comment]
All this to say, yes, it was "broken", but I think it was less broken than the existing api

**Comment by tlambert03** [comment]
One more thought: I actually think the immutability might be a good idea. It reminds you that you need to set layer.data to a new value (same as numpy arrays, in most cases, right?).  The class _does_ implement things like `__add__`, so it's easy to concat and stuff.  Thoughts on that?

**Comment by jni** [comment]
> It reminds you that you need to set layer.data to a new value (same as numpy arrays, in most cases, right?).

No? I'd say I reasonably often mess with the contents of numpy arrays then call `layer.refresh()`. All painting and painting-like functionality (e.g. watershed split in zarpaint) is implemented this way. Probably that use has always been broken with multiscale, though.

>  The class does implement things like __add__, so it's easy to concat and stuff. Thoughts on that?

Yeah, seems pretty forced. 😂 That's what I meant when I said "tries hard to hide it". Which is a fine and lofty goal! I'm just saying, I would be suuuuper un-shocked if #3560 breaks some code "in the wild", and about equally unshocked if it doesn't. This change will almost certainly break some code in the wild, I'm just hoping that it'll be worth everyone's time. =)

**Comment by jni** [comment]
btw to the PR at hand: I was thinking of the following:

- fancy indexing in `__getitem__` will return a single-scale (largest dim) result, since by definition you have the memory to instantiate that — the added levels are just wasted.
- integer-only indexing always returns the value.
- fancy indexing in `__setitem__` will work as it does currently in the PR, which is to set the same number of items at each level, even if there is redundancy.

**Comment by tlambert03** [comment]
> Yeah, seems pretty forced

?  I went to see all of the methods that an immutable sequence implements (a tuple) and implemented them.  Seems like a pretty standard protocol.  

This is all a relatively silly discussion... we're going this direction either way.  I definitely see this as the far more risky but feature-rich version, and the previous implementation as the bare minimum that fixes the current broken API... but I'm happy to go wherever you want to take this one :)

**Comment by sofroniewn** [comment]
@jni #3560 has now been merged

**Comment by d-v-b** [comment]
This is relevant to my interests! 

- What the assumptions of this datastructure with respect to coordinates? For example, downsampling with 2x2 windowed averaging generates a new sampling grid with origin  `new_origin = old_origin + [.5, .5]`, but you could also downsample by smoothing and resampling at [0, 2, 4...], which would make `new_origin = old_origin`. Is there a standard model for multiscale coordinates somewhere in napari?... [inevitable reference to xarray]
- What are the assumptions of indexing with respect to coordinates?: I use 2x2x2 windowed averaging and I don't like image padding if I can avoid it (I'm doing this with dask and my task graphs are complicated enough as it is). That means I crop images before downsampling, so I get multiscale collections with shapes like `[(101, 101, 101), (50, 50, 50), (25, 25, 25), (12, 12 ,12), (6, 6, 6), (3, 3, 3), (1, 1, 1)]`. I don't see how you could cleanly broadcast array indexing over a collection like this -- `collection[0,0,0]` returns the first element of every scale level, that's fine (but these values are kind of hard to relate to each other without factoring in the translation transform associated with each scale...), but `collection[-1,-1,-1]` returns the _last_ element from every scale level, but the spatial relationship between _these_ elements depends on both the translation associated with each iteration of downsampling _and_ whether higher scale levels were cropped. And the situation can be made more complicated if you crop symmetrically, etc. And the smallest scale level can have a single element. Broadcasting numpy-style indexing to an array with a single element feels pretty icky. 

I think if you don't formally represent the coordinates of the downsampled arrays, it's very hard to relate the scale levels to each other, unless there's a strict Napari Multiscale Model somewhere that carefully defines the downsampling routine.

**Comment by jni** [comment]
> This is relevant to my interests!

Ha, yes, I discovered [xarray-multiscale](https://github.com/JaneliaSciComp/xarray-multiscale) only recently! :sweat_smile: 

> What the assumptions of this datastructure with respect to coordinates? For example, downsampling with 2x2 windowed averaging generates a new sampling grid with origin new_origin = old_origin + [.5, .5], but you could also downsample by smoothing and resampling at [0, 2, 4...], which would make new_origin = old_origin. Is there a standard model for multiscale coordinates somewhere in napari?... [inevitable reference to xarray]

Great question! No we do not have a standard model, nor have I really thought about the consequences for slicing in this PR — thus far I have used the simplest possible operation (`downscaled_coord = round(full_res_coord * downscale_factor).astype(int)`) and left the careful grid specification for later rounds.

In terms of how napari views multiscale coordinates, I think here too we have been working implicitly based on similar code to the above.

> What are the assumptions of indexing with respect to coordinates?: I use 2x2x2 windowed averaging and I don't like image padding if I can avoid it

At any rate, I think *most* in-the-wild implementations of pyramids are 2x windowed averaging as you suggest rather than Gaussian pyramids, so that should form the basis of our display and coordinate models. (CC @joshmoore)

> collection[0,0,0] returns the first element of every scale level

Please see my notes above: thinking about this more, indexing a *single* element will only ever return a single element. Fancy indexing will return a single scale.

I *think* that indexing slices that "vanish" (become smaller than (1, 1, 1), or (0.5, 0.5, 0.5)) will result in a truncated pyramid (fewer levels than the original). The one case where this falls over is if we slowly paint an area that is bigger than an individual pixel at the highest level, but each paint stroke is smaller, then we will never see it propagate. For this I think we need asynchronous consistency checking of the pyramid that treats the higher resolution levels as the "truth". I don't see this as necessary for a v0.1 of this feature, though.

**Comment by d-v-b** [comment]
> At any rate, I think most in-the-wild implementations of pyramids are 2x windowed averaging as you suggest rather than Gaussian pyramids, so that should form the basis of our display and coordinate models. (CC @joshmoore)

This is a pretty big assumption! I use 2x windowed averaging because I can ignore aliasing, and this is probably true for most people doing bioimaging, but I can think of plenty of domains where aliasing would matter -- photography and satellite imagery come to mind. Also, even for windowed averaging it's not clear if 2 is the optimal downsampling factor -- 3x has the advantage that downsampling keeps you on a subset of the same sampling grid: elements from coordinates `[0, 1, 2]` get averaged and the result is localized to coordinate `[1]` (i.e, the translation transform associated with 3x windowed averaging is integral). So I would hesitate before making 2x windowed averaging canonical.

**Comment by Carreau** [comment]
This PR have not been active for quite some time. 

In order to keep the list of PRs short and easier to work with, I am going to tag this PR as [stale](https://github.com/napari/napari/pulls?q=is%3Apr+label%3Astale+is%3Aclosed) and close it.

Feel free to reopen and remove the "stale" label when work on this PR resumes. 
If you do not have the permissions to do so, feel free to request help from one of the maintainer to reopen and remove the `stale` label .

**Comment by joshmoore** [comment]
FWIW, there has been progress on supporting hierarchies of xarray DataArray's ("datatrees") thanks to @TomNicholas, @aurghs, @malmans2, and @thewtex which could conceivably be a model-object that could be used for multiscale which has also been discussed in https://github.com/ome/ngff/pull/114

(further background in https://github.com/spatial-image/multiscale-spatial-image/issues/8)

**Comment by thewtex** [comment]
Yes, by experimenting with what works well in practice, taking in the feedback and suggestions of others, and looking for synergies with efforts in the community, and there have been exciting developments.

We can have an elegant, layered data structure with numpy arrays as the core structure and add additional information from there. Layers are:

- The NumPy/Dask image array.
- Spatial metadata
- "Multi-channel" datasets
- Multiscale images
- Multiple, related datasets

and this can be done in a way that works with tools that operate on NumPy arrays, Dask arrays, Xarray DataSets / DataArrays and serialized in a OME-NGFF / NetCDF compatible way.

This is specifically enabled by @TomNicholas et. al.'s work on these [Xarray DataTrees](https://github.com/xarray-contrib/datatree), which are a beautiful way to provide the higher-level associations. They can be optionally combined with xarray's version of Python dataclasses for extra niceness. Looking at geoscience practices, we could borrow from NetCDF best practices for an important issue that @sofroniewn brought up: associate a [long_name](https://docs.unidata.ucar.edu/netcdf-c/current/attribute_conventions.html), e.g. `laser`, `camera`, `anterior-posterior`, with standardized dimension names, e.g. `x`, `y`. `z`. @joshmoore I am currently in the process of returning from paternity leave, but on my todo list is to add a PR / discussion on `long_name` to the `ngff` repository.

**Comment by sofroniewn** [comment]
Wow these are great updates @joshmoore @thewtex! Thanks!! As these work come online we'll want to make sure that they can be supported in napari. @jni have you checked any of this out?

I'm also flagging for @andy-sweet just for visibility for when he might think about tiled rendering / multiscale in napari.

**Comment by jni** [comment]
@sofroniewn I looked at the first link and severely (?) misunderstood it, 😂 thanks @thewtex for clarifying there.

@thewtex one issue I've had with xarray is that the metadata specification is that I didn't see a nice way to specify rotation — one simply specifies the x, y, and z arrays for each axis? Which seems wasteful? Or have I misunderstood how to use it? If I want to specify an array with pixel spacing (5, 0.5, 0.5), origin at (300, 100, 500), and a 30º rotation about z (leading axis), how does that look in an xarray?

At any rate the datatree stuff looks awesome. ❤️ thank you for pointing it out!

**Comment by TomNicholas** [comment]
Glad to hear that people are excited by our work on xarray-datatree :blush: If people have questions / input / ideas on tree data structures in xarray I would love to hear about them!

I had a great chat with @kevinyamauchi at SciPy about whether napari could be using xarray as an internal data structure more generally. I think the conclusion was that it would be a great fit for at least part of your internal data model, even before thinking about multi-scale arrays. Do you have another issue for that anywhere?

If anyone has any questions about xarray then feel free to tag me or to raise issues / discussions on the xarray github - that's the best place to reach us.

**Comment by tlambert03** [comment]
Hi @TomNicholas, yeah, we've definitely thought many times about integrating xarray more deeply into our data model.  It's come up in multiple places, but here's one of our earliest open issues https://github.com/napari/napari/issues/14

**Comment by brisvag** [comment]
@TomNicholas I'm not familiar with the older issues, but I can at least point you to a few other places where I thought xarray would fit well and brought it up:

- my personal favourite: #2917
- #906
- #3848 (though maybe a bit deep in theoretical-land)

**Comment by thewtex** [comment]
>  didn't see a nice way to specify rotation

@jni yes, you are right! I experimented with adding a rotation matrix / numpy array as an additional Xarray attribute. This is functional, but other software does not know how to interpret it. However, we likely could/should have try something that also works with OME-NGFF and is documented and standardized across the community. So, a more impactful approach would work towards supporting rotation transformations in OME-NGFF, then use the same model, i.e. naming, parameterization, order in Xarray.

> I had a great chat with @kevinyamauchi at SciPy about whether napari could be using xarray as an internal data structure more generally

It would be wonderful if geospatial folks could also use napari, join in the community. Feedback from geospatial folks at the SciPy Visualization BoF indicated that there would be more interest in Napari with Xarray / NetCDF compatilibilty.

**Comment by d-v-b** [comment]
You can express rotations by introducing new non-dimensional coordinates to a `DataArray`: https://docs.xarray.dev/en/stable/user-guide/plotting.html#multidimensional-coordinates

**Comment by jni** [comment]
@d-v-b I'd thought of this as an option and am glad to see it's supported, but it's really not a very attractive one, is it? What could be expressed by a 3x4 matrix of numbers is now expressed by an index that is 3x your data? — Maybe even 12x your data if you have uint8 data!

I'm wondering what the odds are of getting xarray to support implicit indices based on a transformation matrix... Perhaps flexible indices help here?

**Comment by d-v-b** [comment]
following up after an eternity: 

> I'm wondering what the odds are of getting xarray to support implicit indices based on a transformation matrix... Perhaps flexible indices help here?

All we need is an array-like object that retrieves values by calling a function instead of getting stuff from storage. Dask would work here, but this problem doesn't really require all the dask stuff. The coordinate arrays will always be "simple" in the sense that they are parametrized over a small number of values -- start, stop, step. xarray doesn't care how the underlying values are stored, it just wants the array API on top.

**Comment by joshmoore** [comment]
cc: @rabernat and @briannapagan who are actively working on https://github.com/zarr-developers/geozarr-spec

**Pull request closed without merging**
