### PR TITLE
Add CircleCI to enable docs preview on PRs

### LINKED ISSUE #5713: Add documentation preview also in main repository
## 🚀 Feature

It will be nice to have the option to preview docs also when someone creates PR to the main repository to check if everything renders appropriately. 

## Motivation

It is easier to preview documentation if rendered in the same way as in the docs repository. 

## Pitch

Ad circeCi job to build docs and github action that will add link to fast preview.

### PR DESCRIPTION
**Pull request by melissawm**
# Fixes/Closes

Closes #5713

# Description
Activates CircleCI to allow for docs previews in PRs. This is very similar to what is done on napari/docs.

# References

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by melissawm** [comment]
Ok this should be good on my side but there is a pending bug on the CircleCI artifact redirector side (see https://github.com/larsoner/circleci-artifacts-redirector-action/issues/40, confirmed by https://github.com/napari/docs/actions/runs/4679190349/jobs/8288880213) so I will wait for that to be resolved before marking this as ready for review.

**Comment by psobolewskiPhD** [comment]
@melissawm Looks like a new secret is needed:
https://github.com/larsoner/circleci-artifacts-redirector-action/issues/40#issuecomment-1505543564

**Comment by melissawm** [comment]
I don't think I can add a secret to the org, but I will update the code accordingly and when an org owner has the time maybe they can add it?

**Comment by Czaki** [comment]
@jni You are called here.

**Comment by melissawm** [comment]
Ok! To make it easier, here's what's missing:

> The token must be a personal API token, not a project token at the CircleCI end as those aren't supported yet.
>
> 1. You can create a personal CircleCI token here (I named mine CIRCLE_STATUS): [app.circleci.com/settings/user/tokens](https://app.circleci.com/settings/user/tokens)
> 2. Add the token value (from the CircleCI website) it to the secrets of your org or project, e.g., for MNE-Python I added it under the name CIRCLECI_TOKEN for the org to [github.com/organizations/mne-tools/settings/secrets/actions](https://github.com/organizations/mne-tools/settings/secrets/actions)
> 3. ~~Add it to the action as api-token: ${{ secrets.CIRCLECI_TOKEN }} in the with for the action~~ DONE

I believe this will solve the problem for napari-docs as well if the token is added to the napari org, but we will also need a PR there to add the api-token definition to the circleci redirector config. I will do that now. EDIT: See napari/docs#136

**Comment by jni** [comment]
I've added the secret to the org. btw anyone at @napari/steering-council should be able to do this — it would be good to know whether that is actually true 😂

**Review by jni — APPROVED** [review]

**Comment by melissawm** [comment]
Gentle ping - is there anything missing here?

**Comment by Czaki** [comment]
label and milestone

**Comment by melissawm** [comment]
Thanks @Czaki - let's see if all is working well!

**Pull request merged**
