### PR TITLE
Add error message if local file doesn't exist.

### PR DESCRIPTION
**Pull request by jczech**
# Description
Previously, if you tried to open a non-existent local file, you'd get an error message like this:

`ValueError: No plugin found capable of reading '/path/to/nonexistent/file'`

This commit provides a hopefully more helpful error message:

`ValueError: Requested path '/path/to/nonexistent/file' does not exist.`

## Type of change
- [ ] Bug-fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
This commit addresses this issue: https://github.com/napari/napari/issues/3382

It doesn't address non-existent remote files, but maybe that should be a new separate issue.

# How has this been tested?
- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

Not sure if this PR warrants adding new tests, but I'm happy to write them if needed.

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If I included new strings, I have used `trans.` to make them localizable.

### CODE REVIEW

**Review by tlambert03 — COMMENTED** [review]
thanks @jczech, this is a very nice improvement!

i'm wondering if this would be better placed in the `abspath_or_url` function right above it.  We already do the `urlparse` and the `str/list` checks there.  so maybe rather than doing it again, we could add a `must_exist=False` parameter there, and then add this `exists()` check around line 350 in `utils/misc.py`?

**Comment by jczech** [comment]
Thanks @tlambert03! That's a very good point. I think you're absolutely right. Tbh, I had originally planned on changing `abspath_or_url`. Not sure why I changed my mind. Anyway, I'll go ahead and make that change now.

**Comment by Carreau** [comment]
Rebased on master to fix tests, moved into abspath_or_url, added must_exist=False, and call it in napari/plugins/io.py original location with must_exists=True.

**Comment by sofroniewn** [comment]
@Carreau this still has some fails, but they might now be fixed on main - can you rebase again. Thanks!!

**Review by tlambert03 — APPROVED** [review]
LGTM!  Thanks @jczech!

**Review by jni — APPROVED** [review]

**Pull request merged**
