### PR TITLE
Add release notes for 0.4.17

### PR DESCRIPTION
**Pull request by alisterburt**
# Description
This PR adds the autogenerated template of our 0.4.17 release notes - if anyone would like to take a pass at writing some highlihghts or proposing which PRs should go in which sections that would be really useful!

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Holy cow that's a lot of PRs going in...
But...
💯 Highlights:
```
 - Revert "Fix sys.path issue with subprocess relaunch in macOS" (#5027)
 - Revert "Revert "Fix sys.path issue with subprocess relaunch in macOS"" (#5029)
 ```
(sorry @alisterburt )

**Comment by andy-sweet** [comment]
Some highlights that I authored or reviewed.

- Optimized Points (#4648) and Vectors (#4794) slicing. With this change, doing something like slicing 3D points for 2D display should be ~10x faster in some large cases.
- Multi-color text (#4464). This uses the API that we intend to spread elsewhere (e.g. for things like `Points.face_color`), so it might be a good idea to highlight it. On the other hand, it isn't that well documented yet.

**Comment by Carreau** [comment]
I would highlight support for PyQt6, I think that's necessary for native M1 ?

**Review by Carreau — APPROVED** [review]
Can I suggest we merge as is and iterate on the various highlight ?

**Comment by psobolewskiPhD** [comment]
> I would highlight support for PyQt6, I think that's necessary for native M1 ?

Sort of? conda-forge has native pyqt5 and pyside2
but pip only has the Qt6 ones native.
Plus it's still sort of experimental, so maybe a bit premature?

Speaking of macOS arm64, maybe it's worth mentioning that in the install docs somewhere?

**Comment by Czaki** [comment]
> I would highlight support for PyQt6

Experimental support. There are some glitches, and parts of our Qt code are not tested, so it may happen that somehow will not work because of API changes.

**Comment by alisterburt** [comment]
> Can I suggest we merge as is and iterate on the various highlight ? 

Merged, agree this is better!

**Comment by Czaki** [comment]
I do not understand. Why merge when the job is not done? Did we need more commits?

**Comment by alisterburt** [comment]
I think it's a similar situation as the NAPs where it is easier to iterate using the PR mechanism rather than coordinating efforts across multiple PRs

**Pull request merged**
