### PR TITLE
better isosurface rendering with colormaps

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR significantly improves our isosurface rendering by making it respect our colormaps and getting rid of the light green default. To do this I "vendored" the vispy volume shaders, which results in quite a bit of copied code, but which will give us significant flexibility as we continue to address issues like #574.

The changed lines are relatively minor
```bash
const vec4 u_ambient = vec4(0.2, 0.2, 0.2, 1.0);
```
 gets rid of the green, and 
```bash
                color = $sample(u_volumetex, iloc);
                if (color.g > u_threshold) {
                    color = calculateColor(color, iloc, dstep);
                    gl_FragColor = $cmap(color.g);
```
puts the colormap call in the right place

Here is a gif of the new performance, which I think is quite nice!!
better_iso_surface

Ultimately we will probably want to push these changes to vispy, but I imagine we'll be making a bunch of them over the next chunk of time, so might make sense to wait till we're done.

### CODE REVIEW

**Comment by sofroniewn** [comment]
I've figured out how to fix #574 by enabling nearest neighbor interpolation in the volume layer - something like 
```python
        self._tex = Texture3D((10, 10, 10), interpolation='nearest')
        self.shared_program['u_volumetex'] = self._tex
```
we'll need a little bit more wrapping to make that settable etc, but the labels now look great in 3D transluencent mode (so no more max intensity projecting)

I'll maybe make a new PR that builds off of this one to implement this

**Comment by jni** [comment]
@sofroniewn 😍😍😍😍😍

This is amazing! And fixing #574... 🤯

I would suggest pushing these to vispy as they happen. On the vispy side it's a smallish change (?), which is much easier to review than an all-encompassing overhaul. Smaller is better with PRs!

**Comment by jni** [comment]
@sofroniewn indeed, to help with *my* review, would it be hard for you to split this into two commits:

- vendoring _vispy volume at a particular git hash
- making the necessary changes to that file

?

I might even temporarily enable merge without squash for this purpose...

**Comment by sofroniewn** [comment]
I'll make a vispy PR now - I think it is quite nice. I've added two commits - one which takes the PR back to the vispy vendored state, and one called `our_changes` which includes the 6 vispy lines changed.

**Comment by jni** [comment]
@sofroniewn wowza! So simple, so great.

I'm happy to do this for you but in case you don't know this, you can use:

```
git rebase -i master better_isosurface_rendering
```

to launch an interactive rebase, and squash the first two commits together, then force push to update the PR. 

Or even simpler, just found through `tldr git-rebase`:

```
git rebase -i HEAD~3
```

to rebase/rearrange/squash the most recent three commits in-place.

**Comment by sofroniewn** [comment]
@jni I didn't know, thanks for the git tips! If you want to do that go-ahead. I just made a PR https://github.com/vispy/vispy/pull/1802 with the change too

**Comment by tlambert03** [comment]
Omg 😍😍

**Comment by jni** [comment]
Good-oh! I've force-pushed, will merge (not squash) once CI passes.

**Review by jni — APPROVED** [review]

**Comment by royerloic** [comment]
Fantastic @sofroniewn , I see you are starting to hack the shaders :-) 
I will find some time this year to do some of that myself :-)

**Pull request merged**
