### PR TITLE
processEvents before nbscreenshot

### LINKED ISSUE #1596: nbscreenshot not always showing layerlist
## 🐛 Bug
as [jni noted](https://github.com/napari/napari/issues/1588#issuecomment-682233015) from my screenshot in #1588 (shown below) ... `nbscreenshot` is sometimes not showing the layer list... and possible other inconsistencies with the viewer? 
(cropped is a dask array in this case)
91489668-2bb51600-e87f-11ea-81e6-6a7a4470de0a

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
fixes #1596.  See explanation in https://github.com/napari/napari/issues/1596#issuecomment-785225753 ... nbscreenshot will not work for "docs" screenshots without an event loop running (because none of events created by the lines prior to the call to `nbscreenshot` have actually been executed prior to starting the event loop with `napari.run()`).  This PR forces events to be processed before creating the screenshot.

(there are a couple unrelated type annotations in here ... for IDE completion... I can make a separate PR if you'd like)

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by sofroniewn** [comment]
Nice catch

> That unfortunately requires a qt import outside of the qt folder... but I think that's the compromise we have to make at the moment for the fact that we rely on qt for our entire event loop.

Screenshot stuff is tricky. One could also argue that maybe the screenshot stuff should live in the qt folder too then, but that would change the import. I guess our headless tests are still ok as we don't have a test for this? Maybe another reason it should live elsewhere. I did like `from napari.utils import nbscreenshot` though. If you think this will be a longterm thing, how about putting this inside a `utils/_qt` folder, but still exposing it as `from napari.utils import nbscreenshot`? Might just make the organization of the code and what can be headless vs what's not a little more clear. Thoughts?

> (there are a couple unrelated type annotations in here ... for IDE completion... I can make a separate PR if you'd like)

that's fine

**Comment by tlambert03** [comment]
> One could also argue that maybe the screenshot stuff should live in the qt folder too then, but that would change the import.

Yeah, that's a good argument actually :)  the whole "screen" depends on qt anyway... so it should probably live in Qt.   But I agree, we should try to maintain `napari.utils.screenshot`.  I think it's probably fine to just punt and leave it all where it is for now.  That qt import will only ever get triggered when IPython asks for the screenshot (and that _already_ implicitly required Qt to be running anyway).  Since we're already exporting from `napari.utils`, let's just leave it there.  sound good?

**Comment by sofroniewn** [comment]
> Since we're already exporting from napari.utils, let's just leave it there. sound good?

What about the `utils/_qt/notebook_display.py` idea, so that we keep the import the same, but isolate the code. This would just help someone looking at the internal code base understand why we've made an exception here. I just worry that otherwise we'll keep on with this trend and things will get back to how they were before the headless test?

**Comment by tlambert03** [comment]
sounds good. will move

**Comment by tlambert03** [comment]
ok, moved stuff around...

**Comment by tlambert03** [comment]
ok undid move stuff! 😂

**Comment by sofroniewn** [comment]
> ok undid move stuff! 😂

lol for anyone reading along, @tlambert03 and i had a convo about the tradeoffs of reorging to isolate qt vs simplicity. I think here because we're just using the event loop it's ok. we have our headless test anyway, so we're in good shape to see if there is more qt leakage. this looks good to me now, and i will merge!! thanks

**Review by sofroniewn — APPROVED** [review]

**Comment by jni** [comment]
🎉 awesome! ❤️

**Pull request merged**
