### PR TITLE
MAINT: Add a script to start auto-managing the "ready to merge" labels.

### PR DESCRIPTION
**Pull request by Carreau**
Currently we can run this locally, but later on we can add it to a cron that runs every 24h.

Once we are more confident on the script I guess we can have it auto merge PR on its own.

Step toward #5983

### CODE REVIEW

**Comment by Carreau** [comment]
> Maybe it could be simpler to use PyGithub package? As then we do not need to trace API changes.

Every time I tried to use PyGitHub for simple things it ended up being more complicated and break more often on version upgrade.

**Comment by Czaki** [comment]
I use only PyGithub a little so I may not meet such a problem. 

Is it possible to add the checking status of CI?

**Comment by Carreau** [comment]
I tried using pyGithub, but it's not made to: 1) find PR by labels, 2) find date/time when label are added/removed. So I don't think it's appropriate.

I've added check that a) PRs was not modified since label was added, though that does not only reflect push, but editing description for example. b) check CI status.

**Comment by Czaki** [comment]
I use it heavy for 1 task in release tools. `GitHub.search_issue()`
For second it looks like `get_timeline` method of Issue should work bt I don't check it.
https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html#github.Issue.Issue.get_timeline

But your solution looks great so the discussion about PyGitHub is theoretical. 

> I've added check that a) PRs was not modified since label was added, though that does not only reflect push, but editing description for example. b) check CI status.

Thanks

**Pull request closed without merging**
