### PR TITLE
Filter all nan axis warning on layer extent

### LINKED ISSUE #1536: RuntimeWarning when creating empty points
## 🐛 Bug
not a bug exactly, but a runtime warning that users will now see when creating empty points after #1360 

```python
In [1]: viewer = napari.Viewer()     

In [2]: viewer.add_points()    
napari/napari/components/layerlist.py:209: RuntimeWarning: All-NaN axis encountered
  min_v = np.nanmin(
napari/napari/components/layerlist.py:212: RuntimeWarning: All-NaN axis encountered
  max_v = np.nanmax(
```

@sofroniewn, would it be possible to catch the all-NaN cases before running np.nanmax/min here?

https://github.com/napari/napari/blob/2315443d9bd4fb6b8cc30967cf433d017f7c8ca2/napari/components/layerlist.py#L209-L214

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
Closes #1536 by filtering the warning - see comment in code about why this is ok. Thoughts @tlambert03 if you like this approach or would prefer another?

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
Sure, works for me!

**Comment by sofroniewn** [comment]
Thanks for the quick review @tlambert03.

Looks like test fails on linux are conda related and not connected to this PR https://github.com/napari/napari/pull/1540/checks?check_run_id=964211252.

I'll let sit for a little in case anyone else wants to comment and will then merge

**Comment by sofroniewn** [comment]
Got a zulip green light from @jni on this one. Re-running the failing linux tests to see if CI has fixed them, but they are independent of this PR. Will merge soon

**Comment by sofroniewn** [comment]
CI still failing here and now on master, but I will merge this regardless, as it is independent

**Pull request merged**
