### PR TITLE
Use pyi for better support type checking of Array

### PR DESCRIPTION
**Pull request by Czaki**
# Description

use stubs file to told that Array is expected to be one of `ArrayLike`, `np.ndarray`, `zarr.Array` or `dask.array.Array`

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

#1713

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

@tlambert03 see this

### CODE REVIEW

**Comment by tlambert03** [comment]
can you clarify a bit your intention here?  are you wanting better type checking when you provide an object to `Layer(data=...)`?  are you wanting better hinting when you grab `layer.data`?
the pyi file was a good solution for #1713, because the underlying functions were themselves dynamically generated.  Here a pyi file is less convenient, since the code is not autogenerated, and the pyi can go out of sync.  Also, the Union here isn't strictly accurate, since our array support is more of a protocol than a strict union of types.  We are aware that typing around accepted input data is vague at the moment, but this is just a generally hard problem. 
the `Array` class that we use is mostly for internal usage in declaring our models (so that we can assert shapes of things).  it's _not_ intended to be a general type hint for external users.  Can you provide a bit more context on exactly what you'd like to see in your IDE?

**Comment by Czaki** [comment]
Without this change:

Zrzut ekranu z 2021-09-17 20-06-07

With this change:
Zrzut ekranu z 2021-09-17 20-06-49

So You could see that without this change PyCharm (Which is a popular IDE) mark simple code as the wrong usage which could confuse non expected user.

Add a type annotation told tools that this overload is only for pytantic and data do not need to be Array subclass instance.

**Comment by tlambert03** [comment]
I do understand the implications of annotation something with `Array` ... my question to you is more about where _in the `napari` codebase_ you're trying to get IDE hinting.  i.e. not your "sample_fun".  See my original question:

> can you clarify a bit your intention here? are you wanting better type checking when you provide an object to Layer(data=...)? are you wanting better hinting when you grab layer.data?

**Comment by Czaki** [comment]
I prefer to have both. After think more it looks like best is to have defined two types. One for function argument and second one for function return. But there is also problem with pydantic class which may ned third class with type annotation (to have validator but not park assignment of `np.ndarray` as wrong one.

**Comment by tlambert03** [comment]
ok, now that I'm understanding a bit better... yes: we definitely all want better type hinting for arrays in napari (and more generally across the whole python ecosystem).  This is basically the same thing as https://github.com/napari/napari/pull/1175.

There are a number of things that make this hard.  first, as mentioned, we need to define protocols, not Unions.  This PEP (https://www.python.org/dev/peps/pep-0646/)  coming in 3.10 will also eventually help so that we can declare a bit more about the shapes of those array protocols.  Most of the time we've just fallen back to using `Any`, because for now we'd rather be too vague than start creating overly strict type hints that aren't really correct.

If you did want to start working on `layer.data`... `custom_types.Array` is not the place to do it.  the stubs generated for `add_<image>` and `view_<layer>` _might_ be a way to inject a little more meaning, but we'd need to go through the code and track all the array APIs we use (i.e. `.shape`, `.data`, make a union with lists for images, etc...).  This also touches on the `LayerDataProtocol` that I tried to introduce in #2683.

In general, very high value, important stuff.  but non-trivial.

**Comment by tlambert03** [comment]
This falls into the same general category as https://github.com/napari/napari/pull/1175#issuecomment-951410080.  Closing in favor of (waiting for) proper tensor-like hinting

**Pull request closed without merging**
