### PR TITLE
Single scale tiled rendering

### LINKED ISSUE #2230: Error displaying dask array with NAPARI_ASYNC and NAPARI_OCTREE
This code block:

```python
import napari
import os
import dask.array as da

for envvar in ('NAPARI_ASYNC', 'NAPARI_OCTREE'):
    print(f'{envvar} : {os.environ.get(envvar)}')

ndim = 2
data = da.random.randint(0,255, (2048,) * ndim, chunks=(64,) * ndim, dtype='uint8')

with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.add_image(data)

```

produces this traceback:
```bash
NAPARI_ASYNC : 1
NAPARI_OCTREE : 1
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/bennettd/dev/napari/napari/_qt/qt_event_loop.py", line 213, in gui_qt
    yield app
  File "/Users/bennettd/dev/napari/examples/test.py", line 14, in <module>
    viewer.add_image(data)
  File "/Users/bennettd/dev/napari/napari/components/viewer_model.py", line 676, in add_image
    layer = image_class(data, **kwargs)
  File "/Users/bennettd/dev/napari/napari/layers/image/experimental/octree_image.py", line 75, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/bennettd/dev/napari/napari/layers/image/image.py", line 276, in __init__
    self._update_dims()
  File "/Users/bennettd/dev/napari/napari/layers/base/base.py", line 530, in _update_dims
    self.refresh()
  File "/Users/bennettd/dev/napari/napari/layers/base/base.py", line 940, in refresh
    self.set_view_slice()
  File "/Users/bennettd/dev/napari/napari/layers/base/base.py", line 800, in set_view_slice
    self._set_view_slice()
  File "/Users/bennettd/dev/napari/napari/layers/image/experimental/octree_image.py", line 420, in _set_view_slice
    base_shape_2d = [base_shape[i] for i in self._dims_displayed]
  File "/Users/bennettd/dev/napari/napari/layers/image/experimental/octree_image.py", line 420, in <listcomp>
    base_shape_2d = [base_shape[i] for i in self._dims_displayed]
IndexError: tuple index out of range
```

If this errors, what kind of chunked images was the async functionality tested on?

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
Closes #2230. This adds support for single scaled tiled/ chunked data to use our tiled loader. For example the following now works well with `NAPARI_OCTREE=1`

```python
import dask.array as da
import napari


ndim = 2
data = da.random.randint(0,255, (65536,) * ndim, chunks=(256,) * ndim, dtype='uint8')

viewer = napari.Viewer()
viewer.add_image(data, contrast_limits=[0, 255])
# To turn off grid lines
#viewer.layers[0].display.show_grid = False
viewer.camera.zoom = 0.75
napari.run()
```

Everything is still 2D only. Also I need to provide the contrast limits so that we don't accidentally try and compute them on whole data set. I could try improving that now before this PR merges (or later)

Also note that I have to set the camera zoom to be close to 1 before we launch the viewer, otherwise we'll start trying to load all the tiles and even the async code will get over run.

I think in a separate PR I might add `min_zoom` (and possibly, `max_zoom`) values that if set will define the upper and lower limits on the zoom. Then when using this functionality someone could define min_zoom and not have to worry about a user accidentally zooming out too far!

Here is what a movie looks like with that toy example. Note that unlike the normal octree case here we're only ever showing the high res tiles, and if we've got nothing to show then the canvas is empty. Otherwise the code path is all the same!

https://user-images.githubusercontent.com/6531703/110360450-95169e00-7ff3-11eb-80ae-7afda45dad14.mov

@d-v-b @emilmelnikov I think you're both interested in this functionality. Please let me know if it works for you, cc @jni @neuromusic 

I've also added a screenshot test that passes locally, but is disabled until we get our CI OCTREE testing working

### CODE REVIEW

**Comment by sofroniewn** [comment]
Ok, this PR now contains #2381 which fixes the contrast limit estimation for large data.

I've also place a limit of 81 chunks per level which prevents a massive rendering explosion if you zoom out. This means that limiting the zoom is no longer required.

This is ready for review @jni!

**Review by jni — APPROVED** [review]
I love this. So much fun to use. Do you want to add your test script, *along with setting the env var at the top of it ;)*, to the examples gallery?

**Comment by jni** [comment]
It would probably also be nice to rebase on/merge master so that the PR is clean and contains only the changes after #2381

**Comment by jni** [comment]
@sofroniewn test script can be added in a new PR. =)

**Comment by sofroniewn** [comment]
> @sofroniewn test script can be added in a new PR. =)

I actually wanted too! But didn't have time today. New PR sounds good though

**Pull request merged**
