### PR TITLE
WIP Fast labels rendering

### PR DESCRIPTION
**Pull request by jni**
# Description

This is the beginning of an attempt to use vispy/vispy#1920 (ie you need that PR's version of VisPy) to speed up labels rendering (for now, only in 2D). Still lots to do but wanted to post it up here for reference after a pair session with @OKaluza @djhoese.

Currently this fails with a big and scary traceback from VisPy 😂 

<details>

<summary>
current traceback
</summary>

```pytb
 $ python examples/add_labels.py
image.dtype=dtype('int32')
image.dtype=dtype('int64')
image.dtype=dtype('int64')
image.dtype=dtype('int32')
image.dtype=dtype('int32')
data.dtype=dtype('int32')
data.dtype=dtype('int32')
data.dtype=dtype('int32')
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/jni/projects/vispy/vispy/app/backends/_qt.py", line 844, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 454, in __call__
    self._invoke_callback(cb, event)
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 472, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 470, in _invoke_callback
    cb(event)
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/Users/jni/projects/vispy/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/Users/jni/projects/vispy/vispy/visuals/visual.py", line 436, in draw
    if self._prepare_draw(view=self) is False:
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 856, in _prepare_draw
    self._build_texture()
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 815, in _build_texture
    self._texture.set_data(self._data)
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 329, in set_data
    self._reformat_if_necessary(data)
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 322, in _reformat_if_necessary
    self._resize(data.shape, internalformat=internalformat)
  File "/Users/jni/projects/vispy/vispy/gloo/texture.py", line 277, in _resize
    internalformat = self._check_internalformat_change(internalformat, shape[-1])
  File "/Users/jni/projects/vispy/vispy/gloo/texture.py", line 260, in _check_internalformat_change
    raise ValueError(
ValueError: Invalid texture internalformat: 'r32'. Allowed formats: {'r8': 1, 'r16': 1, 'r16f': 1, 'r32f': 1, 'rg8': 2, 'rg16': 2, 'rg16f': 2, 'rg32f': 2, 'rgb8': 3, 'rgb16': 3, 'rgb16f': 3, 'rgb32f': 3, 'rgba8': 4, 'rgba16': 4, 'rgba16f': 4, 'rgba32f': 4, 'luminance': 1, 'alpha': 1, 'red': 1, 'luminance_alpha': 2, 'rg': 2, 'rgb': 3, 'rgba': 4}

ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/jni/projects/vispy/vispy/app/backends/_qt.py", line 844, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 454, in __call__
    self._invoke_callback(cb, event)
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 472, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 470, in _invoke_callback
    cb(event)
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/Users/jni/projects/vispy/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/Users/jni/projects/vispy/vispy/visuals/visual.py", line 436, in draw
    if self._prepare_draw(view=self) is False:
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 856, in _prepare_draw
    self._build_texture()
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 815, in _build_texture
    self._texture.set_data(self._data)
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 329, in set_data
    self._reformat_if_necessary(data)
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 322, in _reformat_if_necessary
    self._resize(data.shape, internalformat=internalformat)
  File "/Users/jni/projects/vispy/vispy/gloo/texture.py", line 277, in _resize
    internalformat = self._check_internalformat_change(internalformat, shape[-1])
  File "/Users/jni/projects/vispy/vispy/gloo/texture.py", line 260, in _check_internalformat_change
    raise ValueError(
ValueError: Invalid texture internalformat: 'r32'. Allowed formats: {'r8': 1, 'r16': 1, 'r16f': 1, 'r32f': 1, 'rg8': 2, 'rg16': 2, 'rg16f': 2, 'rg32f': 2, 'rgb8': 3, 'rgb16': 3, 'rgb16f': 3, 'rgb32f': 3, 'rgba8': 4, 'rgba16': 4, 'rgba16f': 4, 'rgba32f': 4, 'luminance': 1, 'alpha': 1, 'red': 1, 'luminance_alpha': 2, 'rg': 2, 'rgb': 3, 'rgba': 4}

ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/jni/projects/vispy/vispy/app/backends/_qt.py", line 844, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 454, in __call__
    self._invoke_callback(cb, event)
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 472, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/jni/projects/vispy/vispy/util/event.py", line 470, in _invoke_callback
    cb(event)
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/jni/projects/vispy/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/Users/jni/projects/vispy/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/Users/jni/projects/vispy/vispy/visuals/visual.py", line 436, in draw
    if self._prepare_draw(view=self) is False:
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 856, in _prepare_draw
    self._build_texture()
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 815, in _build_texture
    self._texture.set_data(self._data)
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 329, in set_data
    self._reformat_if_necessary(data)
  File "/Users/jni/projects/vispy/vispy/visuals/image.py", line 322, in _reformat_if_necessary
    self._resize(data.shape, internalformat=internalformat)
  File "/Users/jni/projects/vispy/vispy/gloo/texture.py", line 277, in _resize
    internalformat = self._check_internalformat_change(internalformat, shape[-1])
  File "/Users/jni/projects/vispy/vispy/gloo/texture.py", line 260, in _check_internalformat_change
    raise ValueError(
ValueError: Invalid texture internalformat: 'r32'. Allowed formats: {'r8': 1, 'r16': 1, 'r16f': 1, 'r32f': 1, 'rg8': 2, 'rg16': 2, 'rg16f': 2, 'rg32f': 2, 'rgb8': 3, 'rgb16': 3, 'rgb16f': 3, 'rgb32f': 3, 'rgba8': 4, 'rgba16': 4, 'rgba16f': 4, 'rgba32f': 4, 'luminance': 1, 'alpha': 1, 'red': 1, 'luminance_alpha': 2, 'rg': 2, 'rgb': 3, 'rgba': 4}
```

</details>

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

See #204, #569, #713, #1759, napari/product-heuristics-2020#38

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by djhoese** [comment]
Did...did I make up the `r32` format? Well I guess I'll have to improve my tests and come up with something better.

**Comment by djhoese** [comment]
I think we are limited to the formats listed here:

https://github.com/vispy/vispy/blob/b6cbf11bd506d48c435c6e01e36e89fc54a16d1e/vispy/gloo/glir.py#L373-L395

I can't seem to find away around that. We may need to do the hacky 32-bit float view of the 32-bit integers. When I started my PR I must have seen the R8 and R16 and just kept going to R32 even though that isn't a supported format.

**Comment by sofroniewn** [comment]
Now that https://github.com/vispy/vispy/pull/1920 has merged we can try this with vispy master, will be great to see if it works! I'm happy to help test too :-)

**Comment by djhoese** [comment]
During the Feb Sprint I attempted to add the non-normalized texture formats to VisPy, but could not get OpenGL to let me use them. I have a feeling they require telling PyQt (or other backend) to use the "Core" OpenGL profile or something similar. This has never worked very well for me so I think if you want something not normalized in the GPU you'll either need to convert to floats or represent the integers as floats like @jni mentioned in a call we had about this. For example, `some_32int_data.view(np.float32)` and pass that to VisPy.

**Comment by liu-ziyang** [comment]
@DragaDoncila are you working on something similar? anything you want to link here?

**Comment by jni** [comment]
No, @DragaDoncila is working on the low-hanging CPU fruit I pointed out in #2380, which doesn't deal with the shaders themselves.

**Comment by jni** [comment]
Superseded by #3308

**Pull request closed without merging**
