### PR TITLE
Added sphinx-gallery

### LINKED ISSUE #1387: Executed examples in the docs
## 📚 Documentation
It would be great to be able to use sphinx-gallery together with `nbscreenshot` to run our examples for our documentation and embed screenshots.

The tutorials would also be great to run automatically, although that might be not be feasible since some use large datasets, or demonstrate interactivity.

### PR DESCRIPTION
**Pull request by melissawm**
# Description
Adds a basic gallery to the website, exposing all files under the `examples` folder.

A few notes:
- As of now, the examples are not actually executed to generate the gallery, which is why there are no new images set as thumbnails or in the examples themselves. This can be investigated later, and is an easy option to activate. I have also verified that all examples are running, but some require extra dependencies which further complicated this execution.
- I added a custom.css file to eliminate extra styling on the download buttons for each example, but this should probably live in the theme. 
- Some of the examples could probably use better titles and descriptions - feel free to make suggestions!
- We could also benefit from some nesting/organization of examples such as folders or tags. This can also come at a later stage (or now if you have ideas!)

Any feedback or ideas for improvement is appreciated!

EDIT: Closes #1387

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
this is a great base to build on, thanks @melissawm!

>As of now, the examples are not actually executed to generate the gallery, which is why there are no new images set as thumbnails or in the examples themselves. This can be investigated later, and is an easy option to activate. I have also verified that all examples are running, but some require extra dependencies which further complicated this execution.

agreed, should come in a later PR, as it will likely require a lot of per-file consideration.  just out of curiosity though, I took a stab at it using `qtgallery`.  So, some notes for a future PR:

1. add `qtgallery` to extensions and requirements.txt
2. update `sphinx_gallery_conf` to set `plot_gallery` to True, and add the qtgallery scrapers:
```python
   import qtgallery

   sphinx_gallery_conf = {
       ...
       "image_scrapers": (qtgallery.qtscraper,),
       "reset_modules": (qtgallery.reset_qapp,),
   }
   ```
3. hide all the `napari.run()` commands behind `if __name__ == '__main__':`
   ```python
   if __name__ == '__main__':
       napari.run()
   ```
4. deal with all the examples that don't execute without additional deps :joy:

Untitled1
Untitled 2

**Comment by melissawm** [comment]
OOooh I love this - did not know about qtgallery! Let me play with it but I am +1 on adding it to this PR to enable the nice screenshots. I was struggling a bit to come up with a solution.

**Comment by melissawm** [comment]
Here's an attempt at using the qtgallery. I disabled the broken examples by appending an underline at the end of the filename just as a temporary convention.

**Comment by brisvag** [comment]
This is amazing, love it!

For additional deps: what about adding to `setup.cfg` and `examples` extra dep section?

**Comment by jni** [comment]
I wonder whether there's a way to add "postprocessing" code to the gallery generation, so that every example would have a `nbscreenshot(viewer)` call appended to it, for example? Even if it requires a PR to sphinx-gallery? All good if qtgallery works, but it seems there's still a few warts with it, so thought I'd throw some ideas out there.

@melissawm it seems you missed a critical part from Talley's notes in your last commit:

> hide all the `napari.run()` commands behind `if __name__ == '__main__'`: 

Again, I'm not sure if that is the best approach compared to preprocessing of the scripts.

Definitely all this is looking so promising though! :heart:

**Comment by DragaDoncila** [comment]
I absolutely love where this is going, and I feel like it's probably one of the single most useful things we can do to expose a rich set of usage documentation. 

I don't have any input really on the nuts and bolts of the generation, because I'm not too familiar with the space. I did notice a few things which I'll leave here - I don't think they all need to be addressed in this PR:

- The theme changes after theme-setting examples for all subsequent examples. I actually don't mind this necessarily but I guess ideally we would be keeping things consistent?
- I think we definitely need some sort of tagging or categorization system for the gallery. I'm not sure whether there are already existing tools to allow this or whether we want to add subdirectories to the gallery but I think this is relatively high priority
- There are some outdated examples e.g. the reader plugin and we may need to update the docstrings of some of these examples with more complete explanations. We probably need a full review of each example but this can come later

Overall I'm a huge fan @melissawm

**Comment by jni** [comment]
> The theme changes after theme-setting examples for all subsequent examples. I actually don't mind this necessarily but I guess ideally we would be keeping things consistent?

Oh man, some of the screenshots above suggested that but I didn't understand why so I :shrug:ed, but indeed this is a huge problem I think. How do we deal with examples that demonstrate how to change state? Is there a way to configure sphinx-gallery to reset napari preferences after each example?

> I'm not sure whether there are already existing tools to allow this or whether we want to add subdirectories to the gallery

Yes, sphinx-gallery works from sub-directories with READMEs, see e.g.:

https://scikit-image.org/docs/stable/auto_examples/

generated from:

https://github.com/scikit-image/scikit-image/tree/main/doc/examples

But I fully agree with @melissawm that this can come in a subsequent PR.

**Comment by sofroniewn** [comment]
I'm super excited about this. We're getting some failing tests, and when I try and build docs locally I get a seg fault with `set_theme.py`. Maybe we just exclude that one for now.

```
make: *** [docs] Segmentation fault: 11] set_theme.py
```

It would be great to get this one over the finish line and in - let us know @melissawm if you need help!! Thanks!!

**Comment by melissawm** [comment]
I think I got all of it - @sofroniewn can you test again? I think it was actually another example that was creating an issue, but it should be good now. As far as I'm concerned this is good to merge now, unless you folks think the organization or sub-galleries is a blocker.

**Comment by sofroniewn** [comment]
I think the
```
make: *** [docs] Segmentation fault: 11] set_theme.py
```
error was actually caused by my settings, once i reset them it built correctly

This is truly increadible I love it. I think so many of us have been dreaming about this PR for so long and I can't belive it is now here! 

Screen Shot 2022-03-31 at 8 41 15 PM

I think we should merge as is and then do increased organization/ subgalleries in a followup PR

**Review by sofroniewn — APPROVED** [review]

**Review by jni — APPROVED** [review]
So much ❤️!

**Comment by psobolewskiPhD** [comment]
Really excited for this. The examples are sooooo valuable!

**Comment by lucyleeow** [comment]
I know this is old but could someone enlighten me on why we want:

> hide all the napari.run() commands behind if __name__ == '__main__':

thank you.

**Comment by brisvag** [comment]
I think otherwise if you import them as modules the qt loop is started and everything blocks.

**Pull request merged**
