### PR TITLE
add github links to contributor list

### PR DESCRIPTION
**Pull request by boonepeter**
# Description

Addresses issue #995. I changed the script to keep track of users by login, then write out their name as the text with a link to their github profile.

## Type of change

- [x] documentation
# References

# How has this been tested?

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
@boonepeter this is looking good, thanks for taking it on.

Right now is looks like each name in the list starts with '\`' and ends with a '\`_' 

I don't know so much about `rst` format but is there a reason for that? Is that the link syntax?

- \`Nicholas Sofroniew <https://github.com/sofroniewn>\`_

Maybe instead it would be nice to have just the handle appear with an @ symbol and bold - so as follows, and at the beginning followed by hyphen name (bonus points if the handle can be a link to the right page too):

- **@sofroniewn** - Nicholas Sofroniew

Given that one of the major things I do with release notes is post them into GitHub, which is expecting to render markdown, I wonder @jni and @kne42 if we shouldn't make this script generate md files instead of rst files? And tweak things to look nice as md. That could make this a lot easier

**Comment by boonepeter** [comment]
Yeah that is the rst link format. I like markdown better as well, esp since it renders well everywhere on GitHub.

**Comment by sofroniewn** [comment]
@boonepeter can you do a conversion to md for the autogeneration in this PR? Don't worry about the old existing files, I can convert them some other time if we want

**Comment by boonepeter** [comment]
Will do

**Comment by jni** [comment]
@sofroniewn @boonepeter Well, the main question is whether we are intending to eventually serve the release notes on napari.org using sphinx. If so, it might be best to stay with ReST for now, which I think github renders correctly anyway, see e.g. here: https://github.com/scikit-image/scikit-image/blob/master/doc/source/skips/0-skip-process.rst

In the long term, the sphinx folks are working on an extension to markdown to enable all of the ReST features that it's missing (e.g. cross-document linking and referencing, executable directives), but I think that is a long way from prime time.

At any rate, I do think we should stick to ReST for now...

**Comment by jni** [comment]
@sofroniewn here's a quick reference for ReST syntax: http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

**Comment by boonepeter** [comment]
Either way works well, so I can leave it as ReST for now.

Also, the pull request titles don't match up with the different categories (New Features, Improvements, etc.). Do you want me to use Github labels to do that or do you manually organize the pull requests after the fact?

**Comment by jni** [comment]
We manually organise. Let's just leave them as is for now. Sometimes PRs evolve beyond their original scope, and labels don't quite match/necessarily get updated.

**Comment by sofroniewn** [comment]
> At any rate, I do think we should stick to ReST for now...

Fine with me, thanks for the ReST link!!

**Comment by boonepeter** [comment]
Cool. It should work as it is. I can tweak it if you would like the final ReST output to look different, like one of the following:
- Juan Nunez-Iglesias [@jni](github.com/jni)
- Juan Nunez-Iglesias  - [@jni](github.com/jni)
- Juan Nunez-Iglesias ([jni](github.com/jni))
- [Juan Nunez-Iglesias](github.com/jni)
- [Juan Nunez-Iglesias @jni](github.com/jni)
- [Juan Nunez-Iglesias - jni](github.com/jni)
- [Juan Nunez-Iglesias (@jni)](github.com/jni)

GitHub's username rendering, hovering, and auto-linking is pretty nice, so it would be sorta cool to keep that. You could use readthedoc's [markdown to rst converter](https://github.com/readthedocs/recommonmark) to convert.
Then you could do something like this in ReST and it would look good on both:
- [Juan Nunez-Iglesias](github.com/jni) @jni

**Comment by sofroniewn** [comment]
>GitHub's username rendering, hovering, and auto-linking is pretty nice, so it would be sorta cool to keep that. You could use readthedoc's markdown to rst converter to convert.
Then you could do something like this in ReST and it would look good on both:
>
>Juan Nunez-Iglesias @jni

I liked this last option the best, though I would make the name link

be: https://github.com/napari/napari/commits?author=jni
instead of: https://github.com/napari/napari/compare/github.com/jni?expand=1

Also if if goes name then handle, can you keep the order of the list alphabetical by first name.

I will let @jni comment on "readthedoc's markdown to rst converter to convert". Personally I much prefer having md files in our repos and then autoconverting to rst if we need to for readthedocs, but maybe best to let @jni weigh in before going further

**Comment by jni** [comment]
Oops, apologies that I missed this. The github autohover is very good for usability. @boonepeter I couldn't tell whether this was something you could do only with markdown or with both formats? If it can work with ReST, let's stick with it, and we can make a ReST->md PR later. If it only works with markdown, let's bite the bullet and use that.

**Comment by boonepeter** [comment]
No worries, @jni! The hovering and auto linking is just markdown, so I will edit things a little to produce a .md output.

**Comment by boonepeter** [comment]
@jni and @sofroniewn, I lied about github rendering usernames nicely for markdown. It actually only does it in pull requests/issues, not random .md files in your repository. So I am leaving this as ReST formatted output per @jni's suggestion. 

The users will be sorted by first (real) name and I put two links in, one to the user's commits, and the other to the user's github profile. It looks like this raw:
```
- `Ahmet Can Solak <https://github.com/napari/napari/commits?author=AhmetCanSolak>`_ - `@AhmetCanSolak <https://github.com/AhmetCanSolak>`_
```

But will be rendered like this:

- [Ahmet Can Solak](https://github.com/napari/napari/commits?author=AhmetCanSolak) - [@AhmetCanSolak](https://github.com/AhmetCanSolak)

Sorry this has been a little more complicated than needed.

**Review by sofroniewn — APPROVED** [review]
Hi @boonepeter when I look at the generated rst file it looks amazing - just what we want, so I will approve, but I do have one more question
image

I also though (if possible) would like to be able to paste the contents on the doc into our release page - see this one for example, https://github.com/napari/napari/releases/tag/v0.2.12, but this one renders as markdown by default, so if I assume similar to the way issues render bellow it would appear as follows

image

Is there anyway maybe to make that issue understand it is being given `rst` instead of markdown and have it do the right thing? Is there another way you'd recommend approaching this?

Thanks again for the very nice work!! And apologies this ended up being a little complicated

**Comment by boonepeter** [comment]
Ahh...I didn't check how github would render release notes.

They do render the handles nicely:
image

They also auto link to issues and pull requests.

So I guess markdown really would be the way to go. I could throw in a command line argument to specify the output format?

**Comment by sofroniewn** [comment]
> So I guess markdown really would be the way to go. I could throw in a command line argument to specify the output format?

Maybe at this point that is the best option, but I'll ultimately just want to generate one file per release. I'm curious what @jni and @kne42 thinks. Just for clarity I want to point out that we have two competing needs

1. Rendering release notes in our documentation see [link here](https://napari.org/docs/release/release_0_2_12.html) for example. This is autogenerated from the file in the repo, and I guess is better as `.rst` but could be `.md` if we did a conversion somewhere (as I understand).
2. Rendering release notes in the release tab on our GitHub see [link here](https://github.com/napari/napari/releases/tag/v0.2.12) for example. This is generated by me copying and pasting the contents of the documents into a GitHub release tag, which I think behaves like a GitHub issue and so renders markdown well. If we could make it render `.rst` by using some special markup that would be great, but I can't see how to do that. I could also use [pandoc](https://pandoc.org/) to convert the `.rst` to markdown, though with the current formatting when I [tried it](https://pandoc.org/try/) I get

  - [Genevieve
    Buckley](https://github.com/napari/napari/commits?author=GenevieveBuckley)
    - [@GenevieveBuckley](https://github.com/GenevieveBuckley)
  - [Grzegorz
    Bokota](https://github.com/napari/napari/commits?author=Czaki) -
    [@Czaki](https://github.com/Czaki)
 
Which doesn't look so nice because of the multiple lines. If we could fix that so the automatic pandoc conversion made those all on one line too, then it's not that big a deal for me to do it before pasting in the release notes, but maybe it would be nice if I didn't have to.

I probably should have put both those use-cases in the original issue, it might have saved some confusion. My apologies.

**Comment by boonepeter** [comment]
@jni and @sofroniewn, sorry for the delay. I have changed the output format to markdown. It looks like you already have the sphinx markdown to rst parser here: https://github.com/napari/napari/blob/7650eb732d665dbbc1d73d13c52ac6d8beb8a838/docs/source/conf.py#L71

This should render these release note correctly on napari.org.

**Comment by sofroniewn** [comment]
Looks beautiful @boonepeter 

image

I'm am merging now, thanks for pushing this one through to the finish line. I will merge now

**Pull request merged**
