### PR TITLE
Allow just backspace to delete a layer

### PR DESCRIPTION
**Pull request by jni**
# Description

I often find that I want to delete a layer with just backspace. Since that key is not used for anything else, it might as well be used here?

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Backspace is actually used in the points layer to delete selected points - see https://github.com/napari/napari/blob/master/napari/layers/points/_points_key_bindings.py#L62

We don't really have much of a rule anymore for what types keybindings live on layers (say modified/ unmodified) vs viewer.

I'm open to any changes, we should just try and be consistent

**Comment by jni** [comment]
> Backspace is actually used in the points layer to delete selected points

That's great, but can the shortcut be dependent on what part of the UI is selected? ie, backspace deletes what I have just selected, be it a point, a shape, or a layer.

**Comment by jni** [comment]
> I'm open to any changes, we should just try and be consistent

Well, I just added a key to the existing binding. Hard to be more consistent than that. =P

**Comment by sofroniewn** [comment]
> That's great, but can the shortcut be dependent on what part of the UI is selected? ie, backspace deletes what I have just selected, be it a point, a shape, or a layer.

We could do that, but right now I think the keybindings are additive, so we'd need to make some changes - otherwise every time you deleted some points you'd also delete the whole layer

**Comment by jni** [comment]
> otherwise every time you deleted some points you'd also delete the whole layer

Might save users some time??? :joy: 

Ok fair enough. I'll try to rework this a bit. Would be great to get some advice from @kne42 when she comes back about the best way to achieve this — or if it's even feasible with the current framework.

**Comment by cwood1967** [comment]
If someone is changing the name of a layer, they will often need to backspace to to fix something. It might be too easy to hit tab or something to take you out of edit mode and have the layer deleted when that is not desired.

**Comment by sofroniewn** [comment]
@jni i think we can close this now since we are moving to user configurable shortcuts, at which point you will be able to customize this as you wish!!

**Pull request closed without merging**
