### PR TITLE
PR: Add interface language selection to preferences

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

This adds the option to select the interface language if any language pack has been installed.

image

This Pr does the following:

- [ ] Loads language settingsa directly, since the models need to use them. To do this I moved some variables to a `_base.py`. Not a great name so I am open to suggestions :)
- [ ] Created a base settings class, to simplify code in models a bit.
- [ ] Added the language to the settings and created a `Language`  class to be able to dynamically check for installed language-packs (if any). 

## For another PR
- A separate PR will add the prompt for a restart.
- Investigate how to pass a mapping for the options, so we can display "Spanish (Spain)"  instead of "es_ES".

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by goanpeca** [comment]
You can install the language pack for testing from the language packs repo

https://github.com/napari/napari-language-packs/tree/main/language-packs/napari-language-pack-es-ES

```
pip install -e .
```

**Review by ppwadhwa — APPROVED** [review]
I think this all looks good. The one comment I want to make is that when looking for the `Preferences` dialog to change it back from Spanish to English, I noticed that the option for Preferences moved.  Mac moves it to a particular location on the first drop down menu and gives the `Preferences` dialog a particular keyboard shortcut.  When you change the language to Spanish, it doesn't do that. It puts it where we told it to go in the code with the shortcut that we assigned to it.  Is there a way to keep the behavior the same?

**Comment by goanpeca** [comment]
Thanks Pam, I have a fix for that issue

**Comment by goanpeca** [comment]
Made the fix @ppwadhwa

**Review by Carreau — APPROVED** [review]

**Comment by ppwadhwa** [comment]
@goanpeca Works great!  Are you planning to fix the translations on the preferences dialog with this PR?  
Screen Shot 2021-03-26 at 10 56 59 AM

**Comment by goanpeca** [comment]
>Works great! Are you planning to fix the translations on the preferences dialog with this PR?

Thanks @ppwadhwa, added new localizable strings (they are not on the language pack) so they will not appear on the current one, but will be localized soon :)

**Review by sofroniewn — APPROVED** [review]
Ok nice, this is looking really good! Thanks @goanpeca for the PR and others for review. I'm approving now, but will leave open until tomorrow in case anyone else wants to add further comments. Really cool to see translation coming to napari!

**Review by tlambert03 — APPROVED** [review]
yep, lovely work as always

**Pull request merged**
