### PR TITLE
Create component folders

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description

This PR refactors the position of our files to be organized by components. The justification is presented in issue #111. Curious what people think around organisation / naming. None of the files have changed in content beyond the naming

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# References

# How has this been tested?

- [x] ran `examples/layers.ipynb`

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by freeman-lab** [comment]
This seems like a great direction to me! Two suggestions, based on an offline chat with @sofroniewn

1) rename `elements` -> `components` for (loose) consistency with various web MVC naming conventions

2) for cases where there are multiple views, add a `view` folder and put the different views inside it, i.e. use

```
layer/model.py
layer/view/one.py
layer/view/two.py
```

rather than

```
layer/model.py
layer/view_one.py
layer/view_two.py
```

Just feels a bit cleaner and more consistent.

**Comment by sofroniewn** [comment]
I have implemented the two suggestions by @freeman-lab. Maybe @kne42 or @shanaxel42 wants to weigh in as they were both present during some discussions around this topic (further fleshed out in #111).

**Review by kne42 — APPROVED** [review]
I like this PR as a way of reorganizing how our existing classes are structured in terms of filepaths. However, I think that ultimately the direct reference of an MV(C) architectural pattern is inaccurate since:
- the brightness/contrast control bar is a view of a layer
- a vispy visual is a view of a layer
- the control/layer panels are not really attributed to any models
- the window is both a model and its view
- the dimensions bars are (conceptually) a view of the canvas

(correct me if I'm wrong @shanaxel42)

These were really just intended as points for discussion so I'm going ahead and approving this while we come to a decision on our ultimate architectural design and we can create a follow-up PR.

**Comment by freeman-lab** [comment]
agree with @kne42 that it makes sense to merge this now and we’ll continue to clarify the architecture

approving!

**Review by freeman-lab — APPROVED** [review]
lgtm!

**Review by AhmetCanSolak — APPROVED** [review]
I think this will be really helpful for future architecting the project. @sofroniewn thanks.

**Pull request merged**
