### PR TITLE
async-24: Multiscale Octree w/ Async Loading (Golden Spike)

### PR DESCRIPTION
**Pull request by pwinston**
# Multiscale Octree w/ Async Loading

* We can now create an octree from multiscale data:
    * Previously we were only creating octrees from single-scale images.
    * The new test image "digits" creates a multi-scale image first, then renders that.
* All octree data access now goes through the  `ChunkLoader`
    * This is hooking the octree up to the existing async loading.
    * Same as before but now a chunk is a chunk of the octree, as was always planned.

Here we are panning in-memory data, `ndarray`'s,  so `ChunkLoader` loads synchronously:

napari-async-octree-nodelay

To illustrate `ChunkLoader` is doing something, here we use `@dask.delayed` to insert a random delay into every chunk access. This is not napari just directly sleeping. Instead we are rendering an octree full of `dask` chunks, and when the `ChunkLoader` calls `asarray` dask does the sleep. So it's a good proxy for any sort of network or compute latency:

napari-async-octree

# Background

Prior to this PR all test images were single scale images, but under the hood we created a multi-scale octree on the fly inside `OctreeImageSlice`. That is, when viewing a single-scale image we created an octree and visualized it with that octree. This was just a quick and dirty way to work on the octree visuals. 

Now that the visuals are working, and async was always working, this PR was all about hooking those two together, hence the title [Golden Spike](https://en.wikipedia.org/wiki/Golden_spike). 

With this PR we can now create multi-scale test images. This PR add as a new `OctreeMultiscaleSlice` class to replace `OctreeImageSlice`. The new `OctreeMultiscaleSlice` is for visualizing multi-scale data using the octree natively, how it will be done for real. Taken together `OctreeImage` and `OctreeMultiscaleSlice` are meant to eventually replace the original `Image` class.

# One Image To Rule Them All

When this code is promoted from experimental, the hope is:
* `OctreeImage` becomes the new `Image`
* `OctreeMultiscaleSlice` become the new `ImageSlice`

So one code path and one visual handles every type of image, even though there are three different cases, two of them kind of degenerate:

| Type | Description | Octree Usage |
|---|---|---|
|Type 1|Small image **without** downsampled levels |Octree with level zero only, one tile only|
|Type 2|Large image **without** downsampled levels|Octree with level zero only, a grid of tiles|
|Type 3| Large image **with** downsampled levels|Octree with all levels fully populated|

An example of Type 1 is a 1024x1024 image. We set the tile size to 1024x1024 and we create a octree with no downsampled levels. So the tree is one level which contains one tile.

An example of Type 2 is a 16384x8192 image with no downsampled levels. We create an octree that only has level 0. Let's say we are using 256x256 tiles. The level 0 will have 2048 tiles in the shape 64x32. This will work great when zoomed in, you can pan around fine.

What we do when zoomed out is TBD. Without downsampled tiles you would need to display all 2048 tiles. We might allow that but you will just have to wait while they load in a few at a time. Eventually, you might run out of VRAM. We probably need to compute downsampled tiles on the fly in the background. And swap 4 small tiles with 1 downsampled tile, basically building the full octree. We'd probably not attempt that anytime soon.

An example of Type 3 is any old multiscale image. The octree is fully populated with all levels, and we render using the most appropriate level.

For all three types of time we will use the same `Image` class, same `ImageSlice` class, and same visual classes: `VispyTiledImageLayer`, `TiledImageVisual`, `TextureAtlas2D`. So the code is all the same, although Type 1 and Type 2 will bypass portions of it.

# Legacy

With a new unified `Image` and `ImageSlice` these classes can be deleted:

* `ImageSliceData`
* `ChunkedSliceData`
* `OctreeImageSlice`
* `ImageLoader`
* `ChunkedImageLoader`

Those classes were basically bending over backwards to support async/octree without changing the existing `Image` class. The new `Image` class will be structurally a lot simpler. Although the octree stuff makes it fairly complicated under the hood, but it will be simpler itself.

The advantage of one code path is there is no duplicated code, and there is only one path to understand, debug, and extend.

# Next Steps

A lot of code was bypassed or disabled to get this working at a basic level first. The two big missing things are `clim` support or other processing of the image, and proper multi-dimensions support such as multiscale time-series and higher dimensionalities.

Soon get it working with real data and then slowly expand the number of type of real data it works with.

## Type of change
- [x] New features in experimental code

# How has this been tested?
- [x] Manual testing

# Files
async-24-files

### CODE REVIEW

**Comment by pwinston** [comment]
Ready for review. The PR description is accurate and fairly detailed.

I updated the Octotree file image, it's still just one line of one non-experimental file that changed: `image.py`.

**Comment by sofroniewn** [comment]
> To illustrate ChunkLoader is doing something, here we use @dask.delayed to insert a random delay into every chunk access. This is not napari just directly sleeping. Instead we are rendering an octree full of dask chunks, and when the ChunkLoader calls asarray dask does the sleep.

At some point this would be great to add to our examples so we could just run `python examples/delayed_digits.py` or something an see that example. Doesn't have to be this PR, just noting for the future

**Comment by sofroniewn** [comment]
> What we do when zoomed out is TBD. Without downsampled tiles you would need to display all 2048 tiles. We might allow that but you will just have to wait while they load in a few at a time. Eventually, you might run out of VRAM. We probably need to compute downsampled tiles on the fly in the background. And swap 4 small tiles with 1 downsampled tile, basically building the full octree. We'd probably not attempt that anytime soon.

Wow, this would be really cool!!

**Review by sofroniewn — APPROVED** [review]
Changes look good to me @pwinston, nice work. I'm approving. If you can fix the one failing test I will then merge. I will also rename PR to "Multiscale Octree w/ Async Loading (Golden Spike)" so that we get both the nice reference and the literal on what this PR does.

**Pull request merged**
