### PR TITLE
Add HighDPIScaling policy to fix GUI scaling issues under Windows

### LINKED ISSUE #367: Window scaling issue on Linux and Windows
## 🐛 Bug

The drop down menu has scaling issues on linux
image

## To Reproduce
Run `python examples/labels-0-2d.py` and expand drop down menu for segmentation

## Environment

 - napari: 0.9
 - Linux Ubuntu 18.04LTS
 - Python version: 3.7
 - Laptop: Lenovo X1 Carbon 6th gen

### LINKED ISSUE #530: The GUI seems a little off with a HighDPI screen
## 🐛 Bug

image

## To Reproduce

```
$ pip list
Package          Version          Location
---------------- ---------------- ---------------------
backcall         0.1.0
certifi          2019.9.11
cycler           0.10.0
decorator        4.4.0
freetype-py      2.1.0.post1
imageio          2.5.0
ipykernel        5.1.1
ipython          7.8.0
ipython-genutils 0.2.0
jedi             0.15.1
jupyter-client   5.3.1
jupyter-core     4.5.0
kiwisolver       1.1.0
matplotlib       3.1.1
napari           0.1.5+4.ge16e116 /home/mark/git/napari
networkx         2.3
numpy            1.17.2
parso            0.5.1
pexpect          4.7.0
pickleshare      0.7.5
Pillow           6.1.0
pip              19.2.3
prompt-toolkit   2.0.9
ptyprocess       0.6.0
Pygments         2.4.2
PyOpenGL         3.1.0
pyparsing        2.4.2
PySide2          5.13.1
python-dateutil  2.8.0
PyWavelets       1.0.3
pyzmq            18.1.0
qtconsole        4.5.5
QtPy             1.9.0
scikit-image     0.15.0
scipy            1.3.1
setuptools       41.2.0
shiboken2        5.13.1
six              1.12.0
tornado          6.0.3
traitlets        4.3.2
vispy            0.6.1
wcwidth          0.1.7
wheel            0.33.6
```

```
$ conda list
# packages in environment at /home/mark/miniconda3/envs/napari:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
backcall                  0.1.0                    pypi_0    pypi
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.0                    pypi_0    pypi
freetype-py               2.1.0.post1              pypi_0    pypi
imageio                   2.5.0                    pypi_0    pypi
ipykernel                 5.1.1                    pypi_0    pypi
ipython                   7.8.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.15.1                   pypi_0    pypi
jupyter-client            5.3.1                    pypi_0    pypi
jupyter-core              4.5.0                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
matplotlib                3.1.1                    pypi_0    pypi
napari                    0.1.5+4.ge16e116           dev_0    <develop>
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                      pypi_0    pypi
numpy                     1.17.2                   pypi_0    pypi
openssl                   1.1.1c               h516909a_0    conda-forge
parso                     0.5.1                    pypi_0    pypi
pexpect                   4.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    6.1.0                    pypi_0    pypi
pip                       19.2.3                   py37_0    conda-forge
prompt-toolkit            2.0.9                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pygments                  2.4.2                    pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 2.4.2                    pypi_0    pypi
pyside2                   5.13.1                   pypi_0    pypi
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                    pypi_0    pypi
pywavelets                1.0.3                    pypi_0    pypi
pyzmq                     18.1.0                   pypi_0    pypi
qtconsole                 4.5.5                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.0                  hf8c457e_0    conda-forge
scikit-image              0.15.0                   pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi
setuptools                41.2.0                   py37_0    conda-forge
shiboken2                 5.13.1                   pypi_0    pypi
six                       1.12.0                   pypi_0    pypi
sqlite                    3.29.0               hcee41ef_1    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tornado                   6.0.3                    pypi_0    pypi
traitlets                 4.3.2                    pypi_0    pypi
vispy                     0.6.1                    pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

## Expected behavior
Better spacing between buttons
## Environment

Ubuntu 19.04 + XPS 15 with a high DPI 4k screen.
200% scaling. Wayland I guess.

## Additional context

In my applications, I Created my gui with QtCreator, then use 
https://github.com/hmaarrfk/qtpy-tools
To convert the UI file to a py file.

After that, my spacing is kinda ok for high dpi and normal dpi screens. Not sure if that can help you in your challenges.

### PR DESCRIPTION
**Pull request by honkomonk**
**I have to retract this PR. While it fixes the issue with the scaling of the UI elements, it has the side effect to trigger an [issue in VisPy](https://github.com/vispy/vispy/issues/2189). I have to do more testing to see if it's still a bug in VisPy or a matter of the right parameters.**

# Description

This small change sets Qt's scaling policy for the OS settings for the desktop. Contrary to what [the documentation says](https://doc.qt.io/qt-6/qguiapplication.html#setHighDpiScaleFactorRoundingPolicy), the default appears not to be "PassThrough" but "Round". This results in scaling factors below 150% being rounded down to 100% and above rounded to 200%.

You can check this by opening the Help->napari Info menu and comparing the screen information with you systems settings.
In my case with 2 screens under Windows set to 125% and 150% scaling, the result without the fix:
image
... and with the fix:
image

## Note
This fixes the problem under Windows 10 with PyQt5. I testet it under Ubuntu 22.04 and it did not affect the reportet scaling there, but the GUI looked fine anyways. I had no Mac at hand to check it under macOS.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

[QGuiApplication::setHighDpiScaleFactorRoundingPolicy()](https://doc.qt.io/qt-6/qguiapplication.html#setHighDpiScaleFactorRoundingPolicy)
[Qt::HighDpiScaleFactorRoundingPolicy](https://doc.qt.io/qt-6/qt.html#HighDpiScaleFactorRoundingPolicy-enum)

might fix #530
might fix #367

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@napari/core-devs anyone have Windows to test the current status of this PR?

**Comment by DragaDoncila** [comment]
@psobolewskiPhD I've tested this on Windows and it works as described - napari's scale reflects the Windows scale value.

I don't notice any VisPy issues and it looks like the[ linked issue](https://github.com/vispy/vispy/issues/2189) was closed, so I don't think that's a concern? But I'm really not at all familiar with this stuff.

I checked the scaling on my Mac too and this PR had no effect on the scale values. When I change resolution on my Mac the scale just changes from 1.0 to 2.0 and I can't get any in-between values - but on Mac you specifically pick a resolution rather than scaling the UI so I don't know if it's equivalent. Anyway, since the behaviour is the same as on main, I don't think that should bother us.

**Comment by DragaDoncila** [comment]
@brisvag yeah I think I just don't have a high enough DPI screen to check this. On my 1920x1080 laptop in Ubuntu, bobth `main` napari and this PR just go from 1.0 to 2.0 scaling as soon as I increase scale past 100% (no rounding down like in the OP), but the canvas and viewer look normal. 

If you're saying this PR is borking Ubuntu scaling for high DPI screens we definitely can't move forward with this PR until we can verify if it's fixing Windows (it worked well for me on Windows but not sure if my screen counts since it's only 1920x1080). If we can verify it fixes Windows maybe we can do a platform specific setting here.

**Comment by brisvag** [comment]
> If you're saying this PR is borking Ubuntu scaling for high DPI screens we definitely can't move forward with this PR until we can verify if it's fixing Windows

Sorry, I wasn't clear: the cropped/offset canvas issue I described is happening on main as well. It's just not solved here :P

**Comment by andy-sweet** [comment]
I could reproduce the vispy error in the description on Windows 10 with a high DPI screen, so I'm marking this as draft so it doesn't get merged by accident.

windows-dpi-issue

**Comment by psobolewskiPhD** [comment]
Bump, does https://github.com/vispy/vispy/pull/2540 have any interaction with this one?

**Comment by melonora** [comment]
The PR currently does not solve the issues on my windows machine. Given the statement of retracting the PR I will close it. Thanks for looking into it though @honkomonk !

**Pull request closed without merging**
