### PR TITLE
Feature: add Label brush size keybinds that can be held down 

### LINKED ISSUE #3994: Brush size keybinding
## 🚀 Feature

Keybinding to change label paint brush size.
## Motivation

During labeling, I usually completely label each object (cell, cell colony, etc) before moving to another. To do so I label the coarse structure of the object first, using little zoom ("overview mode"). Then, I zoom in to label the finer details of the object (rim areas, branches, string-like features), before I switch to the next object. This involves quite a bit of paint brush size changing. 
Changing the size in the layer controls is inconvenient, as I have to move the cursor out of the image to be labeled, change the size, move back to the image to check if the new size is correct, (optionally move back to the layer controls to re-adjust), and then continue labeling. This disrupts the workflow.

## Pitch

I suggest a simple key binding (e.g. `q` and `e` to have them close to the `1`-`5` mode switches) to adjust the brush size.

## Alternatives

Alternatively, one could change the brush size using the mouse wheel (not used at the moment as far as I know).

## Additional context

This is my first request. I searched the issue list for potential duplicates of this request, but didn't find any, so I hope this request makes sense.
There already is a  menu `Preferences -> Shortcuts -> Group: Labels layer` to adjust keybinding, so I think it should be quite easy to add an option for brush size adjustment.

If anybody has pointers towards where this behavior is controlled, we ([MBPhys](https://github.com/MBPhys/) and me) are happy to implement this ourselves and merge it if you'll allow it.

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description
This PR adds [ and ] (from Photoshop) as keybinds for decreasing and increasing the Labels brush size. If they are held down, the size keeps increasing/decreasing. 
However, at the moment, to make the hold-down to increase/decrease work, the keybinds are hard-coded, so they are not registered (because if the user changed them, then the hold-down behavior wouldn't work.)

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
closes https://github.com/napari/napari/issues/3994
Uses the methodology by @RobAnKo to white-list [ and ] for repeating/hold-down behavior, see https://github.com/napari/napari/issues/3994#issuecomment-1025713296
The hold-down behavior (and white-list for arrow keys) is here:
https://github.com/napari/napari/blob/6a3e11aa717e7928a0a5a3c7693577729a466ef1/napari/utils/key_bindings.py#L471-L490

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change: I edited the test to account for the 2 extra layer method
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by alisterburt** [comment]
Omg, because of Grzegorz' recent work this works on press and hold? Or am I misunderstanding - either way 😍

**Comment by psobolewskiPhD** [comment]
> Omg, because of Grzegorz' recent work this works on press and hold? Or am I misunderstanding - either way 😍

No, that's different, pretty sure. 
Press-and-hold to repeat the key is currently only allowed for the arrows.
See:
https://github.com/napari/napari/blob/6a3e11aa717e7928a0a5a3c7693577729a466ef1/napari/utils/key_bindings.py#L471-L490

Here I've added [ and ] to the white-list and added them to Labels keybinds.
The need to white-list is why I've not just registered the keybinds.
But will poke around a bit more.

**Comment by alisterburt** [comment]
Sorry, read in a rush as I jumped on a plane, just saw you whitelisted the keys (I'm fine with this!)

We should definitely find a general mechanism for press and hold keybindings though :)

**Comment by RobAnKo** [comment]
The white-list approach using hard-coded keys works, but is hacky. It works as long as users stick to the hard-coded keys. When changing the brush size keybinding in Preferences -> Shortcuts -> Group: Labels layer, increase/decrease still works with the new key, but not press-and-hold if the new key is not in ['Up', 'Down', 'Left', 'Right', '[', ']' ].

My idea would be to add a boolean flag to ALL keybindings, which
- defines if this function allows autorepeat
-  is used to create a list of all autorepeat-able keys. This list could be referenced as exceptions in key_bindings instead of hard-coded keys.
- can be changed by the user in Preferences -> Shortcuts (an additional column 'autorepeat' in the menu with a simple checkbox)

As far as I understand, all key-bound callbacks are executed through the on_key_press method, which restricts them all to be executed only once, except for the navigation keys. Since there is probably a good reason to do that, adding additional flexibility through the autorepeat flag could be a useful pattern for this specific issue, but also for potential future extensions.

**Comment by psobolewskiPhD** [comment]
Maybe let's think how many other functions would benefit from auto-repeat before adding an extra flag/column for every keybind? For the majority it's probably useless.
Things like sizes, sliders, and movements is totally logical—it should be the default in fact, because every user that's used any other software would expect that behavior.
What else? 🤔 

Maybe instead of white-listing specific keys, it should be about white-listing specific registered keybindings? Maybe someone wants to move dims sliders using < and > and move objects using AWSD, so they could change those bindings and they'd still autorepeat, because those registered functions are autorepeating.
(Huh, I just noticed you *can't* use arrows to move stuff, like selected shapes/points. This seems like a big oversight?)

**Comment by Czaki** [comment]
Ridding out of encoded list need to be done using action manager when a programmer could register the action as repeatable. The action manager should have a method to check if some shortcut is autorepetable.

**Comment by RobAnKo** [comment]
> Maybe instead of white-listing specific keys, it should be about white-listing specific registered keybindings? 

I agree. 

Is the following situation realistic?

_We want a key (let's say "Left") to be autorepeatable in one context (e.g. moving objects around) but not in another context (e.g. switching between channels/dimensions)._ 


If this is a realistic scenario, we have to 

- control autorepeatability on the level of the action, since a specific key is sometimes autorepeatable and sometimes not.

If it is not realistic, we could 

- create a white-list based on the user-chosen shortcuts (i.e. from choices made in `Preferences -> Shortcuts`) which we then reference in L482 of https://github.com/napari/napari/blob/6a3e11aa717e7928a0a5a3c7693577729a466ef1/napari/utils/key_bindings.py#L471-L490
 
I'm not sure on how the action-level control might be implemented (@Czaki  maybe you know more?), but for the second option we could add an additional column in the `Preferences -> Shortcuts` table indicating with a boolean flag whether a given action is auto-repeatable. The set of keys belonging to auto-repeatable actions then represents the white-list.

In both scenarios we need additional settings controllable by the user, with some reasonable defaults already predefined. I think that a second column in the `Preferences -> Shortcuts` table representing these settings is a reasonable choice.

What do you think?

**Comment by Czaki** [comment]
At first, the repeatable field should be introduced in Action class https://github.com/napari/napari/blob/9bf5d0ff29438b3df3462f97427bdd8a326e596a/napari/utils/action_manager.py#L36

then update https://github.com/napari/napari/blob/9bf5d0ff29438b3df3462f97427bdd8a326e596a/napari/utils/action_manager.py#L102 to accept the repeatable argument

and implement similar function to `_get_active_shortcuts` (ex. `_get_active_repetable`)
https://github.com/napari/napari/blob/9bf5d0ff29438b3df3462f97427bdd8a326e596a/napari/utils/action_manager.py#L351
That will collect repeatable shortcuts based on the currently active keymap provider. 

Suppose we would like to allow users to change behavior in settings. In that case, it should be limited only to this action marked as ready by the creator because in the context of some actions, enabling such a thing has no sense (switch layer mode) or could be problematic (start in the background some calculation).

**Comment by alisterburt** [comment]
really loving the discussion here - @RobAnKo @psobolewskiPhD based on what @Czaki suggested it looks like we really aren't far away from achieving the final vision on this one! What do you think about trying to get (at least a minimal version of) it out there for 0.4.17?!

**Comment by RobAnKo** [comment]
I agree, @Czaki's suggestions and pointers are golden. I'll start working on it tomorrow :+1:

**Comment by psobolewskiPhD** [comment]
> I agree, @Czaki's suggestions and pointers are golden. I'll start working on it tomorrow 👍

I'm definitely out of my depth here and the action manager approach is obviously superior to this hard-coded approach, so @RobAnKo I suggest you make a new PR for that and then we can close this.

**Comment by alisterburt** [comment]
@RobAnKo very exciting! I'm cc-ing @andy-sweet who will be taking over the 0.4.17 release process from tomorrow

@psobolewskiPhD you bringing this back to the forefront has been a fantastic catalyst and is why we will have this in 0.4.17, thank you for the amazing work! 🥳

**Comment by andy-sweet** [comment]
I'm unsure about progress here for inclusion in v0.4.17.

The current code changes look OK to me, but my understanding of the conversation is that we want to avoid hard-coding these keybindings and that there is an alternative that @RobAnKo is working on. Is that correct? If so, what does progress look like? And is this likely to be done in the next day or two?

Given the changes could be quite isolated, I don't think this change would have to go in the first release candidate, but that depends on the new implementation. If we want this in v0.4.17, then the PR likely needs to be merged by the end of the week.

**Comment by RobAnKo** [comment]
Hi @andy-sweet !

> we want to avoid hard-coding these keybindings and that there is an alternative that @RobAnKo is working on. Is that correct?

That is correct. At the moment I am still in the process of reading the code to understand how keymaps, keybindings, events and the action manager interact with each other. If anybody has resources other than the code in 
[napari/utils/key_bindings.py ](https://github.com/napari/napari/blob/main/napari/utils/key_bindings.py)
[napari/utils/action_manager.py](https://github.com/napari/napari/blob/main/napari/utils/action_manager.py)
I'd be happy about a pointer. 

This is my first contribution to napari, so I'm pretty clueless about how long this will take. I feel like understanding the inner workings iand sketching a solution is the bottleneck, implementing the changes should not take long.

So I can't promise that I'll have a working solution within the next two days, but if I find one I'll open a new PR immediately.

**Comment by andy-sweet** [comment]
> This is my first contribution to napari, so I'm pretty clueless about how long this will take. I feel like understanding the inner workings iand sketching a solution is the bottleneck, implementing the changes should not take long.
> 
> So I can't promise that I'll have a working solution within the next two days, but if I find one I'll open a new PR immediately.

Thanks for clarifying! Based on that, sounds like we should not plan to add the alternative implementation to v0.4.17 (at least the first release candidate), so no pressure on the timing. If the work gets done quicker and expected, and the changes look isolated enough, we could consider bringing it into a later release candidate, but (without having much knowledge about this area of the code), it feels like a more natural fit for v0.5.

The remaining question is if we bring in the hard-coded keybindings for `[` and `]` for v0.4.17 (as with this PR right now). My intuition is to say no as we've lived without them until now, and we're working on an alternate implementation. But open to other opinions - maybe it's fine to have them hard-coded for 0.4.17 then set those as defaults (with the new/alternate) implementation for 0.5?

**Comment by RobAnKo** [comment]
Since the hard-coded version relies on the usage of a specific set of keys ("[" and "]") in Peters implementation, users who want to use other keys might be baffled by the loss of push-and-hold functionality. 
Since the hard-coded solution is really more of a workaround but easily implemented, I'd say we keep this PR as well as the initial [issue](https://github.com/napari/napari/issues/3994) open so people who are interested will find this and can change it for themselves if needed.
This way they will read that this is a half-baked solution and will not expect it to work flawlessly, which could lead to unnecessary confusion/issues.

So I agree with @andy-sweet on putting a proper solution in a later release candidate or 0.5. Gonna work hard on this nevertheless :hammer:

**Comment by andy-sweet** [comment]
> So I agree with @andy-sweet on putting a proper solution in a later release candidate or 0.5. Gonna work hard on this nevertheless 🔨

Thanks for clarifying! I updated the milestone to reflect this.

**Comment by RobAnKo** [comment]
For sake of completeness: I opened a new PR #5086 implementing the changes discussed here.

What might be missing is solid testing and a review by people who have a deeper understanding of general patterns and relations implemented in the napari event/keybinding/actionmanager ecosystem to assess whether this stuff makes sense.

**Comment by psobolewskiPhD** [comment]
Closing! https://github.com/napari/napari/pull/5086 is much better!
Kudos @RobAnKo and @Czaki

**Pull request closed without merging**
