### PR TITLE
Add progress bar when opening list of files

### LINKED ISSUE #3125: Progress bar when loading multiple files
## 🚀 Feature

Progress bar when loading multiple files (for example from drag n drop)

## Motivation

When loading multiple files it will be nice to have some feedback information, not frozen interface. 

## Pitch

As there Is a great threading mechanism with the generator worker then loading data could be moved to separated thread, layers added live and progress bar in the interface.

### PR DESCRIPTION
**Pull request by DragaDoncila**
# Description
Partially addresses #3125 by adding a progress bar when the user opens a list of files as individual layers. If only one path is being opened, progress bar is indeterminate. This PR doesn't thread the file reading, as that would require an API change for `viewer.open` (or us picking #2581 back up) - ~~draft PR incoming shortly to show~~ #3356 shows one of the options we have now.

https://user-images.githubusercontent.com/17995243/132453235-5aacc41e-cea8-4913-b579-2df3ba920eed.mp4

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
Partially addresses #3125.

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by DragaDoncila** [comment]
Because `progress` lives in `qt` we need to wrap its import in a `try-except` block - I think we should be able to do better than this, since `progress` actually works just fine in headless mode - reverting back to `qt` - this goes back to the discussion on #2661. Could we shift the burden of checking for `qt` imports onto `progress` itself somehow - @tlambert03 maybe you have some idea?

This would also be an issue with #3356 and other approaches we might take to thread reading, since `thread_worker` lives in and relies on `qt`.

**Comment by tlambert03** [comment]
> Could we shift the burden of checking for qt imports onto progress itself somehow - @tlambert03 maybe you have some idea?

yeah that's totally fine with me.  we do this same thing with our `Window` class.  If there's an object that has something to offer both with and without qt, then I think it's totally fine for it to live outside of `_qt`, try to import what it needs from `_qt` and fall back to the standard behavior otherwise.  `progress` seems like a good candidate to have some presence outside of `_qt`

**Review by sofroniewn — APPROVED** [review]
LGTM! Very cool, let's get this in 🚀

**Comment by sofroniewn** [comment]
Actually I may have spoken too soon here - sorry I hadn't caught the qt import was in the viewermodel and not the import the viewer. I actually really don't like the try catch pattern here - the point of separating the viewer model out was to have  a separation from qt and the try catch basically seems like a way to fool our headless test.

> Could we shift the burden of checking for qt imports onto progress itself somehow - @tlambert03 maybe you have some idea?

I still feel like this is just again subverting and fooling our headless test, but I'm not sure how to easily resolve. Maybe the open method like this really shouldn't be on the viewer model, but should be on the viewer itself where having the qt import is allowed (and one day `open` could move to an application like object or somewhere else).

Thoughts @jni?

**Review by sofroniewn — CHANGES_REQUESTED** [review]
See above

**Comment by tlambert03** [comment]
> I still feel like this is just again subverting and fooling our headless test, but I'm not sure how to easily resolve.

I think there's a difference: if we have some functionality that _fundamentally depends_ on Qt, and doesn't have a fallback, then the whole thing belongs in `_qt` and we should let it fail on import.  If we have something that has functionality that offers a gui when qt is present, and something else when it's not available, then that thing should live outside of `_qt`, try to import from `_qt` (for the gui part) and then provide the fallback behavior otherwise.

as long as a given section of the tests isn't flat out _skipped_ in the headless tests, then you can't really fool it: we literally uninstall qt in those tests, so if they pass (without skipping things) then it means the code still works headless

**Comment by sofroniewn** [comment]
> I think there's a difference:

Yeah that's fair. Something still happens in the non-qt case, it's not like it just does nothing.

So I guess @DragaDoncila if you can make the qt import try/ catch instead in "progress" instead of in viewermodel that would be better. Though I do wonder now if that progress should still live in `_qt` or if it should live somewhere else. I'd really prefer to avoid opening viewermodel.py and seeing an import from `_qt` right at the top. I do think there's a design flaw here. Maybe @nclack wants to take a look and could weigh in with a suggestion. It's also fine if we get something in shorter term and then improve longer term

**Comment by DragaDoncila** [comment]
This PR is waiting on #3379  - after we merge that I will update this accordingly.

**Comment by DragaDoncila** [comment]
@sofroniewn I've updated this after merging #3379 if you want to take another look.

**Review by sofroniewn — APPROVED** [review]
LGTM! Thanks for updates

**Pull request merged**
