### PR TITLE
Return full colormap dict in get_state

### PR DESCRIPTION
**Pull request by brisvag**
# Description
When working with custom colormaps, reader and writers trying to use that colormap will fail because the only information returned by `Layer.get_state` is the colormap name. This works fine with builtin colormaps, but anything custom will fail due to `[unnamed colormap 0]` not existing.

By returning the full colormap model (in dict form) we can also account for this.

Plugin writers and readers using `colormap` will likely break (like our napari-svg) because they assume it to be a string.

Note that this includes #5805. which is a lot smaller and just a bug fix.

# References

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Czaki** [comment]
But what happen when we add layer using this and built-in colormap? Did it properly select the existing one or create `[unnamed colormap 0]`?

**Comment by brisvag** [comment]
Not sure what you mean; colormaps are checked by name first, so if a colormap is called `viridis` it should simply return the builtin viridis, no matter the actual contents of the provided colormap.

**Review by Czaki — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
Looks like the constraints files also need to be updated for the new napari-svg, in order for tests to pass.

**Comment by brisvag** [comment]
@Czaki how do I update the constraints when bumping a dependency? should I just go through it myself manually or run a script?

**Comment by Czaki** [comment]
to Wait until monday or go to Actions, select Upgrade test constraints action and trigger action (I have done it for now) 
obraz


Then need to fix bugs eventually and merge to main.

**Review by Carreau — APPROVED** [review]

**Comment by andy-sweet** [comment]
The only usage of the colormap state I found is in napari-bbox: https://github.com/bauerdavid/napari-bbox/blob/ad6483c1298c4097d6beddf084cb98eabfe9283c/src/napari_bbox/boundingbox/bounding_boxes.py#L1934

The fix should be easy enough there, so I think this breaking change is OK.

**Comment by brisvag** [comment]
Ok, thanks @andy-sweet for digging through github! Will merge then :) @bauerdavid: if you need help with updating your code in `napari-bbox` for this change, feel free to ask!

**Comment by bauerdavid** [comment]
@brisvag thanks for the notification! I'll try to do it as soon as I get there.

**Pull request merged**
