### PR TITLE
Remove deprecation of sceenshot in qt_viewer

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Because QtViewer is still part of public API, then screenshot functions should not be deprecated. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
Thanks @Czaki, as discussed on zulip, I'm ok with this.  It would be nice if we could figure out a way to discourage napari users from using `viewer.window.qt_viewer.screenshot`.  Can you think of a way?  Perhaps, check if `QtViewer` has a parent that is an instance of a napari Window?

**Comment by Czaki** [comment]
But qt_vierer is already deprecated? 
https://github.com/napari/napari/blob/7323d8af95ddff3581aa2ecad4104a383616d36f/napari/_qt/qt_main_window.py#L551-L561 so why the additional warning is needed?

**Comment by tlambert03** [comment]
ah good point!  ok ok, i think we're fine here then.  @sofroniewn?

**Review by tlambert03 — APPROVED** [review]

**Review by sofroniewn — APPROVED** [review]
> ah good point! ok ok, i think we're fine here then. @sofroniewn?

Yup, i had the same concerns as @tlambert03 - but i think this is fine, we can live with for now

**Pull request merged**
