### PR TITLE
Add tooltip implementation for points

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR add tooltip and status information for Points Layer. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by jni — APPROVED** [review]
I'm happy to get this in. Hopefully the code paths can get merged between all properties-compatible layers soon, but in the meantime this adds useful functionality and I don't think it significantly detracts from the unifying properties work. Thank you @Czaki!

**Comment by Czaki** [comment]
> Hopefully the code paths can get merged between all properties-compatible layers soon

I agree. Waiting for unification of properties is one of reasons why I do not touch it earlier.

**Comment by brisvag** [comment]
After a quick test using the `points_over_time` example, it seems that the tooltip only shows `value: ...` on a few points, while most only have an `index`. Can you reproduce?

**Comment by Czaki** [comment]
> After a quick test using the `points_over_time` example, it seems that the tooltip only shows `value: ...` on a few points, while most only have an `index`. Can you reproduce?

I could, and it is cause by function `get_value` which return none for this because `view_direction` and `dims_displayed` are not passed.

Could you check now?

**Review by brisvag — APPROVED** [review]
It's fixed! LGTM :)

**Pull request merged**
