### PR TITLE
Adds calendar to docs 

### PR DESCRIPTION
**Pull request by codemonkey800**
# Description

- Adds the napari calendar using the `napari-calendar` directive
- Updates the navbar title to be aligned with the napari theme
- As a result of merging this PR, we'll also get the included fixes in https://github.com/napari/napari-sphinx-theme/pull/77
  - This also fixes the issue with the search bar overlapping with the navbar

image

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- Tested locally using `make docs`

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by codemonkey800** [comment]
FYI This depends on the `GOOGLE_CALENDAR_ID` and `GOOGLE_CALENDAR_API_KEY` secrets to be set in the repo, which @jni helped with adding to the repo already 😄

**Comment by jni** [comment]
Hmmm... Did I mess up adding the id and keys though @codemonkey800? The downloaded build displays the calendar widget for me but it's empty — no events...

**Comment by jni** [comment]
Or do I need them set *locally*? I find that weird...?

**Comment by codemonkey800** [comment]
> Or do I need them set _locally_? I find that weird...?

Yeah they need to be set up locally. It's implemented this way so that we're not embedding the secrets into the library, and so that if someone wants to use the calendar on their website, they can use a different calendar ID to show different events if they want

**Comment by jni** [comment]
@codemonkey800 I have no understanding though of how deployment works? ie how does the "serving" environment on gh-pages get the env vars?

**Comment by codemonkey800** [comment]
The secrets are passed over in the GitHub Action here:
https://github.com/napari/napari/blob/c1f65b1b12ddcec9addb759d4eb47543d503b492/.github/workflows/deploy_docs.yml#L41-L43

The secrets are then injected by the theme at build time (specifically after the build). This works by having the theme register a callback that injects the secrets from the environment into the JavaScript source code:
https://github.com/napari/napari-sphinx-theme/blob/8426695f53d60b6afeaad49d80b42c19ca58e2e2/src/napari_sphinx_theme/__init__.py#L513-L530

**Comment by jni** [comment]
Aaaaah! So we need to add those lines to the `build_docs` action as well, right? I will make a separate PR for that. Thanks!

**Review by jni — APPROVED** [review]

**Comment by codemonkey800** [comment]
awesome! calendar is looking good 😄 

https://napari.org/community/meeting_schedule.html

**Pull request merged**
