### PR TITLE
Allow ability to run all tests on local Windows installs

### LINKED ISSUE #1455: Ability to run all tests on local Windows installs
## 🚀 Feature

In #1372, we started to use the 'CI' environment variable to run our windowed tests on CI only. We can run them locally by setting CI=1 *except* when running locally in a Windows box, in which case, you have absolutely no way to run those tests.

Here's the marker we use:

```python
@pytest.mark.skipif(
     sys.platform.startswith('win') or not os.getenv("CI"),
     reason='Screenshot tests are not supported on napari windows CI.',
 )
```

Reading the reason description, I expect the condition to read `sys.platform.startswith('win') and os.getenv('CI')`. I think the point is that we are making the CI variable do double duty, and we should add our own variable:

```python
@pytest.mark.skipif(
     sys.platform.startswith('win') and os.getenv("CI"),
     reason='Screenshot tests are not supported on napari windows CI.',
 )
@pytest.mark.skipif(
    not os.getenv('NAPARI_POPUP_TESTS'),
    reason='Tests requiring pop-up napari windows are skipped by default.',
)
```

Thoughts @sofroniewn @tlambert03?

### PR DESCRIPTION
**Pull request by UmbWill**
Fixes #1455

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jni** [comment]
@UmbWill and I tested this manually at the SciPy Japan sprints, and it works! 🎉

**Review by jni — APPROVED** [review]
This is awesome, thank you @UmbWill!

**Comment by jni** [comment]
Just checked and the tests are also running in CI as expected, see e.g. https://cirrus-ci.com/task/6130607342223360?command=test_pyside2_with_coverage#L262 🎉

**Comment by jni** [comment]
Hmmm looks like there is a problem on Windows CI now... Maybe chaining skipifs is not as straightforward as I thought... Will investigate.

**Comment by jni** [comment]
Ok so I don't actually understand why it's failing. The use of `pytest.mark.skipif` is correct. I changed the platform to 'linux' and pretended to be in CI, and things were totally fine:

```python
 $ CI=1 pytest -rs napari/_vispy/_tests/test_vispy_multiscale.py
==================================== test session starts ====================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
PyQt5 5.12.3 -- Qt runtime 5.12.9 -- Qt compiled 5.12.9
rootdir: /home/jni/projects/napari, configfile: pyproject.toml
plugins: napari-plugin-engine-0.1.8, timeout-1.4.2, ordering-0.6, qt-3.3.0
collected 6 items                                                                           

napari/_vispy/_tests/test_vispy_multiscale.py ..ssss                                  [100%]

================================== short test summary info ==================================
SKIPPED [1] napari/_vispy/_tests/test_vispy_multiscale.py:63: Screenshot tests are not supported on napari windows CI.
SKIPPED [1] napari/_vispy/_tests/test_vispy_multiscale.py:97: Screenshot tests are not supported on napari windows CI.
SKIPPED [1] napari/_vispy/_tests/test_vispy_multiscale.py:138: Screenshot tests are not supported on napari windows CI.
SKIPPED [1] napari/_vispy/_tests/test_vispy_multiscale.py:175: Screenshot tests are not supported on napari windows CI.
=============================== 2 passed, 4 skipped in 0.99s ================================
```

If anyone from @napari/core-devs has any ideas, they would be much appreciated!!!

**Comment by tlambert03** [comment]
i know it's weird... but try using a string as the `skipif` condition (it will be `eval`ed).  Also, in order to reduce all the duplication, you can create a custom decorator like this:

```python
skip_on_win_ci = pytest.mark.skipif(
    "sys.platform.startswith('win') and os.getenv('CI')",
    reason='Screenshot tests are not supported on windows CI.',
)

skip_local_popups = pytest.mark.skipif(
    "not os.getenv('CI') and not os.getenv('NAPARI_POPUP_TESTS')",
    reason='Tests requiring GUI windows are skipped locally by default.',
)

@skip_on_win_ci
@skip_local_popups
def test_z_order_adding_removing_images(make_test_viewer):
    ...
```

**Comment by jni** [comment]
Thanks @tlambert03! I saw the string eval option in the docs but it was marked as deprecated. Still, worth a try, might help us narrow down the issue... 🤷

**Comment by UmbWill** [comment]
According with the os.getenv documentation:
Return Type: This method returns a string that denotes the value of the environment variable key. In case key does not exists it returns the value of default parameter.

Every time, the statement has been skipped. 
I changed the code as Lambert-san said, and added os.getenv('NAPARI_POPUP_TESTS')=='1'

**Comment by jni** [comment]
@UmbWill awesome, so good that this is passing now! 🎉

**Pull request merged**
