### PR TITLE
Handles empty chosen files and folder

### LINKED ISSUE #706: Clicking File > Open Folder then cancelling causes a crash
## 🐛 Bug

If I click on File > Open Folder but then hit cancel (in this case, because I actually wanted to open a file, not a folder), I get the following traceback:

```pytb
WARNING: Traceback (most recent call last):
  File "/home/jni/projects/napari/napari/_qt/qt_viewer.py", line 233, in _open_folder
    self._add_files([folder])
  File "/home/jni/projects/napari/napari/_qt/qt_viewer.py", line 247, in _add_files
    self.viewer.add_image(path=filenames)
  File "/home/jni/projects/napari/napari/components/viewer_model.py", line 485, in add_image
    data = io.magic_imread(path)
  File "/home/jni/projects/napari/napari/util/io.py", line 71, in magic_imread
    image = io.imread(filename)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file " "in mode %r" % mode
ValueError: Could not find a format to read the specified file in mode 'i'
WARNING:vispy:Traceback (most recent call last):
  File "/home/jni/projects/napari/napari/_qt/qt_viewer.py", line 233, in _open_folder
    self._add_files([folder])
  File "/home/jni/projects/napari/napari/_qt/qt_viewer.py", line 247, in _add_files
    self.viewer.add_image(path=filenames)
  File "/home/jni/projects/napari/napari/components/viewer_model.py", line 485, in add_image
    data = io.magic_imread(path)
  File "/home/jni/projects/napari/napari/util/io.py", line 71, in magic_imread
    image = io.imread(filename)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file " "in mode %r" % mode
ValueError: Could not find a format to read the specified file in mode 'i'
Aborted (core dumped)
```

We probably need to add a check for when the return value is None.

### PR DESCRIPTION
**Pull request by HagaiHargil**
# Description
Fixes #706.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?
No tests were added since there aren't any currently, and I'm not sure how to would opening a file dialog fair in CI\CD pipelines.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by HagaiHargil** [comment]
I see that `test_play_api` fails quite irregularly.

**Comment by tlambert03** [comment]
> I see that `test_play_api` fails quite irregularly.

still? 😠 point me to a failing test log and I'll relax it according

**Comment by tlambert03** [comment]
oh weird: github is showing a successful test for osx py3.7 on b072f7e but cirrus [is not](https://cirrus-ci.com/task/6559196484468736).  I'll submit a separate PR.

**Review by sofroniewn — APPROVED** [review]
Nice fix, this looks good to me! I'll wait to see if @jni wants to weigh in, otherwise I will merge promptly!

**Comment by jni** [comment]
Thanks @HagaiHargil!

**Pull request merged**
