### PR TITLE
Ensure consistent layer tooltip

### LINKED ISSUE #6435: Tooltip of elided long layer names doesn't give full name when coming from a plugin
### 🐛 Bug Report

When having layers with long names, the names are elided, which is good...
Normally when mousing over them, the full name is provided in the tool tip.
This works for example for a sample image -- e.g. astronaut renamed something really long.
**But**, when using a plugin to open, after mousing over them, the full layer name is not provided, instead info about the filename and plugin is provided -- useful, but not exactly the most helpful when layers have long names that start the same. Especially since this is also provided when mousing the canvas. E.g.:
image

The only way to see the full name is to expand the layer list, which is annoying.

### 💡 Steps to Reproduce

1. open an image file with a plugin -- can be any file, e.g. a jpg or png using `builtins`
2. make the name of the layer really long, enough to elide, e.g. add `qwertyuiopasdfghjklzxcvbnmqwertyuiop`
3. mouse over the layer name

### 💡 Expected Behavior

Disambiguating long-named layers is really important. Knowing the file name of origin and plugin is nice.
Seeing the full text of an elided label should be preserved when a plugin is used.
Ideally, when using a plugin the tooltip would *gain* the file name and plugin name as a 2nd line, with the full layer name being still provided.

### 🌎 Environment

napari: 0.4.18
Platform: macOS-13.6.2-arm64-arm-64bit
System: MacOS 13.6.2
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.25.2
SciPy: 1.11.1
Dask: 2023.8.0
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.2

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2056x1329, scale 2.0
  - screen 2: resolution 1920x1200, scale 1.0

Settings path:
  - /Users/sobolp/Library/Application Support/napari/napari-418_d279d6cf5d4193876ed97858e757fe322037331b/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-aicsimageio: 0.7.2 (2 contributions)
  - napari-animation: 0.0.7 (2 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  - napari-workshop-browser: 0.0.3 (2 contributions)
  - ome-types: 0.4.1 (2 contributions)

### 💡 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# References and relevant issues
Closes https://github.com/napari/napari/issues/6435

# Description
In this PR I ensure that when mousing over a layer in the layer list the tooltips are consistent.
The layer name is always shown, which covers the case of long names which might be elided in the list (the linked issue). If there is a file name and the other info, it's also shown. Here's an example of a long layer name (but all layer names are shown):
image

Also, I add a small amount of logic to format the tooltip better, so that when something is missing the spurious punctuation seen on live, e.g. with empty Points, is eliminated.
Live
image
this PR:
image

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Question 1:
this issue: https://github.com/napari/napari/issues/1251
here could make the tooltip show the whole path rather than just the filename.
Personally, I'm fine with just the filename, but it's an option.

Question 2:
The status bar shows the `layer_base`  which is the filename (when available) when mousing the canvas. Frankly, I think this should show the layer name, which this PR makes possible.
One can have multiple layers from the same file after all!

**Comment by brisvag** [comment]
> here could make the tooltip show the whole path rather than just the filename.

I think this could go wrong. Maybe we should have an "info" or "properties" dropdown that opens a dialog with full info and/or metadata of the layer. For abnother PR though :P

> Frankly, I think this should show the layer name, 

Uhm, I think they're both important... but maybe the name is the more immedately useful information, and you need more you can check the layer tooltip. So I agree with you, unless putting both is an option despite the real estate.

**Comment by psobolewskiPhD** [comment]
> > here could make the tooltip show the whole path rather than just the filename.
> 
> I think this could go wrong. Maybe we should have an "info" or "properties" dropdown that opens a dialog with full info and/or metadata of the layer. For abnother PR though :P

Yes, a `get info` or `Get properties` widget for layers would be very nice to have. Most image/video software has something like that. It would summarize the basic layer properties, including source, scale, shape, etc. and metadata. I think this is somewhat similar to @andy-sweet metadata plugin?

> > Frankly, I think this should show the layer name,
> 
> Uhm, I think they're both important... but maybe the name is the more immedately useful information, and you need more you can check the layer tooltip. So I agree with you, unless putting both is an option despite the real estate.

I think both would be rough, especially for layers that display more then just a coordinate...
Anyhow my mental model is that layer list shows the layers and would have the higher level info of the file name. The canvas shows the layer data, so mousing over the canvas should give the layer associated. Layer names have to be unique--I think--while file names need not, and multiple layers can come from the same file.
I think changing the status bar willl/would be a followup PR--should be trivial now--to make decision making easier.

**Comment by brisvag** [comment]
> I think this is somewhat similar to @andy-sweet metadata plugin?

I think it's a lot easier to do than that plugin; at least to start with we can just print out, not allow modification. It should also be a modal dialog I think, so it doesn't stick around nor clutter up the widgets.

> Layer names have to be unique--I think--while file names need not, and multiple layers can come from the same file.

yup, I agree!

**Review by melonora — APPROVED** [review]
This looks fine to me. Windows CI is failing, but that is a known issue I believe not related to this PR.

**Comment by Czaki** [comment]
Is this ready to merge?

**Comment by psobolewskiPhD** [comment]
I don't have anything to add...
I think a similar homogenization of info for the status bar would be a followup.

**Pull request merged**
