### PR TITLE
[WIP] Remove vendored mesh

### PR DESCRIPTION
**Pull request by alisterburt**
# Description
This PR removes our vendored vispy `MeshVisual` code. This change requires only one tiny modification to the call order in `VispySurfaceLayer._on_data_change()` and an update of the minimum vispy requirement to `0.7.0`. They're at `0.9.0` now.

This allows us to more easily leverage new vispy mesh features required for #2970 

@brisvag I left the clipping planes mixin, vendored in napari do you know what version of vispy this is present from?

## Type of change
refactor/simplification

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality

### CODE REVIEW

**Comment by alisterburt** [comment]
everything is working locally, not sure why all tests are failing. will look into it - don't review yet!

**Comment by brisvag** [comment]
I suggest we hold off with this until vispy/vispy#2227 is merged and released (hopefully in a patch release soon). The PR is passing and approved, so it will probably be merged soon. 

This would allow us to get rid of most (possibly all) of our vendored code in one fell swoop. I already have [a branch with these changes](https://github.com/brisvag/napari/tree/bump-vispy), ready to open a PR as soon as vispy is updated (albeit still with a couple of issues to discuss).

Having said this, I'm not opposed to removing some parts already, where possible. The clipping plane mixin is a napari-only thing, so it should not go! (vispy has the filter, but does not attach it by default to the visual).

**Comment by alisterburt** [comment]
thanks for taking a look! happy to wait but definitely need to be careful updating in one fell swoop - unvendoring the mesh shader here has meant that the `ShadingFilter` can only be attached/changed once before getting stuck, round-trip behaviour like this is not well tested :/

edit: so tests are now passing (except macos 3.8 where failures seem unrelated) but I need to fix this round trip error and add a test so let's hold off on merging

**Comment by alisterburt** [comment]
The shading filter itself in vispy has changed so something about the way we were previously attaching/detaching the shading filter was causing issues. Removing that logic means that the nD surface example runs fine, can be switched between 2D/3D and switched between the shading modes. Switching between 2D/3D with larger meshes now breaks with
<details open>
<summary>traceback</summary>
<br>

```python
WARNING: Error drawing visual <SurfaceVisual at 0x7fde4acf5fa0>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py in paintGL(self=<vispy.app.backends._qt.CanvasBackendDesktop object>)
    895         # (0, 0, self.width(), self.height()))
    896         self._vispy_canvas.set_current()
--> 897         self._vispy_canvas.events.draw(region=None)
        self._vispy_canvas.events.draw = <vispy.util.event.EventEmitter object at 0x7fde4ad39460>
        global region = undefined
    898 
    899         # Clear the alpha channel with QOpenGLWidget (Qt >= 5.4), otherwise the

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/util/event.py in __call__(self=<vispy.util.event.EventEmitter object>, *args=(), **kwargs={'region': None})
    451                     raise RuntimeError('EventEmitter loop detected!')
    452 
--> 453                 self._invoke_callback(cb, event)
        self._invoke_callback = <bound method EventEmitter._invoke_callback of <vispy.util.event.EventEmitter object at 0x7fde4ad39460>>
        cb = <bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5) at 0x7fde4ad178e0>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    454                 if event.blocked:
    455                     break

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/util/event.py in _invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5)>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    469             cb(event)
    470         except Exception:
--> 471             _handle_exception(self.ignore_callback_errors,
        global _handle_exception = <function _handle_exception at 0x7fde5844cd30>
        self.ignore_callback_errors = False
        self.print_callback_errors = 'reminders'
        self = <vispy.util.event.EventEmitter object at 0x7fde4ad39460>
        global cb_event = undefined
        cb = <bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5) at 0x7fde4ad178e0>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    472                               self.print_callback_errors,
    473                               self, cb_event=(cb, event))

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/util/event.py in _invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5)>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    467     def _invoke_callback(self, cb, event):
    468         try:
--> 469             cb(event)
        cb = <bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5) at 0x7fde4ad178e0>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    470         except Exception:
    471             _handle_exception(self.ignore_callback_errors,

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/scene/canvas.py in on_draw(self=<VispyCanvas (PyQt5)>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    216         # scheduling of further updates
    217         self._update_pending = False
--> 218         self._draw_scene()
        self._draw_scene = <bound method SceneCanvas._draw_scene of <VispyCanvas (PyQt5) at 0x7fde4ad178e0>>
    219 
    220     def render(self, region=None, size=None, bgcolor=None, crop=None, alpha=True):

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/scene/canvas.py in _draw_scene(self=<VispyCanvas (PyQt5)>, bgcolor=<class 'numpy.ndarray'> (4,) float32)
    275             bgcolor = self._bgcolor
    276         self.context.clear(color=bgcolor, depth=True)
--> 277         self.draw_visual(self.scene)
        self.draw_visual = <bound method SceneCanvas.draw_visual of <VispyCanvas (PyQt5) at 0x7fde4ad178e0>>
        self.scene = <SubScene at 0x7fde4ad39370>
    278 
    279     def draw_visual(self, visual, event=None):

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/scene/canvas.py in draw_visual(self=<VispyCanvas (PyQt5)>, visual=<SubScene>, event=None)
    313                         else:
    314                             if hasattr(node, 'draw'):
--> 315                                 node.draw()
        node.draw = <bound method VisualNode.draw of <SurfaceVisual at 0x7fde4acf5fa0>>
    316                                 prof.mark(str(node))
    317                 else:

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/scene/visuals.py in draw(self=<SurfaceVisual>)
     97         if self.picking and not self.interactive:
     98             return
---> 99         self._visual_superclass.draw(self)
        self._visual_superclass.draw = <function Visual.draw at 0x7fde4a330700>
        self = <SurfaceVisual at 0x7fde4acf5fa0>
    100 
    101 

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/visuals/visual.py in draw(self=<SurfaceVisual>)
    449         self._configure_gl_state()
    450         try:
--> 451             self._program.draw(self._vshare.draw_mode,
        self._program.draw = <bound method ModularProgram.draw of <vispy.visuals.shaders.program.ModularProgram object at 0x7fde4d460b80>>
        self._vshare.draw_mode = 'triangles'
        self._vshare.index_buffer = None
    452                                self._vshare.index_buffer)
    453         except Exception:

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/visuals/shaders/program.py in draw(self=<vispy.visuals.shaders.program.ModularProgram object>, *args=('triangles', None), **kwargs={})
    100         self.build_if_needed()
    101         self.update_variables()
--> 102         Program.draw(self, *args, **kwargs)
        global Program.draw = <function Program.draw at 0x7fde49d064c0>
        self = <vispy.visuals.shaders.program.ModularProgram object at 0x7fde4d460b80>
        args = ('triangles', None)
        kwargs = {}
    103 
    104     def build_if_needed(self):

/opt/homebrew/Caskroom/miniforge/base/envs/napari/lib/python3.9/site-packages/vispy/gloo/program.py in draw(self=<vispy.visuals.shaders.program.ModularProgram object>, mode='triangles', indices=None, check_error=True)
    496         if not all(s == sizes[0] for s in sizes[1:]):
    497             msg = '\n'.join(['%s: %s' % (str(a), a.size) for a in attributes])
--> 498             raise RuntimeError('All attributes must have the same size, got:\n'
        global RuntimeError = undefined
        msg = '<VertexBuffer size=16908 last_dim=1>: 16908\n<VertexBuffer size=16980 last_dim=3>: 16980\n<VertexBuffer size=16908 last_dim=3>: 16908'
    499                                '%s' % msg)
    500 

RuntimeError: All attributes must have the same size, got:
<VertexBuffer size=16908 last_dim=1>: 16908
<VertexBuffer size=16980 last_dim=3>: 16980
<VertexBuffer size=16908 last_dim=3>: 16908
```

</details>

The shading filter has changed enough that flat/smooth now look pretty much identical for the nD_surface example - I've confirmed with the triceratops in #3477 that these options still provide meaningful differences for meshes with more than a few triangles.

I need to figure out what's wrong with the 2d/3d switching with a larger mesh and add a test for it

**Comment by kevinyamauchi** [comment]
Hey @alisterburt ! Did you want a review of this PR or is this the one you said I could ignore?

**Comment by alisterburt** [comment]
ignore for now please @kevinyamauchi - still haven't quite got this figured out :)

**Comment by alisterburt** [comment]
superseded by #3494

**Pull request closed without merging**
