### PR TITLE
Add support for negative labels

### PR DESCRIPTION
**Pull request by jni**
# Description

At the Eurasia community meeting, @tibuch requested support for negative values in the labels layer. This is useful when marking background, objects, and sentinel "not yet proofread" values. It is easy for us to support so in the absence of a good reason not to, I suggest here that we do! :blush:

The only caveat is that the indexing-based colour lookup is a bit wonky.  As a reminder, for performance reasons, whenever the largest label is not very large, we keep an array of "low discrepancy" values and we index into that array with the labels values (#2415, and subsequent PRs). In this case, this means that -1 indexes to the end of the array, so if you have more than 50 labels but fewer than n-pixels labels, the color of the -1 label will match the color of the max labels.

This situation is only temporary until we move colormapping to the shader (#3308), so I don't think we should worry about it.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

- [x] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by kevinyamauchi — COMMENTED** [review]
Thanks for the PR, @jni! I agree that we should try to support negative labels. I just took it for a spin and I get some weird behavior for the -1 label color. It seems to get updated as I scroll through z in a 3D label image being viewed in 2D.

https://user-images.githubusercontent.com/1120672/142464447-614a3ddd-639f-489b-99c8-3318d9b4d02a.mov

Note that I scroll through a section, the color remains stable until I scroll through new slices again. I am not too familiar with how the colormap is generated. Is the map made lazily?

```python

from skimage import data
from scipy import ndimage as ndi
import napari
import numpy as np


blobs = data.binary_blobs(length=128, volume_fraction=0.1, n_dim=3)
viewer = napari.view_image(blobs[::2].astype(float), name='blobs', scale=(2, 1, 1))
labeled = ndi.label(blobs)[0]

# make the space between the blobs -1
labeled[np.logical_not(blobs)] = -1

viewer.add_labels(labeled[::2], name='blob ID', scale=(2, 1, 1))

napari.run()
```

**Comment by Carreau** [comment]
Rebased to fix many of the failure.

**Comment by jni** [comment]
Thanks for the rebase @Carreau!

@kevinyamauchi yeah that's the caveat I alluded to in the description: the -1 label will share a colour with the highest-valued label encountered. I hadn't considered how terrible that is in the slicing case. :joy: 

@tibuch are you mostly working in 2D or 3D? And instance or class segmentation?

Here's our options:
1. ignore the problem since it will get fixed with #3308 
2. compute the min as well as the max when determining whether to use the indexing shortcut, and turn it off if the min is <0. This will come at a performance cost when there are negative labels *and* we hit the max label.
3. this just occurred to me and might be my favourite: make `_all_vals` the size of the highest encountered label **+1**, so that -1 hits a new value instead of the max value. We could extend this to +10 or whatever, *or*, perhaps even better, we could combine it with 2, compute the min and max, then compute an array large enough to contain all of them.

Actually 3 is pretty elegant and I might go for that. Depending on @tibuch's use cases and patience, this could be done as part of this PR or a new one.

**Comment by sofroniewn** [comment]
> ignore the problem since it will get fixed with [WIP] Use a shader for low discrepancy label conversion #3308

I worry this might be still some ways away, so am probably not inclined to go with this option

**Comment by kevinyamauchi** [comment]
> @kevinyamauchi yeah that's the caveat I alluded to in the description: the -1 label will share a colour with the highest-valued label encountered. I hadn't considered how terrible that is in the slicing case. 😂

Ah got it!

> Actually 3 is pretty elegant and I might go for that. Depending on @tibuch's use cases and patience, this could be done as part of this PR or a new one.

I am also in favor of solution 2+3. I agree with @sofroniewn that we shouldn't wait for #3308 since we have a reasonable path that is open now.

**Comment by jni** [comment]
@kevinyamauchi @sofroniewn Ok, I've implemented that option. I'll note that there is still one case where this doesn't work, shown in the test marked as xfail. It goes as follows:

- the first slice doesn't have a negative label, so the lookup table doesn't get one either.
- the second slice does have a new negative label, but no other new labels: this means that the -1 doesn't trigger an IndexError which is our cue to recompute the color lookup table. So, the -1 shares the color with the max label.
- the third slice now does contain -1 *and* a new label. This triggers a recomputation of the color lookup table, so both -1 and the new max label get a new color, which again causes the flickering that @kevinyamauchi saw.

Ultimately, I think this PR gets @tibuch unstuck and so it strictly improves the situation for him, even if there are quirks. We could in the meantime prioritise #3308 to remove the quirky behaviour, but I think quirky behaviour is better than impossible behaviour?

@tibuch any thoughts?

**Review by sofroniewn — APPROVED** [review]
LGTM! But maybe @kevinyamauchi and @tibuch can confirm they both like the behaviour before merge. Thanks!!

**Comment by Carreau** [comment]
merged master into this and all tests are passing. 
I'll merge that next time I came across it in 24h or more, unless someone else bets me to it.

**Comment by kevinyamauchi** [comment]
Hey! Sorry I missed this @sofroniewn . Thank you for merging!

**Comment by tibuch** [comment]
Thank you everyone! I am sorry for my silence, I was on vacation last week. I did not expect for things to move so fast :rocket: Thanks a lot!

**Pull request merged**
