### PR TITLE
Unblock axis labels event to be emitted when slider label changes

### LINKED ISSUE #5630: Changing the axis slider label does not emit the axis_labels event
## 🐛 Bug

Changing the axis slider label does not cause the `Dims.events.axis_labels` event to be emitted, though `Dims.axis_labels` are updated. This means anyone listening to changes to axis labels will be unaware of the change in this case.

## To Reproduce

Here's one of the existing tests in `test_qt_dims` with some updates to reproduce the issue:

```python
def test_update_dims_labels(qtbot):
    """
    Test that the slider_widget axis labels are updated with the dims model
    and vice versa.
    """
    ndim = 4
    view = QtDims(Dims(ndim=ndim))
    qtbot.addWidget(view)
    view.dims.axis_labels = list('TZYX')
    assert [w.axis_label.text() for w in view.slider_widgets] == list('TZYX')

    observed_axis_labels_event = False

    def on_axis_labels_changed():
        nonlocal observed_axis_labels_event
        observed_axis_labels_event = True

    view.dims.events.axis_labels.connect(on_axis_labels_changed)
    first_label = view.slider_widgets[0].axis_label
    assert first_label.text() == view.dims.axis_labels[0]
    first_label.setText('napari')
    assert first_label.text() == view.dims.axis_labels[0]
    assert observed_axis_labels_event
```

## Expected behavior

The `Dims.events.axis_labels` to be emitted when the axis slider label is changed.

## Environment

This is on main at commit 3ec4be1ae8eee50ab4912ba87981261cc94c075f

## Additional context

Found while working on a plugin (https://github.com/andy-sweet/napari-metadata/issues/25).

### PR DESCRIPTION
**Pull request by andy-sweet**
# Description
This removes an unnecessary blocker on the `Dims.events.axis_labels` event that is temporarily held when responding to a change to the text of the slider's `QLineEdit` label. I considered adding a `QSignalBlocker` for the widget's related signal to prevent infinite event/signal loops, but that's not necessary since the value/text won't change after the first pass.

I also removed the `QtDimSliderWidget.axis_label_changed` signal since it's not part of the napari public API and we can use `QtDimSliderWidget.axis_label.textChanged` instead.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# References
Closes #5630

# How has this been tested?
- [x] I modified an existing test to fail before the fix and which passes after the fix.
- [x] All other existing tests pass with my change.

I also manually tested changing the axis label by assigning `Dims.axis_labels` to a new value and by changing the slider label widget text. Both worked without causing any issues.

### CODE REVIEW

**Comment by andy-sweet** [comment]
@psobolewskiPhD : I picked you as a reviewer to help spread the review load a bit. Feel to unassign or pass this one on to someone else for any reason though.

**Review by jni — APPROVED** [review]

**Comment by andy-sweet** [comment]
Thanks for the review @jni!

@psobolewskiPhD : as a result, I took you off as a review, but feel to take a look if you want.

I'll merge this on Monday unless anyone objects.

**Review by psobolewskiPhD — APPROVED** [review]
Works as advertised.
Took me a bit, but I get it.
At first I was confused as to what was being emitted, but it's the QLineEdit event.

**Comment by andy-sweet** [comment]
Probably small and contained enough to be brought into 0.4.18, but feel free to drop if hard to cherry pick.

**Pull request merged**
