### PR TITLE
updates for magicgui 0.3.0

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
magicgui 0.3.0 has an improved register_type decorator. we can remove our internal one now. 

note: this would bump our magicgui requirement to 0.3.0... while I've tried hard to make that a backwards compatible change for everyone, it does introduce a deprecation in the event system that will cause people to see warnings.  Don't have a super strong opinion on whether we should bumpy this now, or later.  but, ya know, it's the future :joy:

### CODE REVIEW

**Comment by sofroniewn** [comment]
I can give this a try asap, but does "it does introduce a deprecation in the event system that will cause people to see warnings" happen pretty much everytime magicgui get's used, or is it only if something fairly specific is being done? Either way, probably ok to go ahead, but just wanted to get a rough estimate on frequency expected

**Comment by tlambert03** [comment]
Sorry, should have been more specific.  It will happen not with napari, but rather if they have a plugin that uses magicgui that also uses events that has not updated yet to type annotate their callbacks

**Review by sofroniewn — APPROVED** [review]
Nice. This looks good to me. Maybe some of the more heavy magicgui users say @haesleinhuepf can give this a test too, but I'm happy for it to go in whenever.

**Comment by tlambert03** [comment]
> Nice. This looks good to me. Maybe some of the more heavy magicgui users say @haesleinhuepf can give this a test too, but I'm happy for it to go in whenever.

There's nothing in this PR in particular that they need to test... 

i've submitted PRs to [cellpose](https://github.com/MouseLand/cellpose-napari/pull/13), [stardist](https://github.com/stardist/stardist-napari/pull/2) and [pyclesperanto-assistant](https://github.com/clEsperanto/napari_pyclesperanto_assistant/pull/34) with all of the changes they each need.  For anyone else stumbling on this, there's a migration guide at https://napari.org/magicgui/api/v0_3_0.html

**Comment by sofroniewn** [comment]
>  there's a migration guide at https://napari.org/magicgui/api/v0_3_0.html

Ah perfect! I hadn't seen that - thanks, sorry i've been a bit out of loop. Good to have that link here

> i've submitted PRs to cellpose, stardist and pyclesperanto-assistant with all of the changes they each need.

That's great! Looks like they were all ~ in the past 24 hours. They look pretty minor, but should we wait and see how the PRs go before merging this one, or do you just want to go ahead and merge now? I'll be fine either way

**Comment by tlambert03** [comment]
no hurries here...

**Review by jni — APPROVED** [review]
I'm happy with the bump. I think at some point the napari ecosystem will stabilise and we can start to support non-bleeding-edge things, but I think it makes sense to move quickly now so we can get to that point. Thanks @tlambert03!

**Pull request merged**
