### PR TITLE
Remove max brush size from increase brush size keybinding

### PR DESCRIPTION
**Pull request by alisterburt**
# Fixes/Closes

@RobAnKo added autorepeatable key bindings and set an upper bound on the brush size equal to the default max brush size in the GUI (40px)

Often we want to increase it to more than that, so this PR removes that upper bound

discussed in #5753 - I don't think we need an upper bound here

We could (should?) also set the range for brush size in the gui dynamically based on some heuristic involving image shape/zoom at layer creation time, at least when creating from the viewer when an image layer is selected

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Review by psobolewskiPhD — DISMISSED** [review]
Looks good, two small comments:
1. I can't click the number by the slider to increase it above whatever I manually `]` to achieve. Initially it's 40--you can't type a larger value. 
This is because the QSlider maximum is still set to 40 here:
https://github.com/napari/napari/blob/ede0563f8fae60331a0b03f34d688c8b80a2a783/napari/_qt/layer_controls/qt_labels_controls.py#L123
But here we let setting the size override maximum, so `]` works:
https://github.com/napari/napari/blob/ede0563f8fae60331a0b03f34d688c8b80a2a783/napari/_qt/layer_controls/qt_labels_controls.py#L439-L446
I think if we're dropping the upper bound, then the field should be free-fill with a desired size.

I think you need to change:
https://github.com/napari/napari/blob/ede0563f8fae60331a0b03f34d688c8b80a2a783/napari/_qt/layer_controls/qt_labels_controls.py#L367-L375
To something like:
```
        if value > self.brushSizeSlider.maximum():
            self.brushSizeSlider.setMaximum(int(value))
        self.layer.brush_size = value
```


and 2. is for a new PR:
would be nice to have some acceleration feature for `[` and `]`. the +1 -1 is awefully slow once you're you're in >100 range. Something like after some amount of holding it's +2, +3, etc?

**Comment by Czaki** [comment]
@alisterburt As it is marked for 0.4.18 cold you finish it, or I should do this?

**Comment by alisterburt** [comment]
I've taken a look at this - for the GUI to work I have to make some changes to `superqt` - will submit a PR there

**Comment by alisterburt** [comment]
but I don't know how long that process will take and don't want to hold up release

**Comment by alisterburt** [comment]
PR opened at superqt pyapp-kit/superqt#172

**Comment by Czaki** [comment]
I'm not sure if @tlambert03 will accept it fast. The minimum and maximum should not be updated so silently in Slider. 

But it is not a problem to create a subclass in napari to achieve the same result.

**Comment by alisterburt** [comment]
@Czaki let's see how it goes over there first, @tlambert03 is fast and seems ready to merge - I'd rather fix upstream properly for this :-)

**Review by jni — APPROVED** [review]
❤️

**Comment by jni** [comment]
Just to update myself on this PR: things work from the keyboard, but the slider then falls out of sync, but to fix that, we need to fix superqt — but will the superqt fix then instantly fix napari or do we need concerted changes? ie, should we merge this. 😂

**Comment by alisterburt** [comment]
@jni almost! The slider doesn't even fall out of sync if you use the keyboard, it's just not possible to achieve the keyboard behaviour (moving past the edge of the slider) with the mouse.

This is working fine it's just not perfect perfect, I vote merge this as is and follow up with slider changes in superqt - the change there is proving a little annoying and I don't know if I'll get it done

**Comment by jni** [comment]
@alisterburt Great, I will take advantage of the fact that @psobolewskiPhD is busy with a transconstinental move to sneakily merge this in 😂

**Pull request merged**
