### PR TITLE
Update best_practices.md

### PR DESCRIPTION
**Pull request by cwood1967**
The line:
Try not to depend on packages that require C compilation, but do not offer “wheels”

seems to say  don't depend on C compilation, but do offer wheels either.

# Description

Clarifies documentation

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — COMMENTED** [review]
This has more to do with the dependency than the plugin.  If a plugin offers wheels of its _own_ code, but the dependency has compiled code without a wheel, then it's still no good.  I think this wording suggests that providing a wheel for your plugin solves the problem... (which it doesn't).  Thoughts?

**Comment by DragaDoncila** [comment]
I can see how the current wording is unclear so we could say something like "Try not to depend on packages that require C compilation if these packages do not offer wheels"

**Comment by jni** [comment]
I like @DragaDoncila's wording. Does that sound good to you @cwood1967?

**Comment by cwood1967** [comment]
@jni Yes, the wording by @DragaDoncila better. I I updated the pull request.

**Review by tlambert03 — APPROVED** [review]

**Pull request merged**
