### PR TITLE
Add parent to layer delegate to be able to propagate theme to context menu

### LINKED ISSUE #3361: Layer list menu not using current theme
## To Reproduce

1. Open napari
2. Change theme (toggle theme)
3. Add any sample image and right click on the layer
4. The menu will show the old theme not the current one

## Expected behavior

The layer list menu should follow the current theme

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

Screen Shot 2021-09-08 at 4 20 09 PM

### PR DESCRIPTION
**Pull request by goanpeca**
# Description

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

Fixes https://github.com/napari/napari/issues/3361

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

napari

### CODE REVIEW

**Comment by tlambert03** [comment]
I actually specifically avoided that because the themed menus don't always look as good (for instance, hover behavior, etc...).  There's pretense for this too (vscode, and photoshop don't style their context menus even when a theme is active).   I need to play with it a bit to remind myself why I eventually opted to not provide the parent... but will comment later

**Comment by goanpeca** [comment]
Thanks @tlambert03 for the comments, I see. It felt odd to me, that menus looked like that.


---


Pinging @liaprins-czi and @isabela-pf for insight and ideas :)

**Comment by liaprins-czi** [comment]
Thanks for looping us in @goanpeca ,,, but I am not sure what is the exact issue? Can you explain a little? Is it to do with the light-theme's menu from within napari's left sidebar (not the MacOS-specific menubar menu) or somethng else? Thanks!

**Comment by goanpeca** [comment]
@liaprins-czi thanks

So should the context menu inside napari follow the global theme of the operating system, or should the use the current colors of the napari theme?

This might change from operating system guidelines, so what makes sense in OSX might not make sense on windows.

**Comment by sofroniewn** [comment]
I could go either way here, I'll defer to the consensus opinion

**Comment by isabela-pf** [comment]
I checked a few different apps I had around just to understand what popular practices are in theming context menus. Here's the lists.

Uses OS theming:
- Firefox
- Chrome
- Zoom
- Microsoft Office desktop apps
- Adobe creative suite apps

Uses app-based theming:
- Figma (desktop and web app)
- JupyterLab
- Spyder

Side note: JupyterLab and Figma's web app do preserve the OS themed context menus for browser context menus and use their own theming for their own context menus. They may be choosing this extra theming to help users catch the distinction between those two menus.

More apps seem to be using their own theming than I personally expected, probably because it does create a very cohesive experience. I still would recommend we use the global OS theming because
- It seems to be a common enough practice that I doubt it will confuse users.
- As far as I'm aware, OS themes have been much more tried and tested in terms of accessibility than anything we could quickly do. This will also reflect any configuration the users may have already made for accessibility reasons.
- I think it would be less maintenance for us long term.

**Comment by liaprins-czi** [comment]
Thanks for weighing in @isabela-pf ! I agree esp for a11y reasons, and the fact that we may have theme-specific plugins before long; it'd be great to be able to control at least this aspect of a11y within them.

**Comment by goanpeca** [comment]
Thanks for the input :)

Will close the PR then, would be great to start writing these guidelines somewhere so that we can reference it to napari devs, contributors and plugin developers :)

**Comment by psobolewskiPhD** [comment]
This is tangential, but I'd love a way to have Napari use my macOS theme.
It's *super awesome* that the napari theme can be easily checked, so I use:
```
if self.viewer.theme == "light":
            colormap = "gray_r"
        else:
            colormap = "gray"
```
But I have to manually change the theme each time. 
I've managed to get a bunch command line utilities and my R console (radian) to do it, by calling:
`defaults read -globalDomain AppleInterfaceStyle`
I've figured out I can use `os.system` and `os.popen` to get that value of the theme, so I can actually set the napari theme programatically, but it's kinda annoying since it will still open "wrong".

**Comment by goanpeca** [comment]
@psobolewskiPhD please open an issue :)  

---


Closing this one, thanks for all the comments!

**Comment by sofroniewn** [comment]
Thanks for weighing in @isabela-pf @liaprins-czi was very helpful to read about this all more - I ❤️ how this was handled 🚀

**Pull request closed without merging**
