### PR TITLE
improve stack trace of autogenerated `ViewerModel.add_xxxx` methods

### PR DESCRIPTION
**Pull request by Czaki**
# References and relevant issues

The problem is visible in stacktrace from here https://github.com/napari/napari/issues/6789#issue-2214508767

# Description

Instead of using a string template and passing source file name, create template file and pass the path to it to compile function.

On main:

```python
Traceback (most recent call last):
  File "/home/czaki/Projekty/napari/examples/add_points.py", line 22, in <module>
    viewer.add_points(points, size=size)
  File "/home/czaki/Projekty/napari/napari/components/viewer_model.py", line 7, in add_points
    from collections.abc import Iterator, Sequence
                ^^^^^^^^^^^^^^^^
  File "/home/czaki/Projekty/napari/napari/layers/base/base.py", line 112, in __call__
    raise ValueError("sample exception")
ValueError: sample exception
``` 

with this PR:

```python
Traceback (most recent call last):
  File "/home/czaki/Projekty/napari/examples/add_points.py", line 22, in <module>
    viewer.add_points(points, size=size)
  File "/home/czaki/Projekty/napari/napari/utils/add_layer.py_tmpl", line 7, in add_points
    layer = {cls_name}(**kwargs)
            ^^^^^^^^^^^^^^^^
  File "/home/czaki/Projekty/napari/napari/layers/base/base.py", line 112, in __call__
    raise ValueError("sample exception")
ValueError: sample exception
```

You can see that before this change, `from collections.abc import Iterator, Sequence` points to an incorrect line of code regarding the source of the error.

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
Not sure I love this, but I see the benefit.

**Comment by Czaki** [comment]
@brisvag could you check now?

**Review by jni — APPROVED** [review]
I love this! 🙏 I'm happy with the code comment.

I often wonder if long-term we could compile and write-out actual Python files at import-time, but in the meantime I think this is a very significant improvement — pointing to weird-but-correct code is much better than pointing to a totally incorrect line of code.

**Comment by Czaki** [comment]
> if long-term we could compile and write-out actual Python files at import-time

It may be a problem if napari is installed in read only location. It should be generated during wheel build.

**Pull request merged**
