### PR TITLE
MAINT: Split test file in two to find hanging test.

### PR DESCRIPTION
**Pull request by Carreau**
It looks like some tests in test_qt_dims do hang sometime in CI. Though it's not clear which one with Pytest output.

This split the test into two file approximatively where the hang happens, so we can narrow down the problem.

This may help with #5443 maybe ?

### CODE REVIEW

**Comment by Czaki** [comment]
@Carreau What did we should do here? It is ready for merge, or you would like to rerun it a few times to try to trigger the problem?

**Comment by Carreau** [comment]
I've rebased. Even if it does not fail at least that should give us a hint if it's actually here in later PRs.

**Comment by Czaki** [comment]
The longer I think about this, it looks like merge this in the main could be a good idea, but it requires to put docstring that will describe when the file was split.

**Comment by Carreau** [comment]
How about this ?

**Review by Czaki — APPROVED** [review]

**Pull request merged**
