### PR TITLE
Fix resize window problem by to long text in help 

### LINKED ISSUE #4980: Adding empty layers (shapes, labels) changes viewer size (caused in #
## 🐛 Bug

#4814 (according to git bisect) added a somewhat nasty UI bug wherein adding an empty shapes layer makes the window very wide.

https://user-images.githubusercontent.com/1609449/186669399-21a80104-9aee-4e78-bf5a-a65870243eb1.mov

haven't looked at the code to see why, but pinging @Czaki

### PR DESCRIPTION
**Pull request by Czaki**
# Description

Use `QElidingLabel` instead `QLabel` for help text on status bar

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

close #4980

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by tlambert03** [comment]
thanks @Czaki 

this is definitely better ... but there's still a graphical glitch when mousing over the canvas:


https://user-images.githubusercontent.com/1609449/186692209-e165b393-bfce-4baa-90b9-330a8c7451b3.mov

I know this would be a bummer, but I think we should consider removing the `layer.events.mode.connect(self._on_layer_mode_change)` line from #4814.    I know there's way too much "undiscoverable functionality, and the goal there was to fix some of that... but I fear we simply don't have a solid enough GUI styles framework for it.  I think visual glitches are worse in the sense that _everyone_ notices them, but only a small number of people notice the lack of a discoverable function.

That said, maybe it just requires a bit more tweaking here

**Comment by tlambert03** [comment]
yeah, played with it a bit more.  basically, I don't think we can mark #4980 as "fixed" until moving the mouse on the viewer doesn't ever mysteriously change the window size.  Even if that was just a happy coincidence before #4814 ...

**Comment by Czaki** [comment]
Yes. It looks like QElitedLabel does not play nice with `QStatusBar`.

**Comment by Czaki** [comment]
@tlambert03 it looks working now, could you check again?

**Review by tlambert03 — APPROVED** [review]
yep! works great. thanks!

**Pull request merged**
