### PR TITLE
update readme for alpha release

### PR DESCRIPTION
**Pull request by sofroniewn**
# Description
This PR updates the readme for the alpha release and should be merged when we make that release, after merging #400 and #401

### CODE REVIEW

**Review by kne42 — APPROVED** [review]

**Comment by jni** [comment]
@sofroniewn side note: you've made tons of awesome gifs of napari, but none are in the README. Would be great to have a gif of a 3D or 4D volume in the readme!

**Comment by kne42** [comment]
since we're switching from `pre-alpha` to `alpha`, do you want to also change https://github.com/napari/napari/blob/master/setup.py#L15
?

**Comment by sofroniewn** [comment]
@kne42 updated, thanks

**Comment by sofroniewn** [comment]
@jni I will try and add gifs to the readme

**Comment by sofroniewn** [comment]
i've updated the readme with a gif - @kne42 can you check over and then merge and make the `0.1` release!!!

**Pull request merged**
