### PR TITLE
Fix access denied windows fail of test on github actions

### PR DESCRIPTION
**Pull request by Czaki**
# Description

This PR fix failing test on windows with limit `GabrielBB/xvfb-action` usage to linux. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by nclack — APPROVED** [review]
Thanks. This looks good to me. 

I looked at the upstream action and all it does for non-linux targets is forward the commands through github's `actions.exec` (see [here](https://github.com/GabrielBB/xvfb-action/blob/36f535812f1bd7e367d9fc8be6eb55502c47db26/index.js#L48)). I don't understand what changed for the windows runners but thanks to this change I don't need to!

**Comment by tlambert03** [comment]
issue here https://github.com/GabrielBB/xvfb-action/issues/25

**Comment by Czaki** [comment]
> `actions.exec`

maybe this call is somehow buggy on windows?

**Comment by tlambert03** [comment]
to be honest, I'd kind of like to figure this one out upstream.  we use that action _everywhere_, it's in the cookiecutter, superqt, magicgui, etc... I really like using it and I don't want to have to add another `if runner.os` step to all of our pipelines, just to (hopefully) remove them.  There really isn't a lot of code in that action, so we could fork it and use it, and try to fix it

**Comment by Czaki** [comment]
This what I see is that `Current runner version:` was changed from `'2.286.1'` to `'2.287.1'`.
But also this action contains, in `node_modules`, frozen version of `actions/core` and `actions/exec` from two years ago. And for example core has a release 4 months ago:  https://www.npmjs.com/package/@actions/core 

So maybe just updating of actions versions to the latest one may be a solution. It is late here, so feel free to try.

**Comment by tlambert03** [comment]
thanks!

**Pull request closed without merging**
