### PR TITLE
Update packaging files, remove setup.py and requirements.txt

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
This PR continues the slow march towards PEP 517 packaging.  It removes setup.py, requirements.txt, and mypy.ini from the root level.  This stuff can always be a bit confusing, so here's some background:

- `setup.py` - this file is no longer necessary
     - even after we had setup.cfg, it was necessary for a while as a shim to support `pip install -e` editable installs, but as of version 21.3, pip now supports this (https://github.com/pypa/pip/issues/8212)
     - all of the setuptools metadata is supplied by setup.cfg, and we have no compile-time execution (like cython stuff)
     - directly invoking `setup.py` (via, e.g., `python setup.py sdist bdist_wheel`) is actually deprecated and discouraged, so getting rid of it helps remove that tendency.  Excellent post about [that here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) 
 
here are the replacements for things that setup.py used to do
setup.py command | New command
-- | --
setup.py sdist bdist_wheel | python -m build (with [build](https://pypi.org/project/build/))
setup.py test | pytest (or via tox/nox)
setup.py install | pip install
setup.py develop | pip install -e
setup.py upload | twine upload (with [twine](https://pypi.org/project/twine/))
setup.py check | twine check (this doesn't do all the same checks but it's a start)

- `requirements.txt` isn't really appropriate for a package.  It was used as something of a "lock file" earlier on, and might make sense for people trying to set up repeatable analysis environments, but packages should use `install_requires`.  ( more [background](https://caremad.io/posts/2013/07/setup-vs-requirement/))
- `mypy.ini` can go into `pyproject.toml`

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
LGTM! Thanks

**Comment by alisterburt** [comment]
LGTM too!

**Review by alisterburt — APPROVED** [review]

**Comment by Czaki** [comment]
> * `requirements.txt` isn't really appropriate for a package.  It was used as something of a "lock file" earlier on, and might make sense for people trying to set up repeatable analysis environments, but packages should use `install_requires`.  ( more [background](https://caremad.io/posts/2013/07/setup-vs-requirement/))

I would love if napari has requirements lock file with information on which packages it works (pip-compile output) for each release.

**Comment by alisterburt** [comment]
@Czaki could you make an issue to track? thanks!

**Pull request merged**
