### PR TITLE
Benchmark PR reporting fix

### PR DESCRIPTION
**Pull request by kcpevey**
# Description

Reporting the results of the benchmark back to a PR on which it was run has been broken. This should fix it. m

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

# How has this been tested?

- [x] implementation on private repo works

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by andy-sweet** [comment]
I triggered a benchmark run to test this out. Feel free to cancel if there's a reason this is not expected to run successfully.

**Comment by kcpevey** [comment]
>I triggered a benchmark run to test this out

Thanks. I meant to do that!

**Comment by kcpevey** [comment]
Unfortunately this suffers from the same issues the last ci PR had - The workflow I'm modifying here is being pulled from the main branch, not this branch. https://github.com/napari/napari/actions/runs/3285994186/workflow

The failures from the Qt benchmark workflow seem to be coming from a couple of timeouts and from this
```
[100.00%] · Running '/usr/local/bin/git name-rev --name-only --exclude=remotes/* --no-undefined 5080ab0685ff446ce938615dcbddc2154ea704f0'
            OUTPUT -------->
            fatal: cannot describe '5080ab0685ff446ce938615dcbddc2154ea704f0'
[100.00%] · Running '/usr/local/bin/git name-rev --name-only --exclude=remotes/* --no-undefined a858ef3ab7e8b5676e9f0193fe9556cb6ed15ea9'
            OUTPUT -------->
            fatal: cannot describe 'a858ef3ab7e8b5676e9f0193fe9556cb6ed15ea9'
```

At any rate, the benchmark failures here are not related to this PR.

**Comment by kcpevey** [comment]
Just a brief mention of what seems to be a separate issue - The benchmark timeout is being set at 300s [here](https://github.com/napari/napari/blob/main/.github/workflows/benchmarks.yml#L28-L32) and [here](https://github.com/napari/napari/blob/main/.github/workflows/benchmarks.yml#L119) but it doesn't seem like that's being honored ([see timeout at 60s here](https://github.com/napari/napari/actions/runs/3284717461/jobs/5411003957#step:7:3004)).

**Comment by jaimergp** [comment]
```
Running '/Users/runner/work/napari/napari/.asv/env/63b4d1e2919fcd950c89910ea84c38ee/bin/python /Users/runner/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/asv/benchmark.py run /Users/runner/work/napari/napari/napari/benchmarks benchmark_qt_slicing.QtViewerAsyncPointsAndImage2DSuite.time_z_scroll-26 {"timeout": 300.0} None /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpf6x8wp8h'
```

Is that the right syntax we should see? The dict-like string. Or is it just the way it's reported on stdout? Might be worth taking a look at that.

**Comment by kcpevey** [comment]
@andy-sweet  To clarify, this is a reversion to fix something I introduced when working with the benchmarks recently. This is the original PR that this is returning to https://github.com/napari/napari/pull/4554.

**Comment by kcpevey** [comment]
>Unfortunately this suffers from the same issues the last ci PR had - The workflow I'm modifying here is being pulled from the main branch, not this branch. https://github.com/napari/napari/actions/runs/3285994186/workflow

@andy-sweet just realized why this is the case. The `Benchmark - Report` workflow is triggered by the `Benchmark` workflow. For whatever reason, that causes it to run outside the scope of this PR (i.e. you won't see it in the list of Actions for this PR, you'll have to look for it under actions for the repo). 

We are carrying along all the metadata for this PR so I'm sure its possible to force it to checkout the branch associated with the PR. Not sure its worth the effort though as this is a rare issue.

**Review by andy-sweet — APPROVED** [review]
Thanks for pointing to the PR this reverts to. Will merge this after 24 hours unless anyone objects.

**Pull request merged**
