### PR TITLE
Allow LayerList to be initialized by passing in a list of layers

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
# Description

## 🚀 Feature

This PR alllows you to initialize a `LayerList` by passing in a list of layers. 

## Motivation
Currently the LayerList class in `napari/components/layerlist.py` doesn't allow you to initialize it by passing in a list of layers. It would be convenient to be able to do this, instead of having to append multiple times for very long lists. 

```python
from napari.components.layerlist import LayerList
from napari.layers.image import Image
from skimage import data
```

Currently you need to do this to create a layerlist with image layers in it:
```python
my_layerlist = LayerList()
my_layerlist.append(Image(data.camera()))
my_layerlist.append(Image(data.astronaut()))
```

But with this PR, we can make that a one-line call:
```python
my_layerlist = LayerList([Image(data.camera()), Image(data.astronaut())])
```

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update. The docstring for LayerList has been updated.

# References

# How has this been tested?

- [x] added a new test checking you can initialize LayerLIst with a list of layers
- [x] all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
This seems like a reasonable addition @GenevieveBuckley - but I am curious where you are encountering this in practice.

Are there places within the repo that we could use the new syntax to cutdown on code? Do you find yourself instantiating `Layers` and a `LayerList` like this when you are using napari? I only ever create a Viewer and use `add_*` methods so curious to learn more about your usage practices

**Comment by GenevieveBuckley** [comment]
> This seems like a reasonable addition @GenevieveBuckley - but I am curious where you are encountering this in practice.
> 
> Are there places within the repo that we could use the new syntax to cutdown on code? Do you find yourself instantiating `Layers` and a `LayerList` like this when you are using napari? I only ever create a Viewer and use `add_*` methods so curious to learn more about your usage practices

I think this is only really useful to have while debugging or coding new features, I don't see this happening much in general use of napari from an end-user. 

I was debugging something else at the time (for https://github.com/napari/napari/pull/885, although the context here doesn't really matter).

**Comment by sofroniewn** [comment]
> I think this is only really useful to have while debugging or coding new features, I don't see this happening much in general use of napari from an end-user.

Ok fair enough. Curious how @jni feels about this.

**Comment by jni** [comment]
> Curious how @jni feels about this.

I suggested the PR! :joy: @GenevieveBuckley and I were working on TransformChains and we were trying out/debugging our use of the ListModel indexing magic that @kne42 made, and we were pretty surprised that LayerList could not be instantiated from a list of layers. Even if we see little use for it right now, I think it's worthwhile to avoid surprising behavior in our classes.

**Comment by tlambert03** [comment]
I like!  Seems like a very logical thing to be able to do :)

**Review by sofroniewn — APPROVED** [review]
Great that everyone is supportive. I will approve now, but will wait if @kne42 wants to weigh in before merge. Thanks @GenevieveBuckley!

**Pull request merged**
