### PR TITLE
[WIP] Fix memory leaks

### LINKED ISSUE #2027: Memory keeps increasing as we viewer.layers.pop(0) and viewer.add_image()
## 🐛 Bug
I am using napari (thanks for this great tool!) to browse a large folder of images and using callback functions to move files to different folders.

For instance, the callback for the `space` key is as follow:

```python
    @viewer.bind_key("Space")
    def space_callback(viewer):
        global i, all_files
        viewer.layers.pop(0)
        shutil.move(all_files[i], os.path.join(FOLDER, os.path.basename(all_files[i])))
        all_files.pop(i)
        i = i % len(all_files)
        img = imread(all_files[i])
        viewer.add_image(img, name=str(i))
```

The issue is that the memory usage keeps increasing, while I would expect it to be constant since, in theory, I always only have one image in memory at the same time.

I thought `viewer.layers.pop(0)` would release memory but this is not the case.

### PR DESCRIPTION
**Pull request by tlambert03**
# Description
Following on the discussion and tests run in #2027, this PR hopes to plug a memory leak caused both by the vispy and qt objects hanging on to the layer object, and by the series of `ImageSlice`, `ImageSlideData`, `ImageView` objects through which the data travels while rendering.  The memory leak is fixed in this PR, but the rendering is broken... so this is just a marker of the places that need to patched up for now.

fixes #2027

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sofroniewn** [comment]
Thanks for getting this going! I'm happy to help pitch in with this too. I tried pulling the PR and running `p.py`, but I'm still getting a memory leak (the rendering is broken too, but that was expected).

```
Mem used after  68 layers: 881.84 (MB)
r is  d d is  <class 'numpy.ndarray'>
Mem used after  69 layers: 891.17 (MB)
r is  d d is  <class 'numpy.ndarray'>
Mem used after  70 layers: 900.63 (MB)
r is  d d is  <class 'numpy.ndarray'>
Mem used after  71 layers: 910.03 (MB)
r is  d d is  <class 'numpy.ndarray'>
Mem used after  72 layers: 919.46 (MB)
```

If I run your code from https://github.com/napari/napari/issues/2027#issuecomment-766182182

I get 
```
(base) czirwc1macos2701:image-demos nsofroniew$ python test-examples/memory_leak_gc.py
0 unreachable objects after collection
referenced layer is: <Points layer 'Points' at 0x7fe6ec8cc5d0>

1 remaining references:
0 {'layer': <Points layer 'Points' at 0x7fe6ec8cc5d0>, 'layout': <PyQt5.QtWidgets.QHBoxLayout object at 0x7fe6ed9abeb0>, 'thumbnailLabel': <PyQt5.QtWidgets.QLabel object at 0x7fe6ed9abd70>, 'visibleCheckBox': <PyQt5.QtWidgets.QCheckBox object at 0x7fe6ed9abcd0>, 'nameTextBox': <PyQt5.QtWidgets.QLineEdit object at 0x7fe6ed9abe10>, 'typeLabel': <PyQt5.QtWidgets.QLabel object at 0x7fe6ed9abb90>}
```

Is the culprit here the `ImageSliceData` you think? If I remove the `ImageView` weakref changes they don't change anything - still 1 remaing reference and a memory leak, so I'm wondering if somehow that fix isn't even enough for me?

As said above, I'm happy to dive in more, I just want to make sure I'm starting from the same place as you!

**Comment by tlambert03** [comment]
awesome thanks!  

>I'm still getting a memory leak

hmm... perhaps I changed something before pushing.  Will check shortly. 

> Is the culprit here the ImageSliceData you think? If I remove the ImageView weakref changes they don't change anything - still 1 remaing reference and a memory leak, so I'm wondering if somehow that fix isn't even enough for me?

The way I actually determined that was to start at `_set_view_slice`, while running `t.py`, and I just fully commented out the last line in that function:

https://github.com/tlambert03/napari/blob/0bab85fae2df3b200f3f1a0ac54dfc1d4b5384c7/napari/layers/image/image.py#L615-L616

that fixed it, so I started following the chain down, commenting things out to see how far I could go.   I bet if you go back to set_view_slice and comment that out it will work, and you can start going through the chain like that

**Comment by goanpeca** [comment]
Hi @tlambert03. Is this PR still relevant, or could we close it?

**Comment by tlambert03** [comment]
Very relevant. Still difficult

**Comment by tlambert03** [comment]
gonna close this.  I think that #3217 covered at least some of what this was aiming to do.  Refer back to the scripts in https://github.com/napari/napari/issues/2027 and the following to scripts for testing tools:

```py
import gc
import sys
import weakref

import numpy as np

import napari

viewer = napari.viewer.Viewer()
lr = weakref.ref(viewer.add_image(np.random.rand(512, 512)))
dr = weakref.ref(lr().data)

viewer.layers.pop()
print(gc.collect(), "unreachable objects after collection")
print(gc.collect(), "unreachable objects after collection")
print("l is ", lr(), "d is ", dr())

if lr():
    print(f"\n{sys.getrefcount(lr()) - 1} remaining references to {lr()}")
if dr() is not None:
    print(
        f"\n{sys.getrefcount(dr()) - 1} remaining references to {type(dr())}"
    )
    print(gc.get_referrers(dr()))
```

```py
import gc
import os
import weakref

import numpy as np
import psutil

import napari

v = napari.Viewer()


def get_process_memory():
    return psutil.Process(os.getpid()).memory_info().rss / 1e6


for i in range(1000):
    d = np.random.rand(1024, 1024)
    r = weakref.ref(v.add_image(d))
    dr = weakref.ref(d)
    del d
    v.layers.pop(0)
    gc.collect()
    print("r is ", r(), "d is ", type(dr()))
    print(f"Mem used after {i:3} layers: {get_process_memory():0.2f} (MB)")
```

**Pull request closed without merging**
