### PR TITLE
Change pytest-xvfb to explicit xvfb run

### PR DESCRIPTION
**Pull request by Czaki**
# Description

To remove x11 errors which cause fail negative test results.

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
seems to have solved the IO problem!

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Comment by sofroniewn** [comment]
Will merge this tomorrow unless I hear otherwise, thanks!!

**Comment by Czaki** [comment]
I would prefer to check if merging #3127 solves current CI failures.

**Comment by tlambert03** [comment]
@Czaki, I just merged #3127

**Comment by Czaki** [comment]
I have no idea how to deal with this:

```
  [xcb] Unknown request in queue while appending request
  [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
  [xcb] Aborting, sorry about that.
  python: ../../src/xcb_io.c:151: append_pending_request: Assertion `!xcb_xlib_unknown_req_pending' failed.
  Fatal Python error: Aborted
```

**Comment by tlambert03** [comment]
> [xcb] Aborting, sorry about that.

😂

**Comment by Czaki** [comment]
I do not have any idea what happens, but I got segfault when running locally with tox.
Here is stack trace:

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff2c6a63f in _XSend () from /lib/x86_64-linux-gnu/libX11.so.6
(gdb) bt
#0  0x00007ffff2c6a63f in _XSend () from /lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007ffff2c61c4a in XQueryExtension () from /lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff2c55b57 in XInitExtension () from /lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007fff73eda511 in XextAddDisplay () from /lib/x86_64-linux-gnu/libXext.so.6
#4  0x00007fffeb6be97b in ?? () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#5  0x00007fffeb6ae941 in glXDestroyContext () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#6  0x00007fffeb9b3c41 in QGLXContext::~QGLXContext() () from /tmp/.tox/py38-linux-pyqt/lib/python3.8/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
#7  0x00007fffeb9b3c69 in QGLXContext::~QGLXContext() () from /tmp/.tox/py38-linux-pyqt/lib/python3.8/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
#8  0x00007fffb0f947eb in QOpenGLContext::destroy() () from /tmp/.tox/py38-linux-pyqt/lib/python3.8/site-packages/PyQt5/Qt5/lib/libQt5Gui.so.5
#9  0x00007fffb0f94ac7 in QOpenGLContext::~QOpenGLContext() () from /tmp/.tox/py38-linux-pyqt/lib/python3.8/site-packages/PyQt5/Qt5/lib/libQt5Gui.so.5
#10 0x00007fffb18b17dd in sipQOpenGLContext::~sipQOpenGLContext() () from /tmp/.tox/py38-linux-pyqt/lib/python3.8/site-packages/PyQt5/QtGui.abi3.so
#11 0x00007fffb491f465 in cleanup_qobject(_sipSimpleWrapper*, void*) () from /tmp/.tox/py38-linux-pyqt/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#12 0x00007fffb1aff5d9 in sip_api_visit_wrappers (visitor=0x7fffb491f3a0 <cleanup_qobject(_sipSimpleWrapper*, void*)>, closure=0x5556c32edbd0) at siplib.c:13280
#13 0x00007fffb491f0f0 in cleanup_on_exit(_object*, _object*) () from /tmp/.tox/py38-linux-pyqt/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#14 0x00007ffff7d1bc2a in cfunction_vectorcall_NOARGS (func=func@entry=0x7fffb4a27860, args=<optimized out>, nargsf=nargsf@entry=0, kwnames=<optimized out>) at Objects/methodobject.c:459
#15 0x00007ffff7cd7013 in PyVectorcall_Call (callable=0x7fffb4a27860, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:199
#16 0x00007ffff7e59527 in atexit_callfuncs (module=<optimized out>) at ./Modules/atexitmodule.c:87
#17 0x00007ffff7df1b2d in call_py_exitfuncs (istate=0x55555555cc10) at Python/pylifecycle.c:2236
#18 Py_FinalizeEx () at Python/pylifecycle.c:1183
#19 Py_FinalizeEx () at Python/pylifecycle.c:1154
#20 0x00007ffff7e16d35 in Py_RunMain () at Modules/main.c:646
#21 0x00007ffff7e1748a in pymain_main (args=0x7fffffffe6a0) at Modules/main.c:674
#22 Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:698
--Type <RET> for more, q to quit, c to continue without paging--
#23 0x00007ffff7a59565 in __libc_start_main (main=0x555555555060 <main>, argc=9, argv=0x7fffffffe808, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe7f8) at ../csu/libc-start.c:332
#24 0x000055555555509e in _start ()

```

So it looks like there is a problem with some OpenGL Widget destroy. Did you have any idea which PR lately plays with such objects?

**Review by goanpeca — APPROVED** [review]

**Comment by sofroniewn** [comment]
Do we have a sense if we still want to go with this approach? Do you think it might help #3034 which has quite a lot of test fails that are hard to pin down?

**Pull request closed without merging**
