### PR TITLE
Coerce vector length type

### LINKED ISSUE #1801: If a list of length one is passed to add_vectors as length, strange things happen
## 🐛 Bug

Passing something like `[1]` as length to `viewer.add_vectors()` leads to random windows opening.

## To Reproduce

```
viewer.add_vectors(np.random.rand(1,2,3), length=[1])
```
we get a reasonable error:
```
TypeError: setValue(self, float): argument 1 has unexpected type 'list'
```
but at the same time, these 2 windows open:
image

Other non-number values give a range of errors that are hard to interpret, making it hard to debug in case something other than a number ended up there. For example:
```
UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
```
to an unexperienced user like me would not suggest that `length` was a string.

## Expected behavior

No windows should open. Type checking should give more informative error messages.

## Environment

```
napari: 0.4.0
Platform: Linux-5.9.1-arch1-1-x86_64-with-glibc2.2.5
Python: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
Qt: 5.15.1
PyQt5: 5.15.1
NumPy: 1.19.2
SciPy: 1.5.3
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.6 (Compatibility Profile) Mesa 20.2.1
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```

### LINKED ISSUE #2347: Vector layer scaling inconsistencies
## 🐛 Bug

When trying to use the `scale` parameter of vector layers, I encountered some issues. Type errors are raised unexpectedly, and arrays are reshaped strangely.

However, I can create a layer and *then* set its scale to have the expected behaviour.

EDIT: actually, it seems that using a single float is not accepted either way.

## To Reproduce

This works as intended:
```python
import napari
import numpy as np

v = napari.Viewer(ndisplay=3)
l = v.add_vectors(np.random.rand(10, 2, 3) * 100)
l.scale = [1, 2, 1]
```

However, this raises an error:
```python
l = v.add_vectors(np.random.rand(10, 2, 3) * 100, scale=[1, 2, 1])
.....
~/.local/lib/python3.9/site-packages/napari/utils/transforms/transforms.py in __call__(self, coords)
    347         if coords.shape[1] != self.linear_matrix.shape[0]:
    348             linear_matrix = np.eye(coords.shape[1])
--> 349             linear_matrix[
    350                 -self.linear_matrix.shape[0] :, -self.linear_matrix.shape[1] :
    351             ] = self.linear_matrix

ValueError: could not broadcast input array from shape (4,4) into shape (3,3)
```

The docs say that `scale` accepts a single float, but that fails as well with:
```python
TypeError: object of type 'int' has no len()
```

## Expected behavior

Same as setting `scale` posthumously.

## Environment

```yaml
napari: 0.4.6
Platform: Linux-5.11.2-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.1
SciPy: 1.6.1
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.56
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- ndtiffs: 0.1.1
- svg: 0.1.4
```

### PR DESCRIPTION
**Pull request by brisvag**
# Description
Super tiny change that should fix one of my oldest forgotten issues, #1801 :)

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References
closes #1801

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Review by nclack — APPROVED** [review]
lgtm!

**Review by sofroniewn — APPROVED** [review]
LGTM!

**Comment by sofroniewn** [comment]
@brisvag can you add a test for this one before merge - can be super simple, maybe based on #1801 thanks!!

**Comment by brisvag** [comment]
I'm actually not sure how to test for this. Both before and after this change, the result is a `TypeError`. The only difference is where this is raised, which before the change leaves in an inconsistent state (i.e: it opens some windows other nonsense). How can I check where the error actually happens, if that's even the right approach?

**Comment by sofroniewn** [comment]
Hmm, ok - maybe fine without a test. @jni any thoughts here? Otherwise we can just merge

**Pull request merged**
