### PR TITLE
[Maint] Update docs constraints for new napari-sphinx-theme release

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description
Updates constraints file for new napari-sphinx-theme release.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@napari-bot update constraints

**Comment by psobolewskiPhD** [comment]
@jni everything passes now. But if you want I can go undo the non-docs related pins manually or something..

**Comment by jni** [comment]
> But if you want I can go undo the non-docs related pins manually or something..

what does this mean??

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
Oh, I know what you mean. Nah, if they're working it's good to have them up to date

**Pull request merged**
