### PR TITLE
MAINT: Remove QtStateButton, marked for removal in 0.4.14

### PR DESCRIPTION
**Pull request by Carreau**
Extracted from #4756

### CODE REVIEW

**Comment by Carreau** [comment]
Failure on ubuntu-latest 3.9 pyside6 likely due to #5069 (new version of shiboken)

**Comment by Czaki** [comment]
Please postpone it 0.5.0. I use it in PartSeg and need to rewrite it.

**Comment by Carreau** [comment]
> Please postpone it 0.5.0. I use it in PartSeg and need to rewrite it.

Converting to draft to avoid accidental merge then.

**Comment by Carreau** [comment]
As 0.4.17 was released, marking as ready, and rebased.

**Review by brisvag — APPROVED** [review]

**Pull request merged**
