### PR TITLE
Add show_debug notification

### PR DESCRIPTION
**Pull request by seankmartin**
# Description
This PR is to add a `show_debug` notification function, to round out the existing functionality to show info, warning, and error.
I've been looking into plugin debugging in relation to #2948. I noticed that there was no `show_debug` function, which I thought might be a nice way to help debugging as the console log level preferences in napari can be set to `info` level to hide these.
Open to thoughts though if there is a reason it would be preferred not to have this function! I could use an alternative if so, outside of core, something like:

```Python
import napari
def alt_show_debug(message: str):
    napari.utils.notifications.notification_manager.dispatch(
        napari.utils.notifications.Notification(
            message, severity=napari.utils.notifications.NotificationSeverity.DEBUG
        )
    )
````

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# References
Related to #2948 as I noticed it during writing this guide.

# How has this been tested?

- The test suite for my feature follows the structure for the existing `show_x` notification functionality

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by kcpevey** [comment]
Thanks @seankmartin for this PR! 

I'm adding @brisvag or @Czaki as reviewers since it seems this went overlooked. If there is someone else who would be better to review, feel free to swap!

**Comment by brisvag** [comment]
Good, seems pretty straightforward to me. I'm not sure I understand how to enable/disable this when actually using napari. Is the default loglevel `WARN`?

**Comment by seankmartin** [comment]
As I understand it (please correct me if wrong!)

There are two default log levels set here https://github.com/napari/napari/blob/ee94c35c04674ddc8e89ed63ac7674c27fa8fc6c/napari/settings/_application.py#L104-L115
1. `gui_notification_level` - by default `info`.
2. `console_notification_level` - by default `none` (so it prints every log message).

By default `show_debug(msg)` would print to console, but not show it in the GUI message popup box in the bottom right of the viewer.

To change the level in napari and see the `show_debug` output, you can directly set it
```
settings = napari.get_settings()
settings.application.console_notification_level = "debug"
settings.application.gui_notification_level = "debug"
```

Or if using the GUI, you can set it in Preferences -> Application -> GUI notification level / Console notification level.

**Review by brisvag — APPROVED** [review]
Great, thanks for the rundown! Seems useful to me :)

**Review by Czaki — APPROVED** [review]

**Pull request merged**
