### PR TITLE
Move Qt view menu actions inside Qt folder

### PR DESCRIPTION
**Pull request by lucyleeow**
# References and relevant issues
Noticed when working on #6743

# Description
The current 'non-qt' actions defined in: `napari/_app_model/actions/_view_actions.py` actually only make sense with a GUI viewer (visibility of axes etc). I have moved these inside: `napari/_qt/_qapp_model/qactions/_view.py` with the other Qt view actions.

Note I have kept `ViewerToggleAction` where it is as it is general enough that it *could* be used with a non-qt viewer, but happy to move if requested.

### CODE REVIEW

**Comment by lucyleeow** [comment]
cc @DragaDoncila

**Comment by DragaDoncila** [comment]
@lucyleeow definitely agree with moving these actions. Let's also move the `ViewerToggleAction` imo. I don't see the benefit of keeping it separate from its usage until and unless we actually run into a need for it.

**Comment by Czaki** [comment]
@lucyleeow It looks like dropping python 3.8 introduces conflicts

**Comment by lucyleeow** [comment]
Thanks @Czaki, fixed. Are you interested in reviewing?

**Comment by lucyleeow** [comment]
CI error due to timeout and I don't think related.

**Review by DragaDoncila — APPROVED** [review]
Looks good to me! I really do think these actions don't make sense without qt. Pulled it down and played with it too.

**Review by jni — APPROVED** [review]
I was just chatting with @DragaDoncila and I am fine with this but I wanted to flag that even though these things don't make sense without Qt *now*, I think in the future they would make sense regardless:
- when using a different UI such as a web-UI
- when using a virtual UI to compose an image/animation which then gets rendered off-screen and saved as an image

@DragaDoncila points out that at that point we can take ~all of the Qt menu actions and move them in some intermediate "on-canvas" actions to distinguish from model-only actions.

**Comment by lucyleeow** [comment]
Agreed. I there are things in the qt folder are just UI specific, not necessarily Qt specific. We don't have a UI but backend agnostic folder atm.

**Pull request merged**
